### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/legacy-assets-issue-tracker#10]
**Name:**
 Cricketx818

**Summary:**
I think most cars should have a cap @ 120 unless you upgrade them, people like Me spent over 20k upgrading a car and its very very slow now, Example : Benelaction Shafter (Sedan)
I bought the car for 28k and spent over 20k in upgrades and it does not pass 105MPH

Super cars should not have a cap on them at all, because people pay over 100K+ and spend over 50 hours playing on the server and they find out its capped thats pretty upsetting, Let me know what you think.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Alot of people are upset

**Comment by Karpenkooo** [comment]
Hey @Cricketx818 

There was a bug that caused the Vanilla Cars to reset to old speeds. This has however been fixed and should come out in the next Update. If the issue still continues after the next update then please ask for this issue to be re opended.

_Karpenko_

_**OP-FW Car Developer**_
