### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Chizz3** [InZidiuZ/legacy-assets-issue-tracker#100]
**Reporter:**
Who is reporting this? Please include discord name.
Chizee Wang
**Summary:**
Write a summary of what you're experiencing.
Cannot take out Assault Smg weapons
## Additional Information
![image](https://user-images.githubusercontent.com/53583215/68002991-810da000-fc39-11e9-9bef-0b6d36d8a82c.png)

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.
doesent show up when you press tab and or on your back

**Comment by iGreatWhite** [comment]
Wrong place to report this and it’s already on the framework tracker.
