### ISSUE TITLE
Cars the community wants

### ISSUE THREAD

**Issue by Seferti** [InZidiuZ/legacy-assets-issue-tracker#101]
**Name:**
seferti#4952

**Summary:**
So i got together with a few people and we came up with a list of 15 cars that are a wide variety of cars that we feel would be a good fit for Legacy Roleplay. I will provide a list of each car with it's name and a link to the download to make it easier for you.

**Link:**
https://www.gta5-mods.com/vehicles/2019-bmw-x5-g05-add-on - 2019 BMW X5
https://www.gta5-mods.com/vehicles/2020-ford-f-350-king-ranch-dually-godzgift - 2020 Ford F-350 King Ranch Dually
https://www.gta5-mods.com/vehicles/infiniti-q60-2017 - 2017 Infiniti Q60
https://www.gta5-mods.com/vehicles/2017-bentley-bentayga-startech-add-on-tuning-analog-digital-dials - 2017 Bentley Bentayga StarTech
https://www.gta5-mods.com/vehicles/range-rover-vogue-startech-add-on-tuning - Range Rover Vogue Startech
https://www.gta5-mods.com/vehicles/toyota-camry-xse-2018-replce-add-on - 2018 Toyota Camry XSE
https://www.gta5-mods.com/vehicles/ford-focus-rs-2017-add-on-replace-tuning-template-multi-livery - 2017 Ford Focus RS
https://www.gta5-mods.com/vehicles/honda-civic-type-r-ek9 - 1997 Honda Civic Type-R
https://www.gta5-mods.com/vehicles/2015-honda-civic-type-r-fk2-add-on-rhd - 2015 Honda Civic Type-R
https://www.gta5-mods.com/vehicles/cambered-nissan-silvia-s14-kouki-tuning-add-on - Nissan Silvia S14 Kouki
https://www.gta5-mods.com/vehicles/chevrolet-camaro-z28-70-add-on - 1970 Camaro Z28
https://www.gta5-mods.com/vehicles/1970-dodge-challenger-rt-440-six-pack-addon-version - 1970 Dodge Challenger RT
https://www.gta5-mods.com/vehicles/2016-cadillac-cts-v - 2016 Cadillac CTS-V
https://www.gta5-mods.com/vehicles/yamaha-yzf-r6-2017 - 2016 Yamaha YZF R6
https://www.gta5-mods.com/vehicles/harley-davidson-knucklehead - Harley Davidson Knucklehead

**Reason:**
Well we feel like with this selection of cars you can go through and choose the ones you feel like would fit best within the community. Like i said we have included cars from multiple years as well as many different types of cars.

**Comment by TwoplePop** [comment]
1992 Nsx| Tuning Add-On 
https://www.gta5-mods.com/vehicles/honda-nsx-r-na1-1992

**Comment by TwoplePop** [comment]
unfortunately, I don't think half of these cars have tuning

**Comment by TwoplePop** [comment]
r32 rb: https://www.gta5-mods.com/vehicles/nissan-skyline-gt-r-r32-rocket-bunny-tuning-template

**Comment by Seferti** [comment]
> unfortunately, I don't think half of these cars have tuning

explain what you mean by tuning?

**Comment by LilMags** [comment]
I like the list, maybe add the 90's NSX and a classic Fairlady Z

**Comment by LilMags** [comment]
NSX - https://www.gta5-mods.com/vehicles/honda-nsx

**Comment by LilMags** [comment]
FairLady Z- https://www.gta5-mods.com/vehicles/nissan-fairlady-z-s30-addon-rhd-devil-z

**Comment by Lunar929292** [comment]
https://www.gta5-mods.com/vehicles/2015-dodge-ram-2500-add-on-tuning

**Comment by Lunar929292** [comment]
https://www.gta5-mods.com/vehicles/mazda-rx7-veilside-fortune
https://www.gta5-mods.com/vehicles/nissan-skyline-gt-r-r32-rocket-bunny-tuning-template
https://www.gta5-mods.com/vehicles/1987-ferrari-f40-add-on-replace-tuning

**Comment by Karpenkooo** [comment]
Hey guys!

Thanks for all the car suggestions. The third pack is almost finished now and quite a few of these cars have made it into the third pack! 

I'm going to close this bug however feel free to send in more suggestions in the comments. 

_**Karpenko - OP FW Assets Developer**_
