### ISSUE TITLE
Suggestion of a 64 slot server

### ISSUE THREAD

**Issue by EVILKTM** [InZidiuZ/legacy-assets-issue-tracker#102]
KTM#0661
Who is suggesting this? Please include discord name.

Write a short summary of what your suggestion is about.
My summary is about the 3 servers we do what I would like to see is that we just have one server and make the one server a 64 or a 55 slot server

Why would your suggestion be a good addition to Legacy?
I think this would be a good addition to legacy rp because we wouldn’t have to switch servers to meet our friends and we since we have more people in one server we can have way more rp. Over all I think it would be better for legacy and it would stop people from going on dead servers that there is no one on the server and doing stuff like the gun heist and selling coke so they don’t get robbed or having cops mess with them

**Comment by iGreatWhite** [comment]
Wrong tracker.

**Comment by InZidiuZ** [comment]
*sigh* This doesn't even fit into the other issue tracker... The plan is to move to OneSync eventually.

**Comment by Miliax** [comment]
Hell no, i Love how it is right now! We had a 55 slot before, almost no one used it!
