### ISSUE TITLE
Bug report(Items disappearing from house)

### ISSUE THREAD

**Issue by Chizz3** [InZidiuZ/legacy-assets-issue-tracker#103]
**Reporter:**
Who is reporting this? Please include discord name.
chizz#1800
**Summary:**
Write a summary of what you're experiencing.
Almost all of my stuff in my house has disappeared- I had a Assault SMG-Micro Smg-4x green decryption keys-2 red decryption keys-3 blue decryption keys-2 handcuffs-6 bolt cutters-16 normal lockpicks-3 "chips"-6 thermite and 6 drills
## Additional Information
I had it all last night but now I do not
**Screenshots:**
If suitable, include some screenshots.
![image](https://user-images.githubusercontent.com/53583215/68074234-bf54ad80-fd66-11e9-9e83-81d6e90830a7.png)

![image](https://user-images.githubusercontent.com/53583215/68074237-cb406f80-fd66-11e9-9ab7-e35aba0dac3a.png)

![image](https://user-images.githubusercontent.com/53583215/68074239-e01d0300-fd66-11e9-9013-d1b418bdf586.png)

https://plays.tv/video/5dbe00574ccad25344/this-is-the-glitch-ive-lost-so-much
**Notes:**
For anything else noteworthy. None of my other stuff is there

**Comment by Chizz3** [comment]
#
![image](https://user-images.githubusercontent.com/53583215/68074321-ba442e00-fd67-11e9-9472-03ef48ce6899.png)

None of the wight shows up either so it clearly scuffed- there is not number/2000 .00 pounds you know

**Comment by InZidiuZ** [comment]
Wrong issue tracker. This most likely was related to an issue with the Assault SMG, which has since been fixed.
