### ISSUE TITLE
Bug report(more things despawning form houses)

### ISSUE THREAD

**Issue by Chizz3** [InZidiuZ/legacy-assets-issue-tracker#104]
**Reporter:**
Who is reporting this? Please include discord name.
chizz#1800
**Summary:**
Write a summary of what you're experiencing.
my stuff just keeps disappearing 
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://plays.tv/video/5dbe00574ccad25344/this-is-the-glitch-ive-lost-so-much
**Notes:**
For anything else noteworthy.

**Comment by triatomic** [comment]
have you tried getting outside the house ingame then going in or logging out ?

**Comment by InZidiuZ** [comment]
Wrong issue tracker. This most likely was related to an issue with the Assault SMG, which has since been fixed.
