### ISSUE TITLE
Mazda RX7 Bug

### ISSUE THREAD

**Issue by DopePixel** [InZidiuZ/legacy-assets-issue-tracker#105]
**Reporter:**
Snow#9481

**Summary:**
I bought a Mazda RX7 from the exclusive dealership a few months ago ended up getting banned for combat logging I got unbanned and now when I go to customize my RX7 I cant put any new bumpers hoods or rear bumpers on it just says stock in the tab.  Another thing is I take the livery off the car put it in the garage pull it back out and its still there. But I can upgrade the default things like engine and stuff like that.  And I did buy my donator rank back if that would interfere with anything.

## Additional Information

**Screenshots:**
![image](https://user-images.githubusercontent.com/57329053/68091082-6873d480-fe49-11e9-9e6b-0f9c5d6d8940.png)

![image](https://user-images.githubusercontent.com/57329053/68091095-79244a80-fe49-11e9-9577-255d8e4e7fbd.png)

![image](https://user-images.githubusercontent.com/57329053/68091102-8e997480-fe49-11e9-8e00-be7b4c8861a2.png)

**Notes:**

**Comment by Karpenkooo** [comment]
Hey,
This issue should be fixed with the new LS Customs however if not I will just remove all of the liveries for that vehicle. 

_**Karpenko - OP FW Assets Developer**_

**Comment by Skihop** [comment]
where can i find the ls custom script?
