### ISSUE TITLE
Pegassi Bati 801 RR

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/legacy-assets-issue-tracker#106]
**Reporter:**
Randy James#4851

**Summary:**
I am experiencing that the bike cant change colour. Primary or Secondary. It stays red and white.

## Additional Information

**Screenshots:**
[![Screenshot from Gyazo](https://gyazo.com/52b22f95535e7449ea6c70cd190673f8/raw)](https://gyazo.com/52b22f95535e7449ea6c70cd190673f8)

**Notes:**
For anything else noteworthy.

**Comment by Djmeowzle** [comment]
The Bati 801 RR is a livery only bike, if you want to change colors, either exchange it for a regular Bati 801, there's no performance difference, only style options :)

**Comment by TwoplePop** [comment]
it's bc it has that livery on. in regular GTA, you weren't able to change the color of the bati 801 rr , it was only the bati 801 that you could change

**Comment by Aesfy** [comment]
Ah okay, stuck with the bike then I guess. Cant sell the thing even I lose money on it.
