### ISSUE TITLE
Weed Growing/ Cost

### ISSUE THREAD

**Issue by IdkToDoo** [InZidiuZ/legacy-assets-issue-tracker#109]
Reporter: 
     IdkToDoo#3142 

 Summary: This is a suggestion to possibly stabilize weed growing. Weed growing, in my opinion, is not balanced we have $100 fertilizer and it takes 5 fertilizer for 1 plant so if I wanted to grow 10 weed plants I would have to spend around $5300 just in fertilizer. Yeah, you might make 1 or 2k profit but waiting hours for 1 plant to grow it just isn't balanced. My goal with this suggestion is to make 1 fertilizer pack for 100% of the growing or near there. Just to make weed growing not expensive as shit. 
    
     11/08/2019

**Comment by InZidiuZ** [comment]
Wrong issue tracker.
