### ISSUE TITLE
Modded Motorcycles

### ISSUE THREAD

**Issue by Scrubject** [InZidiuZ/legacy-assets-issue-tracker#11]
**Name:**
Scrubject#1646

**Summary:**
Being in an MC, I really wish there was more variety on the server. I'd like to propose these two Modded Bikes to be added to the server.

**Link:**
Kawasaki Eliminator
https://www.gta5-mods.com/vehicles/kawasaki-eliminator400se

Harley Davidson XLCR
https://www.gta5-mods.com/vehicles/harley-davidson-xlcr-add-on

**Reason:**
I can say that my club Men of Mayhem would appreciate some more variety to the bikes available on the server, and I assume the same could be said for the Lost MC.

**Comment by Karpenkooo** [comment]
Hey @Scrubject ,

Thank You for suggesting these motorbikes. I'm already working on a "Custom Bike" pack. I'll need to make sure that these bikes are optimized and bug free. If that is the case then i'll consider adding these to the pack. 

_Karpenko_

**_OP-FW Vehicle Developer_**
