### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KidDano** [InZidiuZ/legacy-assets-issue-tracker#111]
**Reporter:**
Who is reporting this? Please include discord name.
Dano#5666
**Summary:**
Write a summary of what you're experiencing.
hey boss just reporting another issue on the best server right now the latam the account tab on the /comp is not working properly you have to click on other tabs and go back to the account one so it can show and if you deposit money it will only take it but not put it in your account and there for we can't pay our rents. 
## Additional Information
just hmu on disc if you need any more info 
**Screenshots:**
If suitable, include some screenshots.
if you want screen shots just let me know i dont know how to upload them so i will just dm you  
**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

This is, unfortunately, is the wrong issue tracker. Sorry for taking 9 years to reply :) Please re-write this in the Framework tracker. Thanks
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

**_Karpenko - OP FW Assets Developer_**
