### ISSUE TITLE
 Face Expressions and more Emotes.

### ISSUE THREAD

**Issue by HP714** [InZidiuZ/legacy-assets-issue-tracker#112]
**Name:**
  HP#9403

**Summary:**
u can add Face Expressions and many other emotes 

**Link:** here are 
https://cdn.discordapp.com/attachments/628567735235903490/643475707204468736/20191111191956_1.jpg  
https://cdn.discordapp.com/attachments/628567735235903490/643475705249923072/20191111192006_1.jpg 
https://cdn.discordapp.com/attachments/628567735235903490/643475708227747850/20191111192340_1.jpg

**Reason:** RolePlaying  will be more fun and interesting  and more realistic with Face Expression and other Emotes.

**Comment by AdeptCL** [comment]
I don't think facial expressions are useful personally.

I would like to see some new emotes though. It's just finding them.

**Comment by Karpenkooo** [comment]
Hey,

This is, unfortunately, is the wrong issue tracker. Please re-write this in the Framework tracker. Thanks
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

**_Karpenko - OP FW Assets Developer_**
