### ISSUE TITLE
Add a pawn shop and or Recycle facility

### ISSUE THREAD

**Issue by JC-5** [InZidiuZ/legacy-assets-issue-tracker#113]
**Name:**
Who is suggesting this? Please include discord name.
JC
**Summary:**
Write a short summary of what your suggestion is about.
It would be cool to add a pawn shop and or recycling facility for a lot of the random stuff you get from doing the legal jobs. The money doesn’t have to be anything crazy just a little something instead of throwing everything on the ground that doesn’t have a use 
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Help out the economy and new players.

**Comment by SATIN187** [comment]
Try roleplaying it out... there’s a lot of people that would give you a little cash for those unwanted materials

**Comment by AdeptCL** [comment]
I do +1 to this. And I myself have tried, and I do buy it here and there.

However, it would also be a nice feature to add in a pawn/recycle facility.

**Comment by JC-5** [comment]
I have. When’s the last time you’ve sold recycled material, broken glass, condom or a pistol. Even the mechanics don’t buy the materials bc they say it’s a waste of time. Until mechanics are whitlisted and can control the market it’s always going to be easier and cheaper to repair your own vehicle

**Comment by AdeptCL** [comment]
When my character was heavily civ RP. I used other people and bought their metals/glass/rubber, and then I'd just put my prices slightly higher so I'm making profit. I loved it.

But the problem is, the current state of the server. Until things are moved around, whitelisted, enforced, etc. People will resume to hoard their own materials. Or, not provide a potential RP scenario for others.

**Comment by JC-5** [comment]
This is a way to help out the new people no more no less. It’s a suggestion. Let’s leave it there, if the devs see it and like it then they can move forward with it. No need to make this into a rant of back in my days lol

**Comment by Karpenkooo** [comment]
Hey,

This is unfortunately the wrong issue tracker. Please re-write this in the Framework tracker. Thanks
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

**_Karpenko - OP FW Assets Developer_**
