### ISSUE TITLE
Audi RS4 Avant BUG

### ISSUE THREAD

**Issue by NobodyisLive** [InZidiuZ/legacy-assets-issue-tracker#114]
**Reporter:**
Nobody#2438

**Summary:**
Audi RS4 Avant Neon Light Not Working.

## Additional Information

**Video Proof:**
https://drive.google.com/open?id=1jKbrwirgVYFVq5zhobzoAzlYzOIgByfm

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

Please try again. This issue may be fixed after this update.
