### ISSUE TITLE
Suggestion - Increasing the time a fire burns.

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/legacy-assets-issue-tracker#115]
**Name:**
CyberSkunk#5173

**Summary:**
So I'd love to see the fire burn way longer or until it's been extinguished. Ex. on cars etc.

**Link:**
-

**Reason:**
I think this would be a really good thing for the LSFD to actually do what they are ment to do and also it could be used in so many different scenarios. In general, much people would probably like to have this implemented. Maybe even add a fire extinguisher?

**Comment by Karpenkooo** [comment]
Hey,

This is unfortnatily the wrong issue tracker. Please re-write this in the Framework tracker. Thanks
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

**_Karpenko - OP FW Assets Developer_**

**Comment by Karpenkooo** [comment]
Yes i realised i spelt **unfortunately** wrong in all of those :)))))
