### ISSUE TITLE
South Rockford Drive 7 garage

### ISSUE THREAD

**Issue by Chizz3** [InZidiuZ/legacy-assets-issue-tracker#116]
**Reporter:**
Who is reporting this? Please include discord name.
Chizz#3758
**Summary:**
Write a summary of what you're experiencing.
The garage spawns my titan to that it is in the wall and blows up every time
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://plays.tv/video/5ddc53851071706713
**Notes:**
For anything else noteworthy.
wondered if you can make the house spawn the cars parallel with the street instead of just straight on

**Comment by Karpenkooo** [comment]
Hey,

This is unfortnatily the wrong issue tracker. Please re-write this in the Framework tracker. Thanks
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

**_Karpenko - OP FW Assets Developer_**
