### ISSUE TITLE
[Bug report] Grandmas house broken?

### ISSUE THREAD

**Issue by Lunar929292** [InZidiuZ/legacy-assets-issue-tracker#117]
**Reporter:**
Who is reporting this? Please include discord name.
Lunar#0799

**Summary:**
Write a summary of what you're experiencing.
When I went down I was taken to grandmas house. (carrying) I "Checked in" to get fixed for $2500 nothing happened.. so I airlifted. nothing happened.. I got charged $700 for my injuries I was still at grandmas but couldn't leave the couch.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

This is unfortnatily the wrong issue tracker. Please re-write this in the Framework tracker. Thanks
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

**_Karpenko - OP FW Assets Developer_**
