### ISSUE TITLE
[Suggestion] Crash Priority Buff~

### ISSUE THREAD

**Issue by Lunar929292** [InZidiuZ/legacy-assets-issue-tracker#118]
**Name:**
Who is suggesting this? Please include discord name.
Lunar#0799

**Summary:**
Write a short summary of what your suggestion is about.
Crash priority is kinda bad. like real talk its horrible. if I wait 35 minutes already in the queue to get in and play for 15 mins to crash & I want to go back in but I am slapped in the face by 3/4 cause there is a legendary or staff in front of me.. thats a huge slap in the face, you shouldn't lose your spot to something YOU have no control over (the crash)

**Link:**
If there are any links to what you're suggesting, please add them here.
https://i.imgur.com/5wYuZV3.png

**Reason:**
Why would your suggestion be a good addition to Legacy?
MANY people struggle with uncontrollable crashes cause FiveM is not stable on its own and on top of this we have an abundance of scripts that add to this. short story crashes suck & losing your spot to a crash sucks even more.

**Comment by Karpenkooo** [comment]
Hey,

This is unfortnatily the wrong issue tracker. Please re-write this in the Framework tracker. Thanks
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

**_Karpenko - OP FW Assets Developer_**
