### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LilMags** [InZidiuZ/legacy-assets-issue-tracker#119]
**Name:**
Who is suggesting this? Please include discord name.

Magzify

**Summary:**
Write a short summary of what your suggestion is about.

I am suggesting that Gun and weighting overall needs to be reduced. I own a mansion with my buddy that only has 7,500 storage. That’s 3750 storage each. I have 1 2000 storage crate that literally has 1 AK, some shotguns and some pistols and is already almost filled up. maybe the max weight for guns should be something like 15. Because you do not get a lot of storage with these houses. Especially a mansion being over 10k a week. You kinda need to be a grinder, or live with someone.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?

It would just be a nice addition to help with storage

**Comment by Karpenkooo** [comment]
Hey,

This is unfortnatily the wrong issue tracker. Please re-write this in the Framework tracker. Thanks
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

**_Karpenko - OP FW Assets Developer_**
