### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kristoffermyr** [InZidiuZ/legacy-assets-issue-tracker#12]
**Name:**
Who is suggesting this? Please include discord name.
Kristoffer#9080
**Summary:**
Write a short summary of what your suggestion is about.
i recently bought every engine related mod to the Supra Like /Turbo transmission and Engine lvl4) And i think its weird it still barely hit 180 when i didnt have a upgrade on my engine at all it went 170 so in my opinion the Toyota Supra should atleast hit like 190-200 Depends on the where you re driving etc. I Personall think somethink could have been done with the accelaration aswell sine its pretty slow on the acceleration

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Because its faster and has pretty good acceleration in real life so thats one of the reasons i think ot would be a good addition. and the second thing is after all it is an exclusive car you have to pay money in order to buy it so i dont see a reason why it would be slower then the cars you get at the PDM for almost the same price

**Comment by Karpenkooo** [comment]
Hey @Kristoffermyr,

The 1996 Toyota Supra A80 has a "Stock" acceleration of 5.6 Seconds. It's also stated that it has a top speed of 160 mph. The current handling matches these specs quite well. However i will look into changing the multipliers on the Upgrades. 

_Karpenko_

_**OP-FW Car Developer**__

**Comment by Karpenkooo** [comment]
The Supra Upgrades have now been buffed by a little. To get more performance you can always find a tuner chip ;)
