### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Jxffries** [InZidiuZ/legacy-assets-issue-tracker#120]
**Reporter:**
Jxffries#1387

**Summary:**
Modifications missing on vehicle.

## Additional Information
Financing a Toros from PDM, added a different exhaust to it the day I got it, last week. Today, I took some money out of my stocks from PDM (Around £18,000) to fully tune my car, transmission, engine and turbo, with a 5k bonnet. Playing around fine, me and my friend have a couple friendly races together, which he too fully upgraded his car, and lost all his mods.

Fast forward a couple hours to where we both go to log back into the server after being off for a while, get our cars out of the garage and all the mods we put on today were gone.

I have no evidence, as far as I knew these issues were fixed when the OP-FW servers opened, because it happened to people _alot_ back then on the old framework, me included. 

**Screenshots:**
N/A

**Notes:**
Might be worth checking PDM stocks from today, I sold a few shares for £18,000 worth to withdraw the money to pay for the upgrades. All upgrades were bought in Benny's, full transmission, full engine, turbo and a bonnet that was roughly 5k.

Car the upgrades were bought on was a Pegassi Toros, date the modifications were added (02/12/19) Date the modifications were lost (02/12/19) 

My in-game ID is 9102, not sure if that's relevant but I'll post it here anyway.

Really hope this gets resolved, this bug gets fixed and it doesn't happen in the future to anyone else.

Thanks,

Jack.

**Comment by TwoplePop** [comment]
You have to store the vehicle to "save" the changes to the car. If you logged off after buying those upgrades without storing it, your car wont have those upgrades when you retrieve it

**Comment by Jxffries** [comment]
> You have to store the vehicle to "save" the changes to the car. If you logged off after buying those upgrades without storing it, your car wont have those upgrades when you retrieve it

I did, as with every time I log off.

**Comment by Isacwallin** [comment]
Just happened to me aswell, put the car in the garage before going off to "save" the mods. Has happened twice these last 2 days. Around 30k in mods lost.. Got video of the engine and turbo mods i did yesterday after it happened the first time so if it would happen again i'd get some help. Cant get my recording software to work in fivem so sorry for the quality...

https://youtu.be/_mt6sydX91Q

**Comment by Karpenkooo** [comment]
Hey,

I'm not exactly sure what's causing this mod issue. However, I will look into this.  

_**Karpenko **_

**Comment by Karpenkooo** [comment]
Hey, 

From what I know this is more of a backend issue which should be fixed in one of the coming updates.

_**Karpenko - OP FW Assets Developer**_
