### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Livius99** [InZidiuZ/legacy-assets-issue-tracker#121]
**Name:**
Nemmesys#1235
**Summary:**
I was just checking the gta online cars and came in contact with this amazing car which I forgot about but I always wanted to buy both gta O and FiveM (but it's not available on Legacy yet) the car's name is the Karin 190z, it's literally a gta version of the Datsun 240z and it can be modified pretty good!
**Link:**
https://gta.fandom.com/wiki/190z
**Reason:**
I'd really like to bring this in certains scenarios like the car shows or races! the good thing is that the car is already implemented into the game with an older DLC of gta online so it won't be that hard to add I guess. I also think it's worth having such car on Legacy because most of the players focus only on buying cars like the Elegy Retro Custom and in rare cases the comet retro custom so this wouldn't be a bad option for a classic sport since it can be modified almost as the retros.

**Comment by Karpenkooo** [comment]
Hey, 

Cricket has already spoken to me about this! I'll try to get this added as soon as possible!

_**Karpenko - OP FW Assets Developer**_

**Comment by Livius99** [comment]
You're the best guys!!!
