### ISSUE TITLE
If possible buff the corvettes handling 

### ISSUE THREAD

**Issue by JC-5** [InZidiuZ/legacy-assets-issue-tracker#122]
**Name:**
Who is suggesting this? Please include discord name.
JC

**Summary:**
Write a short summary of what your suggestion is about.
I think the vettes handling needs a pretty significant buff. If you compare it to the some of the cars half it’s price the lower end cars severely outperform the vette. I understand the theory that it’s a vette and not a ricer but the top speed is comparable to the Supra (granted I haven’t upgraded the vette bc of how bad it drives). The Z06 has one of the best traction control systems made of any sports car and it would be nice if the car in game didn’t spin out bc you needed to brake even when peddling the car around town. 

**Link:**
If there are any links to what you're suggesting, please add them here.

I don’t have any links but if anyone hasn’t driven it in a while I suggest trying it out and comparing it to cars half it’s price 

**Reason:**
Why would your suggestion be a good addition to Legacy?
I feel like it would be good because it would allow people to drive them and show different cars to the city rather than the same Evo, Supra and Lambo

**Comment by TwoplePop** [comment]
+1 the traction needs a big upgrade

**Comment by Karpenkooo** [comment]
Hey, 

I'll take a look at this! Thanks for taking the time to report the issue.

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Hey, 

This issue has now been fixed and the C7 has had a slight buff. 

_**Karpenko - OP FW Assets Developer**_
