### ISSUE TITLE
Transporter Job needs help

### ISSUE THREAD

**Issue by EKrabs** [InZidiuZ/legacy-assets-issue-tracker#123]
I have done around 100 deliveries with my semi and I have gotten enough to get my semi fixed and some gas for it. Some days I end up in the negatives. I don't know if its broke atm but the ranks in this job needs to be fixed or the money needs to go up. Thank you for your time.

**Comment by Karpenkooo** [comment]
Hey, 

This issue has been sent to the wrong GitHub page. Please re-submit it on this **Framework Tracker**(https://github.com/InZidiuZ/op-framework-bug-tracker/issues). Also, please fill out the template provided or your bug-report / suggestion will be ignored. 

![image](https://user-images.githubusercontent.com/40771170/70819487-49644d00-1dce-11ea-8700-e0c2b7df1129.png)

_**Karpenko - OP FW Assets Developer**_
