### ISSUE TITLE
License Plate Bug

### ISSUE THREAD

**Issue by Kudue** [InZidiuZ/legacy-assets-issue-tracker#124]
**Reporter:**
In-game name Ronnie Palenski. Discord yo#8216 

**Summary:**
When I use a fake license plate on my supra and get back in, it tells me to hotwire the vehicle as if I never owned it lol. So I have to hotwire it just to drive it. It's very odd.

## Additional Information
This happened two times in a row so it was a waste of 4k :/

**Screenshots:**
No screenshots, sorry.

**Notes:**
For anything else noteworthy.

**Comment by TwoplePop** [comment]
Wouldn't have been a waste if you just lockpicks it.

**Comment by Karpenkooo** [comment]
Hey, 

This issue has been sent to the wrong GitHub page. Please re-submit it on this Framework Tracker(https://github.com/InZidiuZ/op-framework-bug-tracker/issues).

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
If possible please provide screenshots too so that it's easier for InZidiuZ to understand this issue.
