### ISSUE TITLE
Supra loses control while driving.

### ISSUE THREAD

**Issue by Kudue** [InZidiuZ/legacy-assets-issue-tracker#125]
**Reporter:**
In-game name Ronnie Palenski. Discord yo#8216

**Summary:**
This past week or so, I have been having an issue with my supra that while I'm driving, the car randomly loses control as if a tire has been popped and I literally have no control for a couple of seconds. This has happened frequently throughout the week, but has happened at least 4-5 times today and even caused me to crash during a bank robbery because I lost control going 200mph while going in a straight line. Even with no damage to the vehicle, it still happens and it's honestly starting to get annoying :/.

## Additional Information
This has never happened before, just last week or 2.

**Screenshots:**
No screenshots, sorry.

**Notes:**
For anything else noteworthy.

**Comment by TwoplePop** [comment]
Bank Robbery with a supra? And it's the handling. You have to get used to it and try not to spin it out.

**Comment by Karpenkooo** [comment]
Hey, 

Could you please provide a video of this issue? I was not able to replicate the reported issue.

_**Karpenko - OP FW Assets Developer**_

**Comment by Kudue** [comment]
> Bank Robbery with a supra? And it's the handling. You have to get used to it and try not to spin it out.

Nah man, trust me it def wasn't the handling. I've had the car for over 5 months and this specifically that's happening has never happened. It literally feels like my car's tires are popped and it drifts to one side, usually the right. I can't do anything either while it's losing control like it casually goes to a side by itself and moving any other wat doesn't help. It even happened while inside the mechanic lol.

**Comment by Kudue** [comment]
> Hey,
> 
> Could you please provide a video of this issue? I was not able to replicate the reported issue.
> 
> _**Karpenko - OP FW Assets Developer**_

Yeah, i'm gonna be recording now to see if i can catch it in action.

**Comment by TwoplePop** [comment]
Yea the car is bumpy so when you fly over a small bump at 200, you have to keep the supra straight. I don't mean to be going against your point but I've had this supra since July and all it takes is practice to drive it correctly. It's really fast on acceleration by the car equals out on the "hard to counter" suspension.

**Comment by Karpenkooo** [comment]
Did you manage to get that recording?

**Comment by TwoplePop** [comment]
Wait, should I record it or him?

**Comment by Karpenkooo** [comment]
Whoever is encountering the bug?

**Comment by Karpenkooo** [comment]
Any Updates?

**Comment by TwoplePop** [comment]
I've been driving the supra daily and haven't encountered this issue, when I get back tonight, I'll try and replicate it and send it to you.

**Comment by Karpenkooo** [comment]
Alright cool. Quick question @Kudue . Was the helicopter following you during the chase?

**Comment by Karpenkooo** [comment]
This issue has now been closed due to a lack of requested video evidence. To re-open please contact me on Discord.
