### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Arnob106** [InZidiuZ/legacy-assets-issue-tracker#126]
**Reporter:**
Arnob#8600
Steam: https://steamcommunity.com/id/arnobislam/

**Summary:**
Block Payment option is not showing 

## Additional Information
**Screenshots:**
https://cdn.discordapp.com/attachments/473560960536150036/655087014097453066/Screenshot_5.png
**Server:**
Bangladesh Legacy 
**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey, 

This issue has been sent to the wrong GitHub page. Please re-submit it on this Framework Tracker(https://github.com/InZidiuZ/op-framework-bug-tracker/issues).

_**Karpenko - OP FW Assets Developer**_
