### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kr1zzzz** [InZidiuZ/legacy-assets-issue-tracker#127]
Name:
Who is suggesting this? Please include discord name.
Kristoffer#9080
Summary:
Write a short summary of what your suggestion is about.
a body kit for the BMW M4
https://www.gta5-mods.com/vehicles/m4-f82-widebody
Reason:
Why would your suggestion be a good addition to Legacy?
i think it would have been a good addition since the BMW doesn't have a lot customizable to the car the only thing you can change is the roof and the hood

**Reason:**
Why would your suggestion be a good addition to Legacy?
it would be nice sine the BMW  has no customizations

**Comment by Karpenkooo** [comment]
Hey, 

Although I cannot alter the current BMW M4 F82 Vehicle mod. I can add this mod in. Maybe even swap it with the current one on the next server wipe. Whenever that is. 

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
There are certain car models I'd like to swap though so this is a possibility for when maybe BETA Comes.
