### ISSUE TITLE
Bug report - RT 1200 Police MC

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/legacy-assets-issue-tracker#128]
**Reporter:**
Cyberskunk#5173

**Summary:**
So after the recent changes to PD vehicle sirens and lights, the bike is not working. It's still working like the old system we had, but not even 100%. You can only use lights AND sirens at the same time or just nothing at all.

## Additional Information

**Notes:**
Would be great to have this fixed as we cannot go with lights only or do a proper 10-11 etc.

**Comment by Karpenkooo** [comment]
Hey, 

I'll take a look at this. Chances are that it's just a flag missing from the Vehicles.meta.

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Hey, 

So I managed to fix this by simply adding a flag in the metafiles. However, The BMW 1200 RT is getting a new model with new textures too! Simply put.. the issue is fixed + some extras :P 

_**Karpenko - OP FW Assets Developer**_
