### ISSUE TITLE
Bug report: Garage at Roy Lowenstein Boulevard apartments doesn't work when vehicle is in the next spot over

### ISSUE THREAD

**Issue by DaSkeeT** [InZidiuZ/legacy-assets-issue-tracker#129]
**Reporter:**
-In game name: Johnny Flame
-Discord: Johnny2s#5991

**Summary:**
The Roy Lowenstein Boulevard apartments garage bugs out when a local parks their vehicle next to the "garage spot". Basically have to wait until the local leaves, hopefully the "garage spot" can be made smaller so it doesn't detect a vehicle in the next parking spot.

## Additional Information

**Screenshots:**
![Untitled](https://user-images.githubusercontent.com/58045478/71316008-924f7d80-242e-11ea-9fbe-0db8ad7bcee7.jpg)
![Untitled2](https://user-images.githubusercontent.com/58045478/71316009-924f7d80-242e-11ea-9cd2-f0073ce43902.jpg)

**Comment by Karpenkooo** [comment]
Hey,
This issue has been sent to the wrong GitHub page. Please re-submit it on this Framework Tracker.
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

_**Karpenko - OP FW Assets Developer**_
