### ISSUE TITLE
Bug report GROTTI car now only goes 120 with full upgrades

### ISSUE THREAD

**Issue by Serpentamer** [InZidiuZ/legacy-assets-issue-tracker#13]
**Reporter:**
Who is reporting this? Please include discord name.
James Dean#3814
**Summary:**
Write a summary of what you're experiencing.
My car used to go 200 MPH, but now it tops at 120 MPH. I spent over 30k on this car and am still making payments on it...I don't even like the look of the car I bought it specifically for /race....Literally can't get it over 120. If this was done intentionally I'd like to make a compensation request for my money back on the car and upgrades so that I can buy an exclusive car that actually goes the speed I need it to...
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
http://prntscr.com/ojmjbx

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Is it still going that speed after the update?

**Comment by Serpentamer** [comment]
No, as said in the post, the car maxes at 120 now. It still has all the upgrades, but it is capped at 120 somehow.

**Comment by Karpenkooo** [comment]
What car was it?
