### ISSUE TITLE
Air One Lock On Bug

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/legacy-assets-issue-tracker#130]
**Reporter:**
Dean Hunt aka TwoplePop#7989

**Summary:**
After a bank, Air one locked on to my voltic and it caused it to be undriveable completely. I couldn't turn or control my acceleration. 

## Additional Information

https://drive.google.com/open?id=1uQIKJ0zrfIujsvsyUrZaxFsq9CH0AAzo

**Notes:**
Getting locked on by air one should probably be fixed soon. Randle Caster Claimed to not have locked on but after my 46 days of playtime, thats never happened to me unless air one locks on.

**Comment by Karpenkooo** [comment]
Hey,
This does look pretty weird however the issue has been sent to the wrong GitHub page. Please re-submit it on this Framework Tracker. I'm assuming it's something to do with the heli-cam script, not the vehicle assets. 
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

_**Karpenko - OP FW Assets Developer**_
