### ISSUE TITLE
Liberty Walk Stickers

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/legacy-assets-issue-tracker#131]
**Name:**
Dean Hunt | TwoplePop#7989

**Summary:**
I think that the Liberty Walk kit on the GTR R35 should have the stickers on it if possible.

**Link:**
https://www.gta5-mods.com/vehicles/liberty-walk-nissan-gt-r this link shows the full car as an add on but it also has the livery. Im not sure if there's a way to use only the stickers but I'll suggest anyway.

**Reason:**
I think that adding this would make the kit pop out a bit more.

**Comment by Karpenkooo** [comment]
Hey, 

As of right now, I won't be replacing this with the current GTR. However once beta comes through I'll consider swapping the 2 models. Does look pretty nice after all. 

_**Karpenko - OP FW Assets Developer**_
