### ISSUE TITLE
Declasse Moonbeam Custom 

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/legacy-assets-issue-tracker#135]
**Reporter:**
Lars #9309

**Summary:**
I bought the Declasse Moonbeam Custom van, tested topspeed / acceleration stock and went straight to LS customs to fully upgrade. After upgrading the topspeed stayed the same and i don't think the acceleration  changed in a postive way.

**Screenshots:**
Car name in my garage : https://imgur.com/7jdarpv

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey, 

This issue has now been fixed and you should see a speed boost on the vehicle.

_**Karpenko - OP FW Assets Developer**_
