### ISSUE TITLE
Add Rockstar Editor Option

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/legacy-assets-issue-tracker#136]
**Name:**
Vishal Bhosale (Vishal#6256)

**Summary:**
We want Rockstar Editor in our legacy server so we can edit our roleplay seen and have more fun.. or see  a movie and cinematic scene of our roleplay..

**Link:**
https://www.youtube.com/watch?v=M6R1aWQXFao (this is video is made with the help of rockstar editor)

**Reason:**
it will help players to do more things and enjoy the situations they did in a game and content creators can make movies out of it.

**Comment by Karpenkooo** [comment]
Hey,
This issue has been sent to the wrong GitHub page. Please re-submit it on this Framework Tracker.
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

_**Karpenko - OP FW Assets Developer**_

**Comment by bhosalevishu** [comment]
okay bro
