### ISSUE TITLE
Tatto remove plastic surgery  

### ISSUE THREAD

**Issue by DewanMahide** [InZidiuZ/legacy-assets-issue-tracker#138]
**Reporter:**
Who is reporting this? Please include discord name. TerminatoR2#2260

**Summary:**
Write a summary of what you're experiencing.
There is no option to remove the tattoo from the tattoo shop. If plastic surgery is still not working by the commissioner.

**Notes:**
For anything else noteworthy.
Please fix this problem thank you

**Comment by Karpenkooo** [comment]
Hey,
I like this idea however this issue has been sent to the wrong GitHub page. Please re-submit it on this Framework Tracker.
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

_**Karpenko - OP FW Assets Developer**_
