### ISSUE TITLE
Suggestion: More legal jobs (ex: fishing)

### ISSUE THREAD

**Issue by DaSkeeT** [InZidiuZ/legacy-assets-issue-tracker#139]
**Name:**
-In game name: Johnny Flame
-Discord: Johnny2s#5991

**Summary:**
1. I believe there should be more legal jobs, as in fishing for example. Not sure if it's been suggested before, but it would be fun to go fishing along with scuba diving. Or just be able to fish legally and then have a "fish store" to turn into the fish for cash that goes straight into your bank account. I think it would be cool to have 2 spots to fish (1. dock to fish off of and and store to turn in nearby) and (2. spot to rent a fishing boat to take out in the water to a general designated fishing spot, then can take all fish back and turn into another store nearby).

2. Also, maybe have a part of the fishing that can be illegal? For example, another city I played in awhile back had different kinds of bait (ex: sea turtle bait to fish for sea turtles, that can be turned in a shady turn in spot that gives dirty money/cash back per turtle). Can expand on that where you can fish turtles for sharks for a bigger payout, but obviously more rare chance to catch.
There's a good amount of options just for fishing, that I believe would be fun for both legal and illegal parts.

**Link:**
Sample images:
![maxresdefault](https://user-images.githubusercontent.com/58045478/71786838-031d9a80-2fd6-11ea-8e10-5cd68b53de2d.jpg)
![maxresdefault2](https://user-images.githubusercontent.com/58045478/71786840-0a44a880-2fd6-11ea-9e2f-344c74ea1099.jpg)
![1432809019_Fishing Mod3](https://user-images.githubusercontent.com/58045478/71786842-1466a700-2fd6-11ea-989d-94e27152b0ee.jpg)
![46c282-screen_sell](https://user-images.githubusercontent.com/58045478/71786844-1597d400-2fd6-11ea-873c-c154b6dd7d35.jpg)

**Reason:**
Increase legal jobs as there aren't that many, would be fun to fish and RP with others either on the dock or fishing boat.

**Comment by Karpenkooo** [comment]
Hey,
I'm really sorry to say this because you've put a lot of effort into this... However, this issue has been sent to the wrong GitHub page. Please re-submit it on this Framework Tracker.
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Sorry <3
