### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by HazzerEFC** [InZidiuZ/legacy-assets-issue-tracker#14]
**Reporter:**

Harry. Q - hazzerefc#4679

**Summary:**

Ubermacht Revolter - Limited to 113 Mph even on a down hill. There is no handling file made for this and a custom one needs put into place if possible as its extremely fast acceleration does not pair with its top speed by any means.

## Additional Information

n/a

**Screenshots:**

http://prntscr.com/ojmvn7
**Notes:**

n/a

**Comment by Karpenkooo** [comment]
Hey @HazzerEFC ,

This issue has now been fixed and the Ubermacht Revolter is no longer restricted to 113 mph. This fix should come in the next server update.

_Karpenko_

**_OP-FW Vehicle Developer_**
