### ISSUE TITLE
Sooo, the S15 in its entirety. Here we go.

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/legacy-assets-issue-tracker#141]
**Name:**
Dean Hunt | TwoplePop#7989

**Summary:**
So basically, I feel like there are a few things that should be tweaked about the new S15. First off, the handling feels like I'm playing regular GTA with this add on. It feels way too light. Light enough to go on 2 wheels every other corner. Another thing is the turn radius. It has way too much of a turn radius while accelerating for a car like the Silvia. Even going on a normal street, it feels like the car is jumping around as I turn(1:14 in the video, watch the tires jumping around while accelerating up the road.). Now this looks like a major issue when you watch the video. Moving on, this car has 36 spoilers. Now, the 36th spoiler is, welp, 15,100 dollars. That's a lot for a spoiler. The front bumper and most of the body work that can be customized on this car have the same issue since it seems to be the most customizable car on the server currently. I feel like the car sound could also use a change. The sound right now sounds like an SUV or the Lampadati Felon. I think it's actually the Super Diamond engine sound. This car does not fit the sound that it has currently in my opinion. This car does seem to not want to double clutch even though it is rear wheel drive but thats probably to do with the awkward handling(2:05 is where I demonstrate the double clutch.). While mid double clutch, It idles and doesnt accelerate at all. This doesn't happen on the supra or any other car with RWD or even AWD which I have been able to double clutch with my methods. I also think for an S15, this should have a higher top speed but that could just be me admiring the car :) More info about my car that you're seeing in the video, It has ZERO upgrades(straight from dealership.) It also seems to be damaged a little bit. I think it was at 60 percent at the time of recording. But even with 100%, this car would be on 2 wheels around corners even more with the extra power of being 100% and its lightness of a feather. Sorry i'm editing this a lot because I forget things lol. I have 1 more thing to add. The suspension upgrade for the competition suspension(Tier 4) is the exact same as the stock suspension while Race Suspension(Tier 3) is currently the lowest I can get it to. Screenshots will be provided as usual. Flipping through the screenshots, you can tell that the suspension doesn't change at all and it looks like the photo is the same but you can tell that it's not by looking at what suspension I am choosing. Now, I don't have a screenshot of the Sport Suspension but I can assure you that that suspension is the lowest I can currently go. Might add more depending on what I find. I added a turbo which didn't really affect handling at all but definitely bettered the engine/exhaust sound. I'm not sure the current sound is still a good fit to this car though.

**Link:**
1. Video of handling https://drive.google.com/file/d/1CdOA3jGI_mVnng1iObpgxfu5bSAxwWuu/view?usp=sharing

2. 15000$ spoiler
https://drive.google.com/open?id=1j-yEsf5eU_7cxGfUphauHapZbGy_4sT9

3. 10000$ Front Bumper
https://drive.google.com/open?id=1qolSh5H6vH2OhlgVe8gcA1LJXHYW1G1q

4. Suspension Stock
https://drive.google.com/file/d/1Um8Oxkep8dXMNfbo6O8n4ylFwHzWU2Iv/view

5. Competition suspension(Tier 4)
https://drive.google.com/file/d/1FFQUZNOjWrgXORLdYgAsuBZa1wM4lB0X/view

**Reason:**
I think it would be a good suggestion to Legacy RolePlay since this is one of the most iconic cars and seeing it like this is probably not so good in comparison to its potential. BTW, thank you sooo much Karpenko and Ben for putting this car in the server.

Motivation Picture lol
https://drive.google.com/open?id=1cXNjfQTMr3cvoInB0i3xqgFf6hagOMxm

**Comment by Karpenkooo** [comment]
Hey, 

Thanks for taking the time to write up such a lengthy bug report. I'm going to make some handling changes however I will not assist you in making the vehicle "double clutch" as I see this as an unrealistic approach to driving. In terms of the LS Customs prices, I can not do anything about them however I'll take the time to speak to @InZidiuZ about them. 

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Hey, 

This issue had now been fixed with the last server update! If you feel like it's still broken then please send another report. 

_**Karpenko - OP FW Assets Developer**_
