### ISSUE TITLE
Invisible Wall in San Andres Avenue near Burger Shot!

### ISSUE THREAD

**Issue by MrHitmanDrHitman** [InZidiuZ/legacy-assets-issue-tracker#142]
**Reporter:**
IGN: Mr. Hitman
Discord: YouTubeGaming_YT#7274

**Summary:**
Every time I drive Transport Truck my truck gets blocked at San Andress Avenue, near Burger Shot! I cant reverse or move my truck after the impact with this invisible wall and my job gets ruined!! 

This happened over 30 times in a row. First I tried to ignore that road but now I feel like it needs to be fixed!! I lost more than 15000$ Jobs due to this! I have 2 more witnesses who faced the same issue in same area while driving Transport Truck.

## Additional Information
This only blocks the Transport Truck no other vehicles!!

**Screenshots:**
![image](https://user-images.githubusercontent.com/59993622/72619526-82f71d80-3963-11ea-875a-2f0a6d6b09c6.png)

**Notes:**
Fix it as soon as possible please!!

**Comment by AdeptCL** [comment]
Never had this issue myself, but can see why it'd be a pain.

**Comment by Karpenkooo** [comment]
Hey,

This doesn't seem to be a server-side issue as the burger shot looks just fine for me however I have had a similar bug before and the way to fix it is to go to verify the game file. To do this you go to your Steam Library > GTA V > (right-click) select "Properties" >Local Files >then click "verify the integrity of game files". 

![image](https://user-images.githubusercontent.com/40771170/72632394-19204900-394e-11ea-9f3a-d2086a4e36af.png)

Once you've done that and you've acquired the necessary files you shouldn't experience this bug! 

Try this and let me know if the issue has been fixed! 

_**Karpenko - OP FW Assets Developer**_
