### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Hanssonjao** [InZidiuZ/legacy-assets-issue-tracker#143]
**Name:**
Who is suggesting this? Please include discord name.
IG: Ryan Williams
Discord: Hansson#8418

**Summary:**
Write a short summary of what your suggestion is about.
3 New bikes for the mc people. Since it lacking a lot on the bike front for all the mc's and everyone around the city that love bikes. We could use some new faces around town.

The Cali Cholo bike is a nice looking bike has some inspo from the mayans. 
The American Bobber is a nice custom bike that has a mean look to it.
And the Victorious is a huge bike that is a good raodtrip bike if you wanna go up north. or take a long ride with your friends.

Just hit me up for the files if they are of interest.

**Link:**
If there are any links to what you're suggesting, please add them here.
Start with the first bike: Cali Cholo https://gyazo.com/edf75120e568a9bab5fe9ab0c7551190
second bike: American Bobber https://gyazo.com/6bb3b71b0e71302d36e72dab45b8fc00
third bike: Victorious https://gyazo.com/01216f76f8d3c974baf0a0010e68c1f7

**Reason:**
Why would your suggestion be a good addition to Legacy?
Since we are lacking a lot on the bike front from what i have seen and heard. this would make it so people would react more when they see the bikes. It would make the RP for MC's better as well, it will look more real.
And i think we need some new bikes around the city. Cuz those old ones are looking old when you see those import cars comes driving around.

**Comment by Karpenkooo** [comment]
Hey, 
I do agree that we need more motorbikes however I don't think we will be adding any soon. Possibly will add some once Beta comes around. I'll keep this suggestion open until I make a final decision. _(Chances are that a few will be added but not all of the bikes)_

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
@Hanssonjao Are you able to send the 2 you want most added?

**Comment by Hanssonjao** [comment]
Yes ofc i am. I can send them over on discord to you

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

________________________________
Från: Karpenko <notifications@github.com>
Skickat: Wednesday, March 25, 2020 11:19:46 PM
Till: InZidiuZ/legacy-assets-issue-tracker <legacy-assets-issue-tracker@noreply.github.com>
Kopia: Hanssonjao <simon_952@msn.com>; Mention <mention@noreply.github.com>
Ämne: Re: [InZidiuZ/legacy-assets-issue-tracker] Suggestion (#143)


@Hanssonjao<https://github.com/Hanssonjao> Are you able to send the 2 you want most added?
