### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RandleCaster** [InZidiuZ/legacy-assets-issue-tracker#144]
Name:
Who is suggesting this? Please include discord name.
@ST-407 | Randle Caster

Summary:
Write a short summary of what your suggestion is about.
I feel that the Vagner could use some tweaking.

Reason:
Why would your suggestion be a good addition to Legacy?
The Vagner is a 340,000$ super car that only goes 145-150 stock on flat and has rather poor acceleration.

**Comment by Livius99** [comment]
Almost all super cars or classic cars go slow af rn. Karpenko is changing something to all the cars atm as long as I know

**Comment by Karpenkooo** [comment]
Hey, 

As stated in the comment above I'm currently adjusting the vehicle handlings of every single car. This will take a little more time however I can promise that the Vagner will be buffed in time for the next handling update. 

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Hey, 

I believe this issue has now been fixed! If you still feel like it should still be tweaked then please send another report in. 

_**Karpenko - OP FW Assets Developer**_
