### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DopePixel** [InZidiuZ/legacy-assets-issue-tracker#145]
Who is reporting this? Please include discord name.
DopePixel#9481

**Summary:**
The garage of the block of Spanish Avenue Apt. Complex M (122) The garage is very terribly placed.  When you go to get a vehicle such as a tow truck out of the garage it will spawn on top of youu and while putting vehicles in the garage it is very easy to get stuck on the stairs.

## Additional Information
The more suitable place for this garage would be out of the front door and down the stairs to the left.  As there is an actual garage here and a lot more room so the vehicle will not spawn on top of you.

**Screenshots:**
 
 The Block : 
![image](https://user-images.githubusercontent.com/57329053/74096588-d249ed00-4ace-11ea-9e56-f61b8b42fa45.png)

New Garage Location:

https://youtu.be/phMnPBBHIcc

For anything else noteworthy.
I feel as if this would help as it is more realistic and will stop the car spawning on top.

**Comment by Miliax** [comment]
agree. its terrible. there is a better spot for the garage. there is a '' parking lot '' under the stairs down left of the pic. much better spot

**Comment by Karpenkooo** [comment]
Hey,
This issue has been sent to the wrong GitHub page. Please re-submit it on this Framework Tracker.
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

_**Karpenko - OP FW Assets Developer**_
