### ISSUE TITLE
Bug report - Audi SQ7 SUV Trunk

### ISSUE THREAD

**Issue by TCruxer** [InZidiuZ/legacy-assets-issue-tracker#146]
**Reporter:**
Cruxer#4806

**Summary:**
After buying the Audi SQ7 SUV I realized quickly that it was impossible to open doors 5 and 6 (trunk and hood). At first, I thought it didn't matter but I then realized that it caused an issue where the car didn't recognize the trunk and so it is impossible to place bodies even though the trunk looks to be quite a decent size. 

## Additional Information
Not sure if this is for you or Ben but I'm gonna put it here anyway.  I also don't know if this is fixable but I just thought I'd put it in here if it is.

**Screenshots:**
https://imgur.com/a/bZzhS8k

**Comment by Karpenkooo** [comment]
Hey, 

This should just be an issue within the Vehicles.Meta file. However, I'll need to take a closer look at it. Thanks for using the GitHub report <3

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Hey, 

I've come to realise that this issue cannot be fixed due to the mod being broken. I'll need to wait for the next wipe and replace this vehicle with a new model. 

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Hey, 
This issue should soon be fixed with a new trunk system. This system will not be worked on by me.

_**Karpenko - OP FW Assets Developer**_
