### ISSUE TITLE
New MLO Hospital Interior - Pillbox Hill (#764 Repost)

### ISSUE THREAD

**Issue by LikeConnorr** [InZidiuZ/legacy-assets-issue-tracker#147]
**Name:**
Con#0053 | Connor | X-130 C. Steel

**Summary:**
My initial suggestion is to add a new hospital interior. Interiors and maps are generally really expensive and costly for almost any FiveM server. For example, this one here is $1,500. https://www.youtube.com/watch?v=dlJ-4uKrVdU. It contains 47 rooms and 4 floors. Since then, another has been released, which is only a $30 monthly subscription for 1 premium interior a month. If Legacy would only purchase the hospital, the subscription can be immediately cancelled. The interior is used by NP. This is the interior:

https://www.youtube.com/watch?v=4B0f0GO2MYM
The interior contains offices, lobbies, wards, examination rooms, x-ray rooms, mri rooms, diagnosis rooms & more...

**Reason:**
Everyday in the medical department we're urging to teach more advanced medical knowledge for the roleplay and everyday medical needs. We all feel that with a new hospital we can deliver the roleplay in an appropriate setting. For now, I tend to complete surgeries and scans within the morgue. This would be an exciting feature for beta, and would finally bring a suprise to the server that aren't crosshairs ;). The hospital has appropriate locations for signing on-duty, signing on doctor-duty, checking into the hospital and exciting the city when permaing. It also has appropriate clothing editing locations.

I hope you understand why this would be an amazing feature to bring LRP to the next level.

**This suggestion was reposted in the correct board.**

![pb](https://user-images.githubusercontent.com/32584094/74665799-4738b900-5198-11ea-87a4-9b8dc829f3d4.jpg)

**Comment by LikeConnorr** [comment]
Refer to https://github.com/InZidiuZ/op-framework-issue-tracker/issues/764 for previous commentation.

**Comment by AdeptCL** [comment]
For someone who spends a large majority of their time on an EMS character. Having this overhaul and renovation to Pillbox would be very motivating, and increase productivity when being on-duty.

At the moment, Pillbox feels like a scapegoat for people who have been shot up/badly injured as a way to almost disregard previous encounters. Having this change, I believe it would not only improve the medical roleplay side of things, but also help people identify how much effort some of us put into the EMS department on Legacy Roleplay.

Having set rooms for certain procedures completely improves the medical roleplay on the server because we don't have to perform certain things in the main ward like we currently do.

**Comment by W1lsonCodes** [comment]
The hospital is in the works of being updated. Note that this interior will be available soon.

**Comment by Livius99** [comment]
Is it possible to have like two hospitals? :/ or the other interiors cant be unlocked /used?

**Comment by W1lsonCodes** [comment]
2 Hospital situation is a work in progress.

But someone has suggested it.

For now it will replace the current Hospital

**Comment by Karpenkooo** [comment]
"this one here is $1,500."

 o_O WOT

**Comment by iGreatWhite** [comment]
It’s not $1500 rather only $30 through Gabz Discord. The guy makes great assets.

**Comment by LikeConnorr** [comment]
The $1,500 one is not the one listed. I am giving an example on how expensive the market can be. Thus being that this one is an amazing buy, although Ben already has the files.

Really happy to have confirmation that this will be pushed.

**Comment by Karpenkooo** [comment]
If he has them then it will be pushed

**Comment by Karpenkooo** [comment]
Idk when though

**Comment by Karpenkooo** [comment]
Hey, 

This suggestion has now been implemented by @InZidiuZ . 

_**Karpenko - OP FW Assets Developer**_

**Comment by walalzh12** [comment]
Hey
