### ISSUE TITLE
Bug report Dodge Charger

### ISSUE THREAD

**Issue by Miliax** [InZidiuZ/legacy-assets-issue-tracker#148]
**Reporter:**
miliax#2530
**Summary:**
I Just bought the Dogde Charger from legendary tier. 
I can't open the hood, i hear the sound but it wont go up. i bought the hood that was most expensive so i don't know if it's the same on the stocked one.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Miliax** [comment]
Apparently its like that with all 3 hoods, only the stocked one can open

**Comment by Karpenkooo** [comment]
Hey, 

After a bit of testing, I've also found that the stock hood does lift up however the rest do not. Unfortunately, there isn't anything I can do about this issue however I'll keep an eye out for any updates to the mod. 

_**Karpenko - OP FW Assets Developer**_
