### ISSUE TITLE
Functional spotlight on policecars.

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/legacy-assets-issue-tracker#149]
**Name:**
Jason Gonzales - CyberSkunk#5173

**Summary:**
So basically I would love to see a working spotlight on the cruisers that you actually can use, rotate and such when it's dark outside. IRL the cruisers have this feature and I think it would be really cool to have it here as well. I've seen it on other servers as well.

**Reason:**
I think it could be extremly useful in many different situations. I.e. searching for suspects etc when it's dark outside. This would also give the police a much more realistic and fun RP when ever they are in need of extra lights.
![PDSpotlight](https://user-images.githubusercontent.com/50070645/75113662-0e915780-5650-11ea-8127-5a12afd2e7fe.png)

**Comment by Vedder742** [comment]
I see this being used on real videos (Live PD) all the time, I think this would be a great addition for the server. 
I am not a developer but I'd like to think that it's not too hard to create a controllable spotlight. 
Please make this a thing!

**Comment by Karpenkooo** [comment]
Hey, 

I like the idea of having a spotlight and i actually found it really useful back when I used to play LSPDFR. I'll definitely look into this however it probably won't be me that works on this addon.

_**Karpenko - OP FW Assets Developer**_

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
