### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by HazzerEFC** [InZidiuZ/legacy-assets-issue-tracker#15]
**Reporter:**
Harry. Q - hazzerefc#4679

**Summary:**
Declasse Tulip - muscle car

This car is limited to 103. Its car specs are to be shown in this link and it refers to the vehicle being associated with the vehicle "Chevelle Malibu". This vehicle has a V8 engine which has the option to be supercharged. When fully upgraded the vehicle hits 103 and on bumps to 115 the same as prior to this when not upgraded, just with more acceleration. It states that its handling is remarkable but upon turning and bumps its suspension is extremely soft due to its offroad racing capabilities. The car in my opinion needs a bump in speed as well as stiffer suspension as its too easy to roll the vehicle as well as being a muscle car its quite slow.

## Additional Information
"The car holds a V8 engine with a mounted cylinder air filter, positioned in a front-engine, rear wheel drive configuration through a 4 speed gearbox."

As stated from " https://gta.fandom.com/wiki/Tulip "
**Screenshots:**

n/a

**Notes:**
Another issue with this car is due to a lot of cosmetic upgrades that its offers, every extra upgrade add around $500-$1000 each upgrade which means just for a bonet cosmetic it costs $6.5k. In my personal opinion this is not fair and equally matched with the economy as well as other upgrades, *HOWEVER* I acknowledge that a *lot* of cars have the same issues involving prices for upgrades. On a whole apart from performance upgrades, the prices need decreasing

**Comment by Karpenkooo** [comment]
Hey @HazzerEFC 

The Declasse Tulip has now been buffed. However i can't do much in terms of the Los Santos Customs prices. That would be for @InZidiuZ . 

_Karpenko_

_**OP-FW Vehicle Developer**_
