### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Livius99** [InZidiuZ/legacy-assets-issue-tracker#150]
**Name:**
Nemmesys#1235
**Summary:**
I'd like to see an improvement on the speed of the Infernus Classic. The car's handling is good, the grip is perfect, the acceleration ok but the top speed is quite low. I've tested it and stock reaches 125mph on straight roads, 130-139mph sometimes on highway. 

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
The car's price is quite high and I think a slight improvement would be great on it. Also it should compete with the Turismo Classic which reaches around 160-170mph stock. Both cars are great looking, the speeds don't fit them since they are replicas of Ferrari and Lamborghini.

**Comment by Imaghost1337** [comment]
Huge +1 on this one

**Comment by Livius99** [comment]
I already know that Karpenko is working on it, just wanted to make sure that gets improved xd

**Comment by Karpenkooo** [comment]
Hey, 

As I've said a few time I'm midway through fixing some car handlings. The Infernus Classic will receive a speed buff in the next update. 

_**Karpenko - OP FW Assets Developer**_

**Comment by Livius99** [comment]
That's all I wanted to know
♥️
