### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by coryraulerson** [InZidiuZ/legacy-assets-issue-tracker#152]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185

**Summary:**
Write a short summary of what your suggestion is about.
New Hairs, Beards, ETC for Males and Females
**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/player/long-haircut-for-mp-female
https://www.gta5-mods.com/player/another-braided-haircut-for-mp-female
https://www.gta5-mods.com/player/long-braided-haircut-for-mp-female
https://www.gta5-mods.com/player/long-haircut-with-bangs-for-mp-female
https://www.gta5-mods.com/player/hair-styles-for-mpfemale-part-3
https://www.gta5-mods.com/player/harley-quinn-cry-baby-bangs-hair-for-mpfemale
https://www.gta5-mods.com/player/hair-styles-for-mpfemale-part-5
https://www.gta5-mods.com/player/hair-styles-for-mpfemale-part-5-serskyamn

**Reason:**
Why would your suggestion be a good addition to Legacy?
Add more variety for females and or males so they don't all have the same hairstyle

**Comment by Karpenkooo** [comment]
Hey, 

We now have a Discord channel made for custom clothing and hairstyles. Please send it into #clothing-suggestions in the Framework development tab. 

_**Karpenko - OP FW Assets Developer**_
