### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by coryraulerson** [InZidiuZ/legacy-assets-issue-tracker#153]
**Reporter:**
Who is reporting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a summary of what you're experiencing.
Headlights on the Mustang GT (70k Legendary tier) Headlights do not work on it at all. Tried even buying the Xeon lights and still nothing
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://prnt.sc/rby7v5
https://prnt.sc/rbycmm
https://prnt.sc/rbycw3
**Notes:**
For anything else noteworthy.

**Comment by coryraulerson** [comment]
also found another issue the back taillights are always blinking even when your hazards arent on......
makes this very distracting while driving
https://prnt.sc/rbyhe9 Brighter than the picture makes it
https://prnt.sc/rbyily

**Comment by Karpenkooo** [comment]
Hey, 

I'm currently working to fix this issue. I'm assuming it's an issue within the carcols.meta of for the vehicles. I apologise for any inconvenience. 

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Hey, 

This issue has now been fixed and will be pushed to GitHub soon!

_**Karpenko - OP FW Assets Developer**_
