### ISSUE TITLE
Suggestion - Moving the outfit/doctor sign-on triggers in the Hospital

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#155]
**Name:**
AdeptCL#0402

**Summary:**
Changing the location of where people get changed to the new locker room, which is accessed via behind the desk.
Changing the location of the doctor sign-on to the break room, which is accessed via behind the desk.

**Link:**
There are no links available. But I will provide some screenshots to assist in the reason.

**Reason:**
Currently, the outfit change location is still in the Morgue area which I feel is now out-dated. I recommend this being moved to the new locker area in the staff room next to the new reception desk.
> https://gyazo.com/65469be8dc2c65de5297fbc94df438ea
Essentially where the current "Doctor sign-on" trigger is.

In addition to this movement, I would also recommend moving the "doctor sign-on" trigger to the room before it - the break room.
> https://gyazo.com/17410d5595bf1b033e5eee353ebc9563

The move would hopefully stop them overlapping when triggering one of them.

**Comment by Karpenkooo** [comment]
Hey, 

I have forwarded this issue to @InZidiuZ and he should be able to take care of it in time for the next update. 

_**Karpenko - OP FW Assets Developer**_

**Comment by Karpenkooo** [comment]
Hey,
This issue now needs to be sent to the framework bug report. Please re-submit it on this Framework Tracker.
https://github.com/InZidiuZ/op-framework-bug-tracker/issues

_**Karpenko - OP FW Assets Developer**_
