### ISSUE TITLE
Nissan Titan Bug And No Livery.

### ISSUE THREAD

**Issue by hcboss** [InZidiuZ/legacy-assets-issue-tracker#156]
**Reporter:**
MJ #6969
**Summary:**
EDM car as we know Nissan Titan has a Light Bug and no Livery Option. Please Look into it Screenshots down here.
## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/603653826427486217/687738000163209258/Desktop_Screenshot_2020.03.13_-_00.31.28.52.png

https://cdn.discordapp.com/attachments/603653826427486217/687738004671823923/Desktop_Screenshot_2020.03.13_-_00.25.06.56.png

**Comment by Karpenkooo** [comment]
Hey, 
The issue with the lights has now been fixed however I don't have any plans to add liveries to the Titan. Thanks for including screenshots in your bug report. If you have any more issues, please create another bug report. 

_**Karpenko - OP FW Assets Developer**_
