### ISSUE TITLE
Flash GT missing a trunk and top speed.

### ISSUE THREAD

**Issue by MPar22** [InZidiuZ/legacy-assets-issue-tracker#158]
**Reporter:**
Par#0396

**Summary:**
I recently purchased the Flash GT from PDM and the car went 168 mph stock. After spending thousands of dollars fully upgrading the vehicle, the top speed remained the same at 168 mph. I also noticed that there is no option to put someone in the trunk of the vehicle.

![Flash GT](https://user-images.githubusercontent.com/62226246/76717164-42204880-6709-11ea-8257-e89f39e63d44.png)

Thanks for looking into these issues!

**Comment by maguhd** [comment]
I own the same car. Spent thousands of dollars fully upgrading the vehicle too, same top speed. And yeah, it does not have a trunk. But clearly there's space in the trunk to fit a person.

**Comment by maguhd** [comment]
Top speed still 168 after 2.4.1

**Comment by TCruxer** [comment]
Hey, 

The car speed/acceleration has been adjusted and will be fixed in the upcoming updates.

Regarding the lack of trunk this should no longer be an issue with the new trunk system.

**Cruxer   _Lead Asset Developer_**
