### ISSUE TITLE
EMS Tahoe Lights

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/legacy-assets-issue-tracker#159]
**Reporter:**
Duroode#2178

**Summary:**
The Lights on the Tahoe have become "Scuffed" which i can only assume its from the latest update where the PD Lights/Lightbars got changed, it must have Effected the EMS Tahoe too. along with that the lights are supposed to be all red, and it has some blue flashses in there too.

## Additional Information

**Screenshots:**
https://www.youtube.com/watch?v=GA-XIuXxysQ&feature=youtu.be

**Notes:**
:)

**Comment by Karpenkooo** [comment]
Alright, I'll take a look at this issue. Just want to clear some things up though.

How long has this been an issue? 
Was it working properly before the update? 
Were the lights all red and amber before? 

Thanks for the video though! Helps me see the issue!

**Comment by Duroode** [comment]
1. Since the Update with the New PD Vehicles
2. Yes
3. Yes

**Comment by Karpenkooo** [comment]
Wow my friends don't even reply to me that fast

**Comment by Karpenkooo** [comment]
Alright, thanks! I'll take a look and can hopefully fix it without changing models. However, if there is a bigger issue with the model I may need to change it.

**Comment by Duroode** [comment]
Its a slow day and i got exited when i seen the email.

**Comment by Duroode** [comment]
Worst case Scenario, you can just give us the Charger :))

**Comment by Karpenkooo** [comment]
Or a reliant robin :))

**Comment by Duroode** [comment]
[:)](https://i.kym-cdn.com/photos/images/newsfeed/000/114/139/tumblr_lgedv2Vtt21qf4x93o1_40020110725-22047-38imqt.jpg)

**Comment by Karpenkooo** [comment]
If I do replace the car then what replacement you want?

**Comment by Duroode** [comment]
Refer ro discord DM's

**Comment by Karpenkooo** [comment]
Hey, 
This issue has now been fixed. The Tahoe has been replaced with a 2017 Silverado. PogU

_**Karpenko - OP FW Assets Developer**_
