### ISSUE TITLE
Mercedes CLS AMG

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/legacy-assets-issue-tracker#16]
**Reporter:**
Lars. #9309

**Summary:**
I own a Mercedes CLS AMG, i installed a Turbo, Race Trans and Engine level 4.
Topspeed on a flat surface is about 190MPH.
But when i have passengers in the car it doesn't go any quicker then 150 - 160MPH, even when going downhill.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by y0Razz** [comment]
I don't think it has something to do with passengers.
On this screenshot i'm driving solo.
https://i.imgur.com/CZDbVAS.png

**Comment by Karpenkooo** [comment]
Hey @y0Razz 

Thanks for submitting this bug. I'll take a look at this issue in a few hours. I already have a good idea of why this is happening. 

_Karpenko_

**_OP-FW Vehicle Developer_**

**Comment by Karpenkooo** [comment]
Hey 

Is this still an issue on the live servers? After trying to replicate it i was unable to see a decrease in the vehicles top speed.

_Karpenko_

_**OP-FW Vehicle Developer**_

**Comment by y0Razz** [comment]
Hi,

Car is still capped at 162MPH for me.
Both body and engine are at 100%.

**Comment by y0Razz** [comment]
Hi,

I can confirm that the car still doesn't go any quicker then 150 - 160mph, even when going downhill.

**Comment by Karpenkooo** [comment]
Yikes, Well i've got a fix now but it will only come in the next update
