### ISSUE TITLE
Add a trunk to the Lost Slam Van - Suggestion

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/legacy-assets-issue-tracker#160]
**Name:**
CranioDad#0619

**Summary:**
The Lost Slamvan does not have a trunk to put a player in?

**Link:**
None

**Reason:**
It seats four, has back doors, hard to believe that you cannot put a player in the trunk.

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
