### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/legacy-assets-issue-tracker#161]
**Name:**
Duroode#2178

**Summary:**
change the Mustang sound to the Frankenstrange

**Link:**
https://www.youtube.com/watch?v=RtsTiV6V7qg

**Reason:**
It sounds cool :)

**Comment by Karpenkooo** [comment]
not enough effort LULW

**Comment by pxyeb** [comment]
Car has been given another sound, even a better one than the Frankenstrange.
