### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Livius99** [InZidiuZ/legacy-assets-issue-tracker#162]
**Reporter:**
Nemmesys#1235
**Summary:**
The 190z is in PDM but cannot put it in the showroom 
## Additional Information
You can actually see the name of the car showing up but when you choose it nothing shows up in the showroom and when you try to /testdrive it says that " the vehicle doesn't exist" 
**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey, 

This issue has now been fixed! It was caused by an incorrect spawn name that I wrote. I apologise for the mistake! (Will come in the next update)

_**Karpenko - OP FW Assets Developer**_
