### ISSUE TITLE
Car Suggestion: Fränken Stange

### ISSUE THREAD

**Issue by LadyH0pe** [InZidiuZ/legacy-assets-issue-tracker#164]
**Name:**
Lady Hope [LadyHope#0723]

**Summary:**
**Car suggestion:** Fränken Stange

**Link:**
https://gta.fandom.com/wiki/Fr%C3%A4nken_Stange

**Reason:**
Interesting car, unique and would fit certain characters perfectly as their vehicle of choice. Has a lot of potential customisations as well as fits this exclusive genre of hot rod and classic car.

**Comment by TCruxer** [comment]
Hey @LadyH0pe,
This car has now been added to PDM and will be available to buy in the upcoming updates.

**Cruxer _Lead Asset Developper_**
