### ISSUE TITLE
Can't use any items

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/legacy-assets-issue-tracker#165]
**Reporter:**
Beezy#6584

**Summary:**
All items in inventory currently will randomly stop working. I'm not sure what is causing them to work at a certain time and then stop working later. It is extremely frustrating as police because you are unable to draw any weapons or use anything from your inventory at all.

## Additional Information
https://streamable.com/yj1uyv

**Screenshots:**
Uploaded video of trying to use items as well as a quick scroll through F8 if it helps anything as i don't know when it stopped working.

**Notes:**
Don't know how this is happening to reproduce. it just randomly stops workings and i don't know what is causing it. Has happened 4 times since the update.

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
