### ISSUE TITLE
R32 constantly going over bumps.

### ISSUE THREAD

**Issue by MPar22** [InZidiuZ/legacy-assets-issue-tracker#166]
Reporter:
Par#0396

Summary:
While driving the R32, the car sounds like it is constantly going over bumps. From time to time, the car has trouble handling and will also randomly flip in the air because of the bumps, causing the car to easily be totaled. I'm not sure if the car is off-balanced causing the constant bumps, but something is throwing the car off. Thanks for taking a look at this issue!

**Comment by MPar22** [comment]
Below is a clip of the issues I have been experiencing with the car. Listen for the constant sound of driving over bumps, and look for the few times the car randomly jumps up in the air. It seems as though the car is as light as a feather!

https://medal.tv/clips/22145400/d1337JYHnTMG

**Comment by AndersHSR** [comment]
Fix have been pushed, if this happens again, please do inform.
