### ISSUE TITLE
Police Evidence Locker not responding

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/legacy-assets-issue-tracker#167]
**Reporter:**
Beezy#6584

**Summary:**
The evidence locker inventory is currenlty not opening. On open it closes immediately. Not sure if the last fixes interfered with it in some way as it was working before to my knowledge.

## Additional Information

**Screenshots:**
https://streamable.com/e7mtrq

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
