### ISSUE TITLE
Seat Belts - Gun Crates

### ISSUE THREAD

**Issue by JFEAndrews** [InZidiuZ/legacy-assets-issue-tracker#168]
I have notices a issue when using a seat belt that if you have it on you can still get out of the car....now idk if this only happens when you stop but I haven't tried it while driving.....

when doing a gun run, when you open the crate for your weapon it tells you you got a weapon but you don't receive it

**Comment by JFEAndrews** [comment]
Oh and also the warehouse seems to not be giving money for the scrap and materials that you turn in

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
