### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by NovaPurpl3** [InZidiuZ/legacy-assets-issue-tracker#169]
**Reporter:**
Who is reporting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a summary of what you're experiencing.
Headlights on Camaro do not work
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.
Really bothering that my lights dont work at night time :(

**Comment by AndersHSR** [comment]
Hi there, can you please upload a screenshot showing which camaro and which lights are not working? I've investigated, and couldnt find your issue.

**Comment by AndersHSR** [comment]
No Response, and issue could not be reproduced.
Closing.

**Asset Developer Anders**
