### ISSUE TITLE
Audi RS3 Not Showing Neon Kit

### ISSUE THREAD

**Issue by WoooMonsta** [InZidiuZ/legacy-assets-issue-tracker#17]
**Reporter:**
- WoooMonsta⭐#1
https://steamcommunity.com/id/WoooMonsta/

**Summary:**
Bought a Audi RS3 from imports and the neon kit does not show. I spend 3800 on it as i though i did not put the kit on it and it bought again to double check. Changed the colour twice and then tried it again the third time but no change.

## Additional Information

**Screenshots:**
![Untitled2](https://user-images.githubusercontent.com/52989835/61995644-b473e800-b0a8-11e9-8e33-7f3323998b56.png)
![Untitled1](https://user-images.githubusercontent.com/52989835/61995645-b473e800-b0a8-11e9-8d77-235194ce99d6.png)
![Untitled](https://user-images.githubusercontent.com/52989835/61995646-b50c7e80-b0a8-11e9-8b0d-12dea25e616d.png)

**Notes:**
Thanks for the server and again i appreciate the hard work you put into the server for the community :)

**Comment by Karpenkooo** [comment]
Hey @WoooMonsta 

We are aware of a bug with Addon cars in LS Customs. We're looking into it and will hopefully have a fix for it in the near future. 

_Karpenko_

**_OP-FW Vehicle Developer_**

**Comment by WoooMonsta** [comment]
Roger That !

**Comment by WoooMonsta** [comment]
@Karpenkooo Same issue with flatbed (which i upgraded and tried putting a neon kit and it doesnt show 1000$ ded) 

Just thought i should bring it to your notice :D
