### ISSUE TITLE
Automated Ban

### ISSUE THREAD

**Issue by RandomKilled** [InZidiuZ/legacy-assets-issue-tracker#170]
**Reporter:**
RandomKilled#0300

**Summary:**
Some people are getting automatically banned when completing the first part of hacking for gun runs.

## Additional Information
Only happens when the part of the hack where you have to spell out INZIDIUS

**Screenshots:**
https://gyazo.com/51fe61eb20b3299b254e63a053907696

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
