### ISSUE TITLE
Reduce Key Find Chances

### ISSUE THREAD

**Issue by W1lsonCodes** [InZidiuZ/legacy-assets-issue-tracker#171]
**Reporter:**
WilsonPlays#6969

**Summary:**
Decryption Keys are being found too quickly. Some say people are getting between 10-15 keys a day.
 Keys may need to have the chances of finding reduced to combat this issue as no w people are farming.
## Additional Information

**Screenshots:**
N/A

**Notes:**
Nothing To Add

**Comment by Imaghost1337** [comment]
+1

**Comment by RusuSergiu** [comment]
+1

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
