### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by RusuSergiu** [InZidiuZ/legacy-assets-issue-tracker#172]
**Reporter:**
Xellos#3869

**Summary:**
Items in appartment property-1453 keep returning to the apartment after a few minutes after taking them into my pockets. If i pick items from stash and take a soft nap they also go back to the stash.
## Additional Information

**Screenshots:**
https://www.youtube.com/watch?v=mEduYHDGQ4g&feature=youtu.be

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
