### ISSUE TITLE
Unpaid Finances

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/legacy-assets-issue-tracker#173]
**Reporter:**

Cricketx818

**Summary:**

So PDM Dealer has noticed a bug for quite a while now, So once somebody finances a car from PDM, and a Cop or I /checkplate The system detects the car has unpaid finances, right when they get the car out the dealership, The system forces, the owner to pay two payments once the car gets bought for them to be on top of the payments.

**Comment by Livius99** [comment]
Yup... Noticed that as well, it was when the server was whitelisted as well...

**Comment by InZidiuZ** [comment]
Hey,

This is the incorrect issue tracker. Please use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker) for non-asset related issues.

**InZidiuZ**
*OP-FW Developer*
