### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ItsStatic** [InZidiuZ/legacy-assets-issue-tracker#176]
**Reporter:**
Who is reporting this? Please include discord name.
Richard Gonzalez (ItsStatic#1377)
**Summary:**
Write a summary of what you're experiencing.
I got a supra and top speed stock was 175 i then upgraded it i did max engine max trans and added turbo and top speed is still 175 i stored it when i bought upgrades and i even took a hard nap and nothing works.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by TCruxer** [comment]
Hey, 

After review of the supra it does not seem to be capping at 175mph on my end after customizations. Try clearing your cache as it might solve the issue. 

Feel free to DM me and we can discuss about it if the problem still occurs.

**Cruxer  _Lead Asset Developer_**
