### ISSUE TITLE
Suggestion - Transforming the former "Los Santos Customs" shop in Paleto Bay, to a functional mechanic shop.

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#178]
**Name:**
AdeptCL#0402
Con#0053

**Summary:**
Transforming the former "Los Santos Customs" shop in Paleto Bay, to a functional mechanic shop.

**Link:**
Location of where the mechanic shop would in correspondence to Paleto Bay: https://imgur.com/a/QMdy4xC 
The store front: https://imgur.com/a/w2MMa33
Video of the pre-existing interior (identical to Lost MC shop): https://www.youtube.com/watch?v=UpPyu-NEYNs

**Reason:**
Paleto Bay is having more and more activity now that whitelisted groups are extending territory to outside of the main city of Los Santos. Currently, there are 4 mechanic shops. 3 of those are within the boundaries of the main city, and 1 being situated towards Sandy Shores. There is no mechanic shop past Sandy Shores.
As there are gangs now pushing up North, it would be really helpful to organisations and just the general pass-by if there was somewhere in which vehicles can be maintained.

Having this, would also enable those that have storylines being played up North rather than in the city to have an area which their vehicles can be serviced. This also brings more roleplay to be played up North, whether that be mechanical based, car show/racing based, etc.

**Comment by TCruxer** [comment]
Hey,

This is the wrong GitHub for this GitHub for this suggestion. Please use [the following](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose) issue/suggestion tracker.

**Cruxer   _Lead Assets Developer_**
