### ISSUE TITLE
Coke Plane Scuffage

### ISSUE THREAD

**Issue by samsn8** [InZidiuZ/legacy-assets-issue-tracker#179]
**Reporter:**
samsn#0666

**Summary:**
Every time I and a couple of others to run the plane our game crashes before we're able to take off on the airstrip. I've reinstalled fivem twice now and have cleared cache like 5-6 times and so have a few other people attempting to run the plane.

## Additional Information

**Screenshots:**
https://streamable.com/9s0l3m

**Notes:**
Sir i beggith of you to fix this as I am red mafia scum and it is how I make my money sir plz

**Comment by DaxterPancake** [comment]
Hi,

This is the incorrect place to post this issue. Please go [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) and post your issue there.
On that github you'll see that there is a lot more information that is needed, please try to fill in as much as you can.

Thank you,
Daxter.
**Project Manager.**
