### ISSUE TITLE
Police Charger Needs a buff or Bikes need a nerf

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/legacy-assets-issue-tracker#18]
Its a constant everyday thing when I'm having to chase a bike that's going 200+ mph on the highway or going fast in the streets and making insane turning radiuses. We as police can not pit a bike so the only thing we can do is wait for them to fall off it but that's so unlikely because of how good they are. The charger goes 173 max has a decent turn radius and brakes are decent too.

**Comment by Karpenkooo** [comment]
Hey @Aesfy 

I'm going to be closing this issue as you have not followed the bug-report template that you're meant to use and everyone else uses. Feel free to re-submit a bug-report using the provided template. 

_Karpenko_

_**OP-FW Vehicle Developer**_
