### ISSUE TITLE
FLASH GT ONLY 50 TRUNK STORAGE??!!

### ISSUE THREAD

**Issue by ABOW402** [InZidiuZ/legacy-assets-issue-tracker#181]
**Reporter:**
Roger Terrry. Discord - ABOW402#5662

**Summary:**
My flash gt used to store way more in the trunk, and now its as big as my glovebox. Only holds 50, not 500. Can this get fixed?

## Additional Information

**Screenshots:**
N/A

**Notes:**
I am wondering if this was intentional? Theres plenty of room for 500 storage just like my R32

**Comment by TCruxer** [comment]
Hey,

For the low trunk space please refer to the other issue tracker [over here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose) as this is not related to the asset but to the trunk script.

**Cruxer    _Lead Asset Developer_**
