### ISSUE TITLE
I think there is a bug in belt system in car

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/legacy-assets-issue-tracker#182]
**Reporter:**
Ppthegamer#7381

**Summary:**
In Rp today when i was driving car i put seatbelt then i pressed F to exit and my character came outside the car.     (Update 2.4)

In previous versions first we used to take off seat belt then character came outside.

## Additional Information
No additional information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by TCruxer** [comment]
Hey,

This issue is not related to the assets and rather to the belt script. I will therefore be closing this issue report. I invite to reopen it on the other issue tracker [right here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose).

**Cruxer   _Lead Asset Developer_**
