### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Boutton** [InZidiuZ/legacy-assets-issue-tracker#183]
Name:
@boutton#7433

Summary:
Would like an addition or an updated model for PD explorer(2020 Version) and also a suburban.

Link:
Suburban kinda something like this https://www.gta5-mods.com/vehicles/chevrolet-suburban-secret-service-add-on-wipers      (you can take flags off)

For the explorer i couldn't find a model but don't really know what im looking for

**Reason:**
I think it is time for an update on the model and also there a good addition to the pd vehicle for various scenarios.

**Comment by Lunar929292** [comment]
PD Vehicles are currently being looked at & buffed out, for now there is no suburban planned.
The explorer on the other hand is also being sorted :)..
