### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Terry-Crews** [InZidiuZ/legacy-assets-issue-tracker#184]
**Name:**
Xwezio#5716

**Summary:**
Exclusive car suggestion

**Link:**
https://www.gta5-mods.com/vehicles/mini-cooper-r56-jcw-gp-liberty-walk-add-on

**Reason:**
Unique Car and i have not really seen a standard car which has had some nice modifications in the exclusive dealership yet they all seem to be rare or exotic cars.

**Comment by AndersHSR** [comment]
We will take this suggestion into consideration and we will look on it
Closing for now.

**Asset Developer Anders**
