### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DC0402** [InZidiuZ/legacy-assets-issue-tracker#186]
**Reporter:**
DC#4176

**Summary:**
EMS Vehicle like (BMW 1200RT) and (FORD explorer) can't be repair,Getting down from the EMS chopper or police chopper leads to falling down in ground,Incorrect Movement of the Tracker of police and EMS.
![Screenshot (369)](https://user-images.githubusercontent.com/64458489/80455016-9ba2a680-8948-11ea-85db-5efa9715ff21.png)

## Additional Information
I'm a EMS in LEGACY sub division Bangladesh,i was facing such problems mentioned above,and i think it should be fixed soon.Thank You.
**Screenshots**
![Screenshot (366)](https://user-images.githubusercontent.com/64458489/80454509-ca6c4d00-8947-11ea-8400-26eaddcfacf0.png)
![Screenshot (364)](https://user-images.githubusercontent.com/64458489/80454742-246d1280-8948-11ea-98c2-c2b6a49a992c.png)
![Screenshot (368)](https://user-images.githubusercontent.com/64458489/80454765-318a0180-8948-11ea-8cdd-58dda9becf75.png)

**Notes:**
Facing problem with this things,I know it will be fixed soon.

**Comment by Splash004** [comment]
Yeah. I am also facing the same problems. I cant repair the BMW RT and also Ford Explorer. Exiting the chopper on the grounds leads to a fall and damage. Trackers are not  working as they should be.  We need a quick fix for this.....

**Comment by BmFarhan** [comment]
Everyone facing the same problem . its now like so difficult for us to play freely hope fix soon . also facing head light issue in the vehicle . after spawning a vehicle the headlights turn off auto , and can't turn on later .

**Comment by TCruxer** [comment]
Hey,

Regarding the /repair on emergency vehicles not working this should be fixed shortly as this was an error on our end. For the helicopter, I'm not sure just yet what is causing this issue and will be investigated further.

As for the trackers, this is not related to the assets and therefore needs to be redirected to the proper issue tracker [right here](https://github.com/InZidiuZ/op-framework-issue-tracker). Feel free to submit a report about it on that issue tracker.

**Cruxer _Lead Assets Developer_**

**Comment by AndersHSR** [comment]
Hey There Again!
Both the Explorer and BMW has been fixed,
regarding the helicopter issue, it's not something that we can help you with.
The Model is the standard one from GTA, so its either a Hospital interior issue, that causes 
the Game think you are in air, or an overall GTA Issue.

**Anders** _**Asset Developer**_
