### ISSUE TITLE
Suggestion (motorcycle buff for “cruisers”

### ISSUE THREAD

**Issue by JC-5** [InZidiuZ/legacy-assets-issue-tracker#187]
**Name:**
Who is suggesting this? Please include discord name.
J.C.#6959
**Summary:**
Write a short summary of what your suggestion is about.
I feel like the cruiser style motorcycles are very under powered or at least some of them. I own the Western zombie chopper and the top speed with engine upgrades is 115 I also own the night blade and the top speed is about 120. I don’t think a major buff is needed but if they hit about 135-140 I feel like they would feel a lot better. Also the first gear acceleration is pretty rough as well. I can’t speak for sport bikes but from I heard they’re pretty fast. This suggestion is just for the “cruiser” style. 
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
I feel like it would balance them a bit. Hardly anyone is going to rob anything on this type of bike especially when it’s fairly easy to get a car to hit 160-190, or when a sport bike for about 5k more can hit some pretty nutty speeds.

**Comment by AndersHSR** [comment]
Motorbikes will be looked at in near future!
Thanks for suggestion.

**Anders, Asset Developer**
