### ISSUE TITLE
Suggestion on buffing the SultanRS slightly

### ISSUE THREAD

**Issue by RandomKilled** [InZidiuZ/legacy-assets-issue-tracker#188]
**Name:**
RandomKilled#0300
**Summary:**
Currently the sultan has been nerfed to the point where cheaper and regular sports car are able to keep up with it. As a super car which cost 200k or 250k if paid by finance it should be way better than any of the regular sports car and be back on par with the super cars. 

**Link:**
N/A

**Reason:**
This isnt asking to buff it back to what it was, just that the nerf was so much that it doesnt even feel like a sultan RS anymore. I believe that reason it got nerfed cause people were abusing its speed for bank robberies but its unfair for those who never did so. Again not asking it to be super fast again just slightly faster

**Comment by AndersHSR** [comment]
Tweaks have happend after another review. 
**Anders** _**Asset Developer**_
