### ISSUE TITLE
Suggestion for Fight Night Arena

### ISSUE THREAD

**Issue by Cyniah** [InZidiuZ/legacy-assets-issue-tracker#189]
**Name:**
Known as Cyniah Reid in the city.
Jenny#1862

**Summary:**
In the city, myself and two others run a fight night every week and we are looking to bring in a fighting ring to help make it more professional.

**Link:**
Possibly something like this...
https://www.gta5-mods.com/maps/gta-iv-fight-club-interior-sp-fivem
or...
https://www.gta5-mods.com/maps/fight-club-ymap
or...
https://www.gta5-mods.com/maps/nightclub-fightclub-ymap
I prefer the first one but the others are pretty cool too. Whichever works better is fine with me thank you!

**Reason:**
In the city, myself and two others currently run a weekly event. This event is a weekly fight night that is hosted in the evening, usually, once a week on behalf of Rooftop Mayhem and Tequi La La. Fight night is an event that I believe a majority of the city enjoys as it gives people something to do and something a lot of people look forward to. Each fighter has a chance of winning a large cash prize.  As of right now, we do not have a set location for the fight night. We have been using places around the city but I believe it would be a great asset to the city if we had an actual fighting ring. Bringing in a ring into the city will allow for better roleplay with the fight nights and can be seen as more of a professional event rather than hosting it in places that aren't necessarily fit for the fight. I also believe that with the proper fighting ring, it will be safer for the audience and the people we have working for us. The ring with the night club would be interesting as I could push more events other than just a fight night which may also bring more to the city. Thank you!

**Comment by TCruxer** [comment]
Hey,
There might be something like this coming in the near future. I am not the one working on it. There isn't a due date just yet but I'm sure you will enjoy it when and if it does come. I will, therefore, be closing this for now.

**Cruxer Lead Asset Developer**
