### ISSUE TITLE
Can't take Ferrari 488 Out of Garage D

### ISSUE THREAD

**Issue by PhizioN** [InZidiuZ/legacy-assets-issue-tracker#19]
**Reporter:**
PhizioN#4462

**Summary:**
I bought the Ferrari 488 from the exclusive dealership, fully upgraded it, and stored it in Garage D. After I tried to take it out, I noticed that nothing happened. It says that it's there, but is just unresponsive upon selection.

**Steps to Reproduce:**
Buy a Ferrari 488 from the exclusive dealership, upgrade it fully from LS customs, then take it directly to Garage D and store it. Then try to take it back out.

**Expected Results:**
That you will not be able to take it out.

**Actual Results:**
Nothing happens when I select my car and try to take it out, even though it says that its in.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 223

**Notes:**
For anything else noteworthy.

I don't think this has anything to do with the garage, because I watched someone store a tow truck and take it back out of the same garage, so maybe this has more to do with the actual car? Thanks for your time.

**Comment by Karpenkooo** [comment]
Hey

Would you be able to get screenshots of your console as you take the 488 out?

**Comment by PhizioN** [comment]
![SS of F8](https://user-images.githubusercontent.com/50087643/62305977-f9a06d00-b44e-11e9-80f9-765819bc87af.jpg)

[Video of problem and Console.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/3457461/Video.of.problem.and.Console.zip)

**Comment by PhizioN** [comment]
![Console](https://user-images.githubusercontent.com/50087643/62306350-b5fa3300-b44f-11e9-9102-47dd876df599.jpg)

[Video of problem and Console.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/3457476/Video.of.problem.and.Console.zip)

**Comment by Karpenkooo** [comment]
Should be fixed now, Thanks to @InZidiuZ <3
