### ISSUE TITLE
Suggestion about opening Sandy Shores Medical center

### ISSUE THREAD

**Issue by amixubaer** [InZidiuZ/legacy-assets-issue-tracker#190]
**Name:**
Jubi#5059

**Summary:**
Sandy Shores Medical Center can be opened

**Link:**
https://gta.fandom.com/wiki/Sandy_Shores_Medical_Center

**Reason:**
Currently there are only one medical center which is pillbox. If any people is injured in the northern part he has to travel a long way. If he calls for ems they also need a good amount of time to respond there. If there is no Heli unit available then it becomes more hard. currently the city slots are also increased. more people means more injury and it needs more ems to serve them. In a big country only one medical center exists it's very disappointing, You recently opened the BCSO Headquarter. The citizens of northern part needs some medical help too. If  you open the medical center the peoples will get help. Not only that no ems will sit without work. Again you can increase the capacity of EMS team as more people will get job. You can also transfer the doctors as their service . All other medical centers(currently off in our cities) are close to the pillbox and it covers the southern part very easily But for the northern part(Paleto,sandy shores etc.) we need one more Medical Center.

**Comment by AndersHSR** [comment]
Outdated.

**Asset Developer** _**Anders**_
