### ISSUE TITLE
R34 Skyline catches on fire instantly

### ISSUE THREAD

**Issue by iNubby** [InZidiuZ/legacy-assets-issue-tracker#191]
I've had this car for a while but I don't drive it anymore due to the fact that after maybe 2-4 crashes, it starts smoking and then catches on fire. There is one other R34 in the city, and the owner of it has told me even with full armor, it still is the exact same. So the armor in the customs is broken as well on it.

**Comment by AndersHSR** [comment]
Please use the Template.

**Anders, Asset Developer**
