### ISSUE TITLE
No Trunk Audi SQ7

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/legacy-assets-issue-tracker#192]
**Reporter:**
Lars.#0181

**Summary:**
The Audi SQ7's trunk is not accessible, i thought it was because their wasn't an actual trunk in the back in the vehicle but actually their is. I placed the car on a ledge so the angle with the car would change and i was able to access the trunk. Would it be possible to re-position the trunk so it can be reached normally? See screenshots for more info.

## Additional Information

**Screenshots:**
https://i.imgur.com/5klTSWZ.jpg
https://i.imgur.com/KWXmAwV.jpg

**Notes:**
For anything else noteworthy.

**Comment by AndersHSR** [comment]
Outdated.

**Asset Developer** _**Anders**_
