### ISSUE TITLE
R34 Skyline has really low health

### ISSUE THREAD

**Issue by iNubby** [InZidiuZ/legacy-assets-issue-tracker#193]
**Reporter:** 
xNub#9251

**Summary:**
I've had this car for a while but I don't drive it anymore due to the fact that after maybe 2-4 crashes, it starts smoking and then catches on fire. There is one other R34 in the city, and the owner of it has told me even with full armor, it still is the exact same. So the armor in the customs is broken as well on it.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
https://streamable.com/r7snin
In this video, my R34 Skyline is 100% engine and 100% body. I hit it into the wall going somewhat fast, and after 3 hits, it catches on fire.

**Comment by AndersHSR** [comment]
Hey There!
Issue has been resolved, Thanks for Reporting.
Remember! Fix is not yet implemented on Live servers, we need to wait a server update afterall.

**Anders, Asset Developer**

**Comment by Masik52** [comment]
Yay another rocket ship tank incoming. IMO cars with high speeds an acceleration should not be able to take a lot of damage before beginning to break down. there is simply zero penalty to driving them.
