### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Sajib201** [InZidiuZ/legacy-assets-issue-tracker#194]
**Sajib_322#5850**

Legacy BANGLADESH is now getting so popular.It becomes a top server in bangladesh.
Since there is no payment option for bangladeshi people. It named a bangladeshi server. But there is a great lakency of Payment option.
We on behalf of bangladeshi player, wants a bkash payment option. and a weekly membership option.
I thing it'll support your team and we enjoy a premium service from you.

If my suggation is wrong pls pardon me.
But I must say there is a shortage service for bangladeshi player.
thank you

**Reason:**
Because,I cant pay with your payment service.
I want a easiest and more comfortable way.
And must a weekly pack too.

**Comment by InZidiuZ** [comment]
This is not related to the framework's assets. Please use the OP-FW's or your own community's discord for other matters.
