### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/legacy-assets-issue-tracker#196]
**Reporter:**
Matt;)#7784

**Summary:**
A part of a building located underwater at the Sunken Ship is broken and you can walk through it. 

## Additional Information
Once inside, if you don't know what happened, it would be hard to understand how to come back out.

**Screenshots:**
Below are screenshots of the building with indication as to which part of it is broken!
Building: https://prnt.sc/srvwaf
Myself clipping through the building: https://prnt.sc/srvwvf
Inside the building: https://prnt.sc/srvy21

**Comment by InZidiuZ** [comment]
As this is a GTA issue, this will not be resolved at this time.
