### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DrCrazyBD** [InZidiuZ/legacy-assets-issue-tracker#197]
**Reporter: DrCrazyBD**
discord name: DrCrazyBD#7184

**Summary:**
hello i have e bike in the city After i lock my bike the lights don't work i have change the light's but same problem Bike Name : Shitzu , Hakuchou drag, motorcycles

**Comment by InZidiuZ** [comment]
This is not an issue related to the assets themselves. The issue you're referring to has also already been resolved, the fix has just not yet been pushed to the live servers.
