### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Yusuf0007** [InZidiuZ/legacy-assets-issue-tracker#198]
**Name:**
@𝕐𝕦𝕤𝕦𝕗#3211

**Summary:**
It is about new role related state.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
I am suggesting a new role which is related to state named as State Security. Every country Mayor have their own security service like agents or Detective which is most likely separate from police job and not related with the DOJ worker. I have been working as a state security of LEgacy Bangladesh Mayor. Whenever the Mayor arrived in the city me along with my team have to be active about his security. Which bring more rp towards the mayor as well. But the security worker does not have their own role to work and do not have powers such as cuffing someone or normally impounding vehicle which are blocking the mayors path. I would suggest to bring a role with some power for state security to bring more rp for a Mayor will be good. I thing I can not make you understand through this github but think about it carefully if possible and you will understand the importance of these role as well.

**Comment by InZidiuZ** [comment]
This is in no way related to assets
