### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by PsychoGrandpa** [InZidiuZ/legacy-assets-issue-tracker#199]
**Reporter:**
IGN: Rakeen Rahman, Discord: PsychoGrandpa#8936

**Summary:**
While working as a garbage collector, I face problem accessing dustbins beside weazel news building. 

## Additional Information
There ia a bunch if dust bins which are enclosed by fence and cannot be accessed if not climbed the roofs. If you even get inside you wont be able to come out. 

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Not an issue related to assets
