### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kristoffermyr** [InZidiuZ/legacy-assets-issue-tracker#2]
**Name:**
Who is suggesting this? Please include discord name.
Kristoffer#9080

**Summary:**
Write a short summary of what your suggestion is about.
Make the Toyota Supra sound like a Toyota supra (if possible)
And doing it to more vehicles make special sounds 

**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/vehicles/new-engine-and-blow-off-sound-for-toyota-supra
**Reason:**
Why would your suggestion be a good addition to Legacy?
Because it would make a little variety in the vehicle sounds not every vehicle sounds the same

**Comment by RGDaviid** [comment]
Hey @Kristoffermyr ,

This sound mod is pretty cool however it's a client sided mod. Meaning that we can't stream it to the server. However you can add it to your own game files and then you will be able to hear a difference. Thank You for your suggestion however i can't add it to the server. I'm now going to close this suggestion.

**Karpenko**

**_OP-FW Car Developer_**
