### ISSUE TITLE
Mustang GT500 Secondary Colour

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/legacy-assets-issue-tracker#20]
**Reporter:**
Duroode - (Duroode#2178)

**Summary:**
When i go to change the secondary colour for the Mustang it changes the Wheel rims.

**Screenshots:**
https://gyazo.com/760a8048db03b2295f3a6cac476304ea

**Notes:**
Not 100% sure if its intended or not but i feel the secondary colour should change the stripe instead of always needing to have it blue.

**Comment by Karpenkooo** [comment]
Hey @Duroode 

I agree with you that the secondary colour should be used to change the colour of the stripes. However this is down to the mod author and not me. Unfortunately i'm not able to edit his work. I will however look into it a bit more and try to find a work around. 

_Karpenko_
