### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PsychoGrandpa** [InZidiuZ/legacy-assets-issue-tracker#200]
**Name:**
Who is suggesting this? Please include discord name.
PsychoGrandpa#8936
**Summary:**
Write a short summary of what your suggestion is about.
There is a car named Jester which is a replica of Toyota Supra. I would kindly request you to replace that jester with an original supra. 
**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/vehicles/toyota-supra-jza80

**Reason:**
Why would your suggestion be a good addition to Legacy?
Many people are love jdm cars. But they love the supra most. When they get to have one they realise this particular car has rectangle headlights awkwardly shaped taillight housing. This addition may not be much helpful but many of us will love this so why not! 😊

**Comment by Doughnut2001** [comment]
we've already got real cars, they're imports meaning that you have to be a donator to be able to buy them, i think that the import specs are the same as their equivalent GTA car so there's not much difference. and there already is a supra there.

**Comment by AndersHSR** [comment]
Will be taken into consideration as import, although we will surely not replace an In-Game model.

**Asset Developer** _**Anders**_
