### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Imaghost1337** [InZidiuZ/legacy-assets-issue-tracker#201]
**Reporter:**
gHo$T#0188

**Summary:**
All shots were taken around 1 meter away from the car bonnets with a PD rifle using rifle bullets

Crown Vic                                  - smoke at 180, fire at 240.
Ford F150                                 - no smoke, no fire after +600 bullets
Ford Interceptor                       - smoke at 18, fire at 27
2016 Explorer                          - smoke at 120, fire at 205
2014 Charger                          - smoke at 135, fire at 235
BMW 1200 RT                          - not gonna test a bike, fucc them
Tahoe                                       - smoke at 230, no fire after 600+ bullets
2018 Charger                          - smoke at 170, fire at 260
2017 Silverdo                          - can't open the bonnet :/
2018 Camaro ZL1                    - nothing after 600+ bullets

## Additional Information
 
**Screenshots:**
-

**Notes:**
For anything else noteworthy.

**Comment by AndersHSR** [comment]
Police Fleet is to-be updated.

**Asset Developer** _**Anders**_
