### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JC-5** [InZidiuZ/legacy-assets-issue-tracker#202]
**Reporter:**
Who is reporting this? Please include discord name.
JC5#6959
**Summary:**
Write a summary of what you're experiencing.
Bought the harley chopper from EDM and I did not receive the bike and it took the money, There were no errors in the f8 console 
## Additional Information
I have a video but it wont let me get a link from the nvidia 
**Screenshots:**
If suitable, include some screenshots.
I can get screenshots if needed but I think its pretty cut and dry what happened lol 
**Notes:**
For anything else noteworthy.
I dont know if all vehicles are messing up or just the chopper, asked around to see if anyone else bought anything from there and all the people i asked said they didnt know of anyone

**Comment by AndersHSR** [comment]
Did it occur aswell on live servers?

**Comment by jethiya** [comment]
The vehicle usually get transferred into your garage. In this case try retrieving it from the nearest available garage.

**Comment by InZidiuZ** [comment]
This is not related to assets. Use the issue tracker related to scripting & UIs.
