### ISSUE TITLE
Facing UI Problem [Indian Sub-Division]

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/legacy-assets-issue-tracker#203]
**Reporter:**
Who is reporting this? Please include discord name.
ppthegamer#7381

**Summary:**
Character selection overlay issue while on main menu 

## Additional Information
Screen Resolution 1366 x 768

**Screenshots:**
![20200628232159_1](https://user-images.githubusercontent.com/63738935/85978342-26ad2500-b9fc-11ea-8640-094a540431ed.jpg)

![20200628232202_1](https://user-images.githubusercontent.com/63738935/85978339-24e36180-b9fc-11ea-9297-b975d380f263.jpg)

**Notes:**
For anything else noteworthy.

**Comment by AndersHSR** [comment]
Wrong section, report it here instead: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Asset Developer** _**Anders**_
