### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Xwezio** [InZidiuZ/legacy-assets-issue-tracker#204]
**Name:**
Xwezio#5716

**Summary:**
New interior of the ranch on senora road 

**Link:**
https://www.gta5-mods.com/maps/beta-parts-of-madrazo-ranch-rancho-room-with-safe-from-beta

**Reason:**
Because myself think its a great place to have meeting and host events, The current one is very buggy with the collisions not very accurate and invisible barriers.

The link above fixes the collision issues and also adds some new furniture to the rooms.

**Comment by CaptainVro** [comment]
+1

**Comment by AndersHSR** [comment]
Will be added into consideration list, Thanks.

**Asset Developer** _**Anders**_
