### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Xwezio** [InZidiuZ/legacy-assets-issue-tracker#206]
**Reporter:**
Xwezio#5716

**Summary:**
Maserati Lavante Super soft suspension, no trunk, broken Back Passenger doors or usable space and slow.

## Additional Information
https://medal.tv/clips/27634523/0eD6UpcC6cZn
https://www.youtube.com/watch?v=D0-SFuVibF4
**Screenshots:**
If suitable, include some screenshots.

**Notes:**
I believe an 80k car should have a trunk with usable storage and also have a little faster acceleration and also the real lavante hits 145mph-185mph in real life i believe this should somewhat be resembled.  

Maybe this could be used as a replacement if these things can not be fixed
https://www.gta5-mods.com/vehicles/maserati-levante-mansory-add-on

**Comment by AndersHSR** [comment]
We are aware of the issue, Thanks anyway.

**Asset Developer** _**Anders**_
