### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by arafat0951** [InZidiuZ/legacy-assets-issue-tracker#207]
**Reporter:**
Yasin Arafat? Alfa々MAS#1957
EMAIL
arafat0951@gmail.com

**Summary:**
Issues With Car Like gari Running Obostai gayeb hoye jai, parking a thake na, store, Retrive, kora shob jaigai glitch hoi.

ANd another one is House robery i don't get any thing from some houses like nothing. 

## Additional Information
 no
**Screenshots:**
no I dont have

**Notes:**
 no

**Comment by AndersHSR** [comment]
Unable to understand what you mean, could you please try to explain further? Use Google Translator if required, noone will be mad about it.

**Comment by InZidiuZ** [comment]
Recreate your issue in English
