### ISSUE TITLE
All the edm vehicles are too underpowered.

### ISSUE THREAD

**Issue by manikgoyal04** [InZidiuZ/legacy-assets-issue-tracker#208]
BlueMoon#0135

Summary
EDM vehicles are too underpowered and overpriced now so that there's no point in buying those vehicles and pdm vehicle or more powerful than them! For example mercedes c63-s top speed is like 150 only on straight road, that's not enough at all like if you would take an example of bmw f82 its top speed was like 200 on a straight road, and Livery walk nissan gtr is also too underpowered compared to the old bmw i8 both price was almost same and performance difference was too big! I think some work should be done on the edm vehicles and you should make them more balanced! Like mercedes c63 s amg should easily go like 190 on stock and at straight road.
And Aston Martin db11 should easily go upto like 220 because that car costs 2 lakh and according to what I heard it's top speed is 180 only so that's not enough at all please make edm vehicles more powerful.
Reason:
if edm vehicles are not even good in performance like they used to be then there's no point in buying them people can easily buy pdm vehicles instead of edm vehicles and they don't need to spend money on priority also.

**Comment by AndersHSR** [comment]
1. Use the template properly.
2. Handlings were changed in terms of speed.

**Asset Developer** _***Anders***_

**Comment by manikgoyal04** [comment]
But still the handling of mercedes is not that good bruh in real life mercedes goes much faster and it goes 150mph only doesn't make sense to me because nissan skyline can easily go like 185 stock on straight road before
