### ISSUE TITLE
Pegassi Toros

### ISSUE THREAD

**Issue by samimenad** [InZidiuZ/legacy-assets-issue-tracker#209]
**Reporter:**
Sami
SAMI#3378

**Summary:**
The Pegassi Toros has no trunk, you are able to store things within it's trunk however you cannot open the door nor can you carry and place people into the trunk. The SUV clearly has ample truck space.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by AndersHSR** [comment]
Will be looked at.

**Asset Developer** _**Anders**_
