### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by henryvolk** [InZidiuZ/legacy-assets-issue-tracker#21]
**Reporter:**
Who is reporting this? Please include discord name.

**Summary:**
I bought a $20 patreon just for the evo 9 and it is so slow, it caps out at 135 mph even when i spent $25k in upgrades, also the car seems to be RWD when it should be AWD. Evo9 fully kitted are one of the craziest cars out there and i believe this should be able to hit 200MPH with no upgrades

**Comment by Karpenkooo** [comment]
Hey,

So first of all i'd like the say that the Evo IX MR is AWD on this server. (Take another look).
The Evo IX MR also has a stated top speed of 155 mph. So for that reason i'm not going to set its stock speed to 200 mph. In Terms of the speed cap i'll take a closer look at that and maybe raise it if it's incorrect.

**Comment by Karpenkooo** [comment]
Hey @henryvolk 

So i decreased the "LowSpeedTractionLoss" meaning that you'll feel the AWD grip a little more on launch. i also bumped the top speed to a more realistic speed & upgrades should now be working properly. 

_Karpenko_

**_OP-FW Vehicle Developer_**
