### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/legacy-assets-issue-tracker#210]
**Name:**
Who is suggesting this? 
Jethiya#0941

**Summary:**
Need a shop inside pillbox (same as the pd has one ) where we can shop the essentials rather than travelling all the way up to the grocery store. 

**Link:**

**Reason:**
It would save time which could be then used to treat patients or attend calls.

**Comment by Livius99** [comment]
Everyone liked that

**Comment by InZidiuZ** [comment]
This is not related to assets. Use the issue tracker related to scripting & UIs.
