### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SmoggyRaptor** [InZidiuZ/legacy-assets-issue-tracker#211]
**Reporter:**
SmoggyRaptor#4329.

**Summary:**
Tuner Chips seem to affect the car in no way. I have tried it on different car types as well. The UI itself is so messed up that it gives the message loud and clear that it is not going to work.

## Additional Information

**Screenshots:**
https://imgur.com/56GEpjL

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Use the issue tracker related to scripts & UIs.
