### ISSUE TITLE
An Idea eh?

### ISSUE THREAD

**Issue by HuhCjay** [InZidiuZ/legacy-assets-issue-tracker#212]
**Name:**
Who is suggesting this? Please include discord name.
HuhCjay#2888

**Summary:**
Write a short summary of what your suggestion is about.
I am in a "Mafia" and I do not even have a m1928 to flex with or otherwise known as a Thompson Sub machine gun. Its not really a big thing or anything. Its already in the GTA V files and stuff so I am kinda confused why it never came around when gun crates came around, I mean I wouldn't mind if there also was a special way only "mafia's" could get it either but best case just have it in the crates. It could literally be the worst preforming gun I just want it for the mafia RP

**Link:**
If there are any links to what you're suggesting, please add them here.
No

**Reason:**
Why would your suggestion be a good addition to Legacy?
I think it would make for a small extra little detail of RP its all the small things that make some RP great huh? As stated I have no interest in it being a OP gun I just want to look sick with the gang and create a decently nice story-line that fits that old school mafia-oso ya heard?

**Comment by RusuSergiu** [comment]
+1

**Comment by AndersHSR** [comment]
Taken Into consideration

**Asset Developer** _**Anders**_
