### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BigFugginBrain** [InZidiuZ/legacy-assets-issue-tracker#213]
Reporter:
Big Brain#1958

Summary:
I bought the shitzu bike a few days ago and have since consistently had alot of issues with it getting stuck inside the ground as well as not letting me store it, is this a normal occurrence or is that bike just scuffed?  I have heard of issues with vehicles not storing in the garage but they seem fairly infrequent, unfortunately I do not have any screenshots of the bike stuck in the ground but it has happened every time I have tried to flip the bike if that is helpful.

**Comment by AndersHSR** [comment]
Please use Legacy framework issue tracker regarding errors with garage etc.
This is a vanilla model, so not much we, as asset devs can do about it, although I'll try my best on our end.

**Asset Developer** _**Anders**_
