### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by IrishRonan** [InZidiuZ/legacy-assets-issue-tracker#214]
**Name:**
IrishRonan#5797 / Rocky Rackoon in city
**Summary:**
This isn't a suggestion but more of a balance fix, i'm wondering if i could try and get the Dinka Jester Classic (Custom) buffed a bit. The car is 65k and classed as a sports car. With all engine and speed upgrades it maxes out at 160mph. Most of the 40-50k cars can get this speed and also get a bit above it. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
I just feel like since the car is a lot more expensive it should at least be a bit faster (maybe max it at 180). I'm planning on racing in it so i'd like for it to be able to outspeed the cars that are 20k less than what i paid. Nobody is going to buy it if it's in it's current state, there's not reason to

**Comment by IrishRonan** [comment]
160 is actually a stretch, on the highway  i max out at like 150

**Comment by AndersHSR** [comment]
Will be looked at.

**Asset Developer** _**Anders**_
