### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by deartsylens** [InZidiuZ/legacy-assets-issue-tracker#215]
**Reporter:**
discord : NINJA#2653
steam : Ninja

**Summary:**
my car INFERNUS CLASSIC is not going more than 130 mph as compared to cars like jester classic which are half way cheaper and they go 140+ mph on stock engine. my car cost about 1.2 lakhs but when i tested on stock it went up to 130 and when i upgraded its engine and acceleration then also there is no change. i guess it should go up to 190 mph easily according to its price and other stats. maybe this is with other cars too which i dont know but when i tested jester classic it was much faster lol.

## Additional Information
test1 : just take a infernus classic and make it run on freeway
test 2: upgrade its engine to lvl 4 i.e max and acceleration to race transmission

Expected Results:
stock speed should reach upto 160-170 mph and upgraded should be atleast 190 to max 200 at that price

Actual Results:
reaching only 125-130mph on stock and upgraded one is going 128-130mph(there is no increase in speed approximately)
**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
I've already answered this is the other github but I will say it again.

People were abusing the fact that you cannot shoot into the back of an Infernus but can shoot out of it. Hence why it was nerfed. To stop people doing that.

**Comment by deartsylens** [comment]
> I've already answered this is the other github but I will say it again.
> 
> People were abusing the fact that you cannot shoot into the back of an Infernus but can shoot out of it. Hence why it was nerfed. To stop people doing that.

ifirst its not infernus , i am talking about infernus classic and second inzidiuz dropped a comment to report that issue in this assets issue tracker and by the way now the recoil system is good while shooting from inside that at higher speeds its impossible to shoot accurately

**Comment by DaxterPancake** [comment]
They both have the same issue with the back window.

The speed has been increased slightly and you will see these changes in the next update. 

Cheers.
Daxter.
Project Manager.

**Comment by deartsylens** [comment]
> They both have the same issue with the back window.
> 
> The speed has been increased slightly and you will see these changes in the next update.
> 
> Cheers.
> Daxter.
> Project Manager.

alright thanks
