### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/legacy-assets-issue-tracker#216]
**Reporter:**
Who is reporting this? Please include the discord name.
KaiEagle🦅#8283

**Summary:**
Write a summary of what you're experiencing.
This T-shirt is bugged for a male character when we pick this T-shirt & close the clothing menu then it will change to the next clothing. For female characters, it's working all good.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://vimeo.com/438458995

**Comment by KaiEagle** [comment]
Oops forgot to mention that it's bugged both on live & test server...

**Comment by AndersHSR** [comment]
Locking. Reason private.
