### ISSUE TITLE
Tuner Chip

### ISSUE THREAD

**Issue by JFEAndrews** [InZidiuZ/legacy-assets-issue-tracker#217]
Seems as the Tuner Chip like interface is a little scuffed....Idk if it has anything to do with the pocket issues or not....I will provide a picture when I get one.

**Comment by DaxterPancake** [comment]
This issue has already been posted on the other issue tracker.

I will close this for now.

Please go [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/873) if you wish to add your images to the original post.
