### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Artyxoxo** [InZidiuZ/legacy-assets-issue-tracker#218]
Legacy City user Sky Baxy
Discord: Artyx#9410

I bought myself a Supersport Car called Ocelot XA-21. The car coloration u can buy it in, had a gray & red outside. It was the ONLY car with a RED INSIDE. After i bought it and stored it, the red color was gone from the inside. It changed to a Gray inside. 
I would love to have a Red inside back, because this is how i bought it, and why i bought it in that pesific color. 

## Additional Information

![Car inside 0 1](https://user-images.githubusercontent.com/68968611/88842394-b1da3000-d1df-11ea-87c8-e736cf270ee1.PNG)
![Car inside 0 2](https://user-images.githubusercontent.com/68968611/88842416-bacb0180-d1df-11ea-94a7-07519a78dcb5.PNG)

I hope you can do something about it. Thank u for taking your time reading it.

**Comment by z-Lunar** [comment]
Currently there is nothing that can be done about the interior color of cars from an asset standpoint...the only hope will be when LS Customs is rewritten from a Script/UI Standpoint.  https://github.com/InZidiuZ/op-framework-issue-tracker/issues ~Lunar
