### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/legacy-assets-issue-tracker#22]
**Reporter:**
ST-412 Ethan Banks | Doughnut#1718

**Summary:**
Whenever I'm in a chase it will go on forever because the system where cars break down doesn't work anymore, it's replaced by the vanilla GTA V system and I've had multiple chases where at the end the car blows up killing the suspect and ems not being able to revive him.

## Additional Information

None

**Screenshots:**

None

**Notes:**

I'd hope for you to bring back the old system because mechanics don't have a purpose aside from visual anymore too

**Comment by Karpenkooo** [comment]
Hey,

That's not for my area. That's for @InZidiuZ . However i'd suggest getting some sort of videos along with it.

_Karpenko_

_**OP-FW Developer**_
