### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Pearypens** [InZidiuZ/legacy-assets-issue-tracker#220]
**Reporter:**
PearyPens#5427.

**Summary:**
F-450 ambulance lights are broken.

## Additional Information
They are too bright and people complain about them
![Annotation 2020-08-06 005232](https://user-images.githubusercontent.com/69289575/89492243-26344680-d77f-11ea-8b39-9194cf75e2cd.png)

**Screenshots:**
If suitable, include some screenshots.

**Notes
![Annotation 2020-08-06 005404](https://user-images.githubusercontent.com/69289575/89492331-5d0a5c80-d77f-11ea-96cd-7cce679ed544.png)
![Annotation 2020-08-06 005437](https://user-images.githubusercontent.com/69289575/89492355-6d223c00-d77f-11ea-924f-149f6a41e29f.png)

.

**Comment by z-Lunar** [comment]
Thank you for this report, looking into this now :)

**Comment by Pearypens** [comment]
:) ok

**Comment by z-Lunar** [comment]
This has been resolved, Thanks Again!
