### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by RyanShlap** [InZidiuZ/legacy-assets-issue-tracker#221]
**Reporter:**
Who is reporting this? Ryan SHlap#0477

**Summary:**
Ever since trains have been implemented around the server my frames have been so bad. I used to average around 120-130 fps in the city now I struggle to reach them numbers. If I'm around Davis area or legion/alta street or mission row my frames are so bad and I literally lag everywhere. I've asked a few people have the been getting the same issue and they can confirm it. But if I leave those areas my game would be fine. If I went sandy, or even the docks in the city or the airport I would be totally fine. 

## Additional Information

**Screenshots:**
I don't have one rn but I can grab a couple of clips later. 

**Notes:**
I used to stream everything I was doing on legacy but rn with the current state I can't stream because the frames are so toxic it wouldn't be a stream at all.

**Comment by z-Lunar** [comment]
Do you use any texture packs?

**Comment by RyanShlap** [comment]
Nope. I genuinely don't. I did have some for a test last week before the update and I removed them because I lost some frames but currently I'm running a base FiveM with no texture packs.

**Comment by RyanShlap** [comment]
@z-Lunar So I had to tone down my graphics to medium everything for the lag to stop. So I think the trains etc and mission row pd may be taking up some texture resources. But for my I can close this but for other people I'm not to sure.

**Comment by z-Lunar** [comment]
> t

Ok, Definitely taking MRPD into consideration as its not the first we've heard of it.
