### ISSUE TITLE
Game crashes when sending a text

### ISSUE THREAD

**Issue by BigFugginBrain** [InZidiuZ/legacy-assets-issue-tracker#222]
**Reporter:**
Big Brain #1958

**Summary:**
Any time I attempt to send a text through the phone in game it immediately freezes and winds up crashing. I have tried clearing the cache and that did not help.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Wrong issue tracker
