### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Pearypens** [InZidiuZ/legacy-assets-issue-tracker#224]
**Reporter:**
Who is reporting this? Please include discord name.
I fell through at the street next to the ammunation and bank near legion

**Summary:**
Write a summary of what you're experiencing.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Follow the template
