### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Pearypens** [InZidiuZ/legacy-assets-issue-tracker#225]
**Name:**
PearyPens#5427

**Summary:**
More diving spots or change them every now and then and have higher risk areas with better loot but more danger like sharks or something 

**Link:**
   N/A

**Reason:**
It would be a good addition to the diversity and wouldn't be the same thing over and over when diving

**Comment by z-Lunar** [comment]
This would be directly related to the Framework not Assets. [https://github.com/InZidiuZ/op-framework-issue-tracker/issues](url)
