### ISSUE TITLE
Suggestion Evo X handling

### ISSUE THREAD

**Issue by MarioGigante** [InZidiuZ/legacy-assets-issue-tracker#23]
Who is suggesting this? Please include discord name.
dnk | Mario Gigante#0874
**Summary:**
Write a short summary of what your suggestion is about.
I bought my Mitsubishi Evo X and the handling gotta be worked on a little bit. The car flips like nothing. And im not sure if that can be changed, The only thing i can change on that car is spoiler and skirts !
**Reason:**
Why would your suggestion be a good addition to Legacy?
Because i would like to get my car fixed a little bit :D eheh

**Comment by SATIN187** [comment]
hey just a heads up the mods on the car i believe are what only the creator of the mod put in, if that is the case then it would be up tot the creator to add in more options to customization. Karp would be able to correct me if im wrong

**Comment by Karpenkooo** [comment]
Hey,

So in terms of customisation @SATIN187  is correct in saying that it's up to the mod author. However the handling has been reworked recently and should hopefully come out with the next update.

_Karpenko_

**_OP-FW Vehicle Developer_**
