### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by babanthelegend** [InZidiuZ/legacy-assets-issue-tracker#230]
Please update the Ammunition shop's shooting range,provide static/movable dummy s so that one can practice shooting there 
to improve skills.Also provide a system that for training there will be cheap bullets which can only be used in shooting range.And those cheap bullets will have no action on citizens,it would act as fake bullets only usable for training.

**Comment by DaxterPancake** [comment]
Follow the template, please.
