### ISSUE TITLE
[assets/maps] Vagos Savehouse & Jamestown Upgrade.

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/legacy-assets-issue-tracker#231]
**Name:**
**@Vishal@1523**

**Summary:**
There is one place near Garbage HQ, where there is interior of Vagos Savehouse and One Small addition to Jamestown for Vagos is also added below. The second link have one gate to enter in Jamestown apartments, plus one chilling area and one jail also. 

**Link:**
**Vagos Savehosue** - https://www.gta5-mods.com/maps/vagos-savehouse-1-0-0-mlo
**Vagos district update ( YMAP )** https://www.gta5-mods.com/maps/vagos-district-update-ymap
**Reason:**
This should be added because Vagos don't have any repair shop or club in city. but there are clubs for LMC and SOL. so it will be a good addition in Legacy server if we add this interior and make this one as a repair shop from inside too.

**Comment by z-Lunar** [comment]
This will be looked into 😄

**Comment by bhosalevishu** [comment]
Please add Savehouse and make it Repair Shop :'(
