### ISSUE TITLE
 Addition of some new PDM vehicles

### ISSUE THREAD

**Issue by BlueMoon6969** [InZidiuZ/legacy-assets-issue-tracker#232]
Name:
BlueMoon#0135
Summary :  new cars didn't got added in pdm from a long time and I think you should add some new cars in pdm aswell instead of adding only edm vehicle. Currently all the cars in pdm are too old and I think you should add cars like invetero coquette d10 this car is a copy of corvette c8 and it has some really cool customisations. I think this car should be added into the game, ocelot jugular crazy liveries and customisation and a new cool 4 seater car which can be the most expensive 4 seater car in-game expensive than Pfister neon, Lampadati komoda it can be priced at around 80-90k more than kutuma and it can perform better than that + some good liveries, truffade thrax A copy of buggati divo it can be a little expensive than truffade nero priced at around 450k, Obey 8f drafter this is also a cool 4 seater car and the last one is overflod imorgon This is a 2 door electric sports car this can also be a good addition to pdm.
Link:don't have any link for now but can give you if you really want.
Reason : There is literally no new pdm vehicle from a long time and only edm gets updated in every update i think you should update pdm also this time. It will make be a good update for guys like me who can't afford priority, (Took priority for four times but servers got wiped F) And it'll make pdm more exciting it's boring now same old cars i think you will have a look into this and will probably add these cars xD btw if you don't wanna add all those cars please add atleast invetero coquette d10, obey 8f drafter and ocelot jugular. :D

**Comment by novapurple** [comment]
These vehicles you suggested would need to be EDM or else it will cause issues with the city.

**Comment by BlueMoon6969** [comment]
Oh okay then, thanks
