### ISSUE TITLE
Clothing of VAGOS GANG 

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/legacy-assets-issue-tracker#233]
**Name:**
**@Vishal# 0069**

**Summary:**
This clothing is created by me. let me know if we can add this and If this can be added successfully 
, I can make more custom clothing for our legacy also. 

**File**

[vagosclothing.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5211385/vagosclothing.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?
as per now, there is no clothing available for gang vagos like SOL, LMC, Pirados have their own clothings.  Adding Vagos Clothing can give great experience to those are in VAGOS Gang.

**Comment by DaxterPancake** [comment]
Hi Bhosalevishu!

I had a look at the clothing and they're nice! A few of them are going to be added into the city, thank you for making those!

If you're interested in making clothing for Legacy, you can fill in either the [Development Contributor](https://forms.gle/K4MAY6hzm3a2rFLF9) fourm or the [Developer](https://forms.gle/E6oNXiiG54pKAipq7) fourm. 

Cheers!
Daxter.
