### ISSUE TITLE
Assets/import-police: Vehicle Damage Multiplier

### ISSUE THREAD

**Issue by its-vishal** [InZidiuZ/legacy-assets-issue-tracker#234]
**Reporter:**
@Vishal# 0069

**Summary:**
So, I was testing New Damage System on PD vehicles, So "When we repair vehicle by /repair on PD or Pillbox, Vehicle tyres do not get burst when vehicle get heavy damage by accident". It's happening only when we repair vehicle by /repair

**VIDEO LINK**
https://youtu.be/TNcT8u3MMIw

**Comment by z-Lunar** [comment]
Please use the correct Issue Tracker found [Here](https://github.com/InZidiuZ/op-framework-issue-tracker)

**Comment by z-Lunar** [comment]
> @z-Lunar
> ![image](https://user-images.githubusercontent.com/56230822/96850269-3ef5f380-1474-11eb-8039-d37a1a276a1a.png)

I will take this into consideration & look into it 😄 thank you.
