### ISSUE TITLE
Add additional Yoga mats.

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/legacy-assets-issue-tracker#235]
**Name:**
Who is suggesting this? Please include discord name.
KaiEagle🦅#2469

**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is about adding Yoga mats inside the Police Department (Mission Row) somewhere inside the locked rooms (so that civilians can't access it).

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
This will stop the cops from smoking joints to lower their stress.

**Comment by DaxterPancake** [comment]
What's stopping cops from going to the yoga spot and doing yoga there? Or just smoking cigarettes?

**Comment by KaiEagle** [comment]
> What's stopping cops from going to the yoga spot and doing yoga there? Or just smoking cigarettes?

People just asked me to suggest this, idk I think they too lazy to buy cigars in a bulk or going to it. :|

**Comment by DaxterPancake** [comment]
This won't be added.

Buy Cigarettes. 

Punish those who are smoking joints on duty.

Go to the yoga spot that is provided to allow for interactions to happen.
