### ISSUE TITLE
Bug report: when we jump in normal vehicle tires get pop and it increases the chance for police to get us 

### ISSUE THREAD

**Issue by RDX1** [InZidiuZ/legacy-assets-issue-tracker#236]
**Reporter:**
Who is reporting this? Please include discord name.

**Summary:**
Write a summary of what you're experiencing.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Please remake and follow the template.

There are certain sections you need to fill out.
