### ISSUE TITLE
Clothing of Weazel News 

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/legacy-assets-issue-tracker#237]
**Name:**
ppthegamer#7381

**Summary:**
These clothes are made by me for cali cartel gang and for Weazel News. If these clothes are added i can 
make more clothes for legacy 

**File**
[WN.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5250018/WN.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?
Now there are no clothes for Weazel News like other departmens Cops,EMS,Mechanic so addition of these clothes can give better experience to those who are doing news RP

**Comment by ppthegamer** [comment]
Do these clothes will be added? Please let me know.

**Comment by z-Lunar** [comment]
These files will be looked into & considered in the next clothing push.
