### ISSUE TITLE
Assets/ped-clothes_addon: PD FTO/Instructor EUP

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/legacy-assets-issue-tracker#238]
**Name:**
Igna#6192

**Summary:**
Add a shirt for instructors to wear during PD Academy.

**Link:**
https://gyazo.com/9156a9b04de64f75576d57ca10c087dd
https://gyazo.com/63f7e1357ce237512bb7635d06369f45

**Reason:**
It would be a nice addition to add immersion and professionalism to the academies. The design does not have to be that of the images. I just present the idea

**Comment by TCruxer** [comment]
We try to add clothing on a regular basis as well as PD uniforms. I will be taking this suggestion into consideration and closing it for now.

Cruxer
Lead Asset Dev
