### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Splash004** [InZidiuZ/legacy-assets-issue-tracker#240]
**Reporter:**
Who is reporting this? Please include discord name.
 Splash#6996
**Summary:**
Write a summary of what you're experiencing.
I am the Owner of The a Apartment in Eclipse Boulevard Block- [77]. I cant see or find  any Garage over there.
## Additional Information
Tried to give access [Leve-02] to Several peoples there but we couldnt find any Garage
**Screenshots:**
If suitable, include some screenshots.
![FiveM_-_Legacy_Roleplay_Bangladesh___Wiped_Recently___Custom_Framework___Active_Staff_Development___](https://user-images.githubusercontent.com/64459889/93934736-69ee0a00-fd45-11ea-9096-82c6c6ef1c4c.png)

**Notes:**
For anything else noteworthy.

**Comment by Shanto16** [comment]
Searched for it for more than half an hour, didn't find any garage to store vehicles.

**Comment by Khunter6y9** [comment]
Add a garage please , couldn't find the option for garage. Please add it.

**Comment by arafat0951** [comment]
I cant also find any garage, please help

**Comment by PsychoGrandpa** [comment]
No garage option to take out cars. Please fix it.

**Comment by babanthelegend** [comment]
NO GARAGE ...... please fix it,by adding garage.

**Comment by AdeptCL** [comment]
Okay guys. We get it. There isn't a garage. The bug report is made. It will get looked into when a developer sees this.
Don't need everyone to continuously say that there is no garage.

**Comment by FarhanST** [comment]
There is no garage in that block (77) please add a garage .

**Comment by AdeptCL** [comment]
**Okay guys. We get it. There isn't a garage. The bug report is made. It will get looked into when a developer sees this.
Don't need everyone to continuously say that there is no garage.**

**Comment by KollaKata** [comment]
sir it's been 1 month we bought the block . please please please try add a garage on that block as soon as possible . 😭😭

**Comment by z-Lunar** [comment]
please use the correct Issue tracker found [Here](https://github.com/InZidiuZ/op-framework-issue-tracker)

**Comment by FarhanST** [comment]
Is there no way to add a garage on that block !
It's been 3 months !

**Comment by AdeptCL** [comment]
please use the correct Issue tracker found [Here](https://github.com/InZidiuZ/op-framework-issue-tracker)
