### ISSUE TITLE
Clothes 

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/legacy-assets-issue-tracker#241]
**Reporter:**
Who is reporting this? Please include discord name.
KaiEagle🦅#2469

**Summary:**
Write a summary of what you're experiencing.
The clothes you wear are different in your eyes and it's different in other eyes. 
Like, suppose I am wearing a jacket then in other's eyes it will look like I am wearing a half-sleeved T-shirt.
It's only happening in Shirts components till I know.

**Comment by DaxterPancake** [comment]
This will be fixed when we remove the Summer Collection clothing that is being streamed. In the mean time, the clothing at the end of the Components will be the same and will work.
