### ISSUE TITLE
Assets/import-civilian_2: Charger Dirt Map

### ISSUE THREAD

**Issue by poopgawd** [InZidiuZ/legacy-assets-issue-tracker#242]
**Reporter:**
Who is reporting this? Please include discord name.
ghostface#5314

**Summary:**
Write a summary of what you're experiencing.
The 1970 Dodge Charger import does not get dirty, it instead completely changes the color of the car (where primary color is applied, secondary not affected). Black turns grey, white turns cream. COMPLETELY changes the entire primary color area instead of adding dirt. Would like the car to be the color I painted it for more than five minutes. Dirt I understand, but not paintjob lol

## Additional Information
You folks are awesome.

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by TCruxer** [comment]
Hey,
The 1969 Dodge Charger dirt map should now be fixed in the upcoming update, as well as the breakable windows and the hand steering wheel position. I Will now be closing this issue

Cruxer
Lead Asset Dev
