### ISSUE TITLE
Assets/Maps: La Mesa Mechanic Shop Interior [MLO]

### ISSUE THREAD

**Issue by zonaG** [InZidiuZ/legacy-assets-issue-tracker#243]
**Name:**
Zona G (Discord YoungZona#3217) 

Summary:
The Vagos would like a simple mechanic computer located on the east side in La Mesa sector. I have added images of the location via the link below.We are wanting to buy parts and repair vehicles there.  

**Link:**
http://imgur.com/a/ur8S72I
Like this https://www.gta5-mods.com/maps/vagos-savehouse-1-0-0-mlo

**Reason:**
Why would your suggestion be a good addition to Legacy?
Having more mechanic shops and businesses would add to roleplay and make competition in the city for other shops

**Comment by TCruxer** [comment]
Thank you for your suggestion,
There are already quite a few mechanics shops around the city and I don't have any plans to add more at this very moment.

Cruxer
Lead Asset Dev
