### ISSUE TITLE
Assets/import-civilian_2: Mustang Repair Bug

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/legacy-assets-issue-tracker#244]
**Reporter:**
Who is reporting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a summary of what you're experiencing.
Mustang not being able to be repaired
## Additional Information
when a door flys off or gets ripped off it seems to no be recognizing that there is a door missing.
**Screenshots:**
If suitable, include some screenshots.
https://cdn.discordapp.com/attachments/714462023735574549/765212058903904276/unknown.png
https://cdn.discordapp.com/attachments/714462023735574549/765212102226083860/unknown.png
**Notes:**
For anything else noteworthy.

**Comment by TCruxer** [comment]
This is related to the car model itself and I don't think there is much I can do about that unless I replace the entire model. Will be closing this for now.

Cruxer
Lead Asset Dev
