### ISSUE TITLE
Mayor's Office

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/legacy-assets-issue-tracker#245]
**Reporter:**
Who is reporting this? Please include discord name.
KaiEagle🦅#2469

**Summary:**
Write a summary of what you're experiencing.
So the new Mayor's office interior was added to the server a while ago but seems like Mayor can't open the door or anyone from the state.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://cdn.discordapp.com/attachments/521973785218252802/765877596646539284/FiveM_b2060_GTAProcess_iqoz4qhgka.png

**Notes:**
For anything else noteworthy.

**Comment by z-Lunar** [comment]
Keys exist on the doors of the CEO Office, currently I do not believe they're assigned to a job, if you wish to request them to be assigned to the State Jobs create a suggestion [Here](https://github.com/InZidiuZ/op-framework-issue-tracker)
