### ISSUE TITLE
[peds/clothes_addon] Assorted Clothing Additions

### ISSUE THREAD

**Issue by DAYMOOO** [InZidiuZ/legacy-assets-issue-tracker#246]
**Name:**
Who is suggesting this? DAYMO leader of abm new gang in the city

**Summary:**
Write a short summary of what your suggestion is about.
clothing pretty much we just wanted to ask if a few outfits could be added to the city
we just see alot of people wearing the basic outfits it gets kind of dull

**Link:**
https://www.gta5-mods.com/player/2-pack-preme-sagged-jeans
https://www.gta5-mods.com/player/jordan-11-three-pack
https://www.gta5-mods.com/player/air-jordan-xiv-lows
**Reason:**
Why would your suggestion be a good addition to Legacy?
everyone would like a little more drip threw out the whole city

**Comment by glocknine234** [comment]
These pants looks kinda childish, I suggest these https://www.gta5-mods.com/player/amiri-jeans-2-pack

**Comment by DAYMOOO** [comment]
> These pants looks kinda childish, I suggest these https://www.gta5-mods.com/player/amiri-jeans-2-pack

i just needed that blue you feel me its our color

**Comment by glocknine234** [comment]
I actually have clothing for fivem that are exclusive since last year. I have these sagged pants and every color, I have other gang releated clothes too.

**Comment by DaxterPancake** [comment]
Various jeans & pants have been added that are along these lines.

Cheers,
Daxter.
Project Manager.
