### ISSUE TITLE
Phone will not purchase.

### ISSUE THREAD

**Issue by benpaquin** [InZidiuZ/legacy-assets-issue-tracker#247]
**Reporter:**
ben84#6881 aka Eddie Cantrell

**Summary:**
When I attempt to buy a cell phone, I drag the phone into my inventory and instead of purchasing I receive either an error message or an error 'sound'. 

## Additional Information
There is no other problems buying any other items from any other shops.  I've tried buying the phone from at least half the shops on the map and have experienced the same result. I've cleared my cache, I'm positive I have the cash on hand each attempt, and have done several full reboots over the course of the last 9 hours trying to isolate the problem without any luck.

**Screenshots:**
![image](https://user-images.githubusercontent.com/20466829/96548181-603fbf80-127b-11eb-93cf-97790d50f519.png)

**Notes:**
The other screenshot is from another person who was having the exact same issue earlier today. I tried to contact him without any luck. If it would help I can stream the issue for you via discord as it happens.

**Comment by z-Lunar** [comment]
Please use the correct Issue tracker found [Here](https://github.com/InZidiuZ/op-framework-issue-tracker)

**Comment by benpaquin** [comment]
Thank you. I found the problem. There is no bug. The phone appears in the store appears as $500 but you have to pay taxes to the extent of $535ish. I was testing with $500 in my inventory and that was the problem. Apologies. Keep up the good work.

Kind Regards,
Ben
