### ISSUE TITLE
Assets/import-civilian_2: Car Pack Addition Suggestions

### ISSUE THREAD

**Issue by its-vishal** [InZidiuZ/legacy-assets-issue-tracker#248]
**Name:**
Vishal Bhosale (@Vishal# 0069)

**Summary:**
There are some cars I will love to see on our server as current EDM vehicles are pretty old and already seen on server.
the links for vehicles is given below.

**Link:**
**Bentley Bentayga** - https://www.gta5-mods.com/vehicles/bentley-bentayga
**2019 Range Rover Velar** - https://www.gta5-mods.com/vehicles/2018-range-rover-velar
**2021 Mustang Mach E** - https://www.gta5-mods.com/vehicles/2021-mustang-mach-e-add-on-fivem
**2021 Ducati V4S StreetFighter** - https://www.gta5-mods.com/vehicles/2021-ducati-v4s-streetfighter
**2018 Bentley Continental GT Supersports** - https://www.gta5-mods.com/vehicles/2018-bentley-continental-gt-supersports-add-on-template-automatic-spoiler

**Reason:**
New Luxurious Vehicles are always a attraction for Players, and If we add something new, Players will love it and not so tough task to add the vehicles in server.

**Comment by z-Lunar** [comment]
This is being looked into & considered, feel free to continue updating this list 😃
