### ISSUE TITLE
Suggestion - Exclusive Dealership addition (for the bikers)

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#249]
**Name:**
Adept (AdeptCL#0402)

**Summary:**
When it comes to the exclusive dealership, the common vehicle in rotation is always the 4 wheelers. Which I understand, it's what people want. However, there are a select group of people who like the 2 wheels (sometimes 3 wheels). I have found a bike add-on which I know not just myself will be appreciative of if it is added.

**Link:**
https://www.gta5-mods.com/vehicles/harley-davidson-flhxs-street-glide-special-2018-addon-replace-fivem

**Reason:**
When it comes to bikes in the exclusive dealership, unless it's a specific designed bike, it is only really the "superbikes" that are added. The bike add-on I have provided is a bike which truly reflects the biker community and will be a bike that represents the MCs that have developed in the server.

**Comment by TrialByCombxt** [comment]
**+1**

**Comment by Pyrotimegamer** [comment]
As a biker , Hell yea

**Comment by z-Lunar** [comment]
This suggestion was taken into consideration in the most recent Github commit for Assets 😅
