### ISSUE TITLE
[imports/ems] Medical Boat Unit

### ISSUE THREAD

**Issue by Rithvikk05** [InZidiuZ/legacy-assets-issue-tracker#250]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
A Boat Like PD Have Which EMS Can Also Take From Harbour Where PD Takes Boat Out.

**Reason:**
Why would your suggestion be a good change to the framework?
Sometime People Gets Drowned In between Of Water And In Helicopter you can't take a down body so if a boat comes for rescue will increase more RP [livery should be different its would help to rescue people drowning by boat

![image](https://user-images.githubusercontent.com/64654455/96851981-3d2d2f80-1476-11eb-895f-3f933b5d8908.png)

**Comment by joevapes3** [comment]
The suggestion is noted and if in the future a suitable boat model is found that can benefit all legacy subdivisions, then one will be added at that time. Thank you for your suggestion.
