### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PatelBhai03** [InZidiuZ/legacy-assets-issue-tracker#252]
**Name:**
Patel Bhai | Vish Patel#9166

**Summary:**
Gang Houses - There should be Secret Bunker's or Gang houses in which only People with GANG ROLE (For Eg - PD cadet Role) 
can access the house and they all should have a common locker (for eg PD Evidence Locker) and a individual Locker as well
 
**Link:**
I think Inzi would have to do it manually! 
**Reason:**
As now a days gang rp is taking a boost in the Legacy Server's this would promote Gang RP and a better Gang RP experience as well

**Comment by TCruxer** [comment]
Although I can add certain gang interiors it would require a certain amount of scripts that don't revolve under me. Will be closing this, for now, might come back to this in the future if we have scripts to support it.

Cruxer
Lead Asset Dev
