### ISSUE TITLE
Assets/ped-clothes_addon: Face Mask for SOL

### ISSUE THREAD

**Issue by ultrahacx** [InZidiuZ/legacy-assets-issue-tracker#253]
**Name:**
Who is suggesting this? Please include discord name.
- ultrahacx#2621

**Summary:**
Write a short summary of what your suggestion is about.
- Custom SOL facemask/bandana resource ready to be streamed made by me.
Files:
[sol_mask.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5470681/sol_mask.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?
- It would be nice to see more custom clothing for gangs and let the players deep dive into the RP maybe.

**Comment by AdeptCL** [comment]
Can you post a screenshot of this? 
I'm the current "Gang Leader" for the Sons in the main server, so definitely would like to see/add any feedback. :)

**Comment by ultrahacx** [comment]
Its just a with a simple logo but I'm editing it rn to add some more designs so that there can be multiple varients. Most possibly I'll upload it by today
https://prnt.sc/vb7le9

**Comment by AdeptCL** [comment]
That is the old Sons Club emblem. If you message me on Discord (AdeptCL#0402), I can send you the updated one.
However, I believe @Nuzi (?) is already potentially working on some masks for the Sons as we have discussed this with him.

**Comment by ultrahacx** [comment]
Updated files with some changes:
[sol_mask_2.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5471428/sol_mask_2.zip)

**Comment by TCruxer** [comment]
This has now been added. It will be in the city at the next asset merge.

Cruxer
Lead Asset Dev
