### ISSUE TITLE
Assets/ped-clothes_addon: Clothing of Cali Cartel GANG

### ISSUE THREAD

**Issue by Spyro17** [InZidiuZ/legacy-assets-issue-tracker#258]
**Name:**
Who is suggesting this? Please include discord name.
Name : Spyro
Discord : Spyro YT#3901
**Summary:**
Write a short summary of what your suggestion is about.
This clothing is created by me. We are Whitelisted Gang in Whitelist India Server since Season 1 , we Run a Cartel there , we are famous for our Purple color , but unfortunately we don't have proper Purple Suits in stores , so i did a Little rework on High Rollers suit and placed our Gang Logo on The Coat which States CC , its a custom made Logo made by us , so there is no copyright issue for streamers and we are very Thankful to all legacy developers who designed our very first Armor (it was designed by Nova Purple) . I hope you'll like it and push our creation into the server :) Pictures of the dresses are inside the Zip Folders .
**Link:**
If there are any links to what you're suggesting, please add them here.
[Cali Cartel closed Suit.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5507366/Cali.Cartel.closed.Suit.zip)
[Cali Cartel.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5507368/Cali.Cartel.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?
as per now, there is no clothing available for Cartel/Gangs like Vagos SOL, LMC, Pirados have their own clothings. Adding Cali Cartel Clothing can give great experience to those are in Cali Cartel.

**Comment by TCruxer** [comment]
This has now been added and will be in the city on the next asset merge.

Cruxer
Lead Asset Dev
