### ISSUE TITLE
[imports/*] Light options for vehicles

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/legacy-assets-issue-tracker#259]
**Name:**
Jethiya#1111

Summary:
I think currently we have only two light options for every vehicle i.e stock & xeon , so adding of new light options would add more aesthetics to the vehicles along with other modifications available.

Reason:
More modifications and aesthetic options would be available to the players to add into their vehicles.

**Comment by joevapes3** [comment]
This would have to be updated via the Los Santos customs script and is not able to be done from assets. I will reach out about getting the script from that development team and work on getting them added, as there is other features/mods I'd like to see added to Los Santos Customs as well. Thank you for your suggestion.
