### ISSUE TITLE
Car Suggestion : 1969 Dodge Charger

### ISSUE THREAD

**Issue by XBTech** [InZidiuZ/legacy-assets-issue-tracker#26]
**Name:**
[M-26] CO-306 C. Rendell | Buck
discord: Cruxer#4806

**Summary:**
After discussing with a few people and looking around I found this awesome and slick design of the Dodge Charger 1969 (With a general Lee livery). I thought this could be a great addition to the exclusive dealership. You will find bellow the links mentioned.

**Link:**
Dodge Charger 1969 files:
https://www.gta5-mods.com/vehicles/1969-dodge-charger-r-t-add-on-replace-tuning-hq

General Lee livery:
https://www.gta5-mods.com/paintjobs/1969-dodge-charger-rt-general-lee-skin

**Reason:**
I have had some great feedback on this car and it seems like a lot of people would enjoy riding around the city in this charger. It would also bring some variety and balance in the exclusive dealership as it doesn't seem to contain a lot of american muscle cars compared to other types of vehicles like the JDM and business type cars.

**Comment by Karpenkooo** [comment]
Hey

This suggestion has been noted and may be added in the next vehicle Pack.

_Karpenko_

_**OP-FW Vehicle Developer**_
