### ISSUE TITLE
Add new vehicles to PDM

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/legacy-assets-issue-tracker#260]
**Name:**
Who is suggesting this? Please include discord name.
GlockNine#4920

**Summary:**
Write a short summary of what your suggestion is about.
You should add some of these cars to PDM.

**Link:**
If there are any links to what you're suggesting, please add them here.*

![image](https://user-images.githubusercontent.com/70439794/98452242-2402cf00-2156-11eb-9751-dc9262f5758b.png) Tempesta

![image](https://user-images.githubusercontent.com/70439794/98452129-33cde380-2155-11eb-86b2-9f49927885d2.png) Cheetah2

![image](https://user-images.githubusercontent.com/70439794/98452133-3a5c5b00-2155-11eb-9c69-149fec98a605.png) Torero

![image](https://user-images.githubusercontent.com/70439794/98452141-4b0cd100-2155-11eb-9262-270f0aff090f.png) Raiden
 

![image](https://user-images.githubusercontent.com/70439794/98452148-5eb83780-2155-11eb-95a4-bb485dab5cdf.png) Dominator3

![image](https://user-images.githubusercontent.com/70439794/98452150-6972cc80-2155-11eb-8892-025e2bd6a2dc.png) Jester3

![image](https://user-images.githubusercontent.com/70439794/98452170-8a3b2200-2155-11eb-9942-6b774a92d95d.png) Hellion

You can spawn them with /sv (Name) right now ,but players can't buy them from PDM.

**Reason:**
Why would your suggestion be a good addition to Legacy?
They look good enough and I think they should be added to PDM.

**Comment by TCruxer** [comment]
Most of these cars can already be found in PDM and the last one the Hellion is an exclusive dealership vehicle. Will therefore be closing this.

Cruxer
Lead Asset Dev
