### ISSUE TITLE
New liverys + vehicles

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/legacy-assets-issue-tracker#262]
**Name:**
Who is suggesting this? Please include discord name.
GlockNine#4920

**Summary:**
Write a short summary of what your suggestion is about.
You should add some of these liverys/cars. Found them from my PC files and decided to put them somewhere instead of just standing there.

**Link:**
If there are any links to what you're suggesting, please add them here.
https://drive.google.com/drive/folders/1DAMvLXEZaVlrkK6vpiIc4WYfROtZCpJd?usp=sharing

**Reason:**
Why would your suggestion be a good addition to Legacy?
They look decent.

**Comment by glocknine234** [comment]
If these liverys don't work on current vehicles and really necessary then I could give car models aswell.

**Comment by TCruxer** [comment]
We already use a lot of custom liveries for emergency vehicles. As we just recently changed all our liveries I don't believe this is still relevant and will therefore be closing it.
