### ISSUE TITLE
New Loading Screen Maybe ? 

### ISSUE THREAD

**Issue by PatelBhai03** [InZidiuZ/legacy-assets-issue-tracker#263]
**Name:**
Patel#9166

**Summary:**
I think its now time to add a new Loading screen into our servers

**Link:**
https://drive.google.com/drive/folders/1E6mDJJhSb0ObEqv3cLKxvBbsf6A4Eywv?usp=sharing

**Reason:**
Its been More than 1 year and it would be a change for everyone 
If you do like it let me know if you need any file or images particularly!

**Comment by PatelBhai03** [comment]
@TCruxer ?

**Comment by TCruxer** [comment]
Although this doesn't really fall under my assets section, I believe a new loading was already introduced. I will therefore be closing this for now.

Cruxer
Lead Asset Dev
