### ISSUE TITLE
Split Side west interior

### ISSUE THREAD

**Issue by kevin7803** [InZidiuZ/legacy-assets-issue-tracker#264]
**Name:**
Who is suggesting this? Please include discord name.
kevin patel#1685

**Summary:**
Write a short summary of what your suggestion is about.
Its a club for organizing party. This club is way better than 'bahama mamas'.
**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/maps/split-sides-west-mlo-fivem-ragemp

**Comment by XwezioGH** [comment]
Thank you for your suggestion,

Currently we have no plans to add more interiors, as our current goal is working on getting all of our MLO's we have already have and getting them optimized before we add more.

I will add this to my spreadsheet and will look into it in the future.

**Xwezio
Asset Dev**
