### ISSUE TITLE
Add Large Vehicle Repair Location at Flywheels

### ISSUE THREAD

**Issue by KookieNCoffee1** [InZidiuZ/legacy-assets-issue-tracker#266]
**Name:**
Who is suggesting this? Please include discord name.
KookieNCoffee1#0906

**Summary:**
Write a short summary of what your suggestion is about.
I am suggesting for a repair location to be added at the back of Flywheels, the mechanic shop located right next to Sandy Shores Airfield. Around about this location.
https://cdn.discordapp.com/attachments/741326915956244650/778095275372707870/unknown.png

Maybe possibly removing this garage door...
https://cdn.discordapp.com/attachments/741326915956244650/778095391295537172/unknown.png

There is already a way for big cars to get in and out of the area, a fence that automatically opens and closes as the player draws near.
https://cdn.discordapp.com/attachments/741326915956244650/778095514305822730/unknown.png

 Opening the garage door linked above would just allow for the mechanic to have easy access to the repair table.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Currently, the only place for someone to get their tow truck or semi truck repaired is at the docks repair shop. This would allow for there to be a second location that people could go to.

**Comment by poopgawd** [comment]
Wow, this sounds like such a goog idea! I hate going to the docks for repairs on my semi.

**Comment by TCruxer** [comment]
We already have quite a few mechanic shops around the city. I will not be implementing this at this time.

Cruxer 
Lead Asset Dev

**Comment by KookieNCoffee1** [comment]
I no longer have any interest in Flywheels, however it already is a functional mechanic shop with a repair spot ("Review Vehicle" spot) located inside (though without a materials computer). Was requesting for another one of the "Review Vehicle" access spots to be placed directly behind the shop so Large vehicles (semi-truck and tow truck) can be repaired. Currently, only spot is the docks. Could make the shop more appealing.
