### ISSUE TITLE
[Livery addon] Addon SOL livery for burrito gang van

### ISSUE THREAD

**Issue by ultrahacx** [InZidiuZ/legacy-assets-issue-tracker#267]
**Name:**
Who is suggesting this? Please include discord name.
- ultrahacx#2621

**Summary:**
Write a short summary of what your suggestion is about.
- Addon SOL livery texture/ytd for burrito gang van

**Link:**
If there are any links to what you're suggesting, please add them here.
[gburrito.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5552769/gburrito.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?
- Just another thing to make gang members more happy and show the presence of thier gang in the server without any super extra workload on the developement team.

**Comment by AdeptCL** [comment]
:D! Do you got an image of this we could see?

**Comment by TCruxer** [comment]
The current system does not allow me to put custom liveries on vanilla vehicles I will therefore be closing this and coming back to it in the future if the situation changes.

Cruxer 
Lead Asset Dev
