### ISSUE TITLE
Add horns modifications

### ISSUE THREAD

**Issue by aay4abdullah** [InZidiuZ/legacy-assets-issue-tracker#268]
**Name:**
Who is suggesting this? Please include discord name.
Tripper#1111
**Summary:**
Write a short summary of what your suggestion is about.
different types of music and other horns are available in offline/online gta 5 . i think we should have them here too as that will definitely be a good addition 
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by TCruxer** [comment]
Unfortunately, this does not fall under my department and is related to the Los Santos script. Please repost in the proper GitHub listed below.

[Framework Issue Tracker](https://github.com/InZidiuZ/op-framework-bug-tracker/issues)

Cruxer
Lead Asset Dev
