### ISSUE TITLE
[peds/*] EUP update

### ISSUE THREAD

**Issue by pepaj420** [InZidiuZ/legacy-assets-issue-tracker#269]
**Name:**
Who is suggesting this? Please include discord name.
Pepaj#7224

**Summary:**
Write a short summary of what your suggestion is about.
I suggest updating EUP to 8.9 version by Alex Ashfold.

**Link:**
If there are any links to what you're suggesting, please add them here.
https://mega.nz/folder/9D42Gboa#N-eQlSbZT3O5czY3GNwFHg

**Reason:**
Why would your suggestion be a good addition to Legacy?
This update would greatly improve experience from game, especially for players in emergency services. Clothes on the server look totally outdated compared to the newest version of EUP, in an aspect of quality of models and textures, but also in variety of different pieces of clothing. I think having this would make this server stand out in one more positive way, because at least in Poland nobody even has it yet.
Edit:
I have seen the whole content of it and it is one big piece of art.

**Comment by glocknine234** [comment]
That's not for FiveM as it's in beta stage...

**Comment by ReqsoN** [comment]
> That's not for FiveM as it's in beta stage...

I saw this eup on a few polish FiveM servers and it worked fine

**Comment by gighul** [comment]
As a polish subdivision manager I approve this message 🤣

**Comment by glocknine234** [comment]
Uum is there any pictures of this EUP 8.9? I didn't find any :D

**Comment by ReqsoN** [comment]
> Uum is there any pictures of this EUP 8.9? I didn't find any :D

You can see all images of EUP 8.9 on Alexs Ashfold's Discord.

**Comment by glocknine234** [comment]
Oh, god yea that's nice. Definitely vouch for that!

**Comment by Reyess14** [comment]
Very good idea. It would be nice to update the eup for services.

**Comment by joevapes3** [comment]
Not the exact pack you specified, but the latest EUP pack is planned to be added. Exactly when it will get added is not exactly clear, but should be at some point in the near future.
