### ISSUE TITLE
Bug police vehicles

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/legacy-assets-issue-tracker#27]
**Reporter:**
Who is reporting this? Please include discord name.
Sercan#0001

**Summary:**
Write a summary of what you're experiencing.
Police cars got weight installed, the only problem is that the cop cars not accelerating properly. they accelerate in like 3. or 4. gear.
Its big issue as we cant even keep up with the other local vehicles.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
Nope, but i could include a video to should the issue

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey

This issue has been discussed already and will be fixed in the next big PD Overhaul. ETA will be just over a week i think.   :)))

_Karpenko_

**_OP-FW Vehicle Developer_**
