### ISSUE TITLE
Assets/ped-clothes_addon: C C Face Mask

### ISSUE THREAD

**Issue by Spyro17** [InZidiuZ/legacy-assets-issue-tracker#270]
**Name:**
Who is suggesting this? Please include discord name.
Name : Spyro
Discord : Spyro YT#3901
**Summary:**
Write a short summary of what your suggestion is about.
This clothing is created by me. We are Whitelisted Gang in Whitelist India Server since Season 1 , we Run a Cartel there , As Many Gangs have their own Face Mask, so i designed our very own Gang Face Mask , its a custom made Logo made by us , so there is no copyright issue for streamers and we are very Thankful to all legacy developers Specially Cruxer ,who helped us and motivated us to design more clothes like these :)
**Link:**
If there are any links to what you're suggesting, please add them here.
[Cali Mask.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5557247/Cali.Mask.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?
as per now, there is no Face Mask available for Cartel/Gangs like Vagos SOL, LMC, Pirados have their own Face Masks. Adding Cali Cartel face Mask can give great experience to those are in Cali Cartel.

**Comment by Spyro17** [comment]
Cruxer please look into this .

**Comment by TCruxer** [comment]
This has now been added and will be available in the next asset update.

Cruxer 
Lead Asset Dev
