### ISSUE TITLE
[imports/*] Colored Xenon Lights

### ISSUE THREAD

**Issue by kevin7803** [InZidiuZ/legacy-assets-issue-tracker#271]
**Name:**
Who is suggesting this? Please include discord name.
kevin patel#1685

**Summary:**
Write a short summary of what your suggestion is about.
this a different xenon lights . in legacy there is only one light but we should add this so car looks good at night.

**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/misc/colored-xenon-lights
**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by joevapes3** [comment]
This would have to be done via the Los Santos Customs script and not from assets. I will reach out to the script developers to get this added to the Los Santos Customs script. Thank you for your suggestion.
