### ISSUE TITLE
[peds/*] New clothings for EMS

### ISSUE THREAD

**Issue by ghost** [InZidiuZ/legacy-assets-issue-tracker#272]
**Name:**
Who is suggesting this? Please include discord name.
TᴀɴZɪM#6996

**Summary:**
Write a short summary of what your suggestion is about.
I'm working as an EMS in Legacy server for a long time. It's been a long time since new EMS dresses have been added to our servers. Recently many police dresses have been added but nothing has been added for our EMS. I'm also working in SASP department and there I've seen recently a lot of dresses were added but in EMS, nothing much. Our dress components are lesser than the ranks. So I think it would be great to add some more new dresses for EMS.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
As we have less components, so we had trouble matching our ranks but now if new outfits are added, then it would be great to match ranks and clothes and Etc.

**Comment by BmFarhan** [comment]
*+1*

**Comment by keepcodingstar** [comment]
+1

**Comment by DaxterPancake** [comment]
The generous EMS community of the NA/EU server banded together to purchase EMS scrubs, not only that but we've recently updated the EUP to include more EMS things and the old EUP will (hopefully) being added back in the next clothing update, so I am going to consider this completed. If you have anything specific you'd like, please open another issue.

Cheers,
Daxter.
