### ISSUE TITLE
[vehicles/handlings] Roosevelt Valor Speed/Velocity

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/legacy-assets-issue-tracker#273]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a short summary of what your suggestion is about.
After test driving the base model and this version of the Roosevelt, the more expensive Roosevelt Valor goes MUCH slower about 100 MPH difference and the acceleration in this one is much worse. The handling with this one is great so if the handling of this one with the speed and acceleration of the base version was put on her instead it would make a more incentive to buy this one instead of the looks and losing over 100 MPH Also if the price of these cars could be a little cheaper? 250,000$ for these seem rather expensive 
**Link:**
If there are any links to what you're suggesting, please add them here.

https://gta.fandom.com/wiki/Roosevelt_Valor

**Reason:**
Currently it is really really slow :( so slow it would push people to buy the cheaper one instead.

**Comment by joevapes3** [comment]
This vehicles top speed and acceleration has been buffed to match it's vehicle class in the latest handling update that will be pushed once all changes are complete. This update will more than likely be pushed in the next couple weeks.
