### ISSUE TITLE
[maps/burger_shot] ATM in BurgerShot

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/legacy-assets-issue-tracker#275]
**Name:**
Who is suggesting this? Please include discord name.
ppthegamer#7381

**Summary:**
My suggestion is about adding ATM in BugerShot

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
In Legacy India WL BurgerShot RP is started and it is going pretty well but there is no ATM so players have to go other store for money. If this is added then it will be easier for them to take out money from bank and continue RP there.

**Comment by XwezioGH** [comment]
Thank you for the suggestion, This has now been added.

I will be closing this now.

**Xwezio
Asset Team**
