### ISSUE TITLE
BurgerShot Van Livery

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/legacy-assets-issue-tracker#277]
**Name:**
ppthegamer#7381

**Summary:**
My suggestion is about adding BurgerShot livery in Rumpo Van

**Link:**
[BurgerShot Van.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5596932/BurgerShot.Van.zip)

**Reason:**
I do BurgerShot RP in Legacy India WL and its going good. In RP players ask for home delivery but there is burgershot van or livery available in server. If this is added in other sub-division too people can start burgershot RP which will increase RP in the server. And this addition would be great for creating RP. 

Thank You

**Comment by TCruxer** [comment]
The current framework doesn't properly support custom textures on default GTA vehicles. I will therefore be closing this for now but I might consider making a Burgershot livery on the Speedo Custom that is in the exclusive dealership in the future.

Cruxer
Lead Asset Developer
