### ISSUE TITLE
Gate at Caesars Place 2

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/legacy-assets-issue-tracker#278]
**Reporter:**
Who is reporting this? Please include discord name.
Masik52#5834
**Summary:**
Write a summary of what you're experiencing.
as of today there is a gate at Caesar's Place 2 that doesn't open and prevents you from pulling into the driveway.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This has since been resolved.
