### ISSUE TITLE
Assets/vehicle-handlings: Toros handling adjustments

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/legacy-assets-issue-tracker#279]
**Reporter:**
Who is reporting this? Please include discord name.
Masik52#5834
**Summary:**
Write a summary of what you're experiencing.
Pegasi Toros needs to be dialed back a bit.  
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by TCruxer** [comment]
Hey,

The Toros has now received a speed and acceleration adjustment and should be live on the server in the next asset update. I will now be closing this issue.

Cruxer
Lead Asset Dev
