### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by thefinalgamer** [InZidiuZ/legacy-assets-issue-tracker#28]
**Reporter:**
Who is reporting this? Please include discord name.
th3finalgamer

**Summary:**
Write a summary of what you're experiencing.
elegy retro custom is slow as shit 
## Additional Information
the car was quick and very good at turning now its like a slow local car 

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
_"Write a summary of what you're experiencing.
elegy retro custom is slow as shit"_

Dunno if that's the way to write up a bug report... Try relog and re write this issue. But put a little more effort into it maybe?
