### ISSUE TITLE
Assets/ped-clothes_addon: FIB Vest Retexture

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/legacy-assets-issue-tracker#280]
**Name:**
Ori#4385

**Summary:**
FIB vest only comes in black/blue, does not match with FIB tactical uniform. (see the picture in links below) 
Needs recoloring or another color version added with dark green/tan/dark tan colors etc. This would be the final touch we'll need for the perfect uniform, we also certainly wanna keep black colors for SWAT.

If you can put the extra work in, the FBI helmet also doesn't go as well with the uniform as the brighter one that says police on it. So if you could rock some swappity doos on the textures or copy some of the color values since it's the same helmet different textures (hoping that's possible). So that way we can use the brighter helmet and it would also say FBI on it. But it's not nearly as critical as the FIB vest color.

**Link:**
https://prnt.sc/vydt16
https://prnt.sc/vydw40
https://prnt.sc/vydwbd

**Comment by TCruxer** [comment]
This has now been fixed and should be live in the next asset update.

Cruxer
Lead Asset Dev
