### ISSUE TITLE
[imports/jobs] BurgerShot Van 

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/legacy-assets-issue-tracker#281]
**Name:**
Who is suggesting this? Please include discord name.

**Summary:**
My suggestion is about adding BurgerShot livery.

**Link:**
[BurgerShot.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5687248/BurgerShot.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?
I have suggested this before but current the framework doesn't support custom texture on default GTA vehicle so I made BurgerShot livery for another vehicle.

**Comment by panpawn** [comment]
I'd love to have something like this - I've been doing a lot of Burger Shot RP lately and I think something like this would be a great addition!

**Comment by Nuziatella** [comment]
See #348 .
