### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by unknownwooptiewoop** [InZidiuZ/legacy-assets-issue-tracker#282]
**Name:**
Who is suggesting this? Please include discord name.
Wes#7238

**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is to add the "Franklin" and "Trevor" ped to the list of charachters that are being able to be used, the michael charachter is currently being used and I feel like adding a Franklin or Trevor for RP purposes would be nice as well. Perhaps it's also a way of not so many michaels showing up. 

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?

It'd be a good addition because it just opens up more roleplay opportunities, I can't really call any downside on it. I know that I personally would love to be able to RP as a crazier redneck version of trevor, it gives some variety around town as well instead of most of the same models/faces.

**Comment by TCruxer** [comment]
This, unfortunately, does not fall under my department and would need to be re-posted under [the following](https://github.com/InZidiuZ/op-framework-bug-tracker/issues) GitHub report.

Cruxer
Lead Asset Dev
