### ISSUE TITLE
[imports/police] Ford Raptor 2012 Model Change

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/legacy-assets-issue-tracker#283]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185

**Summary:**
Write a short summary of what your suggestion is about.
There are many issues with this car in the server, some are visual issues, but some are really bad issues that cause the car to be un-driveable. There is visual glitches that cause the taillights to no work( Flash, or not work correctly) its a four-seater but breaks immersion when you phase right thru the back because this is an extended cab model.

**Link:**
If there are any links to what you're suggesting, please add them here.
https://medal.tv/clips/39772379/d1337FJUAtlE - in this video you can see that the car randomly bounces when driving it. I have tested it with the bumpers off and on and this still happens. 
https://user-images.githubusercontent.com/58092783/103153205-ea654200-475c-11eb-8595-bf24e7725124.png - left taillight
https://user-images.githubusercontent.com/58092783/103153216-ff41d580-475c-11eb-8ddc-ebd1da17bc74.png - right taillight
--------------------------------------------
I found a couple of good replacements for this car
https://www.gta5-mods.com/vehicles/2019-ford-ranger-raptor-add-on-dirtmap-template-livery-extras - 2019
https://www.gta5-mods.com/vehicles/2017-ford-raptor-hq-rigged-suspension-multi-dirt-animated-engine-tuning -2017

**Reason:**
Why would your suggestion be a good addition to Legacy?
this model is broken, and feel like it would make a good addition to have this model replaced with a nicer one as a whole

**Comment by joevapes3** [comment]
The Ford Raptor model that exists currently does have quite a few bugs and is being replaced with an updated Ford Raptor model. I will be pushing this update at some point over the next week, and it will be a direct replacement for the previous model. If the previous Raptor model is owned by a player, the new one will take it's place once the update is pushed live. Thank you for the suggestion.
