### ISSUE TITLE
[peds/*] Ways to make the characters look more diverse from each other

### ISSUE THREAD

**Issue by missskinny** [InZidiuZ/legacy-assets-issue-tracker#284]
**Name:**
Who is suggesting this? Please include discord name.
battery acid#0240 (paris anders)
**Summary:**
Write a short summary of what your suggestion is about.
A few things that would make everyone's characters look better
**Link:**
If there are any links to what you're suggesting, please add them here.
smooth skin: https://www.gta5-mods.com/player/improving-all-mp-female-characters-appearance-1-0 
eyelashes: https://www.gta5-mods.com/player/mp-female-3d-lashes
facial feature customization: https://cdn.discordapp.com/attachments/751344930474950686/793237991828226107/maxresdefault.png
**Reason:**
Why would your suggestion be a good addition to Legacy?
so there's more diversity among other players physical features, after being in the city for a while, a lot of people (esp. the girls) look the same. it would just allow people to look different from each other.

**Comment by DaxterPancake** [comment]
Closing as I believe that this is not needed at this time. If you wish to suggest facial customization then you would need to suggest that in the correct github [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
