### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AverageStatistic** [InZidiuZ/legacy-assets-issue-tracker#285]
**Name:**
Who is suggesting this? Please include discord name.
Dex#5879
**Summary:**
Write a short summary of what your suggestion is about.
Remove the christmas stuff at legion square.
**Link:**
If there are any links to what you're suggesting, please add them here.
N/A
**Reason:**
Why would your suggestion be a good addition to Legacy?
Reduce lag, christmas is over.

**Comment by TCruxer** [comment]
This has already been done closing this issue.

Cruxer Lead Asset Dev
