### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SanSiro513** [InZidiuZ/legacy-assets-issue-tracker#286]
**Name:**
Hewwo it's Kaplo.  Discord: SanSiro#9781

**Summary:**
My suggestion is just simple and easy really if there is any possible way you guys could like to let people like escort downed people into car seats.

**Link:**
no links

**Reason:**
Well in real life you put injured people in car seats and not the trunk lmao

**Comment by AdeptCL** [comment]
@SanSiro513 - I feel like this is more of a framework than assets suggestion. Which can be posted [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose).

**Comment by TCruxer** [comment]
What he said above this is the wrong GitHub please repost in the correct one listed above.

Cruxer
Lead Asset Dev
