### ISSUE TITLE
Suggestion - "SONS" rings added into the accessories section.

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#287]
**Name:**
Adept | AdeptCL#0402

**Summary:**
"SONS" rings adding into the left hand/arm accessories section.

**Link:**
Download below:
[SONS rings.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5768834/SONS.rings.zip)
Image [here.](https://media.discordapp.net/attachments/764042343685816320/768685440236519444/KUcqnOm.png?width=1171&height=676)

**Reason:**
We recently purchased some add-on files to add another piece of "gang" clothing for the Sons of Legacy Motorcycle Club. They are a set of rings split with "SO" and "NS". I believe they sit on the left hand. If these can be added into the accessories section for the left arm/hand, that'd be massively appreciated.

**Comment by TCruxer** [comment]
This has now been added and will be in the upcoming asset update. (The ring will be under decals)

Cruxer Lead Asset Dev
