### ISSUE TITLE
More character customisation 

### ISSUE THREAD

**Issue by WillMurrell0** [InZidiuZ/legacy-assets-issue-tracker#288]
**Name:**
Who is suggesting this? Please include discord name.
ICN : Bertha Good  . Will.Murrell#8935
**Summary:**
Write a short summary of what your suggestion is about.

This is a suggestion to add more face sliders / customisation to characters faces

**Link:**
If there are any links to what you're suggesting, please add them here.
Smooth skin link :  https://www.gta5-mods.com/player/improving-all-mp-female-characters-appearance-1-0
Eyelashes :  https://www.gta5-mods.com/player/mp-female-3d-lashes
facial feature customization: https://cdn.discordapp.com/attachments/751344930474950686/793237991828226107/maxresdefault.png

**Reason:**
Why would your suggestion be a good addition to Legacy?

It would add more diversity and more character style to each character and make the player feel like its truly their own character that they created instead of using pre-made faces that mean nearly everybody is stuck looking the same. Its a good addition because especially amongst the female characters everyone chooses the same face and everyone is made to look the same then.

**Comment by AdeptCL** [comment]
This has already been suggested. Instead of having duplicate suggestions, we recommend closing this one and reacting to the one posted 16 days ago: #284
