### ISSUE TITLE
[peds/clothes_addon] San Fierro Triads Gang Jacket

### ISSUE THREAD

**Issue by Bhavesh02** [InZidiuZ/legacy-assets-issue-tracker#289]
Name: Bhavesh02
Discord: @UnPredictable#1727

**Summary:**
We are a whitelisted gang in Legacy Roleplay India whitelist, As every gang in the server has their own clothing so we decided to have our own clothing too. It would be very helpful of you if you add one for us. We just want a jacket same as LMC, Pirados, SOL etc. Logo for the same has been given below

**Link:**
https://drive.google.com/file/d/1Pme2t_2vYGeIr_Vkb3ISePLBuSbEfEfv/view?usp=sharing

**Reason:**
As we are new gang in the server so getting our own clothes will give us more experience then before. People don't usually recognize us because we don't have any such clothing like other.

**Comment by DaxterPancake** [comment]
A lot of that clothing was PURCHASED by those gangs, so if you wish to have clothing as such, then I would suggest paying for them like others did.

[HERE](https://www.bikermods.com/) is the website a lot of those gangs used.

**Comment by DaxterPancake** [comment]
Is this still something you are wanting?

**Comment by Bhavesh02** [comment]
> Is this still something you are wanting?

Thanks for you reply. You can close this
