### ISSUE TITLE
Truffade Nero Custom Speed Low

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/legacy-assets-issue-tracker#29]
**Reporter:**
Who is reporting this? iGreatWhite#3018

**Summary:**
The Truffade Nero Custom only goes like 140 in a straight at the airport. I feel like this is very low for the car being just modeled like the bugatti.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

I believe that this vehicle a downforce modifier which lowers it's top speed by quite a lot however it makes the cars handling amazing. I'll take another look at it now and maybe bump up the top speed. 

_Karpenko_

**_OP-FW Vehicle Developer_**

**Comment by Karpenkooo** [comment]
Hey,

The Truffade Nero Custom has now been bumped up by almost 60 mph. Sorry for taking so long =P.

_Karpenko_

_**OP-FW Vehicle Dev**_
