### ISSUE TITLE
Adding more vehicles to pdm

### ISSUE THREAD

**Issue by aay4abdullah** [InZidiuZ/legacy-assets-issue-tracker#290]
Tripper#6571
Who is suggesting this? Please include discord name.

**Summary:**
it'd be nice if we see more pdm vehicles .there are very good vehicles . one of them i miss the most in legacy RP is blista kanjo as it is a pure JDM car and following the legacy pakistan RP we love jdm machines and JDM car culture is very much liked and followed here . kindly if possible please add this car in pdm .

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
it'd be a good addition as people will enjoy new cars and will be happy to them in their car collection/garage

**Comment by TCruxer** [comment]
The current PDM system does not allow me to add import vehicles to PDM. I will therefore be closing this for now and coming back to it in the future if the system changes.
