### ISSUE TITLE
More Clothes and Hair!!!

### ISSUE THREAD

**Issue by missskinny** [InZidiuZ/legacy-assets-issue-tracker#291]
**Name:**
Who is suggesting this? Please include discord name.
**ICN:** Paris Anders **Discord:** battery acid#0240
**Summary:**
Write a short summary of what your suggestion is about.
here's a ton of clothing and hair creators that would bring alot more of diversity in what people wear.
**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/users/HeavenDoll (<<she has really good stuff that VU dancers could use) https://www.gta5-mods.com/users/Jaagoda (<<her hairs are high quality and gorgeous) https://www.gta5-mods.com/users/CapatofMods (<<she also has alot of hairs and some clothing pieces) https://www.gta5-mods.com/player/starboy-hairstyle-for-mp-male (<<this is a link to a new hair for the guysss) https://www.gta5-mods.com/users/Dollie (<<her content is so nice!!) https://www.gta5-mods.com/users/HKMods (<<she makes dresses and accessories) https://www.gta5-mods.com/users/neikal (<<this creator also makes dresses and hairs) https://www.gta5-mods.com/users/Ravenay%20Mods (<<hairs and one dress) https://www.gta5-mods.com/users/Sparkles https://www.gta5-mods.com/users/INSANOGAMES (<<THES TWO ARE BY FAR THE BEST CREATORS IVE SEEN)
**Reason:**
Why would your suggestion be a good addition to Legacy?
it would allow the girls to wear different clothes because the female clothing is very limited when it comes to feminine clothing

**Comment by TCruxer** [comment]
New hairstyles and clothing for both males and females have been added and will be available on the next asset merge update.

Cruxer
lead asset dev
