### ISSUE TITLE
[vehicles/*] Schlagen GT cannot drive on sand/dirt

### ISSUE THREAD

**Issue by Jackieskii** [InZidiuZ/legacy-assets-issue-tracker#292]
when trying to drive the Schlagen GT (PDM car) on sand or dirt, the car just spins its wheels and barely moves an inch. have tried storing it/retrieving it. nothing works, seems to be an issue with the cars code.

video link: https://streamable.com/9u836v

**Comment by joevapes3** [comment]
This issue has been fixed/resolved and when the latest handling changes get pushed to all the vehicles as a whole, then it will be implemented at that time.
