### ISSUE TITLE
maps/map-prison: New Prison Interior

### ISSUE THREAD

**Issue by Jacobbss1729** [InZidiuZ/legacy-assets-issue-tracker#294]
**Name:**
I do not remember my discord nick

**Summary:**
Maybe you change the interior of the prison because it bugs a lot and is quite small. Here he gives a link to the new https://youtu.be/Ak7MHmnq4hs

**Link:**
https://youtu.be/Ak7MHmnq4hs

**Reason:**
Better JailRP

**Comment by InZidiuZ** [comment]
The prison interior has since been changed.
