### ISSUE TITLE
La Familia Vest

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/legacy-assets-issue-tracker#295]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a short summary of what your suggestion is about.
La Familia WL Gang vest from International Server #1
**Link:**
If there are any links to what you're suggesting, please add them here.
https://gyazo.com/7f99c6b5cf6edeb73ab36bb0c8fe871f - View it
[La Familia.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5827054/La.Familia.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?
We are a WL group and we have been working on a new vest that is unique.

**Comment by TCruxer** [comment]
This has now been added and will be in the next asset update. 

Cruxer
Lead Asset Dev
