### ISSUE TITLE
[imports/civilian_*] New Exclusive Motorcycle

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#296]
**Name:**
AdeptCL#0402 | On behalf of all biker roleplayers.

**Summary:**
Right, here we go again... The Harley Davidson Street Glide. Please. It's hot.

**Link:**
https://www.gta5-mods.com/vehicles/harley-davidson-flhxs-street-glide-special-2018-addon-replace-fivem

**Reason:**
Within Legacy Roleplay and it's subdivisions, the growth of Motorcycle Club RP has grown massively. In return of this, the MC roleplayers haven't had a bike that really signifies who they are. There was a HD in the past, but it was never a bike that was associated to the type of group.

Having a bike with a structure build like the Harley Davidson Street Glide, it really emphasises what the 1%er roleplayers are trying to be. The link leads to an add-on download which can/could be added to the Exclusive Imports as a new vehicle. I would suspect the bike would either fall under the 1st Tier or 2nd Tier, based on what it is.

I personally have never wanted a particular vehicle so much. And after discussion with my fellow group members and even people not associated to my group, they have shown interest in it also. Please Cruxer, you're our only hope.

**Comment by khunt3r** [comment]
Dayumn, that bike is hawt !.!!

**Comment by Nuziatella** [comment]
This has been added.
