### ISSUE TITLE
[maps/pearls_restaurant] New Pearl's Restaurant 

### ISSUE THREAD

**Issue by PeteDollas** [InZidiuZ/legacy-assets-issue-tracker#298]
**Name:**
PeteDollaz#1452

**Summary:**
Opening the interior of Pearl's Restaurant on the pier.

**Link:**
https://www.fivem-store.com/product/pearls/

**Reason:**
I Feel the city needs more restaurants and new foods to cause new scenarios and a new place for everyone to experience. There isn't much to do on that side of the map so I feel it'll give people more things to do and explore the whole map and enjoy the view on the pier with their friends, Along with bringing their friends to the bar above the restaurant.

**Comment by AdeptCL** [comment]
This could also benefit - if it ever comes - a fishing system. Collect fish from location, and sell it at a marker at this restaurant.

**Comment by PeteDollas** [comment]
> This could also benefit - if it ever comes - a fishing system. Collect fish from location, and sell it at a marker at this restaurant.

That sounds perfect, hopefully a fishing system comes into the city, we could have the marker at one of the doors at pearls and sell the rods at mega mall. We could probably make it to where you can find some scrap while fishing as well. We could also add fancy foods like steak and sushi because we only have fast food and we can have a nicer/ healthier option for whoever wants it. As well as having the upstairs bar area, I could partner with tequila la and get alcohol from there and sell it at the upstairs bar or hire someone who works at tequila la for a event and have them hand out drinks.

**Comment by antihero6713** [comment]
Going to close this for now. until fishing or something comes a long that would warrant it. Japanese place will work for now
