### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by XcarFace** [InZidiuZ/legacy-assets-issue-tracker#299]
**Name:**
XcarFaceYT#3707

**Summary:**
I was Suggesting to add Bravado hellfire Car at PDM at category of Muscles. As its an New car People have much interest to have it on Our Server mainly Legacy BD  

**Link:**
https://www.gta5-mods.com/vehicles/2019-bravado-gauntlet-hellfire-w-o-splitter

**Reason:**
Its been a Long time at PDM no New Vehicles r not coming as a good percent of players wanted it i am Suggesting to add this car on Behalf of them

**Comment by AdeptCL** [comment]
As mentioned a lot previously, the current PDM setup does not allow custom vehicles to be added as it crashes the server.
If anything, this would be an exclusive vehicle.

**Comment by TCruxer** [comment]
As stated above imports may not be added to PDM in the current framework.  A hellcat will however be considered in the exclusive dealership in the future. Closing this for now.

Cruxer
Lead Asset Dev
