### ISSUE TITLE
Vehicle Plates

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/legacy-assets-issue-tracker#3]
**Name:**
Badwolf#3160

**Summary:**
I think i would be great to be able to replace your cars plates with fake plates. Criminals can put fake plates on their cars and use them for criminal activities. But since trunk inventory are plate number based they should be able to take them of and keep the plates so they can reuse them any time or dispose of them if they no longer need them. I also think that customs plates should be a thing where players can request for custom plates of their choice.
I think plastic could be used to forge them by who ever is given the job to make fake plates and this could be a company so they buy plastic of citizens. The last part of the suggestion could be ignored if its not a great one but i think fake and custom plates is a very great addition 

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
This give criminals a nice option to use their own custom built or enhanced cars in criminal situations rather than stealing cars of the road that might not be good enough for the act they want to perform with it

**Comment by InZidiuZ** [comment]
Hey,

Custom plates probably won't be a thing, and you also posted this at the wrong GitHub page, this one is for assets and strictly that, not scripting-related server suggestions.

**InZidiuZ**
*OP-FW Developer*
