### ISSUE TITLE
Different Character, Same Shell?

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/legacy-assets-issue-tracker#30]
**Reporter:**
Who is reporting this? Please include discord name.
Hunter Zurxey - Zurxey#2607
**Summary:**
Write a summary of what you're experiencing.
I logged into Legacy today on my Criminal character, I spawned in at legion as I just was released from prison. I ran over to the train station, and changed over to my cop character. When I did so and went to my Motel in Poleto Bay, I was teleported into the same shell as my criminal character while on my cop character. But once I left the city and came back on my criminal character, I was teleported into MY DIRECT Shell, and it had the items I left in there from my cop character. I then logged back into my cop character, and it fixed itself. I now have my actual hotel room (#1) 
## Additional Information
At first I didn't think anything of it believing it was just Hex ID based, and was something implemented, but the more I thought about it, the less sense it made. 
I transferred a few items over to my criminal characters room from my cop character (it was just my citizen ID) this was all by accident, and has now been removed from Criminal, and moved back to my cop character. 
**Screenshots:**
If suitable, include some screenshots.
Below is linked a YouTube Video: 
https://www.youtube.com/watch?v=W2ltt-tNdII&feature=youtu.be
FOOTAGE IS UN-EDITED.
**Notes:**
For anything else noteworthy.
This was all by mistake, I was not trying to transfer items between characters, as I know it's strictly prohibited. Once I noticed that this didn't make any sense (Which took under a minute) I immediately jumped into the support help room, spoke to M-21, and A-10. They released me, and let me transfer my Citizen ID back to my cop character, and also M-21 reported it directly to InZidiuZ

**Comment by Karpenkooo** [comment]
Hey,

Thank you for reporting this issue to staff straight away and for recording a video of the whole issue. However i don't think there's much that i can do. It's all up to the big dawg  @InZidiuZ .

_Karpenko_

_**OP-FW Vehicle Developer**_

**Comment by ZurxeyH** [comment]
> 
> 
> Hey,
> 
> Thank you for reporting this issue to staff straight away and for recording a video of the whole issue. However i don't think there's much that i can do. It's all up to the big dawg @InZidiuZ .
> 
> _Karpenko_
> 
> _**OP-FW Vehicle Developer**_

Yes, I do understand where you're coming from! This was intended for the big man himself, I do know he's on vacation at the time, but its worth noting for when he gets back.
