### ISSUE TITLE
[imports/police] New DOC Livery

### ISSUE THREAD

**Issue by Jacobbss1729** [InZidiuZ/legacy-assets-issue-tracker#300]
**Name:**
Jacobbb#4927

**Summary:**
Add livery for Department Of Correction (DOC) 

**Link:**
https://www.lcpdfr.com/downloads/gta5mods/vehiclestextures/26154-san-andreas-department-of-corrections/

**Reason:**
I think you can add livery for DOC due to the fact that many unit e.g. FIB, SAHP and SASP have their livery in addition to DOC.

**Comment by joevapes3** [comment]
I plan on adding at least 1 or 2 of the custom police vehicles to get a DOC livery, but they will be custom made for legacy, not premade. Thank you for the suggestion.
