### ISSUE TITLE
Suggestion | Son's President + Vice President Cut Texture Update

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#301]
**Name:**
Adept | AdeptCL#0402

**Summary:**
Replacing the current Son's President and Vice President cut textures with the files provided.

**Link:**
Download [here](https://drive.google.com/drive/folders/1up0UaHbtzFWfEJkfMZUfA0VdYSEIHT_p?usp=sharing).

**Reason:**
Goes along with the storyline of MCs where certain individuals obtain new patches that have certain meanings (accomplishments).

**Comment by TCruxer** [comment]
This has now been added and will be in the next asset merge update.

Cruxer
lead asset dev
