### ISSUE TITLE
[maps/recording_studio] New recording Studio

### ISSUE THREAD

**Issue by PeteDollas** [InZidiuZ/legacy-assets-issue-tracker#302]
**Name:**
PeteDollaz#1452
**Summary:**
I would like to see an actual recording studio in the city.
**Link:**
https://www.gta5-mods.com/maps/record-studio-multimedia-aera-ymap

https://www.fivem-store.com/product/recording-studio-v1/

**Reason:**
I feel we need a recording studio because me and a couple other friends plan to start a music label and record some songs of people in the city and have one of my DJ's play their songs at events and shout them out so everyone can see what people are capable of. We can record a couple songs a week with anyone in the city and then play their song at VU one day and we would let them know we playing their song so their friends can hear it aswell and everyone would have a great time hearing themselves on the music rotation at these events.

**Comment by antihero6713** [comment]
Rockford records has been added to the city
