### ISSUE TITLE
maps/map-mosleys  addition of parking box  and  car  wash on the inside side

### ISSUE THREAD

**Issue by ayushpandit99** [InZidiuZ/legacy-assets-issue-tracker#303]
**Name:**
Who is suggesting this? Please include discord name.
ayushpandit99#1842

**Summary:**
Write a short summary of what your suggestion is about.
as the new shop is added the inside side of the new repair shop not used much as there is no parking box available and its hard to perfectly align without the parking box .. so that review thing comes.. 

**Link:**
If there are any links to what you're suggesting, please add them here.
https://imgur.com/a/60hczbc
**Reason:**
Why would your suggestion be a good addition to Legacy?
addition of the parking box and car wash on inside side will help better use of the inside area of the new mechanic shop.

**Comment by XwezioGH** [comment]
The shop's intended repair location is at the front, where there is 4 boxes on the floor which indicate where the cars should be repaired.


Xwezio
Asset Developer
