### ISSUE TITLE
Add Chicken farm/factory

### ISSUE THREAD

**Issue by robin-401** [InZidiuZ/legacy-assets-issue-tracker#304]
**Name:**
Robin 

**Summary:**
There is a place where there is full of Chickens..u can add chicken farm and factory. And dealer.as a result there will be a. New job.

**Comment by TCruxer** [comment]
This doesn't fall under the asset department as it is script related. I will therefore be closing this. Please reopen another suggestion in the correct OP-FW issue tracker.

Cruxer
Lead Asset Developper
