### ISSUE TITLE
[peds/*] Combat Medic Helmet

### ISSUE THREAD

**Issue by unknownwooptiewoop** [InZidiuZ/legacy-assets-issue-tracker#305]
**Name:**
Who is suggesting this? Please include discord name.
Wes#7238

**Summary:**
Write a short summary of what your suggestion is about.
With the recent addition of the "Medic" squad within the Special Operations Bureau/SWAT, I've made a little edit in one of the current helmets that we use. If this could be added as an "additional" form of texture on top of the ones we already have then that'd be great.
**Link:**
--FILES ADDED--

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be a good addition to RP and especially the SWAT RP as it would provide a more clear overview of who is the "Medic" during a situation as it would make them stand out a bit more.
[SWAT.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5908609/SWAT.zip)

**Comment by MetaHatter** [comment]
Closed as not is added to #524
