### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by VICKYSOHAM** [InZidiuZ/legacy-assets-issue-tracker#306]
DON BADSHAH 

I WANT A CAR IN THE CITY THAT CAR NAME IS TATA HARRIER .

**Link:**
https://www.bing.com/images/search?view=detailV2&ccid=bY7YN%2fgh&id=D8E0B98CAF6037D7196BC512437FDB495E0B3963&thid=OIP.bY7YN_gh8LCuzy2V7B8-rQHaEk&mediaurl=https%3a%2f%2fimages.carandbike.com%2fcar-images%2flarge%2ftata%2fharrier%2ftata-harrier.jpg%3fv%3d40&exph=741&expw=1200&q=tata+harrier&simid=608027151899954370&ck=925706EB8DDFD25E2E7B1B68F6A8EA32&selectedIndex=4&FORM=IRPRST&ajaxhist=0.

**Reason:**
BECAUSE IT IS MY FAVOURITE CAR FOR THAT REASON I WANT THIS CAR IN THE CITY

**Comment by TCruxer** [comment]
Your suggestion was noted. I will however be closing this for now. Please follow the template next time you make a suggestion.

Cruxer
Lead Asset Dev
