### ISSUE TITLE
"The Santoskaya Bratva" Vest

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/legacy-assets-issue-tracker#307]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a short summary of what your suggestion is about.
Replacement of current La Familia Vest to this one from our gang rebranding 
**Link:**
If there are any links to what you're suggesting, please add them here.
[Vest.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/5939185/Vest.zip)

**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by TCruxer** [comment]
This has been added and will be in the next asset merge update.

Cruxer 
Lead Asset Dev
