### ISSUE TITLE
[peds/clothes_addon] Masks for chubby faces

### ISSUE THREAD

**Issue by icyWsi** [InZidiuZ/legacy-assets-issue-tracker#309]
**Name:**
Who is suggesting this? Please include discord name.
ICN: Wasil Buhmide DEiscord name: Icy.Ws#4593

**Summary:**
Write a short summary of what your suggestion is about.
would be cool if every people can wear wich mask they want no matter if they got a chubby face or not. because if u wear a bandana but you got a chubby face it wil stick out of the mask. 

**Link:**
If there are any links to what you're suggesting, please add them here.
i dont have any links.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Because then people can wear what they want to waer and not only animals masks because thats the only mask that fit chubby face.

**Comment by kodaaaaaaaaaa** [comment]
ive been dealing with my face poking through masks since ive joined and seeing them a bit bigger to fit bigger faces would be amazing

**Comment by DaxterPancake** [comment]
Two maks have been added with this next clothing update that work with bigger faces, a bandana and a buff style one.

In the future we may look into ways that allow bigger faces to fit in all masks but until then, this will be closed.

Cheers,
Daxter.
Project Manager.
