### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/legacy-assets-issue-tracker#31]
**Reporter:**
Who is reporting this? iGreatWhite#3018

**Summary:**
The Elegy Retro Custom with Engine 3 and turbo seems to only grasp 125 to 130. It also climbs very slow once it hits 70. I do not know what happened this car used to do 160 when i test drove it and now it seemed not worth it after purchasing.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

I've noticed that there's been a lot of complaints about vehicle handlings. I've not edited them as of recently so i'm thinking that there's an issue streaming them to the FiveM server. we can only really find out once the owner is back from his well deserved holiday. 

_Karpenko_
