### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by SmythGG** [InZidiuZ/legacy-assets-issue-tracker#310]
My discord is SmythGG#8913 feel free to dm me with any questions.

Summary
Be able to buy boats as a civilian.

Being able to buy a boat would give people more reason to see a dealership worker and it would help greatly with scuba diving.

**Comment by TCruxer** [comment]
Hey,
This is not asset-related as it requires scripting please repost following the template in the proper issue tracker.

Cruxer
lead asset dev
