### ISSUE TITLE
Racing suggestion

### ISSUE THREAD

**Issue by DebeliFetus** [InZidiuZ/legacy-assets-issue-tracker#312]
**Name:**
Zenica Bahud  Tin#0524

**Summary:**
My suggestion is to make /race have a few checkpoints so we can make a race go in circles or a few places and not just the fastest way to the waypoint. Or to make a app in phone that already has some race tracks in it around the city or around the whole island or  something close to that. And also make possible a few circles if the race is going in circles.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
I think it would be helpful to add one more purpose to all the fast cars in the city. I also think people would enjoy some racing with skill and not that the fastest car wins because it is in a line with not much turns.

All best,

Tin

**Comment by TCruxer** [comment]
Hey,
This is unfortunately not asset-related please re-open your suggestion in the correct issue tracker thank you,

Cruxer
Lead Asset Dev

**Comment by DebeliFetus** [comment]
Hey

And could you help me by saying where do i have to write suggestion like
that or a link.

Best,
Tin

pet, 12. velj 2021. u 04:10 TCruxer <notifications@github.com> napisao je:

**Comment by KookieNCoffee1** [comment]
Don't worry too much about creating another issue about it, there have been a few. Here's a link to one posted in March of last year :)
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/840
