### ISSUE TITLE
Haircut suggestion

### ISSUE THREAD

**Issue by T4NZIM** [InZidiuZ/legacy-assets-issue-tracker#313]
**Name:**
Who is suggesting this? Please include discord name.
TᴀɴZɪM#3642

**Summary:**
Write a short summary of what your suggestion is about.
If possible please add these haircuts, thank you :)

**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/player/slicked-back-hair-for-mp-male-1-0
https://www.gta5-mods.com/player/mp-male-miguel-s-hair
https://www.gta5-mods.com/player/starboy-hairstyle-for-mp-male
https://www.gta5-mods.com/player/freemode-male-haircut-from-agent-14
https://www.gta5-mods.com/player/short-male-hair-for-mp-male

**Reason:**
Why would your suggestion be a good addition to Legacy?
Just some good looking haircuts

**Comment by TCruxer** [comment]
More hairstyles have been added and will be available in the next asset merge update.

Cruxer 
Lead Asset Dev
