### ISSUE TITLE
[imports/civilian_*] Motorcycle side car

### ISSUE THREAD

**Issue by SmythGG** [InZidiuZ/legacy-assets-issue-tracker#315]
**Name:**
Who is suggesting this? Please include discord name.
SmythGG#8913

**Summary:**
Write a short summary of what your suggestion is about.
Adding a side car to certain motor cycles like the gang motor cycles and the tricycle

**Reason:**
Why would your suggestion be a good addition to Legacy?
i just think it would be a cool addition to motorcycles and allow a third person to ride which is always handy. i talked to a several other people in the city and they agree it would be really cool to have that option in the city

**Comment by joevapes3** [comment]
While it would be an amazing feature to have, it's something that doesn't exist within the game or 3rd party modded so far that I can find. So it's something that isn't possible to bring to Legacy at this time. If you are able to find vehicle model model that has these features, feel free to open up new github post as a suggestion at that time.
