### ISSUE TITLE
[imports/civilian_*] Vehicles colors/livery/interiors flashing and changing

### ISSUE THREAD

**Issue by ainstaylor** [InZidiuZ/legacy-assets-issue-tracker#317]
**Reporter:**
ainstaylor#3692

**Summary:**
I have noticed on some cars the exterior and interior flash and change colour. I think it might be cars that are exclusives. I've noticed it mainly on the Mercedes AMG however an Audi was also once flashing.  I've also noticed it on a pick up truck which I think is an exclusive car.

## Additional Information

**Screenshots:**
https://medal.tv/clips/44547838/d1337xHHVPur
https://medal.tv/clips/44548411/d133785k2eIX

**Notes:**
I've also noticed that the interior of burger shot also once did this.

**Comment by ainstaylor** [comment]
Clearing cache and reloading fixes this issue, and I've not noticed this happening in a while, could it be a problem at my end?

**Comment by Nuziatella** [comment]
This is a corruption on local client cache. Clearing cache will correct this issue.
