### ISSUE TITLE
Bug report :- Game Crashing when entering House.

### ISSUE THREAD

**Issue by MrFraud** [InZidiuZ/legacy-assets-issue-tracker#318]
**Reporter:**
! Mr Fraud#8891

**Summary:**
Game Crashing When I enter my house. I showed this problem in support team of legacy bangladesh. They Said that its a bug issue and told me to report it to github.

## Additional Information

**Screenshots:**
https://drive.google.com/file/d/1ZVrX5agM6JE0U9CwjRoqYuk9RZpfP9o_/view?usp=sharing

**Notes:**
Please fix this issue as fast as possible. Because I am Keep Paying the rent for the house.

**Comment by InZidiuZ** [comment]
This issue tracker is for assets only. Please redirect your issue to the op-framework issue tracker.
