### ISSUE TITLE
[maps/*] Sandy Shores/Paleto Bay impound lots

### ISSUE THREAD

**Issue by RyanShlap** [InZidiuZ/legacy-assets-issue-tracker#319]
**Name:**
Who is suggesting this? Ryan Shlap#0001

**Summary:**
Write a short summary of what your suggestion is about.

My suggestion it possibly could be an easy addition. It just involves adding an impound lot in Paleto and possibly Sandy or over towards great ocean highway to kind of spread it out. Me personally I do a lot of towing up around the north, not that I don't mind driving to the city but with how things are with a lot of towing and mechanics it would be a really good solution.

**Link:**
If there are any links to what you're suggesting, please add them here.
No links just a request for an addition.

**Reason:**
Why would your suggestion be a good addition to Legacy?

I personally think it would be a good addition for the purpose of where some people base their roleplay. I basically run the mechanic shop for Sons of Legacy and the fact that I like cleaning up around the highways and getting rid of blown up vehicles and such it would make sense for me to go back up to Paleto impound lot if we had one. Same goes for Sandy for the gangs and civs that like to situate around that area.

**Comment by AdeptCL** [comment]
A feature like this will/should spread the activity for BCSO too around the North. Having the option for actual tow drivers to take part in that activity when their shops are Northern based.

**Comment by teddythedev** [comment]
Love the idea. I think this would be great especially as Teddy as Governor is trying to make use of the whole state and as more and more people are heading up into Sandy/Paleto there are a lot of crashed cars that tow truck drivers aren't going to take since it's such a long drive down into town.

**Comment by XwezioGH** [comment]
Thank you for your suggestion.

I have found suitable locations for impound lots and forwarded them to InZidiuZ.

I will be closing this.

**Xwezio
Asset Team**
