### ISSUE TITLE
Addition of car controls UI ( Suggestion)

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/legacy-assets-issue-tracker#322]
**Name:**
Who is suggesting this? Please include discord name.
GUARDIAN#7777
**Summary:**
Write a short summary of what your suggestion is about.
Addition of a UI that displays buttons that are actually present in cars such as the engine start/stop windows , and also the door locking and lighting controls.
**Link:**
If there are any links to what you're suggesting, please add them here.
https://gyazo.com/f8555a608d249dc2b67e0fb418265e10
https://forum.cfx.re/t/release-standalone-vehcontrol-nui-menu/1746959
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would be a good addition to legacy as this would be more realistic and convienient for everyone and this could possibly create more realistic rp for the players.

**Comment by InZidiuZ** [comment]
This issue tracker is for assets only. Please redirect your issue to the op-framework issue tracker.
