### ISSUE TITLE
[vehicles/police] Bringing back the LSPD fleet

### ISSUE THREAD

**Issue by ENDLE5S** [InZidiuZ/legacy-assets-issue-tracker#323]
**Name:**
Who is suggesting this? Please include discord name.

ENDLE5S†#1842

**Summary:**
Write a short summary of what your suggestion is about.

Hi, I'm a member of the polish server community and I'm writing that suggestion on behalf of the server's police department. We were talking about our police lately, and all of us are confused about us driving SASP vehicles with LSPD badges on our arms. So our suggestion and request is to bring back the LSPD cruisers fleet. I know that it is the big deal because it would change Police Department on every server around the world but I still think it would be a good idea.

**Link:**
I haven't got a link to your templates.

**Reason:**
We think that our suggestion would be a good change because maybe you guys don't really care about your uniforms etc. but here in Poland people are different. Sometimes some random pedestrians are laughing at us because they don't know if we're LSPD or SASP(yes, they are paying attention to it, and so do we).

Peace out.

**Comment by gighul** [comment]
My entry as polish subdivision manager.

My police fellows pointed out that most of clothes (vast majority of it) is with LSPD emblems. So they would like to ask if its possible to bring back old LSPD liverys (they have been replaced with SASP mostly, some for sheriffs, high way patrol and others -whcih they use of course) but for roleplay point of viev it would be more immersive to have these as well.
(or have both old LSPD ones with the new ones, two birds one stone)

This simple adjustment may significantly improve RP thread on all servers.

**Comment by joevapes3** [comment]
LSPD will not be expanded beyond the vanilla variant, and no custom LSPD liveries or clothing will be added at this time. Thanks for the suggestion
