### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by XwezioGH** [InZidiuZ/legacy-assets-issue-tracker#324]
**Name:**
Xwezio#8203

**Summary:**
Re-assignments of real estate blocks.

**Link:**
https://cdn.discordapp.com/attachments/629754738895749132/818464951244554260/unknown.png

**Reason:**
Throughout legacy's real estate system being a thing it has been really hard to for southside groups to purchase a block worth 100k a week, Simply a real estate company does not want to purchase a block worth 100k when its very difficult to fill all house and bring in a profit.

This can be very limiting for southside groups to evolve when they are living out of their vans and it makes no sense for a Balla to be living in a forum apartment.

With the current gang system and limitations on group numbers its simply unrealistic to expect a Southside 'hood' group to upkeep 100k per week and manage to help the realtors sell 20 houses in a not so desirable location. 

I propose that the grove street gets split into two parts, the culdesac and the main road you can see the two different sections in the pictures linked above.

**Comment by PoshoGH** [comment]
+ 1

**Comment by TUKTUKTAI** [comment]
+1

**Comment by InZidiuZ** [comment]
This issue tracker is for assets only. Please redirect your issue to the op-framework issue tracker.
