### ISSUE TITLE
[imports/*] Allow lowrider custom vehicles to change the interior color

### ISSUE THREAD

**Issue by TUKTUKTAI** [InZidiuZ/legacy-assets-issue-tracker#325]
Name:
TUKTUKTAI#3145
Summary:
So what i noticed when purchasing a bennys gta car at pdm is that when u try and customize it u can only change the trim design  but not the interior colour, whilst in gta u can change the interior colour aswell of these lowrider vehicles. In the gta when u go into customizations there is a trim colour option on legacy u dont have that. So what I would like to see is that u can change the trim colour of these lowriders cars.

Link: https://cdn.discordapp.com/attachments/471788803254648842/818271946402693130/unknown.png

Reason:
I think this would be a very nice addon for people who like these lowrider cars. Cus it limits them from the colours and especially gang members aswell. I dont think its that hard to add in aswell but I might be wrong. All around I think it would be a nice thing for people who like these type of vehicles cus atm at pdm they all come in stock blue well most of them and u cant change the colour.

**Comment by Nuziatella** [comment]
This is a script related issue. Please submit your ticket over [here.](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
