### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by macanu** [InZidiuZ/legacy-assets-issue-tracker#326]
**Name:**
Who is suggesting this? Please include discord name.
Ayush. DC: 彡мαϲ∂єѕτяυϲτινє彡#7023
**Summary:**
Write a short summary of what your suggestion is about.
To include fishing and deep sea fishing as a job.
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
As there are a limited no. of white-collar jobs, this addition would help to increase the variety and interest of characters and would help them to increase their RP by doing this job in parties.

**Comment by InZidiuZ** [comment]
This issue tracker is for assets only. Please redirect your issue to the op-framework issue tracker.
