### ISSUE TITLE
Local Food Delivery Job

### ISSUE THREAD

**Issue by SmythGG** [InZidiuZ/legacy-assets-issue-tracker#327]
**Who is suggesting this? Please include discord name.**
Matthew Gibbs Taco Farmer Owner (SmythGG#8913)

My suggestion is about adding local food delivery jobs for Taco Farmer and Up n Atom like what Burgershot has currently. Burgershot can deliver food to locals and make good money off of that. Taco Farmer and Up n Atom doesn't have anything like that which is discouraging to the employees. I'm the owner of Taco Farmer and I would love for me and my employees to be able to go around to locals and legally deliver food. There are not enough legal jobs in the city once you have a government job.  

**Why would your suggestion be a good addition to Legacy?**
This suggestion would be a great addition to Legacy because it would add another LEGAL job to the server and give all the employees who work for Taco Farmer and Up n Atom more ways to do their job and make money.

**Comment by iMStokes** [comment]
Seconded. With reviews of official and unofficial businesses within the server - the work between Burgershot, Taco Farm and Up N Atom has been wonderful.  However it is noticeable that although the RP and services of all three can be immaculate towards other players - having an option to do a delivery service in their downtime to make some money to continue to supply deliveries and these options to everyone would be ideal.
