### ISSUE TITLE
New interior of prison [MLO]

### ISSUE THREAD

**Issue by kloocek** [InZidiuZ/legacy-assets-issue-tracker#329]
**Who is suggesting this? :**
klocek#7082

**Summary:**
New interior MLO for Bollingbroke Prison

**Link:**
[Youtube](https://www.youtube.com/watch?v=1r4qfFCjwag&ab_channel=UncleJust)

**Reason:**
I don't know what about Legacy US but in our country (Poland) a lot of people like prison roleplay so we want to add a new interior that gives us more options for roleplay.
Especially that the administration plans to do the JailRP event, in actually interior there are not too many interesting rooms.

In new we have a lobby, place with things of prisoners, reception, cells, gym, canteen with kitchen, the magazine of kitchen small education room,  whole power place with pipes and other stuff, small ward from which you can see all the cells and much much more.

**Comment by ENDLE5S** [comment]
That's a good idea. I think it would give everyone a lot more options to have fun while roleplaying. It would also allow players to interact with Law Enforcement even more.

**Comment by gighul** [comment]
Totaly agree, we have experience may problems with present interior (being hit by police bat causes people to disappear and many other troublesome issues).

These circumstances prevents me (as project manager of polish subdiv) from organizing the event which will meet the expectations of people, simply to be appreciated.

Please kindly have a look on that and assist us.

**Comment by Nuziatella** [comment]
This will be looked into. Appreciate the suggestion!

**Comment by InZidiuZ** [comment]
This has since been added.
