### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by macanu** [InZidiuZ/legacy-assets-issue-tracker#331]
**Reporter:**
Who is reporting this? Please include discord name.
MacDestructive#7023
**Summary:**
Write a summary of what you're experiencing.
I was unable to see and collect the airdrop from ocean although I tried 2 times
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue tracker is for assets only. Please redirect your issue to the op-framework issue tracker.
