### ISSUE TITLE
[maps/observatory] Interior for the Observatory

### ISSUE THREAD

**Issue by calzonie** [InZidiuZ/legacy-assets-issue-tracker#332]
**Name:**
Calxonie#7215

**Summary:**
Interior for the Observatory

**Link:**
https://www.gta5-mods.com/maps/villa-vinewood-observatory 
https://www.gta5-mods.com/maps/galileo-michael-mansion

**Reason:**
I think the BBC (bad bitch coven) love the location of the observatory, we enjoy it so much, but with little to interact with mainly being the fault of where we chose I think adding something like the above links not exactly, I couldn't find anything to truly fit, but having something like that would help our roleplay out so much we already spend a lot of time there but when hunger thurst atm stuff come calling we gotta run, also a lot of the girls fall off a lot causing a lot of trips to pillbox and delaying a lot of what we try to get done, I don't expect the links above to be great examples its all I could find sorry about that, ima also aware it's not easy, but having a hub in any way the girls could have people come to and see us and have chairs, etc would be great, appreciate your time, or even a space to hold meetings and group, or even ritualistic things since the BBC are witches.

**Comment by kloocek** [comment]
It looks disgusting and destroys the entire observatory, biig -1

**Comment by calzonie** [comment]
> It looks disgusting and destroys the entire observatory, biig -1

I do agree I just really couldn't find anything at all as an example so just sent what I could find

**Comment by XwezioGH** [comment]
Thank you for your suggestion

I agree with the comments on this post, the following mlos do ruin the aesthetic of the observatory, i will keep and eye out for mlos that fit the location a little better.

**Xwezio
Asset Team**
