### ISSUE TITLE
Bug report Taxi cab purchase Bug

### ISSUE THREAD

**Issue by Khasnuwr** [InZidiuZ/legacy-assets-issue-tracker#333]
**Reporter:**
arif#1111

**Summary:**
 taking taxi job, I go to buy Cab, it is showing I bought the taxi money also cut from me but I don't have the ownership of the cab.

## Additional Information

screen resolution : 1920*1080

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
Other players facing this bug.

**Comment by InZidiuZ** [comment]
This issue tracker is for assets only. Please redirect your issue to the op-framework issue tracker.
