### ISSUE TITLE
[peds/*] Update fleet and possibly the EUP

### ISSUE THREAD

**Issue by kloocek** [InZidiuZ/legacy-assets-issue-tracker#334]
**Name:**
klocek#7082

**Summary:**
Update fleet.

**Link:**
[EUP 9.0](https://www.youtube.com/watch?v=EIZd8DHoNLM&ab_channel=TheUnderbellyOfParadise)
[LSPD](https://www.gta5-mods.com/vehicles/lspd-lssd-pack)
[SAHP](https://www.gta5-mods.com/vehicles/sahp)
[BCSO](https://www.gta5-mods.com/vehicles/blaine-county-sheriff-pack-bozza-et-al)
[FIB](https://www.gta5-mods.com/vehicles/fib-unmarked-pack-add-on-sound)
[BEARCAT](https://www.gta5-mods.com/vehicles/vapid-tarv-lore-friendly-bearcat-add-on-eup)

**Reason:**
Why would your suggestion be a good addition to Legacy?
Updating the fleet and EUP would give a lot of new roleplay, especially since the vehicles from the links are interesting, they would give a lot of immersion on their own, the latest EUP can enter with them.

**Comment by BUSZ3KK** [comment]
+1. I think this is a very good proposition, it will add a nice thread to the roleplay additionally the models are well optimized.

**Comment by Saszkaxd** [comment]
This is very good idea!

**Comment by pepaj420** [comment]
https://gta5-mods.com/vehicles/retro-blanie-county-sheriff-office-replace-add-on-rde-style https://gta5-mods.com/misc/realism-dispatch-enhanced and some proper helicopter and boat for BCSO in this packs.
![7f8d80-sheriff_boat](https://user-images.githubusercontent.com/74616932/111989417-02592180-8b12-11eb-8ee4-bada8ae04fef.png)
![e100e9-bcso18](https://user-images.githubusercontent.com/74616932/111989429-071dd580-8b12-11eb-8c11-f360fe0f6c03.png)

**Comment by joevapes3** [comment]
The latest EUP pack is going to be added sometime here in the near future. Exactly when it get's added is still being determined. As far as the vehicle fleet, we will be mostly utilizing the redneck models that were purchased for the server, but there will be a few additions coming soon as well. Thank you for the suggestion.

**Comment by Djmeowzle** [comment]
> The latest EUP pack is going to be added sometime here in the near future. Exactly when it get's added is still being determined. As far as the vehicle fleet, we will be mostly utilizing the redneck models that were purchased for the server, but there will be a few additions coming soon as well. Thank you for the suggestion.


Will there be any Hi-Vis or "Press/News" Related vests?
