### ISSUE TITLE
[maps/bean_machine] The Bean Machine Improvements

### ISSUE THREAD

**Issue by sleighwhite** [InZidiuZ/legacy-assets-issue-tracker#335]
**Name:**
sleighwhite#8707

**Summary:**
As the owner of The Bean Machine, there are a few suggestions that I'd like to make to help facilitate RP:
- If we could create a bar icon on the map for BM that would be great. It's hard for people, especially new players, to find the location of BM, which affects attendance of our events. 
- If we could get an in-game drink item for "coffee" that'd be awesome! We're a coffee shop that can't sell coffee, and it limits what we're able to RP. The item could make people faster (simulating caffeine) or it could work like the alcohol items (meaning there's an emote for drinking it, but it doesn't affect thirst). There's already a "/e coffee" emote. 
- It would be nice if we could have door locks on the building itself. Most other whitelisted businesses are able to lock their doors for safety and RP purposes. 
- It would be nice if we could have a "local" barista available at the BM. Similar to how The Yellow Jack and the bar at the VU have. We could sell donuts, wonderwaffles, water, coke, and potentially coffee if we get an in-game item. 

**Link:**
N/A

**Reason:**
I believe that the Legacy staff has been trying to encourage players to "hang out" and RP across the city (and thus staying away from hotspots like PillBox). Adding more features to an existing business that's still in the city, but not directly downtown or in the southside could really help spread out the RP and create more jobs and events.

**Comment by InZidiuZ** [comment]
All of these except for the third one (with adding door integration) needs to be redirected to the op-framework issue tracker. I'll see about getting the doors done soon.

**Comment by InZidiuZ** [comment]
Door locks have now been added.
