### ISSUE TITLE
VU Improvements Suggestion

### ISSUE THREAD

**Issue by sleighwhite** [InZidiuZ/legacy-assets-issue-tracker#337]
**Name:**
sleighwhite#8707 on behalf of Erin#1000

**Summary:**
There are a few suggestions that we've gathered for the VU that we think would increase the level of RP for this establishment:
- With the new VU interior, we'd also like to suggest that we take advantage of the interior by adding more emotes/mechanics for actually dancing on the pole. Please see link below.
- Within the dressing room backstage, it would be really helpful if there was a changing area available for dancers so that they don't have to run across the street in their dance outfits. 
- If we could also have some sort of storage available in bars for managers/owners to access, that'd be really helpful as well.  

**Link:**
https://youtu.be/o9UV9tdLU30?t=39

**Reason:**
Adding additional mechanics can increase RP scenarios and an exchange of money across the city which can also add to more RP. We believe that the VU is a successful business within the city that facilitates a lot of RP and relationship-building. Investing time/dev work in an establishment like this one will continue to add to that.

**Comment by InZidiuZ** [comment]
This issue tracker is strictly for asset suggestions. This interior has since been added, so will close this. The other changes would need to be suggested in the op-framework issue tracker. (though most of them have already been done.)
