### ISSUE TITLE
[peds/*] Additions

### ISSUE THREAD

**Issue by MikaChanPL** [InZidiuZ/legacy-assets-issue-tracker#338]
**Name:**
Mika-Chan#8925

**Summary:**
Here is my proposition about new wearing for man and woman. I think, they will give some fresh look for our servers. If my suggestions will be interesting for you, i can give you more ads. Hope you guys enjoy! 

**Link:**
https://pl.gta5-mods.com/player/oversized-hoodie-for-mp-female
https://pl.gta5-mods.com/player/very-long-hairstyle-for-mp-female
https://pl.gta5-mods.com/player/long-wavy-hairstyle-for-mp-female-jaagoda
https://pl.gta5-mods.com/player/corset-dress-for-mp-female
https://pl.gta5-mods.com/player/pull-dress
https://pl.gta5-mods.com/player/beautiful-long-hair-for-mp-female-c427438f-6a0c-427b-8f0b-ca66b46ca42c
https://pl.gta5-mods.com/player/holografic-geek-arcade-texture-mp-female
https://pl.gta5-mods.com/player/jacket-space-unicorn-texture-for-female-and-male-mp-spaceunicorn
https://pl.gta5-mods.com/player/allian-dress-fivem-sp
https://pl.gta5-mods.com/player/short-skirt-for-mp-female
https://pl.gta5-mods.com/player/hairband-for-mp-female
https://pl.gta5-mods.com/player/platform-high-heel-boots-mpfemale
https://pl.gta5-mods.com/player/ripped-jeans-mp-female
https://pl.gta5-mods.com/player/baseball-pack-mp-female
https://pl.gta5-mods.com/player/mp-female-high-heel-lace-boots
https://pl.gta5-mods.com/player/cros-strapped-top-for-mp-female
https://pl.gta5-mods.com/player/long-double-color-curly-hair-with-buns-for-mp-female
https://pl.gta5-mods.com/player/short-top-for-mp-female-583e274c-e8ca-4ad9-bc9e-5c3902710f7d
https://pl.gta5-mods.com/player/nike-sb-dunk-low-ben-jerry-s-chunky-dunky
https://pl.gta5-mods.com/player/short-top-for-mp-female-moko
https://pl.gta5-mods.com/player/cute-coat-for-mp-female
https://pl.gta5-mods.com/player/be-happy-hoodie-for-mp-male
https://pl.gta5-mods.com/player/tokyo-wangan-hoodie-for-mp-male
https://pl.gta5-mods.com/player/denim-skirt-and-tube-top-mpfemale
https://pl.gta5-mods.com/player/super-long-hair-for-mp_female
https://pl.gta5-mods.com/player/mp-female-dress-pack-3-dresses
https://pl.gta5-mods.com/player/nike-air-more-uptempo-supreme-mp-female-male

**Reason:**
I want to add some fresh look to our servers. Everyone will benefit from it.

**Comment by Saszkaxd** [comment]
Good idea

**Comment by DaxterPancake** [comment]
Your suggestions have been looked at and potentially added.

Thank you!
Daxter.
**Project Manager.**
