### ISSUE TITLE
[maps/?] Addition of an ATM at the dock repair shop

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/legacy-assets-issue-tracker#339]
**Summary:**
Addition of:
-clothes changer blip inside of mechanic for its employees
-ATM inside/outside
-Garage blip outside 
-Locker inside

Location:
![obraz_2021-03-23_141912](https://user-images.githubusercontent.com/71882732/112152596-bde98680-8be2-11eb-8d5d-3bdf619ffee9.png)

**Reason:**
Owner of mechanic located at screenshot mentioned above asked us that for RP purposes it would be great to have these 4 features in it.
Often people that comes here for repair forget the fact there is no ATM nearby.
Garage addition would be great as well for people who would just log out there,
Outfit blip for its employees to change clothes that they have at their /outfits disposal.
Same goes for locker in side, for employees

**Comment by InZidiuZ** [comment]
All of these except for the ATM suggestion should be redirect to the op-framework issue tracker.

**Comment by XwezioGH** [comment]
Thank you for the suggestion, This has now been added.

I will be closing this now.

**Xwezio
Asset Team**
