### ISSUE TITLE
[maps/sandy_shores_medical_center] Sandy Shores Medical Center

### ISSUE THREAD

**Issue by bossace** [InZidiuZ/legacy-assets-issue-tracker#340]
**Name:**
Bossace#7764      Marty Sanders EMS in legacy

**Summary:**
To open up Sandy Shores Medical Center to allow spawning/repair of vehicles and allow patients to check in and be healed. 

**Link:**
No link

**Reason:**
As an EMS I have been making significantly more calls up to the Sandy Shores area as of late. Unfortunately for the patients they are roughly smack in the middle between Paleto Bay Hospital and Pill Box making their drive to either location long and dangerous depending on how locals are. Opening a location there would make it easier for citizens of Sandy Shores to be treated for simple injuries as well as easier for ems to drop the patients off at a more central location. It would also be a great place to get a new ambulance or helicopter if needed. With The Yellow Jack and Flywheels now there we are seeing a big population growth and visitor growth to the area so I feel it benefits everyone.

**Comment by bossace** [comment]
Additional thought I had: As our EMS staff grows as well it would be great if possible to be able to go on and off duty there as well as doctor duty for that specific location as well with changing rooms etc vending machine, water fountain. So we can offer everything pillbox does in sandy without it feeling "inferior"

**Comment by InZidiuZ** [comment]
An interior for a hospital at Sandy Shores has now been added.
