### ISSUE TITLE
Lockable Doors - Save Lock Data

### ISSUE THREAD

**Issue by cammyyeet** [InZidiuZ/legacy-assets-issue-tracker#341]
**Name:**
Hey it's me Cammpy hashtag0001

**Summary:**
My suggestion is a very small feature however will improve the roleplay of many individuals majority of them being business owners.

Business owners like to lock their doors when they're not actively hosting events which boosts popularity when they do open their doors. Currently upon server restart doors all reset to being open and people go into these areas and use them without permission from the business owners. It's currently very hard to combat this.

**Link:**
No Links.

**Reason:**
It would be a great addition as it would provide a buzz when a certain location is open or an event is being hosted at that venue. It also gives business owners the option to keep people out of their venue when they're not there.

**Comment by InZidiuZ** [comment]
Are you suggesting that door states should save over restart, or that the default lock setting for some of these (unknown) interiors should be set to locked?

**Comment by cammyyeet** [comment]
> Are you suggesting that door states should save over restart, or that the default lock setting for some of these (unknown) interiors should be set to locked?

Door states saving over restart.

**Comment by InZidiuZ** [comment]
That would be something for the framework issue tracker. Please redirect this issue to [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
