### ISSUE TITLE
[maps/boat_shop] Boat shop

### ISSUE THREAD

**Issue by cammyyeet** [InZidiuZ/legacy-assets-issue-tracker#344]
**Name:**
Cammpy hashtag0001

**Summary:**
BOATS! I think this would create so many new experiences for everyone who plays Legacy. This would really open doors for a lot of individuals.

**Link:**
https://github.com/esx-framework/esx_boat

**Reason:**
Boats are awesome! It will also give people something to spend their money on when they've got 1Mil+ sitting in their bank. This could create new and fun experiences for players such as Yacht Parties, boat trips around the city, police chases, and more,

**Comment by InZidiuZ** [comment]
Are you suggesting an interior for a boat shop/garage, or n actual shop and garage to be added?

**Comment by cammyyeet** [comment]
A shop and garage to be added. I guess that would mean finding an interior for a shop also.

**Comment by InZidiuZ** [comment]
An interior for a boat shop is something that would have to be suggested here, though the other things and the actual features for it would have to be suggested [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).

**Comment by cammyyeet** [comment]
> An interior for a boat shop is something that would have to be suggested here, though the other things and the actual features for it would have to be suggested [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).

Oops, my bad! I have submitted a suggestion in that department.

**Comment by DaxterPancake** [comment]
Thank you for your suggestion!

Closing in favour of #432 to keep the github clean.

Cheers,
Daxter.
