### ISSUE TITLE
[maps/?] Parsons Rehabilitation Center interior offices for ems use

### ISSUE THREAD

**Issue by bossace** [InZidiuZ/legacy-assets-issue-tracker#345]
**Name:**
Bossace#7764 Marty Sanders

**Summary:**
Interior offices or space over at the Parsons Rehabilitation Center ems facility for use of therapy sessions and helping other patients with mental care needs.

**Link:**
N/A

**Reason:**
As an aspiring Therapist (currently applied) I want to be able to have therapy sessions and help individuals in the city. I've noticed sessions are now taking place at pillbox where things can get very loud and chaotic. I feel since Parson is under EMS control as listed in my handbook it would be a great opportunity for us to have enclosed offices up there so we can have a more secluded one on one sessions without the heavy traffic at pillbox. This could allow a more peaceful and tranquil therapy sessions for patients and able to help any of them with other pressings mental needs and give clients/patients a much better and therapeutic experience.

**Comment by bossace** [comment]
Sorry for the late additional idea. Could a sign on and off duty be added there if we are just coming on to do a session and I’m curious if the main building should be open and used for support groups etc while the smaller building houses offices for more one on one? I’m not the most creative person with design just thoughts

**Comment by XwezioGH** [comment]
Thank you for this suggestion I believe I have a suitable interior ready for this.

I will make a start when I finish my current project.

Xwezio 
**Asset Team**

**Comment by bossace** [comment]
Would it be possible to add a sign in/off duty as well as able to pull out hospital vehicles? Just want to be able to sign on up at parsons if I am coming on duty to only do a session so I don't need to go to pillbox to sign on. I also sometimes use the ems explorer to transport patients to and from sessions especially in cases of physical therapy.

**Comment by antihero6713** [comment]
This has been pushed to the test server for now.

**Comment by antihero6713** [comment]
Sounds like we are good to go. Should show up soon

**Comment by bossace** [comment]
Thank you so much you and the whole team are greatly appreciated!
