### ISSUE TITLE
Can We Reduce the Amount for PD Tracker and MicroPhone

### ISSUE THREAD

**Issue by imDazzler** [InZidiuZ/legacy-assets-issue-tracker#346]
**Name:**
Dazzler#0176

**Summary:**
The Amount for PD Vehicle Tracker & PD Microphone is 2000$ Right Now Can You reduce It to 500 or 700 as If we use this in Any Kind of Situation This is very Costly to Purchase.

**Link:**
No

**Reason:**
As its not possible to Purchase this items as its too Much Costly

**Comment by InZidiuZ** [comment]
This issuer tracker is for assets only. Please redirect this to [this](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) issue tracker.
