### ISSUE TITLE
[imports/job_vehicles] Burger Shot vehicle(s)

### ISSUE THREAD

**Issue by Bhavesh02** [InZidiuZ/legacy-assets-issue-tracker#348]
Bhavesh (UnPredictable#7237)
Who is suggesting this? Please include discord name.

I would like to suggest you to add a burgershot van/Scooty which people will get from burgershot once they have BurgerShot ingame role same as weazel news/Taxi job. Secondly a personal locker inside the burgershot store where people can store items. In india subdivision we have made a custom menu for people to increase burgershot rp. Some items like fries and energy drinks are not available in burgershot store to the person needs to go and buy that fromthe nearest grocery store. Lockers can help them to store those items in it. Thanks :)
Write a short summary of what your suggestion is about.

1.https://cdn.discordapp.com/attachments/518528722849234944/825436849568874621/ffcc2651b0107bc85b9a4db32944b5bb7c57f6b8.jpeg
2.https://cdn.discordapp.com/attachments/518528722849234944/825437072742416484/c9cdf8eccca55095481c89398763d7a36fba932b.jpeg
If there are any links to what you're suggesting, please add them here.

This changes will help in increasing burgershot RP. 
Why would your suggestion be a good addition to Legacy?

**Comment by Nuziatella** [comment]
Custom Burger Shot Van added.
