### ISSUE TITLE
Semi trucks from trucking

### ISSUE THREAD

**Issue by KrigTroff** [InZidiuZ/legacy-assets-issue-tracker#349]
**Reporter:**
Who is reporting this? krigtroff#8460 Please include discord name.

**Summary:**
I have been doing the trucking job ever since I join this server, I have noticed that regardless of what amount of fuel in the truck, when you get it repaired it goes back to about 64% every time. Even if you have a fuel tank or on empty, also the semi trucks from the job are way slower then local semis by almost 50+ mph, top speed I got my truck to is about 120, but local semis I can get to 160+ on the same route from vine wood toward sandy or grapeseed. Also in the custom shops when trying to add neon lights to the truck it takes you under the world and can’t see anything, then when you come back or exit out in that view the truck becomes scuffed and you can get back in the truck and it’s stuck.

## Additional Information 

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
So to be honest for truckers it’s also most better to steal a local truck and do runs if you want the speed versus using the one you buy.

**Comment by InZidiuZ** [comment]
This issue tracker is for assets only. Please redirect this issue to [this](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) issue tracker.
