### ISSUE TITLE
Headlight issue on the Ferrari 488

### ISSUE THREAD

**Issue by PhizioN** [InZidiuZ/legacy-assets-issue-tracker#35]
**Reporter:**
PhizioN#4462

**Summary:**
I would like to start off by saying that I'm not sure if these issues are related - but the headlights on the Ferrari 488 do not show up at all, even when they are at full blast, they are not on. I notice in certain instances, if I reverse, the headlights cause some insane deformities on my screen, almost a blinding, blurry, light source. It doesn't happen every time I get in the car, but I notice it can either happen when I lock the doors, or I reverse, it's never both at the same time.

For what it's worth, I have heard of other people experiencing the same phenomenon with the R-35. I let a few people drive the 488, and they all said there was something seriously distorted with the lights after they were in the same area as my car or even drove it.

## Additional Information

**Screenshots:**
Attached, is a short video of what happens.

**Notes:**
It doesn't happen every time you get into the car, but when it does happen, it doesn't stop. 
It wasn't only the 488, I experienced this with my friends GTR R-35 when he just pulled in the area, I wasn't even in his car but I was blinded by his car, some how.
[488.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/3497778/488.zip)

**Comment by Karpenkooo** [comment]
Hey,

Are you using any sorty of Visual Mod for GTA 5?
That maybe what's causing the blinding light. I tried to replicate however i wasn't able to get the same result. 

_Karpenko_

**_OP-FW Vehicle Dev_**
