### ISSUE TITLE
[peds/*] Additions

### ISSUE THREAD

**Issue by MikaChanPL** [InZidiuZ/legacy-assets-issue-tracker#350]
**Name:**
Mika-Chan#8925

**Summary:**
Here is my suggestion for a new outfit for men and some for women. I think they will give our servers a bit of a fresh look. If you find my suggestions interesting, I can give you more ads. Before that, I added clothes for women. Now I want to diversify something for men. Hope you like it!

**Link:**
-----MALE-----
https://pl.gta5-mods.com/player/custom-air-force-1-s-unreleased
https://pl.gta5-mods.com/player/highlife-hoodie-pack-fivem-ready-mp-male-quakex64
https://pl.gta5-mods.com/player/nike-air-force-1-g-dragon-peaceminusone-para-noise-2-0
https://pl.gta5-mods.com/player/flux-morz-t-shirt-pack-for-mp-male
https://pl.gta5-mods.com/player/hypebeast-crewneck-pack-supreme-off-white-palace-vlone-sp-fivem
https://pl.gta5-mods.com/player/2021-nike-dunk-colorways
https://pl.gta5-mods.com/player/custom-air-force-1-louis-vuitton-pack-quinziszn
https://pl.gta5-mods.com/player/supreme-camo-collection-hoodies-pants-any-character
https://pl.gta5-mods.com/player/jacket-samurai-lian
https://pl.gta5-mods.com/player/t-shirts-for-mp-male-fivem-ready
https://pl.gta5-mods.com/player/adidas-pro-bounce-2019-lows
https://pl.gta5-mods.com/player/nike-adapt-bb-nike-mag
https://pl.gta5-mods.com/player/asap-rocky-bomber
https://pl.gta5-mods.com/player/bomber-jacket-for-mp-male
https://pl.gta5-mods.com/player/gang-irmaos-metralha-mp-male
https://pl.gta5-mods.com/player/colored-head-bandanas-for-mp-male
https://pl.gta5-mods.com/player/2-shirt-textures-mp-male
https://www.gta5-mods.com/player/bandana-pack-mp-male-mp-female
https://pl.gta5-mods.com/player/fivem-ready-mp-hoodie-chinese-collection-ee23faba-fc2d-41a0-90c2-2c1f003d66ed
https://pl.gta5-mods.com/player/shirt-pack-01-for-mp-male
https://pl.gta5-mods.com/player/shirt-textures-mp-male
https://pl.gta5-mods.com/player/hollister-shirt-pack-mp-sp
https://pl.gta5-mods.com/player/fendi-x-balmain-sagged-jeans-mp
https://pl.gta5-mods.com/player/air-jordan-11s-mp-male
https://pl.gta5-mods.com/player/dior-shirt-pack-for-mp-male
https://pl.gta5-mods.com/player/nba-youngboy-shirts-for-sp-mp-fivem
https://pl.gta5-mods.com/player/mp-hoodie-pack-off-white-supreme-nasa-sp-fivem
https://pl.gta5-mods.com/player/trending-hoodies-mp-male
https://pl.gta5-mods.com/player/franklin-ralph-lauren-polo-hooded-jackets-new-upper
https://pl.gta5-mods.com/player/shirt-pack-for-sp-fivem-male-jeremydaking
https://pl.gta5-mods.com/player/short-hairstyle-for-mp-male
https://pl.gta5-mods.com/player/mp-ped-marko-s-yeezys-350-sply-texture-pack-sp-fivemready
https://pl.gta5-mods.com/player/hoodies-collection
https://pl.gta5-mods.com/player/supreme-jordan-1s
https://pl.gta5-mods.com/player/mp-gucci-space-snake-print-hoodie-fivem-ready
https://pl.gta5-mods.com/player/supreme-sweatshirt-pack
https://pl.gta5-mods.com/player/louis-vuitton-open-zip-jackets-pack-junghoj
https://pl.gta5-mods.com/player/it-boy-hoody-pac-2x-heavy-spoilers-merch

----FEMALE----
https://pl.gta5-mods.com/player/sport-dress-2
https://pl.gta5-mods.com/player/dress-for-mp-female
https://pl.gta5-mods.com/player/sweatshirt-texture-adidas-pack-for-female-mp-character-noviacadaver
https://pl.gta5-mods.com/player/cros-strapped-top-for-mp-female
https://pl.gta5-mods.com/player/short-skirt-for-mp-female
https://pl.gta5-mods.com/player/fluffy-dress-for-mp-female
https://pl.gta5-mods.com/player/inocent-hairstyle-for-mp-female-fivem-sp
https://pl.gta5-mods.com/player/brujah-boots-for-mp-feemale-fivem-ready
https://pl.gta5-mods.com/player/super-long-hair-for-mp_female
https://pl.gta5-mods.com/player/high-heels-boots-for-mp-female
https://pl.gta5-mods.com/player/short-outfit-dress-for-mp-female

---Male and Female---
https://pl.gta5-mods.com/player/universe-baseball-texture-for-female-and-male-mp-spaceunicorn
https://pl.gta5-mods.com/player/couples-sweater-for-mp-male-female-fivem-ready
https://pl.gta5-mods.com/player/unhappy-hoodie-mp-male-female
https://pl.gta5-mods.com/player/a-set-of-tracksuits-for-mp-female-male

----Accessories----
https://pl.gta5-mods.com/player/valentines-ring-fivem-sp
https://pl.gta5-mods.com/player/tiara-for-mp-female-glows-in-the-dark
https://pl.gta5-mods.com/player/fitted-hats-pack
https://pl.gta5-mods.com/player/shelby-s-scar-pack-fivem-ready-singleplayer

**Reason:**
I want to add some freshness to our servers. Next time, maybe I suggest some shoots for children, because a few people on the server are pregnant.
Everyone will benefit from this. <3

**Comment by DaxterPancake** [comment]
Thank you for your suggestions, They have been looked at and might be added in the future. 

Cheers,
Daxter.
**Project Manager.**
