### ISSUE TITLE
[imports/job_vehicles] Ice Cream Trucks/Ice Cream Food

### ISSUE THREAD

**Issue by mrfishess** [InZidiuZ/legacy-assets-issue-tracker#351]
Hi, My name is Tay and I play a character named Tiffany Kyrstallyne! Shes a peppy young lady who really hasnt figured out what she wants to do in the city yet but i have an idea~! Discord Fish#1561

I'd like to suggest adding icecream trucks to legacy! Because i think if she managed to open an icecream shop it would be so cute!!! Theres already a location for it (Which wouldnt be super important yet, to keep things simple.) and i think it would be a great addition to the server! Especially since we just recently added boomboxes just imagine an icecream truck flying down the street busting some cool copyright free song with people chasing after for icecream!!!

[https://www.gta5-mods.com/paintjobs/ice-cream-van-cherry-popper-ice-cream-company#comments_tab](url)

Something like the link above would be super cool, plus adding a dessert place to the city could really be cool! Ive been in the city around two months and i think having this as a buisness could be super benificial to the ever growing need for interaction and entertainment!!! Doing events on the beach and being able to keep the city lively wherever i go would be a dream of mine <3 Please consider adding the trucks and icecream! I also think if icecream were to be added that it would be interesting to keep it out of convinience stores (So the truck will be more exciting).

![icecream](https://user-images.githubusercontent.com/80552618/112784907-a0178980-9007-11eb-86f9-7f62b64bf6d9.PNG)

**Comment by bestdriverinthecity** [comment]
Sounds sick

**Comment by Nuziatella** [comment]
This vehicle has been added.
