### ISSUE TITLE
[peds/*] Clothes additions!!!

### ISSUE THREAD

**Issue by mrfishess** [InZidiuZ/legacy-assets-issue-tracker#352]
Hi Tay here again (Fish#1561) and a huge issue on legacy is clothing! We do have some pretty promising stuff but me and a couple of girls compiled a list of clothing for you guys to add! I dont know much about the modding of FIVEM or GTAV as a whole but ive recognized garments by these creators that you guys have added. I dont know what the difficulty in adding clothes is (Whether it be the actual process or finding clothes to add, but i hope this helps somehow!!!! We need more dresses for weddings and more hair for different vibes!

Female Outfits
https://www.gta5-mods.com/player/short-top-for-mp-female-654d321e-9941-43d9-b945-87fc53f98c85
https://www.gta5-mods.com/player/harness-top-for-mp-female
https://www.gta5-mods.com/player/jeans-dress-for-mp-female-sp-fivem
https://www.gta5-mods.com/player/off-white-hoodies-4-hoodies-total-replace-mp-male
https://www.gta5-mods.com/player/retexture-top-for-mp-female
https://www.gta5-mods.com/player/ensemble-angel-of-the-hell-fivem-sp
https://www.gta5-mods.com/player/summer-dress-for-female-fivem
https://www.gta5-mods.com/player/hairstyle-for-mp-female
https://www.gta5-mods.com/player/super-long-hair-for-mp_female
https://www.gta5-mods.com/player/cute-dress-mpfemale
https://www.gta5-mods.com/player/short-wavy-hair-for-mp-female
https://www.gta5-mods.com/player/knot-cropped-top-for-mp-female-moko
https://www.gta5-mods.com/player/short-laced-top-for-mp-female
https://www.gta5-mods.com/player/recolored-lingerie-for-mp-female
https://www.gta5-mods.com/player/mp-female-dress-pack-3-dresses
https://www.gta5-mods.com/player/innocent-angel-miller-s-mods
https://www.gta5-mods.com/player/nympho-dress-for-mp-female
https://www.gta5-mods.com/player/sports-bra-mp-female
https://www.gta5-mods.com/player/sports-top-mpfemale
https://www.gta5-mods.com/player/nympho-dress-for-mp-female
https://www.gta5-mods.com/player/short-top-for-mp-female
https://www.gta5-mods.com/player/saloon-dress-for-mp-female-sp-fivem
https://www.gta5-mods.com/player/top-for-mp-female
https://www.gta5-mods.com/player/short-outfit-dress-for-mp-female
https://www.gta5-mods.com/player/ripped-jeans-mp-female
https://www.gta5-mods.com/player/top-for-female-fivem-ready-sp
https://www.gta5-mods.com/player/open-back-tank-top-for-mp-female
https://www.gta5-mods.com/player/short-jeans-mp-female
https://www.gta5-mods.com/player/flexico-camo-bikini-pack-for-mp-female
https://www.gta5-mods.com/player/dress-for-mp-female-52b1c755-5028-43a6-8ea3-0707eb4645ca
https://www.gta5-mods.com/player/sneakers-with-socks-for-mp-female
https://www.gta5-mods.com/player/mp-female-bodysuit-top-textures-pack-1
https://www.gta5-mods.com/player/mp-female-high-heel-lace-boots
https://www.gta5-mods.com/player/leather-straps-for-mp-female
https://www.gta5-mods.com/player/basics-top
https://www.gta5-mods.com/player/basics-shorts
https://www.gta5-mods.com/player/basics-leggings
https://www.gta5-mods.com/player/belted-jeans-mp-female
https://www.gta5-mods.com/player/sports-top-mpfemale
https://www.gta5-mods.com/player/jeans-for-mp-female-adoramods
https://www.gta5-mods.com/player/cargo-pants-for-mp-female
https://www.gta5-mods.com/player/gucci-pants-for-female-sp-fivem
https://www.gta5-mods.com/player/high-heels-pack-for-mpfemale-part-1
https://www.gta5-mods.com/player/momiji-thongs-for-mpfemale
https://www.gta5-mods.com/player/momiji-tops-for-mpfemale
https://www.gta5-mods.com/player/mp-crop-hoodie

Hair:
https://www.gta5-mods.com/player/curly-hairstyle-for-mp-female
https://www.gta5-mods.com/player/double-bun-hairstyle-for-mp-female-jaagoda
https://www.gta5-mods.com/player/ponies-with-two-synthetic-braids-hairstyle-for-mp-female
https://www.gta5-mods.com/player/short-top-for-mp-female-jaagoda
https://www.gta5-mods.com/player/long-wavy-hairstyle-for-mp-female-jaagoda
https://www.gta5-mods.com/player/long-hairstyle-for-mp-female-ba0681c6-3c47-402f-ba4a-d5ce16ddab00
https://www.gta5-mods.com/player/long-hairstyle-for-mp-female-bf050e0e-ea6d-44eb-aa5d-269a090fb68e
https://www.gta5-mods.com/player/long-braid-for-mp-female
https://www.gta5-mods.com/player/cute-hairstyle-for-mp-female-h4iley
https://www.gta5-mods.com/player/ponytail-hair-for-mp-female
https://www.gta5-mods.com/player/long-haircut-with-highlights-for-mp-female
https://www.gta5-mods.com/player/another-braided-haircut-for-mp-female
https://www.gta5-mods.com/player/medium-long-hairstyle-for-mp-female
https://www.gta5-mods.com/player/long-hair-for-mp-female-and-mp-male-fivem-ready
https://www.gta5-mods.com/player/positions-hair-headband-for-mp-female
https://www.gta5-mods.com/player/long-hairstyle-for-mp-female-bf050e0e-ea6d-44eb-aa5d-269a090fb68e
https://www.gta5-mods.com/player/half-long-braid-sp-fivem
https://www.gta5-mods.com/player/long-fluffy-hairstyle-for-mp-female
https://www.gta5-mods.com/player/long-hairstyle-with-rose-for-mp-female
https://www.gta5-mods.com/player/messy-pinned-back-long-hairstyle-for-mp-female
https://www.gta5-mods.com/player/braid-with-long-hairstyle-for-mp-female
https://www.gta5-mods.com/player/hime-haircut-for-mp-female
https://www.gta5-mods.com/player/summer-hair-capatofmods
https://www.gta5-mods.com/player/flexico-camo-bikini-pack-for-mp-female
https://www.gta5-mods.com/player/ariana-ponytail-hair-custom-haircut-for-mp-female-singleplayer-fivem-ready
https://www.gta5-mods.com/player/long-wavy-hair-custom-haircut-for-mp-female-singleplayer-fivem-ready
https://www.gta5-mods.com/player/maiden-hair-custom-haircut-for-mp-female-singleplayer-fivem-ready
https://www.gta5-mods.com/player/long-bun-hair-custom-haircut-for-mp-female-singleplayer-fivem-ready
https://www.gta5-mods.com/player/long-braided-haircut-by-ajnamods-5204d3eb-ea8e-484d-b97d-befe4a9da6f6
https://www.gta5-mods.com/player/wavy-bangs-for-mp-female
https://www.gta5-mods.com/player/short-fluffy-wavy-hair-for-mp-female

Mens
https://www.gta5-mods.com/player/gang-kevlar-vests-mp-fivem
https://www.gta5-mods.com/player/nike-sb-dunk-lows-for-frank
https://www.gta5-mods.com/player/bomber-jacket-for-mp-male
https://www.gta5-mods.com/player/trending-hoodies-mp-male
https://www.gta5-mods.com/player/the-hundreds-shirt-pack-for-sp-fivem
https://www.gta5-mods.com/player/odd-future-shirts-sp-fivem
https://www.gta5-mods.com/player/short-hairstyle-for-mp-male
https://www.gta5-mods.com/player/the-supreme-x-cdg-hoodie-collection-mp-male-mp-female-replace-10-hoodies-total
https://www.gta5-mods.com/player/assc-x-undftd-x-f1-hoodie-fivem-ready
https://www.gta5-mods.com/player/tokyo-wangan-hoodie-for-mp-male
https://www.gta5-mods.com/player/vlone-t-shirt-pack-for-mp-male
https://www.gta5-mods.com/player/vlone-tee-pack
https://www.gta5-mods.com/player/vintage-band-t-shirt-pack-mp-male
https://www.gta5-mods.com/player/country-shirt-for-girls-mp-female
https://www.gta5-mods.com/player/nike-t-shirt-pack-zokeen
https://www.gta5-mods.com/player/bape-vlone-hoodie-for-mp
https://www.gta5-mods.com/player/shirt-pack-for-sp-fivem-male-jeremydaking
https://www.gta5-mods.com/player/the-hundreds-shirt-pack-for-sp-fivem
https://www.gta5-mods.com/player/drip-experiments-x-winson-reynaldi-eternal-flame-tee
https://www.gta5-mods.com/player/pack-nike-academy-jogger-pants
https://www.gta5-mods.com/player/t-shirt-pack-1-supreme-fw20-scarface-pulp-fiction-balenciaga-givenchy-bape-marvel-kamiseb
https://www.gta5-mods.com/player/fox-racing-hoodies-pack

Wedding
https://www.gta5-mods.com/player/wedding-dress-fivem-ready
https://www.gta5-mods.com/player/new-wedding-set-for-female-sp-fivem
https://www.gta5-mods.com/player/dress-for-mp-female-e95808cb-b1ab-4c73-80fc-6a2135bd0443
https://www.gta5-mods.com/player/long-dress-retexture-five-m

Necklace
https://www.gta5-mods.com/player/mp-silver-gold-necklace-with-heart-for-female
https://www.gta5-mods.com/player/corset-dress-for-mp-female

I hope this list isnt overwhelming in any way, we just think itll be a great idea and every person on legacy seems full excited and supporting!!! Please we need more dresses than the 6 we have.

**Comment by missskinny** [comment]
YES

**Comment by DaxterPancake** [comment]
Thank you for your suggestions! They have been looked at and may be added in the future.

Cheers,
Daxter.
Project Manager.
