### ISSUE TITLE
[imports/civilian_*] Car Interiors

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#353]
**Name:**
Riedling#8969

**Summary:**
Purchased a Ladybird (VW Beetle) from the import store.  The interior is unchangeable (yes ive checked all menus).  Kinda makes it silly to offer paint jobs (resprays) as the interior is burgandy and creme.  Would be great to have the interior match the primary and secondary colors.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
frankly, i wouldnt have bought this car if i knew it was going to be stuck with this interior.  I think more people would buy these cars if they could get this functionality...

**Comment by joevapes3** [comment]
Yes unfortunately that's the way the model came from it's creator, and there is no current way to add that function to the model in it's form. If in the future one with more options is added, it will be considered to replace that model with the current one. Until that time, there will be nothing that can be done.
