### ISSUE TITLE
Suggestion adding rewards or items to trucking missions

### ISSUE THREAD

**Issue by KrigTroff** [InZidiuZ/legacy-assets-issue-tracker#354]
**Name:**
Who is suggesting this? KrigTroff#8460 

**Summary:**
Looking over the life invader jobs and different things. Garbage job is the best for new players or just getting started because they can make quick cash and have random chances at getting items.(gold bars, zombie pills, etc...) which makes a lot of people pick that to make money and stay with it forever till they can get into more things. Where semi trucking get you only a small cash amount depends if on the run. We do not get any random items or anything special. A thought would be to add something to trucking to give other professions a chance to compete or spread the role play to other areas of the island. Making trucking bring something to the game that gangs or people would want. Stuff can always fall off the trucks. ( drugs, guns, jewels, parts for cars, etc). Or if not adding anything maybe increase the reward for trips. I have been trucking since I joined the legacy NA server cause it works for the background and RP I am doing. But so many people try it for a day or two till they find out what they can make from garbage. Currently I mean one zombie pill sells for about 2k. That is 4 -6 trips for truckers to go from all the way north to all the way south if lucky to get a load.

**Link:**
I do not have any links, but just adding something that is already in the game or adding something new to only semi trucking to make it worth having us around.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would spread the new players or people out across the land. Semi trucking takes you all over the island. It would cut down on all the garbage trucks and give another profession something unique to the role play and island.

**Comment by KrigTroff** [comment]
Just had another thought for the gangs , shops or government to add something to the server and role play. Maybe once a week or every few days. Have a special truck load to deliver to some group or store. That could pay out a good amount to the trucker and be stole by someone. Having the truck get hijacked. Some many people use small cars or cargo vans to move and store everything. Why not bring in truck loads of stuff for delivery. Ie guns, ammo, car parts, drugs... truckers could deliver these to different store or groups around the area.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. For framework-related issues, use [this](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) issue tracker.
