### ISSUE TITLE
Speed Cap on TrashMaster Trucks Suggestion

### ISSUE THREAD

**Issue by XMDSpectre** [InZidiuZ/legacy-assets-issue-tracker#355]
**Name:**
Who is suggesting this? Spectre#1694

**Summary:**
Garbage truck drivers are speeding everywhere around the City. Hitting cars, people, and buildings. Having a speed cap "chip" installed in the trucks to where they cannot go over 60 mph would help reduce this.

**Link:**
I do not have a link

**Reason:**
It would keep the people and places of Legacy safe when we have so many garbage people out on the road. Our trucks are tanks and if you get hit by one, you are more than likely going to have a really bad day. This offers a more safe work environment not only for us as drivers, but also for the communities that we work in.

**Comment by joevapes3** [comment]
With the latest handling adjustments the trashmasters top speed has been reduced, but was only reduced slightly as it was discussed that 60mph is too slow. More reductions to the speed will be made if it's deemed that it still doesn't match the current vehicle meta. This change will be live on the next server update.
