### ISSUE TITLE
[peds/*] children

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/legacy-assets-issue-tracker#356]
**Summary:**
As there are group of people who would like to play some sort of familly roleplay introducing new peds for kids would be great.

**Link:**
https://pl.gta5-mods.com/player/teenage-dante
https://pl.gta5-mods.com/player/dante-brother-child-skin
https://pl.gta5-mods.com/player/baby-add-on-ped
https://pl.gta5-mods.com/player/ellie-left-behind-v2
(could not found any young looking girl ped other than this)

**Reason:**
New possibilities of playing the family RP, distinguished into both genders. Great immersion potential.

**Comment by DaxterPancake** [comment]
I don't think child peds have a place in an RP server. Let alone an RP server that has drugs, sex, killing, etc.

**Comment by SmythGG** [comment]
@DaxterPancake I agree 100% with your comment.

**Comment by joevapes3** [comment]
Yah going whole heartedly agree with DaxterPancake, children ped models have no place in the current roleplay server.

**Comment by gighul** [comment]
Who says you have to use them? Its only a choice for people who would like

**Comment by DaxterPancake** [comment]
Other peoples roleplay effects every single person they come in contact with.

**Comment by Saszkaxd** [comment]
I think it's good idea to add child peds to server. It will add more advantage to play with other players like family and it will be more immersive. On polish legacy we have few families that want this peds to be in game.

**Comment by DaxterPancake** [comment]
This suggestion has already been given a no before from the owner of Legacy.

You can find that [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1210).

**Comment by joevapes3** [comment]
I allowed the discussion to continue for a bit, but on behalf of the asset team it's been decided that child peds will not be addended at this time. As the Inzidiuz has already expressed disinterest in allowing them on the server as seen in the post linked by DaxterPancake. We appreciate the suggestion.
