### ISSUE TITLE
[maps/gta] Vending Machine at Garbage HQ

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#358]
**Name:**
Riedling#8969

**Summary:**
requesting a Vending Machine be placed next to the water cooler, on the dock at Garbage HQ

**Link:**
N/A

**Reason:**
With as many people working there as we have, and no store close by, this would be very helpful to the garbage employees.  We also have dedicated security that can't leave the property on shift.  This would allow them to get some food.  Part of the items being requested by the new Garbage Management Company for its employees.

**Comment by antihero6713** [comment]
Issue has been fixed
![image](https://user-images.githubusercontent.com/25892037/122710724-de030300-d22e-11eb-9bc4-88f08e6c4991.png)
