### ISSUE TITLE
[vehicles/*] Slamvan speed glitch

### ISSUE THREAD

**Issue by LasqX** [InZidiuZ/legacy-assets-issue-tracker#359]
**Reporter:**
Who is reporting this? Please include discord name.
Lasq#3704
**Summary:**
Write a summary of what you're experiencing.
If u use tuner chip on slamvan custom there's a bug that allows to get speed boost by hitting brakes.
## Additional Information
To do this, just get slamvan custom, doesn't have to be modified, use tuner chip, then set brakes almost completly to front, accelerate to about 20mph, hit and hold brakes, and enjoy the ride to almost 300mph or more if u can handle it. I guess it's somewhat related to slamvans poor handling, and braking.
**Screenshots:**
If suitable, include some screenshots.
https://i.imgur.com/E6KDDq8.png
https://i.imgur.com/pSW8Z1T.png
https://i.imgur.com/7d4gl4J.png
**Notes:**
For anything else noteworthy.

**Comment by KrigTroff** [comment]
Also the slamvan has a braking issue, it basically does not brake at all regardless of what level of upgrade brakes you put on it. Can the brakes be adjusted at all. For the slam van, buy a new one from pdm drive and see how long it takes to slowdown, then go to customs shop put on brake upgrades and see it takes the same to slow it down.. I was just about to go and report this also for the tuner bug, after my original report about the braking. Thanks for posting this. I saw the same thing happen to my slamvan. It is crazy.

**Comment by joevapes3** [comment]
So the slamvan has a well known issue with it's top speed and brakes, we've been aware of this issue and have tried to address it. However it's a bug within GTA handling files that doesn't allow it be changed. I am currently looking for a solution but so far none have been found. The top speed isn't much a concern as the brakes don't allow it to stop once you get there. So it sorta cancels itself out and isn't op in any way. If a solution is found, you will see a post in the github commits.
