### ISSUE TITLE
Add house salesmen/house system

### ISSUE THREAD

**Issue by ZiiMs** [InZidiuZ/legacy-assets-issue-tracker#36]
**Name:**
Who is suggesting this? Please include discord name.

**Summary:**
So currently right now the only thing you can get is a apartment. Its just a plain apartment no-one can enter your apartment or interact with it. It would be nice if you could add houses. I understand adding houses throughout LS is very, VERY time consuming. So what I suggest is that you add a house salesmen who has perms to create houses and set all their interiors, entrance, exit points and garage making it so you dont have to go around placing houses.

**Link:**
I believe its kinda similar to NoPixel's house system.

**Reason:**
I believe this would add alot of depth to RP, it would allow for another business to open up and allow for people to RP in houses.

**Comment by SATIN187** [comment]
Houses are in development right now. Ben the owner is on vacation right now but it is being worked on
