### ISSUE TITLE
[maps/gta] ATM Ace Liquor Sandy Shores

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/legacy-assets-issue-tracker#360]
**Name:**
Who is suggesting this? Please include discord name.
iGreatWhite#0999

**Summary:**
Write a short summary of what your suggestion is about.
An ATM added to the Ace Liquor in Sandy Shores.

**Link:**
If there are any links to what you're suggesting, please add them here.
N/A

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would make sense to have an ATM at this store since there is many things that may require you to bring money. Plus a lot of people come to the store to buy food and medkits.

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/123879869-999ef380-d90f-11eb-96c9-c363a984e7a0.png)
Already there
