### ISSUE TITLE
[maps/mirror_park_tavern] Remodel the interior or mirror park tavern and add workstations

### ISSUE THREAD

**Issue by nikkoendres** [InZidiuZ/legacy-assets-issue-tracker#361]
**Name:**
[T-604] Nikko Endres#1581

**Summary:**
The Mirror Park Tavern has just recently been recognized by the state as a functional bar that can be owned and events hosted from such. The current interior of the Mirror Park Tavern is crimescene like with broken bottles everywhere and bloody boot prints on the floors and walls. I am asking for the Tavern to be cleaned up interior wise and have at least one workstation added. I am just suggesting an interior remodel but am completely for a complete redesign I just want to give out the simplest ideas that would require the least effort.

**Link:**
https://www.youtube.com/watch?v=mPTllt8dPZk
something along those lines like I said would be a complete makeover and would be awesome but I would be satisficed with something as simple as cleaning up all the mess on the interior and adding a workstation.

**Reason:**
I am currently the owner of Mirror Park Tavern and hosting events inside the Tavern are a nightmare and most of the time they are hosted outside due to the interior being so cramped and having no work stations for anyone to attend giving no reason to be inside in the first place. I feel like a redesign entirely would also help bring more traffic around mirror park as it being one of the top 5 most popular neighborhoods yet no one ever has a reason to stay around.

**Comment by MalcolmFrosty** [comment]
I am the new Owner / Manager of this tavern and we would still love a remodel. Hopefully not a LOST MC bar,  If possible would love to have an upstairs or downstairs that can be locked.

**Comment by MalcolmFrosty** [comment]
Any news on this? :/  Been waiting to put a lot of RP into this.

**Comment by DaxterPancake** [comment]
Unless you can find an interior you would like to be used, we currently do not have a map developer that can custom make something for you. Creating interiors is also a lot of work so although it may be nice to have a two story interior custom made for you, that may not be possible, especially for free.

These things also take time so even if you found a new interor you'd like to be used, it may not be added instantly.

Regards,
Daxter.
Project Manager.

**Comment by MalcolmFrosty** [comment]
https://www.gta5-mods.com/maps/mirror-park-tavern

**Comment by DaxterPancake** [comment]
That is not the correct type of map file.

When an suitable map comes up, we will make sure it gets added.

Until then, I cannot give you an ETA.

**Comment by MalcolmFrosty** [comment]
Thanks. So the one that was previously posted, there's no way to just remove the LOST MC signage? https://www.youtube.com/watch?v=mPTllt8dPZk

**Comment by Nuziatella** [comment]
> Thanks. So the one that was previously posted, there's no way to just remove the LOST MC signage? https://www.youtube.com/watch?v=mPTllt8dPZk

Correct as it's rendered into the frame and we currently do not have a map developer.

**Comment by Nuziatella** [comment]
Tavern has been replaced.
