### ISSUE TITLE
[imports/civilian_*] Hype cars suggestion

### ISSUE THREAD

**Issue by kloocek** [InZidiuZ/legacy-assets-issue-tracker#362]
**Name:**
klocek#7082

**Summary:**
Some hype cars, what will be nice in a new pack of Car Dealer

**Link:**
https://www.gta5-mods.com/vehicles/2013-mercedes-amg-c63-w204-facelift-add-on-black-series-brabus-tuning
https://www.gta5-mods.com/vehicles/mercedes-s-class-w222-wald-black-bison
https://www.gta5-mods.com/vehicles/bmw-m4-gts-liberty-walk
https://www.gta5-mods.com/vehicles/bmw-m6-prior-design-edition-2013-add-on-fivem
https://www.gta5-mods.com/vehicles/2016-honda-nsx-nc1
https://www.gta5-mods.com/vehicles/2019-ferrari-488-pista-spider-animated-roof-add-on-template

/link from gta5modhub because on gta5mods author delete his account\ 
http://www.gta5modhub.com/mercedes-benz-g65-amg-2-0/

**Reason:**
They are nice, have a visual option, and if you need to add new cars, these links will be useful.

**Comment by gighul** [comment]
+1

**Comment by MikaChanPL** [comment]
+10000

**Comment by ainstaylor** [comment]
Definitely the BMW

**Comment by Nuziatella** [comment]
Suitable vehicles from this list have been added. When and where they'll be added can be discovered at a later date. Thank you for our suggestion.
