### ISSUE TITLE
Suggestion/ Can You Remove ClipBoard Emote for Pressing U

### ISSUE THREAD

**Issue by imDazzler** [InZidiuZ/legacy-assets-issue-tracker#363]
**Name:**
Who is suggesting this? Please include discord name.
Dazzler#0176

**Summary:**
Write a short summary of what your suggestion is about.
Just a Suggestion to Remove To Clipboard Emote For ID Check Because whenever anyone Press U the Other RP Player gets affect by that and sometime they stop continuing the RP. 

**Link:**
If there are any links to what you're suggesting, please add them here.
no i dont have

**Reason:**
Why would your suggestion be a good addition to Legacy?
Using Clipboard in between RP many time refuses others RP.

**Comment by DaxterPancake** [comment]
I have been able to catch people abusing the mechanic by using the U menu to look through walls to see if there is anyone inside buildings. The emote is needed to ensure that people are not powergaming but I do agree that it can be extremely immersion breaking.

**Comment by Jeetez** [comment]
In a server which ain't whitelisted. It's important to have the clipboard thing as many new players lit do metagaming. Or the rule breakers who check weather there is a admin present or not. It becomes easier to catch people like these by the clipboard emote so.

**Comment by imDazzler** [comment]
> In a server which ain't whitelisted. It's important to have the clipboard thing as many new players lit do metagaming. Or the rule breakers who check weather there is a admin present or not. It becomes easier to catch people like these by the clipboard emote so.

i was talking about to remove the emote on we can keep the U but without Emote

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for issues not related to assets.
