### ISSUE TITLE
[maps/harmony_gas_station] New business idea. 

### ISSUE THREAD

**Issue by MafieCoding** [InZidiuZ/legacy-assets-issue-tracker#365]
**Name:**
Mafie#5389 ( Malakai Jackson | Mafie ) 

**Summary:**
Been thinking about a business that would both benefit the employees of it, and the server as a whole. 

A mechanic shop at the Harmony gas station, with a scrap yard at the neighboring lot. 

The mechanic/gas station would be as they normally are, just need edited to be functional. 

But the scrap yard is something new. 

Would have tow drivers employed for both normal tow operations. But also an ability to tow an abandoned vehicle (within acceptable RP scenarios) to the scrap yard and be able to "Scrap it". Similar to "Chop" But with no chance at anything other than a few materials. Wouldn't want it to be able to break the material rates.

So different sizes cars offer a set amount of materials each, based on size. A compact would only offer a small batch of like 5 random materials. Where a Trash Truck would offer more like 15. 

This scrap option would only be available to employees of this company, but other tow drivers could bring a car there and sell it to the scrap yard. So if a tow company in the city had a vehicle ,they could bring it up and offer it to scrap attendant. Who could have a price book based off the potential materials gained. 

Example - A compact would be like $200-300 giving the scrap mechanic a small margin for profit. 

Also as a way to limit number of cars scraped. These scrap mechanic would need to keep a log of every vehicle they scrap/tow. With the plates/info of situation. Like where was vehicle, why was it towed, why was it not taken to mechanic shop. 

And in the case of player owned vehicles, was an attempt made to contact the owner? Which may require a script to be able to look up plates and see owners number?

It's a big idea, and I really wanna get it in the city. 

**Reason:**

I think it would offer another dynamic to the towing/material system. 
Most materials would be used by the gas station/shop mentioned. 
Would offer another way to help keep the city streets cleaned of wrecked locals and player abandoned vehicles. 
By limiting the use to the company, and requiring paperwork for each vehicle, would hinder the abuse of the system by towing random parked cars. 
Any employee found abusing would be fired and reported to the authorities for theft of public property.

**Comment by rajbastakoti** [comment]
isnt the towing system already enough , as it gives 50-100 $ for even for local tows , 
this is nice idea but isnt it already enough ?

**Comment by MafieCoding** [comment]
> isnt the towing system already enough , as it gives 50-100 $ for even for local tows ,
> this is nice idea but isnt it already enough ?

I am just trying to find a way to integrate the towing into a more immersive and incorporating RP scenario. Sure you can tow meaningless cars all day. But what if there was a way to make it more in depth. A way to make towing something people may actually enjoy, instead of the same old repetitive motion?

**Comment by KrigTroff** [comment]
For the more in depth role play it really depends on the people and players. Example when a can smacks into a wall or anything. Most people shake it off and continue down the road like your car is magical cause you just landed that huge jump or did not die from hitting a tree or another car at 100 mph. But IRL you know the car would be damaged. You should call a tow truck. Role play taking it to a shop instead of just the impound. Tow drivers could charge you some money for the tow. I have done this on so many other server and cities as a tow drive. Just need the people in the city to think more that way then, oh my car can hit anything and drive off.

**Comment by MafieCoding** [comment]
> For the more in depth role play it really depends on the people and players. Example when a can smacks into a wall or anything. Most people shake it off and continue down the road like your car is magical cause you just landed that huge jump or did not die from hitting a tree or another car at 100 mph. But IRL you know the car would be damaged. You should call a tow truck. Role play taking it to a shop instead of just the impound. Tow drivers could charge you some money for the tow. I have done this on so many other server and cities as a tow drive. Just need the people in the city to think more that way then, oh my car can hit anything and drive off.

ABSOLUTELY. And my scrap yard idea is more for the abandoned cars, the scuffed cars, and such. But I totally agree, we need to instill more of a realistic mindset for RPers. I want on no way to take normal tows away from them. But to offer another option, especially during "crackhead" hours.

**Comment by KrigTroff** [comment]
I totally agree on that statement.

**Comment by InZidiuZ** [comment]
You posted this in the assets-related issue tracker. Are you suggesting that an interior is to be added near the Harmony gas station?

**Comment by MafieCoding** [comment]
> You posted this in the assets-related issue tracker. Are you suggesting that an interior is to be added near the Harmony gas station?

I was thinking an interior to the Harmony Gas station, with a company ready to pay the needed 50k that is, which would allow for a potential mechanic shop there. 

But also was wanting to know if there would be a way of implementing the scrap yard idea in a legal manner. Allowing for a new potential for RP for tow drivers. I am willing to discuss this part in a voice chat at some point if ever available.

**Comment by InZidiuZ** [comment]
I know there was just an improved interior added for the LSC near Route 68, though nothing for the Harmony gas station. At least not yet.

> But also was wanting to know if there would be a way of implementing the scrap yard idea in a legal manner.

Is this an interior, or a feature?

**Comment by MafieCoding** [comment]
Mainly would be a functional interior so that a mechanic shop would be opened at this location.

The scraping would be a new feature, but it is something I am unsure of how to properly explain. Also I am unsure of what is actually possible with scripts and such.

**Comment by MafieCoding** [comment]
I have a crew together and we are getting the 50k fee together to apply for the official buisness license for the location.

**Comment by MafieCoding** [comment]
Would I be able to message someone on discord to ask more about the limitations with scripts and work on possible details for my scraping idea?

**Comment by XwezioGH** [comment]
There has just been a renovation to the route 68 mechanic shop and there is multiple unused mechanic shops around the city, I feel adding another one is unneeded at this time.

Xwezio
**Asset Team**
