### ISSUE TITLE
Weazel News Police Scanner Suggestion 

### ISSUE THREAD

**Issue by WeazelMicky** [InZidiuZ/legacy-assets-issue-tracker#366]
**Name:**
TwonMcFry#2849 

**Summary:**
911 calls to be broadcasted to News Journalists as they are to law enforcement 

**Link:**
I don't have one  

**Reason:**
If registered Journalists or even select (Real) Journalists could have access to a police scanner or receive 911 call alerts, this would make for a better RP. The current system has Journalists just chasing around cops to get footage to report the news. This isn't really feasible due to how quick the police cars are, and the journalists only get the starting or, if they are lucky, the end of a robbery. Having 911 calls go to journalists would give them the ability to search the area that home robbery's, shootings, etc., are taking place in and capture footage to either report in the news and sell the footage to the police or even other criminals. The RP possibilities would be endless.

**Comment by DaxterPancake** [comment]
I love this suggestion, but I need you to follow the correct format, please.
The correct format can be found [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose).

Thanks,
Daxter.
**Project Manager.**

**Comment by WeazelMicky** [comment]
Thank you for considering this. Will the edit I just made work or would you like me to create a new one?

**Comment by DaxterPancake** [comment]
Nope, this should be fine, thank you!

**Comment by joevapes3** [comment]
My thoughts on this is if the system were to ever exist, then it would have to have server rules built around it, that if you're using such a scanner, that you only are doing the news job, and not for doing any type of crime. As well as no alerting someone via radio, text, or phone calls about police being alerted to crime. Other than that it would be awesome to have news arrive to scenes and create RP out the scenarios.

**Comment by DaxterPancake** [comment]
I actually just realised that you've posted this in the asset tracker, this needs to be in the normal op-fw github which can be found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).

Sorry for the confusion, this github is for cars, clothing and maps.

Thanks,
Daxter.
**Project Manager.**

**Comment by WeazelMicky** [comment]
No..done
