### ISSUE TITLE
[maps/dispensary] Rebrand

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/legacy-assets-issue-tracker#367]
**Name:**
Who is suggesting this? Please include discord name.
o0ochanceo0o#5735

**Summary:**
Weed shop near MRPD was approved as an official business today. Would like the following:

Parking either in front (replace red curb in front or add stalls in alley)
Add a water jug / fountain for thirsty customers / employees
Rename storefront from Best Buds to Green Wonderland
Add map location
Make storage / lockers for employees to store weed for sale

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
The business is approved and I received the license today. Would like the shop functional for myself and my employees. Also need ability to give keys to employees and remove from fired employees (as needed).
![Wide Logo](https://user-images.githubusercontent.com/81762234/114632186-6091a400-9c7b-11eb-9933-35aedfd57729.png)

**Comment by vicarsrd** [comment]
@XwezioGH please message me in Discord if you have any questions on what we need to get this up and running.

**Comment by XwezioGH** [comment]
This has been completed

I will close this now.

Xwexio
**Asset Team**
