### ISSUE TITLE
Weazel News Van Upgrades 

### ISSUE THREAD

**Issue by WeazelMicky** [InZidiuZ/legacy-assets-issue-tracker#369]
**Reporter:**
TwonMcFry#2849

**Summary:**
3 days ago, I upgraded my Weazel News Van in LS Customs, and today it's showing everything like I didn't. 

## Additional Information

**Screenshots:**
Included

**Notes:**
I upgrade the suspension, armor, and turbo 3 days ago to my Weazel News Van, and today it's showing that it never happened. Cost about $17k. News reporters do not make enough money to do it again. :>(
![Suspension](https://user-images.githubusercontent.com/82047690/114644878-fa6a4880-9c9d-11eb-93d3-8fbbea274871.png)
![Armor](https://user-images.githubusercontent.com/82047690/114644883-fdfdcf80-9c9d-11eb-9d14-d221c53ace04.png)
![Turbo](https://user-images.githubusercontent.com/82047690/114644888-00f8c000-9c9e-11eb-94e1-d5bbfebb52ec.png)

**Comment by InZidiuZ** [comment]
This is a script issue and should be posted in the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
