### ISSUE TITLE
[maps/gta] ATM at Yellow Jack

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/legacy-assets-issue-tracker#370]
**Name:**
Who is suggesting this? Please include discord name.
Daxter#7158

**Summary:**
Write a short summary of what your suggestion is about.
Add an ATM to Yellow Jack.

**Link:**
If there are any links to what you're suggesting, please add them here.
N/A

**Reason:**
Why would your suggestion be a good addition to Legacy?
We hold a lot of events at Yellow Jack and always have to tell people to go elsewhere when they want to take out money. Most other bars/clubs (Bahama Mamas & Vanilla Unicorn) have ATMs at their club. The ATM could easily be placed on the outside of the building near the door, or anywhere you find appropriate.

**Comment by Nuziatella** [comment]
This has been added.
