### ISSUE TITLE
Suggestion to add cream-cookie to the game

### ISSUE THREAD

**Issue by Saszkaxd** [InZidiuZ/legacy-assets-issue-tracker#371]
**Name:**
Saszka#1942

**Summary:**
Add cream-cookie as a new food item to the game.
**Link:**
I think it don't need 3D model. But here is screen of this item.
![kremowka](https://user-images.githubusercontent.com/80044399/114706200-f8010080-9d28-11eb-95f9-32e5e771903d.jpg)

**Reason:**
It will add more food to the game and it can be added to bean machine as item that can be sold to players.

**Comment by DaxterPancake** [comment]
I'm just curious.. Why specifically this..?

**Comment by Saszkaxd** [comment]
> I'm just curious.. Why specifically this..?

I think it's most popular cookie in coffee house.

**Comment by InZidiuZ** [comment]
That looks delicious. You posted this in the wrong issue tracker, though. Post it in the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) instead.
