### ISSUE TITLE
[imports/civilian_*] BMW vehicles

### ISSUE THREAD

**Issue by ainstaylor** [InZidiuZ/legacy-assets-issue-tracker#372]
**Name:**
Ainstaylor#3692

**Summary:**
Two BMW vehicle imports

**Link:**
https://www.gta5-mods.com/vehicles/bmw-x6m-f16
https://www.gta5-mods.com/vehicles/bmw-m5-f90-2018-add-on-hq-template

**Reason:**
BMW's are one of the most popular cars available around the world today. Legacy only has one which is the i8 which I feel is actually one of the worst BMW cars. The BMW M5 and X6M are popular and attractive. 

BMW drivers are renowned for not using indicators which I feel also reflects most drivers on Legacy.

**Comment by iGreatWhite** [comment]
There is also another BMW that I haven’t seen for a while in rotation. The m4 is there too.

**Comment by ainstaylor** [comment]
I haven't seen the M4 being driven around. To be honest though, I don't see the i8 often either.
