### ISSUE TITLE
In game MDT

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/legacy-assets-issue-tracker#373]
**Name:** Brundoggy
Who is suggesting this? Please include discord name.

**Summary:** In game MDT
Write a short summary of what your suggestion is about.

**Link:** 
https://www.fivem-store.com/product/nopixel-mdt/
If there are any links to what you're suggesting, please add them here.

**Reason:** 
I believe this would enhance in game RP and would allow us to not have to deal with outside game assets and would allow us to keep more stuff in game rather than relying on discord
Why would your suggestion be a good addition to Legacy?
I feel it would be a huge upgrade for PD and would also allow us to track things much easier rather than using a google doc to track everything

**Comment by FossiiLs** [comment]
+1 This would be a great item in the city. and its very cheap. Do it Ben.

**Comment by ultrahacx** [comment]
1- Wrong issue tracker. It should go [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
2- It is made for ESX framework and we use a custom framework which whill require a lot of changes. Also if Ben wants to add it, there are open source, better and free MDT's available but it again comes down to the intergration with our framework which might take a chunk of time.

I would recommend you to close this issue and open up the issue in the correct issue tracker if you wish to and if there isn't an already existing MDT issue tracker.
