### ISSUE TITLE
[peds/*] Add new textures for SKB vest

### ISSUE THREAD

**Issue by kloocek** [InZidiuZ/legacy-assets-issue-tracker#374]
**Name:**
klocek#7082

**Summary:**
Add more textures

**Link:**
///

**Reason:**
SKB vest is the best model of all vests, I think that the model asset team can add texture for police, sheriff, and other units.

**Comment by DaxterPancake** [comment]
This has been done.

Cheers!
Daxter.
Project Manager and Clothing Extraordinaire.
