### ISSUE TITLE
New Night Club

### ISSUE THREAD

**Issue by AldoLEGACY** [InZidiuZ/legacy-assets-issue-tracker#375]
I would like to present as a proposal to add a new nightclub to Los Santos. There is no other club like Vanilla Unicorn in the city, there is Bahamas Mamas of course, but the interior does not live up to its potential. In the link below I put pictures and a video that shows what the club looks like and where it would be located

https://pl.gta5-mods.com/maps/nightclub-ymap-projectprisma-de

**Comment by DaxterPancake** [comment]
Please follow the template found [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose). 

Please remake following the correct format.

Thanks,
Daxter.
**Project Manager.**
