### ISSUE TITLE
Lockers at Garbage HQ

### ISSUE THREAD

**Issue by XMDSpectre** [InZidiuZ/legacy-assets-issue-tracker#377]
**Name:**
Who is suggesting this? Spectre#1694

**Summary:**
Having Lockers at the Garbage HQ for people to change their clothes when going to work. Some people don't want to work in their everyday clothes and having the vest on the entire time. Having a locker system where they can put on "work clothes" would be amazing.

**Link:**
N/A

**Reason:**
People can have their usual clothing that they wear in the city and then they can have dedicated work clothes they can change into at HQ rather than having to drive all the way near MRPD to change their clothing.

**Comment by InZidiuZ** [comment]
This issue tracker is for assets only. Use the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for requests like this.
