### ISSUE TITLE
Add ped

### ISSUE THREAD

**Issue by Filippek2115** [InZidiuZ/legacy-assets-issue-tracker#378]
Name:
Filippek#6981/ 416967686787170314

Summary:
Regarding the addition of an alternately created child's pedigree, together with mother and father, IC, we will play a fictional role play that we have developed towards character traits that is very important for us to develop them gradually.

Link:
https://megawrzuta.pl/download/fe8199ce99cbdb1829ffcb38ab7be6b3.html

Reason:
Together with the people who play my parents, we develop our roleplay in the smallest aspects of character, the story we follow and the gradual maturation of the child based on real life experiences are important to us.

**Comment by DaxterPancake** [comment]
Child peds have been shut down two times now.
Child peds have no place on this server.

If this is not what you were talking about, please remake.

Cheers,
Daxter.
**Project Manager.**
