### ISSUE TITLE
 appeal - Daxter

### ISSUE THREAD

**Issue by Gventeryd** [InZidiuZ/legacy-assets-issue-tracker#379]
Hello Daxter, I would like to refer to your rejection of the request to add a child pedal for the user with the nickname Flippek, Maybe my name is Hubert and I come from Poland for a long time with two friends looking for a server on which the bar is located, if by the level, we wanted very much so that we can play a RolePlay which will have an extensive system through the emotions and interests of each of our characters. Legacy RolePlay is one of the few servers that has such a display on how there is one leader project. Returning to the vote on the application, we want us to play in this atmosphere, but we are blocked by the fact that our friend cannot play the role of a child or a story in an exemplary manner. I have never seen through doing things that protrude through the laws of realism, which he also showed during his whitelist verification on the user "WIEWIÓRA # 0998". Unfortunately, it is to some extent limiting the role of Play in relation to players. There are players in Poland who, playing the peda, add climate and something to the game. I know that maybe in the place where Legacy was created, the custom gameplay system is not well received by people, but with us it is not a delayed thing. When it comes to cloud server optimization, I know that shoots do not limit the flow to website optimization, in Poland servers with shoots do not lose anything in quality, so I would ask you to consider my account, thank you in advance Gventeryd

**Comment by DaxterPancake** [comment]
Im really sorry, but I am finding it hard to understand what you're trying to say to me.

At this time child peds will not be added.

I understand that your friends would like a server in which they can have a child and roleplay having one, but a roleplay server with sex, murder, drugs, etc.. Is not the place.

Thanks,
Daxter.
**Project Manager.**
