### ISSUE TITLE
[maps/mirror_park_tavern] Issues with interior

### ISSUE THREAD

**Issue by MalcolmFrosty** [InZidiuZ/legacy-assets-issue-tracker#380]
**  Malcolm.Frosty   .Frosty.#1776   :**

**Summary:**
The Mirror Park Tavern interior looks like it has been vandalized, it was working perfect prior to the tuesday tsunami. I was doing interviews there to try and get it up and running since I'm the new manager. Please help.

## Additional Information

**Screenshots:**
I dont have any screen shots, but every one can see how messed up it is.

**Notes:**
For anything else noteworthy.

**Comment by KrigTroff** [comment]
Same thing goes for yellow jack. Everything inside is missing. People just standing in the new wide open spaces. Seems like everything has vanished.

**Comment by Nuziatella** [comment]
See #361
