### ISSUE TITLE
[maps/*] Interior for hospitals across from city hall and by morgue

### ISSUE THREAD

**Issue by bossace** [InZidiuZ/legacy-assets-issue-tracker#381]
**Name:**
Marty Sanders, Bossace #7764

**Summary:**
Adding interiors and making fully functional hospitals out of the two larger hospitals in the city. The one across the street from city hall and the one next door to the coroner's building.

**Link:**
N/A

**Reason:**
With our population as a city growing to new caps every so often so are the calls to EMS. Locations like pillbox become chaotic hotspots due to the mass amounts of people who congregate. At times we can have 10 ems on duty in that one building due to needing to be in the city the most as most calls come from there. Like most cities there are multiple hospitals so opening two more in the city that are spread out making an ease of access for people who just have simple injuries as well as allow us as ems to spread out and create more environments to help people.

**Comment by z-Lunar** [comment]
> **Name:**
> Marty Sanders, Bossace #7764
> 
> **Summary:**
> Adding interiors and making fully functional hospitals out of the two larger hospitals in the city. The one across the street from city hall and the one next door to the coroner's building.
> 
> **Link:**
> N/A
> 
> **Reason:**
> With our population as a city growing to new caps every so often so are the calls to EMS. Locations like pillbox become chaotic hotspots due to the mass amounts of people who congregate. At times we can have 10 ems on duty in that one building due to needing to be in the city the most as most calls come from there. Like most cities there are multiple hospitals so opening two more in the city that are spread out making an ease of access for people who just have simple injuries as well as allow us as ems to spread out and create more environments to help people.

For the sake of the servers Performance and everyones Santity, no.
