### ISSUE TITLE
[maps/st_fiacre_hospital] Not an issue just an improvement on st fiacre hospital

### ISSUE THREAD

**Issue by PsychoGrandpa** [InZidiuZ/legacy-assets-issue-tracker#383]
**Name:**
Who is suggesting this? Please include discord name.
ChiknLegPiss#8936

**Summary:**
Write a short summary of what your suggestion is about.
I play as an EMS on Subdivision- Bangladesh. The issue I face is that whenever I drive an F-450, the roof of the ambu. gets scratched whenever I try to enter the parking lot. The issue is clearly explained in a video link below.

**Link:**
If there are any links to what you're suggesting, please add them here.
(This link shows the issue we are facing)
[https://streamable.com/buff3w](url)

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be an improvement for the EMS also scratching an ambulance everytime we enter or exit is both disturbing for the patients and the EMS.

**Comment by XwezioGH** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/fSOThTnH/31-test)

**Comment by z-Lunar** [comment]
This has been taken into consideration and pushed in the most recent commit :).
