### ISSUE TITLE
[peds/?] Cat looking for claw or bite

### ISSUE THREAD

**Issue by XinarTheNeko** [InZidiuZ/legacy-assets-issue-tracker#384]
**Name:**
Neko Discord:  Neko (XinarTheNeko)#1904   (Visable discord name Neko Aka Ghost Demon | Max Salem)

**Summary:**
I am playing a little cat model on the server, not a murder cat xD And I been in many instances already that people do not respect /me messages of Bit or Claw or similar in situations when its natural for a cat to get agressive, our go full on fight with me while I have no way of fighting back. The small cat model do not have a attack / dmg muscle ingame and I wonderd if there is was ways to add that to the game for pure rp purpuses and kinda remind the other rp'r present that if a cat gets angry it actualy warents a reaction. Some people seam to think they can do what they want to the pets.
Im aware the biger animals have ways of biting / clawing if agrivated. But I know the cat cant do this, and id assume other small animals too.
I mostly play a rly kind hearted cat and its not much needed, but randoms have killed me whitout reason cuz I cant fight back. And fellow biger animals (like dogs) some times dont like cats naturly and hurt me while I have had no reason to show any fistiness, and just been forced to run from every situation for the sake of survival despite it dont fit the situation I am in rp wise.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Widens the small pets rp pool in a situation when agrivated / treatend, and reminds fellow rp'rs that small animals cant be done what they whant with. ANd its generaly natural a cat (other small animal) would retailate at times.

**Comment by Nuziatella** [comment]
This is RAGE issue and can't be fixed via assets.
