### ISSUE TITLE
[peds/*] Wrong mask model

### ISSUE THREAD

**Issue by Decyphers** [InZidiuZ/legacy-assets-issue-tracker#385]
**Reporter:**
Decypher#5668

**Summary:**
One of the masks for male models has the wrong model for the texture. ex/ The correct texture is spread over a hyena mask

## Additional Information
The mask works correctly for the female model, bug only seems to effect male model
Feel free to reach out if anything extra is needed

**Screenshots:**
https://imgur.com/a/1a6zjQN

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Closing due to this not being a thing anymore? If it is, please re-make?
