### ISSUE TITLE
[maps/?] Garage at PD for state impounds

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/legacy-assets-issue-tracker#386]
**Name:**
Who is suggesting this? Please include discord name.
Brundoggy#8692

**Summary:**
Write a short summary of what your suggestion is about.
Make a garage at PD specifically for state impounding vehicles. As they are used in crimes and the PD requests for a vehicle forfeiture for vehicvles used in crimes, the PD obtain in through IC means, obtain ownership of it and place it in then PD garage where the original owner has to go through court procedings/DOJ in order to get it back. 

**Link:**
N/A

**Reason:**
I feel like this would be a huge addition as it would allow the PD and DOJ to clean up alot of these vehicles used in crimes time and time again and would introduce a new risk factor for criminals as they could potentially lose their car (If PD does the paperwork correctly of course)

**Comment by Nuziatella** [comment]
So this is looking for a marker and script modification to the impound system. Please make your suggestion over at [this github.](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
