### ISSUE TITLE
[maps/bahama_mamas] Bahama Mama's Interior Revamp

### ISSUE THREAD

**Issue by stardome101** [InZidiuZ/legacy-assets-issue-tracker#387]
**Name:**
Who is suggesting this? Please include discord name.
Melody Balooga | Erin | Erin#8942
**Summary:**
Write a short summary of what your suggestion is about.
This Bahama Mama's interior is basically a revamp of the current one. We feel as if this could be a good move to go more towards a nightclub and bring more life to the business itself. The current one does not have much room in it and very little to offer. The extension itself would provide more working room for our guests to meet new people and for our workers to ensure the full potential of enjoyment. 
**Link:**
If there are any links to what you're suggesting, please add them here.
Link to MLO: https://www.youtube.com/watch?v=UH_jjhcIqxw
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be a good addition as it fits more of the nightclub feel overall to appease more of the crowd. Our goal is to improve the nightlife scene and bring back the joy in events at our location.

**Comment by Djmeowzle** [comment]
+1 The current bar there is very lacking, a new and improved one would provide more to do there.

**Comment by Imaghost1337** [comment]
+1 on this one. Compiling all Legacy interiors, Bahama Mamas lacks the most. Talking about a back entry, staff rooms, bathrooms and private places for people to talk

**Comment by nikkoendres** [comment]
+1

**Comment by antihero6713** [comment]
Work has started on this project

**Comment by antihero6713** [comment]
new interior has been added
