### ISSUE TITLE
[imports/service] Bean Machine car/livery 

### ISSUE THREAD

**Issue by Deggan8** [InZidiuZ/legacy-assets-issue-tracker#388]
**Name:**
Iain: Dreggan8#3619

**Summary:**
With the new additions to Cars being added for other businesses and the addition to the quick dial number for Bean Machine, I think a livery could be added in, in order to improve the RP for the deliveries for Bean Machine. 

**Link:**
https://www.gta5-mods.com/paintjobs/karin-dilettante-livery-bean-machine

**Reason:**
This would give any employee for the Bean Machine to advertise the company and Improve the RP with civilian RP. This would also fall in line with the new additions to commercial cars being added to the city for other delivery businesses.

**Comment by Brookiedoughh** [comment]
I believe this would be a great addition to the Bean Machine company, because it will provide a more professional look for the café.

**Comment by Nuziatella** [comment]
This has been added as well food delivery vehicles for all restaurants.
