### ISSUE TITLE
[imports/service] Weazel news van and helicopter suggestion

### ISSUE THREAD

**Issue by azpranto** [InZidiuZ/legacy-assets-issue-tracker#389]
**Name:**
This is AZ Pranto. My discord: Anon_Marcus#6997 

**Summary:**
Weazel news vehicles need to improve. We can't shoot any event, race or robbery scene. We need a news helicopter with a camera in game to improve news reporter rp. And news vans are not realistic. In real life, usually news vans have some antennas, wireless receivers etc. But in game we don't have any of these. It's a request. If we get those van and helicopter, it will be more exciting to do news reporter job.

**Link:**
Helicopter: https://www.gta5-mods.com/vehicles/buckingham-maverick-2nd-generation-add-on-liveries

Tv van: https://www.gta5-mods.com/paintjobs/mercedes-sprinter-low-roof-tv-van

**Reason:**
It will help both in news rp and other rp's. Unique then any other server out there and people will be more interested about news rp as they have a chance to ride a helicopter.

**Comment by Nuziatella** [comment]
These plus 2 additional vehicles have been added.
