### ISSUE TITLE
Suggestion Police Heli

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/legacy-assets-issue-tracker#39]
**Name:**
Who is suggesting this? Please include discord name.
Sercan#0001

**Summary:**
Write a short summary of what your suggestion is about.
Police helicopter while on the cam and locked on vehicles it shows you the speed in KM. I would like to suggest that to be converted to Miles, so its easier to forward the speed to the ground unit.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?

In my opinion it does not make sense that we have miles on the cars and km on the chopper.

**Comment by Karpenkooo** [comment]
This would be for @InZidiuZ . Although he's got a lot of stuff to do right now so you'll probably need to wait.
