### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by RoyalLuck** [InZidiuZ/legacy-assets-issue-tracker#391]
**Reporter:**
Who is reporting this? Please include discord name.
discord name :- RoYaL LuCk#0001

**Summary:**
Write a summary of what you're experiencing.
The oxy is marked as false in my server.cfg but is still not working 

**Screenshots:**
here is a short video showing it :- https://www.youtube.com/watch?v=6pp3KzUXZ-o

**Notes:**
For anything else noteworthy.
Server 13

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) instead.
