### ISSUE TITLE
[maps/soyler_textile] Convert building in to loft style spaces!!!

### ISSUE THREAD

**Issue by LeBewm** [InZidiuZ/legacy-assets-issue-tracker#392]
**Name:**
Who is suggesting this? Please include discord name.
LeBewm# 0507

**Summary:**
Could we please add the **Soyler Textile Building**  in La Mesa area as rentable Loft space please? _and me as the landlord of course ;)_.  I would love to be able to have something more industrial to rent over just a house. I'm pretty sure others would as well. 

_building:_
https://cdn.discordapp.com/attachments/706134120014676048/838955794396610640/unknown.png

_Location ( right across the street from the highway patrol building):_
https://cdn.discordapp.com/attachments/706134120014676048/838963522288877618/unknown.png

**Link:**
I don't have any links,  but I could see us using an instance of the pre-existing office from the warehouse space  we currently sell the materials at,  as the loft space. just clear out the existing furniture but keep the overhead pipes. load beams , gak etc.
https://cdn.discordapp.com/attachments/706134120014676048/838963174346588210/unknown.png
Instead of wood on that back wall maybe make it brick? and the floor just a grey concrete?
https://cdn.discordapp.com/attachments/706134120014676048/838963251903463464/unknown.png

There is even a place for parking ! :)
https://cdn.discordapp.com/attachments/706134120014676048/838970564423974962/parking.jpg

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would add more dynamic living spaces to the city. allowing for a different vibe to be created. also could allow the possibly to add a coffee shop or open the taco shop in the area.  The arcade is close and I feel this location would get more traffic with places like I am suggesting near by. Plus , its super cool to live in a loft over a house. ha! 

Thanks for reading and I hope we can make this dream happen ! !  !  ! ! ! 
#ProjectRebuildLaMesa #lofts #industrialspace

**Comment by DaxterPancake** [comment]
This has technically already been requested on the Framework Tracker.

The issue is [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/800).

The general idea is to add larger spaces to be able to be rented to allow buisnesses and criminal orginizations to have a place with more storage and hopefully in the future, become full blown stash places.

**Comment by LeBewm** [comment]
That's cool too! a little different then what I'm suggesting but still cool.  I'm guessing this means request denied? LOL

**Comment by DaxterPancake** [comment]
No, not at all!

 I believe this could be a really cool addition but I don't believe it would be benificial to the server to only add this one space when we could allow all warehoses/barns, etc to be rentable.

I will say though, this doesn't seem like an asset issue as you're not asking for an interior, you're asking for a rentable building.

**Comment by Nuziatella** [comment]
Script support would be required for this. Please move this suggestion to [here.](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)

A warehouse shell will be provided to support this feature if it is implemented.
