### ISSUE TITLE
[imports/police] Police Maverick (Heli needs Buff)  

### ISSUE THREAD

**Issue by Ashraf2112** [InZidiuZ/legacy-assets-issue-tracker#393]
Discord: Ashraf#9999

**Summary:**
As of now the current Police Heli seems to be very slow when it comes to movement & controlling. I feel like before there was a time where the Heli was pretty smooth and it was fun when it comes to flying with it. But now I can't say the same thing. The speed pickup has decreased and the movement has also went down. Making it hard in some situations & the maneuver is also pretty rough. 

**Link:**
https://www.youtube.com/watch?v=59fOVd9e_lQ&t=133s

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would make the Heli RP even better and it would create a bit more tension when it comes to chasing.

**Comment by Nuziatella** [comment]
Adjustments have been made
