### ISSUE TITLE
Garage not recognizing my own vehicles

### ISSUE THREAD

**Issue by WtfIsHappeninghelpppp** [InZidiuZ/legacy-assets-issue-tracker#395]
**Reporter:**
0u7law#5292

**Summary:**
I bought BMX bike from PDM i put it in my garage and brought it back out and was riding it around. I then put it back into my garage and tried to take it out, it spawned with a different color and when i tried to put it back in it said the vehicle didn't belong to me. The same thing happened with my Akuma when I got it from the impound. I brought it to the garage and stored it but when i brought it back out the color was changed and I couldn't store it back into the garage, it was telling me to hotwire it. I have a clip of what happened to the BMX bike and the Akuma. 

## Additional Information

https://medal.tv/clips/51651276/d1337aFGycKN

**Notes:**

**Comment by Nuziatella** [comment]
This isn't the correct GitHub for this. Please use: https://github.com/InZidiuZ/op-framework-issue-tracker/issues
