### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Supbro112** [InZidiuZ/legacy-assets-issue-tracker#396]
**Reporter:**
Who is reporting this? Please include the discord name.

Supbro112 (Steam)   |   ╲⎝⧹Sunny Bro⧸⎠╱#0379   |   Adam Pelozi

**Summary:**
I bound carry to a scroll-wheel up bind and when trying to delete the bind it still exists. I tried to hard nap as well and it also stays as a bind. I didn't realize that the binds would stick to the keys even after removing so now I am regretting it because anyone in my vicinity when I try to zoom in. I will say does it tells me I removed the bind "Bind 'carry' removed" or some message like that.

I tried to bind it to a new key, but it bound to both keys now (Right bracket and scroll wheel up)

**Screenshots:**
N/A

**Notes:**
I might try clearing the cache and see if that will do it, but not sure if I will.

**Comment by Nuziatella** [comment]
This isn't the correct GitHub for this. Please use: https://github.com/InZidiuZ/op-framework-issue-tracker/issues
