### ISSUE TITLE
[maps/pizza_restaurant] Restaurant Appearance/Features to Reflect Approved Business Plan

### ISSUE THREAD

**Issue by terpsaucin** [InZidiuZ/legacy-assets-issue-tracker#399]
**Name:**
Who is suggesting this? Please include discord name. DAMON#0001

**Summary:**
Write a short summary of what your suggestion is about.

- [x] ATM for customers and gamblers
- [x] Window Signage
- [x] Exterior Signage
- [x] Door lock for basement

Our primary focus with this location is to provide exciting and unique RP in the basement of the restaurant via underground gambling. We have created a system via current in-game commands and Excel spreadsheets to deliver a pretty solid gambling experience including blackjack for up to 4 people at the same time per table and roulette for how ever many people we can fit. We have been taking feedback from players on what they would like to see added and the majority of it has been adding an ATM so they don't have to leave the area to get more cash and a lock on the door to feel more secure while in the basement. 

I can provide server ready image assets for signage to the interior assets team as well. 

**Link:**
If there are any links to what you're suggesting, please add them here.

<a href="https://ibb.co/qJvGnVF"><img src="https://i.ibb.co/1zkVnjJ/windowsignage-1.jpg" alt="windowsignage-1" border="0"></a>

<a href="https://ibb.co/4Ph1XGy"><img src="https://i.ibb.co/kQNmwfn/signage-2.jpg" alt="signage-2" border="0" /></a>

<a href="https://ibb.co/8rfPRVk"><img src="https://i.ibb.co/5rSszVZ/signage-1.jpg" alt="signage-1" border="0"></a>

<a href="https://ibb.co/3ScDb6q"><img src="https://i.ibb.co/dkDdvCq/ATM.jpg" alt="ATM" border="0" /></a>

<a href="https://ibb.co/PYKmTJB"><img src="https://i.ibb.co/3s2rfVt/Untitled-1.jpg" alt="Untitled-1" border="0" /></a>

Here is a link to the function GitHub requests: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1808

**Reason:**
Why would your suggestion be a good addition to Legacy?

We've received a massive amount of feedback and praise for the efforts we've put in to bring a "mafia vibe" underground gambling ring to the city and the general consensus is that if we can get a door lock and an ATM, along with the food function requests that have been submitted in the other GitHub, that it will be just about as good as it can be without an actual gambling system integrated into the city.

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/123556462-6155b480-d759-11eb-9b5d-9927f3cd46ba.png)
![image](https://user-images.githubusercontent.com/25892037/123556473-703c6700-d759-11eb-9fc2-bb69f82ad170.png)
![image](https://user-images.githubusercontent.com/25892037/123556481-7fbbb000-d759-11eb-85cc-52d8e157c2f3.png)
![image](https://user-images.githubusercontent.com/25892037/123556523-aa0d6d80-d759-11eb-872b-808f1dbad8f3.png)

Added custom branding, added menus to tables, added ATM removed chairs from gambling area
