### ISSUE TITLE
CAR seat 

### ISSUE THREAD

**Issue by hcboss** [InZidiuZ/legacy-assets-issue-tracker#4]
M.Jay 
 
Adding a command to change seat we have a SHUFF command but it is only for 2 seats what if the car is 2 door and 4 seater can we add command like /seat (1,2,3,4) so its good to occupy car that are for 4 people with 2 doors.

**Comment by SteezyRen** [comment]
You’re not fitting a grown ass man in the back of some of these two doors.

**Comment by InZidiuZ** [comment]
Hey,

Closing as you posted this at the wrong GitHub page, this one is for assets and strictly that, not scripting-related server suggestions.

**InZidiuZ**
*OP-FW Developer*
