### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/legacy-assets-issue-tracker#40]
**Reporter:**
Who is reporting this? Please include discord name.
Andrew Smith - Zurxey#2607
**Summary:**
Write a summary of what you're experiencing.
After Tsunami I noticed that the Tow Truck has become definitely more powerful. Now, all I know is that the tow truck is now going from 0-60 almost instantly. I got it to top out at 167mph+ driving on the freeway, no hills at all. The brakes are also extremely messed up, almost non-existent. 
## Additional Information
I also noticed that after using a Basic Repair Kit, and then an Advanced repair kit to fix it as best as possible, it got even more insane. 
**Screenshots:**
If suitable, include some screenshots.
Video Evidence Below:
https://www.youtube.com/watch?v=sFgisJxlU9U&feature=youtu.be
**Notes:**
For anything else noteworthy.
I honestly find this quite funny, feels like a monster super truck.

**Comment by Karpenkooo** [comment]
Once again the handlings seem to be randomly changing. Trying to get to the bottom of it but the current reasoning for this bug is unknown.
