### ISSUE TITLE
[maps/mosleys] Modify locking / activation proximity of Mosely's Bay Doors

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#401]
Name:
Who is suggesting this? Please include discord name.
Riedling#8969

Summary:
Write a short summary of what your suggestion is about.
Change locking and activation proximities for Garage bay doors at Mosely's

Link:
If there are any links to what you're suggesting, please add them here.
N/A

Reason:
Why would your suggestion be a good addition to Legacy?
Currently, cars need to either be less than a foot away or actually bump the 2 large glass bay doors in the main building to activate.  Would like to ask that the locking proximity be set to 12 feet away, and the activation proximity set to 6 feet.  This will make it much easier for customers to get in and out of the building, while allowing the owners the safe ability to lock the doors without them opening.

**Comment by Nuziatella** [comment]
This is script related. Please post your request [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
