### ISSUE TITLE
Suggestion - Second Parts Computer at Moseley's

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#403]
Name:
Who is suggesting this? Please include discord name.
Riedling#8969

Summary:
Write a short summary of what your suggestion is about.
Place a Parts Computer in the main building / area for use

Link:
If there are any links to what you're suggesting, please add them here.
N/A

Reason:
Why would your suggestion be a good addition to Legacy?
Currently, the only Parts Computer is located in the office above the large truck bay in the back of the building, 4 doors and quite a distance away from the main repair areas. Would like to ask that one be placed inside the office in the corner of the main bay area. Currently, there is a desk with screens, and a file cabinet. The desk would be the perfect place, and easily accessible from the main area. image attached.

![moseleys-parts-pc](https://user-images.githubusercontent.com/26015469/118011287-785d5600-b315-11eb-9f15-8ca6817b7077.png)

**Comment by DaxterPancake** [comment]
At this time, you will not be given a second computer.

Cheers,
Daxter.
**Project Manager.**

**Comment by riedling11** [comment]
Can I inquire as to why?  I know other shops with large buildings / multiple bays have 2 lockers one near each service bay?

**Comment by DaxterPancake** [comment]
If you would like to request for your Parts Computer to me moved, create another ticket.

You will not be recieving a second Parts Computer.

Thanks,
Daxter.
**Project Manager.**
