### ISSUE TITLE
[maps/mosleys] Add Car Washes to Moseley's

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#404]
Name:
Who is suggesting this? Please include discord name.
Riedling#8969

Summary:
Write a short summary of what your suggestion is about.
Place 2 outdoor car wash / air pumps for customer use

Link:
If there are any links to what you're suggesting, please add them here.
N/A

Reason:
Why would your suggestion be a good addition to Legacy?
Currently, there isnt any ability to wash cars at Mosley's.  Would like to ask that 2 of the small external ones that look like small air pumps (seen at Flywheels for an example) be placed outside the main bay doors for customer use.  Image attached.

**Comment by riedling11** [comment]
![moseleys-washes](https://user-images.githubusercontent.com/26015469/118012211-6d56f580-b316-11eb-968d-5ea75ece1a4b.png)

**Comment by xarxesthegreat** [comment]
adding this would also be a good way to get rid of the fire hydrant out front that blows up randomly

**Comment by MoolanRooge** [comment]
This would be fantastic, for Eva has been spending thousands on cleaning kits to give hand washing to big tippers, when $10-15 is better than spending $50.

**Comment by antihero6713** [comment]
Added requested car washes and deleted the fire hydrant.
![image](https://user-images.githubusercontent.com/25892037/123504057-facf7a00-d624-11eb-8bc6-b7924f69f767.png)
![image](https://user-images.githubusercontent.com/25892037/123504088-2ce0dc00-d625-11eb-90d7-77d055180389.png)

**Comment by xarxesthegreat** [comment]
somehow with the last big update on tuesday the hydrant came back and the car washes are no longer there. can we please get these added again?

**Comment by antihero6713** [comment]
fixed it again

**Comment by xarxesthegreat** [comment]
Thank you so much!

**Comment by xarxesthegreat** [comment]
they were removed again with todays tsunami and a large amount of trash and dumpsters were placed around the exterior of the shop

**Comment by antihero6713** [comment]
yeah when the other guy added the trees it took them out. I will put them in their own ymap so it wont happen again. sorry
