### ISSUE TITLE
Suggestion- New Vest

### ISSUE THREAD

**Issue by Fenix03** [InZidiuZ/legacy-assets-issue-tracker#405]
**Name:**
(Flexin)#5698

**Summary:**
This is a vest for a gang and it will look great for that gang, it will match the gang name and the RP.

**Link:**
https://www.gta5-mods.com/player/gang-kevlar-vests-mp-fivem

**Reason:**
The vest is not in the game, it would be great to have that vest for that gang, The gang needs to have a custom vest because they don't have a custom one. The vest that they want is the white one called "Cartel"

**Comment by DaxterPancake** [comment]
Thank you for the suggestion.

It has been looked at and may be added in the future.

Cheers,
Daxter.
**Project Manager.**
