### ISSUE TITLE
Garage at Garbage HQ

### ISSUE THREAD

**Issue by XMDSpectre** [InZidiuZ/legacy-assets-issue-tracker#406]
**Name:**
Who is suggesting this? Please include discord name.
Scott Shephard/ Spectre#1694
**Summary:**
Write a short summary of what your suggestion is about.
Garbage HQ has become a complete nightmare with how many people work there. The parking lot is not big enough to be able to hold all of the cars that come into work.
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
If we turned one of the factory buildings into a garage that is already in the parking lot of Garbage HQ, people could store their cars and not have to worry about being robbed or their cars exploding from people driving crazy in the parking lot. There have been many times where someone's car blows up in the parking lot and the entire lot goes, causing everyone who parked there to be stranded and have to pay to get their cars back for something they did not have control over. This would help keep the parking lots clear and allow more people to work and not worry about losing everything in their vehicles.

**Comment by riedling11** [comment]
This is a great idea!

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for this.
