### ISSUE TITLE
[peds/*] New Tactical Bike Uniform

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/legacy-assets-issue-tracker#407]
**Name:**
Who is suggesting this? Please include discord name.
superiorchicken#2703

**Summary:**
Write a short summary of what your suggestion is about.
We are currently starting to get the Tactical Emergency Casualty Care division up and running and there is no "Body Armor" labeled for EMS for active shooter situations. It also includes a bike uniform for the BMW 1200RT that we currently have assigned to the unit.

**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/player/ems-uniform-eup-l-u-epu-s-r

**Reason:**
Why would your suggestion be a good addition to Legacy?
I believe this would be a good addition to Legacy to help RP the Tactical side of EMS where they go into the "warm zone" of active shooter incidents and the "EMS" vest will help us stand out against the PD that are on scene as well.

**Comment by MetaHatter** [comment]
Closing this in lieu of newer ticket #524
