### ISSUE TITLE
[imports/civilian_*] Increasing trunk space of youga classic 4x4 custom

### ISSUE THREAD

**Issue by Bucmirshek** [InZidiuZ/legacy-assets-issue-tracker#408]
**Name:**
Deva Zajic Bucmirshek #5155

**Summary:**
I wanted to suggest to increses the trunk space of the youga custom 4x4 from edm, i think it would be fair to increse it cuz it is a van and it should hold more then a car

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
It is a van and it should hold more then a car

**Comment by riedling11** [comment]
100% agree.  has less than the normal Youga, and costs double.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for this.
