### ISSUE TITLE
[peds/*] Outfit suggestions more street gang items

### ISSUE THREAD

**Issue by Darskus** [InZidiuZ/legacy-assets-issue-tracker#409]
**Name:**
Darskus#1334

**Summary:**
Some extra gang related items loose bandana over head, hat with bandana, wrist bandana, neck bandana, reverse Tupac look and the Tupac look i could not find the two top male options in female as well but if its possible to add female versions that would be hype too.

**Link:**
https://www.gta5-mods.com/player/loose-head-bandana-mp
https://www.gta5-mods.com/player/bandana-hat-mp-male
https://www.gta5-mods.com/player/bandana-pack-mp-male-mp-female
https://www.gta5-mods.com/player/bandana-for-protrikk-sagged-jeans-mp-sp-male

**Reason:**
there is a lot of gangs and they are missing the gang vibes in my opinion and i think these styles will add value to the gangs in the city. Make the ones that want to be street gangs actually look like street gangs if they want.

**Comment by Griknasty** [comment]
These look great, I hope these get implemented!

**Comment by ChiggityChavis** [comment]
I would like to say these are some great options for gangs. Currently the styles are fairly limited and would be nice to see additional ways to express the gang gang life style!

**Comment by seekertransformer** [comment]
Love these and that they are unisex and got many options, would be amazing. yes pleaaaase!

**Comment by Kamobentz** [comment]
This would really help distinct the gang members looks and give them more options to show their colors. Great Idea!

**Comment by Darskus** [comment]
you bet im already wearing that neck tie banny <3

**Comment by Darskus** [comment]
https://www.gta5-mods.com/player/bandana-for-protrikk-sagged-jeans-mp-sp-male
this might be late but this is actually so nice
