### ISSUE TITLE
Car Suggestion

### ISSUE THREAD

**Issue by MarioGigante** [InZidiuZ/legacy-assets-issue-tracker#41]
**Name:**
Who is suggesting this? Please include discord name.
TA-731 J. Andrade/Mario Gigante#0874
**Summary:**
Write a short summary of what your suggestion is about.

I would like to talk about my Mitsubishi Evo X, the thing i wanna talk the most its gonna be the handling on it, It bounces everywhere, Turns are trash at the moment.. For me the top speed on it its kinda urrhmmm because i wasted 25k tuning it and kinda sucks anyway because when it wasn't tuned and upgraded it was doing 165/170 now its doing 180 full upgraded ! The Sound of the engine isn't the right for that type of car ( opinion ) and it brakes so easy, and im not being cocky by sayin that i mean that car brakes like a flower .. and i already tried to upgrade the armor on it but it doesn't do nothing. Same with my Custom Comet, the engine is on the back and if i brake and if even isn't with the back it brakes anyway the same way !

**Reason:**
Why would your suggestion be a good addition to Legacy?
I would like to think everybody who owns that car would like to get your car fixed !

**Comment by MarioGigante** [comment]
@Karpenkooo I'm not sure if i was suppost to "@" you but 🏎

**Comment by Karpenkooo** [comment]
yeah there seems to be some sort of issue with handlings randomly changing. Not sure what's causing it but we're trying to get to the bottom of it.
