### ISSUE TITLE
Bug Report : Apartment Complex L on Forum Drive

### ISSUE THREAD

**Issue by RedShirtBandit** [InZidiuZ/legacy-assets-issue-tracker#410]
Name : RedShirtBandit#1679

Summary : This report is about Complex L on 12 Forum Drive owned by King Estates. The garage at this complex is bugged out. When pulling out a vehicle it has a chance to scuff out and it will be default and say that you do not own it. I've heard complaints from other residents in the complex having the same issue and it causes a HUGE inconvenience to everyone living there.

NOTES : Unfortunately I have not been able to recreate this issue again but I have gotten reports from 2 other residents with the same issue... If i can recreate this on video I will post it as a comment below. 

Thank you

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for this.
