### ISSUE TITLE
Spawn location for weazel news 

### ISSUE THREAD

**Issue by azpranto** [InZidiuZ/legacy-assets-issue-tracker#411]
**Name:**
Who is suggesting this? Please include discord name.
Anon_Marcus#6997

**Summary:**
Write a short summary of what your suggestion is about.
Recently, i asked for some new weazel news vehicles. Thank you so much that you did what i requested. But they need a spawn location now. Please do that asap. 

**Link:**
If there are any links to what you're suggesting, please add them here.
It doesn't need any link.

**Reason:**
Why would your suggestion be a good addition to Legacy?
New recruits are awaiting for it. And we will get more new recuits after that.

**Comment by WeazelMicky** [comment]
I know some updates like this don't normally get published. How can we get a heads up when the spawn point is added?

**Comment by DaxterPancake** [comment]
If it gets done you will see it in the changelogs that are posted with each update.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for this.
