### ISSUE TITLE
[maps/?] Paleto Bay Overhaul

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#412]
**Name:**
AdeptCL#0402 

**Summary:**
Overhaul of the environment and textures of Paleto Bay.

**Link:**
https://www.gta5-mods.com/maps/paleto-bay-overhaul

**Reason:**
Just an environment and/or texture change of buildings around Paleto Bay, would give it a refreshed feeling. This is something the "Sons of Legacy Motorcycle Club" have been aiming to do across all subdivisions; bring life to Paleto Bay.
   This overhaul includes building retextures of buildings which have textured as "shut down/closed". As Paleto Bay has grown with new interiors and buildings, it seems only matching to have some of the buildings that are also present in Paleto Bay to "grow" too.
   Finally, I'm not sure if it's included in the overhaul pack. But, it would be also be interesting if more foilage (trees, bushes, etc) were added throughout Paleto Bay. This including Paleto Boulevard, Great Ocean Highway, Duluoz Avenue, and it's remaining surrounding areas.

**Comment by Knoxmortis** [comment]
Along these lines, any chance of getting a real convenience store up north like where we can get phones, and food, maybe even tools?

**Comment by antihero6713** [comment]
closed for now. Will look into this later
