### ISSUE TITLE
[maps/gta] Moving Water and vending machines at Garbage HQ

### ISSUE THREAD

**Issue by XMDSpectre** [InZidiuZ/legacy-assets-issue-tracker#413]
**Name:**
Who is suggesting this? Scott Shephard Spectre#1694

**Summary:**
We have a water cooler and snack machine at Garbage HQ, but they are right next to the truck spawn. Having them moved would make it to where they don't accidentally get used together. Also, the water cooler does not replenish your thirst.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Moving the snack machine and water cooler would stop people from accidentally spawning a truck while getting a snack.

![20210526115234_1](https://user-images.githubusercontent.com/81781833/119692789-b2e8e780-be19-11eb-8188-8cb1a49bee19.jpg)

**Comment by riedling11** [comment]
100% needed.  water isnt working and the vending machine "E" is too close to the "E" for spawning a truck.

**Comment by antihero6713** [comment]
Issue has been fixed
![image](https://user-images.githubusercontent.com/25892037/122710724-de030300-d22e-11eb-9bc4-88f08e6c4991.png)
