### ISSUE TITLE
Suggestion - idea for a cook profession 

### ISSUE THREAD

**Issue by vlaskgar** [InZidiuZ/legacy-assets-issue-tracker#414]
**Name:**
Vlaskgar, discord: vlaskgar#0957

**Summary:**
Adding a cook profession that crafts food items from ingredients 

**Link:**
[LegacyRP cook role.pdf](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/6556154/LegacyRP.cook.role.pdf)

**Reason:**
This new profession will make existing jobs more relevant and immersive as well as adding more jobs and player interactions

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use the [framework issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for this.
