### ISSUE TITLE
Windows and doors in jail dosen't have colision

### ISSUE THREAD

**Issue by Saszkaxd** [InZidiuZ/legacy-assets-issue-tracker#415]
**Reporter:**
Who is reporting this? Please include discord name.
Saszka#1942
**Summary:**
Write a summary of what you're experiencing.
Windows and doors in jail dosen't have colision

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://youtu.be/6nolZCY9aaU

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Closing in favour of #398 

Thank you for your report,
Daxter.
Project Manager.
