### ISSUE TITLE
[imports/civilian_*] Jeep TrackHawk

### ISSUE THREAD

**Issue by kallen45901** [InZidiuZ/legacy-assets-issue-tracker#417]
Jack Daniels Jr/ icemanillest#7885

I think the Jeep TrackHawk is a dope 4door SUV something different i think

https://www.gta5-mods.com/vehicles/2018-jeep-grand-cherokee-trackhawk-series-iv-add-on

I feel like it would be a cool 4door muscle/ family SUV and good for any terrian

**Comment by joevapes3** [comment]
This exact vehicle already exists in import pack 2, but just hasn't made it into the rotation for the Exclusive Dealership in a while. Be patient and it will find it's way back in soon I imagine.
