### ISSUE TITLE
Neon underglow does not save on vehicles

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/legacy-assets-issue-tracker#419]
**Reporter:**
Who is reporting this? Please include discord name.
IC: Richard Robin
OOC: Hell of the Devil#0666

**Summary:**
Write a summary of what you're experiencing.
If you visit any Vehicle Modification Shops (Midnight autos, los santos customs) and apply neon, it will only show until you put the vehicle in the garage or until tsunami. It appears that no matter the neon configuration, it still does not save.

I have tried this on many different vehicles including personal and local vehicles and nothing seems to allow neon to be saved!

**Comment by iGreatWhite** [comment]
This has already been reported on the other tracker. Will not be fixed until the garage system is redone per the comment by InZidiuz on the post.

This is also the wrong tracker: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

Post: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1791

**Comment by hell-of-the-devil** [comment]
InZidiuz just told me it was never reported, weird... 
![image_2021-05-31_214028](https://user-images.githubusercontent.com/4959366/120240578-d3b99e80-c258-11eb-8059-806428cf8918.png)

**Comment by Nuziatella** [comment]
> This has already been reported on the other tracker. Will not be fixed until the garage system is redone per the comment by InZidiuz on the post.
> 
> This is also the wrong tracker: https://github.com/InZidiuZ/op-framework-issue-tracker/issues
> 
> Post: [InZidiuZ/op-framework-issue-tracker#1791](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1791)
