### ISSUE TITLE
Tuner Chip

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/legacy-assets-issue-tracker#42]
Who is suggesting this? Please include discord name.

Dean Hunt or TwoplePop#7989

Write a short summary of what your suggestion is about.

I am feeling that the tuner chip is not as powerful as its rarity is. I feel like something that rare or expensive should be somewhat good. I have tried over 30 combinations on my fully upgraded elegy retro and i'm not feeling a difference at all.

Why would your suggestion be a good addition to Legacy?

I think that my suggestion will be good to everyone that owns a tuner chip. It will increase its use and it will allow it to actually do something.

**Comment by MarioGigante** [comment]
agreed
