### ISSUE TITLE
TrashHQ Water Fountain and Vending Machine

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/legacy-assets-issue-tracker#420]
**Reporter:**
Who is reporting this? Please include discord name.
IC: Richard Robin
OOC: Hell of the Devil#0666

**Summary:**
Write a summary of what you're experiencing.

The Water Fountain
    The water fountain that was recently added to TrashHQ is rather buggy, if used as intended, it does not quench a players thirst. 
    however, if you have someone block the front of the water fountain and you get a drink from any other angle than directly 
    infront, it will work correctly!

The Vending Machine
    The Vending Machine is too close to both the water fountain and the stairs to the garbage truck marker. sometimes people 
    pull trucks out when they're just trying to get something from the vending machine, or they try get a drink and buy food 
    instead.

## Additional Information
It was suggested that the vending machine and water fountain should be moved onto the TrashHQ loading dock in order to better accommodate the issues listed above.

**Screenshots:**
Clips are provided below!
https://www.youtube.com/watch?v=4QjV0AKdHYM
https://www.youtube.com/watch?v=8bxRW18VOoU

**Notes:**
For anything else noteworthy.
The TrashHQ community really want a break room for things like a changing room, water fountain/vending machine and a couple other things. maybe this could be a resolution to all the issues aside from parking at TrashHQ, which could be resolved by providing a garage space in one of the spare buildings!

I hope that this all helps

**Comment by Nuziatella** [comment]
Closing in favor of #413
