### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Astoric** [InZidiuZ/legacy-assets-issue-tracker#421]
**Name:**
Dec#0717

**Summary:**
Increase the off duty paychecks of EMS & PD

**Link:**
N/A

**Reason:**
I'd just like to preface the suggestion by saying that I absolutely agree that EMS and PD should be getting paid more on duty than off duty. I was incredibly happy to see that the paychecks were being slightly decreased in a previous commit, and was excited to see what kind of new activity it would bring to both jobs. However, as it stands, 10% of pay off duty is realitically just not enough. I love PD RP, as I'm sure everyone else that does it does, however, I also enjoy the RP that I get off duty at the same time. I don't want to spend my entire time on duty just to afford to pay for my house. I want to suggest an increase to the previously mentioned -10 of the on duty pay, maybe even -20 or -30.

**Comment by Nuziatella** [comment]
This isn't the github you are looking for.
Please visit [this github.](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
