### ISSUE TITLE
Easier /furniture 's manage object 

### ISSUE THREAD

**Issue by rajbastakoti** [InZidiuZ/legacy-assets-issue-tracker#423]
**Name:**
hi this is me Grishma , RajGrishma#9781

**Summary:**
This is in regards to Real Estate  ( making interiors ) ,  I really like how the furniture menu is but the actual problem / improvement i am suggesting is an easier or a more convenient way of searching right furniture to be modified . 
in process of making interiors There are a lot of people who want to remove their furniture or think of making some changes in the arangement of things inside a house .
 problem is even to search a correct item in house full of furniture , it might take a few tries , having 100+ furniture is already hard , usually its between 200-400 items , so like we need to keep on clicking mouse on the **next** or **previous** buttons alot , 
having said that sometimes we need to look for multiple furniture(s) that are to be modified/moved 

if possible change it from clicking to  something else so its more faster  or something like that , that would make the moving  furniture more easier .

**Link:**
If there are any links to what you're suggesting, please add them here.
a photo of what i am talking about 
https://gyazo.com/9b34704fe797a621a18c1125c690785d

**Reason:**
Why would your suggestion be a good addition to Legacy?
to edit or even to make it upto a furniture just to edit is so hard can we make it a convenient way of editing the interior 
so that its easier for everyone to decorate their houses .

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this. Use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) instead.
