### ISSUE TITLE
Bug report - convenience store safe bug

### ISSUE THREAD

**Issue by Darskus** [InZidiuZ/legacy-assets-issue-tracker#424]
**Reporter:**
Darskus#1334

**Summary:**
So I've noticed a strange pattern with grocery stores/convenience stores where every once in awhile you wont get a audible queue when you get to the number. out of 3 so far only 1 did not scuff which is some pretty rough odds.

## Additional Information

**Screenshots:**
i might be able to get you some video clips of this happening on multiple occasions

**Notes:**
what I think is happening but not confirmed is lets say for ex I'm spinning to the right and hit 35 and get the lock then the next number is 40 for ex. but I have to spin left because i just went right now that this number is passed 0 it no longer triggers a audible queue. I have tried to correct the issue by even spinning the dial back the opposite way an equal amount of times and then trying again. I've also tried just spinning and spinning where me and my buddy both have gotten upwards of 4 rotations and still no audible queue

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this. Use [this issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for issues relating to scripts.
