### ISSUE TITLE
[imports/?] Hellian seems broken

### ISSUE THREAD

**Issue by Knoxmortis** [InZidiuZ/legacy-assets-issue-tracker#425]
So default Hellian maxes out at 100mph, after putting like 12k in it; Turbo, Race transmission, and EMS 5. Basically everything but the breaks, still only goes 100mph. 110mph downhill with a back wind. Other trucks like sand king and ford police truck, still go MUCH faster. 

This seems broken to me, I think it should at least go up to default (as of 2 days ago 157) speed with full upgrades. Otherwise what's the point of spending all that money? It's also disturbing that this is a car you HAVE to have a paid ticket to even get access to. Can't even sell it... Please review. <3

**Comment by joevapes3** [comment]
While all speeds of vehicles have been changed in the last few days, the latest vanilla casino cars update included the default GTA handling for that vehicle and was conflicting with the streaming file causing it to have the wrong handling. It has now been corrected and and as soon as the next update is pushed will be corrected.
