### ISSUE TITLE
Burger Shot Delivery BUG

### ISSUE THREAD

**Issue by GramGram420** [InZidiuZ/legacy-assets-issue-tracker#426]
**Reporter:**
Who is reporting this? Please include discord name.
Gram Gram GramGram#3253
**Summary:**
Write a summary of what you're experiencing.
when i pickup a delivery from burger shot, no delivery is ever started.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Nuziatella** [comment]
Wrong github. Please report in: [Framework Github](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
