### ISSUE TITLE
[peds/?] Mask Suggestion

### ISSUE THREAD

**Issue by Knoxmortis** [InZidiuZ/legacy-assets-issue-tracker#427]
**Name:**
Knoxmortis#2163

**Summary:**
I need a blackout mask that fits my stupid cheeks and covers my hair.

**Link:**
https://img.gta5-mods.com/q95/images/mask-pack-for-mp-freemode/045e21-20201222193758_1.png
it's part of this mod https://www.gta5-mods.com/player/mask-pack-for-mp-freemode 

**Reason:**
There's a limited number of masks that take away HAIR and cover my somewhat bulky face, and I feel like this isn't just a ME issue. The mask I linked above would be Perfect for me esp if they added a matt black version, hex code #171717. I wouldn't complain if it was locked to SoL either... but not trying to be THAT guy. If we could use the hide face script the black paintball looking mask uses where it's basically a face replacement for some of them that would be perfect for a lot of faces too, honestly. Though I would LOVE to have this mask in the city so I have a more personalized NOT face too if you know what I mean bc I think it's extended cheeks would cover my cheek bones. Either way.... <3

I love you Devs and all the hard work you do for this city! Hope you have a great day!

**Comment by Knoxmortis** [comment]
... Please? <3

**Comment by DaxterPancake** [comment]
Two maks have been added with this next clothing update that work with bigger faces, a bandana and a buff style one.

In the future we may look into ways that allow bigger faces to fit in all masks but until then, this will be closed.

Cheers,
Daxter.
Project Manager.
