### ISSUE TITLE
SoL External Repair Bay?

### ISSUE THREAD

**Issue by Knoxmortis** [InZidiuZ/legacy-assets-issue-tracker#428]
**Name:**
Knoxmortis#2163

**Summary:**
Requesting a external repair bay at SoL repair for bigger vehicles like adding a spot to the left of the shop in the ally by the fence, Doesn't even necessarily have to be marked, or even in the parking lot outside the shop either way.

**Reason:**
Fly Wheels has the bay out back for trucks, would be nice to have a slot next our shop for that, seems unfortunate to have to pay other mechanics to repair our tow trucks, considering we're mechanics ourselves.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) instead.
