### ISSUE TITLE
[maps/hayes_autos_body_shop] Water Cooler at Hayes Repair Shop

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#429]
Name:
Riedling#8969

Summary:
Would like to request a water cooler in the office at Hayes Repair Shop .

Link:
N/A

Reason:
We would like to be on par with other shops in the area and have a Water Cooler in our office / lobby for employees and customers to use.

**Comment by WavyPC** [comment]
This would be extremely useful

**Comment by Gingerninja78** [comment]
this is a very nice feature to have for the customers when they are waiting for their repair to be finished can grab a quick drink,

**Comment by Smach90** [comment]
It would also help for garbage while they are picking up trash at hayes and they need a quick drink.

**Comment by skateboarddude30** [comment]
definitely would be nice to have, only a coffee machine currently

**Comment by wero1006** [comment]
love me some water while they do some great repairs!

**Comment by dkokkos** [comment]
allow me to be the water champ of Hayes please!

**Comment by antihero6713** [comment]
Added in water cooler
![image](https://user-images.githubusercontent.com/25892037/122709761-eb1ef280-d22c-11eb-8a3d-b33a606ec1d7.png)
