### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/legacy-assets-issue-tracker#43]
**Reporter:**
Who is reporting this? Please include discord name.RaviCan'T#0001

**Summary:**
Write a summary of what you're experiencing. Having this bug in PD.

## Additional Information

**Video:**
If suitable, include some screenshots. https://drive.google.com/file/d/1FJfAzzKxlYHG4XJuCnbJG49PMKFf1KTX/view?usp=sharing

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

Not too sure what's causing this however i can't do much about that. Try walking instead of running at the door. 

_Kaprenko_

_**OP-FW Vehicle Dev**_
