### ISSUE TITLE
[maps/hayes_autos_body_shop] Add Changing Circle at Hayes Mechanic Shop

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#430]
Name:
Riedling#8969

Summary:
Would like to request a Changing Circle for Mechanics in office at Hayes Repair Shop .

Link:
N/A

Reason:
We would like to be on par with other shops in the area and have a Changing Circle in our office so that Employees can change into their uniforms on premises.

**Comment by WavyPC** [comment]
This would really be a great feature for all the mechanics in shop.

**Comment by Gingerninja78** [comment]
this would be nice so that we can get changed from street clothing to work outfits iin shop

**Comment by Smach90** [comment]
Also nice bc locals tend to punch sometimes and it's a pain to go to a clothing shop in the middle of a shift lol

**Comment by skateboarddude30** [comment]
locals are crazy at hayes, should definitely have this for employees to have hat & glasses back

**Comment by wero1006** [comment]
This would be very professional.

**Comment by Nuziatella** [comment]
Wrong github. Place your request in [this one](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
