### ISSUE TITLE
[maps/hayes_autos_body_shop] Car Wash at Hayes Automotive Shop

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#431]
Name:
Riedling#8969

Summary:
Would like to request a car wash at Hayes Repair Shop .

Link:
N/A

Reason:
We would like to be on par with other shops in the area and have a Car wash available to our customers.  Currently, the closest carwash is over 8 blocks away in Little Seoul, which is very inconvenient for our customers.  We would like one of the simple air / water pumps, similar to Flywheels, places in between bays 1 and 2 against the brick.

**Comment by WavyPC** [comment]
This would be awesome!

**Comment by Eggowaffled** [comment]
Would be awesome to be able to provide this!

**Comment by Gingerninja78** [comment]
this would be a great service to provide as all the other shops can provide the wash facility

**Comment by Smach90** [comment]
This would honestly put them on par with the other repair shops and would keep the mechanics from having to purchase washing kits

**Comment by skateboarddude30** [comment]
almost no carwashes in the area so this would be super nice. hard to charge people for a wash when the kits are $50 and a carwash is $12

**Comment by wero1006** [comment]
Please add one. all i need is a wash after the great repairs.

**Comment by dkokkos** [comment]
I just want to be able to receive the full package repair + wash from the amazing mechanics there!

**Comment by antihero6713** [comment]
Added car wash to both side 
![image](https://user-images.githubusercontent.com/25892037/122709699-c1fe6200-d22c-11eb-89e6-46d2a21f8ed8.png)
