### ISSUE TITLE
[maps/comedy_club] ATM Comedy Club 

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/legacy-assets-issue-tracker#433]
Name:
Who is suggesting this? Please include discord name.
claystehling#4598

Summary:
Write a short summary of what your suggestion is about.
Add an ATM to The Comedy Club

Link:
If there are any links to what you're suggesting, please add them here.
N/A

Reason:
Why would your suggestion be a good addition to Legacy?
We hold a lot of events the comedy club and always have to tell people to make sure to bring money ahead of time before coming to the events. This would easy people paying at the door if there was an atm located inside where they could take out money before hand.

**Comment by antihero6713** [comment]
Added atm to wall 
![image](https://user-images.githubusercontent.com/25892037/122708784-f8d37880-d22a-11eb-998f-61fb8af83e81.png)
