### ISSUE TITLE
Weed Shop Add Items

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/legacy-assets-issue-tracker#434]
**Name:**
o0ochanceo0o#5735

**Summary:**
Add edibles and blunts to the list that we could sell at Green Wonderland

**Link:**
NA

**Reason:**
Spoke with Antihero and believe this is on the roadmap.  The new weed shop is open and has been growing a lot.  We have received a lot of requests for this.

**Comment by DaxterPancake** [comment]
This is not a framework issue. 
This is something you should be discussing in roleplay with government or whoever.

Closing due to not being something for the tracker.

Cheers,
Daxter.
Project Manager.
