### ISSUE TITLE
[maps/?] Add locks to Lost MC compound and assign to mechanic job role

### ISSUE THREAD

**Issue by Insidious-Space** [InZidiuZ/legacy-assets-issue-tracker#435]
**Name:**
Artoir#3860

**Summary:**
Currently no one in the city has keys to the Lost MC compound or clubhouse. There are locks on the clubhouse doors currently. Ideally a lock could be added to the front gate and bay doors as per other mechanic shops in the city. 

Clubhouse and Shop keys could be tied to the Mechanic job role. 

**Reason:**
Currently no Lost MC members are able to lock their clubhouse which resides in a busy public business. This doesn’t make much sense in terms of RP. In addition, no mechanics are able to lock either the main gate or bay doors which is a very useful function available to other mechanic shops in the city

**Comment by InZidiuZ** [comment]
When you say the 'Lost MC compound', do you mean [this](https://gyazo.com/8f914c527547b2a6bea862277022b4db) place?

**Comment by Insidious-Space** [comment]
> When you say the 'Lost MC compound', do you mean [this](https://gyazo.com/8f914c527547b2a6bea862277022b4db) place?

That’s the one indeed

**Comment by InZidiuZ** [comment]
This has now been added.
