### ISSUE TITLE
[maps/dealership_premium] Add GPS Marker for RACE

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#436]
**Name:**
Riedling #8969

**Summary:**
Asking for GPS Marker for RACE (Rockford Auto Concierge Experience) (Used Car Shop)

**Link:**
N/A

**Reason:**
Per Governor's suggestion, asking for a marker on the map to indicate where the RACE Used Car Shop is located.  ITs difficult to explain to people our exact location, and this would be extremely helpful for people that don't even know we are an option!

**Comment by InZidiuZ** [comment]
Is this an official thing? Is there an interior for this?

**Comment by z-Lunar** [comment]
> Is this an official thing? Is there an interior for this?

Yes, it uses the Luxury Autos interior

**Comment by InZidiuZ** [comment]
This has now been done.
