### ISSUE TITLE
[maps/dealership_premium] Remove Plastic displays at RACE

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#437]
**Name:**
Riedling #8969

**Summary:**
Remove clear display stands from RACE showroom (4 total)

**Link:**
N/A

**Reason:**
There are several plastic displays at RACE on the showroom floor that are clear, and have a benefactor logo on them.  There are 3 along the main windows, and one next to the circle display island. They are "cemented" objects, so when moving cars into and out of the showroom, they make getting around difficult, and risk scratching the cars.  These don't serve any "RP" purpose, so asking for their removal.

**Comment by InZidiuZ** [comment]
What is 'RACE', and could you explain what you mean by 'clear display stands'?

**Comment by Spitfire2k6** [comment]
> What is 'RACE', and could you explain what you mean by 'clear display stands'?

It's a business on the NA/EU server. The display stands are the props next to the windows that display marketing material.

**Comment by riedling11** [comment]
Thanks @Spitfire2k6 !! RACE is the used car dealership that is in the Luxury autos building.  You added a GPS marker for is in another request. There are 3 display stands near the main windows, and another next to the high end display platform.
Thanks!

**Comment by z-Lunar** [comment]
Will do this when I wake up :)

**Comment by riedling11** [comment]
Awesome, THANKS!!!  Have a good rest!

**Comment by antihero6713** [comment]
Removed plastic stands
![image](https://user-images.githubusercontent.com/25892037/123534731-30d83100-d6ed-11eb-878f-34ed162f4ab9.png)
