### ISSUE TITLE
[maps/paleto_bay_moto] SoL Repair Colision Mapping.

### ISSUE THREAD

**Issue by Knoxmortis** [InZidiuZ/legacy-assets-issue-tracker#438]
**Reporter:**
Knoxmortis#2163

**Summary:**
Subject SoL Mechanic Shop
We have several "Holes" in the walls, and roof of the new shop also the over hang above the door, has a hole. The collision mapping needs work, you can "fall through" the roof, in multiple areas, and that allows you to possibly access (restricted areas) like the club meet room. Also locals can run through the walls details below. We need Locking doors also, for the repair bay, and the club room. Also the front wall (with the door) is both inside and outside the shop, so if you park by it, you'll come back to find a flipped car at best, possibly blown up even. 

It would be really nice if we had a "exit door" also, so we aren't funneling cars through 1 door, esp since trucks kinda fit, but not really, so they block the door, if we could make it like 3ft taller would help this issue, and we have space inside to make a secondary front door, or a back door. 

The ATM is also REALLY far from the garage, if we could get one inside that would be AMAZING, as well as maybe snacks to go with the water... I'm assuming someone is already working on the Storage Locker as there's a spot for it. But I'm more than slightly confused about the wooden park bench table with what appears to be meth supplies on it.. would be nice if the bar was there instead but that's small potatoes FR compared to other issues. 

## Screens
https://media.discordapp.net/attachments/849072830423498792/857648601001230406/unknown.png?width=857&height=418
https://media.discordapp.net/attachments/840609164837650475/857650121793863710/2021-06-24_1.png?width=743&height=418
https://media.discordapp.net/attachments/840609164837650475/857650157226033152/2021-06-24_2.png?width=743&height=418

## Additional Information
A local car ran through the shop sideways, killed someone in the middle of the shop next to the wooden table, caused a fuel leak, and blew up some things yesterday... I had to get the downed person unstuck from the upside down using a hole in the roof, before they popped up in one of the far bays bc they got BLOWN THROUGH a wall. 
 
## Notes
Will add screens if requested, but the "holes" are easy to find if you go on the roof, or play with the wall next to the door. Let me know if you need more info.

**Comment by AdeptCL** [comment]
As the owner of the shop itself, the interior design from the old one, I really don't mind. It's a new vibe. I do miss the bar being there, but I definitely like the whole "mechanic shop" vibe throughout the new interior.

There are definitely some issues with the sound barriers, as walking through the interior, you simply cannot hear someone if they're in a separate half/side of the shop.

The collisions I've noticed are on the roof, and sometimes you'll fall in and end up in the repairing area of the shop.

An ATM would be a big priority, as it's causing individuals to go quite the distance on foot when needing cash to pay for their repairs. Finally, what Knox had mentioned in the lockers, near the office there is a whole locker set on the wall. So having a locker system implemented will definitely assist.

**Comment by z-Lunar** [comment]
This has been resolved in latest commit.

**Comment by Knoxmortis** [comment]
I've also landed in the conference room, and storage room from the holes. Which is disconcerting bc if you know much about this mapping and LOD issues, you'll know when you access that area in this way, you can't see the area really but you can hear, and ppl in the area can't see you... Meaning you might have literal ears that you can't see.
