### ISSUE TITLE
Can't review cars as a mechanic.

### ISSUE THREAD

**Issue by Detnom** [InZidiuZ/legacy-assets-issue-tracker#439]
**Reporter:**
Who is reporting this? Please include discord name.
Detnom#6912

**Summary:**
Write a summary of what you're experiencing.
I work as a mechanic in Mosley's. When I try to fix a car, I am able to review a vehicle one time after I fly in, but no review shows up and I'm stuck holding the clipboard until I hard nap (pressing U also works to rid myself of the clipboard, but doesn't let me review another car). Also can't place crafted doors/windows on cars that need them.

## Additional Information
I'm aware of at least one other mechanic having this issue, _Robin_#7329 on Discord. It seems our issues started around the same time as well for some reason.

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.
Have met with moderators in support, they tried stripping my job and giving it back multiple times, but it sadly didn't fix anything. Have also cleared cache multiple times.

**Comment by FullMetalAlphonse** [comment]
I'm having the exact same problem

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this. Use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) instead.

**Comment by Detnom** [comment]
> This is the wrong issue tracker for this. Use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) instead.

This is where I was sent by Twentz, lol. Will post it over there though.
