### ISSUE TITLE
Ford Raptor Enhancement

### ISSUE THREAD

**Issue by Shifty123** [InZidiuZ/legacy-assets-issue-tracker#44]
**Reporter:**
Shifty#4167, Shifty

**Summary:**
The ford raptor feels like it has vanilla handling, the gears are very short and its capping at aroudn 110-120mph. The Nissan titan is cheaper and is an 8 seater and is way better than this car which is a 2 seater

**Comment by Karpenkooo** [comment]
Hey 

This vehicle has been buffed a long time ago. Sorry for the rapid response :)
