### ISSUE TITLE
[imports/police] Go back to the old Black and White SASP liveries

### ISSUE THREAD

**Issue by Cerrella** [InZidiuZ/legacy-assets-issue-tracker#440]
**Name:**
Cerrella

**Summary:**
Go back to the old Black and White SASP liveries. 

**Link:**
///

**Reason:**
Alright, first of all the new liveries are cool, they're unique and they're fun. However the old black and white ones used to fit the feel a lot better. They matched the uniforms we have the ability to wear right now and from getting a overall feel from most people people liked them a lot better. I don't think we need to necessarily go back to these liveries, more of a possible colour change to black and white as It fits better.

**Comment by joevapes3** [comment]
We definitely won't be going back to the old liveries, but we can see about doing bit of a color change for the existing ones, or possibly even a new layout in the near future. Appreciate the suggestion.

**Comment by z-Lunar** [comment]
> We definitely won't be going back to the old liveries, but we can see about doing bit of a color change for the existing ones, or possibly even a new layout in the near future. Appreciate the suggestion.

we definitely need heavy inspiration from the old ones than...lmfao the new ones are ugly af
