### ISSUE TITLE
[maps/vanilla_unicorn] Small & Easy Vanilla Unicorn Upgrades to enhance tremendously employees RP experience

### ISSUE THREAD

**Issue by MsBBBones** [InZidiuZ/legacy-assets-issue-tracker#441]
**Name:**
BB Bones, BertBones#2590

As of right now, The Vanilla Unicorn is in a thriving state and that's extremely beneficial for both employees and the city's economy alike. However, as an owner, I'm facing certain inconveniences that could easily be solved to enhance the roleplay experience from both an employee and a consumer perspective. Here are some simple and easy changes that could be major improvements for the Vanilla Unicorn.

**ATM's OUTSIDE of the club:** 

- There are currently THREE ATM's inside of the Vanilla Unicorn which are conveniently placed for customers to take out cash as necessary in order to tip the dancers, which is great. The problem we're facing is that not everyone carries cash on their person, so they rely on ATM's to make transactions to pay the entry fee of an event. Because the Vanilla Unicorn only has ATM's inside, we have to let them go in to take out money and have them come back to pay. Which not only delays the entry line, but also adds a small window of chaos to form as not everyone is very honest, so they do tend to run inside and never come out to pay. It makes the security team's job much harder, and makes an uncomfortable atmosphere inside a club who's sole purpose is to have fun. Adding an ATM and placing it conveniently right by the door would benefit both the employees AND the customers. Resulting in honest, easy and quick roleplay. x

**A Changing Room Backstage:** 

- Our dancers have expressed concerns about not being able to change backstage. They have to run all the way to the nearest clothing store in order to change outfits, which not only leaves them exposed and feeling uncomfortable outside, but also consumes an abundance of time from their schedule. Adding a changing mechanism to the backstage of the Vanilla Unicorn (Same as the one that's in the backstage room of the Comedy Club) will not only allow them to change their outfits and be on time for their shifts, BUT it'll also allow them to have numerous costume changes to boost revenue and enhance the experience for the customers.

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/123893041-ab8d9000-d929-11eb-99cc-78dc198f4dd0.png)
ATM has been added to the outside.

**Comment by InZidiuZ** [comment]
There already is a clothing spot, though locked behind the 'Business / Vanilla Unicorn' job.

**Comment by MsBBBones** [comment]
Hi! What part of the club is it in? 🥺

**Comment by InZidiuZ** [comment]
Right [here](https://gyazo.com/006dba2f9094e2280717eaf9221db30d).

**Comment by MsBBBones** [comment]
Ooop- We don’t see that when we go in but maybe the server hasn’t updated
yet 😁

**Comment by InZidiuZ** [comment]
It has been there for a few months. You have to have a certain job to see it. (Job name "Business" and department name "Vanilla Unicorn")

**Comment by InZidiuZ** [comment]
I'll close this as everything seems to be okay now.
