### ISSUE TITLE
Suggestion: Move ATM at RACE

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#442]
**Name:**
Riedling#8969

**Summary:**
Would like ATM Relocated

**Link:**
NA

**Reason:**
Currently, the ATM has been located in the showroom, which looks a little unsightly for a Luxury Dealership.  Requesting that it be moved to the transition area by the workshop.  Picture attached..

![race-atm-cooler2](https://user-images.githubusercontent.com/26015469/123527698-30b54280-d6a7-11eb-8bac-a33772f7db5e.png)

**Comment by antihero6713** [comment]
Added new atm position and added watercooler
![image](https://user-images.githubusercontent.com/25892037/123534184-3895d680-d6e9-11eb-9d35-072506c1211c.png)
