### ISSUE TITLE
Suggestion: Add Water Cooler at RACE

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#443]
**Name:**
Riedling#8969

**Summary:**
Adding water cooler at RACE

**Link:**
NA

**Reason:**
Asking for a Water Cooler for employees that can't leave the site while cars are in the lobby.  Until we get locking doors down the road, this would be very helpful.  Location in picture attached:

![race-atm-cooler2](https://user-images.githubusercontent.com/26015469/123527779-c5b83b80-d6a7-11eb-8f7f-c1b908fc9d68.png)

**Comment by antihero6713** [comment]
Added new atm position and added watercooler
![image](https://user-images.githubusercontent.com/25892037/123534184-3895d680-d6e9-11eb-9d35-072506c1211c.png)
