### ISSUE TITLE
t/extra 8 issue on PD vehicles

### ISSUE THREAD

**Issue by T4NZIM** [InZidiuZ/legacy-assets-issue-tracker#444]
**Reporter:**
Who is reporting this? Please include discord name.
TᴀɴZɪM#5534

**Summary:**
Write a summary of what you're experiencing.
If the /extra 8 is enabled in custom PD vehicles, and you go midair/make a jump, the car will always flip left to right. Doesn't matter how you are jumping, it will always flip left to right. This is so annoying. Please fix it.

## Additional Information
The ford crown victoria and dodge hellcat, these two vehicles are the exception to this. The extra 8 is the Spotlight.

**Screenshots:**
If suitable, include some screenshots.
https://imgur.com/a/4UMLZ6a

**Notes:**
For anything else noteworthy.

**Comment by Nuziatella** [comment]
This is a won't fix. Don't enable the extra
