### ISSUE TITLE
[maps/dealership_premium] Remove hoist at RACE

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#445]
**Name:**
Riedling#8969

**Summary:**
Requesting removal of engine hoist in garage bay at RACE

**Link:**
N/A

**Reason:**
We don't have a parking lot, so removing this object will allow us to more efficiently park cars in the garages that we do have. As it sits, we cant use the corner as this is in the way.

![hoist](https://user-images.githubusercontent.com/26015469/123689516-ec49b400-d818-11eb-9b33-2e80748474b5.png)

**Comment by antihero6713** [comment]
@riedling11  Are their any other changes wanted before I fix this one?

**Comment by riedling11** [comment]
No, I apologize for the trickling in of requests.  The remainder will come in once we work a few things out with the state.  As always, appreciate the team's hard work!

**Comment by Geevum** [comment]
Yes, removing the hoist would give us much needed space in the bay

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/124370986-3e406e80-dc4b-11eb-985e-04a964d91eb9.png)
Engine hoist has been removed
