### ISSUE TITLE
Suggestion: Add Carwash at RACE

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/legacy-assets-issue-tracker#446]
**Name:**
Riedling#8969

**Summary:**
Add a carwash at RACE

**Link:**
n/a

**Reason:**
As we bring cars into the showroom from test drives, it would be awesome to have a carwash between the bay doors.  we are currently spending a lot of money on washing kits and this would be an amazing addition.,

![carwash2](https://user-images.githubusercontent.com/26015469/123895554-a0d0fc00-d925-11eb-8a91-cfdef09ced3c.jpg)

**Comment by Geevum** [comment]
We could really use a car wash station, please

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/124370991-5d3f0080-dc4b-11eb-93ab-83e674a878d2.png)
added car wash to outside race doors
