### ISSUE TITLE
[?] Changes to Vehicle Damage

### ISSUE THREAD

**Issue by dxvyxd** [InZidiuZ/legacy-assets-issue-tracker#447]
**Name:**
dxvy#9492

**Summary:**
My suggestion is to change the vehicle damage from just straight up leaking => explosion to making a car disable when its shot a lot. 

**Link:**
N/A

**Reason:**
I have noticed that in a lot of car fights, cars tend to leak fuel/blow up very quickly which i know is intended and i know this is to try and stop people from fighting in cars, however the aim to start more fights on foot is hard when you blow up and don't have any time to get out of the vehicle. If a car is shot a lot, i think the car should disable which forces people to get on foot (It wouldn't need to take a lot of shots to disable). Vehicles are the main source of getting away (from cops/gangs) and finding eachother. Right now, if anybody shoots a vehicle only a couple of times it starts leaking and soon catches on fire which causes it to blow up, you simply don't have enough time to get on foot. If a car disables (enables when repaired with a repairkit) it would force people to get on foot and fight. Which i know is the main reason for the current vehicle dmg. I know a lot of people prefer foot fights but its simply impossible to force it by blowing up cars within seconds of a fight.

**Comment by lildiavolo** [comment]
+1 for sure,

The current mechanics of car blowing up that quickly doesn't achieve the goal in mind (forcing people to get out of their vehicles to finish off a fight on foot), but rather it just turns car fights into who blows up the other persons car the fastest.

**Comment by Nuziatella** [comment]
This will be considered.

**Comment by Darskus** [comment]
ngl couldnt have said it better myself

**Comment by MetaHatter** [comment]
Not sure if this will help but there's a FiveM project that does some of this.
https://forum.cfx.re/t/release-realistic-vehicle-failure/57801

**Comment by Nuziatella** [comment]
This has been resolved.
