### ISSUE TITLE
[imports/ems] EMS Boat

### ISSUE THREAD

**Issue by ekhowan12** [InZidiuZ/legacy-assets-issue-tracker#449]
**Name: Ekhowan
Discord: Ekhowan_#7222

**Summary:**
A boat unit will be very helpful for EMS department. Sometime we receive some calls form deep sea. Most of them are plane crash patients. Now there is newly aviation department  available in the city. Those deep sea case will be more then before. Main reason of my suggestion is to make the rescue more genuine. As helicopter cant land on water. Ultimately rescue team climb down to rescue a patient. But its too hard to swim all the way to any nearest island or beach to treat the patient is hard .If we get a boat unit as police we can use that boat to get the patient within a short time period. It will be more realistic 

**Link:**
N/A

**Reason:**
It will make a differences between other servers EMS RP. Another big reason is EMS department will get some now way to initiate RP 
![Screenshot_6](https://user-images.githubusercontent.com/78637016/124559257-58ea3180-de5d-11eb-9332-59a08ba9124a.png)

**Comment by GloriousMir** [comment]
Impressive Idea.

**Comment by joevapes3** [comment]
I really like this idea, I've added it to my to-do board and will consider the possibility of adding something along this line, as I agree it's a needed asset. Though I may look into seeing if I can find a shared asset for both PD and EMS in regards to boats so we can consolidate the use of a single asset vs multiple if that's possible. Thanks for the suggestion!

**Comment by joevapes3** [comment]
EMS boat was recently added and will be live on when the next vehicle assets are merged. Thanks for this suggestion.
