### ISSUE TITLE
nissan titan

### ISSUE THREAD

**Issue by tankfurious** [InZidiuZ/legacy-assets-issue-tracker#45]
**Reporter:**
tankfurious

**Summary:**
not been able to change livary on the titan

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
when you purchase the vehicle from the exclusive store you can see many livarys on the nissan titan but we are not able to access these in bennys.

**Comment by Karpenkooo** [comment]
Hey,

From what i know this should now be fixed.

_Karpenko_

**_OP-FW Car Dev_**
