### ISSUE TITLE
[imports/civilian_?] Jeep Wrangler issue

### ISSUE THREAD

**Issue by dm33180** [InZidiuZ/legacy-assets-issue-tracker#450]
**Reporter:**
Dan The Man#7158

**Summary:**
Jeep wrangler on legacy looks like garbage after 1 minute of driving. Constantly getting dirty. Does not feel like a premium product. PDM vehicles do not have this issue, not sure if it's a bug.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
Any way to get a refund?

**Comment by iGreatWhite** [comment]
Refunds are not given in most circumstances. "Looks like garbage", not sure what this entails. Probably would be best to addon more details to your issue than just these vague things.

**Comment by dm33180** [comment]
> Refunds are not given in most circumstances. "Looks like garbage", not sure what this entails. Probably would be best to addon more details to your issue than just these vague 
So the vehicle immediately gets dirty in my eyes after washing it. The garbage comment was based on the fact that I see nothing but dirt /mud all over my wrangler at all times. so in my opinion it does not look pretty or clean when it should. Is this how it is supposed to be or could it possibly be a bug?

**Comment by joevapes3** [comment]
As stated above, refunds cannot be given for EDM purchases. As far as the dirt mapping goes, I've never seen or heard any complaints previously, and the vehicle has been in the server for over a year now. With that said, I added the jeep to my to do list, and will take a look at the dirt map and see if there is any issues that stand out, and get them corrected if founded. Thanks for bringing this concern to our attention.
