### ISSUE TITLE
Bikes and vehicles disappear

### ISSUE THREAD

**Issue by JoshuaJ56** [InZidiuZ/legacy-assets-issue-tracker#451]
**Reporter:**
JoshuaJ56#2749

**Summary:**
Anytime we park our bikes at the "clubhouse," they disappear after a certain amount of time and are retrieved at 0.0 body.

## Additional Information
Senora Road 6

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
Please remove the trees in my front yard. lol

**Comment by InZidiuZ** [comment]
This issue of vehicles disappearing at a certain location most likely does not have anything to do with assets, so closing.
