### ISSUE TITLE
[maps/paleto_bay_moto] Paleto Bay Repairs Additions

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#452]
**Name:**
AdeptCL#0402

**Summary:**
Addition of the following to the Paleto Bay Repairs shop: ATM, personal lockers, and a car washing function.

**Link:**
ATM location: [https://prnt.sc/19ol3hg](https://prnt.sc/19ol3hg)
Personal lockers: opposite the office.
Car washing: [https://prnt.sc/19oltjv](https://prnt.sc/19oltjv)

**Reason:**
It's to keep the balance between all mechanic shops. The closest ATM is quite the walk/run distance. Personal lockers for mechanics to store large counts of materials. Car washing to add an element of further vehicle care to the mechanic shop.

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/125150971-cde59180-e111-11eb-8acf-aaacf3990443.png)
Car wash 
![image](https://user-images.githubusercontent.com/25892037/125150977-d938bd00-e111-11eb-9ba7-5f9a6e2d906f.png)
ATM

Lockers are done by ben.

**Comment by InZidiuZ** [comment]
Lockers have now also been added.
