### ISSUE TITLE
[imports/civilian_*] Mercedes AMG GTR

### ISSUE THREAD

**Issue by ItsK13ran** [InZidiuZ/legacy-assets-issue-tracker#454]
**Name:**
Kieran#9372

**Summary:**
Import of the Mercedes AMG GTR

**Link:**
https://www.gta5-mods.com/vehicles/2017-mercedes-benz-amg-gt-r-add-on-template

**Reason:**
Something new and fresh to the sport/super car collection on EDM that i also think would be really appealing to racers.

**Comment by joevapes3** [comment]
I am working on the latest exclusive dealership vehicles, and this vehicle will be considered as a possibility. I am a big fan of this car as well. I can't reveal the exact vehicles that are going into the pack, but they will become known once they make it into the city. Appreciate the suggestion!
