### ISSUE TITLE
[imports/civilian_*]  Replace Range Rover Velar Model

### ISSUE THREAD

**Issue by ItsK13ran** [InZidiuZ/legacy-assets-issue-tracker#455]
**Name:**
Kieran#9372

**Summary:**
The current Range Rover Velar 2019 model doesn't have a working trunk You can store items in the back, but the door its self doesn't open visually and doesn't allow others to get into the trunk. I have found another model that does seem to have a working trunk.

**Link:**
https://www.gta5-mods.com/vehicles/range-rover-velar-2019-add-on-i-rhd

**Reason:**
It would visually fix the opening of the trunk and allow other players to get into it.

**Comment by Nuziatella** [comment]
This is a won't fix. The model is locked
