### ISSUE TITLE
[maps/paleto_bay_moto] SoL Repair Colision Mapping.

### ISSUE THREAD

**Issue by Knoxmortis** [InZidiuZ/legacy-assets-issue-tracker#456]
**Reporter:**
Knoxmortis#2163

**Summary:**
Subject SoL Mechanic Shop
 The collision mapping needs work, you can "fall through" the roof, in multiple areas, and that allows you to possibly access (restricted areas) like the club meet room. The awning above the repair bay door, has a hole. As well as the awning above the "showroom" doors has weird collision boxes. The entire "lifted" roof on top of the flat roof, you can walk in to the wall and just "fall in the shop".

## Screens
https://media.discordapp.net/attachments/849072830423498792/857648601001230406/unknown.png?width=857&height=418
https://media.discordapp.net/attachments/840609164837650475/857650121793863710/2021-06-24_1.png?width=743&height=418
https://media.discordapp.net/attachments/840609164837650475/857650157226033152/2021-06-24_2.png?width=743&height=418

## Additional Information
We need Locking doors also, for the repair bay, and the club meeting room. Repair Material theft has been a issue. Also wondering if we can get snacks/water like many other businesses have.
 
## Notes
Will add screens if requested, but the "holes" are easy to find if you go on the roof, or play with the wall next to the garage doors. Let me know if you need more info.

**Comment by antihero6713** [comment]
Collision has been fixed.
