### ISSUE TITLE
[imports/civilian_*] McLaren 765LT - Aventador - Mazda RX7

### ISSUE THREAD

**Issue by WavyPC** [InZidiuZ/legacy-assets-issue-tracker#458]
**Name:**
WavyPC#5858

**Summary:**
Import of the McLaren 765LT - Lamborghini Aventador Roadster - Mazda RX7 Spirit R
**Link:**
https://www.gta5-mods.com/vehicles/mclaren-765lt-nejc 

https://www.gta5-mods.com/vehicles/lamborghini-aventador-svj-roadster-oiv-template-21d457d6-3eaa-4fea-9aa0-94097bc9c457

https://www.gta5-mods.com/vehicles/2002-mazda-rx-7-spirit-r-type-a-series-iii-fd3s

**Reason:** These cars would be a great addition to the EDM Family. Very appealing towards car enthusiast and the race community.

**Comment by joevapes3** [comment]
I am currently working on the latest exclusive dealership vehicles, and there are some good suggestions here. Some of these vehicles may or may not be already apart of that pack, but the details of which vehicles are being considered won't be released until they're in the city. I appreciate the suggestions you made, and great picks!
