### ISSUE TITLE
[maps/the_lost_mc] Minor changes to LostMC Shop

### ISSUE THREAD

**Issue by AZTricky** [InZidiuZ/legacy-assets-issue-tracker#459]
Name: Gary Nemex (Shop Supervisor for LostMC) | Discord: AZTricky#1337

Summary: 2 Minor changes to the LostMC Mechanic Shop to improve quality of life for our mechanics. Both recommendations have been approved by the Head Mechanic (TJ) and the Lost MC itself.

Link: 
Outside Sign: https://cdn.discordapp.com/attachments/836846390427516948/865300659205046282/LostMC_Sign.png
Outside Sign Graphic: https://cdn.discordapp.com/attachments/836846390427516948/865301118363500555/LostMCLogo_Alphad.png
Outside Bay: https://cdn.discordapp.com/attachments/836846390427516948/865300663554277386/LostMC_OutsideBay.png

Reason: In my 4 months working in this shop there are a few minor things that recur that I feel are easily fixed that would help a lot. The first are people coming in who are new to the city asking "Is this the/a mechanic shop?" and I feel a simple sign would fix this. Currently we're the only shop in the city without one. A light or two on the sign at night would also be nice. 

My 2nd ask does 2 things, cleans up some trash from the front to give us more open space and add in an outside repair bay that would enable us to fix semi's (which we can only fix body on currently) and easier fixing of our tow trucks (which we can do now but it's kind of scuffy on how we have to go about it by squeezing the truck into the main bay).

**Comment by MetaHatter** [comment]
Also, if possible, can someone check the collision on the roof of the large building on the east side?  You can climb on invisible things.

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/127796597-bde1773a-fcbb-4544-9074-ec1bcb62cde1.png)
new sign
![image](https://user-images.githubusercontent.com/25892037/127796919-80bbe352-caf8-49bb-8f02-3bb9e177eeb7.png)
better bike parking 
![image](https://user-images.githubusercontent.com/25892037/127796786-e9d3791e-a137-40a0-9d08-0eadc92357db.png)
place for truck repair

**Comment by MetaHatter** [comment]
![LostSign](https://user-images.githubusercontent.com/84351858/127877394-66b7551c-821c-4974-81d9-4cb444024a3e.png)

@antihero6713 Any way to use this for the sign instead?
