### ISSUE TITLE
Pegassi Toros

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/legacy-assets-issue-tracker#46]
**Reporter:**
Badwolf#3160

**Summary:**
The pegassi toros has 2 types of spoilers. and none of them work when you put them on in bennys

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by SATIN187** [comment]
the spoiler preview is disabled so you wont be able to see them on the car at bennys until you actually purchase them
