### ISSUE TITLE
[maps/vinewyard] Winery QOL Adjustments

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/legacy-assets-issue-tracker#460]
Name: 
vol 5#3752

Summary:
Winery QOL Adjustments

Link:
N/A

Reason:
Here is a comprehensive list of things I believe would be required to secure smooth operation of the Winery. Its a mix of priority requests and some bugs I have found along the way.  

Winery QOL Update

Priority(vendor, storage, garage):

local vendor like a bar - Copy paste of bar inventory with wine being a fraction of the price so future distribution would make sense. Current wine is $100 from any bar. I would like the price set to $40 so we can sell at($60-$80) below the current value of wine and still profit so employees can make additional cash. Vendor placement: At the top of the stairs in the wine cellar right where the barrels are. If you can not remove the barrels. Down in the wine cellar will do.

Kitchen storage - inside fridge for employees: The bigger the better, 1k storage will do though. If you would rather opt to put a personal locker storage there. That will also do just fine.

Garage at the barn - This would be most appreciated so we can provide golf carts for tours. The nearest garage to the Winery currently is 3miles out.

Bugs/issues:

Fix front 2 doors disappearing (For some reason the two front doors have issues with disappearing after being unlocked and locked again, once you come back to them after walking around in the winery they just poof)

Fix wine cellar door has 2 doors inside one(There are issues with locking the wrong one and its inside the other door)

Remove local spawns from inside winery(They spawn in the kitchen, lounge area by fire, upstairs bedroom, and all over the  the patio out back)

Remove table ped text on blackjack dealer

Main dining table seating to be useable

Future/wants:

Additional wine types if possible[White: Riesling($50), champagne($60), Sauvignon Blanc($70)] [Red: Pinot Noir($50), rose($60), Cabernet Sauvignon] New wine types are not a must at the moment.

Photos in order of document:

![Inked20210716093336_1_LI](https://user-images.githubusercontent.com/86331939/126046842-d5f91439-ac7c-4a7a-a5b7-6b994b66dbf3.jpg)
![Inked20210716093620_1_LI](https://user-images.githubusercontent.com/86331939/126046867-6bcdbb1e-30af-49ad-9086-6ca628d0de31.jpg)
![Inked20210716093512_1_LI](https://user-images.githubusercontent.com/86331939/126046876-b7513f19-c620-4f0c-a5c9-fb91ef9f74ae.jpg)
![Inked20210716093417_1_LI](https://user-images.githubusercontent.com/86331939/126046883-5b2154d9-9838-4a51-b05c-a20f514c6458.jpg)
![Inked20210716093353_1_LI](https://user-images.githubusercontent.com/86331939/126046895-0f2d866c-c6c5-4ce6-a6b6-b2a4acc17b6a.jpg)
![Inked20210716093447_1_LI](https://user-images.githubusercontent.com/86331939/126046903-794f80ea-13b3-4bad-a82f-a765bbf949cd.jpg)
![Inked20210716093709_1_LI](https://user-images.githubusercontent.com/86331939/126046931-2ee8062d-2be2-4eda-a27f-14dec6adb4cb.jpg)

**Comment by coalaura** [comment]
These are all [script issues](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
