### ISSUE TITLE
[peds/?] Larger mask options for bigger face

### ISSUE THREAD

**Issue by Tterby** [InZidiuZ/legacy-assets-issue-tracker#461]
**Name:**
Who is suggesting this? Please include discord name.
Bretters#0823
**Summary:**
Write a short summary of what your suggestion is about.
I'm wanting to be able to wear the masks within the clothing store. My face is too large to fit in pretty much all of them. I requested a re-skin to see if I could make my face smaller while still looking the same. Is there a way I can get the masks resized to be bigger? The two masks linked below are the style and being able to wear the different variants of that specific mask.
**Link:**
If there are any links to what you're suggesting, please add them here.
https://cdn.discordapp.com/attachments/858518709948907550/866735641488392242/unknown.png
https://cdn.discordapp.com/attachments/858518709948907550/866736033152499732/unknown.png
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would give myself and other people with the same face options to use these specific masks.

**Comment by DaxterPancake** [comment]
Two masks have been added with this next clothing update. A bandana and a buff style one. Both of these work with bigger faces. 

In the future we may revisit this to allow larger faces to wear all masks but until then, this is closed.

Cheers,
Daxter.
Project Manager.
