### ISSUE TITLE
Mayor and deputy mayor special Vehicles

### ISSUE THREAD

**Issue by Deaddro** [InZidiuZ/legacy-assets-issue-tracker#462]
Mayor and deputy mayor need some special
Vehicle to improve there rp and to make it more realistic,If you can add this it will be helpful.

https://www.gta5-mods.com/vehicles/cadillac-the-beast-presidential-state-car-add-on

https://www.gta5-mods.com/vehicles/cadillac-escalade-president-one-limosine

**Comment by DaxterPancake** [comment]
Closing due to not following the template. 

Please go [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose).

Select SUGGESTION and fill in the sections required.

Cheers,
Daxter.
Project Manager.
