### ISSUE TITLE
Decrease wheel spin for PD cars

### ISSUE THREAD

**Issue by T4NZIM** [InZidiuZ/legacy-assets-issue-tracker#463]
**Name:**
Who is suggesting this? Please include discord name.
TᴀɴZɪM#5534

**Summary:**
Write a short summary of what your suggestion is about.
Current PD vehicles are too hard to control. Too much wheel spin and very low acceleration. I think only PD vehicles are the only vehicle having so many wheelspins. A few days ago, car handling updates were made. Still, the wheelspin is too much and very hard to control PD vehicles. And also maybe increase the speed as well a little bit?

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Except for PD vehicles, all other PDM/EDM vehicles have very low wheelspin so far I know and checked. So I think to make it smoother, reduce the PD vehicle's wheelspin as well. TIA!

**Comment by joevapes3** [comment]
Wheel spin for PD vehicles has already been reduced and will be updated once I've finished the next pd handling update.
