### ISSUE TITLE
[vehicles/*] Massacro Racecar and Jester Racecar low top speed issue

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/legacy-assets-issue-tracker#464]
**Reporter:**
Who is reporting this? Please include discord name. Frankenstein#8200

**Summary:**
Write a summary of what you're experiencing.  
Massacro Racecar and Jester Racecar version has too low Top Speed. They hardly touch 120mph. I have tried upgrading those vehicles but it doesn't have an effect at top speed. Acceleration is pretty normal but top speed stuck at around 120mph. With that speed it makes them the slowest cars in sports category.

## Additional Information
The Racecar version of these two cars should have been better than their normal version. But their normal version easily hits 160+ mph mark while racecar version lacks at top speed. 

**Screenshots:**
If suitable, include some screenshots.
https://imgur.com/cTzgq9n
https://imgur.com/V5X2PCA

**Notes:**
For anything else noteworthy.

**Comment by joevapes3** [comment]
They don't have handling files set for them, and in most case share the handling file with the non race version of the vehicle. I've added them to my to do list and will be updated soon. I'll leave this report open and update and close it when it's completed.

**Comment by Nuziatella** [comment]
Both vehicles missing data has been added.
