### ISSUE TITLE
[maps/2nd_gear] 2nd Gear Improvement

### ISSUE THREAD

**Issue by stubiewonder** [InZidiuZ/legacy-assets-issue-tracker#466]
**Name:**
Stuart Beefington
stubie#0538

**Summary:**
All the clutter (barrels, propane tanks, gas tanks, moveable objects) cleared out of the shop, they cause issues and get pushed around all the time.

Painted lines on the floor to show the repair spots better, currently 2 bays have no lines at all and can be hard to spot for a newcomer.

A solid fence line around the property, current fence is constantly breaking and causes a lot of clanging noises and locals tend to drive in to our lot and hit cars. Also a solid wall to keep people from driving through the outdoor bay to the "scrapyard"

Stronger/better lighting for night time. It looks like we are closed at night.

Remove the grand opening flag from the gas station roof. Fix the roof of the gas station, it is crumbling and has only two functional lights.

Turn the unused building across from the garage in to a proper convenience store with an interior.

**Reason:**
Why would your suggestion be a good addition to Legacy?
To clean up the shop and make it more accessible to customers and employees and improve the potential for RP in the area.

**Comment by V4P1Dx69** [comment]
Yeah, the other 2 repair spots are hard to find, would be great if it can be done.
