### ISSUE TITLE
[imports/civilian_*] 2017 RAM TRX concept EDM car

### ISSUE THREAD

**Issue by bloo5799** [InZidiuZ/legacy-assets-issue-tracker#467]
Reporter:
ST-406 [115-H] H. Hobbler#5187

Summary:
There needs to be a RAM in the game for civilians. I know cuz im a RAM guy. This Ram Model seems to be very well done. There are alot of customization options and the suspension seems to work very well. there is working dirt levels, breakable windows, and all the good stuff. this mod has been updated for a while now and looks very well done! This TRX concept model is just like the raptor, but the 575hp supercharged v8 should be a bit faster (the concept model had a hellcat engine, but it was tuned down to 575hp because they didn't have the drivetrain worked out for over 600hp. This should proper balance in the city since it wont be too op with just an imaginary 575hp). I believe this would be a great EDM car that will become very popular if added. there are no ram trucks for civilians in the game, and this is just wrong.

Additional Information
2017 Ram TRX. 

Links:
https://www.gta5-mods.com/vehicles/2017-ram-1500-rebel-trx-concept-add-on-beta

Notes:
For anything else noteworthy.

**Comment by Nuziatella** [comment]
This will be added in the next EDM carpack.
