### ISSUE TITLE
[imports/aircraft] Supermarine Spitfire Mk.IIB

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/legacy-assets-issue-tracker#468]
**Name:**
Spitfire2k6

**Summary:**
Import of aircraft model

**Link:**
https://www.gta5-mods.com/vehicles/supermarine-spitfire-mk-iib

**Reason:**
We currently have a decent selection of aircraft available but I want to try and deepen the pool of historic style aircraft.

**Comment by Nuziatella** [comment]
This will be looked into.

**Comment by antihero6713** [comment]
yes please!  huge warbird fan.

**Comment by Nuziatella** [comment]
This has been added
