### ISSUE TITLE
Police boat Suggestion

### ISSUE THREAD

**Issue by bloo5799** [InZidiuZ/legacy-assets-issue-tracker#469]
**Name:**
ST-406 [115-H] H. Hobbler#5187

**Summary:**
I came across this pack, and it seems to have many assets that may be valuable to the city. These boats may be a good use to the EMS and PD. This Pack has a FiveM package that includes the assets from the pack. There are coastguard, police and sheriff liveries for the boats. There are also some choppers that share sheriff and coastguard liveries. I also spotted a stretcher model in here. I thought i would share this as it looked valuable. 

**Link:**
https://www.lcpdfr.com/downloads/gta5mods/scripts/25465-coastal-callouts/

**Reason:**
We have a police boat, but it has no lights or sirens. it would be nice to have a boat the the police, sheriff, and EMS can use. (ems may be able to use the CG livery?). The medium sized boats will be great for PD shootouts at the Yacht and pier, and EMS can use the bogger boats to store more bodies. The boats would also come in handy at cayo perico.

**Comment by joevapes3** [comment]
I have a PD boat I am working on adding for both PD and EMS to share. It should be added here very soon. Thanks for the suggestion.
