### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/legacy-assets-issue-tracker#47]
**Name:**
badwolf#3160

**Summary:**
I would be very nice if we could get some drift cars coming into the city

**Link:**
https://www.gta5-mods.com/vehicles/6str-benefactor-schwartzer-aggressor-custom-add-on-tuning
https://www.gta5-mods.com/vehicles/6str-bravado-gauntlet-custom-add-on-tuning
https://www.gta5-mods.com/vehicles/awd-gymkhana-hoonicorn-drift-handling

**Reason:**

The addition of more drift cars could create more driving rp in the server because driving rp in the server is kinda low. Also these cars are sick and would be great having them in the server

**Comment by Karpenkooo** [comment]
Noted.
