### ISSUE TITLE
[maps/2nd_gear] 2nd Gear Additions

### ISSUE THREAD

**Issue by stubiewonder** [InZidiuZ/legacy-assets-issue-tracker#470]
**Name:**
Stuart Beefington
stubie#0538

**Summary:**
An extra bay inside the shop, we have plenty of room for it and have an idea of where to put it.

A work bench for the outside repair bay.

An outdoor car wash similar to what is at flywheels and other shops to service the larger vehicles.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Additions to make repairing easier and more efficient.

**Comment by DaxterPancake** [comment]
Closing due to this not being the correct github & it being suggested so long ago. If this is still wanted please create another issue in the correct github found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
