### ISSUE TITLE
Kawasaki Ninja H2R addition 

### ISSUE THREAD

**Issue by ristwell** [InZidiuZ/legacy-assets-issue-tracker#471]
Name:
ristwell #2179

Summary:
It’s a model of the Kawasaki Ninja H2 and H2R would love to see this in the city need better looking super bikes and more than just the R1. It’s OpenIV also :)

Link:

https://www.gta5-mods.com/vehicles/2017-kawasaki-h2-carbon-addons-tuning

Reason:
I love sport bikes and this is the fastest bestest bike of them all, it’s gorgeous and edm needs some more super bikes

**Comment by joevapes3** [comment]
A Kawasaki Ninja motorcycle already exists in the Exclusive dealership. It just has not made it into the rotation in quite some time. Keep an eye out and it should be due to hit the rotation here soon.
