### ISSUE TITLE
[imports/imports-service] Rework of Phantom+Add-ons

### ISSUE THREAD

**Issue by ChocolateNukkat** [InZidiuZ/legacy-assets-issue-tracker#473]
**Name:**
Jethro Daniels
ChocolateNukkat#5742

**Summary:**
I have found that we as truckers are only able to purchases one truck, The Phantom. While it is a good truck and everything, it is uncustomizable, and it really doesn't let you stand out from the crowd when you're on the Freeway or in the City. I also can't count how many times Trash trucks have slammed into my Rig because they think I'm a Local. All we (As truckers) want is to be able to be noticed while in traffic. Listed below is a complete rework of the Phantom, as well as some other trucks that might be able to worked into the city.

**Link:**
https://www.gta5-mods.com/vehicles/jobuilt-phantom-improved-replace-tuning

https://www.gta5-mods.com/vehicles/2012-volvo-vnl-780-truck-livery-add-on-replace

https://www.gta5-mods.com/vehicles/2016-kenworth-t680-semi-truck

https://www.gta5-mods.com/vehicles/1998-freightliner-classic-xl-add-on-replace-extras

https://www.gta5-mods.com/vehicles/scania-r730-streamline-4x2

https://www.gta5-mods.com/vehicles/mercedes-benz-actros-mp4-4x2

https://www.gta5-mods.com/vehicles/scania-r440

https://www.gta5-mods.com/vehicles/truck-camion-daf-xf-euro-6

https://www.gta5-mods.com/vehicles/gta-v-conjunto-volvo-fh-e-carreta

**Reason:**
There is only one truck to buy at the moment, and we need an update.

**Comment by Nuziatella** [comment]
Closed in favor of #531
