### ISSUE TITLE
Body armor added to EMS Store.

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/legacy-assets-issue-tracker#474]
**Name:**
superiorchicken#2703

**Summary:**
Looking to add EMS Body Armor into ems store.

**Link:**
N/A

**Reason:**
We have opened up our TECC (Tactical Emergency Critical Care) division under EMS which responds to active shooter situations with PD.  Currently we have to drive to the Mega Mall to purchase Body Armor before responding to the scene.  It will be much easier and make it quicker to respond to the scene without making an additional scene.

**Comment by Nuziatella** [comment]
This isn't the github for that. See [this](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
