### ISSUE TITLE
Anonymous Calling

### ISSUE THREAD

**Issue by Maruf2471** [InZidiuZ/legacy-assets-issue-tracker#476]
**Name:**
Who is suggesting this? Please include discord name.
Maruf#2471
**Summary:**
Write a short summary of what your suggestion is about.
If you can add Anonymous Calling system on mobile,it is like when you call someone the number will be hide Anonymous Calling
**Link:**
If there are any links to what you're suggesting, please add them here.
![DAC8F544-0D81-4AB6-B356-73F53DDCAC0D](https://user-images.githubusercontent.com/89027366/129581025-1b5d63fc-205d-4057-80f9-87b14bfa5106.jpeg)

**Reason:**
Because it can help us to do better rp and it can also helpful to us.

**Comment by Nuziatella** [comment]
Anonymously calling someone is something that you currently can do, providing you know how.

**Comment by Maruf2471** [comment]
@Nuziatella cant understand
