### ISSUE TITLE
[peds/*] Custom GSF hoodie

### ISSUE THREAD

**Issue by arnabchakr** [InZidiuZ/legacy-assets-issue-tracker#477]
**Name:**
my name is Arnab and i am suggesting this. My discord name is A R N A B#0592

**Summary:**
We have made 2 gsf hoodie for the city 

**Link:**
![jbib_diff_014_a_uni](https://user-images.githubusercontent.com/85373611/129907330-ec77c4b9-4c62-4bc2-b631-e4039bbb0423.png)

![jbib_diff_007_a_uni-Recovered](https://user-images.githubusercontent.com/85373611/129907357-b1779666-fae4-460d-96d9-48b93e5b6bac.png)

**Reason:**
we have made this hoodie because there is no extra hoodie or shirt for gsf

**Comment by DaxterPancake** [comment]
Can you please provide the specific name of the hoodie or atleast a photo? There are multiple different types of hoodies in the game and it will take me a long time to find the specific one that fits this UV unwrap.

**Comment by arnabchakr** [comment]
> Can you please provide the specific name of the hoodie or atleast a photo? There are multiple different types of hoodies in the game and it will take me a long time to find the specific one that fits this UV unwrap.

https://drive.google.com/drive/folders/1V37HLGWJWw-aAJ10oUHMnLP0M3hetU0n?usp=sharing 
this folder has every thing if u need further info please let me know

**Comment by DaxterPancake** [comment]
The black GSF hoodie has now been added, you'll have to wait for the next clothing push which doesn't have an exact time. The white hoodie was not added as we don't have enough room for it.

Cheers,
Daxter.
