### ISSUE TITLE
[peds/*] 2nd Gear Logo placed on certain clothes

### ISSUE THREAD

**Issue by stubiewonder** [InZidiuZ/legacy-assets-issue-tracker#478]
**Name:**
Stuart Beefington / stubie#O538

**Summary:**
Looking to have the 2nd Gear logo placed on a specific tshirt and hat. Along with new color options for the red suspenders in the Neck section.

**Link:**
None available

**Reason:**
Would love to have a proper uniform to enhance the RP and make things feel more immersive.

**Comment by DaxterPancake** [comment]
Can you please provide the names/a photo of the specific tshirt and hat you're wanting to have the logo on?

**Comment by stubiewonder** [comment]
i wish i had the name exactly but i can provide images and will try to get the name

**Comment by DaxterPancake** [comment]
Thank you! You can use this: https://tobii.space/

**Comment by stubiewonder** [comment]
i've checked there and can only find the shirts, can't locate the hat or suspenders. 

im also not 100% sure if these are the right shirts but they would be:

male t shirt (should be tucked in) in black - 
mp_m_freemode_01_mp_m_executive_01_jbib_017 

female t shirt (should be untucked) in black - 
mp_f_freemode_01_mp_f_heist3_jbib_013

I'll attach some pictures. Ideally would like the 2nd gear logo on the front of the shirt in the upper corner. The logo on the hat centered in the front. New color options for the current red only suspenders. I'd be happy to actually talk with you if that makes it easier. 
![shirt](https://user-images.githubusercontent.com/18708093/129991049-bb14ed70-ce04-4cfa-b1ac-1498d588548a.PNG)
![hat](https://user-images.githubusercontent.com/18708093/129991059-0807cf44-513f-4d0b-bafb-48217b105161.PNG)
![hat2](https://user-images.githubusercontent.com/18708093/129991062-1fe9f85e-689c-44ce-9227-2e0e7f55b699.PNG)
![femshirt](https://user-images.githubusercontent.com/18708093/129991070-5e73db91-66f7-4578-926c-5219f985a2e2.png)

**Comment by stubiewonder** [comment]
![Uploading second_gear_cog.png…]()

**Comment by stubiewonder** [comment]
![second_gear_cog](https://user-images.githubusercontent.com/18708093/129995802-0d5f61e3-4a67-42f8-a0cd-f3652b979698.png)

**Comment by stubiewonder** [comment]
Is there anything I can do to help push this along? The employees at 2G are dying for some sort of uniform

**Comment by DaxterPancake** [comment]
I have a list of things that need to be done, this is on the list. Either way though, once it’s done you’ll have to wait for the next clothing push which may not be for awhile. 

I’ll have a look at this later to see if I can get it done but again, that doesn’t mean it will be in the city for awhile still.

**Comment by stubiewonder** [comment]
no worries. wasn't sure what the status was on it, thank you!

**Comment by DaxterPancake** [comment]
These requests have now been done, they will not go live until the next clothing build dont by Cruxer.

Cheers,
Daxter.

**Comment by stubiewonder** [comment]
Can this be reopened?

The female shirt still has no logo. 

Suspenders were removed entirely from neck and ties category and are crucial to the outfit.

**Comment by DaxterPancake** [comment]
The changes were added to the addon section, meaning they havn't been pushed yet and may not be pushed until Cruxer is ready. Having duplicates of things is a waste of space, so the suspenders were removed from their replace to addon to allow for more colours to be added like you requested. 

Are you physically unable to deal with it until a build is done for clothing?

**Comment by stubiewonder** [comment]
No and I appreciate the updates.

I was just in the dark about why they were removed and you cleared it up. Appreciate it and thanks again
