### ISSUE TITLE
EMS Vehicles

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/legacy-assets-issue-tracker#48]
**Name:**
Duroode#2178

**Summary:**
More EMS Vehicle options to be added.

**Link:**
https://www.gta5-mods.com/vehicles/2016-ford-explorer-fpiu-qrv-saems-els
https://www.gta5-mods.com/vehicles/dodge-charger-rt-ems-for-fivem-and-sp

**Reason:**
As of the Moment EMS currently only have 3 Options for Vehicles, Which are all the same Ambulance with a different Livery. If there is a fast response needed where a patient can be transported in a car, i feel both of these would be a good idea. plus it would add some change to the overall style the EMS respond. These could be implemented so you are required to be a certain EMS rank to use them. this can be Discussed with EMS higher ups.

**Comment by Karpenkooo** [comment]
Hey,

Sorry for the slow reply. As you know we have added the Explorer for EMS and maybe in the future we will add more stuff. 

_Karpenko_

**_OP-FW Car Dev_**
