### ISSUE TITLE
[maps/?] Burger shot near Sandy Shores  🍔 

### ISSUE THREAD

**Issue by Maruf2471** [InZidiuZ/legacy-assets-issue-tracker#480]
**Name:**
Who is suggesting this? Please include discord name.
busmanl30#3931
**Summary:**
Write a short summary of what your suggestion is about.
It is very far from the city which makes it very difficult to deliver in Sandy shore and paleto bay,so if you can add a burger shot near Sandy shores it will be helpful and also helpful to do that rp 
**Link:**
If there are any links to what you're suggesting, please add them here.

https://forum.cfx.re/t/sandy-shores-burger-shot-eatery/1135847

**Reason:**
Why would your suggestion be a good addition to Legacy?
It is very far from the city which makes it very very difficult to deliver in Sandy shore and paleto bay,so if you can add a burger shot near Sandy shores it will be helpful and also helpful to do that rp .

**Comment by z-Lunar** [comment]
> **Name:**
> Who is suggesting this? Please include discord name.
> busmanl30#3931
> **Summary:**
> Write a short summary of what your suggestion is about.
> It is very far from the city which makes it very difficult to deliver in Sandy shore and paleto bay,so if you can add a burger shot near Sandy shores it will be helpful and also helpful to do that rp
> **Link:**
> If there are any links to what you're suggesting, please add them here.
> 
> https://forum.cfx.re/t/sandy-shores-burger-shot-eatery/1135847
> 
> **Reason:**
> Why would your suggestion be a good addition to Legacy?
> It is very far from the city which makes it very very difficult to deliver in Sandy shore and paleto bay,so if you can add a burger shot near Sandy shores it will be helpful and also helpful to do that rp .

I am going to look into this and possibly a custom interior for the location.
