### ISSUE TITLE
[maps/vineyard] Winery - ATM

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/legacy-assets-issue-tracker#482]
Name:
vol 5#3752 -- Bill Brook

Summary:
Currently the Vineyard has no atm. We are requesting one considering there is a large travel distance between the nearest ATM, roughly 2 mi. This would be appreciated and it would also make the experience at the vineyard more cohesive.

Link:
https://cdn.discordapp.com/attachments/876537143391051776/879953214991122492/Inked20210823033048_1_LI.jpg

Reason:
This would increase the amount of money spent at the Vineyard. The more money moving hands, the better for the economy.

**Comment by z-Lunar** [comment]
> Name:
> vol 5#3752 -- Bill Brook
> 
> Summary:
> Currently the Vineyard has no atm. We are requesting one considering there is a large travel distance between the nearest ATM, roughly 2 mi. This would be appreciated and it would also make the experience at the vineyard more cohesive.
> 
> Link:
> https://cdn.discordapp.com/attachments/876537143391051776/879953214991122492/Inked20210823033048_1_LI.jpg
> 
> Reason:
> This would increase the amount of money spent at the Vineyard. The more money moving hands, the better for the economy.

This has been resolved and included in latest Github Commit
