### ISSUE TITLE
[peds/*] Adding clothing options and faces for a local character.

### ISSUE THREAD

**Issue by VinnyPistone** [InZidiuZ/legacy-assets-issue-tracker#483]
**Name:**
Pablo_#5505

**Summary:**
The local character I'm suggesting outfits and a few masks for currently has very few outfits but I think it's possible to add several outfits and masks for the character. P.S: I will be attaching the picture of the character down below.

**Link:**
https://youtu.be/WGlIPekm1J8
https://www.youtube.com/watch?v=Pxgf8oLZheQ&ab_channel=KANKI

**Reason:**
Currently. it's not quite possible to do certain RP scenarios with the currently available outfits.

**Picture:**
![20210706091408_1](https://user-images.githubusercontent.com/89471617/130765241-677b6674-b121-4d36-ba7e-9ff2cf2d5605.jpg)

**Comment by z-Lunar** [comment]
> **Name:**
> Pablo_#5505
> 
> **Summary:**
> The local character I'm suggesting outfits and a few masks for currently has very few outfits but I think it's possible to add several outfits and masks for the character. P.S: I will be attaching the picture of the character down below.
> 
> **Link:**
> https://youtu.be/WGlIPekm1J8
> https://www.youtube.com/watch?v=Pxgf8oLZheQ&ab_channel=KANKI
> 
> **Reason:**
> Currently. it's not quite possible to do certain RP scenarios with the currently available outfits.
> 
> **Picture:**
> ![20210706091408_1](https://user-images.githubusercontent.com/89471617/130765241-677b6674-b121-4d36-ba7e-9ff2cf2d5605.jpg)

At this time we're not working with PED models & their clothing.
