### ISSUE TITLE
[peds/*] Update to LostMC Mechanic Clothing

### ISSUE THREAD

**Issue by AZTricky** [InZidiuZ/legacy-assets-issue-tracker#484]
Name: Gary Nemex (Shop Supervisor for LostMC) | Discord: AZTricky#1337

Summary: 

Link:
Current Clothing Front: https://cdn.discordapp.com/attachments/867591645083598899/880315124269875220/20210825203220_1.jpg
Current Clothing: Back: https://cdn.discordapp.com/attachments/867591645083598899/880315124269875220/20210825203220_1.jpg

Reason: LostMC Mechanic Clothing still says 2020 on it and would like to be updated to 2021. We also would like variants where the females have the dirty white shirt like the males and the males have the clean grey like the females. I can submit a new ticket but tucked in versions would also be liked as a variant of the shirts below:

Tucked in front: https://cdn.discordapp.com/attachments/867591645083598899/880315850459058196/20210825204051_1.jpg
Tucked in back: https://cdn.discordapp.com/attachments/867591645083598899/880315855672578108/20210825204615_1.jpg

**Comment by DaxterPancake** [comment]
A hoodie has been added for your mechanic shop. 
I will not be editing the shirt at this time.

Cheers,
Daxter.
