### ISSUE TITLE
[?] Addition of the Nagasaki Shotaro 

### ISSUE THREAD

**Issue by PedroTheTurtle** [InZidiuZ/legacy-assets-issue-tracker#485]
**Name:**
pedro_the_turtle#8115

**Summary:**
Addition of the Nagasaki Shotaro

**Link:**

**Reason:**
Why would your suggestion be a good addition to Legacy?
I believe that the addition of the Shotaro into the city will make a few bike enthusiasts happy. I personally have been RPing as a fan of the Tron fan in the server since the suit is already available as a clothing option in the city. The addition of the bike would help to complete the look and the Shotaro itself is an excellent bike. I understand that there may be an issue with the fact that the bike has lights on the frame; however, I feel that this would not be unrealistic because people have made modded bikes in the world that resemble that of the Shotaro. That being said I will understand if you do not wish to see such a beautiful bike in the city

**Comment by Nuziatella** [comment]
I fully support this!

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this, but I'll leave it for now since @TCruxer is the one who'd take care of it if anyone.
