### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by marcf1979** [InZidiuZ/legacy-assets-issue-tracker#486]
**Reporter:**
Marcf1979#5158

**Summary:**
bought a Merc earlier today and painted and put a spoiler on it and it saved fine when garaged. later I went to the custom shop in the Sandy area with my Merc I just purchased earlier. upgraded the lights, Armor, Transmission, engine, chassis, turbo and tint went to my house in sandy and garaged it. when I pulled it out all the upgrades were gone 21,900 worth. i'm not looking for the money back but i would like something done about the upgrades if possible. that's just a lot of money yo waste with nothing to show for it

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Nuziatella** [comment]
This isn't the github for this. Please post this bug [here.](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
