### ISSUE TITLE
[maps/dispensary] Swap the location of the ATM and the water jug

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/legacy-assets-issue-tracker#489]
**Name:**
Who is suggesting this? Please include discord name.
o0ochanceo0o#5735

Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes

Summary:
Write a summary of what your suggestion is about.
Green Wonderland is Los Santos' only legal recreational and medical marijuana dispensary. We have been open since April 2021 and would like to swap the location of the ATM and the water jug.

Reason:
Why would your suggestion be a good change to the framework?
People in the store often end up buying a snack instead of using the ATM because of the close proximity of the ATM and the vending machine.

**Comment by XwezioGH** [comment]
Due to lack of room I've separated the vending machine and atm as much as possible if you're still facing issues please remake ticket.

I will close this now.

Xwezio
Asset Team
