### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/legacy-assets-issue-tracker#49]
Reporter:
Lars. #9309

Summary:
I own a Mercedes CLS AMG, i installed a Turbo, Race Trans and Engine level 4.
I feel like the topspeed is bugged out, it doesn't go quicker then 160, even when going downhill.
Topspeed didn't increase after installing the upgrades. The car actually starts to slow down in the last gear.

Additional Information
Screenshots:
https://i.imgur.com/CZDbVAS.png

Notes:
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

This issue has been fixed since the last update! Sorry for the long wait.

_Karpenko_

_**OP-FW Asset Dev**_
