### ISSUE TITLE
[peds/*] SOL:SA Repairs Mechanic Tshirt Change

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#490]
**Name:**
AdeptCL#0402

**Summary:**
Switching up/changing the SOL:SA Repairs mechanic tshirt.

**Link:**
Currently none.

**Reason:**
The current SOL:SA Repairs mechanic tshirt currently uses the old patch (and top/bottom rockers).
I'd like to have the black top remain, but the design/prints on the tshirt to be changed. I'm open for design suggestions on this, however if you'd prefer us reach out to someone to make one, just let me know.

**Comment by DaxterPancake** [comment]
You're welcome to reach out to me with your ideas of what you want, or put them on here. 

As for the logo that is on the shirts, I will be unable to create these for you, so you'd have to source them or I can just try and use your newer patch.

**Comment by Sinister-Neonfire** [comment]
I had it pointed out to me that the shirt has the 1% badge on it currently. That shouldn't really be there, as mechanics aren't necessarily 1%ers.

**Comment by AdeptCL** [comment]
I'm going to hopefully work up some design rough drafts, and maybe we can certainly look into it. 
I will send them over to you @DaxterPancake, and I'm sure you'll be able to shut me down if the design is too much to do, or if it's okay.

**Comment by roboZcop** [comment]
anyupdate on this?

**Comment by AdeptCL** [comment]
> any update on this?

Not yet. I’m yet to be happy with a design of a tshirt I want to push. So Daxter hasn’t received anything from me.

**Comment by MetaHatter** [comment]
@AdeptCL Is this still needed?

**Comment by DaxterPancake** [comment]
Closing as this has been done with updated T-Shirts.
