### ISSUE TITLE
[maps/gta] Custom ESB graffiti art work added to grove st.

### ISSUE THREAD

**Issue by Lohtx** [InZidiuZ/legacy-assets-issue-tracker#491]
**Name:**
fuckyoupayme#8624

**Summary:**
We would like custom ESB graffiti art work added to grove st. 

**Link:**

![](https://cdn.discordapp.com/attachments/874249395162456104/882972658373910548/image0.jpg)

![](https://cdn.discordapp.com/attachments/874249395162456104/882973123312484362/unknown.png)

![](https://cdn.discordapp.com/attachments/874249395162456104/882975603840663592/427675926490.png)

**Reason:**
I believe it would be a good addition to the story line of ESB since we have officially bought the block.

**Comment by antihero6713** [comment]
do not exist anymore closing open up again if it is still wanted
