### ISSUE TITLE
[imports/civilian_*] BMW i8 currently doesn't have a physical trunk

### ISSUE THREAD

**Issue by MVirk22** [InZidiuZ/legacy-assets-issue-tracker#492]
**Reporter:**
M_Virk#2059

**Summary:**
The BMW i8 currently doesn't have a physical trunk in which people can get in. I am reporting it as a bug as it always used to have a trunk but it was either removed or it's just bugged where you can't enter in it anymore. This is a huge detriment to the car as being able to put injured people in a car is a vital gameplay mechanic and also BMW i8 is also a car that does realistically have a sizable trunk. I would really appreciate it if this feature would be added back to the car or fixed. 

## Additional Information
This is more of a suggestion but since it's about the same car, I would also like to add that the realistically the bmw i8 is a 4 seater car and putting that in the game would bring it a lot closer to its real life counter-part.
**Screenshots:**
![i8 seats](https://user-images.githubusercontent.com/88728561/132106044-f53ca89c-6200-42ce-820e-20bbe4a14d1a.jpeg)

**Comment by Nuziatella** [comment]
This is a model lock issue. It's being addressed though it may not be something that can be fixed
