### ISSUE TITLE
[imports/ems] New emergency vehicles for EMS

### ISSUE THREAD

**Issue by ROXGGG** [InZidiuZ/legacy-assets-issue-tracker#493]
**Name:**
ROX GG
! 𝙍̶𝙊̶𝙓̶ ̶𝙂̶𝙂̶#4752

**Summary:**
A few more cars at the EMS Department would actually be good for the department. Because if you go to a higher rank in the department, you have to change the livery and use that one car. We all have high hopes that if we get a promotion, we will get a new car and the rank will be high and also the salary will increase. Aside from being high in rank, many of our responsibilities will increase. The new car will actually make our roleplay easier and more beautiful. And these cars will actually have a lot more benefits in bringing a very quick call a response and patient. For those who can't use helicopters in the department, all these cars will be much more comfortable and convenient.

**Link:**
Dodge Charger RT EMS
https://www.gta5-mods.com/vehicles/dodge-charger-rt-ems-for-fivem-and-sp
Tahoe
https://www.gta5-mods.com/vehicles/2020-fire-command-tahoe
Volvo XC90 R
https://www.gta5-mods.com/vehicles/2017-volvo-xc90-r-design-replace-els
![0b1cf1-GTA5%202018-07-18%2017-59-35-080](https://user-images.githubusercontent.com/90183457/132196780-dd76fbe8-44d7-41d8-81c4-4dc9475988fb.jpg)
![145f51-Screenshot_1323](https://user-images.githubusercontent.com/90183457/132196787-f5591a95-dcf1-46b4-b178-82f3e03c6ff5.png)
![images](https://user-images.githubusercontent.com/90183457/132196788-4a0f5780-8811-4ce8-ab18-8a18d862b0e9.jpeg)

**Reason:**
It will make a differences between other servers EMS RP. Another reason is that the new car will actually arouse people's interest in the job.

**Comment by AdeptCL** [comment]
I had a character who used to be a part of the Emergency Medical Services. However, I do not believe EMS need even more vehicles.
There is a wide variety as it is, from trucks/ambulances/bikes/helis. Adding more just uses up more server resources, when they could be used for something else.

**Comment by Nuziatella** [comment]
How would these vehicles exactly improve roleplay? 
What functions do they offer that the current vehicles do not?

All 3 suggested vehicles are of low quality compared to the ones being offered and are poorly optimized. Jobs like EMS are not that different from PD. Each vehicle has it's use cases and just to clarify it isn't that we are against adding new vehicles for EMS. We would add them if they provide some type of significant function for roleplay that the current vehicles do not offer.  The simple, "I get a promotion so I get a new vehicle that doesn't enable me to transport downed individuals, which is the core function of my job.", doesn't provide a logical reason for adding any of these vehicles.

**Comment by ROXGGG** [comment]
> How would these vehicles exactly improve roleplay?
> What functions do they offer that the current vehicles do not?
> 
> All 3 suggested vehicles are of low quality compared to the ones being offered and are poorly optimized. Jobs like EMS are not that different from PD. Each vehicle has it's use cases and just to clarify it isn't that we are against adding new vehicles for EMS. We would add them if they provide some type of significant function for roleplay that the current vehicles do not offer. The simple, "I get a promotion so I get a new vehicle that doesn't enable me to transport downed individuals, which is the core function of my job.", doesn't provide a logical reason for adding any of these vehicles.

Why would your suggestion be a good change to the framework?
It's been almost a year, that I'm doing EMS. Though our devs working really hard to bring the best RP server to us and I also appreciate that. Though it's been a long time, the new emergency vehicles given to EMS Department(though it was).
As I'm doing EMS RP in one of the subdivisions of Legacy RP. As in our subdivision/community(Bangladesh), we have like 12 ranks in our department. And it's being really hard to divide all these few vehicles (not really few but somehow) among these ranks

**Comment by AdeptCL** [comment]
> > How would these vehicles exactly improve roleplay?
> > What functions do they offer that the current vehicles do not?
> > All 3 suggested vehicles are of low quality compared to the ones being offered and are poorly optimized. Jobs like EMS are not that different from PD. Each vehicle has it's use cases and just to clarify it isn't that we are against adding new vehicles for EMS. We would add them if they provide some type of significant function for roleplay that the current vehicles do not offer. The simple, "I get a promotion so I get a new vehicle that doesn't enable me to transport downed individuals, which is the core function of my job.", doesn't provide a logical reason for adding any of these vehicles.
> 
> It's been almost a year, that I'm doing EMS. Though our devs working really hard to bring the best RP server to us and I also appreciate that. Though it's been a long time, the new emergency vehicles given to EMS Department(though it was).
> As I'm doing EMS RP in one of the subdivisions of Legacy RP. As in our subdivision/community(Bangladesh), we have like 12 ranks in our department. And it's being really hard to divide all these few vehicles (not really few but somehow) among these ranks

You have just confirmed what Nuzi already stated:
"_The simple, "I get a promotion so I get a new vehicle that doesn't enable me to transport downed individuals, which is the core function of my job.", doesn't provide a logical reason for adding any of these vehicles._"

**Comment by joevapes3** [comment]
For now it seems this issue isn't going to be considered. At some point here in the future I imagine it will be revisited, until then I am closing the suggestion out and if you provide some more points to bring in new EMS vehicles that are an improvement for what we have now, then we can review it at that time.
