### ISSUE TITLE
[imports/civilian_*] Adding additional drift cars to the city

### ISSUE THREAD

**Issue by definitelynothim** [InZidiuZ/legacy-assets-issue-tracker#494]
**Name:**
Me.
Baba#9198

**Summary:**

Adding in a few cars/chassis and/or LSC upgrades for the purposes of starting a drift scene in the city (additionally and not replacing the existing racing scene).

1. Can just have the same characteristics as the existing twin turbo truck (drift yosemite) that just spins through all the gears or the drift tampa.
2. Unless there's some way to lock a car to a certain gear so that it won't keep up shifting automatically, so that you can use existing cars.
3. Can also open up a batch of PDM/EDM cars that have a "drift spec" upgrade to them available (this makes them perform just like the drift truck). This way, you can swap back and forth between how the car feels in case you wanted to use it to race instead.

Whichever one of these 3 ways achieves the goal the quickest/easiest for you. The "drift spec" upgrade at los santos customs is probably the most efficient/coolest way to go about it so you don't have to have an entirely different set of cars just to drift with clogging things up.

**Link:**
n/a

**Reason:**
Would be fun to host events with these cars. Really easy to have a lot of spectators.

**Side note**
I've been learning web development for about a year now and I've also been in the drifting scene IRL for 6ish years, so it would be great if I could talk to or work with the dev assigned. If not, that's cool too.

**Comment by Nuziatella** [comment]
I'll take a look and see what we can come up with

**Comment by kswagz** [comment]
> I'll take a look and see what we can come up with

Thank you!

If it helps, I just found out last night that the EDM Toyota Chaser also has the same drift tune as well and feels the best out of the 3 to base off of. I'd edit the OP but I'll leave it here for viability sake 👍

**Comment by z-Lunar** [comment]
> **Name:**
> Me.
> Baba#9198
> 
> **Summary:**
> 
> Adding in a few cars/chassis and/or LSC upgrades for the purposes of starting a drift scene in the city (additionally and not replacing the existing racing scene).
> 
> 1. Can just have the same characteristics as the existing twin turbo truck (drift yosemite) that just spins through all the gears or the drift tampa.
> 2. Unless there's some way to lock a car to a certain gear so that it won't keep up shifting automatically, so that you can use existing cars.
> 3. Can also open up a batch of PDM/EDM cars that have a "drift spec" upgrade to them available (this makes them perform just like the drift truck). This way, you can swap back and forth between how the car feels in case you wanted to use it to race instead.
> 
> Whichever one of these 3 ways achieves the goal the quickest/easiest for you. The "drift spec" upgrade at los santos customs is probably the most efficient/coolest way to go about it so you don't have to have an entirely different set of cars just to drift with clogging things up.
> 
> **Link:**
> n/a
> 
> **Reason:**
> Would be fun to host events with these cars. Really easy to have a lot of spectators.
> 
> **Side note**
> I've been learning web development for about a year now and I've also been in the drifting scene IRL for 6ish years, so it would be great if I could talk to or work with the dev assigned. If not, that's cool too.

Would compliment this interior. [https://www.youtube.com/watch?v=s8e6U0yNHcI&t=59s](url)

**Comment by joevapes3** [comment]
@z-Lunar I agree it would be cool to see a drift scene in the city, however even with the amount of drift cars there is currently in vanilla assets, and exclusive, nobody utilizes them existing for such activities. I feel like the amount of additional asset resources would be catering more to a niche group of individuals and not as much to the legacy community as a whole. If I seen people utilizing the existing assets in such a manor then I'd be more inclined to add them in the future. Either way I think at some point we could add a few more drift assets but I don't see that boosting the lack of interest that there already is now sadly. Even though I personally think it would be cool to see.

**Comment by joevapes3** [comment]
I think another alternative would be to convert a few more vanilla assets into drift vehicles and see if people actually start to utilize them in such a manor, and if that does happen then consider adding more exclusive drift assets in the future.

**Comment by kswagz** [comment]
> 
> 
> @z-Lunar I agree it would be cool to see a drift scene in the city, however even with the amount of drift cars there is currently in vanilla assets, and exclusive, nobody utilizes them existing for such activities. I feel like the amount of additional asset resources would be catering more to a niche group of individuals and not as much to the legacy community as a whole. If I seen people utilizing the existing assets in such a manor then I'd be more inclined to add them in the future. Either way I think at some point we could add a few more drift assets but I don't see that boosting the lack of interest that there already is now sadly. Even though I personally think it would be cool to see.

You're absolutely right. I wasn't looking for additional asset resources here though. Just asking for existing assets to be "converted" over. Or a "drift tune" added to such vehicles in los santos customs. For example, the existing 180sx from EDM is a good candidate, the elegy from PDM, silvia s15 from EDM. A few others but that's already a decent selection without diving in. Just looking for additional chassis so we don't see the same 10 Toyota Chasers running the events to be had.

I found someone with a Chaser and the Drift truck at a car meet last night and we just had a drift test sorta thing to see if this was viable. Without even advertising anything, we had every car filled with passengers and others hanging out. Drifting is for sure niche and unknown but it's really fun once people get to experience it and watch. I can imagine we'd have a lot of the city coming to watch events held maybe once a week or once every other.

The street racing scene gets plenty of attention and you can't even spectate that. I think this is a great addition.

Here's a few clips I threw together of the test sesh. https://www.youtube.com/watch?v=VJhXfVgHkrI

**Comment by SirPiff** [comment]
There is a way this could be done without adding more assets and without having to change cars into drift cars.

Although this would probably make this more or a script suggestion; adding a /driftmode that puts the car into a toggled state of being able to drift, this would let any car you'd want to drift without adding/modifying current assets. c:

**Comment by Nuziatella** [comment]
The issue with that is not all cars can use the same handling.meta settings because of model differences and how it affects the algorithms. I have a generic drift tune that can be used which could work for most cars. I'll do some testing and see what I can come up with

**Comment by SirPiff** [comment]
Maybe attempting to rewrite this script into a toggle could work?
https://github.com/MoravianLion/Drift-Script
Seems to do a decent bit of maths for it too.

**Comment by Nuziatella** [comment]
Once the tuning chip script is re-written it'll include a "drift mode" toggle.
