### ISSUE TITLE
[peds/?] Adding New Guitar: Telecaster

### ISSUE THREAD

**Issue by Mobellium** [InZidiuZ/legacy-assets-issue-tracker#497]
I've noticed that we have some cool guitars but I think this would be another great one for the collection. 

Preview - https://sebdur.github.io/telecaster/

https://github.com/sebdur/telecaster

**Comment by InZidiuZ** [comment]
Is this a suggestion to add a furniture item, or what are you suggesting it for?

**Comment by Mobellium** [comment]
I was hoping for an emote of playing this guitar.

**Comment by DaxterPancake** [comment]
Closing as this is not needed at this time.
