### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BrodieF1** [InZidiuZ/legacy-assets-issue-tracker#498]
Brodie#3246

i think there should be boats , like a doc near scuba where people can buy a boat and take it over and can store their stuff in it and  return it when they are done with it they just take the boat over and store it

i just think it would be a cool addition and it would save time for people to use the boat instead of swimming out , it would be cool to get boats with better storage as the price gets higher

**Comment by DaxterPancake** [comment]
Thank you for your suggestion! A boat store is already suggested here and is already suggested on the script github so I will be closing this in favour of #432. 

Cheers,
Daxter.
