### ISSUE TITLE
[maps/japanese_restaurant] Kissaki Sushi addtions

### ISSUE THREAD

**Issue by bossace** [InZidiuZ/legacy-assets-issue-tracker#499]
**Name:**
Arty Sanders, Owner of Kissaki Sushi, Bossace#7764

**Summary:**
To add additions to Kissaki Sushi in order to be able to enhance experiences, serve food, and hold events with actually things to sell and serve.

https://media.discordapp.net/attachments/885756412842622977/885762228865871922/GPS.png

Sushi Roll logo on map for gps purposes: 

Our logo on the “smells like a bitch” billboard and “Gusset” Billboard on both sides of the restaurant so we have our name and not have to cover the Japanese characters on the building.

https://cdn.discordapp.com/attachments/885756412842622977/885762228865871922/GPS.png

Logo:

https://cdn.discordapp.com/attachments/885756412842622977/885759370422534144/Kissaki_Sushi-04.jpg

https://cdn.discordapp.com/attachments/885756412842622977/885759730419646524/Kissaki_Sushi-04.png

Location:

https://media.discordapp.net/attachments/885756412842622977/885757650539806741/Gusset_Billboard.png

https://media.discordapp.net/attachments/885756412842622977/885757664695570482/Smell_like_a_bitch.png

A role so employees can have keys and ideally paychecks with roles like Owner, managers, servers, etc.

Locks for all exterior doors and garage, also kitchen, employee room, and office door.

https://media.discordapp.net/attachments/885756412842622977/885756515032637440/Front_three_doors_together.png

https://media.discordapp.net/attachments/885756412842622977/885756917727776768/Side_exterior_door.jpg

https://media.discordapp.net/attachments/885756412842622977/885757593346248775/2nd_floor_exterior_door.png

https://media.discordapp.net/attachments/885756412842622977/885757150436143234/Garage_door.png

https://media.discordapp.net/attachments/885756412842622977/885757013135614002/Kitchen_and_Employee_room_doors.png

https://cdn.discordapp.com/attachments/885756412842622977/885758810369691668/Manager_office_2nd_floor.jpg

Lockers for employees to store items as well as clothes changing station by locker room so staff can change clothes

https://media.discordapp.net/attachments/885756412842622977/885757799487897650/Changing_room_and_locker.png?width=1040&height=443

To ensure customers have to interact with staff have the places to buy food and drinks in the kitchen so people can’t just run in and buy it.

https://media.discordapp.net/attachments/885756412842622977/885757737936519198/Kitchen.png

Custom drinks like Sake, Shochu, Tea, Plum wine, Highball, Chuhai. These could optionally include perks like being drunk effects on the screen or even fill up your thirst.

Custom foods like multiple different sushi rolls (California roll, spicy tuna roll, dragon roll, rainbow roll, spider roll, and the shrimp tempura roll), edamame, ramen. The sushi rolls could have possible effects like swim faster, hold breath longer, etc. Ramen could fill you up even more, edamame as an appetizer could fill you up less.

**Link:**
Links in summary

**Reason:**
To enhance and add to the restaurant rp. Not to have other traditional desserts or typical beer drinks so we can work with other businesses to buy from them as a supplier and say we have beer from draft from other businesses to side promote them as well as other desserts.

**Comment by AdeptCL** [comment]
I really like this idea, and I do believe more "miscellaneous" items should be added in general. 
At this Japanese restaurant, I would love to see some items available such as:
- Avocado/Cucumber/Salmon Maki
- Dragon Roll
- California Roll
- Yasai Roll
- California/Salmon/Yasai Temaki
- Salmon Nigiri

There are also alternative meals which would be a good addition to this restaurant too:
- Beef Teriyaki Bowl
- Chicken/Mushroom/Seafood Ramen Bowl
- Katsu Bowl

They don't necessarily need to have special effects to them, but if they did that would be an extra creative side to them. 
Overall, adding some creative items to current businesses that make them unique even more by being able to provide an actual item can and will only benefit the roleplay.

**Comment by DaxterPancake** [comment]
I'd like to see these additions mix with the fishing and cooking script also. We sell fish to you (aswell as to a local store), so that you can make stock for your store.

**Comment by AdeptCL** [comment]
> I'd like to see these additions mix with the fishing and cooking script also. We sell fish to you (aswell as to a local store), so that you can make stock for your store.

Similar format to how the mechanic job works. Have the ability to turn "fish" or "tuna"/"haddock"/"**SHARK**" into sushi rolls.

**Comment by claymstehling** [comment]
I love this. I agree with @DaxterPancake in that this would be an amazing opportunity  for the fishing and cooking script to be worked in. 

I think overall though this idea is amazing and would really benefit legacy in a lot of different ways

**Comment by z-Lunar** [comment]
> **Name:**
> Arty Sanders, Owner of Kissaki Sushi, Bossace#7764
> 
> **Summary:**
> To add additions to Kissaki Sushi in order to be able to enhance experiences, serve food, and hold events with actually things to sell and serve.
> 
> https://media.discordapp.net/attachments/885756412842622977/885762228865871922/GPS.png
> 
> Sushi Roll logo on map for gps purposes:
> 
> Our logo on the “smells like a bitch” billboard and “Gusset” Billboard on both sides of the restaurant so we have our name and not have to cover the Japanese characters on the building.
> 
> https://cdn.discordapp.com/attachments/885756412842622977/885762228865871922/GPS.png
> 
> Logo:
> 
> https://cdn.discordapp.com/attachments/885756412842622977/885759370422534144/Kissaki_Sushi-04.jpg
> 
> https://cdn.discordapp.com/attachments/885756412842622977/885759730419646524/Kissaki_Sushi-04.png
> 
> Location:
> 
> https://media.discordapp.net/attachments/885756412842622977/885757650539806741/Gusset_Billboard.png
> 
> https://media.discordapp.net/attachments/885756412842622977/885757664695570482/Smell_like_a_bitch.png
> 
> A role so employees can have keys and ideally paychecks with roles like Owner, managers, servers, etc.
> 
> Locks for all exterior doors and garage, also kitchen, employee room, and office door.
> 
> https://media.discordapp.net/attachments/885756412842622977/885756515032637440/Front_three_doors_together.png
> 
> https://media.discordapp.net/attachments/885756412842622977/885756917727776768/Side_exterior_door.jpg
> 
> https://media.discordapp.net/attachments/885756412842622977/885757593346248775/2nd_floor_exterior_door.png
> 
> https://media.discordapp.net/attachments/885756412842622977/885757150436143234/Garage_door.png
> 
> https://media.discordapp.net/attachments/885756412842622977/885757013135614002/Kitchen_and_Employee_room_doors.png
> 
> https://cdn.discordapp.com/attachments/885756412842622977/885758810369691668/Manager_office_2nd_floor.jpg
> 
> Lockers for employees to store items as well as clothes changing station by locker room so staff can change clothes
> 
> https://media.discordapp.net/attachments/885756412842622977/885757799487897650/Changing_room_and_locker.png?width=1040&height=443
> 
> To ensure customers have to interact with staff have the places to buy food and drinks in the kitchen so people can’t just run in and buy it.
> 
> https://media.discordapp.net/attachments/885756412842622977/885757737936519198/Kitchen.png
> 
> Custom drinks like Sake, Shochu, Tea, Plum wine, Highball, Chuhai. These could optionally include perks like being drunk effects on the screen or even fill up your thirst.
> 
> Custom foods like multiple different sushi rolls (California roll, spicy tuna roll, dragon roll, rainbow roll, spider roll, and the shrimp tempura roll), edamame, ramen. The sushi rolls could have possible effects like swim faster, hold breath longer, etc. Ramen could fill you up even more, edamame as an appetizer could fill you up less.
> 
> **Link:**
> Links in summary
> 
> **Reason:**
> To enhance and add to the restaurant rp. Not to have other traditional desserts or typical beer drinks so we can work with other businesses to buy from them as a supplier and say we have beer from draft from other businesses to side promote them as well as other desserts.

Logos have been updated.

Anything related to **Jobs, Keys, Door Locks, & Food/Items** need to be requested on the [OP-FW Github](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
