### ISSUE TITLE
Repossesions

### ISSUE THREAD

**Issue by DevotionRL** [InZidiuZ/legacy-assets-issue-tracker#5]
**Name:**
Devotion#5277

**Summary:**
with unpaid car finances having the option for higher up dealers to repossess the cars and sell them at cut prices to recoup money for them. for instance say a 40k car was financed and only 1 week was ever paid, repossess the vehicle and advertise for sale including the mods for 30k or around that. someone gets a good deal on the vehicle and the dealership gets the car paid off in other means.

**Reason:**
its realistic and gives players the chance to buy pre-modified cars from a trusted seller at reduced costs.

**Comment by InZidiuZ** [comment]
Hey,

Closing as you posted this at the wrong GitHub page, this one is for assets and strictly that, not scripting-related server suggestions.

**InZidiuZ**
*OP-FW Developer*
