### ISSUE TITLE
Small fixes for Vapid Dominator GTX

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/legacy-assets-issue-tracker#50]
**Name:**
Randy James #4851

**Summary:**
Karpenko could we get a small fix on the sliding. Its a dominator sure its suppose to slide but it gets so out of control which brings me to the next issue brakes suck at high speed it takes a good while to fully brake when going high speed. Irl it has very good brakes just little buff. Also the top speed is 174 just put it abit higher i would be more than happy with 180.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
It just fits the car very well to have good brakes and have less sliding.

**Comment by dentalcarefraud** [comment]
As someone who also owns a Dominator GTX, I can second everything Randy has said here. The brakes are hard to work with, it slides alot and does not take bumps well at all.

**Comment by psyCOSMO** [comment]
Drive slower

**Comment by Karpenkooo** [comment]
Hey,

I'll make some slight adjustments but nothing major.

_Karpenko_

_**OP-FW Asset Dev**_
