### ISSUE TITLE
Bean Machine upgrades. 

### ISSUE THREAD

**Issue by Brookiedoughh** [InZidiuZ/legacy-assets-issue-tracker#501]
**Brook Shell *Andrea Higgins**
The owner of Bean Machine.  Brookiedoughh#3833

**Summary:**
We would like the location of the "item spawner" to be moved back behind the counter/bar instead of in front of the counter, or even in the employee break room, if possible. Additionally, we would like to have our Bean Machine Logo added to liveries for the Rampo van. 

**Link:**
If there are any links to what you're suggesting, please add them here. N/A

**Reason:**
Why would your suggestion be a good addition to Legacy? Adding these features would provide more business to Bean Machine. We have had issues in the past where customers ignore working baristas and buy items themselves, even after trying to get their attention. If the inventory is moved out of direct sight from the customers this will increase my employees sales benefiting them. 
Lastly, having our logo (attached below) added to liveries for the Rampo van will help Bean Machine with additional advertising and more commission for my employees. My plan is to be able to set up "food trunk/van" at popular locations around the city. 
Both of these additions will increase the level of RP in the city. Either it being in Bean Machine itself or throughout the city. 

Thank you!

![beanmachinecomplete](https://user-images.githubusercontent.com/90653590/133159791-3394e3cb-6e77-4069-82db-4f22c96ad073.png)

**Comment by z-Lunar** [comment]
> *_Brook Shell _Andrea Higgins__
> The owner of Bean Machine. Brookiedoughh#3833
> 
> **Summary:**
> We would like the location of the "item spawner" to be moved back behind the counter/bar instead of in front of the counter, or even in the employee break room, if possible. Additionally, we would like to have our Bean Machine Logo added to liveries for the Rampo van.
> 
> **Link:**
> If there are any links to what you're suggesting, please add them here. N/A
> 
> **Reason:**
> Why would your suggestion be a good addition to Legacy? Adding these features would provide more business to Bean Machine. We have had issues in the past where customers ignore working baristas and buy items themselves, even after trying to get their attention. If the inventory is moved out of direct sight from the customers this will increase my employees sales benefiting them.
> Lastly, having our logo (attached below) added to liveries for the Rampo van will help Bean Machine with additional advertising and more commission for my employees. My plan is to be able to set up "food trunk/van" at popular locations around the city.
> Both of these additions will increase the level of RP in the city. Either it being in Bean Machine itself or throughout the city.
> 
> Thank you!
> 
> ![beanmachinecomplete](https://user-images.githubusercontent.com/90653590/133159791-3394e3cb-6e77-4069-82db-4f22c96ad073.png)

Github requests regarding Framework changes are to be posted in the [OP-FW Github](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)

As far as the Logo goes, I will pass the word onto the Vehicle Developers in regards to implementing a Bean Machine Livery on the Import Van (Similar to Midnight & Premium Deluxe Motorsports)
