### ISSUE TITLE
Harmony Repair Changes

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/legacy-assets-issue-tracker#502]
**Name:**

ItzBrittanyBitxh#8587

**Summary:**

We would love to make some overall improvements to 'Harmony Repair' which is based on route 68. Below is a few changes that could be awesome for the quality of life at the shop in RP!

1. Editing the interior to remove the car wash from inside, and add a second repair bay eg: https://imgur.com/a/QaGj9MG
3. Adding the hand carwash outside somewhere, possibly between the two bay doors.
4. Adding a couple of vending machines somewhere on the property.

**Reason:**

It has recently opened on main server and we are going to give a decent shot, bringing more people to the harmony area in general, with the ability to experience new places and a fresh location!

**Comment by z-Lunar** [comment]
> **Name:**
> 
> ItzBrittanyBitxh#8587
> 
> **Summary:**
> 
> We would love to make some overall improvements to 'Harmony Repair' which is based on route 68. Below is a few changes that could be awesome for the quality of life at the shop in RP!
> 
> 1. Editing the interior to remove the car wash from inside, and add a second repair bay eg: https://imgur.com/a/QaGj9MG
> 2. Adding the hand carwash outside somewhere, possibly between the two bay doors.
> 3. Adding a couple of vending machines somewhere on the property.
> 
> **Reason:**
> 
> It has recently opened on main server and we are going to give a decent shot, bringing more people to the harmony area in general, with the ability to experience new places and a fresh location!

Harmony Customs, Including Lost MC & Paleto have been altered to Gabz updated interior, **Including 2** carwashes inside for each bay & ATM.
