### ISSUE TITLE
[maps/burgershot] BurgerShot Improvements 

### ISSUE THREAD

**Issue by Infamously1** [InZidiuZ/legacy-assets-issue-tracker#503]
.

**Comment by Nuziatella** [comment]
The map guys will take a look at your suggestions.

**Comment by Infamously1** [comment]
Hey, my Github account got flagged for spam for some reason, you guys should be able to see this now I think. I have another one in the framework section but it got pushed to the bottom because it was "hidden" should I repost it?

**Comment by Infamously1** [comment]
https://gnmods.com/products/burgershot

This was recently released, I feel it would be a good new interior as stated above

**Comment by z-Lunar** [comment]
> https://gnmods.com/products/burgershot
> 
> This was recently released, I feel it would be a good new interior as stated above

If you're willing to supply the resource, we can work something out.

**Comment by Maruf2471** [comment]
And there should be delivery options available,if it is like ufc the it will not gone a help
