### ISSUE TITLE
Suggestion SASP police clothes

### ISSUE THREAD

**Issue by bloo5799** [InZidiuZ/legacy-assets-issue-tracker#506]
**Name:**
Barnacle#5187

**Summary:**
(Clothing Addon) Great SASP uniforms with the correct badge and everything. with this added, the PD will be able to properly dress with correct badges, and dress with color or all black. here are the best EUP outfits i could find that seem to match the department.

**Link:**
https://www.lcpdfr.com/downloads/gta5mods/character/36391-sasp-eup-pack/

https://www.lcpdfr.com/downloads/gta5mods/character/25000-san-andreas-state-police-eup-compatible-with-eup-81-only/

https://www.lcpdfr.com/downloads/gta5mods/character/36222-san-andreas-state-police-eup-82-current-green-mtn-development/

**Reason:**
Currently there are alot of LSPD uniforms but not many SASP uniforms. this should allow for better branding of the SASP, and they match the cars and badge.

**Comment by DaxterPancake** [comment]
New SASP uniforms are already being added, created by one of our developers. 

Cheers for your suggestions though.

Daxter,
Project Manager
