### ISSUE TITLE
🍔 Increase Burger delivery money 

### ISSUE THREAD

**Issue by Maruf2471** [InZidiuZ/legacy-assets-issue-tracker#507]
**Name:**
Who is suggesting this? Please include discord name.
Máruf#1528
**Summary:**
Write a short summary of what your suggestion is about.

When the burger shot started the delivery mony is decent like in city deliverys 550-650$ but after sometime the burger delivery mony decries like in city delivery’s 250-350 $ for that we have to do more burger delivery then before it effect on rp,if the burger delivery mony will increase like before pepople will do more rp and less delivery and also people will excited about doing this job / rp  .

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
When the burger shot started the delivery mony is decent like in city deliverys 550-650$ but after sometime the burger delivery mony decries like in city delivery’s 250-350 $ for that we have to do more burger delivery then before it effect on rp,if the burger delivery mony will increase like before pepople will do more rp and less delivery and also people will excited about doing this job / rp  .

**Comment by Masik52** [comment]
The reason the money was decreased was because people would spend all day grinding deliveries and make stupid amounts of money

**Comment by DaxterPancake** [comment]
More money was not making people RP more. It was making people grind and make stupid amounts of money.

The pay will not be increased. 

Cheers,
Daxter.
Project Manager.

**Comment by Maruf2471** [comment]
> The reason the money was decreased was because people would spend all day grinding deliveries and make stupid amounts of money

The thing is now there is a limit 20-30 etc

**Comment by Maruf2471** [comment]
@DaxterPancake if you have money you don’t have grind too much that mean you can concentrate on rp that’s think
