### ISSUE TITLE
[peds/*] Some interesting clothes

### ISSUE THREAD

**Issue by Enryy** [InZidiuZ/legacy-assets-issue-tracker#508]
**Name:**
Enryy Guevara#0185

**Summary:**
some interesting clothes

**Link:**

https://forum.cfx.re/t/paid-250-tshirt-textures/4765794

https://it.gta5-mods.com/player/nike-af1-off-white

https://it.gta5-mods.com/player/clot-x-nike-af1-1world

https://www.gta5-mods.com/player/alexander-mcqueen-for-mp

https://it.gta5-mods.com/player/pullover-hoodie-pack-sp-fivem

https://it.gta5-mods.com/player/pullover-hoodie-for-mpmale

**Comment by DaxterPancake** [comment]
These have been look at and considered for the upcoming clothing update, thank you!
