### ISSUE TITLE
[imports/police] Police Bike Buff

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/legacy-assets-issue-tracker#509]
**Name:**
Who is suggesting this? Please include discord name.
Tanzim#6969

**Summary:**
Write a short summary of what your suggestion is about.
I think the police bike needs to be buffed. Normal bikes can do wheelies and turn very easily. We don't have any offroad bikes. So we have to use the same bike on-road and offroad. Off-road bikes like Sanchez, Dinka TT these bikes can do wheelies very easily and can make hard turns. On the other hand, it's very hard to do a wheelie and turning in a police bike. It makes police bikes very unfair. So I think the police bike needs to be buffed.

**Link:**
If there are any links to what you're suggesting, please add them here.
No

**Reason:**
Why would your suggestion be a good addition to Legacy?
This would make police bike chase fair and easier to control police bikes, gain speed, make turns, etc.

**Comment by Maruf2471** [comment]
Police bike is already op dinka and other bike can’t go to high speed like police bikes,if police bikes are going to buff then normal bike also need buff because there not op like police bikes and cars

**Comment by T4NZ1M** [comment]
> @T4NZ1M Police bike is already op dinka and other bike can’t go to high speed like police bikes,if police bikes are going to buff then normal bike also need buff because there not op like police bikes and cars

Are you police in any server? ever used police bike in any chase? If I'm not wrong, are play in the same subdivision as mine and there in jewelery you can't even use bike, why? because police bike have some issues. So if you don't have any idea about this then please ignore it, Thanks

**Comment by Maruf2471** [comment]
@T4NZ1M yea I am a police on legacy subdivision but if it is only problem in your subdivision then use bug and ideas this suggestion is for all op fw aka full legacy, and I already use the bike also I think this bike is ok and if can’t even use the bike in jewellery the it’s your problem

**Comment by T4NZ1M** [comment]
> @T4NZ1M yea I am a police on legacy subdivision,if it is only problem in your subdivision then use bug and ideas this suggestion is for all op fw aka full legacy, and I already use the bike also I think this bike is ok and if can’t even use the bike in jewellery the it’s your problem

NVM then, I thought you're someone else...but the Police bike is too much nerfed compared to other bikes. At high speed, it's not possible to make wheelies, and turning is very bad. So I think this should be buffed. Let's see what the developers say!

**Comment by joevapes3** [comment]
PD bike got a tiny buff in acceleration on this latest update. The main issue is that a large portion of the vanilla bikes still need to be balanced, and once that is done the bikes will be more even across the board. If there is a specific bike your having trouble against then let me know which one and I can address that individual bike sooner. I'll leave this thread open so if you have any specific bikes that are harder to keep up with you can say so. Either way it is on my to do list so keep an eye out on in the commits for when it get's finished.

**Comment by T4NZ1M** [comment]
> PD bike got a tiny buff in acceleration on this latest update. The main issue is that a large portion of the vanilla bikes still need to be balanced, and once that is done the bikes will be more even across the board. If there is a specific bike your having trouble against then let me know which one and I can address that individual bike sooner. I'll leave this thread open so if you have any specific bikes that are harder to keep up with you can say so. Either way it is on my to do list so keep an eye out on in the commits for when it get's finished.

Alright, if the other bikes are getting balanced then all good. And about specific bikes, Dinka TT is very easy to make sharp turns. The Sanchez can do a wheelie at its highest speed. PD bike can't even do wheelie after a certain speed. It's very hard to make turns with PD bikes. So for now, Dinka TT, Sanchez.

**Comment by Nuziatella** [comment]
Well this is more to do with weight and vehicle type. Dinka TT is a racing bike that as racing bikes go, can make sharp turns. Dirt bikes like the Sanchez are incredibly light and can wheelie at any point because of their weight class. PD bike is "heavy" do it's not particularly good at either. I am bringing in a PD dirt bike and super bike when I have more time. What we don't want is a white wash where PD bike is as good as every other bike or that every bike feels exactly the same with no discernable difference.

**Comment by Nuziatella** [comment]
This has been correct by @joevapes3
