### ISSUE TITLE
TOP Vehicles

### ISSUE THREAD

**Issue by MarioGigante** [InZidiuZ/legacy-assets-issue-tracker#51]
**Name:**
Who is suggesting this? Please include discord name.
TA-731 J. Andrade/Mario Gigante#0874

**Summary:**
Write a short summary of what your suggestion is about.

I would like to have more car's added to the city, and i feel like you should imagine you put the s15 rocket bunny on the server, make it a rare vehicle .. Imagine you only have a shipment with 3 S15 Rocket bunny's and 3 Skyline Rocket Bunny, i don't like the way you gotta pay to get those exclusive car's ( im not even sure if thats not agaisn't the fivem rules ) but imagine I suggested opening the Tuner Shop and i was the one who was selling those car's to the people in the city, and i know i only can sell 3 of each ! And if i need to buy ownership doesn't matter just tell me how much is it 🗡 

If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/vehicles/1992-mazda-rx-7-rocket-bunny
https://www.gta5-mods.com/vehicles/nissan-350z-rocket-bunny-kit-stanced-add-on
https://www.gta5-mods.com/vehicles/nissan-silvia-s15-rocket-bunny
https://www.gta5-mods.com/vehicles/nissan-skyline-gt-r-r32-rocket-bunny-tuning-template
https://www.gta5-mods.com/vehicles/rocket-bunny-v3-brz-add-on-19c0f857-52f1-4691-9464-287dc8016b41

**Reason:**
Why would your suggestion be a good addition to Legacy?
Because it would be a great addition to the legacy because people would buy more cars and you wont see the same car all over again

**Comment by MarioGigante** [comment]
@Djmeowzle i have a bunch of vehicles ready to be added to the vehicle's list of the city @Djmeowzle i just posted this 4 because i didn't want to spam this suggestion with links.

**Comment by MarioGigante** [comment]
@Djmeowzle And another thing about me owning the tuner shop, i dont give a single fuck if its me or other person, i just feel like you could do much more with a tuner shop !

**Comment by MarioGigante** [comment]
And i would garantee you, like you said and i dont really know why u would say that but .. opinions ! But its not only me who was the car's or that car .. @Djmeowzle so try not to jugde people without knowing what they truly want thats the only thing i wanna tell you

**Comment by Karpenkooo** [comment]
As much as i like these cars the problem is that they do not have any Tuning capabilities. I'm looking to add cars which you can customise to your liking. If everyone runs the same RX7 FD it wouldn't be very special.

Nice cars though

**Comment by MarioGigante** [comment]
@Karpenkooo Thats the thing im saying my brotha make it like an announcement saying " 10 silvia's s15 rocket bunny ( with a photo of the car ) gonna be avaiable at 'whatever time you want' to get it on the exclusive car dealership,. after you already sold 10 of those you change and every week you make a new car announcement, and the guys who enjoy these type of car's can get the car's ! And i have a list of car's like this and im gonna put here a random number but i have around 60 car's like this and im sure people don't need to change nothing on these car's because they are already perfect the way they are !

**Comment by MarioGigante** [comment]
@InZidiuZ Brotha so my suggestion here is maybe open a kind of tuner chip or maybe even a bussiness where i can import car's from other country's and the car's are limited ( and expensive ), I have around 60-70 car's ready to be added to the city if u would like my concept of opening a good car dealership bussiness, with only top-gear car's and yeah if u interesed in that concept after that i can give the car's to karpenko and he can test it out
