### ISSUE TITLE
[imports/civilian_*] Widebody 8F Drafter EDM

### ISSUE THREAD

**Issue by SMHDark** [InZidiuZ/legacy-assets-issue-tracker#510]
**Name:**
Who is suggesting this? Please include discord name.
Dark .#0911
**Summary:**
Write a short summary of what your suggestion is about.
I would like if you could add a Widebody 8F Drafter
**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/vehicles/obey-8f-d-street-widebody-version-add-on
**Reason:**
Why would your suggestion be a good addition to Legacy?
ive talked to many people about the widebody drafter and most people agree that it would be a nice choice to have between regular and widebody

**Comment by Nuziatella** [comment]
This is something that would be in the Exclusive Dealership, EDM. @joevapes3 can add it there

**Comment by joevapes3** [comment]
Being that this is more of a vanilla variant of the vehicles it would more than likely not make it into the EDM vehicles. Also this latest EDM pack has already had all the vehicles chosen for it, so keep an eye out in the next few weeks for an idea of what those might be. Closing this suggestion out.
