### ISSUE TITLE
[imports/vehicles] New EDM Cars

### ISSUE THREAD

**Issue by nimsaJChu** [InZidiuZ/legacy-assets-issue-tracker#512]
Name:
Jasmin Tortuga nimsaJ#9194

Summary:
I want to suggest to put in some new EDM cars, i actually would wish to have 2 specific in city, they might not be super-cars but they're some nice cars imo. 

Link:
https://de.gta5-mods.com/vehicles/dacia-sandero-2021

https://de.gta5-mods.com/vehicles/dacia-sandero-stepway-2021

https://de.gta5-mods.com/vehicles/abarth-500-esseesse-add-on-unlock

https://de.gta5-mods.com/vehicles/seat-ibiza-cupra-add-on

also some more that are not the newest but i think would be nice:

https://www.gta5-mods.com/vehicles/2014-mclaren-p1-fb28b756-465d-43e7-b4e0-9793bfa5f714
https://www.gta5-mods.com/vehicles/2015-bmw-f82-m4-fully-tunable
https://www.gta5-mods.com/vehicles/lamborghini-centenario
https://www.gta5-mods.com/vehicles/2015-ferrari-laferrari-hq-autospoiler
https://www.gta5-mods.com/vehicles/mercedes-benz-s500-w222
https://www.gta5-mods.com/vehicles/2015-porsche-918-spyder-weissach-kit-add-on-555271eb-bb54-4264-afbe-9182bfaebead
https://www.gta5-mods.com/vehicles/1967-shelby-mustang-gt500-hq-supertuning-lowriders-required
https://www.gta5-mods.com/vehicles/2015-dodge-challenger-hq-super-tuning-hellcat-nfs2015-animated-engine
https://www.gta5-mods.com/vehicles/2002-mazda-rx-7-spirit-r-type-a-series-iii-fd3s
https://www.gta5-mods.com/vehicles/2016-dodge-charger-sxt-r-t-srt-392-hellcat-add-on-replace-hq
https://www.gta5-mods.com/vehicles/tesla-roadster-2020-add-on-replace-auto-spoiler
https://www.gta5-mods.com/vehicles/bmw-m5-e39
https://www.gta5-mods.com/vehicles/ford-focus-rs-2017-add-on-replace-tuning-template-multi-livery
https://www.gta5-mods.com/vehicles/mercedes-benz-gls-63-amg-2015-add-on-replace-animated
https://www.gta5-mods.com/vehicles/lamborghini-urus-2018-add-on
https://www.gta5-mods.com/vehicles/2016-volkswagen-passat-b8-add-on

Reason:
I think it would be nice to have some more variety in the EDM especially with new cars, 2020+ so people can drive some of the newest cars. Also i think having more different cars, especially more Compacts/Hatchbacks to choose from would bring more variety into the streets of Los Santos.
Thats also what i heard from multiple people i talked to in city, that they'd wish to have some new cars at EDM to choose from.

**Comment by lewisrobson1** [comment]
I would 10000% buy all of these cars! Gonna get me some saving!

**Comment by Infamously1** [comment]
yooo these are sick! The range on the vehicles u picked is super good, u hit all the bases. Some cheaper ones for people who cant afford the super expensive 65k ones but want EDM, more variety in the mid tier and the super prestigious cars we absolutely need more of since we really only have the lambo and the bugatti which are above 300k!!

**Comment by PedroTheTurtle** [comment]
I love that Shelby Mustang and those little hatchbacks would definitely be a cute addition to this beautiful city.

**Comment by joevapes3** [comment]
Some of the vehicles you've suggested are already in in the new EDM cars that I am working on currently, and some already exist in the server from previous packs. This next pack will be a larger pack that I am working on daily, and should be finished soon. So just keep any eye out for the update when it's announced. 😄 Shouldn't be too much longer.
