### ISSUE TITLE
[peds/*] DOL Tactical Vest does not exist/fit women currently.

### ISSUE THREAD

**Issue by SilkyDrip** [InZidiuZ/legacy-assets-issue-tracker#513]
**Name:**
SilkyDrip#0943

**Summary:**
Need the DOL tactical vest to be altered to fit women models.

**Link:**
No links.

**Reason:**
We have multiple women in our organization that would like to rep our gear.

**Comment by DaxterPancake** [comment]
I have assigned the relevant people for this.

I did say at the start though that you'd need to source a female vest as the one that you're currently using doesn't fit females and editing the 3D model is a lot of work. Our current 3D artists are quite busy but I will see if they're able to add this to the list.

As for your shirt that you requested awhile ago, I have a long list of things that I am doing and never gave an ETA on when they'd be in the city. Lost most other people, you're probably going to have to wait until a new build is done.

Cheers.

**Comment by SilkyDrip** [comment]
Yeah the vest they wanted was removed from the city and none off the others look great with the patches. Are you allowed to use some of the old gangs vests to re-stitch or do they own the rights to them or does it have to be a vanilla vest?
![FFEMALE VEST2](https://user-images.gi
![FEMALE VEST1](https://user-images.githubusercontent.com/87866126/135786861-796d5435-93bc-419f-a9c3-484d4ffdad4f.png)
thubusercontent.com/87866126/135786853-76bc747f-5f49-4da9-9638-7f0452910d2e.png)
https://drive.google.com/drive/folders/1iMy7HCBj8uBFcwhQqqoKvpZ12stXKxbg - These are the images.

**Comment by SilkyDrip** [comment]
[mp_f_freemode_01_female_heist_task_001_u.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/7628846/mp_f_freemode_01_female_heist_task_001_u.zip)
This compressed file contains our vest for the females can someone let us know what the next steps are to get this implemented?

**Comment by SilkyDrip** [comment]
[mp_f_freemode_01_mp_f_january2016_task_001_u.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/7636163/mp_f_freemode_01_mp_f_january2016_task_001_u.zip)
Maybe this one is better? We can only hope.

**Comment by antihero6713** [comment]
Maybe @DaxterPancake  can try these. For me to work the model its very low down on my list of todos

**Comment by SilkyDrip** [comment]
Daxter was looking at it for me.

**Comment by antihero6713** [comment]
SoonTM

**Comment by DaxterPancake** [comment]
OH THIS WAS DONE! I CAN CLOSE THIS! WOHOO! GO US!
