### ISSUE TITLE
Coffee Machine decreasing Health Bar instead of Stress 

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/legacy-assets-issue-tracker#515]
**Reporter:**
Rakibul Hasan. Frankenstein#8200

**Summary:**
There are Bean Machine "Coffee Machine" in different places like Pillbox, PDM. After drinking, they should have decreased the Stress. But rather its decreasing the Health Bar.

## Additional Information

**Screenshots:**
https://imgur.com/a/3os7LAj

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is intended behavior. It's meant to remove some health because of how fast you are drinking the *warm* drink. If you wish for this behavior to change, feel free to create a normal suggestion.
