### ISSUE TITLE
[imports/vehicles]Lowering amount of dirt on the EDM Dodge Challenger

### ISSUE THREAD

**Issue by SirPiff** [InZidiuZ/legacy-assets-issue-tracker#516]
**Name:**
Who is suggesting this? Please include discord name.
Piff#7777

**Summary:**
Write a short summary of what your suggestion is about.
Currently, the EDM dodge challenger gets way too dirty so quickly that almost any paint job you put on it gets completely re-done to a paint job made of dirt, to make your paint job slightly shine through you'd have to use a Matte colour, even then it's kinda bad.

**Link:**
If there are any links to what you're suggesting, please add them here.
N/A

**Reason:**
Why would your suggestion be a good addition to Legacy?
Just a QoL thing so owners of it don't have to wash it every 5min just to see their paint job c:

**Comment by joevapes3** [comment]
Added this to my trello and will take a look at it to see what I can do. I will update this post as soon as I get it addressed. Thanks for bringing this to my attention.

**Comment by Nuziatella** [comment]
This has been resolved
