### ISSUE TITLE
Legendary Japanese cars (and f40) added to EDM rotaton

### ISSUE THREAD

**Issue by definitelynothim** [InZidiuZ/legacy-assets-issue-tracker#518]
**Name:**
Baba#9198

**Summary:**
Just wanted to suggest a few legendary cars to the EDM list. Anyone familiar with cars should be very excited to see these added.

**Link:**
https://www.gta5-mods.com/vehicles/mazda-rx7-fc3s-tunable
https://www.gta5-mods.com/vehicles/honda-s2000-tunable
https://www.gta5-mods.com/vehicles/honda-nsx-r-na1-1992
https://www.gta5-mods.com/vehicles/nissan-fairlady-z-s30-addon-rhd-devil-z
https://www.gta5-mods.com/vehicles/1994-mazda-mx-5-miata-na6c
https://www.gta5-mods.com/vehicles/nissan-300zx-z32
https://www.gta5-mods.com/vehicles/1987-ferrari-f40-1-0

**Reason:**
So we can be super cool with our Japanese cars (and f40) yo

**Comment by joevapes3** [comment]
The latest EDM cars have already been chosen and per chance some of the cars you have listed may or may not be included in that pack. Should be giving out a sneak peek soon for them so just keep an eye out for that when it happens. Closing out suggestion.
