### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ScoochiScooter** [InZidiuZ/legacy-assets-issue-tracker#519]
**Name:**
Who is suggesting this? Please include discord name.
Scooter   pipyeee#5628
**Summary:**
Write a short summary of what your suggestion is about.
The 2017 Camaro ZL1 should be improved performance wise and a sound change so the car can be worth buying again and will be more like it should be IRL the Camaro is deadly slow in legacy and overall is really unrealistic being a 75000 dollar car and its IRL version being amazing
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
With the crazy amount of people who own the Camaro ZL1 and they amount of people I have heard complain about this issue I think this small change will bring big improvement's to the server with people owning the ZL1 and thinking its just a 75000 dollar brick off a car

**Comment by ScoochiScooter** [comment]
For specifics on the sound of the car I think the best option would be near the same sound as the hellcat maybe some changes with it

**Comment by joevapes3** [comment]
Performance balancing of the older EDM cars will be getting addressed once the latest EDM vehicles are completed and pushed live. Until then just hold tight until those changes go live. Updated my trello board with this issue and will review it at that time. Will post results here once that is completed.
