### ISSUE TITLE
[vehicles/vanilla] Shitzu Defiler's Performance

### ISSUE THREAD

**Issue by PsychoGrandpa** [InZidiuZ/legacy-assets-issue-tracker#520]
**Name:**
Who is suggesting this? Please include discord name.
ChiknLegPiss#8936

**Summary:**
Write a short summary of what your suggestion is about.
I am from Legacy BD subdivision. I used to own this bike Shitzu Defiler before our last server wipe. I have purchased it recently again and I was really disappointed after looking at its performance. Earlier it used to go 182 top now it barely goes 140. You will see it in the Clip below.

- Both MAX
- Both are fully repaired
I have included a clip that shows the top speed of both the bikes and a picture showing its damage. I recorded a part where the customizations are done to it are shown but that clip was really choppy for some reason. If you need it will record and post it again.

I know this might not be a top-of-the-list task, but if it is short please solve it for me. <3

**Link:**
If there are any links to what you're suggesting, please add them here.
https://streamable.com/kdt8vl
https://cdn.discordapp.com/attachments/882842174381764638/899910144006168576/unknown.png

**Reason:**
Why would your suggestion be a good addition to Legacy?
It's a single-seater bike and one that is fun to ride too. Looks cool, so I think nerfing it was not a very good decision. It has loads of customs.

**Comment by joevapes3** [comment]
Added this issue to my trello board and will update this suggestion once any changes are pushed.

**Comment by Nuziatella** [comment]
Some adjustments have been made. Further adjustments will be had in the future but for now it's performance has been bumped.
