### ISSUE TITLE
Add A Garage at the Hanger  (Used only for Owned Planes)

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/legacy-assets-issue-tracker#521]
**Summary:**
Write a short summary of what your suggestion is about.
When the aviation dept was added we wanted to do rp where people will be able to own small Jett and Heli once they are fully ready to fly on their own. We had a lot of ideas regarding owing a aircraft. If the garage is added it would make the RP into reality. This will help us reducing the issues with people spawning multiple airplanes and leaving it at the spawners I feel like this would be a great thing to add. 
**Link:**
N/A Any of the Hanger at the airport( Could he labeled as “ Aircraft Hanger”

**Comment by Nuziatella** [comment]
The garage script currently doesn't support this. In the future once development supports this feature it would inherently allow the owning of any vehicle once the script is re-written or updated.
