### ISSUE TITLE
[peds/*] Gang Clothes ( The Crips) 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/legacy-assets-issue-tracker#522]
**Name:**
Discord - гє๔#6245

**Summary:**
It would be nice if we can have Crips outfit. We have a gang at our Sub and we were not able to find any proper dress other than the color blue. 
**Link:**
If there are any links to what you're suggesting, please add them here.
https://prnt.sc/1x0k372
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be nice for our gang and the rp would be a bit more realistic

**Comment by DaxterPancake** [comment]
As of recent more blue themed clothing was added, you also have blue armor and blue shoes. If this is not enough, please feel free to create another issue.
