### ISSUE TITLE
Mitsubishi Evo Top Speed

### ISSUE THREAD

**Issue by Evmo3** [InZidiuZ/legacy-assets-issue-tracker#525]
**Name:**
evmo#9799

**Summary:**
Recently bought the mitsubishi evo from the heroic tier, came to realisation after fully upgrading it that the max speed is around 135mph which is pretty disappointing not sure if this is meant to be the speed but i can steal a car from a local and it goes faster other than the speed the car handles and drives great.

**Comment by joevapes3** [comment]
added issues to trello board, will update when or if any changes are applied.

**Comment by joevapes3** [comment]
This issue has been resolved, evo was hard capped on top speed and that was fixed along with turning improvements and acceleration buff. Should be more on par with the current meta along with the new edm assets on their way in soon tm.
