### ISSUE TITLE
[maps/paleto_bay_pd] Paleto Bay PD

### ISSUE THREAD

**Issue by V4P1Dx69** [InZidiuZ/legacy-assets-issue-tracker#526]
**Name:**
Who is suggesting this? Please include the discord name.
V4P1D#2343
**Summary:**
Write a short summary of what your suggestion is about.
Suggesting a new interior for Paleto Bay PD
**Link:**
If there are any links to what you're suggesting, please add them here.
A preview of the interior -> [Click Here](https://www.youtube.com/watch?v=NuNCBDoepSw)
More details at [UncleJust](https://unclejust.tebex.io/package/4795834)
**Reason:**
Why would your suggestion be a good addition to Legacy?
The interior I'm suggesting maybe a way better than the interior we're currently having. That's it. Lemme know your thoughts on this.

**Comment by DaxterPancake** [comment]
For what reasons do you believe this would be better than what is currently in place? The Paleto PD is fully functioning as it stands currently so without an issue or something of the sort, I don't see why it would need replacing.

**Comment by antihero6713** [comment]
closing due to escrow. can't use this interior anymore
