### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/legacy-assets-issue-tracker#527]
Name: Me
Discord:Star Groot#2478

Summary:
I wanted to suggest a few new cars that you can import to edm to get more vehicles in the city. I asked some of my friends if they have and preffered cars they want to see in the city and according to that came up with a list of cars I suggest being imported to the city.
Links:
https://www.gta5-mods.com/vehicles/1998-mercedes-benz-clk-gtr
https://www.gta5-mods.com/vehicles/maybach-62s
https://www.gta5-mods.com/vehicles/2017-koenigsegg-agera-rs-add-on
https://www.gta5-mods.com/vehicles/hyundai-veloster
https://www.gta5-mods.com/vehicles/toyota-chaser-jzx100-addon-replace-tuning-cambered-hq

Reason:
Importing these cars would add a few nice vehicles to the edm rotation which doesnt seem to get new imports very often so that would probably be nice if people could buy different/new cars

**Comment by joevapes3** [comment]
A new EDM import pack is set to drop here very soon, there is going to be lots of new vehicles for people to chose from. Keep an eye out for those to come. Being that the pack is almost completed, no new EDM vehicle suggestions are being taken at this time.
