### ISSUE TITLE
[maps/harmony_lsc] Harmony Repair Exterior Changes 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#528]
**Name:**
Who is suggesting this? Please include discord name.
CloudTheWolf#0001

**Summary:**
Write a short summary of what your suggestion is about.

Due to the Interior of the harmony repair shop being bound to the same MLO as Lost we would like to shift our focus on having outside bays. This would be beneficial as there is a lot of trucking traffic in there area now.  

I have drawn a rough design with either a second bay outside to the right, or remove the gas station and move the pumps allowing 3 outside bays on the left.

**Link:**
If there are any links to what you're suggesting, please add them here.
Example (Based on stock Harmony Layout)
https://imgur.com/a/rWESbOx

**Reason:**
Why would your suggestion be a good addition to Legacy?

Currently Harmony only has 1 bay so can not effectively handle multiple customers, as well as not being able to repair larger vehicle without the risk of them ending up at EDM or on the roof. This would allow mechanics to repair any vehicle that needs one (Including small aircraft, Tow Trucks and Phantoms)

On the international server State were saying this was being done Soon™️ but there was never any news or updates when they owned it, and it now is privatised as it's own company again.

**Comment by CloudTheWolf** [comment]
Additionally is it possible to have the 2 bay doors changes to one of the following, without impacting the Lost compound:

1: Make the bay doors lockable in the Open Position 
2: Make the bay doors just always be open.
3: Remove the bay doors entirely (Since we can't lock them closed anyway, because of the LS Customs, they are just a pain to find something to keep them open)

**Comment by CloudTheWolf** [comment]
To remove the need to any Map changes, could we get just 1 Outside bay, mirroring how they have it at Lost

Outside Bay at Lost:  https://i.imgur.com/gnWQkh2.jpg

Here: https://i.imgur.com/n7MR2BF.jpg

**Comment by MetaHatter** [comment]
I believe this is completed.  If there is additional work required, open a new ticket.
