### ISSUE TITLE
[vehicles/boats] Suggestion for new PD Boat units

### ISSUE THREAD

**Issue by V4P1Dx69** [InZidiuZ/legacy-assets-issue-tracker#529]
**Name:**
Who is suggesting this? Please include the discord name.
V4P1D#2343
**Summary:**
Write a short summary of what your suggestion is about.
This suggestion is mainly about PD Boat units. As far as I remember it's been a long time that new Boat units are introduced to Police RP. Right now, we only have the default GTA V boat unit for police. So I'm suggesting some new Boat units for our server.
**Link:**
If there are any links to what you're suggesting, please add them here.
[Redneck 2019 Boat Pack](https://redneckmods.com/products/2019-boat-pack?pr_prod_strat=copurchase&pr_rec_pid=6610684838083&pr_ref_pid=6617211076803&pr_seq=uniform)
![image](https://user-images.githubusercontent.com/64460439/141443070-dd223274-c8f5-48db-b6cc-e11650e6989f.png)
**Reason:**
Why would your suggestion be a good addition to Legacy?
As I said, from the beginning of Legacy roleplay there were no new boat units introduced. So adding new addition of boat units may make people more interested in PD.

**Comment by Nuziatella** [comment]
New liveries would need to be created to support the current SASP, BCSO, and FIB grouping. I'll add them once new liveries can be created.

**Comment by joevapes3** [comment]
So we ended up just reskinning the Predator and adding a code 3 light bar to it. It will still provide the function we need for a PD boat and it will at least look a bit better. The boats you suggested by Redneck all have various issues with their models that would not suit our needs. Appreciate the suggestion and closing this thread.
