### ISSUE TITLE
[vehicles/*] New and Improved Commercial/Industrial Vehicles

### ISSUE THREAD

**Issue by Djmeowzle** [InZidiuZ/legacy-assets-issue-tracker#531]
Name: Djmeowzle#4701

Summary: Update to all the Industrial Vehicles in the city.

Link: https://www.gta5-mods.com/vehicles/mtl-packer-replace-tuning-template-31e4338c-f4c4-46f0-a606-af0ccf8b58f5

Reason: Would add a clean fresh look to Truckers, as well as improve the overall quality and aesthetic of the city as a whole.

**Comment by Nuziatella** [comment]
I'll be adding new vehicles soon(tm) that can be purchased in addition to or instead of the default

**Comment by Nuziatella** [comment]
New vehicles for these jobs have been added.
