### ISSUE TITLE
[peds/clothing] Bean Machine's Clothing

### ISSUE THREAD

**Issue by MaxieL99** [InZidiuZ/legacy-assets-issue-tracker#532]
**Name:**
MaxieMassiL99#3103

**Summary:**
With the new additions to Clothes being added in for Bean Machine shirts and hats, i think a we can use Burger shot's shirts make it for Bean Machine and for hat Bean Machine logo on it like 2nd gear hat but on Brown hat

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
This would give any employee for the Bean Machine to stands out and more choice to wear and Improve the RP with civilian RP

**Comment by antihero6713** [comment]
shirt exist now closing
