### ISSUE TITLE
[peds/*] Undershirt 45 additional textures

### ISSUE THREAD

**Issue by tftwsaaron** [InZidiuZ/legacy-assets-issue-tracker#534]
**Name:**
TftwsAaron

**Summary:**
could undershirt 45 come in more colors 

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:*
it would help with outfits undershirt 45 is one of the few undershirt that looks good under a tshirt

**Comment by DaxterPancake** [comment]
This has been done and will be live on the next clothing build.
