### ISSUE TITLE
[maps/*] Suggestion to add Pacific Bluffs interior into city

### ISSUE THREAD

**Issue by TheCuppcake** [InZidiuZ/legacy-assets-issue-tracker#535]
**Name:**
Cuppcake Lamere Cuppcake#0001

**Summary:**
Adding Pacific Bluffs interior into the city.
**Link:**
[If there are any links to what you're suggesting, please add them here.] 
(https://www.youtube.com/watch?v=oVjItVjD4Ns&ab_channel=JackMLO%27s)
**Reason:**
Why would your suggestion be a good addition to Legacy?
I have recently obtained the property in city by getting a permanent business permit. Ideally I would love to add in the interior of the building because it would add immense avenues of roleplay into the city. There's a gym, a mechanics shop, private casino, strip club and much more. Putting an interior on the property could give people a new place to hang out and would allow me to fully utilize the businesses full potential. Where the business is located, it adds an additional location where people can migrate to and provide a business in that area. The area the resort is located does not have much around it business wise so this will be able to distribute role-play more around the city. Adding an interior would also boost the success and rp side of current Pacific Bluffs events, allowing patrons to fully immerse themselves into the resort and enjoy all aspects! Thank you so much for your time :)

**Comment by rubanio** [comment]
This would be a great addition to the city. I would love to see this business

**Comment by Brookiedoughh** [comment]
I believe this could make a big impact to our roleplaying community. Pacific Bluffs can only get better with a proper building to host events and bring our community closer together.

**Comment by BasedWiggles** [comment]
A cool new spot to have event sounds just want the city need. I would love to host some partys there.

**Comment by RetroCharles** [comment]
I believe adding interior to Pacific Bluffs would be a great addition to the city. This area has endless and great potential to hold city events and be a new point of interest for people to gather, interact, and enhance more RP arcs. Based on the youtube link the interior will cater to all types of different lifestyles in the city such as car lovers, gym junkies, spa goers, gambling addicts, exotic dancers, bookworms and coffee heads, beach lovers, the list goes on. The Pacific bluffs with this added interior will be beneficial to the city, especially being that there is no other resort in the city. This resort has potential to be both a place of gathering/events and work opportunities.

Pacific Bluffs also has had multiple successful events in the past, so that alone, has already proven that this resort is hot spot and can use a bit more love and attention. And with a dedicated hard-working individual such as cuppcake, being the business owner, I have no doubt her management experiences and set plans for Pacific Bluffs will thrive and push this resort beyond its limits. 

I'm sure, I and the rest city can't wait to see this business open up.

**Comment by TSWv** [comment]
This would be amazing to the community to have different events in the city,Pacific Bluffs have had multiple success events in the past and people enjoyed their selves when they have been at these events.

I would love to see this business going far!

**Comment by Epps30** [comment]
I think this would be an amazing add to the city because of the location of Pacific Bluffs as there is not too many places around it. Also the amount of new rp arcs and events alone would add so much to the city. Like someone said above every event that has been hosted by Pacific Bluffs was a huge success and had a very big turnout. This would only make the event possibility larger and add a new aspect to north of the city.

**Comment by sleighwhite** [comment]
I love this! Bridging the gap from the city to up North. I like that this business would encourage people to come up north a bit more. While they come to Pacific Bluffs for a party, they may choose to drive through Paleto on the way back to the city and get a repair or change their clothes at the clothing store up there. They may decide to take a hunting trip as well!

**Comment by vol5** [comment]
From my perspective this would be a huge value add. Cuppington has went above and beyond to provide people with experiences in the city and this would logically follow. The amount of effort speaks for itself and this would only empower her to give people more fun and dopamine.

**Comment by MVirk22** [comment]
Pacific bluff's already is one of the best businesses in the city with the amount of unique and quality events hosted by the owner that provide awesome rp interactions within the community. 
Adding the interior requested above is vital to the business as it would not only complete the business but it would also provide so much more content to the city. Having a repair shop, a boxing ring, a casino and a restaurant inside the resort will make this a city hub where people can come hang-out and create a lot of rp interactions. The current business owner has already done an amazing job running the business and if there is anyone who can make pacific bluffs the gem of the city, it would be cuppcake. 
I am really looking forward to the addition of the interior to pacific bluffs and all the content it will provide for the community.

**Comment by Lohtx** [comment]
I think this would bring so much more life to the city. There really isn't too much to do right now and there's not real "hang out" spot and this would be PERFECT!

**Comment by DaxterPancake** [comment]
Is this the only interior you found or is there a different one we can look at?

**Comment by TheCuppcake** [comment]
This is the only one I have been able to find, is there an issue with this one?

**Comment by TheCuppcake** [comment]
If you know of a creator who makes custom ones i am willing to work with someone but I am also very favorable to most of the assetts in this interior and see massive benefits in almost every aspect of it

**Comment by DaxterPancake** [comment]
> This is the only one I have been able to find, is there an issue with this one?

There is no issue, have you purchased this interior to use? Or if given approval are you going to purchase it?

**Comment by TheCuppcake** [comment]
If given approval i will purchase, I wanted to make sure it was possible before purchasing since its quite pricey. I do have the funds on hand though, so just need the approval.

**Comment by DaxterPancake** [comment]
@antihero6713 Could you look into this and advise if this could be done?

**Comment by KatLikesTacos** [comment]
This looks really cool, however I think it's worth pointing out that it would not be very fair to the established strip club in city, The Vanilla Unicorn, if you started running a competing strip club out of this location. This map adds a lot of features at once. So long as they aren't being used to pull traffic away from existing businesses, I think it could be a great addition.

**Comment by TheCuppcake** [comment]
Absolutely not, I've already spoken to the owner of VU and only her dancers would be dancing at our club if they wanted to. I will have back up dancers from Bahama Mamas as well incase VU dancers are not available. My plan and current approach is collaborating with every business in the city so that our city as a community benefits as a whole, Bartenders from O'Malleys and bahama mamas along with catering from burgershot and upcoming restaurants in the city. I definitely do not want to take patrons from the current businesses in the city, if anything I am looking more to expand on their businesses, to work together and to provide a larger hub for events. :D

**Comment by KatLikesTacos** [comment]
> Absolutely not, I've already spoken to the owner of VU and only her dancers would be dancing at our club if they wanted to. I will have back up dancers from Bahama Mamas (a few of them work at both locations including myself) as well incase VU dancers are not available. My plan and current approach is collaborating with every business in the city so that our city as a community benefits as a whole, Bartenders from O'Malleys and bahama mamas along with catering from burgershot and upcoming restaurants in the city. I definitely do not want to take patrons from the current businesses in the city, if anything I am looking more to expand on their businesses, to work together and to provide a larger hub for events. My goal is not to negatively impact the current economy, it is to help it grow. :D

I love that! Sounds like it'll bring a lot of collaboration with existing businesses then. Could be a really interesting venue for a jobs fair or something in the future, since it sounds like this location would have a lot of opportunities to show off. ;)

**Comment by battlea** [comment]
This would be a great place to hang out and interact with new people! Hopefully we get to see it soon <3

**Comment by antihero6713** [comment]
Their is no way for me to check this since its payware. Once i get some other projects out of the way we can talk about this, I am only 1 guy

**Comment by TheCuppcake** [comment]
Any updates on this at all?

**Comment by DaxterPancake** [comment]
> Any updates on this at all?

Antihero commented above your post saying he cannot check this map as it is payware. He currently has other projects he is working on then he can contact you to talk about this map being added.

**Comment by TheCuppcake** [comment]
I have now purchased the interior. Hopefully someone can take a look at it soon and let me know :3 Thank you Dev team for all that u do to make the city better for all of us

**Comment by antihero6713** [comment]
This has been added closing this.
