### ISSUE TITLE
[maps/?] - Winery - Deux Fois: Make Cleaning Great Again

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/legacy-assets-issue-tracker#536]
Name:
vol 5#3752 -- Bill Brook

Summary:
Here is a detailed description of a unique Wine type for the Vineyard that I believe would be an awesome value add to the city. 

Link:
Vendor Location: https://cdn.discordapp.com/attachments/876537143391051776/910939906669441034/Screenshot_2021-11-18_070709.png

This is congruent and has transparent background in real png file
Product Image Design: https://cdn.discordapp.com/attachments/881912453095632896/910386555674308658/deux_fois2.png

Reason and Intent:

Inspiration: https://youtu.be/5NV6Rdv1a3I?t=55

The forefront goal for this is to add more value to cleaning houses. Acting as a chance for a quantity boost increasing the overall amount of items people can earn by gathering. Providing them with a tool that gives them more dopamine and creates a more enjoyable experience overall. In a way to make it more fun and in a way to make it more profitable. The amount of excitement someone would have if they got a drop of two guns instead of one or two diamonds would be enough to make cleaning houses more exciting and something that people would partake in more often. This would not just be a general buff. Because, it's woven in as a product and would act more as a harvesting set that you acquire through RP knowledge. If this is to garner much enthusiasm. It's an additional value add for cops, to break away from bank-bank-bank. Even though it's not a major crime, this is a layer of roleplay that gives more variety to their day. From the crim perspective cleaning is lacking in terms of reward for player time investment within the quantity department. I break this down to the gameplay loop not feeling rewarding enough and this could satiate the hunger for more dopamine within this experience. Becoming a fantastic way to diversify the vineyards' reach to provide value through product. It currently lacks physical products to sell and this would be something substantial yet not over the top. Giving potential employees a mission to pursue, along with identity. Affording them more earning capability outside of events, packages, and paychecks. Another reason to bring people up north away from the pollution is a plus and we would like to make that happen.

I'm trying to add some unique ideas in pursuit of what I would consider a “fun” roleplay experience. The more dopamine the better. If you have any opinions, drop your Ideas down below.  

Product:

Name: Deux Fois - Rosé

Product weight: 5

Product Deux Fois Vendor Pricing: $200 per bottle

Product description: We're up all night to get lucky.

Product Inventory Image: Custom vector and png is made, I am not sure of the correct dimensions required. If any size or file format is needed, I can provide them. Image is linked above.

Character Mechanic: 

Adds X% of stress (5% suggested)
Reduces  X% of thirst (10% suggested)

Game Mechanic:

Has a 50% chance to double the loot drop from every successful search while cleaning houses.
Duration: 15mins - this would make 4 items cover the full cleaning night cycle.

Market price $500ish, If per person quantity restriction would be required this can be enforced similar to the weed store so people can not infinitely buy product.

Vendor: There is no current alcohol vendor in the winery. A replica of one from any bar would be required. Preferred Vendor location is in image above.

**Comment by TheCuppcake** [comment]
This would be such a cool and fascinating add in for the city! It would also give a valuable source of revenue to a business that is severely lacking that last little touch to be at its full potential. I truly think this could drive alot of positive rp arcs for the city both for crims and cops!
