### ISSUE TITLE
Passout/K.O Mechanic for Fist fights & Snowballs

### ISSUE THREAD

**Issue by CharlesMac94** [InZidiuZ/legacy-assets-issue-tracker#539]
Charles Macx
Discord: Hey Im Cody#0216

**Summary:** 

Make it so that fist fighting doesn't require an EMS worker/Hospital, and also heavily reduce the damage that snowballs do. 

**Link:**
N/A but ideally it would be a 60-120 second timer before being allowed to stand up again.

**Reason:** 

I firmly believe that it would be a useful feature to allow people to only be temporarily knocked out after a fist fight for (x) amount of time instead of downed until reaching a hospital. This would encourage more fist fights instead of resorting right to weapons, hopefully encourage more fight night events/activities in the PFC arena as well.

It is super inconvenient and frankly slightly unnecessary that being punched a few times would permanently down someone.

With that being said, I'd also like to discuss the possibility to nerf how much damage snowballs do, so that we can have snowball fights less dangerous than if we were to shoot each other with real guns (lol)

Although they seem like small changes, I really do believe this would be a positive addition to the community.

**Comment by xarxesthegreat** [comment]
YES! MC's need to be able to beat the crap out of their prospects without having to then waste time taking them to pillbox

**Comment by ScoochiScooter** [comment]
I think this is a really good idea it would open up the possibility for so many things such as street fights and maybe even a boxing match, Good things could come out of this.

**Comment by Nuziatella** [comment]
This is script related and should be suggested [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
