### ISSUE TITLE
Pfister Neon speed capped

### ISSUE THREAD

**Issue by Muliki** [InZidiuZ/legacy-assets-issue-tracker#54]
**Reporter:**
Muliki

**Summary:**
The cars top speed caps out at 130 even with engine upgrades.

## Additional Information

**Screenshots:**
N/A

**Notes:**
N/A

**Comment by Karpenkooo** [comment]
Hey,

I've buffed the Pfister Neon by another 20 mph. In the future please put more effort into your Bug Reports.

_Karpenko_

_**OP-FW Car Dev**_
