### ISSUE TITLE
Suggestion to add Ingame document system

### ISSUE THREAD

**Issue by Milan345** [InZidiuZ/legacy-assets-issue-tracker#543]
**Name:**
O'Doyle#3386

**Summary:**
it's all about document/paperwork ingame

**Link:**
Link1: https://forum.cfx.re/t/release-documents-system-paid-esx-qbcore-vrp-standalone/2386305
Link2: https://github.com/apoiat/ESX_Documents
Link3: https://forum.cfx.re/t/release-esx-documents/547648

**Reason:**
We only have notepad as an ingame document. Implementing document system would help doing all the paperwork ingame instead of doing it in discord. Also helping many job such as Lawyer, EMS, SASP etc in issuing warrants, Medical reports, citizen criminal record.

**Comment by DC0402** [comment]
❤

**Comment by Nuziatella** [comment]
Please repost in the correct github: [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
