### ISSUE TITLE
[maps/?] Improve character creation spot

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/legacy-assets-issue-tracker#545]
**Name:**
TheOneLizard#4196 (issue was addressed before by @djkenada in the framework issue tracker, we had talked about it before)

**Summary:**
Adding 4 spotlights at the character creation spot, highlighting all angles with good lighting.
Maybe adding walls too in order to prevent bad visibility from changing sunlight angles.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
At times, the natural light at the airport can make it very difficult to create a character as to being able to see what things actually look like in proper light, because either it is nighttime or the angle of the sunlight disrupts the visibility of the parts in shadows.
These two assets could fix that problem relatively easily.

**Comment by antihero6713** [comment]
Its on a TODO list

**Comment by TheOneLizard** [comment]
apologies <3

**Comment by MetaHatter** [comment]
The character creation spot has been massively overhauled since this was created.   If it's still an issue, create a new ticket,
