### ISSUE TITLE
[maps/boilingbroke] Bug report - Bolingbroke Prison Interior

### ISSUE THREAD

**Issue by Skonchy** [InZidiuZ/legacy-assets-issue-tracker#547]
**Reporter:**
Skonchy#9546

**Summary:**
The man-door entrance to Bolingbroke prison works correctly with the door lock script, but behind the moving door is a solid immovable door preventing entry. There's also a gate that can be accessed by the door-lock script while being out of sight. To reproduce go to the second floor hallway between laundry and the Bubble and look towards the single door at the end of the hall.

## Additional Information

**Screenshots:**
I don't have screenshots but can update later with them if necessary.

**Notes:**
The gate interaction issue is probably more applicable to be listed in https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2097 but was told to bring it here as well!

**Comment by antihero6713** [comment]
should be fixed with latest update
