### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Smolnisno** [InZidiuZ/legacy-assets-issue-tracker#548]
Smol Nismo smol-nisno#3835

**Summary:**
Write a short summary of what your suggestion is about.
Can i get the original Sound to my corvette C7 (44NOOO58) before the update of 12/15?

The new sound is really obnoxious and loud , if I could get the original sound to the car that would be perfect. I can barely drive and hear people in the car.

**Comment by PurpleHzea** [comment]
I agree 100%, I can't hear anything when I drive the C7 now and it hurts to listen to.

**Comment by Nuziatella** [comment]
This had been resolved.
