### ISSUE TITLE
[peds/*] Memorial Armbands

### ISSUE THREAD

**Issue by djclark21** [InZidiuZ/legacy-assets-issue-tracker#549]
Dave (djclark21#1571)

I was wondering, as part of a memorial for Kate, is there a way to add a decal or other article of clothing to honor her for EMS to wear with their uniforms? It would be like an arm band. Black. With white lettering and the only thing on the band would be her call sign? Not sure if it's possible and I apologize if this isn't the right place to post this. Thank you.

Since we've retired the callsign, it's forever hers and this would be a nice way to acknowledge her on a daily basis. Just want to honor her memory as part of EMS and as huge part of our city and community.

**Comment by z-Lunar** [comment]
> Dave (djclark21#1571)
> 
> I was wondering, as part of a memorial for Kate, is there a way to add a decal or other article of clothing to honor her for EMS to wear with their uniforms? It would be like an arm band. Black. With white lettering and the only thing on the band would be her call sign? Not sure if it's possible and I apologize if this isn't the right place to post this. Thank you.
> 
> Since we've retired the callsign, it's forever hers and this would be a nice way to acknowledge her on a daily basis. Just want to honor her memory as part of EMS and as huge part of our city and community.

I am interested in hearing your idea further about this, are you able to post photos or examples of what you mean?.

**Comment by djclark21** [comment]
> 

Sure. Something like below...

![image](https://user-images.githubusercontent.com/96215919/146446690-1fe1be6a-dae0-4353-933c-7f15e795b69a.png)

![image](https://user-images.githubusercontent.com/96215919/146446736-d5790187-dfa8-4595-ba81-29234eb942ce.png)

**Comment by MetaHatter** [comment]
I agree with this being an actual AMAZING idea.  Unfortunately, with the way GTA does decals and the HUGE variations in clothing on that spot on the upper arm it's not technically possible to do in a way that would really work effectively.

**Comment by DaxterPancake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Memorial Armband](https://trello.com/c/lMHXWmq8/59-memorial-armband)
