### ISSUE TITLE
Suggestion: Off-Road EMS Car

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/legacy-assets-issue-tracker#55]
**Name:**
Ciros, Ciros#2048

**Summary:**
Would like to add more EMS cars.

**Link:**
https://www.gta5-mods.com/vehicles/2016-ford-explorer-fpiu-qrv-saems-els
https://www.gta5-mods.com/vehicles/dodge-charger-rt-ems-for-fivem-and-sp

**Reason:**
Many EMT's have been complaining about how they cannot reach calls up north in time, people just respawn on them even after being sent a message, Or that the call is in an area inaccessible by your basic Ambulance, And the only option for them, is Medevac and not everyone is Medevac trained or can fly a Helicopter.

**Comment by Karpenkooo** [comment]
No :)

**Comment by Karpenkooo** [comment]
Sorry for the slow reply LUL
