### ISSUE TITLE
[vehicles/is350mod] Lexus IS350 model issue

### ISSUE THREAD

**Issue by Smolnisno** [InZidiuZ/legacy-assets-issue-tracker#551]
smol-nisno#3835

The Lexus is350 sedan has a Frunk which is very weird on the car as it does have a regular Trunk IRL ,and I think the trunk position should be moved from the front of the car to the back 

IRL the Lexus is350 does not have a frunk as it does a engine in the front and trunk space in the back

**Comment by joevapes3** [comment]
I'll check the vehicle model for the trunk flag and see if it's swapped to the bonnet when I do the seating upgrade to the vehicle. Added this to my board to be worked on, and will update when I have a finding.

**Comment by joevapes3** [comment]
This issue has been corrected and should be live when the next asset merger takes place. I also updated the vehicles dirt map to not be so heavily coated and the vehicle can now seat 5 people instead of 4. Regardless, thanks for bringing this to my attention.
