### ISSUE TITLE
/pole_dance does not work

### ISSUE THREAD

**Issue by PoppySins** [InZidiuZ/legacy-assets-issue-tracker#552]
**Reporter:**
PoppySins#1292

**Summary:**
A few weeks ago, I put a stripper pole in my house and the /pole_dance command worked just fine. Tonight, multiple people tried to get it to work, even going as far as moving the entire pole to no avail- the command just isn't working right now

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Nuziatella** [comment]
This is a script issue and not assets. Please report your issue [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
