### ISSUE TITLE
Designs added for clothing for possible Future Business

### ISSUE THREAD

**Issue by Ghaaastly** [InZidiuZ/legacy-assets-issue-tracker#553]
**Name:**
Roy Johnson Ghaaastly#1958

**Summary:**
I have a business proposal I submitted and would like a uniform to present to get approved. 

**Link:**
I have the files made and done for clothing but would like to submit two car vinyls to get added or custom cars for delivery business. 

**Reason:**
With a hopefully upcoming future business I would need the uniforms to add for future employees. I have done the work to try and make easier on the development team for uniforms.

**Comment by Ghaaastly** [comment]
Panto - Pizza This
![pizzathisponto](https://user-images.githubusercontent.com/96395022/146824947-0ca497b5-6bdd-41e0-b17f-26a211e375f2.JPG)
 Lokus - Pizza This
![pizzathisfaggio](https://user-images.githubusercontent.com/96395022/146825032-57751eb3-b4d2-410c-891b-78fcc958749b.JPG)

**Comment by Ghaaastly** [comment]
https://www.gta5-mods.com/vehicles/foodworks-food-delivery-pack
Link to vehicles

**Comment by Nuziatella** [comment]
This has been added.
