### ISSUE TITLE
[peds/*] New clothes added for new business 

### ISSUE THREAD

**Issue by Ghaaastly** [InZidiuZ/legacy-assets-issue-tracker#554]
**Name:**
Roy Johnson/Ghaaastly#1958

**Summary:**
I am wanting to add Pizza This business to server and would want a uniform added. 

**Link:**
I will attach the clothes I would like added. 

**Reason:**
It will offer a job to new players to city looking for guidance. It will be a great first stop for white list job to learn about the city and what you can do. 
[PIZZADESIGNSFINAL.zip](https://github.com/InZidiuZ/legacy-assets-issue-tracker/files/7774225/PIZZADESIGNSFINAL.zip)

**Comment by Ghaaastly** [comment]
![image](https://user-images.githubusercontent.com/96395022/147364965-4118ae37-3251-43a5-b716-da5d62373ea3.png)
![unknown](https://user-images.githubusercontent.com/96395022/147364985-fed4194b-1595-4356-b4b0-c741227177b8.png)
![unknown](https://user-images.githubusercontent.com/96395022/147364990-14286f8a-6fbf-4af2-a562-0efeb5634793.png)
![unknown](https://user-images.githubusercontent.com/96395022/147364994-d6f8db1e-1042-46dc-bfa9-1d810367078e.png)
![unknown](https://user-images.githubusercontent.com/96395022/147364996-711fe1f1-d32c-473a-b0fb-4dc317d78c8e.png)

**Comment by DaxterPancake** [comment]
I'll look into getting this added once christmas is over :)

**Comment by DaxterPancake** [comment]
Closing due to some of these being added, the shoes will be added in the next update. Thank you!
