### ISSUE TITLE
[maps/hayes_autos_body_shop] Hayes Improvements

### ISSUE THREAD

**Issue by staticisdead** [InZidiuZ/legacy-assets-issue-tracker#555]
**Name:**
Who is suggesting this? Please include discord name.
Sasha Black/staticisdead, staticisdead#3979

**Summary:**
Write a short summary of what your suggestion is about.
Lockers moved into the staff room along with adding a changing circle
Moving the material purchasing to the Laptop at the front counter
Replacing the Bean Machine coffee machine with a snack machine
Replacing the bay doors with the same door style as second gear or adding the ability to lock the doors in the up position
Removing invisible desk/shelving from the staff room and from behind the counter along with the items on them
Removing the dumpster on the west side of the building

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Putting the lockers into the staff room and adding a changing circle will give employees a place to feel comfortable to change into their work attire and dress to code
Moving the material purchasing to the laptop up front will not only give space for the lockers in the staff room it also keeps the rp of it locked to a computer for ordering parts
Replacing the coffee machine with a snack helps keep the employee at the shop as well as provides food for customers in need instead of expired coffee that burns their insides :)
Replacing or adjusting the Bay door will help customers to know when employees are there instead of driving by because the doors are closed in their prospective.
Removing the shelving/desk and items floating will make for a more immersive environment
Removing the dumpster will keep it from bugging out and flying though the wall into people sitting on the couch inside

**Comment by RetroCharles** [comment]
I believe the requests above would definitely help with the overall experience at Hayes Auto body for both the employees and customers.

- The accessibility to have a changing circle can help provide staff with a place to quickly change in and out of uniform.
- The personal lockers into staff room and Material purchase shop to the front desk, makes more sense in an "real world" immersion aspect.
- Adjusting the bay doors to stay open when locked is very essential. Having the doors close when inside the shop (even when working on cars) creates an awkward customer experience. Also having the ability to lock the doors in an "open" position can make the shop more appealing during business hours.
- The dumpster needs to be removed on the side of Hayes, bugs out, or constantly getting hit and hitting customers/cars inside the shop.
- Also Snacks > over

:) Hopefully we can see these improvements in city very soon!

**Comment by twooot** [comment]
> Lockers moved into the staff room along with adding a changing circle
Lockers make no sense in the staff room as there is a locker outside where the lockers are right now. I added the clothing spot.

> Moving the material purchasing to the Laptop at the front counter
I moved the material purchase spot

**Comment by RetroCharles** [comment]
Any updates or thoughts about Hayes auto garage being able to be locked in an "open" position. 
Having to stay relatively close to the garages to keep them open, or dealing with NPC walking near opening the garages when trying to close up shop can get a bit frustrating. 

Especially when the garage door closes when mechanics are working on customers cars.

**Comment by CloudTheWolf** [comment]
> Any updates or thoughts about Hayes auto garage being able to be locked in an "open" position. Having to stay relatively close to the garages to keep them open, or dealing with NPC walking near opening the garages when trying to close up shop can get a bit frustrating.
> 
> Especially when the garage door closes when mechanics are working on customers cars.

This is something all mechanic shops would benefit from

**Comment by antihero6713** [comment]
i believe hayes been updated since this. Reopen if you need something else
