### ISSUE TITLE
Aston Martin DB11 issue

### ISSUE THREAD

**Issue by Redaman154** [InZidiuZ/legacy-assets-issue-tracker#556]
**Reporter:**
_Aman_#3510

**Summary:**
I have been facing issues regarding an EDM car named Aston Martin DB11.. This car is in the heroic tier.. The problem is, whenever I get this Specific vehicle out from any garage my game crashes.. I found this on Legacy Bangladesh server and later tested it out in the Test Server as well... I also had some of my friends test this issue along with me in the test server and they also happened to face it.. It seems to have a problem with the car files..

## Additional Information
The car was perfectly fine but recently after an update it seemed to have this issue... Unfortunately I couldnt identify the specific update.. I would suggest maybe looking into the files of this car can solve this problem easily..

**Screenshots:**
![image](https://user-images.githubusercontent.com/90762972/147510742-c437c9fa-7e65-4470-8897-d0daaebe2780.png)

**Notes:**
 I would highly request to fix this as soon as possible its a really good car and everyone loves it..

**Comment by joevapes3** [comment]
We're aware of this issue and or trying to sort out the root cause. The vehicle files itself have not changed for quite some time now, so trying to resolve this issue has been proven difficult. Will update this post when I have more information.

**Comment by joevapes3** [comment]
This issue has been resolved and will be live with the next asset merger to the live server.
