### ISSUE TITLE
[vehicles/casino] McLaren 765 performance suggestion

### ISSUE THREAD

**Issue by nightfoxlive** [InZidiuZ/legacy-assets-issue-tracker#557]
**nightfoxlive#1183**
Who is suggesting this? Please include discord name.

**Mclaren 765 performance suggestion:**
In short i won the mclaren 765 on the casino wheel, obviously amazing moment! but have been slightly disappointed with the speed of it, as i am aware it is one of mclarens best performing super cars with a top speed of around 205 mph, however on a flat this car in game seems to max at around 170 fully upgraded lower than that of my elegy, and lower than quite a few cars in the city, including that aston martin which seems to have a high top end, my suggestion is just a slight performance tweak getting that top speed up more, i know there isnt many in the city, i was thinking that for such a rare car it might be good to have it go close to its actual top speed? maybe there is a reason for it but i thought i would ask and see anyway.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
My suggestion would be good to legacy as i think the few in the city with this car should be able to drive it close to its actual top speed. having mustangs worth 30k speed past on the highway feelsbadman. Also i would like to use it within the racing scene but am inclined to use other cars, worth a lot less that have better performance! thanks

**Comment by joevapes3** [comment]
I will be sure to take a look at this and update you with my findings on the vehicles performance.

**Comment by nightfoxlive** [comment]
thanks

**Comment by vol5** [comment]
You are correct. Ive been driving the car for roughly 3months. There was a pass on it maybe like 2+ weeks ago that improved the handling which is splendid and thank you for that. Like @nightfoxlive said its a feelsbad that its a hypercar and caps out on flat with no bumps and boosts 170. In my personal opinion since its a hyper if I were to give it a top end range its should sit at 190-200 range like the 2 Huracán variants in the city.

**Comment by howiethief** [comment]
I also agree with whats been said up here as one of the Mclaren owners, being such a rare car, worth so much, and getting out top-speeded by cars from all ranges of 50k to 150k doing 165-170 in a mclaren on a straight is lackluster, being such a rare car that isnt publicly available i dont see a huge issue in it going at least 190 on a straight.

**Comment by Nuziatella** [comment]
One thing to note is all vehicles will eventually be slowed down to better suit what the game engine can handle and user latency. So increasing the speed to just reduce it later is the kind of double work that we try avoid.

**Comment by Nuziatella** [comment]
The top speed has been buffed slightly.
