### ISSUE TITLE
[maps/palomino_fib_facility] Adding ATM inside N.O.O.S.E (FIB) Building 

### ISSUE THREAD

**Issue by DC0402** [InZidiuZ/legacy-assets-issue-tracker#558]
**Name:**
DC#0848

**Summary:**
Adding ATM inside N.O.O.S.E (FIB) Building to Withdraw and Deposit money.

**Reason:**
Need to add ATM in N.O.O.S.E (FIB) Building, it is functional right now and all the other Medical centers and PDs have ATM, So it would be great to have ATM in this NOOSE (FIB) building as well.

**Link:**
SUGGESTED PLACE INSIDE NOOSE BUILDING:

![147811857-eabcb28f-6c1a-41f0-82e8-341978ab6261](https://user-images.githubusercontent.com/64458489/147843501-6a1c1a91-1bc0-4f98-af79-0f21c78127ba.png)
![147811848-40c4f82a-7f1b-4961-872b-dbca4233ae38](https://user-images.githubusercontent.com/64458489/147843502-f1bda455-18fc-4bfc-8559-b262895a1274.png)
![147811827-d6136c34-1653-4636-b448-9ebc9adaf940](https://user-images.githubusercontent.com/64458489/147843503-4c1af100-9bba-4392-b8e8-9adc2d480821.png)

Location:

![147811910-014b0e0c-9910-4be4-ad3b-e5fa5a9f1187](https://user-images.githubusercontent.com/64458489/147843544-c5fbd362-1f1e-4061-9559-f414b5799174.png)
![147811865-ecdebdb6-965a-43a8-bd98-0097c75336d3](https://user-images.githubusercontent.com/64458489/147843546-6e0a38f4-513c-4335-b02b-ffa7d248405b.png)

**Comment by Milan345** [comment]
+1

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/153720350-996611f5-6667-4b55-8c4f-e50184b963a4.png)
![image](https://user-images.githubusercontent.com/25892037/153720362-cc22ebc3-c164-4423-bde8-d7cf99d26e16.png)
ATMS have been added
