### ISSUE TITLE
Suggestion: Change the Skylift to not be paper mache 

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/legacy-assets-issue-tracker#559]
**Name:**
Who is suggesting this? Please include discord name.
claystehling#4598
**Summary:**
Write a short summary of what your suggestion is about.
The Skylift is currently made out of paper mache, and it basically breaks at someone kicking it
**Link:**
If there are any links to what you're suggesting, please add them here.
No links
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would allow the helicopter to not die immediately when picking up a vehicle and would allow for more RP there

**Comment by joevapes3** [comment]
After testing I confirmed the skylift was very easy to damage. Buffed the damage resistance overall. Should be good now. This will not be live until the next vehicle asset merge to the liver server.
