### ISSUE TITLE
Suggestion - Bugatti Speed Enhancement

### ISSUE THREAD

**Issue by metalcut274** [InZidiuZ/legacy-assets-issue-tracker#560]
**Name:**
Who is suggesting this? Please include discord name.
metalcut274#8453

**Summary:**
Write a short summary of what your suggestion is about.
Currently, the EDM Bugatti Veyron with an EMS Level 4 engine upgrade hits a max speed of 170 MPH. Would like to suggest the max speed with full engine upgrade be comparable to the other high-end cars.

**Link:**
If there are any links to what you're suggesting, please add them here.
No links :)

**Reason:**
Why would your suggestion be a good addition to Legacy?
The Bugatti Veyron reaches a top speed of just over 250 mph outside of the city. Scaling that to whatever speeds the city has for other vehicles, it would be nice to see an above-average collector car be able to have above-average speeds.

**Comment by joevapes3** [comment]
Tested the Bugatti. It did preform a bit under it's intended target speed and acceleration. Buffed both slightly and you should see an improvement. These changes will be live when the vehicle asset merge happens for the live server. Thanks for bringing this issue to my attention.
