### ISSUE TITLE
Casino Mazda RX7 Handling Improvement

### ISSUE THREAD

**Issue by SirPiff** [InZidiuZ/legacy-assets-issue-tracker#561]
**Name:**
Who is suggesting this? Please include discord name.
Piff#7777
**Summary:**
Write a short summary of what your suggestion is about.
Although this car's overall speed is pretty decent, I do believe that for being a 1 of 2 casino car (currently) it underperforms especially due to its handling.

It's even hard to sell as most people love how it looks, but no one enjoys driving it, if it could drive a little better that'd be wonderful, thank you :)
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would allow for a beautiful car to be driven more often and not be wasting resources being imported when people don't want to drive it due to its handling and potentially allowing for another car to enter the RP racing scene.

**Comment by joevapes3** [comment]
Tested the vehicle and I agree it was performing terribly all around. Overall balanced the handling in every aspect and buffed the damage resistance as well. Will more than likely need more fine tuning but this is a step in the right direction. This change will be live when the next vehicle asset merger happens. Thanks for bringing this to my attention.
