### ISSUE TITLE
Fix the armor for 1996 Ford Escort RS Cosworth

### ISSUE THREAD

**Issue by richuvc** [InZidiuZ/legacy-assets-issue-tracker#562]
**Reporter:**
pLainbLank#0904

**Summary:**
The 1996 Ford Escort RS Cosworth is currently paper mache. I have driven one with 100% armor upgrade and it started smoking after just two minor crashes (eg hitting a lamppost). It is almost impossible to drive it around without going to the mechanic every 5 minutes. I understand why it needed balancing in its performance but the armor currently does not make sense for a car thats famous for being known as a rally car.

**Comment by joevapes3** [comment]
After reviewing the vehicles collision and engine damage it was set to high. I've lowered it now and it should be able to take a few more crashes before breaking now. This will be live with the next asset merge to the live server.
