### ISSUE TITLE
Vehicle make and model for PD

### ISSUE THREAD

**Issue by TheJayNation** [InZidiuZ/legacy-assets-issue-tracker#563]
**Name:**
TheJayNation

**Summary:**
I'd like to see if there is a way to make it to where when PD pulls someone over or is in an 80 to see the make and model of the vehicle on screen.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Make it easier for callouts, not everyone knows make and models of vehicles, especially PDM cars.

**Comment by twooot** [comment]
You almost had it right https://github.com/InZidiuZ/op-framework-issue-tracker/issues
