### ISSUE TITLE
[Maps/] Midnight club repair shop ATM request

### ISSUE THREAD

**Issue by Smolnisno** [InZidiuZ/legacy-assets-issue-tracker#564]
**Name:**
Smol Nismo - smol-nisno#3835
**Summary:**
I would like to suggest an ATM and car wash bay to be added to the Midnight club shop.

ATM near the office entrance where it's easily accessible.
2.Car wash bay near the entrance / exit of the door

**Link:**
I will attach photos of ideal locations where I think the wash bay and the ATM should be located

**Reason:**
These additions would greatly benefit the future owner of the repair shop as customers do not always carry cash on them and would need it to pay the mechanic. If one isn't added it can cause huge issues with people not being able to pay a person for the work.
The car wash bay would be good for customers to get a free complimentary car wash as other repair shops offer it and would be very weird for that shop to be left out.

![Desktop Screenshot 2022 01 08 - 23 49 05 05](https://user-images.githubusercontent.com/94027492/148671102-0ebcde5c-0aba-4488-b4e0-f035f4405277.png)

![Desktop Screenshot 2022 01 08 - 23 41 57 04](https://user-images.githubusercontent.com/94027492/148671103-0ad58ee2-5c68-4fb1-a68b-367396959e37.png)

**Comment by DaxterPancake** [comment]
Closing in favour of #573
