### ISSUE TITLE
[Vehicles:] Mazda RX7 headlight model issue 

### ISSUE THREAD

**Issue by howiethief** [InZidiuZ/legacy-assets-issue-tracker#565]
**Reporter:**
Howie, hoWie#2302

**Summary:**
The pop-up headlights of the RX7 FD is going into the bumper and not up out of the bumper link here (https://www.youtube.com/watch?v=Ja4XRmnS7EA)

## Additional Information

**Screenshots:**
https://www.youtube.com/watch?v=Ja4XRmnS7EA

**Notes:**
For anything else noteworthy.

**Comment by joevapes3** [comment]
I will take a look and see if it's missing any specific flags that allow it's headlights to move properly up and down. If I find any solution I will update this here. Added this to my todo list.

**Comment by joevapes3** [comment]
After further review, the creator who made this model did not include the animation to lift the headlight eyes. I will continue to look for a solution however for now it's deemed unfixable. Closing this thread.
