### ISSUE TITLE
[vehicles-civilian_4:]Fix armor on amg a45

### ISSUE THREAD

**Issue by breadandchicken** [InZidiuZ/legacy-assets-issue-tracker#566]
**Reporter:**
Who is reporting this? Please include discord name.
ImagineLlamas#8814
**Summary:**
Write a summary of what you're experiencing.
After the newest update, the a45 seems to break extremely fast. Even with full armor, one head on collision makes the car start smoking black. a small collision removed 30% of the body health (around 60 mph) a second one (around 100 mph) removed 50% of the engine health and 40% of the body health.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by joevapes3** [comment]
Tested the a45 and it was indeed a paper tiger. I buffed it's damage resistance and it should be good when the next asset update happens on the live server. Thanks for bringing this to my attention.
