### ISSUE TITLE
Portal door to the void at Burgershot

### ISSUE THREAD

**Issue by howiethief** [InZidiuZ/legacy-assets-issue-tracker#567]
**Reporter:**
hoWie#2302

**Summary:**
Theres an open doorway at Burgershot next to the main entrance that just straight into the under-map

## Additional Information
https://youtu.be/XeuUPakUshU

**Screenshots:**
https://prnt.sc/26cm2k0

**Notes:**

**Comment by joevapes3** [comment]
This will require script intervention to correct. Please post this issue here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues
