### ISSUE TITLE
[Peds/] Clothing Suggestion

### ISSUE THREAD

**Issue by ekhowan12** [InZidiuZ/legacy-assets-issue-tracker#568]
**Name:**
Ekhowan 
Discord: alcoholic#9500

**Summary:**
I've a dress request sir. We are going to do a gang RP based on an Anime which is Tokyo Revengers. If you put the dress in the server it will help use to continue our RP properly 

**Link:**
[If there are any links to what you're suggesting, please add them here.](https://www.gta5-mods.com/player/tokyo-manji-gang-uniform-with-pants-mp-male-sp-fivem) 
I don't know is it ok to put links from here.

**Reason:**
 IT will help people in legacy Bangladesh as well as the people who love Anime and wants to do Anime based RP.Its my humble request sir .Please put this 
![s-l400](https://user-images.githubusercontent.com/78637016/149072394-6ee44a51-e4cc-4770-a0fa-03d8a7366d13.jpg)
![s-l1600](https://user-images.githubusercontent.com/78637016/149072398-4f347c12-f7b5-4c82-8ebb-bc4eada00c52.jpg)

**Comment by Afsun1** [comment]
Please add this outfit. This outfit will help us to continue our RP properly.

**Comment by Alamin4242** [comment]
Please let us  do a new kinds of gangs rp..

**Comment by MetaHatter** [comment]
This outfit contains a swastika. Regardless of intent, context, orientation or religious meaning, due to its history, I can almost guarantee it will not be added.

**Comment by ALFAMAS** [comment]
This Could Enhance the Quality

**Comment by DaxterPancake** [comment]
This will NOT be being added due to the swastika. I recommend finding something different.
