### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/legacy-assets-issue-tracker#57]
**Name:**
Who is suggesting this? iGreatWhite#3018

**Summary:**
Adding the Canis Merryweather Mesa to the PDM dealership.

**Link:**
N/A

**Reason:**
Why would your suggestion be a good addition to Legacy?
There is one version of the mesa in the game already but this one has much more customization to it.

**Comment by Karpenkooo** [comment]
Belive it's been added
