### ISSUE TITLE
[vehicle/wheelchair] Make the wheelchair not require fuel by changing vehicle class.

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#570]
**Name:**
CloudTheWolf#0001

**Summary:**

The wheelchair vehicle that EMS provide to patients following ICU/Surgery has a fuel system that does not make sense, since it has no engine. As such I feel this vehicle should not use fuel / battery. (Potentially reduce the top speed as well)
Could it be changed to vehicle class 13 ('Cycles') to accomplish this?

**Link:**
N/A

**Reason:**
This would allow for more enhanced EMS/Injured individual RP and remove limitations on what the patient can do while in a wheelchair.

**Comment by joevapes3** [comment]
So this would require script intervention, as the wheelchair dummy model is based on a vehicle, not a bike. So when you try to change it's class to bike it crashes the asset. I would suggest making a suggestion here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues
