### ISSUE TITLE
[Peds/] Clothing Suggestions

### ISSUE THREAD

**Issue by Enryy** [InZidiuZ/legacy-assets-issue-tracker#571]
Clothes

https://it.gta5-mods.com/player/nba-chain-synix
https://it.gta5-mods.com/player/mp-male-amiri-hat
https://it.gta5-mods.com/player/diamond-cuban-chain-for-mp-male
https://it.gta5-mods.com/player/nfl-buccaneers-tom-brady-custom-desert-digital-camo-jersey
https://it.gta5-mods.com/player/nfl-titans-marcus-mariota-signed-4k-jersey-2016-17-season
https://it.gta5-mods.com/player/nfl-washington-football-team-chase-young-4k-jersey-2020-21
https://it.gta5-mods.com/player/beanies-for-mp-male
https://it.gta5-mods.com/player/fivem-sp-rolled-up-sleeves-flannel-for-mp-male-tykus
https://it.gta5-mods.com/player/nfl-packers-aaron-rodgers-4k-jersey-2020-21-season
https://it.gta5-mods.com/player/fivem-ready-flannels-for-mp-male
https://it.gta5-mods.com/player/nba-jersey-s-city-jersey-edition-mp-male-boolin
https://it.gta5-mods.com/player/nike-air-jordan-3-mp-male
https://it.gta5-mods.com/player/glasses-sunglasses-for-mp-male-female
https://it.gta5-mods.com/player/mp-female-nails
https://it.gta5-mods.com/player/mp-female-louis-vuitton-hoops
https://it.gta5-mods.com/player/twishes-bellybutton-piercing-pack-twishes
https://it.gta5-mods.com/player/bandana-on-the-arm-for-mp-male-and-mp-female
https://it.gta5-mods.com/player/scarf-original-by-offstore-offstore
https://it.gta5-mods.com/player/hat-with-bandana-for-mp-male
https://it.gta5-mods.com/player/colored-gang-masks-for-mp-male
https://it.gta5-mods.com/player/t-shirt-packv1-for-mp-male
https://it.gta5-mods.com/player/cross-chain-mp-male
https://it.gta5-mods.com/player/purple-brand-sagged-jean-sp-mp-male
https://www.gta5-mods.com/player/head-durag
https://www.gta5-mods.com/player/alexander-mcqueen-for-mp
https://www.gta5-mods.com/player/travis-scott-x-air-jordan-4-cactus-jack
https://www.gta5-mods.com/player/drako-s-old-cartiers
https://www.gta5-mods.com/player/custom-king-von-air-force-1
https://www.gta5-mods.com/player/snood-pack-for-mp-male
https://www.gta5-mods.com/player/givenchy-antigona-crossbody-bag-for-mp-male
https://it.gta5-mods.com/player/lv-handbag
https://www.gta5-mods.com/player/trapper-jeans-v1
https://www.gta5-mods.com/player/didiersachs-3-stv2-mp-female
https://www.gta5-mods.com/player/juana-hair-for-mp-female
https://www.gta5-mods.com/player/skull-emoji-chain-male-and-female-mp
https://www.gta5-mods.com/player/yeezy-slides
https://www.gta5-mods.com/player/iced-out-boar-chain-mp-male
https://www.gta5-mods.com/player/carhartt-beanie-for-mp-male
https://www.gta5-mods.com/player/chain-jesus
https://www.gta5-mods.com/player/canada-goose-jacket

**Comment by Enryy** [comment]
https://www.gta5-mods.com/player/jackets-pack
https://www.gta5-mods.com/player/moncler-vest
https://www.gta5-mods.com/player/drako-s-old-cartiers
https://it.gta5-mods.com/player/vintage-track-jackets
https://it.gta5-mods.com/player/tied-tank-top-for-mp-female
https://it.gta5-mods.com/player/clothes-for-mp-female
https://it.gta5-mods.com/player/sweater-for-mp-female-jaagoda
https://it.gta5-mods.com/player/female-top-crop
https://it.gta5-mods.com/player/sweat-dress-for-mp-female
https://it.gta5-mods.com/player/buckle-shorts-for-mp-female
https://it.gta5-mods.com/player/gucci-pants-for-female-sp-fivem
https://it.gta5-mods.com/player/neon-pants
https://it.gta5-mods.com/player/nike-air-jordan-3-mp-male
https://it.gta5-mods.com/player/glasses-sunglasses-for-mp-male-female
https://it.gta5-mods.com/player/mp-female-nails
https://it.gta5-mods.com/player/mp-female-louis-vuitton-hoops
https://it.gta5-mods.com/player/twishes-bellybutton-piercing-pack-twishes
https://it.gta5-mods.com/player/bandana-on-the-arm-for-mp-male-and-mp-female
https://it.gta5-mods.com/player/scarf-original-by-offstore-offstore
https://www.gta5-mods.com/player/canada-goose-jacket

**Comment by Enryy** [comment]
https://it.gta5-mods.com/player/mp-male-dreads-braids-pack
https://it.gta5-mods.com/player/mp-male-palm-angels-track-jacket
https://www.gta5-mods.com/player/travis-scott-x-air-jordan-4-cactus-jack
https://www.gta5-mods.com/player/snood-pack-for-mp-male
https://www.gta5-mods.com/player/givenchy-antigona-crossbody-bag-for-mp-male

**Comment by DaxterPancake** [comment]
These have been reviewed and some will potentially be added in the next clothing build.
