### ISSUE TITLE
[maps/?] Grocery Store In Paleto 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/legacy-assets-issue-tracker#572]
**Name:**
𝒜𝓃𝑔𝑒𝓁#9999

**Summary:**
It's very hard to get food from Paleto, I mean sometimes we have to travel from paleto to the grocery store. 
**Link:**
https://www.gta5-mods.com/maps/paleto-liquor-mlo-sp-fivem
https://www.gta5-mods.com/maps/paleto-247-store-mlo-sp-fivem

**Reason:**
This would make our RP better. Being part of SOL In my Sub, I feel like it will make our commute much easier.

**Comment by claymstehling** [comment]
Yes, please I would love to be able to get food up in Paleto without having to make the trek out of it

**Comment by Pasha3744** [comment]
@joevapes3 any update about this one?

**Comment by antihero6713** [comment]
this has been added closing
