### ISSUE TITLE
[Maps/] Suggestion: Adding an ATM and CarWash station to the Midnight Club / Tuner Shop (repair shop 9)

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/legacy-assets-issue-tracker#573]
**Name:**
ItzBrittanyBitxh#8587  - Dakota Carter / Brittany

**Summary:**
Adding an ATM and CarWash station to the Midnight Club / Tuner Shop (repair shop 9)

**Link:**

ATM (for convince sake)- https://imgur.com/a/ySXaXoD

Adding a carwash station. This is aimed to be more of a "Detailing zone" - The shop is focused more around tuning and the finer RP details, not as much on mechanics ect. So workers will use emotes as such as /e Clean to polish up a vehicle and then finish it off by actually using the cleaning machine to clean the car of visible dirt.

As this is going to be used as a "zone" to pull up to, I have added an image of where this could be, which would require the car lift shown in this image to be removed, so the machine can be added. - https://imgur.com/a/k2Oeq4j

**Reason:**

This business is owned in the main server as of a two days ago and after being open, these are the two main concerns for the business as a whole, just some user friendly additions that could make the shop and RP flow better as a whole 😄

**Comment by joevapes3** [comment]
The physical ATM is asset related so I'll keep this thread here, but the carwash and the polish emote request would need to be made in the framework github located here:  https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by Nuziatella** [comment]
This will be added in a future update

**Comment by antihero6713** [comment]
updated and done
