### ISSUE TITLE
Suggestion: PDM and BCSO PD

### ISSUE THREAD

**Issue by Mugdha57** [InZidiuZ/legacy-assets-issue-tracker#574]
**Name:**
Who is suggesting this? Please include discord name.
Meer Mugdha#2444

**Summary:**
Write a short summary of what your suggestion is about.
Suggesting this 2 new interior for both pdm and paleto pd. 

**Link:**
If there are any links to what you're suggesting, please add them here.

https://fivem.gabzv.com/package/4873121 (PDM)
https://fivem.gabzv.com/package/4838056 (PD)

**Reason:**
Why would your suggestion be a good addition to Legacy?

this 2 new interior will help both pdm and pd to do some nice rp and it is always exciting to have new things which is better than the one we are currently having in our legacy servers.

**Comment by T4NZ1M** [comment]
Interiors are sick! The addition of these would be great!

**Comment by DC0402** [comment]
Great idea

**Comment by jokester00** [comment]
The addition of these would be great! sexy PDM <3

**Comment by DaxterPancake** [comment]
Unfortunely we cannot add these due to how this creator locks his content making it impossible to optimize if we needed to. Along with it being locked to only specific keys, etc. Sorry about that.
