### ISSUE TITLE
Gambetti's Whitelisted Attire

### ISSUE THREAD

**Issue by AnfewMac** [InZidiuZ/legacy-assets-issue-tracker#576]
**Name:**
Anfew_Mac#6588

**Summary:**
Since being apart of the Gambetti Italian family we really do not have anything that is unique to just our group. There are many MC's and gangs that have their own personal outfit associated to their group. It has been quite a long time of us contemplating on some certain items we would want to see implemented as far as clothing goes. 

**Link:**
Here are a few links we had seen that we thought would help show our Italian Mafia colors more.

_________________________________________________________________________________________________________________
We were looking at this mainly because of the rose. If we were able to make this into more of a pinstripe suit we think this would be perfect with the rose.

https://www.gta5-mods.com/player/bestman-suit-mp-male-sp-fivem
_________________________________________________________________________________________________________________
Here is an edit we did as well for our own tactical vest as well. 

https://cdn.discordapp.com/attachments/923449884399501312/933835632738988062/Gambetti_Vest_Front.png
![Gambetti Vest Front](https://user-images.githubusercontent.com/93451139/150428846-15447ab7-718e-4861-b77d-6ea96faac766.png)

https://cdn.discordapp.com/attachments/923449884399501312/933835633162584184/Gambetti_Vest.png
_
![Gambetti Vest](https://user-images.githubusercontent.com/93451139/150428895-4283c928-16bc-429b-b83b-540e2f143780.png)

![Gambetti Logo2](https://user-images.githubusercontent.com/93451139/150428963-6c701711-7a0e-4700-bf6e-b58d2893dd94.png)
![Gambetti Logo](https://user-images.githubusercontent.com/93451139/150428991-29837df1-22bd-4581-a583-24dd0c5781b8.png)

_______________________________________________________________________________________________________________
We really like the idea of having more of an LA Noir style outfits that not only men can wear but females in our group could wear as well. I looked for a mods pack myself to assist but to no avail I could not find any. I might be able to find a guy to help create some though. Below if you scroll through the photos you can see some Men and Women Mafia style clothing which would be a great addition for our group. Probably more LA Noir style outfits for both Women and Male in the city. 

There is a pinstripe option for women skirts linked below. How about something for the ladies of our group? :)
https://socialclub.rockstargames.com/photo/gtav/tx9oyKoEZUG54e_BGpQt3A

There is a Valentines Day Massacre pack for GTA5 that should show some outfits as well. 
https://gta.fandom.com/wiki/Valentine%27s_Day_Massacre_Special#Gallery

![LA Noir Woman](https://user-images.githubusercontent.com/93451139/150429760-103bd96c-db49-46bf-8115-552fabc7e9b3.png)

**Reason:**
I think we have been doing really great with our Roleplay (Ravioli-Pasta as we call it) and we are just trying to show more of who we are as an Italian family. We want to have more of an unique look for our group.  Just like the Italian Mafia we have our hands in many things and have many connections throughout the city. It would be nice to be able to have people know just by looking at us who we are kind of like how other groups are in the city. More times than none we get told "Oh you are a Gambetti? We thought you just liked wearing suits?" Besides a Gray mask we really don't have much for unique clothing within our group. We would really like to change that. This is something that can assist with our group affiliation within the city.

![20211220005045_1](https://user-images.githubusercontent.com/93451139/150430093-571a6584-ad69-4c69-80be-24424dfa5883.jpg)

**Comment by AnitaSh0wer** [comment]
Representation is huge part of Legacy. These ideas will help further the diversity in the city and allow for even more quality Ravioli Pasta!

**Comment by MetaHatter** [comment]
To proceed with this... we must first have all of your gabagool

**Comment by AnfewMac** [comment]
> To proceed with this... we must first have all of your gabagool

OOOOOF.... How about half? lol

**Comment by DabberDooo** [comment]
looks/represents us great

**Comment by DaxterPancake** [comment]
Closing due armor and male suit being added.
