### ISSUE TITLE
Update our Phone -Suggestion

### ISSUE THREAD

**Issue by ekhowan12** [InZidiuZ/legacy-assets-issue-tracker#577]
**Name:**
NATSU(Discord-alcoholic#9500)

**Summary:**
As we are playing in OP_FW for a long time I think most of the people face this. When someone send you text in your phone or give you a call there should be a option of saving the number from there. IRL we can do this and If we get this it will be easier

**Link:**
N/A

**Reason:**
It will make the people's life easy. Currently if someone wants to save a number they need to memories then save. If we get an update based on this people will get to use a new way of in-game phone using.Thank you

**Comment by Enryy** [comment]
Let's say that the phone needs to be updated a little bit on everything, there are a lot of missing features very important for us gamers that create quite a frustration like the fact that there is no way to take pictures to send on twitter/private messages, or like the fact that there is no SIM system and you are always forced to keep the phone number you always had without the possibility to change it, there is no way to make group calls or things like that... I think it's time to start working on a new phone with new features

**Comment by DaxterPancake** [comment]
This is the wrong github for this kind of suggestion.

Please remake this [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
