### ISSUE TITLE
[Vehicles-Civilian_4] Handling suggestion: 1996 Harley Davidson Softail Springer Performance issue

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/legacy-assets-issue-tracker#578]
**Reporter:**
Who is reporting this? Please include discord name.
Frankenstein#8200

**Summary:**
Write a summary of what you're experiencing.

The *1996 Harley Davidson Softail Springer* bike bounces even in flat road. If there is a very small road bump it jumps in a very unusual way comparing other bikes.

The brake is very bad. Feels like a truck. Even after upgrading the brake, it is not that good. The brake definitely needs some improvement.

**Reason**

Its a very nice bike but the performance is not up to the mark. The bouncing and braking issue is making the driving experience bad. An improvement is needed which will make the experience much better.

**Comment by joevapes3** [comment]
Thanks for bringing this to my attention, I will take a look at this and update this thread once I have done so.

**Comment by joevapes3** [comment]
Went over it's handling and balanced it overall. Changes should be live when the next asset merger goes live.
