### ISSUE TITLE
[Vehicles-Civlilan_4] Model issue: Lowering amount of dirt on the EDM Aventador 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/legacy-assets-issue-tracker#579]
**Name:**
Who is suggesting this? Please include discord name.
Ashraf#9999

**Summary:**

Currently, the EDM Aventador gets way too dirty so quickly that almost any paint job you put on it gets completely re-done to a paint job made of dirt, to make your paint job slightly shine through you'd have to use a Matte colour, even then it's kinda bad.
**Link:**
If there are any links to what you're suggesting, please add them here.
N/A
**Reason:**
Why would your suggestion be a good addition to Legacy?
Just a QoL thing so owners of it don't have to wash it every 5min just to see their paint job c:

**Comment by joevapes3** [comment]
I'll take a look at lowering the dirt mapping opacity to see reduce the dirt on the vehicle. I will update this thread once I've looked at it. Thanks for bringing this to may attention.

**Comment by joevapes3** [comment]
So I was successfully able to reduce the dirt mapping on this vehicle and you should notice a difference once the next vehicle asset merge is completed. Thanks for bringing this to my attention.
