### ISSUE TITLE
Nissan GTR Liberty Walk Kit

### ISSUE THREAD

**Issue by 2001lol** [InZidiuZ/legacy-assets-issue-tracker#58]
**Name:**
Who is suggesting this? Please include discord name. Niko Discord name: 2001

**Summary:**
Write a short summary of what your suggestion is about.
Adding Liberty Walk kit to the GTR. It seemed like there are 0 mods, and it looks like the Nismo Kit would be coming out. For an expensive car with loads of customization I think it would be a nice asset.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would add variety to the car so there is not only one set of customization and everyone drives the same thing around. As before stated in previous suggestions, It would enhance the idea of different styles

**Comment by SATIN187** [comment]
The liberty walk kits is going to be added. you can check out the #github section in discord

**Comment by 2001lol** [comment]
Oh didn't see it until now, thanks. I'll close this thread now.
