### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/legacy-assets-issue-tracker#580]
**Reporter:**
Gody. Gody#4788

**Summary:**
Some EMS user labels show up as `Unknown: departmentLabel`

## Additional Information

**Screenshots:**
https://i.imgur.com/Ae1VVtW.png

**Notes:**
I am not sure if this is their category, but they are listed under Lieutenant (Supervisor) Although this doesn't affect some others in this department

**Comment by joevapes3** [comment]
This github is asset releated, you're going to want to post this issue here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by GodyFromDiscord** [comment]
> This github is asset releated, you're going to want to post this issue here cause it's script related: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

Will do when I can, thank you.
