### ISSUE TITLE
[Vehicles-civilian_4] Model Issue: Dirt mapping bug

### ISSUE THREAD

**Issue by nightfoxlive** [InZidiuZ/legacy-assets-issue-tracker#581]
**Name:**
nightfoxlive#1183

**Summary:**
dirt on the mclaren instead of showing up just changes the colour of the car lighter, a similar thing happens to the golf mk4 both of which i own

**Link:**
![03c253ac-0af1-40f7-a9ff-ad6fdab12e60](https://user-images.githubusercontent.com/96830741/151196513-a43fe22b-74d2-4930-abb8-b1a5db5130eb.png)

![1d5fa393-72b9-4b80-8e6b-3e7d5ff59cfb](https://user-images.githubusercontent.com/96830741/151196554-70be72e1-ec5f-4b20-abd4-c2dadc95e633.png)

**Reason:** 

Why would your suggestion be a good addition to Legacy?
quality of life change, also more realistic mud on the car similar to other cars like the elegy where it looks dirty. im broke from car washes and cleaning kits lol

**Comment by joevapes3** [comment]
I'll take a look at the dirt mapping and update this thread when it's addressed. Thanks for bringing this to my attention.

**Comment by Nuziatella** [comment]
This has been resolved.
