### ISSUE TITLE
[Vehicles-Civilian_4] Model Issue: AMG C63 Windows not tinting

### ISSUE THREAD

**Issue by richuvc** [InZidiuZ/legacy-assets-issue-tracker#582]
**Reporter:**
pLainbLank - DISCORD

**Summary:**
Mercedes AMG C63 front windows are not getting tinted when you modify it in LS customs but the back windows are. It looks weird

## Additional Information

**Screenshots:**
![20220128132359_1](https://user-images.githubusercontent.com/88080705/151522259-1c0e6f53-4f19-44b6-af8f-71c07588f366.jpg)

**Comment by joevapes3** [comment]
Added this to my to do list and will get to it soon. Thanks for bringing this to my attention, and I will update this thread when it's fixed..

**Comment by joevapes3** [comment]
Window tint issue has been corrected. Will be live when asset merge is done.
