### ISSUE TITLE
Add Junkers JU-52

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/legacy-assets-issue-tracker#583]
**Name:**
TheOneLizard#4196

**Summary:**
Add the plane below to the roster of available planes.

**Link:**
[https://www.gta5-mods.com/vehicles/junkers-ju-52-3m-add-on](url)

**Reason:**
- it's a plane with relevance in aviation history, so it would be a cool plane to have at events
- one of a kind
- ideal for parachute drops, as peds don't ram into wings or engines when jumping out
- it's just a damn cool plane, please add :3

**Comment by joevapes3** [comment]
We may or may not add more addon plane assets in the future, however at this time we're not going to be. I will note this suggestion down though and consider if and when we decide they maybe needed. Thanks for the suggestion.
