### ISSUE TITLE
About SOL Edm bike

### ISSUE THREAD

**Issue by Itachi096** [InZidiuZ/legacy-assets-issue-tracker#584]
**Name:**
ITACHI-O !#4484

**Summary:**
suggestion is about to add again the SOL western bike to EDM

**Link:**
https://i.imgur.com/ogksXDV.png

**Reason:**
Basically, After the New EDM Update, there is no good bike like this one. We want this bike Because this bike belongs to the sol club. We want to increase our Club In Rp. As a biker club we need this bike for our club members. I think it's a good symbol of sons of legacy Club. We want it so Badly at the subdivision. Our Bangladesh subdivision Recently got Wiped. It would be great if we get this back again. So Please think about our subdivision to bring it back again. If you dont want to re-add the old bikes again then please add something new to the EDM for SOL.

**Comment by Pasha3744** [comment]
Yeah Bring it back again

**Comment by Jeshu885** [comment]
yeah bring it back again

**Comment by werewiki** [comment]
upvoted

**Comment by SpiderCord** [comment]
Please bring back

**Comment by SiFAT-07** [comment]
👍

**Comment by joevapes3** [comment]
The bike itself gone anywhere, and is still in the EDM rotation. However with the current release of the new EDM pack, we only cycled the new pack for the last few rotations. This next rotation goes back to the normal loop with every vehicle again. You'll have to be patient with the rotation for the vehicle you want but it will come back soon enough.

**Comment by SirPiff** [comment]
With that, would you consider an additional slot per tier? I know that's more script related though, simply of the amount of cars in rotation, people might not see the car they want for many months, that'd help. 

Idk if possible but making "gang" related vehicles with their specific liveries into PDM so it's always available for them blacklisted, which would also free up some slots from randomisation.

**Comment by joevapes3** [comment]
To Answer SirPiff this request regardless is script related, as that is how the edm assets are rotated, so not much that I am able to do here. Also we do not have the ability to change PDM liveries as those are vanilla assets and we don't stream them. 

As for now so that OP is aware, that all the vehicles will be back in the normal rotation with this upcoming update. So there is a chance that the vehicle your looking for may show up then. Hopefully the odds are in your favor.
