### ISSUE TITLE
[peds/*] PDM Logo in Decals

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/legacy-assets-issue-tracker#585]
**Name:**
Who is suggesting this? Please include discord name.
Frankenstein#8200

**Summary:**
Write a short summary of what your suggestion is about.

Add PDM Logo in Decals.

**Reason:**
Why would your suggestion be a good addition to Legacy?

As a PDM employee we often wear suit at workplace. If we had a decals with PDM logo we could use it with our suit. With the help of that it will be easier to recognize a PDM employee.

**Comment by MetaHatter** [comment]
@rakibulhasan456 Can you give us an example decal that fits your suit without clipping? (include screenshot if possible)

**Comment by rakibulhasan456** [comment]
@MetaHatter 

It would be great to get a PDM Badge just like the USA Flag Badge on the chest, simple and easily recognizable. There are two different suit fits. The USA Flag badge doesn't match well with every suit. (See the picture 1 & 2).

![image](https://user-images.githubusercontent.com/88003289/183051587-dd84fbea-7048-4d6a-a6c7-7d0ed1dd62f1.png)

So, if it's possible to give two different PDM logo badges, one like the USA badge and other to fit with the suit, it would be great. Picture 3 & 4 would help you to understand, I think .

![image](https://user-images.githubusercontent.com/88003289/183053180-5cd0e991-5827-4112-8b6d-19643bbef8c3.png)

**Comment by rakibulhasan456** [comment]
@DaxterPancake @MetaHatter Sorry for the mention, but any update on this thing?

**Comment by MetaHatter** [comment]
This is still on my to do list.

**Comment by rakibulhasan456** [comment]
Thanks! Would love to see it soon.

**Comment by MetaHatter** [comment]
This is a 3D modelled asset and requires a dedicated asset slot.  I won't be modelling an asset for a single business.  

If it is acceptable to you, since we have texture space, we can look into adding the logo in that location to one of the suits.  If you provide us with a slot number of suit you would like, we can look to add it.

**Comment by DaxterPancake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PDM Decal/Pin](https://trello.com/c/b6kJ8HAW/57-pdm-decal-pin)

**Comment by rakibulhasan456** [comment]
@MetaHatter 

We use this suit (**Shirt Slot ID: 108**) in our PDM. We have different color/texture for every rank.

![image](https://media.discordapp.net/attachments/849002854965706833/1013884900933370009/Shirt_No_108.jpg?width=421&height=479)

The suit has 8 different texture. I hope adding the logo in the slot will work for every texture. If that does, it'll help us a lot.

![image](https://user-images.githubusercontent.com/88003289/187278516-23964ceb-04d4-4a35-ad6a-2ec3613532e6.png)

**Comment by DaxterPancake** [comment]
Closing due to not being needed at this time. I will potentially revisit this at a later time if I believe PDM workers need further identification.
