### ISSUE TITLE
[maps/?] Missing Section 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#586]
**Reporter:**
CloudTheWolf#0001

**Summary:**
There is a messing section of the fountain floor need pillbox

## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/657208517748326425/942808410812973076/unknown.png

**Notes:**
For anything else noteworthy.

**Comment by antihero6713** [comment]
probably because of the build we are using.  Not gonna fix it at this point. unless it get abused
