### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ThatGuyJayXD** [InZidiuZ/legacy-assets-issue-tracker#587]
**Reporter:**
Who is reporting this? Please include discord name.
Jay - Jay#5902

**Summary:**
Write a summary of what you're experiencing.

- so we were planning on buying a block of houses but we noticed that one of them has a gate that does not open and it is located on Mad wayne thunder drive 4. we were hoping to have the gate either unlocked/ replaced with one that swings open or slides or just have it taken away completely if possible

- we were also hoping that the garage would be moved to within the gates once removed down towards the actual house itself
## Additional Information

**Screenshots:**
https://media.discordapp.net/attachments/919609298282217552/943551461500018778/unknown.png?width=1324&height=676

**Notes:**
this was for a potential block purchase but regardless of whether or not we get it the house can still be owned and would be a nice change IMO

**Comment by antihero6713** [comment]
art part is done

**Comment by DaxterPancake** [comment]
Closing due to the 'moving of the garage' not being an asset issue. If this is still an issue please create an issue [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
