### ISSUE TITLE
Range Rover Evoke Handling and seats

### ISSUE THREAD

**Issue by VintageSlam** [InZidiuZ/legacy-assets-issue-tracker#589]
**Name:**
vinnessa salamari#3184

**Summary:**
When driving around in the Range rover Evoke casino car it feels like you are driving on ice all the time. If it would be possible would there be a way to maybe grip up the tires a little bit more to make the car more able to turn. Also the Evoke has space to sit 4 people. ( 2 at the front and 2 at the rear) but currently only holds 1 driver and 1 passenger. If we could get to fill the 2 back seats that would be great!

**Reason:**
I feel this addition would want said owners to be more inclined to drive these cars around and being able to share said experience with 3 friends instead of 1

**Comment by joevapes3** [comment]
Investigated this issue and confirmed the vehicle was driving rather irregularly. Redid the handling meta and it should feel quite a bit better once the next live server asset merge is done. Closing this issue.
