### ISSUE TITLE
Toyota Supra MKIV Underglow bug

### ISSUE THREAD

**Issue by Shifty123** [InZidiuZ/legacy-assets-issue-tracker#59]
**Reporter:**
Shifty. Shifty #4167

**Summary:**
If you lower the suspension of the Supra to the lowest setting and apply an underglow, the car will be too low and when turning or going over bumps the lights will disappear into the ground.

**Notes:**
Not sure if fixable but it would be nice to have underglow on it, the glitching turns me away for sure

**Comment by Karpenkooo** [comment]
Hey,

Can't really do much about this as it's an issue from the mod author. Unless you'd be fine with raising the car on the 4th Suspension Lvl.

_Karpenko_

_**OP-FW Asset Dev**_
