### ISSUE TITLE
[maps/?] Bubbas Steakhouse

### ISSUE THREAD

**Issue by VintageSlam** [InZidiuZ/legacy-assets-issue-tracker#590]
**Name:**
vinnessa salamari#3184

**Summary:**
At the Moment Bubbas steakhouse is in a state of limbo it is quite hard to find the location and getting in contact with employees can sometimes be very difficult. Here are some changes and improvements I feel would improve the Bubbas Steakhouse to make it more accessible to the public aswell as add appeal to the Paleto Bay area making people want to travel up north.

Things we want added :

- Logo change

- GPS Location

- Contact on phonebook

- New cooking system

- Clothing spot / locker /ATM Additions

---------------------------------------------------------------------------------------------------------------------------------------------------

-Logo Change for the Bubbas steakhouse

We are in love with the location of where Bubbas are but when customers travel up north they are met with a little bit of confusion. At the moment the Bubbas steakhouse has the biker SOL Logo around the steakhouse. We would like it if the logos around the steakhouse were changed to our iconic logo giving the steakhouse more identity that it is Bubbas!

https://media.discordapp.net/attachments/884969561793921127/945791655422873640/bofas2.0.png?width=810&height=810

-Adding a GPS blip on the mini map

To furthermore solidify Bubbas we would love it if we could get a blip on the mini map where Bubbas is located. This can make finding the steakhouse a lot easier as there would be a blip helping potential customers and guests locate where we are established

https://media.discordapp.net/attachments/884969561793921127/945791284940013598/Screenshot_2022-02-22_161632.png?width=810&height=795

-Adding Bubbas as a quick contact

At Bubbas we also rely heavily on deliveries to keep the business afloat. At the moment it is hard for customers to get in contact with us as they have to type in each staff members phone number depending who is clocked in to order a delivery. We feel if we had a Quick line it would not only make every parties life easier to get in contact to order food but also incentivise new customers to text the line and experience Bubbas for the first time!

-potential crafting system for steaks (cooked meat)

A big issue for us at the moment is cooking the raw meat to cooked meat. The process is not only very time consuming but also includes major problems like meat not cooking, meat disappearing, grills not working, charcoal getting missing etc. We feel like a grill or oven at the steakhouse similar to the current one at Burger Shot would streamline the cooking process making it a more smooth experience and also adding more Roleplay allowing us to actively cook steaks in front of customers. 

-Adding a Clothing spot, Locker and ATM to Bubbas Steakhouse

As we do not see this as a major issue it would be a nice quality of life change to make changing into work attire a quicker more swift process. 

We would also like to see an addition of a Locker being added to the steakhouse. This is because at the moment we do have a lot of meat and drinks on us and in cars. an addition of a locker would make life a lot easier for the staff as they don't have to worry about running back and fourth outside to collect items for the customer. Also have the worry of people breaking into cars trying to steal product when it gets busy. 

The third addition we would like is that an ATM be added to the steakhouse. This is because customers sometimes do not have to necessary funds to purchase our products forcing them to leave the establishment trying to find an ATM. If there was one inside the steakhouse Customers would quickly be able to pull out funds if needs be.

---------------------------------------------------------------------------------------------------------------------------------------------------

-Summary

Overall I feel like these changes and additions would increase quality of life aswell as increase roleplay potential in Paleto. As we understand this could be quite a task to handle all at once so we are not looking for a huge change in one go. This is our vision of what we would love to see come to Legacy in the near future.

![bofas2 0](https://user-images.githubusercontent.com/100077900/155221311-a8699d1c-e996-4ab3-8441-57031dfc285f.png)
![Screenshot_2022-02-22_161632](https://user-images.githubusercontent.com/100077900/155221321-720563c5-7a30-4839-96e7-828fd0363432.png)

**Comment by antihero6713** [comment]
closed. Reopen if this is still wanted.
