### ISSUE TITLE
vehicles/vehicles-civilian_2: G Wagon Handling Suggestion

### ISSUE THREAD

**Issue by Fausta2** [InZidiuZ/legacy-assets-issue-tracker#591]
Fausta#6378

The G Wagon has very bad wheel spin when it starts and it can not even go around a corner without slipping at 50mp/h I was wondering if it could get looked at so it will not spin out as much and in the back there is visible 3 seats so maybe the G wagon could be a 5 seater to

**Comment by joevapes3** [comment]
Thanks for bringing this to my attention, I'll take a look at this and update this thread with any findings/changes.

**Comment by joevapes3** [comment]
After reviewing the vehicle handling meta, it was indeed in a bad state as far as turning was concerned. I updated the values to give a much more pleasurable driving experience. These changes will go live when the next asset update is merged with the live server.
