### ISSUE TITLE
Mustange Shelby GT changes - Casino Car

### ISSUE THREAD

**Issue by MAGiCxPOTATOE** [InZidiuZ/legacy-assets-issue-tracker#592]
**Name:**
City - Dick Little, Discord - XxFaZe_MAGiC-x_POTATOExX360#4115

**Summary:**
The Mustang(1 of 3 I think now) is a great looking car, but sometimes it is undrivable because of the way it behaves.

One thing is that it is a very 'boaty' car, whenever you are a taking a corner no matter what speed the car sometimes begins to lift up to a point where it is driving on two wheels. This is on flat city roads as well, it happens when you try to turn, if you break at the wrong time or lock the wheel it basically flips on its own.

Another thing is the suspension, it too soft - this may be the cause of the flipping but am not to sure how it all works so don't want to assume. Whenever you are driving up an inclined road the bottom scrapes the ground.  Another thing it causes is e.g. if you are on the highway and try to switch lane the body goes the complete opposite way of the wheels to the point where it spins out or again begins to flip.

**Link:**
No links but can provide if needed.

**Reason:**
I know muscle cars shouldn't stick to the floor or anything but these issues get in the way even when cruising around.
I've driven quite a few of these types of cars and none of them seem to behave this way, and the few that do aren't this extreme.
Most casino cars seem to be pretty solid in the areas they specialise in but the Mustang Shelby GT isn't anything to talk about apart from the name and look.

**Comment by joevapes3** [comment]
Can you specify which Shelby it is? The one form the Casino or the one from EDM?

**Comment by MAGiCxPOTATOE** [comment]
It's the mustang from casino

**Comment by joevapes3** [comment]
This vehicle did not have it's own independent handling meta. I now gave it it's own handling meta and updated it's handling values to be balanced with the other vehicles in it's class. Should feel a lot better. Changes will be live when the next asset merger is done with the live server.
