### ISSUE TITLE
vehicles/vehicle-civilian_2: C7 Corvette suggestion

### ISSUE THREAD

**Issue by Griknasty** [InZidiuZ/legacy-assets-issue-tracker#593]
**Name:**
Griknasty#7222

**Summary:**
The Corvette C7 Stingray does not go above 150mph without the assistance of added momentum or gravity. I think it should go a bit faster again, maybe a top speed of 175-185 mph without the assistance of added momentum or gravity like most other vehicles.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
A lot of people own corvettes and/or are interested in getting them but they do not want to drive them because they know about its top speed, so we see very few of them in the city. Comparing the C7 corvettes top speed to other vehicles in the city becomes weird because things like a Warrener which is an old russian compact sedan able to go 20-30 mph over it with less upgrades and tuning. Just my thoughts, I don't want it to be a broken car but it would be nice to see those sexy C7's being driven and raced again.

**Comment by Joezombie93** [comment]
100% agree!

**Comment by joevapes3** [comment]
Check the c7's top speed and it was indeed lacking. I adjusted it's handling meta and it is now much more comparable to other vehicles in it's class. Closing this out, and this update should be live when the next asset merger is with the live server.
