### ISSUE TITLE
O'Malley's Irish Pub Updates

### ISSUE THREAD

**Issue by kschreck0105** [InZidiuZ/legacy-assets-issue-tracker#594]
**Name:**
Rogue205#4921

**Summary:**
1. Remove the Local Bartender from the Pub
2.  Add an ATM under The Temple Pub Picture on the back wall

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
1. The local bartender is in the way of employees making drinks and comes back way too fast when we try and move her out of the way. 
2. Would add convenience to the guests to be able to get money without having to leave the pub. 
![136302315-c7d339c7-c0c9-4a5d-9db0-a3ef462884cd](https://user-images.githubusercontent.com/68434249/155831495-833c14b0-cf2c-47d0-85fe-853e30e78884.png)

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/161475875-55bf0fa7-554f-45ab-a285-4dc194245062.png)
got that twoot or ben might need to look at the ped spawning there

**Comment by DaxterPancake** [comment]
Closing due to ATM being added. If the ped spawning is still an issue you will need to create an issue on the correct github which can be found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
