### ISSUE TITLE
View Bug

### ISSUE THREAD

**Issue by Darskus** [InZidiuZ/legacy-assets-issue-tracker#596]
https://drive.google.com/file/d/1f5dVdrDnExwrppaO0f8yngNhOVOk8SCT/view?usp=sharing

Scuff while crouching and laying down
this is super disorienting also I forgot to fix my sound woops. but that right there is the scuff in a nuttshell. this only began to happen when we decided to add the feature to change your camera view while laying down or crouching.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this issue. Use the framework-related one instead.
