### ISSUE TITLE
[maps/city_hall] City Hall

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/legacy-assets-issue-tracker#599]
**Name:**
Matt 
Matt;)#7784

**Summary:**
A few people including myself would like one of the city halls, which used briefly before being removed, to be added back to Legacy. This was the city hall with a 2-floor courtroom, offices, etc.

**Link:**
Sadly I do not have a link currently but I will attempt to find this interior online so it’s easy to understand what I’m talking about. 

**Reason:**
It was a magnificent interior and one that would be used frequently by governments on all subdivisions, especially international. The addition of the courtroom at MRPD was welcomed, but it’s small and personally it’s a last resort for a quick, open and shut court case due to its size and location.

**Comment by antihero6713** [comment]
I will take a look at this again at some point

**Comment by DaxterPancake** [comment]
There was issues with the city hall regarding collisions. Not only that but it was barely used and with the recent addition of the new hospital it would turn that area into a lag fest. Is there any alternative you would be interested in?

**Comment by Lunabelle666** [comment]
I have a lot of alternatives that I have researched that I would be willing to purchase for the city if allowed. I will post the links below.

1. https://www.youtube.com/watch?v=4yn5C-qEV38
2. https://www.youtube.com/watch?v=mJpq9t6zI1U
3. https://www.youtube.com/watch?v=sJmPZgH0Ot8

Whilst there is more, these are the 3 locations that I have found that are not opposite Mount Zonah. I personally am not a fan of the one in the southside and have a large preference to either the one in Legion or an updated interior to our current courthouse interior which I believe is the first link.

**Comment by mxttx** [comment]
The number 1 (https://www.youtube.com/watch?v=4yn5C-qEV38) is very sexy indeed. The meeting table with a logo for SCOTUS stands out the most and it lines up with some "legislative body" that myself and some of the DOJ/State/PD have been talking about.
It would obviously require a reposition of the courthouse shop (for IDs) and the courthouse gavel, but it is amazing.

**Comment by Lunabelle666** [comment]
Is there a particular way to know what maps are escrow or not? As I am willing to put as much time and energy as needed into finding a map that would work for what the city wants and needs.

**Comment by DaxterPancake** [comment]
> [Gta](https://www.gta5-mods.com/) is really only one I know where free stuff is released. The escrow stuff is new and usually runs through tebex.

Map 1 seems to be purchased from the creator in discord. Would this still be locked behind Escrow despite a direct purchase?

**Comment by GodyFromDiscord** [comment]
> > [Gta](https://www.gta5-mods.com/) is really only one I know where free stuff is released. The escrow stuff is new and usually runs through tebex.
> 
> Map 1 seems to be purchased from the creator in discord. Would this still be locked behind Escrow despite a direct purchase?

By the looks of it, the owner sends you the files after purchase, I could try get affirmation from the owner whether it is still escrowed beyond that point but it is £50/Euro for it

**Comment by GodyFromDiscord** [comment]
This one is escrowed unfortunately (Map 1)

**Comment by antihero6713** [comment]
Since escrow is a thing we will have to look at the original city hall we use to have going to close for now. We will look into this at some point
