### ISSUE TITLE
Drift handling

### ISSUE THREAD

**Issue by DevotionRL** [InZidiuZ/legacy-assets-issue-tracker#6]
**Name:**
Devotion#5277
**Summary:**
a few cars with the option to increase steering lock, IE the futo, hoonicorn replica ect. 

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
being able to use what are relative copies of drift cars as they were intended with steering lock adjustments would be an awesome feature unlocking RP in ways such as sanctioned drift events, meeting in the mountain roads for a drift gathering ect

**Comment by RGDaviid** [comment]
Hey @DevotionRL 

I really like your idea however i am not the one that would be coding that. We already have some ideas to make cars have wider offsets and stances. So i will speak to some other developers about this and maybe in the future we can get something like that implimented. I'm going to close this for now though. 

_Karpenko_

**_OP-FW Car Developer_**

**Comment by RGDaviid** [comment]
Hello again,

I'm going to Re-Open this issue and assign it to @InZidiuZ . 

_Karpenko_

**_OP-FW Car Developer_**
