### ISSUE TITLE
Bug report - Schyster Deviant

### ISSUE THREAD

**Issue by Chronicle3D** [InZidiuZ/legacy-assets-issue-tracker#60]
**Reporter:**
Chronicle#9761

**Summary:**
The cars top speed is absolute dog shit rn for being an 80k car compared to other cars that's way cheaper and performing way better. Might be a bug or it's an intentional input from you guys.

**Notes:**
Everything on the car as of now is loveable just that the speed is garbage.

**Comment by Karpenkooo** [comment]
Learn some manners.

**Comment by Karpenkooo** [comment]
don't even bother re-writing this issue
