### ISSUE TITLE
Double back license plates for Ferrari 488GTB

### ISSUE THREAD

**Issue by richuvc** [InZidiuZ/legacy-assets-issue-tracker#601]
**Reporter:**
pLainbLank#0904

**Summary:**
Glitch with two back license plates showing up on top of each other. Looks really bad

## Additional Information

**Screenshots:**
![20220319210537_1](https://user-images.githubusercontent.com/88080705/159127928-fb6f2031-781a-4aa7-abe5-265b2b96c63d.jpg)

**Comment by joevapes3** [comment]
Both License plates are listed in the Extra mod parts on the vehicle. Go to LS customs and remove which either one you don't want. 
![image](https://user-images.githubusercontent.com/44896032/159149931-18a1bc8e-3e92-4641-8126-d004afc6eb26.png)
