### ISSUE TITLE
Aircraft Fuel Stations

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/legacy-assets-issue-tracker#603]
**Name:**
TheOneLizard#4196

**Summary:**
Add a refuel station for aircraft to each airport location.
May need to increase distance at which it is possible to refuel at these stations, unless there is another workaround.

**Reason:**
Since now fuel in aircraft is getting used up much faster and they often only come with a third tank, it would be very helpful to have fuel stations that are accessible to aircraft (enough space) at each airport.

**Comment by superiorchicken007** [comment]
I love how these have been added into the city.  It would be nice if they had a longer range to use them.  Right now you have to almost fly and land right next to it and if you have a bigger aircraft you are unable to refuel it.

**Comment by DaxterPancake** [comment]
@antihero6713 Has this been done?
