### ISSUE TITLE
[maps/?] Request Cluckin' Bell 

### ISSUE THREAD

**Issue by MaxieL99** [InZidiuZ/legacy-assets-issue-tracker#604]
**Name:**
Who is suggesting this? Please include discord name.
Maxie L99#3103

**Summary:**
Write a short summary of what your suggestion is about.
A building for Cluckin' Bell. A place for people in the city to meet up and grab some fried chicken. Served to go or to be enjoyed with their friends inside of Cluckin' Bell. 

**Link:**
If there are any links to what you're suggesting, please add them here.
1st pick
https://forum.cfx.re/t/release-cluckin-bell/1045080
https://forum.cfx.re/t/paid-esx-cluckin-bell-job/3794098
or
2nd pick
https://forum.cfx.re/t/mlo-paid-davis-cluckin-bell-interior/4811638

**Reason:**
Why would your suggestion be a good addition to Legacy?
A new workplace/place to hang out and a delicious verity of new foods and drinks. Burger Shot and Cluckin' Bell can start fast-food wars or join up. Who knows?

**Comment by joevapes3** [comment]
I will leave this open here as it would require an asset to be added, but this would mainly need script development, so please make a similar posting on this github as well:

https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by MaxieL99** [comment]
thx you for help

**Comment by antihero6713** [comment]
gonna close for now. Until we deem having another food place opened up.
