### ISSUE TITLE
[vehicles/casino] Livery additions for the Casino R35, casino Civic Type-R and Casino Mazda Rx7

### ISSUE THREAD

**Issue by HowieTheBrave** [InZidiuZ/legacy-assets-issue-tracker#605]
**Name:**
howie/rio - hoWie#2302

**Summary:**
My suggestion is adding some liveries to these 3 cars (as these are  the 3 i found/looked for on gta 5 mods) to make them even more unique to the owners, there are a good amount of liveries on the mod pages for these cars so new ones wouldnt have to be handmade.

**Link:**
R35 https://www.gta5-mods.com/vehicles/nissan-gtr-r35-varis-wald-c-west-topsecret

RX7 https://www.gta5-mods.com/vehicles/2002-mazda-rx-7-spirit-r-type-a-series-iii-fd3s

Civic Type-R https://www.gta5-mods.com/vehicles/2018-honda-civic-type-r-fk8

**Reason:**
Just to make these cars even more unique than they already are as they are meant to be special cars. Would also give the owners of the cars more chances to make their own one look different to the other owners cars.

**Comment by joevapes3** [comment]
At some point I will take a look at adding more liveries to these vehicles. I've added the info to my trello and will update this thread if and when I am able to get this completed, but for now I am going to close this. Thanks for the suggestion.
