### ISSUE TITLE
[vehicles/ems] Add EMS First Responder Vehicle

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#606]
**Name:**
Who is suggesting this? Please include discord name.
CloudTheWolf#0001

**Summary:**
Write a short summary of what your suggestion is about.

To enhance EMS RP and allow them to do more than sit and wait for calls EMS should have a First Responder Vehicle that they can take out and patrol in. They can then take scene and treat patients while the ambulance is on route.

**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/paintjobs/2005-vauxhall-astra-community-first-responder 

**Reason:**
Why would your suggestion be a good addition to Legacy?

This would enhance EMS RP and allow EMS to do more than sit at the hospital and wait for calls to come in.

**Comment by CloudTheWolf** [comment]
Yeah, at the moment, the explorer is for Lieutenants + & Critical Care Doctors only

**Comment by joevapes3** [comment]
While we appreciate the suggestion, this type of vehicle will not be added at this time. There are other vehicles potentially coming for ems but nothing like that unfortunately. Thanks again.
