### ISSUE TITLE
Command Suggestion

### ISSUE THREAD

**Issue by Djmeowzle** [InZidiuZ/legacy-assets-issue-tracker#607]
**Name:**
Djmeowzle#4701 | Thomas Jones :)

**Summary:**
Let pilots be able to use the /livery command while inside of an airport hanger and plane

**Reason:**
Most aircraft do have liveries, such as the Seabreeze and Shamal, and making use of all liveries possible would be very helpful to the Aviation RP

**Comment by twooot** [comment]
This is a script issue: https://github.com/InZidiuZ/op-framework-issue-tracker/issues
