### ISSUE TITLE
Suggestion/Highway Patrol Badge

### ISSUE THREAD

**Issue by rustyjohn1** [InZidiuZ/legacy-assets-issue-tracker#608]
**Name:**
RustyJohn1#6353

**Summary:**
I would like to add the highway patrol badge to my police badge, please.

**Link:**
https://i.imgur.com/ljjeTDG.png

**Reason:**
I really think this will add more RP to my character that is fully committed to highway patrol and will never take off the uniform no matter what department he would ever join. this will definitely add fun RP within the police and with civs.

**Comment by DaxterPancake** [comment]
What do you mean? 
Which badge specifically?
Please provide example photos.

**Comment by DaxterPancake** [comment]
Closing due to no response and lack of information.
