### ISSUE TITLE
Bug report - Pegassi Toros

### ISSUE THREAD

**Issue by Chronicle3D** [InZidiuZ/legacy-assets-issue-tracker#61]
**Reporter:**
Chronicle#9761

**Summary:**
A couple of issues with the car, the first one being whenever you tap the brake to slow down it's like the brake gets stuck halfway since the acceleration becomes slow as shit so you have to stop the car and reverse for it to fix itself (started doing this when I fully upgraded the car). Second, is that the car has no trunk animation and no place for a person to be put into, which might be an issue you can't do anything about. The third issue is the car has the same top speed when fully upgraded as the stock ones (160).

**Notes:**
Overall an amazing car for being an SUV but with multiple issues.

**Comment by Karpenkooo** [comment]
Hey,

I'm looking into this issue however there's nothing i'll be able to do about the trunk issue. 

_Karpenko_

_**OP-FW Asset Dev**_
