### ISSUE TITLE
Suggestion | Taxi is very frustrating to work for.

### ISSUE THREAD

**Issue by SkySmashify** [InZidiuZ/legacy-assets-issue-tracker#610]
**Name:**
Tadgh Boyne, SkySmashify#9999

**Summary:**
As discussed previously in a ticket, I find the taxi job very frustrating to work, because there's no way to tell who accepts what calls. Since my character follows traffic laws for the most part, I almost never make it to a customer before another driver comes barreling over in their SpaceX endorsed taxi cab to take the customer instead.

We require a systemic way to communicate together and to see who accepts what calls - the current taxi groups don't address this issue, as any "newcomers" can simply take the job and start working immediately, therefore taking calls that others may have accepted.

Some sort of call-claiming method, and a simple way to communicate with other drivers on duty would be the best approach. Perhaps this could be accomplished with a simple app on our phones, or something of that nature?

**Link:**
N/A

**Reason:**
This would improve taxi work for myself and entice others to join in, as it would remove some of the ridiculous competitiveness and lack of communication in it, while still being competitive with regards to who claims the calls that come in.

**Comment by antihero6713** [comment]
So for this seems like more of a frame work request don't really full under this one. This is for custom assets and visuals.
Post this link here :
https://github.com/InZidiuZ/op-framework-issue-tracker/issues
