### ISSUE TITLE
Suggestion: Make an undershirt an armor

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/legacy-assets-issue-tracker#611]
**Name:**
_Who is suggesting this? Please include discord name._
panpawn, panpawn#8183

**Summary:**
_Write a short summary of what your suggestion is about._
Make male undershirt 54 an armor instead.

**Link:**
_If there are any links to what you're suggesting, please add them here._
Undershirt (vest): https://i.imgur.com/GZSyzV0.jpg

**Reason:**
_Why would your suggestion be a good addition to Legacy?_
This is an armor that is under undershirts. There is a similar armor under armor with mags on the front, but this one is not under armor. Having it be under armor instead of undershirt would let police wear a duty belt while also wearing this vest.

**Comment by DaxterPancake** [comment]
This has been done and will be available after the next clothing build.
