### ISSUE TITLE
Suggestion Whitelist a New Business I have started

### ISSUE THREAD

**Issue by DecayGaming** [InZidiuZ/legacy-assets-issue-tracker#612]
Decay#9716

I have been running a personal business in city called Oh, Riley's Auto Parts. I collect materials needed for Mechanics and sell to them. Though I am aware that several players acquire materials and sell them to mechanics, it's usually only when they just happen to acquire these materials with another goal in mind. 

I have built relationships with many of the mechanics and most of them have at least heard of me. Specifically 2nd Gear and The Lost have benefited greatly from my service. The owner of 2nd Gear, Chris Buxell knows me and I believe is very appreciative of me. I believe this business would be a great aid to the city in assuring that all mechanics always have ample materials to repair vehicles.

**Comment by MetaHatter** [comment]
This would be a city specific thing that you would need to RP out and not something for the development team.

**Comment by DaxterPancake** [comment]
As MetaHatter stated, this has nothing to do with development. Pursue this through RP, thanks.
