### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by allank47** [InZidiuZ/legacy-assets-issue-tracker#613]
**Name:**
Allan. Allan#0002

**Summary:**
I wish a chocolate brand called Kismet to be added to Legacy please.

**Link:**
Ze link to [Kismet](https://www.fazer.fi/globalassets/inriver/resources/d1b98ee8-9aba-4595-b7a8-3b27b2aca5776.png)

**Reason:**
This would enhance the RP around my main character - Dmitri Karpov - who is from Ukraine as well as countless others once this gets added and then everyone will be talking about Kismet!
Throughout his life he was searching for the one, the only chocolate brand to dedicate his life to and one day in Ukraine he done did find it - Kismet! When he came to the Legacy City - oh no, he couldn't find his favorite brand - Kismet anywhere. He told all the people about his favorite brand around the city but no had ever even heard of it. Now Dmitri will do everything to make sure everyone will finally get to taste the sweet delicious waferness of Kismet!

**Comment by antihero6713** [comment]
Not sure adding a candy bar to the city. I think the city already has one in stores.

**Comment by DaxterPancake** [comment]
As AntiHero has stated, there is already a candybar in the city. If you wanted to have that changed to Kismet then you'd have to make a suggestion [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
