### ISSUE TITLE
[maps/memorials] Moving the Kate Knight Memorial

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/legacy-assets-issue-tracker#614]
**Name:**
Superiorchicken#0001

**Summary:**
With pillbox no longer being used as a medical facility I am requesting to see if we can have the memorial from across the street moved to where Mount Zonah is currently located.  I attached photos below of a few possible locations.

**Link:**
N/A

**Reason:**
I believe moving it from an area not utilized anymore and moved to the new hospital it will get seen more.

![20220414182249_1](https://user-images.githubusercontent.com/81419197/163487527-25e967fc-b91d-4d73-abad-9aab17a4181b.jpg)
![20220414182414_1](https://user-images.githubusercontent.com/81419197/163487531-c3635a61-9670-4fe3-a3f2-abc24d32015f.jpg)
![20220414182221_1](https://user-images.githubusercontent.com/81419197/163487535-d9e07499-6543-4b55-8085-003db6be7d0f.jpg)
![20220414182232_1](https://user-images.githubusercontent.com/81419197/163487536-65ff7976-ad9a-448e-bb41-3ca756a05888.jpg)

**Comment by ekhowan12** [comment]
It will be great

**Comment by Xaeraan** [comment]
I greatly agree with this. Hinnie's character, Kate, loved EMS and the people she worked with, as well as adored Legacy and spent a lot of her time here. She touched a lot of lives and made an impact with the connections she made. She should have a space where she can continue to watch over EMS now that they've moved to Zonah.

**Comment by GodyFromDiscord** [comment]
![FiveM_b2699_GTAProcess_kVgRNNnnLA](https://user-images.githubusercontent.com/60844168/193459437-25057cbc-c027-4a61-9b16-8b93c7564004.jpg)

Done
