### ISSUE TITLE
Reducing the amount of local cars

### ISSUE THREAD

**Issue by HowieTheBrave** [InZidiuZ/legacy-assets-issue-tracker#615]
**Name:**
hoWie#2302

Lower the amount of locals cars.

Theres just too many local cars imo, its ridiculous on some streets the amount of locals either driving or just parked up at an intersection light. its messy.

**Comment by MetaHatter** [comment]
Do you have a specific location in mind for this?  Can you explain why you would want them removed? How would this change benefit RP/immersion in the city?

**Comment by HowieTheBrave** [comment]
Mainly in the city, to stop massive pile-up of local cars at certain intersections. 1 local dies in an intersection and suddenly theres 14 cars backed up, and with how sporadically locals drive atm i feel like everyone knows the pain of having locals going across lanes, even across dividers and so forth slamming into you, locals drive like maniacs much more so than they used to (dunno what made theme do that) but it would just reduce overall frustration with locals

**Comment by MetaHatter** [comment]
Wouldn't calling a tow truck potentially solve that scenario in a more RP-friendly way?

**Comment by HowieTheBrave** [comment]
Sure but when theres 25+ cars backed up, 1 tow truck is gonna take forever to move all that, and whos gonna pay for a random intersection clean up? 

Not everything is about the RP even tho its an RP server, it gives people nothing but frustration with how insane the locals are idk if its a fivem thing or what, but trying to pass 48 locals on a 3 minute drive having 38 out of those 48 locals pull infront of you is just not fun, and doenst add anything to the server.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. This is for asset changes only. For framework changes use [this issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).

This is also something that can be changed on a server basis.
