### ISSUE TITLE
[maps/hayes_autos_body_shop] hayes garage and back area 

### ISSUE THREAD

**Issue by SilverChix** [InZidiuZ/legacy-assets-issue-tracker#616]
**Name:**
Who is suggesting this? Please include discord name.
sierra wrecker(owner) SilverChix#9157

**Summary:**
Write a short summary of what your suggestion is about.
my suggestions for hayes are to add a garage and to install a outdoor bay for the big semi trucks and to maybe have the garage door that leads to the back section to open to allow us to have access to the back area towards the garage and to the out door bay. and maybe even gates to allow the employees to lock the back area.

**Link:**
If there are any links to what you're suggesting, please add them here.
here are some pictures of where I think these things would go:

https://cdn.discordapp.com/attachments/827011065761497140/967233566297694288/hayes1.png
this one is where you could add an actual garage door to be able to access the back to the outside bay

https://cdn.discordapp.com/attachments/953169243493498990/967254930891096164/hayes2.png
this picture is when you walk out the garage door from picture 1 and then you see the gates and then maybe either 1 or 2 outside bay for the bigger semi trucks because they do not fit in the front of the building.
also ik that chop shop is behind hayes but was wondering if it could maybe be moved across so i could have my bigger bay.

https://cdn.discordapp.com/attachments/951565690450636850/967084023463694386/unknown.png
https://cdn.discordapp.com/attachments/951565690450636850/967084089846927400/unknown.png
IN these photos this is where I would love to have a garage so that we could clean the streets of all the cars from the front of the shop.

**Reason:**
Why would your suggestion be a good addition to Legacy?
I think that hayes really need these changes because it allows our rp to fix bigger trucks and to be able to park our cars in a spot that can be out of the way, it will allow our customers to have the room to park there vehicles in the front to get fixed with out having other cars in the way.

**Comment by QuantumSGT** [comment]
100% Especially for a nearby garage. Traffic tends to obliterate the staff cars parked outside plus the teams tow trucks.

Also a place for big rigs; lots of highway trucks rely on us as we are close to the main western stretch up north. Lots of truckers about that keep on getting stuck 😬

**Comment by Biqley** [comment]
These improvements would allow hayes to bring out its true potential in providing repairs while also providing an even more smooth workflow environment. I 100% am on board with this!

**Comment by ladysanity** [comment]
This would be really helpful. As a new member of the team, we need these adjustments as we don't have space for these things and traffic is a nightmare.

**Comment by CloudTheWolf** [comment]
I did some testing and the inside door (In the image below) doesn't line up with the outside door so would need to make some tweaks to the outside shell and/or some tweaks inside to line them up
![door](https://cdn.discordapp.com/attachments/827011065761497140/967233566297694288/hayes1.png)

**Comment by SilverChix** [comment]
so would there have to be like major changes to the building if it is done?

**Comment by GodyFromDiscord** [comment]
> so would there have to be like major changes to the building if it is done?

![image](https://user-images.githubusercontent.com/60844168/193486165-93e2389f-fb1e-402a-8c5a-d2d7f4d4d517.png)
Basically, these back doors are much lower on the outside so they do not match up with what is on the inside. So the garage door circled may have to be moved to the right or left to fit the outside, either way some things on the inside wall may have to be moved

**Comment by SilverChix** [comment]
ahh ok so kinda like what mosleys has

**Comment by MetaHatter** [comment]
The collision was changed at the front of Hayes to allow large trucks to fit inside. There should be no need for a rear area any more.  Open a new ticket if there are new suggestions.

Request for scripting, like garage points, etc., should be done here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose
