### ISSUE TITLE
[peds/*] Cosmetic | Hat design

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#617]
**Name:**
AdeptCL#0402

**Summary:**
"REAPER CREW" hat, which can be switched from forwards to backwards.

**Link:**
Image 1: [here](https://cdn.discordapp.com/attachments/881550970214055958/967494111919742996/unknown.png)
Image 2: [here](https://cdn.discordapp.com/attachments/881550970214055958/967494112192376932/unknown.png)

**Reason:**
I assume we all know/heard of Sons of Anarchy, well you may recognise this hat worn by Jax Teller in the series. It's just a simple black hat, with REAPER CREW written on the front of it, as well small printed on the back side of the hat. I would like to check if this would be something the asset developers would be able make and implement into the city. 

Preferably, another texture for the hats that allow it to be changed forwards and backward. We have made an attempt to find this hat already made to make life easier, but unfortunately to not luck.

"REAPER CREW" has a lot of story behind it for some groups, specifically the motorcycle club based groups. But this hat could easily be implemented by a new group based around the idea of a reaper.

**Comment by MetaHatter** [comment]
This has been added
