### ISSUE TITLE
[vehicles/civilian_3] Issues with the Audi RS6

### ISSUE THREAD

**Issue by xplrerin** [InZidiuZ/legacy-assets-issue-tracker#618]
**Reporter:**
Erin
Erin#1000

**Summary:**
Recently bought the Audi RS6 that is in the current EDM rotation and discovered a few issues with the model itself
- No door 6 (Trunk door)
- Removing Extra 2 (Aka the roof rack) reappears after you store and bring the vehicle back out of a garage. Meaning you need to take it back to the custom shop everytime.
- The roof rack also has hella collision issues

## Additional Information

**Screenshots:**
![Screenshot_23](https://user-images.githubusercontent.com/77466954/165167465-b53d2cb7-85e5-48c7-ad7b-8fee435474b3.png)
https://streamable.com/qwevma

**Comment by joevapes3** [comment]
trunk has been added to this vehicle and that update is already live. The extra not staying on is a script issue and that I have no control over, I believe that twoot may have come up with a solution but I cannot confirm that myself. As far as the collision on the roof rack goes is that it's fine the way it is as it's only a visual mod vs a physical one and doesn't effect the way the vehicle drives. Therefore I plan on leaving it that way for now.
