### ISSUE TITLE
POP's Diner (Paleto Bay)

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#619]
**Name:**
AdeptCL#0402

**Summary:**
POP's Diner MLO/interior to the North.

**Link:**
MLO link from Gabz, more can found online if necessary: [here](https://fivem.gabzv.com/package/4775182)

**Reason:**
Twoot mentioned that she would like to see more in the North to try spread about players. Here is something that will definitely be a positive addition. We don't need the North full of just criminal based activities. The hunters, the oxy runners, the cocaine runners, the meth heads will all sure to love this location as a point of call, a hang-out spot, or even a quick food/drink stop off.

**Comment by DaxterPancake** [comment]
This is unable to be added due to how escrow works in FiveM now. We cannot use anything locked behind it. Is there something else you can find that is not escrow?

**Comment by AdeptCL** [comment]
> This is unable to be added due to how escrow works in FiveM now. We cannot use anything locked behind it. Is there something else you can find that is not escrow?

I'm not fully sure what you mean, but is it because it requires to be paid for? If so, would there be an issue if a community member purchased it? And I would then also ask if a community member did purchase it, would there be a guarantee it would be added as well as the job around it (I know that's a framework thing).

I only ask because if the guarantees are there, I know myself and others would be willing to purchase it for the community.

**Comment by antihero6713** [comment]
So escrow means they have ties into the back end of the server (for licensing) and ben nor I want to put any maps in that require  us to do that.  Yes it is a nice mlo. yes it be cool. Escrow doesn't give us the ability to make customized updates to the models or interior to make it "legacy".

 If you can give another mlo suggestion that is escrow I am all ears.

**Comment by DaxterPancake** [comment]
Closing this, if you have a different diner/idea for a map that is not locked behind Escrow please feel free to create another github issue.
