### ISSUE TITLE
I Am the PDM Dealer in Indian Legacy Server.Have number of different bugs and Questions.

### ISSUE THREAD

**Issue by rusherw0w** [InZidiuZ/legacy-assets-issue-tracker#62]
**Reporter:**
Who is reporting this? Please include discord name.
Hello this is rUsHeR#2706 On discord.
**Summary:**
I Am the PDM dealer on Indian legacy servers and the bugs are
#1 I sold the car named Emperor ETR1 to a customer i did let him testdrive it and the testdrive vehicle went to 220+Mph on the same highway. and when the customer Bought the car the car barely reaches 180Mph. also it seems Scuffed. Also when the customer lets me testdrive the car the car works perfect and goes beyond 220MPH. but when he takes the keys back and drive it gets scuffed.
2# As the above mentioned details. Same goes with the car Phister Comet Custom.

Now my Questions Releated to PDM
#1 Are the Testdrive Vehicles Stock Or Equipped with Fully Customized performance parts?
#2 Also The commission System Is bugged.

**Comment by Karpenkooo** [comment]
Sorry but this is posted on the wrong Github page.
