### ISSUE TITLE
Suggestion - Additional map within the south side districts

### ISSUE THREAD

**Issue by Enryy** [InZidiuZ/legacy-assets-issue-tracker#621]
I think having an additional map with more neighborhoods like these would be much more stimulating in doing rp in them, we've been playing the same old map for years now and having radical changes like this would increase the beauty of the rp scenes and invite everyone to wander around the map a bit since you definitely won't find the same old things you've seen for years.

I'll give you an example, a lot of people like to helicopter to sandy/palete shores because it's nice to look at all that additional forest we have.

https://www.youtube.com/watch?v=5Z3wzMEgows

**Comment by DaxterPancake** [comment]
We have already said no to this. The map itself does not perform well and it would add a lot of work to change peoples rented houses and adding additional ones.
