### ISSUE TITLE
Adding Heroin into the city

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/legacy-assets-issue-tracker#622]
Name: Nia Guzman selliee#8806

Summary: I believe that Heroin and the processing of the drug should be brought into the city. I believe that it will bring a lot of new RP avenues for criminals and police.

Link: If there are any links to what you're suggesting, please add them here. 

Reason: While I fully understand that there are quite a few drugs already in the city, I believe that bringing Heroin into the city will benefit roleplaying, give multiple gangs something new to do, and control. Below I will lay out the steps of what I believe could be the way Heroin is made and sold.

Heroin is made from Opium Poppy Plants, these plants should be placed on Cayo Perico. The plants should be harvestable. 

Then, taking the “sap” from the poppy plants that was placed in our inventory, there should be a location to process this, turning it into a powder substance known as morphine.

Then the morphine would be taken and mixed up with acid (I highly suggest having acid already available where you mix the morphine, making the product easier to obtain since there are already many steps to make it.)

Once you mix the acid + morphine together, it creates heroine powder.

I suggest that bricks go into our inventory, or if we want to add another step, have a table where you can essentially pack the heroine powder into bricks. 

Then moving onto the main island, have a place to process the bricks into baggies to be sold to locals.

Places where it is possibly suitable for heroin to be sold: South side / Fudge lane areas. Also possibly to the “homeless” locals. 

I also believe that heroin should be usable to civilians. Once injecting the heroin it would go into an animation kind of like cocaine snorting transitioning into the sleep emote, like you do when you take a zpill. Your screen would be nearly fully blacked out (like when you have a head injury). You would lose all injuries but lose 25% health. Taking too much in a 12-24 hour period should result in an overdose as well. 

Going into depth about why I believe bringing heroin into the city would be beneficial, I believe that it will provide more RP all around. It would create more crim RP / activity for gangs which I believe is needed. With this, it also will provide more RP for police. More drug sale calls / sus calls and more drug tests. 

Providing a new drug in this depth, would give multiple groups a chance to “hold down” something in the city. 

Possible things to be held down/controlled:
Entirety of making heroin
Processing bricks into baggies
Place(s) that heroin is sold

It will create more RP both with possible gang wars, and also deals done to move the product. 

I do feel that this product should be held to the same level as cocaine, being sold for the same amount to locals 400-700 depending on time of day.

I firmly believe that adding heroin into the city will be massively beneficial, giving more RP all around, and adding to what criminals are able to do. 

Thank you.

*I have attached prop photos*

![Untitled design (22)](https://user-images.githubusercontent.com/90532434/167489849-07725849-a874-4afe-96fc-b11fb4abaf8c.png)
![Untitled design (23)](https://user-images.githubusercontent.com/90532434/167489852-c84db7bf-407a-42ef-ab4e-e2b65a3a978e.png)
![Untitled design (24)](https://user-images.githubusercontent.com/90532434/167489853-49479913-743d-4a71-b05a-23617cf15023.png)
![Untitled design (25)](https://user-images.githubusercontent.com/90532434/167489855-ab7d1ef2-5aed-4bd1-a4b5-9b8243881e73.png)

**Comment by microwavablepizza** [comment]
I think this is a good segway into creating more rp options and not only rp options for criminals, but for everyone else in the city regardless of their role. It can also be used to encourage more gang activity in the city, giving new upcoming gangs a role to play in the criminal scene with there being more drugs present. 
Good job putting this all together!

**Comment by BizzyBuzBee** [comment]
Not going to lie this is pretty good. Gives even smaller gangs a chance to take something. Right now all stronger gangs ghave everything. I believe this will help smaller gangs to be able to grow. Plus gives everyone something to do make a tasks to do something. +1 to this all day.

**Comment by spitslave** [comment]
Heroin would be a great addition to the city and give criminals new opportunity given that theres not much for us to do in the city.

**Comment by DaxterPancake** [comment]
This is the incorrect tracker, please re-post this in the correct one found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
