### ISSUE TITLE
[vehicles/police] Issue with CVPI tires de-spawning

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/legacy-assets-issue-tracker#623]
**Reporter:**
_Who is reporting this? Please include discord name._
panpawn, panpawn#8183

**Summary:**
_Write a summary of what you're experiencing._
The CVPI's tires will de-spawn when driven on most train tracks and under La Peurta near second gear on the grass. After this happens, there is a brief drop in FPS as well.

## Additional Information

**Screenshots:**
_If suitable, include some screenshots._
![MumXjvC](https://user-images.githubusercontent.com/5314189/168200201-4b889d58-7641-465c-8454-4b123711a952.png)

**Notes:**
_For anything else noteworthy._
This exact same behavior also used to happen on the old model for the CVPI.

**Comment by joevapes3** [comment]
I have not been able to reproduce this issue. I will keep the issue in mind but likely it was just a temporary bug that occurred.
