### ISSUE TITLE
[vehicles/civilian_2] Bug report

### ISSUE THREAD

**Issue by Smolnisno** [InZidiuZ/legacy-assets-issue-tracker#624]
**Reporter:**
Who is reporting this? Please include discord name.
smol-nisno#3835
**Summary:**
Write a summary of what you're experiencing.
So I bought the Nissan 180sx from the EDM shop and I wanted to test out the other pop-up headlights and for some reason when I try going back to the stock and then I garage the vehicle it instantly returns to the headlights that I purchased before and won't revert back to the stock pop-up headlights. I want it to return to stock as the ones I've spent money on are different in style / color and I prefer it stock.
**Notes:**
For anything else noteworthy.
if needed my 180sx info is 35ANF357 (33021)
**Images**
![23ca16cf3ba991879ce4acabcdff0498](https://user-images.githubusercontent.com/94027492/168416181-e83ca553-60df-4e9c-91b7-83769f842e2a.png)
![732b2eea13566ade8da3a50e3e57803e](https://user-images.githubusercontent.com/94027492/168416182-abbf94b2-420b-4aaa-9b6c-256790eb4bea.jpg)
![74ff31fe4d5cdfbfd067784efe9d99a5](https://user-images.githubusercontent.com/94027492/168416183-28117738-2bfe-4d50-b162-76a08c3f8c50.jpg)

**Comment by joevapes3** [comment]
this is an issue with the script that saves the vehicle extra's and there is nothing I can do for it asset wise. Please post this issue in the main github located here https://github.com/InZidiuZ/op-framework-issue-tracker/issues . Closing this issue out.
