### ISSUE TITLE
[maps/?] Parsons Rehabilitation Center Bug report

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/legacy-assets-issue-tracker#626]
**Reporter:**
Superiorchicken#0001

**Summary:**
While walking through Parsons Rehabilitation Center it will start to bug out where the interior goes invisible.  It happens to everyone that goes in there whether they have shades or not.

## Additional Information

**Screenshots:**
[Medal screen capture of bug.](https://medal.tv/games/gta-v/clips/ltq2oqydToadr/d1337LycESvr?invite=cr-MSxQelQsMjU3ODc0MjYs)

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
