### ISSUE TITLE
[vehicles/police] 2014 Dodge Charger Indicators broken

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#627]
**Reporter:**
Who is reporting this? Please include discord name.
CloudTheWolf#0001

**Summary:**

When in the 2014 Dodge Charger, if you indicate Left, the Left Rear and Both front indicators activate, and when you indicate Right only the rear right indicator activates

**Comment by InZidiuZ** [comment]
I believe this was a framework issue which has since been fixed. I was not able to reproduce this issue on the 2014 Dodge Charger locally. Feel free to reopen if I am incorrect.
