### ISSUE TITLE
Introduce Fridges

### ISSUE THREAD

**Issue by ChiknLegPiss** [InZidiuZ/legacy-assets-issue-tracker#630]
**Name:** ChiknLegPiss#8936

**Summary:**  Apartments that have fridges should have a storage of 150-200lb allowing us to store food items that will slow its rotting process. Also if this is done make sure it only works on food and nothing else. Or else people be storing coke and weed in it :3

**Link:**
You can just make a special storage (fridge) in the /furniture command, when stored food and only food in it, the rotting process will slow down. 

**Reason:**
Adding this makes it more realistic I guess. Also this gives people one more reason to get a home and live in it. You won't have to run around for food. You can stock your fridge and eat at home. Be it from Burgershot / Bean Machine or just any grocery store.
Earlier we used to live like 3-4 in a mid size apartment. We put a storage in the fridge and used to fill it up with food and water.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. This is for asset changes only. For framework changes use [this issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
