### ISSUE TITLE
Introduce Password System to Storages

### ISSUE THREAD

**Issue by ChiknLegPiss** [InZidiuZ/legacy-assets-issue-tracker#631]
**Name:**
ChiknLegPiss#8936

**Summary:**
The storage should pop up a Keypad before allowing a player to access it. 

**Link:**
Couldn't find any, But I hope you get the idea

**Reason:**
It will allow us to keep our stuffs safe from our roommates :3 Just like cupboards in real life.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. This is for asset changes only. For framework changes use [this issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
