### ISSUE TITLE
[peds/*] O'Neil brother

### ISSUE THREAD

**Issue by TBxRuSheR** [InZidiuZ/legacy-assets-issue-tracker#632]
**Name:**
Tanjim / Discord : ! TBxRuSheR#1725

**Summary:**
I've a dress request sir. We are going to do a gang RP as O'Neil brother If you put the dress in the server it will help use to continue our RP properly

![Image](https://cdn.discordapp.com/attachments/979125406487683132/979340453239463956/unknown.png)

**Link:**
[Drive](https://drive.google.com/drive/folders/1IUHEsZPusoUvDVLj7xgeHMhSw6IIE8R9?usp=sharing)
I don't know is it ok to put links from here.

**Reason:**
IT will help people in legacy Bangladesh as well as the people who do RP as O'Neil Brothers .Its my humble request sir .Please put this

**Comment by FaLLeN1121** [comment]
Yes! We Need It

**Comment by PiuPiu535** [comment]
Yes we need it

**Comment by NotMe6678** [comment]
Need it!!!!!!

**Comment by RHINO08** [comment]
yeah we need it....

**Comment by ALFAMAS** [comment]
would be great

**Comment by AetioX** [comment]
would be great

**Comment by DaxterPancake** [comment]
Is this still relevant, @TBxRuSheR 

If so I can work on getting this done.

**Comment by TBxRuSheR** [comment]
@DaxterPancake we are not doing this gang right now but if u add it i think it helps others

**Comment by MetaHatter** [comment]
As it's not relevant any more, closing the ticket.  Can be reopened if needed.
