### ISSUE TITLE
[peds/*] Adjust PD Vest Scaling on Female Model

### ISSUE THREAD

**Issue by teg4n** [InZidiuZ/legacy-assets-issue-tracker#633]
**Name:**
tegan☾#0001 

**Summary:**
Adjustment to Female PD Vest

There is a tactical SASP vest, 15 in the armor section, which has a massive gap at the back on female models. Would it be possible to adjust it to make it smaller for female models? Below I have attached images with a female and male comparison of the vest with front and side angles. Obviously, the vest is a lot larger at the back for females. 

**Female PD Vest from the side angle:**
- https://cdn.discordapp.com/attachments/922403458244575263/980084339293438012/unknown.png

**Female PD Vest from the front angle with clothing ID:**
- https://cdn.discordapp.com/attachments/922403458244575263/980084282766803005/unknown.png

**Same PD Vest from the front angle with clothing ID but on male model:**
- https://cdn.discordapp.com/attachments/922403458244575263/980092540168589363/unknown.png

**Same PD Vest from the side angle on a male model:**
- https://cdn.discordapp.com/attachments/922403458244575263/980092594103132320/unknown.png

**Comment by DaxterPancake** [comment]
@MetaHatter I'll leave this to you, let me know if you can't do it and I will assign it to Akemi.

**Comment by DaxterPancake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adjust Female PD Vest Model](https://trello.com/c/dlGYwy8G/58-adjust-female-pd-vest-model)

**Comment by DaxterPancake** [comment]
This has been done and will be added in the next clothing build, no current ETA on it.
