### ISSUE TITLE
Harmony Livery Missing from MTL Towtruck Custom

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#634]
**Reporter:**
CloudTheWolf#0001

**Summary:**
Since Yesterday (Wednesday June 1st 2022) the Harmony Livery has vanished from the MTL Towtruck Custom vehicle (Model Name: towcustom)

## Additional Information
I have been unable to verify this on the c2s1 so can only assume it's a OPFW issue not just an issue on c3s1

**Screenshots:**
https://cdn.discordapp.com/attachments/777722318159347712/981669170171224074/unknown.png

**Notes:**
N/A

**Comment by DaxterPancake** [comment]
This has already been addressed and fixed. It will be live in the next update.
