### ISSUE TITLE
[maps/mosleys] QOL impeovements for Mosleys

### ISSUE THREAD

**Issue by puppyani** [InZidiuZ/legacy-assets-issue-tracker#636]
**Name:**
Harper Thorn / puppyani#8433

Summary:
Several quality-of-life changes/updates/upgrades to Mosley's Mechanic Workshop to make things easier for both workers and clients alike.

1. New doors in the style of Hayes/MRPD garage doors - The doors when they open are also very slow, or slow to respond to opening.

2. Making it so that locals/local cars can't appear in the building. Currently, locals/cars keep appearing in the building, specifically in the back areas where we are unable to tow anything out.

3. Move the ATM to a different location away from doors in the building - currently, when staff tries to lock the door next to the ATM, we get sucked into using the ATM.

4. Move the materials computer down to one of the front offices - currently, the computer is in the upstairs part in the back. Our main trading floor is out the front part.

5. Add a car wash to the backdoor area for tows/big rigs/or other vehicles that are repaired here.

6. Add outside work bay or two in the back/side fenced part for bigger rigs.

7. The vehicle lift in the front area removed and replaced with a second workbench. (the lift doesn't serve any purpose).

Reason:
Why would your suggestion be a good change?

1. Currently, all four main doors get stuck and/or disappear for different people. It's a big issue experienced by everyone and sometimes it causes clients to turn away from the shop. Changing the doors will highly improve part of the service we give at Mosley's!

2. This one will improve the awkwardness of finding locals in the staff areas and not being able to do anything or having to report it.

3. Moving the ATM will be highly beneficial to staff as this hinders us when we are working / going out back for materials and coming back in and locking the door behind us. Those few seconds can seem like an eternity to someone who's in for a quick repair.

4. Like the above reasoning, the materials computer is out back and upstairs. Sometimes if we run out of mats we have to go buy them from the computer, moving it down to one of the front computers will improve the quality of working here as well as the service we provide by being prompt.

5/6/7 self explanatory QOL changes for the shop

![Screenshot_20220612-193938](https://user-images.githubusercontent.com/85951649/174320908-6f112a57-a925-4ea8-8a09-8d1337facf45.jpg)
![Screenshot_20220612-193954](https://user-images.githubusercontent.com/85951649/174320909-aa31efcf-f42d-471e-908d-cd9131e928e4.jpg)

**Comment by Detnom** [comment]
All of these changes would definitely improve everyones experience at Mosley's, and allow us to serve people better. The place has needed some attention for a while now.

**Comment by QuantumSGT** [comment]
As the main go to place for a lot of the city this wouldn’t only benefit the staff but for the customers creating a safer and faster way for people to get their vehicles fixed! Adding an outdoor bay would be amazing too due to the influx of truckers in the city with the taller models; we’ve had a few incidents of trucks ending up on the roof and/or causing issues to other vehicles in the back of the store disappearing or ending up on the roof due to a big rig being towed in.

All would be a quality of life improvement for sure!

**Comment by BazzDarkday** [comment]
These changes would most definitely improve the all round experience for mosleys, for staff and customers alike. An outside work bay would be amazing to ensure all trucks can be attended to, and the Changes to the inside/doors would benefit everyone hugely

**Comment by itachi069** [comment]
This changes would be great

**Comment by puppyani** [comment]
Bumping this please and thank you :)

**Comment by ayushpandit99** [comment]
I would agree with the changes as currently, the doors at mosleys are working "client-side" so there are issues like its open for some and not open for others also as the front bays are used more in the mosleys adding the material buying a computer in the front bay office it self would reduce the time of mechs .. as mosleys being the busiest repair shop .. this changes if made earlier will help solve a lot of problems

**Comment by CloudTheWolf** [comment]
I think 99% of this was done with the Mosley's Overhaul work that was recently done.
