### ISSUE TITLE
[vehicles/civilian_4] Issues with Mercedes A45

### ISSUE THREAD

**Issue by AssAssin1905** [InZidiuZ/legacy-assets-issue-tracker#637]
**Reporter:**
Who is reporting this? Please include discord name.
AssAssin#5441

**Summary:**
Write a summary of what you're experiencing.
Recently bought the Mercedes A45 that is in the current EDM rotation and discovered a few issues 
1- When we switch to fpp we cant see things properly
2- Its armour is soo badd like one hard pit and it will smoke and and all tires poped
3- Its a suggestion ,Can u change the horn becoz current one is so shit.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

![Screenshot (111)](https://user-images.githubusercontent.com/91372301/173053478-72767c41-f222-4948-8477-fa4a7901fa85.png)

**Notes:**
For anything else noteworthy.

**Comment by LastOfOmen** [comment]
Additionally, the A45's handling is just poor. For a Euro tuner its super slidey, too light, and the suspension is VERY stiff. It's become nothing more than a storage bin for me of late because it handles so poorly.

**Comment by joevapes3** [comment]
issue has been fixed and will be live on the next asset merge/server update
