### ISSUE TITLE
[vehicles/police] PD Highway Livery

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/legacy-assets-issue-tracker#639]
**Name:**
Dex#5879

**Summary:**
Can highway liveries be reverted back to all black with white doors. The all white cars is just such a visual pain with how FiveM postFX is wonky and makes it super bright 🙏 . Like how the hellcat is now is perfect.

**Link:**

**Reason:**
Cars look better
The all white cars are a flashbang during the day

**Comment by joevapes3** [comment]
all highway vehicles are going to be updated to the newest matching livery and that is currently a work in progress.
