### ISSUE TITLE
Suggestion - S15

### ISSUE THREAD

**Issue by Aspratic** [InZidiuZ/legacy-assets-issue-tracker#64]
**Name:**
Who is suggesting this? Please include discord name.
Aspratic#3121
**Summary:**
Write a short summary of what your suggestion is about.
Adding an S15 with tuning/customization
**Link:**
If there are any links to what you're suggesting, please add them here.
https://www.gta5-mods.com/vehicles/nissan-silvia-s-15-spec-r-stock-tunable-lods-addon
https://www.gta5-mods.com/vehicles/zlayworks-nissan-silvia-z15
**Reason:**
Why would your suggestion be a good addition to Legacy?
The S15 is an overall amazing car that every fivem server should have. I personally like the first link more but the second is an alternative.

**Comment by Karpenkooo** [comment]
Hey,

As much as i like the S15 i won't be adding it as they all have a bunch of bugs that come with them.

_Karpenko_

_**OP-FW Asset Dev**_
