### ISSUE TITLE
[maps/?] Remove Realtor Signs Mirror Park

### ISSUE THREAD

**Issue by baileycarothers** [InZidiuZ/legacy-assets-issue-tracker#640]
**Name:**
KeepItLokiTho#2596

**Summary:**
All of the houses on Nikola Street in mirror park have green realtor signs all over them, both big and small. They make the houses rather unsightly and the street as a whole would look a lot better with them removed.

**Link:**
[Example](https://cdn.discordapp.com/attachments/955721778846650368/986831633237835877/unknown.png)

**Reason:**
Make the streets look cleaner all around and lived-in instead of vacant.

**Comment by antihero6713** [comment]
As much as I'd like to do something to remove them. Currently i don't think its worth streaming more ymaps in that area. I had ideas for mirror park pond. If I get to that I will then remove said signs, but sadly they will remain till then

**Comment by InZidiuZ** [comment]
Until (or if) @antihero6713 does what he said, I have made all 'for sale' signs automatically be deleted. However, this is not the proper way to do it as they will still appear from a distance & there are some 'for sale' signs and flags that are not objects.

**Comment by antihero6713** [comment]
gonna call this done for what it is not gonna fix on my side
