### ISSUE TITLE
[maps/bean_machine] Require ATM & TV Banner in the bean machine

### ISSUE THREAD

**Issue by HellRaiser5** [InZidiuZ/legacy-assets-issue-tracker#641]
Request you to place a ATM in bean machine.

2 TV is hanging on bean machine, need to place bean machine menu card into tv screen ..

if you do this it will help us a lot.

provide the size of tv screen , so that i can provide bean machine menu card as per your given size.

this menu card is valid only legacy india
reference Photo Link
https://cdn.discordapp.com/attachments/840178806726721606/986886573968740383/unknown.png
https://cdn.discordapp.com/attachments/840178806726721606/986886603366608926/Screenshot_165.png

**Comment by RustyWaters07** [comment]
Question: is the adding the menu to the TV screens a possibility? Asking bc I would like to know if I can do the same at the arcade. Thanks!

**Comment by antihero6713** [comment]
No because the menu items won't be the same across all servers

**Comment by RustyWaters07** [comment]
gotcha. thanks anyway!

**Comment by HellRaiser5** [comment]
any update ?? ATM is very IMP..

**Comment by CloudTheWolf** [comment]
I think this has been asked before, and since there is one on the street outside it was deemed not necessary for another one inside?

**Comment by HellRaiser5** [comment]
yaap we used that .. remove it & move it to store, whenever new people came we need to provide the outside atm location.

**Comment by MetaHatter** [comment]
This has been asked before and declined.  Walking 20 steps to the ATM is not so difficult that we need to edit the map to solve it.

**Comment by antihero6713** [comment]
closing because atm is close enough
