### ISSUE TITLE
PD Spike Strips Suggestion

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/legacy-assets-issue-tracker#642]
**Name:**
Dex#5879

**Summary:**
Right now, spikes get placed horizontally in front of the player model, instead they should be placed parallel with the way the player is facing.

**Link:**
[Arrow pointing how the spikes should deploy](https://i.imgur.com/ERjYsMz.jpeg)

**Reason:**
The horizontal is not how its realistically done, since you have to stand right in the middle of where the car you want to spike, would be driving over

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. This is for asset changes only. For framework changes use [this issue tracker](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
