### ISSUE TITLE
[peds/*] Bring back highway patrol campaign hat

### ISSUE THREAD

**Issue by rustyjohn1** [InZidiuZ/legacy-assets-issue-tracker#643]
**Name:**
RustyJohn1#6353

**Summary:**
Now that Highway patrol is its own thing I would like to ask for the highway patrol campaign hat to be brought back into the city as its park of our uniform. it used to be in the city but with clothing, update was removed unsure why. the link below shows what the hat looks like 

**Link:**
https://i.imgur.com/JomvipU.png

**Reason:**
part of the uniform was originally in the city. also adds to the Highway RP as people like to steal my hat.

**Comment by rustyjohn1** [comment]
Been told was replaced with SASP campaign hat and there is still an open/checkerboard texture if this makes it easy to add back in

**Comment by joevapes3** [comment]
This has been completed and will be live with the next asset merge. Thank you for your patience and enjoy.
