### ISSUE TITLE
[maps/paleto_bay_moto] SOL:SA Repair Additions

### ISSUE THREAD

**Issue by xplrerin** [InZidiuZ/legacy-assets-issue-tracker#644]
**Summary:**
Originally made a script suggestion + Ben suggested I requested the map changes first before any additions were made with the mechanics over there.

**Link:**
We need a outdoor work bench added to the side of our repair shop.
![image](https://user-images.githubusercontent.com/77466954/179551312-f7ee4cf1-4809-4606-857e-d77a6653ec73.png)

Just where it shows in **blue** 

**Reason:**
Originally we requested a external repair bay at sol:sa repairs for bigger vehicles (With the workbench for easier crafting access). We're across from one of the busiest trucking spots and repairing their trucks is next to impossible. The addition of the work bench would make the outdoor bay more possible. :) (Similar to the Lost MC's outdoor bay).

**Comment by antihero6713** [comment]
This change has been completed will be in next update
