### ISSUE TITLE
[maps/?] Invisible tree near Jewelry Store

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/legacy-assets-issue-tracker#646]
**Reporter:**
InZidiuZ on behalf of Hell of the Devil

**Summary:**
Invisible tree near the Jewelry Store.

## Additional Information

**Screenshots:**
![unknown](https://user-images.githubusercontent.com/22295402/180168060-70ea25d6-87fa-47bf-99f4-c22016597d04.png)

**Comment by antihero6713** [comment]
This will be fixed next update
