### ISSUE TITLE
[maps/st_fiacre_hospital] Missing door

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/legacy-assets-issue-tracker#647]
**Reporter:**
InZidiuZ on behalf of Hell of the Devil

**Summary:**
Missing door at St. Fiacre hospital.

## Additional Information

**Screenshots:**
![unknown (1)](https://user-images.githubusercontent.com/22295402/180168332-4081adf6-2e2c-45e1-a668-f367744fb107.png)

**Comment by antihero6713** [comment]
fixed
