### ISSUE TITLE
[vehicles/?] Vapid Dominator GTT texture issue

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/legacy-assets-issue-tracker#648]
**Reporter:**
InZidiuZ on behalf of Hell of the Devil

**Summary:**
Vapid Dominator GTT (Tuner) interior seats have incorrect textures

## Additional Information

**Screenshots:**
![unknown (2)](https://user-images.githubusercontent.com/22295402/180168688-110ea681-69a0-4bfd-99da-cd16c599e72e.png)

**Comment by joevapes3** [comment]
Being that this is a vanilla asset, I am unfortunately not able to do anything for it. It may have been overwritten by an addon vehicle but finding which vehicle is streaming this exact named texture would be next to impossible. I will try and get a solution figured out but for now I am gonna close this github and update this on my trello. Thanks for bringing this to my attention.
