### ISSUE TITLE
[vehicles/?] Spoiler incorrectly rigged on Penumbra

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/legacy-assets-issue-tracker#649]
**Reporter:**
InZidiuZ on behalf of Hell of the Devil

**Summary:**
Penumbra spoilers are not rigged correctly and hang about 2 foot from the back of the car.

## Additional Information

**Screenshots:**
![unknown (3)](https://user-images.githubusercontent.com/22295402/180168986-ac17c873-0868-4602-bcef-84c82be7c3b1.png)

**Comment by joevapes3** [comment]
So this was fixed on my end and on my test server I have all the correct mod parts now, however it hasn't fixed itself on the live server and I am not too sure why. Unless I can find a way to repo this in my test server there isn't much I am able to do. For now I will close out this issue and if I find a way to solve it after the fact I will update this thread again.
