### ISSUE TITLE
[peds/*] Videogeddon clothing added to the city

### ISSUE THREAD

**Issue by RustyWaters07** [InZidiuZ/legacy-assets-issue-tracker#652]
**Name:**
Who is suggesting this? Please include discord name.
Rusty__Waters#9045

**Summary:**
Write a short summary of what your suggestion is about.
Would like to add Clothing for Videogeddon to the city. T-shirt at a minimum but would also like to have a hoodie added if possible.

**Link:**
If there are any links to what you're suggesting, please add them here.
https://cdn.discordapp.com/attachments/989348838336790548/990788170998226954/unknown.png

**Reason:**
Why would your suggestion be a good addition to Legacy?
Would like to have official clothing options added for the arcade so employees can be easily identified.

**Comment by DaxterPancake** [comment]
What colour shirts and hoodie?

**Comment by RustyWaters07** [comment]
Black please.

**Comment by RustyWaters07** [comment]
Actually, if we can do something else as well, I would like to use the pictured hoodie and place the videogeddon logo on the front of that.
[https://cdn.discordapp.com/attachments/990642150725263410/1001972282085867550/Shirt_Back.jpg?width=832&height=468](url)
[https://cdn.discordapp.com/attachments/990642150725263410/1001972282471747665/Shirt_front.jpg?width=832&height=468](url)
[https://cdn.discordapp.com/attachments/990642150725263410/1001972282866024538/Hoodie_Back1.jpg?width=832&height=468](url)
[https://cdn.discordapp.com/attachments/990642150725263410/1001972283176386621/Hoodie_front.jpg?width=832&height=468](url)

**Comment by DaxterPancake** [comment]
> 

Do you want that hoodie in black or that hoodie in that multicolour?

**Comment by RustyWaters07** [comment]
Would like to use the multicolor if possible please

**Comment by DaxterPancake** [comment]
This has been done and should be added in the next clothing build!

**Comment by RustyWaters07** [comment]
Thanks!
