### ISSUE TITLE
[maps/?] Missing collision at Mirror Park

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/legacy-assets-issue-tracker#653]
**Reporter:**
Ben

**Summary:**
There's missing collision at a wall in Mirror Park.

## Additional Information

**Video:**
https://www.inzidiuz.com/u/Byx0govyPj.mp4

**Notes:**
I am not sure which map is causing it. I tried without any maps at all, and the collision was there as intended.

**Comment by antihero6713** [comment]
this has been fixed now
