### ISSUE TITLE
[maps/paleto_bay_moto] Firing bullets and windows causes crashes

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/legacy-assets-issue-tracker#654]
**Reporter:**
Ben

**Summary:**
Firing bullets and windows causes crashes.

## Additional Information

**Video:**
https://www.inzidiuz.com/u/o6igzINK38.mp4

**Comment by twooot** [comment]
@InZidiuZ your video is gone

**Comment by antihero6713** [comment]
Fixed when i commit the changes
