### ISSUE TITLE
[peds/*] Mask Texture

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/legacy-assets-issue-tracker#657]
**Name:**
Who is suggesting this? Please include discord name.
Gody#0301

**Summary:**
Write a short summary of what your suggestion is about.
So there are two masks, some that won't fit on certain people's faces and one that does, but one has a green texture that's slightly different, what I'm asking is for Mask 23, shown below to also have the texture shown in Mask 15, as there isn't one like it and it clips through some peoples faces

**Link:**
If there are any links to what you're suggesting, please add them here.
Mask 15 - https://i.imgur.com/fnCkrMy.jpeg | The mask for the texture I'm requesting to be also added to Mask 23
Mask 23  - https://i.imgur.com/pTmJ9ri.jpeg | This doesn't have that one green texture that 15 has.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It's more or so for one of the whitelisted gangs on Legacy and it just helps for outfits and representing the gang. Thanks :)

**Comment by DaxterPancake** [comment]
This texture is already available on mask ID 23. 
![image](https://user-images.githubusercontent.com/50828532/184525436-3e50e555-b794-4171-b612-d690aec5cece.png)
