### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Khasnuwr** [InZidiuZ/legacy-assets-issue-tracker#658]
**Name:**
arif#8153

**Summary:**
Adding PD Badge Desk/Store in the Highway Patrol PD

**Link:**
![image](https://user-images.githubusercontent.com/58362778/183236466-d7eaf507-f2e3-4f63-a261-07c9dd143226.png)
![image](https://user-images.githubusercontent.com/58362778/183236660-d82ab08e-b38c-4f5e-98b8-51cdf2d309ac.png)

**Reason:**
All the other PD and Sheriff's office has PD Badge Desk/Store except Highway Patrol PD

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. Use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) for framework suggestions.
