### ISSUE TITLE
[maps/?] Unintended interior at position 0,0,0

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/legacy-assets-issue-tracker#659]
**Reporter:**
Ben

**Summary:**
There's an unintended interior at position 0,0,0. This is the result of another interior including this one for some reason.

## Additional Information

**Screenshots:**
![WsZyEL0T](https://user-images.githubusercontent.com/22295402/183298675-c6e28603-e887-4e98-9813-303f65b1232e.png)

**Comment by antihero6713** [comment]
fixed
