### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by naaazz** [InZidiuZ/legacy-assets-issue-tracker#66]
**Reporter:**
discord name --- >>  Naaazz#0545

**Summary:**
i upgrade my car but its feels like nothing changed...
i spend like 15-20k 
can someone help me out pls?
like is this normal? for that much money? 
before upgrade top speed -+175 - 180
AFTER UPGRADE - lower almost

## Additional Information
like you can see in the youtube clip first 0.33 secs is before i tuned my car
after i tune my car i didnt even get at the same speed

https://www.youtube.com/watch?v=EdvZT7UKlNM

**Screenshots:**
no screenshot but i have youtube clip for you guys

**Comment by TwoplePop** [comment]
variables on the road that you tested on. what you should do is test tour car unupgraded on the test server on the grand prix track. time it. then upgrade and time it again on same track.

**Comment by Karpenkooo** [comment]
Hey,

**"AFTER UPGRADE - lower almost"** so does this mean it is lower or not? The YouTube video also doesn't seem to work for me. Plez give a better description.

_Karpenkoooooooooo_

_**OP_FW Assets Dev**_
