### ISSUE TITLE
[vehicles/ems] Exchange the Airbus EMS helicopter

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/legacy-assets-issue-tracker#660]
**Name:**
TheOneLizard

**Summary:**
The Airbus EMS helicopter currently available is a great vehicle overall, however it suffers from one small issue with a rather annoying result.
The physical/hitbox model of the rotor blades does not align with the spinning rotor texture and causes a misunderstanding of where the rotor blades are actually located when mid-air. 
As the helicopter starts spinning up, the rotor blades are still hanging over a little while spinning, until they reach a certain RPM where their visual model gets replaced with the spinning rotor texture, while their hitbox however remains overhanging rotor blades, causing the rotor blades to hit structures and people way lower than the visible spinning rotor texture would suggest.
This does not only cause confusion, but also causes the helicopter to be less practical. Aside of the potential hazard, it allows for less wiggle room to maneuver it properly.

Hence, I'd suggest replacing the Airbus helicopter with an alternate model. This could be the same Airbus model but with straight rotor blades, or it could be a different asset altogether. 

Possible alternatives would be:

- AW139: this used to be the "bigger" version of Angel One a few months back and worked with no issues that I'd be aware of. One thing that could be changed if possible would be the number of seats available, to enhance transport capacity.

- S-70A Firehawk: this would actually pose a very interesting alternate choice, as the model would fit possible future scenarios where the fire department will be in need of aircraft able to extinguish fires. While this may not yet be the case now, this helicopter could still perfectly function as an air ambulance, with possibilities for more in the future.

None of these models have overhanging rotor blades, evading the issue mentioned above. I cannot speak for the overall quality of these models.

**Link:**
AW139: [https://www.gta5-mods.com/vehicles/augustawestland-aw139-lafd-westpac-uk-spain-add-on](url)
S-70A Firehawk: [https://www.gta5-mods.com/vehicles/s-70a-firehawk-fire-fighting-helicopter](url)

**Reason:**
The reasons are already explained above.
- Evade confusing model discrepancies
- Allow for more maneuverability and security

**Comment by joevapes3** [comment]
I'll just readjust the collision of the blades, no need to replace the model. I'll update this thread when it's done

**Comment by TheOneLizard** [comment]
yes, that's absolutely perfect if that work. I didn't just want to state a problem without other possible solutions in mind :)

**Comment by joevapes3** [comment]
this issue should have been corrected, closing out this suggestion. Thanks again for bringing this to my attetnion.
