### ISSUE TITLE
Adding Hypebeast Stuff 

### ISSUE THREAD

**Issue by darshitmachhi** [InZidiuZ/legacy-assets-issue-tracker#663]
**Name:**
Who is suggesting this? Please include discord name.

**Summary:**
Write a short summary of what your suggestion is about.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by DaxterPancake** [comment]
Closing due to suggestion being incomplete. All sections are required to be filled out in order for your suggestion to be considered.

Also, there is already a lot of clothing that is considered 'hypebeast' - Are you wanting something specific?
