### ISSUE TITLE
[peds/*] Texture template for one of the vests to make a vest for the Yakuza 

### ISSUE THREAD

**Issue by cloudeyy** [InZidiuZ/legacy-assets-issue-tracker#664]
**Name:**
Who is suggesting this? Please include discord name.
cloudey#9158

**Summary:**
Write a short summary of what your suggestion is about.
I would like the texture template for one of the vests to make a vest for the Yakuza and was wondering if I would be able to be provided with the template. I would like to make them a vest as I think as a gang they bring a lot to the server and should deserve a vest like this. I would be looking to replace the name on the vest I have put below in the links. Replace the name and the logo to fit the Yakuza gang and make it their own to wear.

**Link:**
If there are any links to what you're suggesting, please add them here.
![Inked1_LI](https://cdn.discordapp.com/attachments/840677887182503966/1009244548607791164/unknown.png)
![Inked2_LI](https://cdn.discordapp.com/attachments/840677887182503966/1009244566722973806/unknown.png)
![Inked2_LI](https://cdn.discordapp.com/attachments/840677887182503966/1009244688349409310/unknown.png)
![Inked2_LI](https://cdn.discordapp.com/attachments/840677887182503966/1009244746411147304/unknown.png)

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would give something for Yakuza to wear that would make them stand out other than wearing just the blue mask. I think as a gang it would give them motivation on the server and something for them to have as their own that no one else has. Anyone can wear the blue mask and be something but with the vest they stand out with the name and the logo. It would give a good change as a gang that can provide good rp. I see this as some kind of reward but also as a piece of motivation for the members to keep striving towards their goals in the server.

**Comment by cloudeyy** [comment]
update: have changed the vest they have differed to as it fits with male and female, if I am able to get the texture files for these so I may edit over them and try make it something of our own, it would be much appreciated :) thank you.

**Comment by cloudeyy** [comment]
update: have changed the vest they have differed to as it fits with male and female, if I am able to get the texture files for these so I may edit over them and try make it something of our own, it would be much appreciated :) thank you.

**Comment by MetaHatter** [comment]
We will not provide the template file. Assets are almost always licensed and distribution of included would potentially break terms.

This specific vest is out of slots but we have new ones in the works.  Provide your graphics assets to us with requested placement in a new suggestion and we'll see what we can do.
