### ISSUE TITLE
[maps/yellow_jack] Improvement and expansion of Yellow Jack

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/legacy-assets-issue-tracker#666]
**Name:**
Who is suggesting this? Please include discord name. Scufflord#0666

**Summary:**
I'm in the process of purchasing the Yellow Jack currently on the international server, and the interior is rather small and lacking. There's an entire second floor that isn't accessible. I was hoping there would be a way to get the previous MLO put in but apparently it was causing headpops, so I was hoping instead that there may be some way for a bit of custom work to be done to open up the upstairs, and add some seating in the back area and turn the fenced in portion into a hangout area. The propane tank should also be removed ideally. Due to concerns of metagaming, I'd prefer to explain the exact details of the second floor if possible via DM.

**Link:**
If there are any links to what you're suggesting, please add them here. 

There aren't very many decent MLO's that I can find out there that don't look super scuffy or tacky. 

**Reason:**
Why would your suggestion be a good addition to Legacy? Would allow a new business to prosper on the international server, and open up roleplay opportunities for the other servers as well.

**Comment by DaxterPancake** [comment]
I'd personally like to see RP put into the spot before anything custom is added for it. Especially if custom work is to be done on it. Spend some time in the area and create your story before we spend lots of work on it.

**Comment by twooot** [comment]
basically what daxter said, RP first then we consider it

**Comment by DaxterPancake** [comment]
Closing due to requester no longer pursuing the RP therefore would no longer want this done.
