### ISSUE TITLE
Addition of Boba Tea/Coffee to Bean Machine Menu 

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/legacy-assets-issue-tracker#668]
**Name:**
Jethiya#2800

**Summary:**
Addition of boba tea/coffee to the last spot on the bean machine menu. 

**Link:**
 NA

**Reason:**
Would add an option to their taste and preferences

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this suggestion.
