### ISSUE TITLE
[maps/arcade] Place functional water cooler in Videogeddon manager's office

### ISSUE THREAD

**Issue by RustyWaters07** [InZidiuZ/legacy-assets-issue-tracker#669]
**Name:**
Rusty__Waters#9045

**Summary:**
Would like to have a functional water cooler placed in the managers office at Videogeddon. There is a non-functional one there now (pictured)

**Link:**
![20220826100425_1](https://user-images.githubusercontent.com/107648789/186922213-6c467755-3794-4f63-b99e-a7114a043870.jpg)

**Reason:**
Since adding the refillable water bottle, we are finding that they are going under-utilized since there aren't many places to fill them around the arcade. Having a functional water cooler in the managers office makes sense because there is one already part of the decor.

**Comment by antihero6713** [comment]
might be done.
