### ISSUE TITLE
Vehicle Issue after new update

### ISSUE THREAD

**Issue by Fieldsy** [InZidiuZ/legacy-assets-issue-tracker#67]
**Reporter:**
Fieldsy#2700

**Summary:**
Not sure if this is intended or not so thought i'd post it as it could be a bug.. before the patch my Mitsubishi evo (which was heroic tier) could hit 190 max on the freeway up to north fully kitted out, however, after the patch it can barely hit 170 (on the same route and bit of road) and the turbo and acceleration is noticeably slower and sluggish which really ruins the aspect of it.

## Additional Information
If this was intended then it is working as planned but if not i thought i would make you aware of this situation. Also, i have a friend who bought the skyline and kitted it up and he has the same issues since the new update and noticed it straight away.

((Update)) We both cleared our steam and fiveM cache and they are still the same.

**Comment by psyCOSMO** [comment]
Some cars got buffed some got nerfed...
