### ISSUE TITLE
[vehicles/civilian_1] rmodgt63 window tint issue

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/legacy-assets-issue-tracker#671]
**Reporter:**
Who is reporting this? Please include discord name. Scufflord#0666

**Summary:**
Front window tint on the rmodgt63 applies to the turn signals on the mirrors instead of to the front door windows.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
No tint, turn signal visible
https://cdn.discordapp.com/attachments/845947698628001862/1016032018808713237/unknown.png
With tint, turn signal darkened.
https://cdn.discordapp.com/attachments/845947698628001862/1016032019387519086/unknown.png

**Notes:**
N/A

**Comment by joevapes3** [comment]
This issue has been resolved and will be live with the next asset merge
