### ISSUE TITLE
World cup jerseys for world cup season

### ISSUE THREAD

**Issue by Rendon310** [InZidiuZ/legacy-assets-issue-tracker#672]
rendon310#9375

**Summary:**
just wondering if we could have some world cup jerseys maybe not all but top teams maybe mexico and usa

**Reason:**
Alot of people watch the sport we can have like a watch/hearin party like a in city event for the world cup final and it would be a good way to show ur support for your country or favorite team

**Comment by DaxterPancake** [comment]
Although this is a cute idea I don't see it as needed at this time. It wouldn't be fair for me to only add a few teams and not others and there are only old variations already made which would mean that these would have to be hand made by our development team. This ia a won't do for now.
