### ISSUE TITLE
savage dogs mc kuttes

### ISSUE THREAD

**Issue by Infomc** [InZidiuZ/legacy-assets-issue-tracker#673]
![download](https://user-images.githubusercontent.com/113386555/189741813-56ea7818-f528-46e6-8308-ecfb6031456f.png)
**Name:**
Who is suggesting this? Please include discord name.Info#4346

**Summary:**
Write a short summary of what your suggestion is about.i would like to request the kuttes to be made for my mc the savage dogs as we are opening a business and would like to have the logo on the sign at the front to let people know we are here to stay  i have it planed  on what it will look like but this is my first time ever doing something like this 

it will be the same as the lost kuttes but with the logo i have but in 

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy? we intend to keep this mc around and we will not be going anywhere and would like kuttes so people know who we are

**Comment by MetaHatter** [comment]
@DaxterPancake can confirm but custom clothing, in general, will not usually be added for any group until they have

- Been around for a long time
- Provide consistent, quality roleplay
- Avoid gang strikes
- Are different enough to warrant the hours of work required

**Comment by DaxterPancake** [comment]
As said above, establish yourself in the city first.

You don't need custom clothing to be able to RP as an MC or a group in general. You don't need your logo plastered all over your buisness either. These things are given to those who earn it and not just given out to everyone.

If you still wish to have this, please recreate this ticket in a few months time and we can see how your group is doing.
