### ISSUE TITLE
[maps/harmony_lsc] Change Harmony Repair Shop To Unlinked MLO

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#674]
**Name:**
CloudTheWolf#0001

**Summary:**
Harmony Repair is currently using the `v_46_carmod3` Archetype which is shared with LostMC and the Paleto Bay LS Customs preventing us from making improvements to the store.

I would like to change the MLO to a custom interior (Called `v_46_carmod3_rv`)  to decouple Harmony / Lost and make the shop feel unique, instead of a Copy/Paste of Lost.

**Link:**
Map Changes: https://drive.google.com/file/d/19y6h8OFVCsWMm24PIcRKrtDrjh6jUV57/view?usp=sharing 

Before:
![before](https://i.imgur.com/Z90KTIK.jpg)

After:
![after](https://i.imgur.com/qynNsbM.jpg)

**Reason:**
Why would your suggestion be a good addition to Legacy?

This would Decouple Harmony from Lost and allow Harmony to make changes with out impacting Lost and visa vera.
This would also allow us to have a 2nd inside bay, that is not shared with LS Customs.

Additionally, I would like to get a copy of the current Harmony Exterior to make additional improvements (Improved outside Bay and Addition of Ait Pump)

**Comment by antihero6713** [comment]
Will talk with meta and you cloud on getting this done
