### ISSUE TITLE
[peds/*] ADD an AMROR FOR A GANG( Black Mafia) 

### ISSUE THREAD

**Issue by Gust123Battle** [InZidiuZ/legacy-assets-issue-tracker#675]
**Name:**
Who is suggesting this? Please include discord name.
BattleGust#0565
**Summary:**
Write a short summary of what your suggestion is about.
So We want to add an armor for an Black Mafia it is an gang in legacy roleplay india. We wanted this armor to be in legacy roleplay india because we think that it will give us a good and quality RP for our gang and we have no Black Mafia named jacket/shirt/pant/mask/armor so we are highly requisition to get that armor on legacy roleplay india. THis armor is already on Legacy but we wanted a new texture of that in that our name and logo will be changed. Also The armor ID-31 in legacy roleplay india so it is a request to add that armor

**Link:**
If there are any links to what you're suggesting, please add them here.
The armor PIC
![IMG_20220912_234057](https://user-images.githubusercontent.com/95690117/189860029-8ac0cbf4-8474-4574-85c1-0bc6d5978460.png)
In this armor. Where BlackWater has been written in front and rear we want BlackMafia on that with same font and thickness
and in LEFT where there is a LOGO we want our logo that is attached below

![Picsart_22-09-13_00-20-11-656](https://user-images.githubusercontent.com/95690117/189860271-669e3168-46c0-48de-8d32-1fef3300b842.png)

**Reason:**
Why would your suggestion be a good addition to Legacy?
It will be a good change in legacy roleplay india becuase it will give more Gang RP. It will improve our RP also. People can recognize us by our armor

**Comment by DaxterPancake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Black Mafia Armour](https://trello.com/c/eD0rCLEs/61-black-mafia-armour)

**Comment by Gust123Battle** [comment]
@DaxterPancake what is this?

**Comment by DaxterPancake** [comment]
> @DaxterPancake what is this?

It just means I have added it to our list of things to look at.

**Comment by Gust123Battle** [comment]
@DaxterPancake Ok So if it gets added by any chance so it going to be added on next patch/changelogs?

**Comment by DaxterPancake** [comment]
There is no ETA on when or even IF this will be made.

**Comment by Gust123Battle** [comment]
@DaxterPancake ok. will i get a msg  if it is added or not

**Comment by antihero6713** [comment]
This ticket will be closed with a comment to let you know "IF" it is made or progress.

**Comment by Gust123Battle** [comment]
any info yet about the armor?

**Comment by MetaHatter** [comment]
> This ticket will be closed with a comment to let you know "IF" it is made or progress.

^^ This hasn't happened yet, so no.

**Comment by Gust123Battle** [comment]
Ahh ok got it, Wait do you mean that the Armor will be not made? If yes like can I know why?

**Comment by MetaHatter** [comment]
The ticket will be closed, with a comment, when it's completed one way or the other.  If the ticket is open, like it is now, it's pending and we're likely not even looking at it yet due to the long list of items ahead of this one.

**Comment by DaxterPancake** [comment]
This has been done and will be live on the next update.

![image](https://user-images.githubusercontent.com/50828532/195781583-05f53c4a-a26b-4f2a-97cc-69484b19551e.png)
