### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MrSnowSar** [InZidiuZ/legacy-assets-issue-tracker#676]
**Name:**
$now, $now#1588

**Summary:**
Me and my friends own a mansion at Sam Austin Dr (West Eclipse Blvd) and it has a very nice terrace up on the roof. The only issue is that you physically cannot access it. That's why I would like to ask for a ladder to be added to the side or the back of the house. 

**Link:**
https://cdn.discordapp.com/attachments/968064715098038333/1021428454253678632/unknown.png

https://cdn.discordapp.com/attachments/968064715098038333/1021428601213689876/unknown.png

**Reason:**
This would be a good addition to the house as it's a good spot for meeting people and talking about business or just discussing anything in general. It would also open so many new doors to RP as there's a lot of things you can do with that. The main reason why we'd want this is because as stated.. We're part of an organization and being able to host FORMAL meetings up on such a nice terrace would be amazing.

**Comment by GodyFromDiscord** [comment]
This has been done.

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/191166047-200f83d1-06d5-463e-a004-e5211ab1c70e.png)


This has been done
