### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by VICKYSOHAM** [InZidiuZ/legacy-assets-issue-tracker#677]
**Name:**
𝓥𝓘𝓒𝓚𝓨 #4482

**Summary:**
I am getting some glitch in the City Gun Run. i am giving right key but it is saying wrong key dont know the reason
**Link:**
https://youtu.be/PdozY0S3lp0

**Reason:**
If u please fix this issue then we can cointinue our rp. thanks!!

**Comment by GodyFromDiscord** [comment]
Closing and completing it only just spams the GitHub channel, it will be looked into. Can you try using the keys from your pockets using 1,2,3,4,5

**Comment by VICKYSOHAM** [comment]
no i have not tried like that but i have tried 1 by 1

**Comment by GodyFromDiscord** [comment]
Try doing what I said and see if it works

**Comment by VICKYSOHAM** [comment]
oke!!

**Comment by VICKYSOHAM** [comment]
no it is not working first time 1 set is oke but when i have done another set the third key is saying wrong,

**Comment by DaxterPancake** [comment]
Sorry for the delay, this is the wrong github for this. You'll need to report this on the correct github [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
