### ISSUE TITLE
[maps/prison] Prison Collision 

### ISSUE THREAD

**Issue by LOUIS70K** [InZidiuZ/legacy-assets-issue-tracker#679]
**Reporter:**
LOUIS 70K#5540

**Summary:**
Prison Collision broken in a few places 

## Additional Information

**Screenshots:**
![image](https://user-images.githubusercontent.com/86194621/192167289-5d2a200d-ffda-47db-8925-6d89ce0fa2d5.png)

**Notes:**
there's other parts of the prison that collision is broken I am unable to get to them locations.

**Comment by GodyFromDiscord** [comment]
Are you able to give a rough location of the other broken collisions

**Comment by CloudTheWolf** [comment]
I believe there are a lot of broken/missing collisions as well as a few double doors/gates.

Honestly, would probably easier to list off what is _not_ broken xD

**Comment by GodyFromDiscord** [comment]
need a whole prison revamp

**Comment by LOUIS70K** [comment]
> Are you able to give a rough location of the other broken collisions

everywhere which isnt the cell block and infirmary ,tbh i was looking to buy a new prison for legacy

**Comment by GodyFromDiscord** [comment]
> > Are you able to give a rough location of the other broken collisions
> 
> 
> 
> everywhere which isnt the cell block and infirmary ,tbh i was looking to buy a new prison for legacy 

As nice as that is a lot of the prisons available for purchase are escrowed meaning when purchased we don't have direct access to files, more like a license to use it, so I'd consider that and ask one of us before possibly wasting your money.

A lot of the issues are known and a whole prison overhaul for collisions is basically needed and it will most likely be worked on soon.

**Comment by LOUIS70K** [comment]
> 

yeh thats what i want to do, i just dont know who to ask to see if its possible

**Comment by GodyFromDiscord** [comment]
> > 
> 
> 
> 
> yeh thats what i want to do, i just dont know who to ask to see if its possible

Any of the map devs which would be Myself, @antihero6713 @MetaHatter 

Everyone will see it and one person will get back to you with the answer for any that you find

**Comment by LOUIS70K** [comment]
> > > 
> > 
> > 
> > yeh thats what i want to do, i just dont know who to ask to see if its possible
> 
> Any of the map devs which would be Myself, @antihero6713 @MetaHatter
> 
> Everyone will see it and one person will get back to you with the answer for any that you find

ah aight bet the most i can get you is a YT video showing the place about everything else is stuck behind a payment

**Comment by GodyFromDiscord** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > yeh thats what i want to do, i just dont know who to ask to see if its possible
> 
> > 
> 
> > Any of the map devs which would be Myself, @antihero6713 @MetaHatter
> 
> > 
> 
> > Everyone will see it and one person will get back to you with the answer for any that you find
> 
> 
> 
> ah aight bet the most i can get you is a YT video showing the place about everything else is stuck behind a payment

That's fine we should be able to find out more from it

**Comment by LOUIS70K** [comment]
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > yeh thats what i want to do, i just dont know who to ask to see if its possible
> > 
> > 
> > > 
> > 
> > 
> > > Any of the map devs which would be Myself, @antihero6713 @MetaHatter
> > 
> > 
> > > 
> > 
> > 
> > > Everyone will see it and one person will get back to you with the answer for any that you find
> > 
> > 
> > ah aight bet the most i can get you is a YT video showing the place about everything else is stuck behind a payment
> 
> That's fine we should be able to find out more from it

bet ill send you it rn

**Comment by GodyFromDiscord** [comment]
So we spoke over Discord regarding this and I've spoke to Antihero as well. To protect you from potentially being scammed or falling into an Escrow trap we won't be having anyone purchase custom MLOs for the prison, instead we're going to work on the prison we have.

Once I've finished [Cherry Popper](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/655#issuecomment-1257340377) I will be taking on the prison as a bigger project. Like we discussed any map related things you want to suggest including rooms and new props around then please leave them here. There is no set date to when work will be stated on the prison but it'll be added onto my project list

**Comment by AmmoOgre** [comment]
If we could get a couple Padded Cells for 5150 cases that would be great for rp for prisoners that are going insane and need to talk to therapists, also if we could get a garage put in for personal vehicles so that we're not having out cars towed away every time we go to work.
