### ISSUE TITLE
Mazda RX7 livery glitch

### ISSUE THREAD

**Issue by Reece0318** [InZidiuZ/legacy-assets-issue-tracker#68]
**Reporter:**
Reece#8811
**Summary:**
When completing a repair or taking out the car from the garage, a red livery always comes back and then you have to go to bennys to take it off

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Aspratic** [comment]
wish this was fixed ;(

**Comment by Cricketx818** [comment]
Does this car have a stock livery?

**Comment by Karpenkooo** [comment]
Hey, 

I seem to have fixed this issue now! However, it may cause texture issues in the future. However, it shouldn't. 

_**Karpenko - OP FW Assets Developer**_
