### ISSUE TITLE
[vehicles/*] Aerial roof markings for Emergency vehicles

### ISSUE THREAD

**Issue by V4P1Dx69** [InZidiuZ/legacy-assets-issue-tracker#681]
**Name:**
*V4P1D#2280*

**Summary:**
*Aerial roof markings for Emergency vehicles*

**Link:**
[Link](https://media.discordapp.net/attachments/737166983384137738/1025382269466189856/unknown.png)

**Reason:**
Why would your suggestion be a good addition to Legacy?
Aerial roof markings would be very helpful for the air units to recognize their nearby units properly.
For example, in the case of searching an area for a suspect, the helicopter might see the suspect, radio down, and say “122, he’s in the back yard immediately to your right”. Without that aerial markings, by the time they finished describing which car they were talking to, the guy could be two states away.
That's just a simple example of how this aerial number can help in pursuit or any kind of cop situation.

**Comment by ThisIsNotDex** [comment]
I know this is really old but basically from what Joe has said in the past, it's possible, **but** it wont be done because that would require _a lot_ of extra liveries being added. (Too many assets or streamed somethings idk know the right word)

**Comment by joevapes3** [comment]
yah unfortunately at this time this isn't something we can fesibly do. If and when this becomes a possiblity I will be first to jump on the oppertunity, but for now it's something that is whishful vs practicle given the amount of work it would take to be possible. Thanks again for the suggestion.
