### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by AddyxScott** [InZidiuZ/legacy-assets-issue-tracker#682]
**Name:** Addy Scott (TLMC) 
Who is suggesting this? Please include discord name.

**Summary:** want to change tlmc jacket to this one ( pic in links ) 
Write a short summary of what your suggestion is about.

**Link:** https://cdn.discordapp.com/attachments/1015595489607041084/1025409388229439559/Screenshot_20220729-102413_YouTube-1.jpg
If there are any links to what you're suggesting, please add them here.

**Reason:**  didn't like this jacket old one is better but need new pic in links and want to change  
Why would your suggestion be a good addition to Legacy?

**Comment by DaxterPancake** [comment]
My group purchased that vest and we will not be re-adding it. Not only that but the new current group spent their own money to purchase this new one for all the subdivisions so I will not be changing it or removing it at this time.
