### ISSUE TITLE
O'Malley's Picture Change

### ISSUE THREAD

**Issue by HawkALoogieSoup** [InZidiuZ/legacy-assets-issue-tracker#683]
**Name:**
Bart Johnson Owner of the O'Malley's    (  HawkALoogieSoup#3910  )

**Summary:**
We have a photo in the bar that we would like to be changed to something more fitting for the bar
**Link:**
https://cdn.discordapp.com/attachments/732645123153723396/1026733739784544306/OldPhoto.PNG  OLD PHOTO
https://cdn.discordapp.com/attachments/732645123153723396/1026661513613807726/Darraghcrop2.png   PHOTO WE WANT

**Reason:**
The photo we want overall fits into the bar better, but it also is a photo of a bar patron and business partner that has left the city to start a new chapter in his life. Overall it would make myself and others really happy to have the photo hanging in the bar.

**Comment by MetaHatter** [comment]
I would prefer not to have any individuals from one region in building photos as it might affect RP in other regional servers.

**Comment by HawkALoogieSoup** [comment]
That's alright I don't want to mess with other people's experience. The bar can do without the photo.

**Comment by antihero6713** [comment]
thanks for understanding.
