### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by cupcade** [InZidiuZ/legacy-assets-issue-tracker#684]
**Name:**
Who is suggesting this? Please include discord name.
(づ｡◕‿‿◕｡)づ#8836

**Summary:**
Write a short summary of what your suggestion is about.
Being the new owner of TeQui-La-La I would like to see if some new things are able to be added to the menu. 
The list:
pigeon milk
canned beer
green tea shots / sour mix
pickles
tacos
pizza 
nachos
wings
french fries
peanuts
chicken tenders
salt
sugar
cranberries, oranges, and limes at the fruit stands

**Reason:**
Why would your suggestion be a good addition to Legacy?
Personally, I feel the suggestion would be a wonderful addition to the quality of roleplay. Having bar food at a bar would be fantastic as at the current time we only have sandwiches. Some more fruit at the fruit stands would be amazing so we could do cranberry vodka, salt and limes to go with the tequila, and oranges for screwdrivers.

**Comment by twooot** [comment]
First of all, this is the asset github. Second of all, that is a ginormous list of items which in the end will all have basically the same functionality/effect. The bahama mamas has, just like all the other bars mainly alcoholic drinks and a few small food items. I'm not adding more food items cause its not a restaurant and i'm not adding more items that simply have a different icon and name but the same functionality. You can provide great RP with that bar even without your huge list of wanted items
