### ISSUE TITLE
[?] Police dummies Red and Green

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/legacy-assets-issue-tracker#685]
Summary:
Could colored dummies be added to the PD armory, Red and Green dummies specifically? Training purposes

Reason:
Having the ability to have green and red dummies inside the PD locker would be a great asset for SWAT/PD training purposes. We can use green dummies in place of Civs, and red as Criminals. These could also be used at the weekly SWAT/PD training that takes place. In place of hostages so we don't have to use live hostages (PD personnel) in training situations. In SWAT/PD our emphasis is put on being the frontline this also includes breaching buildings, having Dummies to use as Civ and Criminal would benefit in training situations as we can prepare them to hopefully not shoot Innocent people.

**Comment by InZidiuZ** [comment]
The current dummies are native & I can't find any native red and green ones. Antihero would have to make custom props for this to be added.

**Comment by antihero6713** [comment]
This is on my TODO list. More so then changing the color. I had planned to make a set of mannequins.  1 with their hands up, 1 pointing a gun. 

Would their be any other setup you want to try to do let me know.

**Comment by antihero6713** [comment]
https://cdn.discordapp.com/attachments/697579213628244008/1028031133927096350/unknown.png

These have been added this should get the job done

**Comment by InZidiuZ** [comment]
They've now been made available in-game!
![zv5E0fho](https://user-images.githubusercontent.com/22295402/194697275-6ecb5875-7815-4cca-a155-5616f31f3900.png)
