### ISSUE TITLE
can we get oxy as business , by giving a table or something in which we can make oxy and supply to other gangs or local people 

### ISSUE THREAD

**Issue by AddyxScott** [InZidiuZ/legacy-assets-issue-tracker#687]
**Name:**
Who is suggesting this? Please include discord name.

**Summary:**
Write a short summary of what your suggestion is about.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by GodyFromDiscord** [comment]
mate there's a format for a reason, you can supply it to other gangs in rp... ?

**Comment by DaxterPancake** [comment]
This is the incorrect github for this suggestion.

Please post it [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
