### ISSUE TITLE
Automatic Car Rental Service at Garages. 

### ISSUE THREAD

**Issue by DopeIndar** [InZidiuZ/legacy-assets-issue-tracker#688]
**Name:** DopeIndar ( AreshK#1824 )

**Summary:**
Having an option to rent a Basic Car/Bike at Garages in Garage Menu.

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Players those who don't own a Vehicle will Kill Civillian very Often just for the Car which is very unrealistic. Adding an option to Rent a Car/Bike will make a Huge difference in Legacy RP Server and players will not kill/hijack a civilian very often they'll ride their own vehicle and also they will not dump this vehicle anywhere just to get another one if it gets Damaged.
         This is how i think it will work :- When you open a garage menu there will be an option to Rent vehicle Either a 2 wheeler or a 4 wheeler. Once a rent vehicle is withdrawn the player will have keys to it just like Giving a car for test drive at PDM the difference will be Money deducted for a rental service will not be given back to the player.

**Comment by ayushpatel1007** [comment]
I think this will not make any difference, let me tell you why.

1st of all those who don’t have vehicles will take this cars on rent , right ? But if we see those who are new in legacy will don’t have car and as they are new to city , they will be not earning much. They will think simple like why would I rent a car if I can get one for free? And you telling that we just give them key like pdm test drive. Better is that they can store car in garage. They can pay rent of car like houses from their tablet (/companies) and use that car for week or month or year by just paying rent of that car. 


Now here some people will think that this will decrease pdm rp. So for this we will only give low performance cars that locals have for example on rent. If they want good cars then they have to go to pdm/LA/Tuner.

**Comment by superiorchicken007** [comment]
I will agree I don't think this should be an option.  When people are new to the city they already get a **free** car.  If they want a 2 week or 4 wheel car they can buy cheap ones at PDM which increases RP.  With the option to "rent" vehicles at any garage is just denying RP from PDM.  

If we are talking about renting cars I would like to see an option through  PDM where someone can "rent" a vehicle for $XXXX and will give them access to that vehicle in the garage for 1 week unlike a test drive where it is only so often.  If they like the vehicle they can go to PDM to purchase their vehicle out.  However long they rent the vehicle will not come out of the cost/finance of the vehicle and will still have to pay the full amount.  This will give citizens the option to try out a vehicle for a longer period to decide if they want that particular vehicle and it will give more RP to PDM employees.

**Comment by DopeIndar** [comment]
> Name: Kantibhai
> 
> I think this will not make any difference, let me tell you why.
> 
> 1st of all those who don’t have vehicles will take this cars on rent , right ? But if we see those who are new in legacy will don’t have car and as they are new to city , they will be not earning much. They will think simple like why would I rent a car if I can get one for free? And you telling that we just give them key like pdm test drive. Better is that they can store car in garage. They can pay rent of car like houses from their tablet (/companies) and use that car for week or month or year by just paying rent of that car.
> 
> Now here some people will think that this will decrease pdm rp. So for this we will only give low performance cars that locals have for example on rent. If they want good cars then they have to go to pdm/LA/Tuner.

I meant rent a car not take a car on lease ! Renting will be for few hours like Once the Server Re-starts The Car is Gone. Second thing about free cars they dont use it they use it to for Storage. Rental service is necessary I reckon. Am not saying like rent any car am talking about only basic vehicles like In 2 wheelers bati 400 or Sanchez and in Cars Premier or Surge Cheval.

**Comment by DopeIndar** [comment]
> I will agree I don't think this should be an option. When people are new to the city they already get a **free** car. If they want a 2 week or 4 wheel car they can buy cheap ones at PDM which increases RP. With the option to "rent" vehicles at any garage is just denying RP from PDM.
> 
> If we are talking about renting cars I would like to see an option through PDM where someone can "rent" a vehicle for $XXXX and will give them access to that vehicle in the garage for 1 week unlike a test drive where it is only so often. If they like the vehicle they can go to PDM to purchase their vehicle out. However long they rent the vehicle will not come out of the cost/finance of the vehicle and will still have to pay the full amount. This will give citizens the option to try out a vehicle for a longer period to decide if they want that particular vehicle and it will give more RP to PDM employees.

Do they buy Cheap Cars ? No, they don't they grind first and Buy a good looking car till then they'll just Hijack and Dump those cars on roads or Parking areas. PDM renting is a thing but no one does it because it's not proper and PDM employees are not present everytime and also those cars cant be Stored in the garage

**Comment by MetaHatter** [comment]
With players getting a free car, the ability to test drive cars in PDM and purchase cars outright in PDM, EDM, and Midnight and call a taxi (job overhaul is currently in progress), the ability to get transportation is more than covered.  

Retrieving a car is essentially the same as what you are proposing.  "Acquire transportation for a non-refundable fee".  I, personally, think it's better for the economy that people have to own multiple cars for this purpose.

We also want people to interact with other people.  Providing this rental option will reduce the need to call a friend, taxi, wave down another car or any number of other possible interaction points, including, interacting with car salespeople.
