### ISSUE TITLE
Suggestion - Roadflares

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/legacy-assets-issue-tracker#69]
**Name:**
Cyberskunk#5173

**Summary:**
So I've been in a lot of different situations now where I felt like I really needed roadflares to make my work easier as a Police Officer. For example traffic accidents, blocking roads, re-directing traffic and even bankrobberies at evenings/nights, where I can put them down to make the "line" way more visible for civilians.

**Link:**
Here's a link for what I mean or that perhaps could be to any use.
https://forum.fivem.net/t/release-road-flare-realistic-slows-down-ai-cars-nearby/249503

**Reason:**
I believe this would improve the RP for the police and the surrounding civilians as it looks realistic and is very useful. This mod example I linked even makes the npc stop(?).

**Comment by psyCOSMO** [comment]
Would like an animation with a flash stick aswell

**Comment by Karpenkooo** [comment]
Hey,

This sounds really cool and i'm all up for this getting added however... This is the wrong GitHub page for that :) Just re-write it on @InZidiuZ  and hopefully it get's added in the near future. 

_Karpenko_

**_OP-FW Assets Dev_**
