### ISSUE TITLE
[peds/*] Add old TLMC jacket also in server for better Quality i

### ISSUE THREAD

**Issue by Rocky9Lockwood** [InZidiuZ/legacy-assets-issue-tracker#691]
### Name

XHarsh#1283

### Summary

We need are old + some new additional jacket in server for TLMC as the new one looks little bad they are good but everyone does not like it so we request to add the old once also and some new jacket links are given below you can see . 
Also add a tattoo ingame for the gang members if they want then can use . 

### Link

https://www.gta5-mods.com/player/lost-mc-biker-vest-with-template
https://www.gta5-mods.com/player/the-lost-mc-bikervest 
https://www.gta5-mods.com/player/swedish-the-lost-mc-tattoo  

### Reason

As everyone does not like everything so its Good to take old + new at same for good.

**Comment by Rocky9Lockwood** [comment]
Any update sir .

**Comment by DaxterPancake** [comment]
The current Lost MC kuttes are going to stay for the moment. I will revisit this when I re-do all clothing at a later date.
