### ISSUE TITLE
[vehicles/police] Nerf PD Enduro Bike OR Buff other bikes

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/legacy-assets-issue-tracker#693]
### Name

Dex#5879

### Summary

Currently, the new PD Enduro bike can do about 155mph on a bumpy city road, without a wheelie or leaning forward. Most other bikes from PDM, can barely hit 120 stock, and around 130-140 upgraded, and maybe 150 while in a wheelie. If this PD Enduro bike were to chase someone's fully upgraded shinobi for example, just on a performance level, the enduro will smack any other bike around like it's nothing.

### Reason

Honestly, I think the more logical option would be to nerf the PD bike, rather than buff civ bikes, it'll be easier, and quicker, as well cop cars will still be able to somewhat keep up with bikes.

**Comment by joevapes3** [comment]
Pd bike is balanced to the crim bikes, it's been tested. While yes the pd bike has more top speed, that's not what bike getaways will be won with. It will come down to acceleration and turning utilizing alleyways and narrow passages. This makes it so PD bike is also effective against car chases is the reason for the higher top speed. Crim bikes already are a formitable foe to chase against and when bikes are used in getaways crims getaway about 75% of the time.  The accelleration and turning of the PD bikes is balanced around crim bikes. Changes will be happening more bikes handling soon, but they will be very similar to the new EDM bikes that were pushed in the latest pack. If you want an idea of how they will be I recomend testing those to get an idea.
