### ISSUE TITLE
[vehicles/random_vehicles] Vehicle Report Koenigsegg Gemera not Getting Damage

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/legacy-assets-issue-tracker#694]
### Reporter

RaviCan'T#0001

### Summary

Koenigsegg Gemera (gemera) is not getting any projectile damages does not matter if u try to shoot it or put it inside Gas Pump It will never blow up.

### Screenshots/Videos

https://img.ravicant.in/u/FTzDYr5.jpg - Before any damage
https://img.ravicant.in/u/2piy1u6.jpg - After 
https://img.ravicant.in/u/2wFTrPB.jpg - After using NOS

**Comment by joevapes3** [comment]
Yah this car wont take any damage, this is a one of one car that was added for our community manager Sia. So it was not meant to be given out beyond her use cause it doesn't take any damage like other vehicles do. So I am not gonna be able to make any changes to this vehicle and I would suggest not giving them out to be used. Any vehicles not found in EDM, PDM , or the Casino may fall under this catagory and shouldnt' be used or given away in the servers, and these vehicles can also be added or removed at any time so there is no garuntee that they wills stay in someones garage if given. Anyways, sorry for any inconviences this may cause but to avoid this from happening, stick with vehicles listed in EDM, PDM, and the Casino rotation in the future.
