### ISSUE TITLE
[vehicles/police] Add a new PD Dodge Durango

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/legacy-assets-issue-tracker#695]
### Name

Dex#5879

### Summary

New PD Durango to secure wins in the cops vs. robbers game mode.

### Link

https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/41289-2018-dodge-durango-pursuit-non-els/

### Reason

After the 13 tahoe was retired, we have been missing another SUV from the fleet, this car could be it's successor.

**Comment by joevapes3** [comment]
I've explored the possiblity of getting a Durango but there isn't any decent models available at the moment. I don't have any itentions of converting a model right now. The model you suggested isn't the best quatility and would take more work than it's worth to make useable, but if you happeen to find a better detailed model then we can possibly considere it at a later time. I've reviewed almost all the models that are available and none of the are quality enough to be utilized, but keep your eye out on future releases by vehicle developers and let me know what you see. Thanks again for your suggestion.
