### ISSUE TITLE
[maps/mirror_park_auto] Workbenches

### ISSUE THREAD

**Issue by vixoni** [InZidiuZ/legacy-assets-issue-tracker#697]
### Name

Flaca#7350 

### Summary

Workbenches not functional for outdoor bays - 

We have 3 outdoor bays out front but no workbenches directly accessible for them. 

There are indoor workbenches within the building but they are not easily reached and require the employees to run through doors and rooms for every car part they need to craft. 

If a workbench can be added in the same area of our outdoor bays this would make the process of crafting car parts seamless and functional.

There is a room off to the very right side of the building that has two workbenches which are not being used as they are not near any repair bays. If these 2 unused workbenches can be repositioned to sit where our outdoor bays it would be ideal. 

Simply put:
- In need of a functioning workbench that sits in our outdoor bays 
- There are 2 unused functioning workbenches that can be relocated

![MP Outdoor](https://user-images.githubusercontent.com/118861073/203449493-74e4c29c-e53a-4e14-8ccd-c208f35d5b23.png)

![MP Non-functioning](https://user-images.githubusercontent.com/118861073/203449490-3b0a218a-e85c-47e9-838f-6933f6d5064b.png)

![MP Room Benches](https://user-images.githubusercontent.com/118861073/203449496-027fbb5f-b1b0-4b85-bb97-ad87c9a9e051.png)

### Reason

This relocation of workbenches would allow us mechanics at Mirror Park to use our repair bays in a quick and functional manner - shortening repair times and boosting customer/employee satisfaction. This would eliminate the event of customers waiting on our mechs to run through the building for every window, door, or tire they need for their repair.

**Comment by CloudTheWolf** [comment]
So I spoke with Ruby on this and suggested the following:

1 - Remove Workbench functionality from the 2 benches in pic 3
2 - Move the second workbench from the inside bay to the outside bench (see below)
![image](https://user-images.githubusercontent.com/7809366/203542393-7b98b654-ba0a-4671-9478-6c4c43f1478e.png)

**Comment by vixoni** [comment]
Awesome, that'd be great!

**Comment by InZidiuZ** [comment]
This has now been done.
