### ISSUE TITLE
[vehicles/?] Gruppe 6 Vehicles

### ISSUE THREAD

**Issue by JohnBaker456** [InZidiuZ/legacy-assets-issue-tracker#698]
### Name

X-ray#0010

### Summary

about adding gruppe 6 vehicles in the server

### Link

https://forum.cfx.re/t/release-gruppe6-security-cars-addon-pack/52574

just an example of what kind of vehicles i am talking about

### Reason

it would improve the experience and quality rp and me i have been doing security rp for like 1 year in other legacy servers so i thought lets move here so here am i been doing the security rp in main server for a while and i think it would motivate the people and me that are supporting me so we could improve the rp experience trying to have something new in the city and i also support other people that do something new so they continue making the rp better and i recommended this since it would really help us out and honestly i was thinking of a gruppe 6 job but i thought it's just not worth it since it wouldn't get added but i think it's the same thing with this but it is what it is ;/

**Comment by coalaura** [comment]
These are basically PD cars just different liveries. No
