### ISSUE TITLE
PD Cars Handlings

### ISSUE THREAD

**Issue by muzarz** [InZidiuZ/legacy-assets-issue-tracker#7]
**Reporter:**
Puceto - pxyeb.#8125

**Summary:**
Some of the police cars have good handling now which is not capped at 150mph but I have noticed that SWAT Explorer, unmarked charger, white SASP/SAHP/Sheriff charger is capped at 145mph when accelerating. Haven't tested all the cars but if we could get this changed or looked at it would be great as the other cars have a great handling now.

**Notes:**
Some of the cars are fine but some of them are not. I think they might be different assets which causes some of them to be capped. This is only regards PD cars.
PS. PLEASE add PD unmarked schafter back :(

**Comment by RGDaviid** [comment]
Hey Puceto,

I've looked into this bug and i can now say that it's been fixed. Thank you for bringing this to my attention. However i will not be adding the Unmarked Schafter just yet. However i may look into it.

**Karpenko**

**_OP-FW Car Developer_**
