### ISSUE TITLE
Bug report - No mini map after new update

### ISSUE THREAD

**Issue by SunnySingh474** [InZidiuZ/legacy-assets-issue-tracker#70]
**Reporter:**
Hi, my discord name is SUNNY #5030.

During our garbage collector mission, when it says, "Return to HQ" Minimap gets disappeared. Please fix this we need a mini-map to know if we are going in the right direction or not.

Thank you

**Comment by AdeptCL** [comment]
When you get back into the garbage truck, the minimap re-appears.

**Comment by SunnySingh474** [comment]
When we go on a mission to collect garbage at certain point and we collects it, it works fine. In cases when we reach at collection point and it directly says, Return to HQ" at that time mini map disappears.

**Comment by AdeptCL** [comment]
Shouldn't need a mini-map to know where the HQ is... considering you start the job there...

**Comment by Karpenkooo** [comment]
Hey,

This issue was posted on the wrong GitHub page. You'll need to re-write on in InZidiuZ's bug report. Use his template too.

_Karpenko_

**_OP-FW Assets Dev_**
