### ISSUE TITLE
[maps/mirror_park_auto] Water Cooler for Mirror Park Autos

### ISSUE THREAD

**Issue by vixoni** [InZidiuZ/legacy-assets-issue-tracker#701]
### Name

Flaca#7350

### Summary

Currently do not have a water cooler at our shop and we believe this would be beneficial to our employees & customers. This would help greatly with keeping everyone hydrated to avoid interruptions mid repair.

### Reason

All the businesses that I know of have a water cooler placed and would like to suggest adding one to Mirror Park Auto Repair shop  to keep all our employees and customers hydrated.

**Comment by Swaiid** [comment]
Since the place has been opened we've had a tonne of customers come in asking for a water cooler as well and most if not all other businesses have one so I think this'll be a good addition to have.

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/210124207-40722e6a-c1fa-4649-865b-f6798335091d.png)
will in next update
