### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by IsDaniBoi** [InZidiuZ/legacy-assets-issue-tracker#703]
### Reporter

IsDaniBoi#1643

### Summary

The audio when you lock/unlock cars sounds distant when the car is moving. While standing still in a car I can hear it fine but once I pick up speed it sounds distant but if I place my camera to the left or right side of the car then I am able to hear it.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this.
