### ISSUE TITLE
[vehicles/civilian_5] 2020 BMW M4 Infiniti Q60 Black S 

### ISSUE THREAD

**Issue by IsDaniBoi** [InZidiuZ/legacy-assets-issue-tracker#706]
### Name

IsDaniBoi#1643

### Summary

So I just bought the 2020 BMW M4 Infiniti Q60 Black S from EDM and was wondering why it is so slow. Idk if the car is meant to be a drift car because of how easily it slides out plus the slow speed as well as the drift king livery. Was just hoping if it's not a drift type car it could be looked up and possibly tuned up a little as it struggles to hit the higher speeds.

### Reason

I think that takes out the value of the car meaning you'll never really see it around city which makes it pointless to have.

**Comment by joevapes3** [comment]
handling was updated on this vehicle and should be live
