### ISSUE TITLE
Improve Exclusive cars after update.

### ISSUE THREAD

**Issue by SunnySingh474** [InZidiuZ/legacy-assets-issue-tracker#71]
Hello,

My discord name is SUNNY #5030.

We are legendary players who are paying per month and our special benefits are premium cars. Me as a Legendary player grinding a lot just to purchase a supercar but now Lamborghini and Ferrari are not available. The car collection which you provided us after the update is really disappointing. 
If you want to make a change in the cars category then do it with PDM cars, not Premium cars because we are paying for these cars.
Does it happen in the real world, where a car showroom removes the availability of existing cars when new cars get launched? NO. In fact, they keep on adding options and choices.
Even in your update log, it says ADDED 12 NEW CARS. Logically it means in existing cars list you have added these 12 new cars. But in reality, what you guys have done is ADDED ONLY 12 NEW CARS AFTER REMOVING OTHER CARS.
I request you to please do something for your paid players who love to spend time in legacy and provide us an option, again to purchase Lamborghini and Ferrari. I understand you don't want everyone to buy Lambo and Ferrari but at least give us choice to purchase Lambo, Ferrari or Porsche or Bugatti.
Thank you

**Comment by AdeptCL** [comment]
It's an RP server. Not money grind server.
If you don't like the fact that an exclusive car like a Lamborghini no longer is available, then you're in the wrong place. It wouldn't be exclusive if everyone in the city was driving round in a Lamborghini.

If you didn't get it before the update, then unfortunately you've missed out.

**Comment by iGreatWhite** [comment]
You were told not to do it in discord and was muted. So you can’t to github to complain about the same thing?

**Comment by SunnySingh474** [comment]
See, don't say anything without understanding my point. I know its RP server. and I know RP rules very well. Here I am just suggesting what I felt is required. So, don't get aggressive try to understand what I am saying.

I understand your point too.
I am just saying one simple thing.  I understand you don't want everyone to buy Lambo and Ferrari but AT LEAST GIVE US CHOICE to purchase between Lambo, Ferrari or Porsche or Bugatti.

**Comment by AdeptCL** [comment]
But giving the choice will lead to that. If you didn't get it before it went, unlucky.

**Comment by psyCOSMO** [comment]
You need to fix your mindset about rp.

**Comment by Karpenkooo** [comment]
I'm just gonna leave this here. ¯\_(ツ)_/¯
