### ISSUE TITLE
[maps/?] Sandy Fire Department MLO

### ISSUE THREAD

**Issue by mastersamii** [InZidiuZ/legacy-assets-issue-tracker#710]
### Name

MasterSamii#3111

### Summary

Requesting the addition of the Sandy Fire Department into the server with some Minor adjustments. I'd like to request the walls either be shortened or removed completely. I would also like to request that the texture of the pavement on the parking lot match the street of Sandy so it blends in better. This addition would be the "home base" for BCFD (Blaine County Fire Department) which the roleplay has been ongoing for over a year now. We've already received development from a scripting side for our firetrucks and etc and would appreciate a building as our home base. I have the file if you would want to look at it and dm me.

### Link

https://www.youtube.com/watch?v=fxunu739Op8

### Reason

- We have already received some minor scripting work for the Fire Department with our own jobs, vehicles, etc. Something that was talked about a while ago was a possible fire script that will be in the works at some point. This building would be our final addition that would also help encourage the roleplay of the fire department. 
- The reason I would like the wall adjusted/texture of the pavement to fit more into the Sandy Vibe. I'm not sure how much work it would take but I would imagine simply deleting something isn't as bad as retexturing the parking lot
- My department already bases itself in sandy where we do training, classes, and our own work up there. As I said before, the roleplay has been started for over a year now and we've kept consistent with it. To my knowledge, there aren't "too many" additions up in Sandy, so I feel with the adjusted changes would bring some more roleplay up to Sandy with this building's addition
- We also paid $60 for the MLO so we would appreciate it if you could help us! It isn't Escrow locked or anything

**Comment by mastersamii** [comment]
I would like to add to this that the Blaine County Fire Department has officially split away from EMS to pursue more RP down the fire avenue we have lots being made on our end such as pieces of training, sops, certs all that jazz, and really need a base of operations that has the ability to house firefighters.

**Comment by CloudTheWolf** [comment]
Mapping work has been done and passed to Anti, just needs reviewing and implementing (Setting door locks, spawners etc)

**Comment by MetaHatter** [comment]
@antihero6713 Is this complete now?

**Comment by antihero6713** [comment]
done for what it is
