### ISSUE TITLE
[maps/?] Nikola Place 1 - For Sale sign in front garden

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/legacy-assets-issue-tracker#711]
### Reporter

Smiithy#4779

### Summary

I bought a property and the for sale sign has not been removed. Spoke to Estate agent who linked me to Arteria and they said it wasn't something they had access to. They recommended I post the issue here. I have attached an image of the issue and yeah not sure what else I need to provide

### Screenshots/Videos

![Nikolai For Sale Signs](https://user-images.githubusercontent.com/32597507/214049823-4e7ef6bf-0fdd-4eb5-ae24-17e40074dd89.png)

**Comment by InZidiuZ** [comment]
This is not a bug, the 'for sale' sign is not meant to go away just because the house is owned.

**Comment by antihero6713** [comment]
What ben said, Its pretty much part of the map and will not be fixed. We dont want to stream that ymap for that change.
