### ISSUE TITLE
[maps/hayes_autos_body_shop] Hayes Garage/Parking/QOL Improvements

### ISSUE THREAD

**Issue by RetroCharles** [InZidiuZ/legacy-assets-issue-tracker#713]
### Name

RetroCharles#7232

### Summary

The suggestions below are for the quality of life for Hayes Auto Body customers and employees. These requests are to better the experience for both customer and worker when coming into the shop. The main priority of this request is having an area to accommodate larger vehicles such as semi trucks to get a repair. 

### Repair Bays for Larger Vehicles/Semi trucks

**Suggestion 1:** If possible, to extend the bay entrance higher by deleting/editing the boxed areas so that trucks are able to pull into the shop without us having to use a Tow truck to place trucks inside. This process is a hit-or-miss. Trucks are damaged when not towed properly into the shop. 
![image](https://user-images.githubusercontent.com/91626825/216422330-8a4d36ee-4919-4bfb-9075-c81c1c99dd76.png)

**Suggestion 2:** Removing the two trees on the left of Hayes, and placing an outdoor bay on the side walk.
![image](https://user-images.githubusercontent.com/91626825/216422674-bff623f0-79c9-4e38-b1a5-36bc7c3b6f14.png)

**Suggestion 3:** Placing an outdoor bay behind the Hayes shop. We can deal with running to the back to repair trucks. As per [[old request](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/616)] it seems to be more work to implement a door/garage to access the back from inside the shop, if its do-able then by all means it would be even better to have a quick access to the backside, but if its too much we can cope with just walking around the back. 
![image](https://user-images.githubusercontent.com/91626825/216423181-e59402d0-e3d0-4fb1-8e33-d5aaeecd2fc8.png)

### Bay 3 Oil pit issues

**Suggestion:** Removing or patch up the oil pit located in Bay 3. The oil bay alone stops mechanics from repairing vehicles in that spot. due to the wideness of the oil pit, most cars (even when driving carefully) eventually falls into the oil pit. Leaving this area not functional for the shop.
![image](https://user-images.githubusercontent.com/91626825/216426710-b799b9bc-9bd0-4096-a115-7adc0be6ffb4.png)

### Issue: Garage door and Repairing 

The key used to repair a vehicle's engine conflicts with the garage door, causing the mechanic to lock the garage door while repairing. This issue causes awkward interactions between mechanic and customer being locked in, or having the customer ram into the garage door thinking its just not being "triggered". The garage door also locks when replacing any craft-able parts on a vehicle (doors, windows, tires) 
![image](https://user-images.githubusercontent.com/91626825/216427707-0b3446f5-c7b4-4de5-b0ff-08dacd7ce684.png)

### Parking lot near Hayes

Having a parking lot near Hayes can help clear the cluster of mechanic's and visitor's cars being parked on the sidewalks in front of the shop. It would be beneficial for the mechanics/tow drivers to have their tow trucks/rumpos parked close by as well. 

**Suggestion 1:** Parking structure behind Hayes
![image](https://user-images.githubusercontent.com/91626825/216429123-9fe53552-83b1-4dd2-a399-f1f3b23ff6d8.png)

**Suggestion 2:** Parking lot behind Hayes
![image](https://user-images.githubusercontent.com/91626825/216429260-cd1c9484-e537-4604-b088-bf8c4f88c20a.png)

### Jerry cans being able to be stored in lockers.
Having Jerry cans be part of the items acceptable in lockers, there are times cars come in for a repair after having a gas a leak, and the mechanics/customer has to run to a gasoline station just to bring back a jerry can so they can refill and leave the shop. 

### Reason

The suggestions above are for the quality of life for Hayes Auto Body customers and employees. These requests are to better the experience for both customers and workers of Hayes.

**Comment by gadjinee** [comment]
Could it be also possible to move the extinguisher away from ATM? 
We have a lot of customers struggling to get the cash out ever since the ATM's were updated as it picks up the extinguisher instead, also anyone who's the mechanic keeps locking / unlocking side door of the ATM due to it been so close.

The ideal place would be close to water cooler if that is moved ever so slightly 

Thank you

**Comment by gadjinee** [comment]
Hey, sorry to be a pain just was wondering if there's any updates regarding the request.

**Comment by antihero6713** [comment]
I will try to get the ATM stuff dealt with tonight

**Comment by RetroCharles** [comment]
Thanks antihero, hoping to see more continued work for Hayes!

**Comment by FruityND** [comment]
It would be great to see some of these ideas implemented. Hayes has become a very popular shop in the city as of recent and only having use of the two bays, due to the pit in bay 3, is impacting the amount of cars that can fit inside at the same time. It would also be great to be able to repair larger vehicles at Hayes which currently do not fit through the doors. So a larger door or an outside bay is a good solution for this. 

I hope this gets looked into :)

**Comment by MetaHatter** [comment]
Extinguisher by the ATM was removed. I added a grate to the oil pit and shaved the door frames a bit so the Phantom model trucks "should" fit inside.

**Comment by RetroCharles** [comment]
> Extinguisher by the ATM was removed. I added a grate to the oil pit and shaved the door frames a bit so the Phantom model trucks "should" fit inside.

Great news to wake up to! Thank you so much, can’t wait for the hayes team and customers to be able to fit their phantoms in!

**Comment by gadjinee** [comment]
Thank you so much! Can't wait to see the changes !

**Comment by elfinskate** [comment]
I think the request for a bigger parking area around the back side of the shop is a great idea as well. I think it would be a great addition for more customer interaction. Seeing other companies with easy access to bigger parking areas leads me to believe it would generate more revenue for us since sometimes I see people drive away when we are slightly busy since parking is tough. It would also allow better opportunities to hold events at the shop in the future.

**Comment by sahol21** [comment]
there are any update about garage behind the hayes

**Comment by DaxterPancake** [comment]
> there are any update about garage behind the hayes.this garage need badly for hayes employee and customers.

This is not an asset issue therefore will need to be made in the correct github found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).

**Comment by RetroCharles** [comment]
Apologies did not see this @DaxterPancake , I'll be posting the garage suggestion in the correct area. Thank you

**Comment by MetaHatter** [comment]
This looks complete.  Closing.
