### ISSUE TITLE
[peds/?] Fallen Angels Gang Clothing 

### ISSUE THREAD

**Issue by PerfectBarbie** [InZidiuZ/legacy-assets-issue-tracker#716]
### Name

SCE_PerfectBarbie#0666

### Summary

My gang would like to bring in custom flags and masks into the city. We would like to use the white masks we've always worn as a base for the design and add some aspects to it that make it unique to us and our gang. 
![mask rough](https://user-images.githubusercontent.com/124804317/217599798-5e15a3b4-0145-4aad-b8b9-ddd964bbf280.png)
I want to copy the blood that the arm ban has on the bottom of the mask ex. 
![arm band 2](https://user-images.githubusercontent.com/124804317/217599937-670324aa-bd7e-4235-aed7-e3914ac8f4f9.png)
![arm band](https://user-images.githubusercontent.com/124804317/217599938-829b7da7-4328-4014-828f-13a1669db0c1.png)
and copy the same design for the pocket flags as well

### Reason

 It has been an issue with other gangs trying to take the color we use as our flag multiple times, and we would rather provide good RP to the city then to fight over flags over and over. We want these so it's no longer an issue and whatever fights we do have in the city can be fun and meaningful. We've struggled with people switching just to fight us and we no longer would like to have to deal with this. Instead, we'd like to get back to our roots in providing good and unique RP to the city and these flags will help us continue that.

**Comment by DaxterPancake** [comment]
This has been done and will be added with the next clothing build!
