### ISSUE TITLE
[vehicles/?] sm722 turning is very poor

### ISSUE THREAD

**Issue by dhondujstchill** [InZidiuZ/legacy-assets-issue-tracker#717]
### Reporter

keyur95#0582

### Summary

the car doesn't turn properly the turning radius is very poor. while the car is in speed it doesn't turn at all can u guys just fix this

### Screenshots/Videos

https://youtube.com/clip/UgkxFV8hz5fqkmiV9u94iWw7j8LMiLnHYLHz

**Comment by dhondujstchill** [comment]
did the car fixed?

**Comment by joevapes3** [comment]
this issue hasd been resolved a few months back closing this ticket
