### ISSUE TITLE
Bug report - Vapid Flash GT Sports INVISIBLE

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/legacy-assets-issue-tracker#72]
**Reporter:**
Cyberskunk#5173

**Summary:**
Basically the named vehicle ain't showing when ever you enter a Customshop. It gets invisible and you're not able to customize it because of that.

## Additional Information

**Screenshots:**
![20191007203131_1](https://user-images.githubusercontent.com/50070645/66338840-35b9e780-e942-11e9-8853-57906490ef22.jpg)
![20191007203308_1](https://user-images.githubusercontent.com/50070645/66338849-394d6e80-e942-11e9-810d-d6e0ccc33da5.jpg)

**Notes:**
Please fix it, because that car is amazing!!

**Comment by Duroode** [comment]
Can you Try it with a different car, Im pretty sure the "not being able to see your car" bug is a One-Sync bug. Might be wrong.

**Comment by Lankovich** [comment]
Indeed it could be, because we got it to work in city 2 👌

**Comment by Karpenkooo** [comment]
Hey,

This does seem to be a one sync bug so for the time i will close this bug report. 

_Karpenko_

_**OP-FW Vehicle Dev**_
