### ISSUE TITLE
[maps/?] Nightshade-Row block

### ISSUE THREAD

**Issue by painxfps** [InZidiuZ/legacy-assets-issue-tracker#722]
### Name

painx#0001

### Summary

Hello,

We had a few suggestions for our block, we know that none of these changes will or are guaranteed to happen but I'm putting the request in case it's possible.

These changes are mostly for the benefit of the Nightshade in general but it's also good for RP-related stuff, we know that we are located very close to vinewood and these changes could cause headaches or stutters to people because of all the business but you never know.

these pictures aren't exactly what we want there more like reference pictures.

if there is confusion in these reference photos please reach out to me in discord or comment here I will make sure to keep checking but discord will probably be cleaner.

### Name (Block ID): Spanish Avenue Apt. Complex J (119)

**Front of the block**
[Our Logo](https://i.imgur.com/CAsh5qY.png)
[Logo in the block](https://i.imgur.com/2MwkCqA.png)
[Before](https://i.imgur.com/BLAHz48.png) -- [After](https://i.imgur.com/ukSJXJI.png)
**Reason:** ever since we bought the block we noticed a couple of weaknesses that are very bad and there is absolutely nothing we can do to defend ourselves if the gang decides to have a meeting or gang RP-related stuff inside the block. There have been multiple instances where people drive their cars backward inside the block and there is no way for us to defend ourselves or a place to run into so were basically defenseless adding the sandbags on top of the arch will help us have people stand there as a scout and watch the area while we are having our meeting in the courtyard.

**Access to the roof from inside the block**
[Before](https://i.imgur.com/ULklkjt.png) -- [After](https://i.imgur.com/7QA1PPa.png)
**Reason**: The reason why we want access to the roof by foot to be from the inside the block is that if you get on the roof with  2 handers you can shoot and do whatever to people at the bottom there are no places to hide other than running inside the house (which we obviously can't do). so if people want to access the roof they must go from inside the block or have a helicopter and land on the roof.

**Remove access to the roof from the back of the block**
[Before](https://i.imgur.com/YY4tyXe.png), [Before](https://i.imgur.com/e70jaGJ.png), [Before](https://i.imgur.com/cHqDGr6.png) -- [After](https://i.imgur.com/o2ATC0j.png), [After](https://i.imgur.com/nqEgnLg.png), [After](https://i.imgur.com/E2phhoI.png)
**Reason:** Explained above.

**Remove the jump**
[Jump](https://i.imgur.com/AmSQ8Zk.png)
**Reason:** The reason we want the jump removed is that there have been events where people take that jump and landed inside the block luckily vehicles haven't landed on top of a person yet but they will eventually, and I don't want vehicles flying over the block...

**Add stuff to the roof**
[Example](https://i.imgur.com/v4toksB.png)
**Reason:** The fences in the back basically there to stop the access to the roof from the back of the block if on foot. the roof is big enough to be accessed by helicopter. The reason we want that little hut on the roof is that there are 2-4 other roofs that people can access with the helicopter that would give clear vision to the roof and allows people to be shot and we would rather not get shot by anyone while having some important stuff with the gang or other gangs.

**CodeWalker stuff**
Don't know if this will help with anything but here.......
[CodeWalker](https://www.mediafire.com/file/rrazdcc2b6ebmjy/nightshade.zip/file)

### Reason

Adding these suggestions to the Nightshade Block will enhance the roleplay Nightshade can have with other members of Legacy whether those players are in other gangs or civilians that would engage with the gang on day-to-day occasions. These additions will also help protect the gang and enhance the scenery of the block for a more "gang-like" presence for better imagery and more interactions between the gang itself inside the block without fear of surprise attack.

**Comment by CloudTheWolf** [comment]
Since this framework is used by multiple servers (Not just Legacy International) I doubt we would add much in terms of Gang Specific branding as this would impact other sub-divisions.

**Comment by painxfps** [comment]
> Since this framework is used by multiple servers (Not just Legacy International) I doubt we would add much in terms of Gang Specific branding as this would impact other sub-divisions.

I don't see how it would impact other sub-divisions negatively, as far as I know, it's one of those blocks where unless you have a whole gang no realtor wants to own it because you just lose money. these images I provided are just examples of what we want, doesn't exactly have to be like it, but they will make this place more unique and more desirable.

**Comment by CloudTheWolf** [comment]
Other changes could be done, but I'm just saying probs wont add logos, as other Gangs might own that block in the other Subdiviosns

**Comment by MetaHatter** [comment]
I am personally not a fan of gang branding blocks.  I am flat out against fortifying a residential area for combat.

**Comment by Mugdha57** [comment]
TANG has their own branding in their block, so why not other groups have their own??

**Comment by painxfps** [comment]
> I am personally not a fan of gang branding blocks. I am flat out against fortifying a residential area for combat. I prefer gang "bases" being away from where their endless supply of storage/cars is...

I understand that, that's why we have a stash house up north. this block is mostly used as a hangout spot for our gang and other gang-related stuff, fortifying this specific resident will help us use it for RP, for example having other gangs invited over to the block while having people on the arch as a scout or taking people in heli and taking them to the roof for the meeting, it's not mostly for combat it's mostly for safety and how other should feel safe in there, us using it for combat will only fuck us over with the cops, and we try to not keep too many weapons over at this resident because of that.

**Comment by MetaHatter** [comment]
> TANG has their own branding in their block, so why not other groups have their own??

I am also, personally, not a fan of this.  The framework is shared across 9 different regional servers.

**Comment by Mugdha57** [comment]
> > TANG has their own branding in their block, so why not other groups have their own??
> 
> I am also, personally, not a fan of this. The framework is shared across 9 different regional servers.

yaah i have seen in another subdivision a gang "Yakuza" using the tang block which had tang logo and others 
that's weird ngl..

**Comment by ImArteria** [comment]
As the others have said I wouldn't probably do gang specific branding for the block. I'll talk with Anti about adding some QOL stuff there. Where is your group's block at?

**Comment by painxfps** [comment]
> As the others have said I wouldn't probably do gang specific branding for the block. I'll talk with Anti about adding some QOL stuff there. Where is your group's block at?

Spanish Avenue Apt. Complex J (119)

[here](https://i.imgur.com/qGegHe2.jpg)
[location in map](https://i.imgur.com/B7AgQrX.png)

**Comment by painxfps** [comment]
is there any updates on this?

**Comment by ImArteria** [comment]
> is there any updates on this?

Am a busy person so unfortunately don't have much on this at the moment. Once I get some more time I plan to start having some things done.

**Comment by antihero6713** [comment]
this has been updated with some changes. Going to close this for now.
