### ISSUE TITLE
[maps/?] addition of a ladder across from Burger Shot

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/legacy-assets-issue-tracker#723]
### Name

Scufflord#0001

### Summary

I think it would be good to add a ladder closer to the helipad across from burger shot. It takes forever to run down and parkour across the roof tops from the only other ladder that gives you roof access on this row of buildings. My suggestion would be in the corner closest to the helipad (pictured below)

### Link

https://cdn.discordapp.com/attachments/845947698628001862/1078611864965087344/image.png
https://cdn.discordapp.com/attachments/845947698628001862/1078611813475819570/image.png

### Reason

Saves a bunch of time getting to the helipad. Quality of life for pilots

**Comment by ImArteria** [comment]
Done

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/221365880-a4daaaba-bbd1-4ceb-9928-5c3dd295e7e9.png)

DONE
