### ISSUE TITLE
[maps/bahama_mamas] Hole in Bahama Mamas roof

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/legacy-assets-issue-tracker#724]
### Reporter

Scufflord#0666

### Summary

Received a report of a player falling through the roof of the bar and becoming trapped inside. Zayne and I went to go check things out and we were able to find the hole. I can provide aerial screenshots as well if necessary if the clip below isn't enough.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/WIvcqxlrgbYG9/d1337HqrjeBJ?invite=cr-MSxEeVIsMjcwMjA5OTYs

**Comment by antihero6713** [comment]
found the issue will fix soontm
