### ISSUE TITLE
Bug report - hack the vehicle tracker

### ISSUE THREAD

**Issue by shivdattg** [InZidiuZ/legacy-assets-issue-tracker#725]
### Reporter

Knucker Gaming#5157

### Summary

I bought the car from luxury autos it is having this problem when I sit in the car and use a chip to hack the vehicle tracker. there is 5hacks remaining.

1
[6:13 PM]

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/126399201/221415898-75753c30-7a0e-4da3-8932-bbff599ad74e.png)

**Comment by CloudTheWolf** [comment]
Issue looks to be a Framework issue, not an asset issue. Please raise this here: https://github.com/InZidiuZ/op-framework-issue-tracker
