### ISSUE TITLE
Bug report - Silencers sometimes 'break' for no reason.

### ISSUE THREAD

**Issue by NoaimeDEVS** [InZidiuZ/legacy-assets-issue-tracker#726]
### Reporter

Kanye South#2782

### Summary

When using silencers on certain guns they stop working.
For me it still works, but for other people around me it still fires like a normal gun without the silencer. This may cause police to hear the shots or get notified (Don't know if this is true but it would make sense)
Right now im using a Pistol .50 and i have seen it happen with the beretta aswell. it happens every 50 - 100 shots, happened twice in a span of 20 minutes, the durability of my pistol is fine and so is my suppressor.

**Comment by InZidiuZ** [comment]
Wrong issue tracker for this
