### ISSUE TITLE
[maps/?] we need a bigger paintball field!!!!!

### ISSUE THREAD

**Issue by 2ataco** [InZidiuZ/legacy-assets-issue-tracker#730]
### Name

2A Taco#9822

### Summary

I hope this message finds you well. I wanted to reach out and express my appreciation for the fantastic work you all have done in creating and maintaining our FiveM server. Our paintball games have been a lot of fun, and I think we have a great group of players.

However, as our group has grown, I've noticed that our current paintball field is becoming a bit cramped. I think it would be really beneficial if we could create a larger field that would accommodate more players and allow for more varied gameplay.

I understand that this may be a significant undertaking, but I believe that it would greatly enhance our paintball games and make them more enjoyable for everyone involved. If there's anything I can do to help with this process, please let me know.

Thank you for your time and consideration.

Best regards,
[2A Taco]                   

### Link

https://cdn.discordapp.com/attachments/766407691379408907/1092720471138652230/image.png

we had around 14 total here is the 12 we got in a pic!!!!

### Reason

1 Provides an alternative activity: While our server already has a lot of great activities to offer, having a paintball field would provide players with a new and exciting way to enjoy their time in the server. It's a fast-paced, action-packed game that is sure to appeal to many players.

2 Builds community: Paintball is a great way to bring players together and build a sense of community. It's a team-based game that requires coordination and communication, which can help players get to know each other better and build stronger relationships within the server.

3 Encourages creativity: Creating a paintball field requires some creativity and imagination. Players can work together to design and build obstacles and cover, which can be a fun and rewarding experience. Additionally, the flexibility of a paintball field means that players can try out different game modes and scenarios, which can keep the gameplay fresh and engaging.

4 Increases server longevity: Finally, having a paintball field can help increase the longevity of our server. It provides an ongoing activity that players can come back to time and time again, which can help keep the server active and vibrant.

**Comment by ImArteria** [comment]
I'll see what I can come up with.

**Comment by antihero6713** [comment]
Closing I know what I want to do just need the time to do it
