### ISSUE TITLE
[peds/?] Gang Vest Request

### ISSUE THREAD

**Issue by vesperarose1** [InZidiuZ/legacy-assets-issue-tracker#731]
### Name

sociopath#0666

### Summary

Nightshade Row is formally requesting a vest with its name and logo, previously owned by DOL. 

Here is an example of what I have come up with for the front:
[Front](https://cdn.discordapp.com/attachments/1038197420498104370/1094870478541295666/vest_front.jpg)

Here are the Images I used on the patches:
[Rose](https://cdn.discordapp.com/attachments/1038197420498104370/1094870527325261955/hand_1.png)
[Logo](https://cdn.discordapp.com/attachments/1038197420498104370/1094870553120210954/My_project-1_8.png)
[Guns](https://cdn.discordapp.com/attachments/1038197420498104370/1094872736322560010/My_project-1_9.png)

Here is what I created for the back:
[Back](https://cdn.discordapp.com/attachments/1038197420498104370/1094870497717657630/vest_back.jpg)

Here is the link for the logo again:
[Logo](https://cdn.discordapp.com/attachments/1038197420498104370/1094870553120210954/My_project-1_8.png)

I don't have a specific font I used to write the gang name so use it at your own discretion that resembles the one I used. The logo behind the gang name in the back was at a lower opacity than the words to reference, and finally, if you could color code the words to the blue face flag it would be greatly appreciated. 

Thank you!

### Reason

Nightshade has been in the city for a bit of time now and would love to have a personalized vest to increase its RP with gun deals and gang activity.

**Comment by DaxterPancake** [comment]
This has been completed. No current ETA on when it will be available as I am unsure when the next clothing build will be. The blue behind the text was colour matched to the mask as best as possible. Skull under back patch words is roughly 50% opacity. 

[Example Photo 1](https://media.discordapp.net/attachments/850252046267711498/1098523015601459251/image.png?width=779&height=559)
[Example Photo 2](https://media.discordapp.net/attachments/850252046267711498/1098523015882473552/image.png?width=679&height=559)
