### ISSUE TITLE
[vehicles/?] ?

### ISSUE THREAD

**Issue by B7ackPanda** [InZidiuZ/legacy-assets-issue-tracker#733]
### Reporter

Panda#4916

### Summary

With PD/EMS being able to switch outfits at the back of their vehicle if the trunk/ door 6 is open. Whit the BCFD vehicles that have a trunk we can open it wil allow us to do the command but it will state that the trunk is closed.I dont know if this can be fixed but it will be nice if we as fire fighters are able to switch our uniforms if needed.

### Screenshots/Videos

![trunkclosed](https://user-images.githubusercontent.com/92066019/233192867-57cf04cf-6b69-4b89-a5b2-cf9c7f6200f5.png)

**Comment by coalaura** [comment]
This would be for the script github https://github.com/InZidiuZ/op-framework-issue-tracker/issues
