### ISSUE TITLE
[maps/vanilla_unciorn] vanilla unicorn remodel 

### ISSUE THREAD

**Issue by panewni** [InZidiuZ/legacy-assets-issue-tracker#734]
### Name

panouni#2595

### Summary

Hello!
I am the owner of the Vanilla Unicorn, and I have been wanting a refreshed look for the VU, to make it more enjoyable for the city. 

I want to know what the possibilities are for you guys to possibly change the interior of the VU! I was told a few months ago that someone was interested in making the VU better for us- so if that still stands! Please help us out!

I am including a video of an interior I saw that is extreme similar to what I would want for the VU! 

Obviously if buying it for the server is not something we can do, if  we could discuss the possibility of creating our own vanilla unicorn for legacy i believe it would be great for the city!!

Thank you!

### Link

https://www.youtube.com/watch?v=dB4RcWOrw54

https://ko-fi.com/s/323876ed8d
https://ko-fi.com/s/829ac961fb

### Reason

This would be a good addition to legacy because more people will be interested in coming to the Vanilla Unicorn and the future events held there. In addition, people will be more interested to coming to a city with interiors that are not the default GTA look. As well as allowing for the city to evolve with the people who fly in.

**Comment by coalaura** [comment]
![bruh](https://media.tenor.com/tgeH4ULNd0QAAAAd/cat-fnaf.gif)

**Comment by panewni** [comment]
any updates thoughts comments concerns?!?!!

**Comment by antihero6713** [comment]
We dont buy interiors anymore and as far as update it probably gonna be super low on the list of things to work on.

**Comment by panewni** [comment]
what if i were to buy it???? it wasn't low on the list when one of the interior devs reached out to a former employee during their stream.

**Comment by hell-of-the-devil** [comment]
I can take a look at it and maybe try a few things, however as @antihero6713 mentioned, it won't be high on the priority list as it already is a working interior so may take a while for it to get worked on...

On a side note who is the former employee and who was the interior dev? do you know perhaps?

**Comment by panewni** [comment]
@hell-of-the-devil i'm not in a rush for it to happen! i just want to know if it would be possible at some point! the employee was saber or tacticalpinup on twitch. I am not sure who the dev was but they were eagar to know what exactly the vu would need for it to be better! 

in addition if it would be possible to make the trash can in the VU just be decor that would be appreciated as it conflicts with the lockers.

**Comment by antihero6713** [comment]
closing if you need anything else make a new ticket
