### ISSUE TITLE
[maps/prison] Removal of props in prison yard

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/legacy-assets-issue-tracker#735]
### Name

TacticalTyl3r#0001

### Summary

My suggestion is to remove box props that are located in the middle of the yard.

### Link

https://i.imgur.com/ezxmUhc.jpeg

### Reason

I am suggesting this because people like to powergame and move the box to a fence to climb over the barbed wire and onto the steps to gain access to the prison buses and attempt to ram them through the gate to escape.  This is for current HUT (Held until Trial) prisoners and are not tied down to the /jail command so they don't get teleported back when they leave.  Removing these boxes will negate said actions from players.

**Comment by antihero6713** [comment]
fixed the one in the picture

**Comment by hell-of-the-devil** [comment]
@TacticalTyl3r i have also fixed the two next to the one that @antihero6713 deleted which were the real offenders, they have been set as static objects therefor are no longer able to be moved by players
