### ISSUE TITLE
[vehicles/?] Lower the sound of the engine of the mustang

### ISSUE THREAD

**Issue by bennywzggz** [InZidiuZ/legacy-assets-issue-tracker#736]
### Name

RobSteiner#5085

### Summary

Lower the sound of the engine of the mustang

### Reason

you are unable to hear people sitting with you or on the radio and its just not that nice to hear this sound the entire day

**Comment by joevapes3** [comment]
The mustangs engine sound was lowered a while back, while still louder than other vehicles it's a catch to driving one of the better vehicels in the city as you can get noticed easier with it.
