### ISSUE TITLE
[maps/yellow_jack] Add some quality of life items to the Yellow Jack in

### ISSUE THREAD

**Issue by AmateurProfessional** [InZidiuZ/legacy-assets-issue-tracker#739]
### Name

Amateur_Professional#7313

### Summary

Add some quality of life items to the Yellow Jack in. 

1: A "Bar" marker on the map
2: An ATM inside the bar on the SW wall

### Link

N/A

### Reason

1: Making it easier to locate on the map at a glance
2: Keep epople from needing to drive to the local

**Comment by antihero6713** [comment]
We did have a custom interior for be it caused people in sandy to crash at times. So now its back to stock vanilla GTA.  

Are you the owner of this place?  I only be able to provide the ATM on my side

**Comment by AmateurProfessional** [comment]
> Are you the owner of this place? I only be able to provide the ATM on my side

Yes, recently came into possession. 

The ATM is plenty, we're not looking for an updated interior. 

Later we might ask for a locker of some kind but we can make what we have work.

**Comment by hell-of-the-devil** [comment]
An ATM has been added to the exterior of the building just outside the front door! as for the blip this would need to be submitted to the OP Framework Issue Tracker

It will be live soon!
