### ISSUE TITLE
Suggestion - Uber Eats

### ISSUE THREAD

**Issue by HollaYalla1** [InZidiuZ/legacy-assets-issue-tracker#740]
### Name

HollaYalla#0001

### Summary

Add Uber Eats to the phone app and it is something anyone can do, so what will happen is, You Open the App, Create an account, Join the Queue, and randomly like the boosting tablet you will get a order and you have to go to a random restaurant and get a Uber Eats box and once you pick it up you will get a waypoint automatically added to your gps, and once you go to said waypoint you will go to the door, and give the person the food, (they will come out aswell kinda like how the people come out for the oxy runs) and you will get a certain amount of money added to your account on the Uber Eats app, there will also be a history tab which you can see all your previous orders and how much you made plus a tip, (the tip can be random or generated by distance and time it took to get to the customer) after you do a order you will be able to go into the app and hit withdraw, once you hit withdraw a new menu will pop up with a text tab asking how much you want to withdraw with the amount of money you have in your uber eats account showing on the top right on the tab, it will then instantly go into your bank account and it will be time based, so if you dont claim a order in like 5 minutes it will disappear, also the orders will be given to everyone so it is first come first serve. It shouldnt be too OP but could be a fun job for everyone that either has a whitelist job or just doesnt want to do trash.

### Reason

Add more Legal jobs for everyone to do.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this.
