### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by ryanhoskins1993** [InZidiuZ/legacy-assets-issue-tracker#742]
### Reporter

hoskins#2057

### Summary

Hey i have recently purchased luxury autos and would like the name on the front door to be changed to Ryan Chase

**Comment by hell-of-the-devil** [comment]
@ryanhoskins1993 could you perhaps post an image of what you would like changed, also this should really be a suggestion and not a bug report!

**Comment by ryanhoskins1993** [comment]
![Uploading 16871185594655337731901449310252.jpg…]()

**Comment by ryanhoskins1993** [comment]
Thus window needs to be changed to Ryan Chase

**Comment by hell-of-the-devil** [comment]
this has been completed!
