### ISSUE TITLE
[maps/mirror_park_auto] ?

### ISSUE THREAD

**Issue by rishabmishra0341** [InZidiuZ/legacy-assets-issue-tracker#743]
### Name

Rishab (rishabmishra)

### Summary

In legacy India mirror park repair shop is one of the best mechanic shop compared to other shops because we guys give 24 hours service but the main problem or suggestions we are getting from our customer that is there are no lines by which customers can get to know which is the repair bay and where they have to place there cars for repair and the second thing is its interior it seems to be too much dark and there are very less lighting inside it and some suggestion which we want to provide that is there is no proper logo of the shop there is one but that is too much blurry and there are total 6 work bench but only 4 bay are there for repair 3 in front and 1 at back so if you guys can increase the repair bay or add some washing stuff instead of the work bench it will look good i have a mlo video of this shop which looks fantastic i will share with you guys if possible you guys can add that because the interior lighting, the exterior everything looks amazing of this mlo. Thank You

### Link

https://youtu.be/zZgusF89vbw

### Reason

The interior of the shop is too bad it doesnt have a proper lighting its too dark from inside it doesnot have the white line to indicate the repairing bae so everytime we have to say the customers keep your car here for repairing and the shop doesnot have any logo also its too much blurry and dirt i have provided one mlo with link if possible we want the shop like that and with the white lines which can indicate the repairing bae

**Comment by rishabmishra0341** [comment]
is there any update on this

**Comment by antihero6713** [comment]
We will not be using this MLO. Other Issue can possible be address at some point

**Comment by MetaHatter** [comment]
That MLO will not be used, the shop has a logo and there's really no need for lines. There's only 1-2 ways to even pull into the shop.
