### ISSUE TITLE
Suggestion - boombox loop

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/legacy-assets-issue-tracker#748]
### Name

Destiny (jwilton)

### Summary

Can there be a way to loop the playlist you make on boomboxes so you can load a bunch of songs and be done with it rather than constantly having to add more songs. Or be able to link playlists from YouTube rather than just videos

### Reason

Everyone I have talked to in city has been really excited by this idea as it takes some of the tediousness out of playing music, and also it brings more realism to the city since you can loop playlists on almost every music platform available in the real world.

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. This one is for assets only. Use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) instead.
