### ISSUE TITLE
[maps/tequi_la_la] ATM

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/legacy-assets-issue-tracker#749]
### Name

Destiny (jwilton)

### Summary

Can we please get an atm inside of tequilala. Literally every person that walks in asks if we have an atm and we have to explain that we do not and they have to run to the nearest one before they can buy any drinks. 

### Reason

Every other business has an atm inside of it other than tequilala, and also patrons are constantly dying because they are crossing the street to the nearest atm to get money for more drinks, while being intoxicated, so they get run over.

**Comment by hell-of-the-devil** [comment]
I have actually already completed this request about a week ago however i have some adjustments for other changes....

Unfortunately i had to put it outside as tequi-la-la is a default interior that we do not stream in, therefor i cannot add it to the interior....

I will get this pushed soon!

**Comment by hell-of-the-devil** [comment]
this has now been completed and pushed

**Comment by MetaHatter** [comment]
Since this appears completed I'm closing the ticket.
