### ISSUE TITLE
Bug report - picking up locals

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/legacy-assets-issue-tracker#750]
### Reporter

Destiny (jwilton)

### Summary

Almost every time that you pick up a local, someone nearby will head pop because of it. Sometimes it’s only one person but frequently it is a large group that all head pop at once

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. This one is for assets only. Use [this one](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) instead.
