### ISSUE TITLE
[roleplay] Small thing but so usefull

### ISSUE THREAD

**Issue by callmeeJeff** [InZidiuZ/legacy-assets-issue-tracker#753]
### Name

callmeejeff

### Summary

Added 3 dots above head when typing in in-game chat.

https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/93746728/f2189df1-54ff-4534-9b35-d9047aebcb5c

### Reason

Adding this small option will ensure that players won't be competing with each other in /me commands and everyone will be able to calmly respond to narrative commands in the right order. In addition, it helps in non-verbal communication between players. Of course, it would have to be done so that administrators using commands when spectating people would not have a problem with the fact that 3 dots would be displayed above their heads. I think it's a very small thing and very helpful.

It is important that these dots are displayed using the chat and not only with narrative commands, because for example it can also be used for communication using /looc between players.

**Comment by scufflord** [comment]
This just feels super immersion breaking

**Comment by callmeeJeff** [comment]
> This just feels super immersion breaking

maybe you're right but note that it will only be when typing in chat. You'll spend most of your time talking to the other player or doing some action anyway. It's just a convenience
