### ISSUE TITLE
Bug report -  Game is not starting only black screen is coming 

### ISSUE THREAD

**Issue by Eagle9211** [InZidiuZ/legacy-assets-issue-tracker#755]
### Reporter

Rajput#9912

### Summary

Game is not starting only black screen is coming Taking respawn form cargo gone to hospital and black screen is coming 

### Screenshots/Videos

[https://cdn.discordapp.com/attachments/1126877808136830986/1127236260390506616/Screenshot_2023-07-08_192333.png](url)

2nd time ma ya gya ha 
[https://media.discordapp.net/attachments/1126877808136830986/1127238137387692082/rWTF.png?width=538&height=670](url)

3rd time ma ya gya ha 
[https://cdn.discordapp.com/attachments/1126877808136830986/1127242627872473088/image.png](url)

### Note

Plz give me my item's

**Comment by InZidiuZ** [comment]
This has since been fixed.
