### ISSUE TITLE
Suggestion -  SAHP Name Bar on Badge

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/legacy-assets-issue-tracker#758]
### Name

enutpeanut

### Summary

Add a texture for the SAHP badge, changing the name bar to just ‘State Trooper’ or something that can be applied to everyone, like on the SASP badge.

### Reason

On the Highway Patrol badge (bag/parachute), the name bar includes surnames for officers, which cannot be applied to the current State Troopers.

**Comment by DaxterPancake** [comment]
Would you mind providing a photo of the badge so I know which one specifically you would like changed?

**Comment by enutpeanut** [comment]
> Would you mind providing a photo of the badge so I know which one specifically you would like changed?

This was the best photo I could find, hope it’s okay!
![265D3549-D04E-4734-BA55-ED6218BE88E0](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/116962577/116f71aa-8883-437b-bab3-0ac12cd662fe)

**Comment by DaxterPancake** [comment]
This has been done and will be live hopefully within the next few days. I have changed the badge shown in the picture above to say State Trooper instead of T. Dodger for both mp_male and mp_female.

**Comment by enutpeanut** [comment]
> This has been done and will be live hopefully within the next few days. I have changed the badge shown in the picture above to say State Trooper instead of T. Dodger for both mp_male and mp_female.

Oh that’s amazing, thank you!
