### ISSUE TITLE
[peds/?] A chain specifically for Chang Gang

### ISSUE THREAD

**Issue by VinnyPistone** [InZidiuZ/legacy-assets-issue-tracker#759]
### Name

p4bl0_5505

### Summary

I'm formally requesting a chain for Chang Gang, as there aren't any specific outfits for Chang Gang. We are giving some example photos adding any one of them would be just fine.

**Examples:**

**Chang Gang Dragon Chain (Silver):**

![cg3](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/89471617/907f731b-0680-48be-ac28-ca5e3b5657a6)

**Chang Gain Plain Chain (Gold):**

![cg2](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/89471617/4b4ccf2e-a603-4ca9-8948-23b544ff67a1)

We are not asking for the exact same design in the game. If you have any better designs for the chain, you can modify it as it seems fit. As we love the past and present clothing add-ons to the server, we hope either you will add it the way it is or make it even better in your own way. ❤

### Reason

We are writing this from the Bangladesh sub-division of Legacy Roleplay. We recently started doing Chang Gang RP but we are doing RP in Legacy Roleplay Bangladesh for over 2-3 years, however, as we don't have any specific outfits for our gang we lack alot of opportunities. 

The other gangs have specific clothing for themselves and can be easily recognized, that's not the case for us unfortunately. The gang has a backstory which doesn't include a certain color, they are recognized by their specific chains. Adding this will enhance our RP and others will be interested in joining the server.

We all are very obsessed with the past clothing suggestions that were added to the server and I hope my suggestion will get approved. 

**Thank you in advance.** ❤

**Comment by DC0402** [comment]
It would be really great if the Chang Gang chain gets added, +1. ❤️

**Comment by VICKYSOHAM** [comment]
Yeah Its a good suggestion. It will be really great if we see some chain of **Chang Gang** ❤️

**Comment by SHIVAM-DARIUS** [comment]
Oh, absolutely! The inclusion of the Chang Gang chain would undoubtedly be a celestial.

**Comment by VinnyPistone** [comment]
We are not following any Chang Gang from Nopixel, we are doing it in our own way. What format should I submit for an alternate logo?

> We don't make custom chains, you will have to source your own and provide it to us. Also, if this is Chang Gang from NoPixel then I will not be adding it at all.

**Comment by DaxterPancake** [comment]
I'm going to make the decision to say no to anything that has the name Chang Gang on it clothing wise or chain wise, not only due to potential legality issues but also due to the fact that Legacy is not NoPixel and therefore people should be trying to create their own gangs and names and not using things from other servers.

Again, we do not make custom chains and if you wish to purchase one when and if you change your gang name to something else, you will have to find someone who will create it for you.
