### ISSUE TITLE
Bug report MANSION DOOR NOT WORKING THE MAIN STEEL DOOR 

### ISSUE THREAD

**Issue by hcboss** [InZidiuZ/legacy-assets-issue-tracker#76]
**Reporter:**
@MJ LEGACY GAMING#0001 LEGACY INDIA SERVER ADMIN 

**Summary:**
ONE OF MANSION IN MY BLOCK HAS A BROKEN ATOMATED STEEL DOOR THAT DOESNT WORK AND NOONE CAN TAKE THEIR CAR INSIDE THE HOUSE SO IT MAKES IT VERY HARD TO SELL HAD TO SELL IT AT COST PRICE PLEASE FIX IT. 

**Screenshots:**
https://cdn.discordapp.com/attachments/603653826427486217/631384522679910420/Screenshot_106.png

HOUSE NAME:- Caesars Place 2

**Notes:**
For anything else noteworthy.

**Comment by Aspratic** [comment]
why in the hell are u using all caps acting like it will make help it get fixed any sooner

**Comment by hcboss** [comment]
> 
> 
> why in the hell are u using all caps acting like it will make help it get fixed any sooner

the place I come from their is no difference in CAPS or nocaps sentences.

**Comment by Karpenkooo** [comment]
Hey,

Sad to say i can't help you with this as i manage most of the server Assets. You'll need to fill in a bug report on @InZidiuZ GitHub. 

_Karpenko_

**_OP-FW Car Dev_**
