### ISSUE TITLE
[maps/burger_shot] Burger Shot New MLO

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/legacy-assets-issue-tracker#762]
### Name

V!kky#7754

### Summary

In Progression Road Map of Legacy Server From the Start till Now , We get new MLO's for mostly all the the Dept. Building like we got new MLO for MRPD , we got new MLO for old Pillbox medical center and then we got new Hospital i.e. Mt. Zonah . Court house got renovated . Can we get same for Burger Shot as well . in Current MLO we've limited space at counter side , and it also look bit of old building . 

### Link

https://www.gta5-mods.com/maps/mlo-burgershot-2023-add-on-sp-fivem

### Reason

As i mentioned above , we get renovation for almost every dept. building . with current MLO of burger shot , it look lil bit of back in time , in the link i provided , there's spacious kitchen area , new counter area , usable washroom , it looks like modern day architecture overall including whole building , parking space and other things . in peak time it got crowded and due to all the tables no space for customers to enjoy there meal in BS . in new MLO we got ample amount of space which players can use to dine in and things just like IRL. may be we can get few more things with this renovation which we all can use in our daily RP.

**Comment by lunarz17** [comment]
I agree with the idea of renovating Burger Shot with the new MLO. It kind of looks a bit old. Even it doesnt have enough place to dine in. With the new MLO we can try for drive thru a new experience for all the players. As far as I know according to my knowledge no other RP server have done this soo we can be the first one to get this in our server.

**Comment by 1M6host** [comment]
The new MLO looks modern and gives a refreshing feel to the players. It seems a pretty good idea to me, to give a new face to an old place which we all know. This also gives new possibilities for RP. I would request the team to please discuss this update for the upcoming plans.

**Comment by ImArteria** [comment]
Im no expert but that building looks like it'll lag the hell out of the server

**Comment by Vikky98** [comment]
> I am not a fan of changing the MLO. This mlo screams like a rip off of the gabz February fast food update. this also will have problems with NVE. The current burger shot is modeled off a five guys. My vote is to not change anything

so is there any other MLO or any way in which we can get new building/renovation for Burgershot ......

**Comment by antihero6713** [comment]
list here in further details what you would like to see changed with the current MLO? Also remember other servers are using the same MLO.

**Comment by Vikky98** [comment]
> list here in further details what you would like to see changed with the current MLO? Also remember other servers are using the same MLO.

some changes like Drive-in path for deliveries , Combined Kitchen and Billing Counter to get bigger space than that of now . may be new and accessible sitting for Customers if they want to sit and enjoy meals , usable Washrooms may be .. if possible only.

**Comment by Vikky98** [comment]
Any Updates on this @antihero6713 . Like any eta or something.....

**Comment by MetaHatter** [comment]
This MLO will not be added.

If there are changes requested to the existing MLO, please create a new github suggestion.
