### ISSUE TITLE
[maps/?] Soundproof the Sandy Shores Sheriff's Office

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/legacy-assets-issue-tracker#766]
### Name

thisisnotdex

### Summary

Soundproof the Sandy Shore's PD, all 3 levels separate of each other, so people in the basement can't hear people above them, people on the ground floor can't hear above or below them, and the people on the top floor can't hear below them at all.

### Reason

People just stand in the lobby to listen in to the cells, and also would be nice to have levels of privacy for each floor.

**Comment by ImArteria** [comment]
Pretty sure sound proofing is done through scripting

https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose

**Comment by coalaura** [comment]
I will gladly soundproof the basement but thats it

**Comment by coalaura** [comment]
I don't see the need to soundproof that entire PD
