### ISSUE TITLE
[vehicles/?] 2013 Subaru Impreza WRX/Sti Hatchback Suggestion

### ISSUE THREAD

**Issue by Renegamr** [InZidiuZ/legacy-assets-issue-tracker#768]
### Name

Rene (Renegamr)

### Summary

I would love if a 2013 or 2014 Subaru Impreza WRX or Sti Hatchback would be added to the server. Along with the popular customization options such as the Vivid Racing Aero Carbon Fiber rally Wing, Grimmspeed Exhaust or Corsa Performance Exhaust (which sounds amazing), Cobb installs and tunes, etc. I own one IRL, so I'll link a picture to it.

### Link

![Subie](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/142545572/d9187273-1c5a-4de1-ad5e-910f6452942c)

### Reason

Subarus are very popular in the US. The Hatchbacks are especially popular because of the amount of tuning and horsepower it provides with its flat 4 engine 5 or 6 speed (depending on if you get the WRX or Sti) with a stock turbo.

**Comment by joevapes3** [comment]
This vehicle is already being made it's currently a WIP, Will close this ticket for now but just keep your eye out for it soon TM
