### ISSUE TITLE
[vehicles/?] PDM cars need a buff

### ISSUE THREAD

**Issue by Kropex6000** [InZidiuZ/legacy-assets-issue-tracker#769]
### Name

kidharspoon

### Summary

PDM cars are really shit compared to EDM cars. I have a PDM sports car fully maxed out with EMS 5, turbo, race suspension and transmission, etc and yet a van from EDM with only EMS 4 on it is faster than it.

### Reason

I understand that EDM cars cost real money and should be better than PDM cars overall, but PDM cars should be buffed a little bit just to seem more realistic. Or the other way round by nerfing EDM cars.

**Comment by Skai97** [comment]
There is a lot of PDM cars that are actually better than 70% of whats available at EDM. As the previous owner of the business and was there whenever all the vehicles got buffed a year ago. I've tested all of the but the newer pdm cars.  Not gonna say what a lot of those cars are but I do agree some of the cars inside of PDM could do with a buff

**Comment by joevapes3** [comment]
Lots of PD cars that are fast as or faster than EDM cars, just gotta buy them and upgrade them to find out. Also the vehicles are constantly changing, what might of been slow a few months ago, might be faster now. Just have to try them.
