### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WallagherTRP** [InZidiuZ/legacy-assets-issue-tracker#77]
**Name:**
Wallagher#0001

**Summary:**
I have been working on an Handbook for the Court system so we can get more RP for arrest giving them more of a story line than just a jail-disappear. At the moment it is a role-play system where cops will request a judge or any civ will, as there are 2 types of courts cases civil and criminal. I would like to see a more dedicated role to the court system where you can save court cases and their sentence, fines, charges so on and so on. You can see below in my links that i have a temp google spread sheet to track the sentences and charges to make it more official role play to try attract more people into it.

Suggestions:
Roles
Criminal Records
Announcements for mandatory summoning to court
some sort of court funds for people to pay for their cases as they do IRL

**Link:**
https://docs.google.com/document/d/19ENoOEtJyTMIkkGAr-jZpLyfcWbn82wdvoC4wg--VkY/edit#heading=h.1j2yhp5owqoy

**Reason:**
It gives a greater Role play to legacy and will attract more people to the law side of legacy rp, with that said i'm okay with carrying on my rp court system as im getting a good amount of interest

**Comment by Karpenkooo** [comment]
Hey,

This sounds like a great idea however i think it's more or so something that you'll need to speak to the mayor of the city about. I don't have too much control over this. Sounds cool though.

_Karpenko_

**_OP-FW Assets Dev_**
