### ISSUE TITLE
Suggestion - Craftable Glock 17 Burst Module

### ISSUE THREAD

**Issue by whargoul420** [InZidiuZ/legacy-assets-issue-tracker#771]
### Name

whargoul420 (ben84#6881)

### Summary

A burst module similar to how the Liberty counterpart was implemented into Rust.  It would be crafted at a secret location using components and only be usable on the Glock 17.

### Reason

It's an added perk for those that can get their hands on a Glock and I think people would buy it.  Make it expensive.  I love both the burst module and the new prototype pistol in Rust.

**Comment by TacticalTyl3r** [comment]
I believe the Glock that was put in ammunation are not meant to take any attachments so Criminals dont just rob citizens for them.

**Comment by coalaura** [comment]
like tyler said
