### ISSUE TITLE
[peds/?] uniforms for split side comedy club and for my security

### ISSUE THREAD

**Issue by merrick453** [InZidiuZ/legacy-assets-issue-tracker#772]
### Name

ASDdoesgames

### Summary

I am wondering about uniforms for my business split sides comedy for my staff and for the security 
having these items would make it look more professional  I am hoping  to get these 

### Reason

having these clothes helps my business

**Comment by DaxterPancake** [comment]
Can you please provide more information on what you're wanting? What type of clothing? What colour? etc

There are already polo's available to you in the server currently. Undershirt 66 & 67 - Texture number 4.

**Comment by merrick453** [comment]
Black button down shirt with red outline to go with the club colors and the split side logo on the front and maybe staff on the opposite side or on the back

**Comment by merrick453** [comment]
![IMG_6183](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/129596308/f1e102cd-846b-4a75-8564-27724d5f7bb1)
Something like this

**Comment by merrick453** [comment]
![IMG_6184](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/129596308/1e097cee-5bd1-4739-ae75-e0ae1bcce3cf) or this as well trying to make it as easy as i can you know what i mean

**Comment by merrick453** [comment]
![uniform](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/129596308/98425b00-1e72-461d-a27f-288267daf41d)
or something like this

**Comment by merrick453** [comment]
any idea when my uniforms will be added?

**Comment by DaxterPancake** [comment]
I have created a basic polo that has a basic texture and security texture.
