### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by iDaxr** [InZidiuZ/legacy-assets-issue-tracker#773]
### Name

daxr.

### Summary

I am requesting my garage being moved to a different location on my house property. Address is Mad Wayne Thunder Drive 4

### Link

![Car garage transfer request](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/143039199/af0437dc-bc96-47cb-b298-13b8913cc299)
![garage now](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/143039199/31fa99ef-8e5e-443f-8502-8ddaae8510bc)

### Reason

I feel like its not realistic to have the garage at the entrance of the driveway when on the property there is an already made garage. I personally think that having the garage arrow and allowing the car to spawn inside or just in front of the garage would make more logical sense. Just an opinion I had

**Comment by coalaura** [comment]
this was already done
