### ISSUE TITLE
[vehicles/?] Bug hakuku Drag Bike top speed

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/legacy-assets-issue-tracker#774]
### Reporter

SluggsV2

### Summary

The Hakuku drag bike flat road tops out at 134 and then I put ems 4 on it and it only goes up to 154,

this just doesn’t sit right with me or other pedestrians in the city, it’s a 27k bike and I’m not asking for it to go 300+ but a drag bike nearly fully maxed should go atleast 220 imo

**Comment by joevapes3** [comment]
Bikes in the city have a lower top speed for balancing purposes, there will be no change to this vehicle at this time unfortunately, but I appreciate the feedback.
