### ISSUE TITLE
Bug report - R34 is now only a 2 seater

### ISSUE THREAD

**Issue by TROWER-MF** [InZidiuZ/legacy-assets-issue-tracker#775]
### Reporter

ID : 765656528165404702 BeansOnToast123#1336

### Summary

The R34 is now only has 2 seats and you can not sit in the back

**Comment by xplrerin** [comment]
There’s two different R34, ones a two seater and ones a four seater 🤔

**Comment by gadjinee** [comment]
hes talkign about ER34, from EDM, that one is a 4 seater however for some reason its now only a 2 seater with 2 back doors
