### ISSUE TITLE
[maps/mosleys] Door & window suggestions

### ISSUE THREAD

**Issue by WipseNL** [InZidiuZ/legacy-assets-issue-tracker#776]
### Name

Wipse

### Summary

This suggestion is about Mosleys. Basically an addition and a change/adjustment. 

1. The two big doors that are the entrance and exit to the main bay of the shop. They don't stay open and aren't able to he locked into place when opened. It would be nice if there was an option to open those doors and keep them open without needing someone to constantly stand next to them. 

2. A window to add a little bit more connection between the inside and the outside of the shop. Most likely the only spot it can be placed is in between the two doors. 

### Reason

The shop is quite dull now, without any connection to the outside world. It would be nice if there was something to look at just like back when the shop was at the front. A window and the doors being able to stay open, would make it a lot less cave like and would make it easier for people who didn't check twitter to notice we are open and working. 

I hope these changes make sense and can be taken into consideration.

Much love, 
Wipse.

**Comment by WipseNL** [comment]
I didn't know I could change the title, my bad.

**Comment by antihero6713** [comment]
We had another map dev working on a new mosleys. For now, it won't be changing till he is done with it

**Comment by selliee** [comment]
> We had another map dev working on a new mosleys. For now, it won't be changing till he is done with it

Hi there! RP Owner of Mosleys here. So I didn't actually know this post existed- however, I have spoken with Max, and to my knowledge he has halted working on the new interior of mosleys. I would like to see though, the possibility of reverting to the old mosleys where the bays are inside the other side, until the creation of the new map is complete. 

I do agree with what the original poster is saying on here. Its very gloomy, and small on the inside with the current layout and I know that is a big  complaint from a lot of people.

**Comment by DaxterPancake** [comment]
The old map caused major frame drops, no? It's not just as simple as turning on the old one, on an optimization standpoint anyway.

**Comment by antihero6713** [comment]
what Daxter has said

**Comment by selliee** [comment]
> what Daxter has said

well then is there anyway to make it a little bit less gloomy, because like i mentioned i know that max told me he stopped working on the interior

**Comment by itachiwho** [comment]
Agree ! It would be great if there was an option to open those doors and keep them open Or if we can get this door instead (the hayes shop doors) https://files.catbox.moe/7ua0nt.png

**Comment by antihero6713** [comment]
closing since already have a new plan moving forward
