### ISSUE TITLE
[maps/hayes] Suggestion TV Placement 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/legacy-assets-issue-tracker#778]
### Name

gadjinee

### Summary

i was wondering if its possible to replace the old car photos above the casting sofa with a TV, i have attached the photo
![264781720-90c657cb-c592-4acd-8fc9-ce106ea3407b](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/124582929/71936fc9-fada-4392-bb2b-52d34f5e7403)

### Reason

the reason is we would like to have some Promotional videos been displayed as well as some future giveaways that would be great, maybe even making a montage of team photos and have it there. One of the ideas would be maybe having a employee of the month and we could esseantually have a photo of the person there with some information

**Comment by RetroCharles** [comment]
I believe this suggestion will have a good impact on immersion and atmosphere of the shop for both customers and workers of Hayes. The idea of having an TV screen to promote current and future events can easily eliminate the workers from repeatedly asking customers after each repair if they heard about Hayes' current events.  Have customers have something to read/watch while waiting for a repair like most real-world mechanic shops. In addition to that, Hayes' owner and management team can include weekly/monthly employee appreciation such as top mechanic, newest mechanic, team photos to boost team morale or have the Hayes' feel more at home with the shop.  

IF possible, to only have mechanics with shop keys to interact/change what is being displayed on the tvs.

**Comment by gadjinee** [comment]
Is there any update on this at all? As we have an event approaching would be amazing to have the TV on the wall to advertise it

**Comment by antihero6713** [comment]
Reopen if this is still wanted
