### ISSUE TITLE
Suggestion - Car BMW M5 E39

### ISSUE THREAD

**Issue by Calmasootra** [InZidiuZ/legacy-assets-issue-tracker#780]
### Name

Calmasootra

### Summary

Its just a car suggestion for a beautiful BMW from the early 2000's, Id like to suggest a nice audio file with it too. The sound mod is not for a 4.9L S62 V8 but I cant find anything that sounds closer to it

### Link

https://www.gta5-mods.com/vehicles/bmw-m5-e39

https://www.gta5-mods.com/vehicles/m5-sound-mod

### Reason

Its just an amazing car I have no clue how good its handeling will be but just for the looks I personaly would love to have it, we have the E46 M3 we should have the bigger badder E39 M5!

**Comment by joevapes3** [comment]
I appreciate the suggestion for the vehicle and will take it into consideration as a future asset. While this exact model may not be used, I also would like to see this year and model vehicle be added at some point. Anyways thanks again for the suggestion. 👋
