### ISSUE TITLE
Suggestion - Locker for Tequilala

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/legacy-assets-issue-tracker#781]
### Name

Destiny Sebastian - jwilton

### Summary

I am the owner of Tequilala and it would be super appreciated if we could get a locker down in the staff room so I could give my employees supplies and menus that they could keep on site for their shifts rather than having to keep everything on them whenever they are going to work. 

### Reason

Most work places have locker rooms or areas in the staff room to put down your stuff, and most places that I have worked have had places where you put your stuff that you work with, you don’t take it home with you. 

It would also be a QoL thing because I frequently show up ready to open then realize I don’t have a boombox or enough tazer ammo or handcuffs or something that I need for the shift.

**Comment by TwinkyVT** [comment]
Please! As a Manager this would be VERY convenient for and not to have to drive out of my way to go change before work!

**Comment by MetaHatter** [comment]
This is not the right github for this.

Should use this one: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose
