### ISSUE TITLE
[vehicles/police] Bug Report - Extras are bugged on vehicles

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/legacy-assets-issue-tracker#783]
### Reporter

enutpeanut

### Summary

Cannot remove Extra 7 (spotlight) from the PD Taurus.

### Screenshots/Videos

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/116962577/10e24e27-a70c-40d3-b302-8884dda46d1c)

**Comment by Skai97** [comment]
This is also the case with the Hellcat speed unit

**Comment by ThisIsNotDex** [comment]
Extra removal is currently scuffed, to remove an intended extra this is what you have to do *Remove Extra (X), and then remove another extra (X) that you dont want actually removed, and only the first extra will actually be removed*

**Comment by coalaura** [comment]
is this still an issue? i bought a taurus, went to ls customs and removed ONLY extra 7 like you described and it stayed removed. Even removing a bunch of other extras i had no issue and they stayed removed even after storing and withdrawing.

![yes](https://i.shrt.day/RRMITSOMF2.webp)
