### ISSUE TITLE
Bug report - Sultan RS Super Car

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/legacy-assets-issue-tracker#784]
### Reporter

botjordan0000

### Summary

Sultan RS PDM car inside of the super section costs about 150k in-game, and makes this horrible bumping sound the entire time you are driving it. It practically doesn't turn.

My car is fully upgraded with lowered suspension. I don't have any offset on the wheels and it continues to do it. Very loud, obnoxious bumping sound whenever driving it. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1u9LWc0Bl1IGws/d1337EPcQ6rg?invite=cr-MSxCMDksNjIzMTM5NDks

**Comment by joevapes3** [comment]
I'll take a look at this and get back to you

**Comment by joevapes3** [comment]
@Skai97 I adjusted the handling on it, and it should be somewhat better, it's a weird car tbh though I think I found a common ground, the suspension knocking is gone as well so no more annoying bouncing sound. Anyways you can thank me later if you like it once it's live in a few days and may need some final adustments. Issue resolved....???? hoepfully
