### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by ashik3453** [InZidiuZ/legacy-assets-issue-tracker#785]
### Name

_imraj

### Summary

Unaverage Gang Legacy Roleplay Bangladesh clothing pack.

### Link

https://drive.google.com/file/d/12fE3rnNgHDVUyX1vQ9HS0RIeYGO6IKk1/view?usp=sharing

### Reason

There are many gangs in this city, and they wear different clothes. There is no specific dress for us. We are threatened whenever we wear any kind of dress. We therefore decided that our city needs a specific dress for us to maintain a positive environment. 

Therefore, we request that you add these clothes as soon as possible.

Thank you

**Comment by DaxterPancake** [comment]
I have added this and it should be in the server within the week hopefully!
