### ISSUE TITLE
[maps/?] Suggestion - Videogeddon TVs

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/legacy-assets-issue-tracker#786]
### Name

navonody

### Summary

We already have 1 of 7 TVs that work:
![image (4)](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/a5d7d0ef-db25-48cf-a69a-172782fdb363)

If possible, we'd like the 2 behind the bar to work as well:
![image (7)](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/ad574f92-b2eb-4024-882f-9bc241af618e)

I'm not too worried about the remaining 4, since they're at a slight tilt. I know the way the axis' work here, it would be difficult to get these panels to display properly.
Side 1:
![image (5)](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/91f7f697-c61e-4b86-9514-304d01272005)
Side 2:
![image (6)](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/43dfe1a1-6916-473b-8f20-a3e981262591)

### Reason

This would help alleviate the hassle of placing a TV down in front of the bar (which always gets stolen or washed away in server reset). This also helps create a more immersive Arcade experience.
![image (8)](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/75909c80-0012-4486-a6d4-e6c6bfec5702)

**Comment by DaxterPancake** [comment]
Our TV script does not work with tilted TVs. No way around that so probably won't be done. As for the other ones behind the bar, if we can find the prop name we might be able to do it but generally a lot of the custom interiors also use custom props which is why they don't have function with our TV script.

**Comment by navonody1** [comment]
> Our TV script does not work with tilted TVs. No way around that so probably won't be done. As for the other ones behind the bar, if we can find the prop name we might be able to do it but generally a lot of the custom interiors also use custom props which is why they don't have function with our TV script.

Yeah I understand. I saw how Bean Machine has it set up, and it doesn't look great...If those tilted ones have to be left alone, that's fine. If the ones behind the bar could be overlayed with panels that accept the TV script, that would be amazing.

**Comment by keaza** [comment]
honestly with the tilted screens i could do the equivilent of putting a PNG file ontop of the TV's if that would suffice, otherwise it would be a case of adding the custom prop to the list of TVs which i'm not sure is possible for custom props

**Comment by antihero6713** [comment]
this should be done
