### ISSUE TITLE
Bug report - Unable to walk thru area in Videogeddon (long time issue)

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/legacy-assets-issue-tracker#787]
### Reporter

navonody

### Summary

For a long time, a specific table has caused collision issues or prevents people from walking past in order to exit the building. Since it could just be an issue with available space, is it possible to just remove the table + stools in question? 

Area in question:
![image (9)](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/6cedb9b3-0608-4348-a61b-faba6716015e)

If possible, please remove these:
![remove these](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/209b6cb7-a255-4584-8b6f-fb7b5d2f0600)

Description of what's happening:
When attempting to walk thru, you start walk in place and cannot go further. If you stand still for a second, you can then continue to walk and it will let you thru; it just cannot be a continuous motion. 
You are also able to crawl under the area in question from the prone position:
![image (10)](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/ca9a5f48-17c7-4aa3-aef3-32428527ca52)

**Comment by MetaHatter** [comment]
This has been completed
