### ISSUE TITLE
Mutilple bank accounts and multiple user account bank accounts

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/legacy-assets-issue-tracker#788]
### Name

SluggsV2

### Summary

It would make business accounts and multiple player accounts a huge part of rp, 

Me and some buddies own a shop and would love it 

### Reason

The short sentence above says all it needs

**Comment by CloudTheWolf** [comment]
Wrong GitHub, should be raised here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose

**Comment by joevapes3** [comment]
as mentioned above the framework github is where this would go, please follow the link provided, closing this suggestion
