### ISSUE TITLE
Suggestion - Replace SOL Livery with Paleto Repairs Logo on MTL Custom (Or Add a new one)

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#789]
### Name

CloudTheWolf (On Behalf Of Xanny DeYeeto#0029)

### Summary

Paleto Bay Mechanics is being debranded from SOL to decouple from the gang

### Link

![Logo](https://cdn.discordapp.com/attachments/1133567826729386036/1154006806608228412/paleto.png)

### Reason

Decouple SOL from Paleto Bay Repair Shop

**Comment by CloudTheWolf** [comment]
@MetaHatter has now done this :poggers:

**Comment by MetaHatter** [comment]
This should now be completed.
