### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by thefinalgamer** [InZidiuZ/legacy-assets-issue-tracker#79]
**Reporter:**
Who is reporting this? Please include discord name.
th3finalgamer

**Summary:**
Write a summary of what you're experiencing.
I was flying the coke plane, got half way over the sea and got teleported back to the hanger. 10 seconds went by and got failed mission and lost the 1k
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

This isn't an assset issue so you'll need to re-write this issue @InZidiuZ  Github page.

_Karpenko_

_**OP-FW Vehicle Dev**_
