### ISSUE TITLE
[peds/ped-clothes-addon] Suggestion - Paleto Bay Repairs Clothing

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/legacy-assets-issue-tracker#790]
### Name

CloudTheWolf (On Behalf Of Xanny DeYeeto#0029)

### Summary

Can we get some Paleto Repairs clothing ty :) 

### Link

![Logo](https://cdn.discordapp.com/attachments/1133567826729386036/1154006806608228412/paleto.png)

### Reason

They deserve some dope clothing :3

**Comment by DaxterPancake** [comment]
Clothing this as there is now clothing for paleto repair (tshirt and overalls)
