### ISSUE TITLE
[maps/?] Suggestion - Gambling Table Added in Vinewood Mansion

### ISSUE THREAD

**Issue by oceandabs** [InZidiuZ/legacy-assets-issue-tracker#793]
### Name

Brendan Thompson (oceandabs)

### Summary

The Incognito Mafia needs a gambling table or multiple tables, added to the mansion that has open doors in the Vinewood hills. It is the mansion franklin had in the story.

### Reason

This would provide a more authentic gambling experience at future events.

**Comment by DaxterPancake** [comment]
Making something from scratch would literally take months. You're better off finding an already made free MLO that is what you want. But that being said, we have never added a whole custom building for a gang and there are multiple places that are unused already that we would suggest using first.

**Comment by antihero6713** [comment]
closing re-open if still needed
