### ISSUE TITLE
Suggestion - Add a garage inside LMC Repair Shop.

### ISSUE THREAD

**Issue by ShajadulGH** [InZidiuZ/legacy-assets-issue-tracker#794]
### Name

Shajadul Karim Bhuiyan#5183

### Summary

I am the owner of LMC Repair Shop in Lagacy Roleplay Bangladesh.  We need a garage inside LMC Repair Shop for Store our Tow Vehicles and customer vehicles when its too much rush. As Moseley  have a garage inside their repair shop. We need the same thing inside our LMC Repair Shop. That will be very helpful. So kindly provide us a garage inside the LMC Repair Shop. Thank You.

### Reason

If you add a garage inside the LMC Repair Shop , employees of LMC can easily use their tow truck and that will be easy to serve customers. Thank You.

**Comment by CloudTheWolf** [comment]
1) This is the wrong place, should be [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose):
2) I would say the Mirror Park Garage is close enough for the Lost Mechanic shop. The only reason Mosleys got a public garage was because there was no garage close by.

**Comment by MetaHatter** [comment]
This is not the right github for this.
Should use this one: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose
