### ISSUE TITLE
[maps/?] Suggestion - Add a TV on burgershot

### ISSUE THREAD

**Issue by sakarpaudel** [InZidiuZ/legacy-assets-issue-tracker#796]
### Name

realblackhawk

### Summary

Would be a great addition if we could show food and menus as well as events on a big screen.

### Reason

There are menu displays on burgershot which does not actually match the food we currently have. Would be better if there was usable TV screen.

**Comment by antihero6713** [comment]
closing for now re-open if you still think it needs it
