### ISSUE TITLE
Suggestion - Addition of new food items to burgershot

### ISSUE THREAD

**Issue by lunarz17** [InZidiuZ/legacy-assets-issue-tracker#799]
### Name

amanz17(Amanz#4928)

### Summary

The menu items available in burgershot has been quite outdated and old. There are multiple options which can be added as a new and creative food items.

There can be an icecream or choco lava cake or pudding sort of a thing as a dessert option.
As we make belgium fries using potatoes. Nuggets could be another food option which can be crafted using a slight different recipe for example maybe 2 potatoes or 4 potatoes for one nugget dish and it can be served. As we have 2 different type of burgers so a new go to snack is also a good option.

### Reason

It would give the players a new dish to explore in the city and a new experience for all the employees working at burgershot to try out new and dishes

**Comment by sanjanasaini** [comment]
love the suggestion! a desert sounds like a great add to the menu. 
 the regular menu (burgers, fries, smoothies) feels boring and basic now tbh.

**Comment by Billu9980** [comment]
+1

**Comment by Billu9980** [comment]
Good suggestion 👍🏻 I think Desert can be a great addition because there are very limited options for these kind of food in the city and it will be a new experience for BurgerShot family also.

**Comment by Ashishy27** [comment]
Great suggestion, already bored with burgers and fries, Addition of some desert will be great to make the meal complete.
