### ISSUE TITLE
Fix Big Bertha

### ISSUE THREAD

**Issue by brycepsd** [InZidiuZ/legacy-assets-issue-tracker#8]
**Reporter:**
Bryce.psd#8276

**Summary:**
I was doing trucking jobs one night and my phantom fell off the road and a rock hit the underneath of it. I thought I was fine till 3 minutes later when I ran out of fuel on the highway. Turns out Big Bertha was leaking all her fuel. I had to consistently get gas canisters and fuel up just to get to the mechanic were I fixed everything up thinking it would fix the leakage. It didn't stop the leakage and I have tried everything such as waiting for a reset, leaving it far way, leaving it in a garage, blowing it up, both repair kits. Nothing seems to work and I have spent over 7k just on trying to figure out how to fix this bug.

## Additional Information

**Screenshots:**
Here is a highlight from my stream. [Link](https://www.twitch.tv/videos/456934924)

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This belongs to the other GitHub page, not here.

**Comment by brycepsd** [comment]
This is what was linked tho lmao

**Comment by InZidiuZ** [comment]
Linked where?

**Comment by brycepsd** [comment]
On the discord, It says 
InZidiuZYesterday at 7:33 PM
We've launched a secondary GitHub page for anything asset-related. This mainly goes for vehicles and their handlings, so if you have any suggestions for new cars, handling edits or any vehicle bugs, feel free to report them here! This GitHub page is mainly tracked by @Karpenko, as he's the car dude. :) @everyone 

https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by brycepsd** [comment]
And this is a legacy vehicle problem Thonk

**Comment by InZidiuZ** [comment]
> This mainly goes for vehicles and their handlings, so if you have any suggestions for new cars, handling edits or any vehicle bugs, feel free to report them here!

Asset bugs, not scripting concerns. This is a scripting concern, there's not an issue with a model.

**Comment by brycepsd** [comment]
Ohhh my bad. Can you either forward me or link me to the right place.

**Comment by InZidiuZ** [comment]
Check #bugs-and-ideas

**Comment by brycepsd** [comment]
Okay thanks dad <3
