### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by thefinalgamer** [InZidiuZ/legacy-assets-issue-tracker#80]
**Name:**
Who is suggesting this? Please include discord name.
Th3finalgamer 

**Summary:**
Write a short summary of what your suggestion is about.
Jewellery, rings , necklaces  bracelet  something that we can give to people 
**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy? Loads of people in legacy are living a normal life, one of things I see happen in this server is weddings but I found it kinda strange that nobody had a ring. Just trying to help people live normal civs

**Comment by Karpenkooo** [comment]
Hey,

I don't have any plans to add these things just yet however i may consider something like this in the near future.

_Karpenko_

**_OP-FW Assets Dev_**
