### ISSUE TITLE
Suggestion - Addition of Garage for house at Vespucci Boulevard 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/legacy-assets-issue-tracker#800]
### Name

Kantibhai / Jignesh (gujju_businessman)

### Summary

Block Name: Vespucci Boulevard 
Block ID : 48 (As per legacy India server)
Total Slots/house: 15

I recently bought above block and got to know that many of the houses of this block dont have garage. Now buying house is not only getting a property but a space and place to store the items inside house and store car at garage. People Rent house in exchange of rent and not having garage make the house useless. And also not having garage in few house make that particular houses worthless for people and no one ever want to buy house without garage. 
I would like to see dev's adding garage at below house.

Below is the list of house that i sold & don't have garage. Please add garage to this houses if possible.

House Number that don't have garage:
Vespucci Boulevard 1
Vespucci Boulevard 2
Vespucci Boulevard 5
Vespucci Boulevard 12
Vespucci Boulevard 13 / Apt1
Vespucci Boulevard 13 / Apt2
Vespucci Boulevard 14

Where we can have garage for this house: 
(1) For Vespucci Boulevard 1 ,  We can use road side for garage and then they can use stairs to reach there house as shown in link " LINK A1"

(2)For Vespucci Boulevard 2 ,  We can use road side for garage and then they can use stairs to reach there house as shown in link " LINK  A2 "

(3) For Vespucci Boulevard 5 ,  We can use Maybe garage of Vespucci Boulevard 6 or We can add new garage for that house on road side as shown in "LINK A3" 

(4) For Vespucci Boulevard 14 , Vespucci Boulevard 13 / Apt1, Vespucci Boulevard 13 / Apt2 & Vespucci Boulevard 12  We can use garage space in front of house as shown in "LINK A4" 

### Link

LINK A1 : https://i.imgur.com/29rSYdf.png

LINK A2: https://i.imgur.com/MJmFsT0.png

LINK A3: https://i.imgur.com/z9TMMSw.png

LINK A4: https://i.imgur.com/y85S1un.png

### Reason

People get house in exchange of rent they are paying  and not having garage make the house useless. And also not having garage in few house make that particular houses worthless for people and no one ever want to buy house without garage. All of my customers/Tenant think that there should be garage  for every house.

It would be great for all the rp players and real estate owners if you add garage. 

Looking for your positive response as soon as possible.

regards,
kantibhai

**Comment by CloudCait** [comment]
Yes pleaseee I own this block on the international server and I have been STRUGGLING selling these houses and I never understood why until someone bought number 2 and said they don't have a garage and then I saw this github. I don't even know which ones do or don't have garages otherwise I'd reduce the rent on those ones.

**Comment by ayushpatel1007** [comment]
> Yes pleaseee I own this block on the international server and I have been STRUGGLING selling these houses and I never understood why until someone bought number 2 and said they don't have a garage and then I saw this github. I don't even know which ones do or don't have garages otherwise I'd reduce the rent on those ones.

In my server, people don’t even want to buy house without garage
