### ISSUE TITLE
Suggestion - Mechanic Masks 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/legacy-assets-issue-tracker#801]
### Name

gadjinee

### Summary

Was wondering if its possible to bring Mechanic shops branded mask (Hayes, MP Auto, Mosleys, Harmony, Paleto Repair)
![mask](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/124582929/5dced777-cc0d-4d8a-91d1-460cce3fefb0)

Maybe something in this style, for male and female 

or even just a normal bandana with small logo on side for each mechanic shop 

### Reason

The reasoning behind this as i see more and more people wearing masks in city due to not liking their faces, or just generic habit of wearing a mask. 
Think having a mask that we can associate to a shop while wearing with uniform, part of uniform, would be great

RP wise will help and keep all of our mechanics safe from all the fumes coming from cars on daily bases as well as gives an oportunity to not have any gang associated clothing while clocked in on duty, as mask would belong to shop and will be part of the uniform for mechanics.

**Comment by DaxterPancake** [comment]
Mechanics don't need masks. I won't be making this, sorry.

**Comment by gadjinee** [comment]
how about all the fumes coming from the cars? 
hard work to deal with all the health and safety regulations

**Comment by RetroCharles** [comment]
This would be great to have for mechanic shops. 
More clothing for mechanics to utilize for uniforms. Isn’t just for flashy purposes as well, chemicals and gas engines are health issues and typical safety regulations for any job.

**Comment by DaxterPancake** [comment]
I do not believe this is needed, the issue is closed. I read why you believe it should be added and I disagree so will not be making it.
