### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/legacy-assets-issue-tracker#802]
### Name

jr.bacon1

### Summary

I am Ryan Bacon the owner of Green Wonderland and I would like to suggest the ability to buy Joints directly from GW or have a rent free grow house.

### Reason

The reason I am suggesting this is because other business owners do not have to have a house that there needs to be a weekly rent payment on. We also have to buy fertilizer, water, buckets, and seeds.

**Comment by CloudCait** [comment]
Lots of mechanics have storage houses for materials as their lockers fill up pretty quickly 

Some restaurants have to go and source food like Kissaki gets a lot of their food from Jim or they have to go get fruits to make bubble tea
