### ISSUE TITLE
[vehicles/police] Suggestion - PD Submarine

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/legacy-assets-issue-tracker#803]
### Name

MetaHatter

### Summary

Create a PD sub as a counter to sending it into the water that's not "beating someone into submission" or insta-carrying them.

When the driver gets within range of a swimmer the driver uses the cuff command and the sub, with a progress bar, cuffs and transfers the escapee into the rear seat.

The range and cone in front of the sub as well as the speed of the sub can be adjusted to ensure some chance for escape.  The time it would take to acquire the sub and track down the escapee is also opportunity to escape.

### Link

Base GTA model that could be reskinned to PD: https://gta.fandom.com/wiki/Avisa 

### Reason

Currently sending it into the water is strongly discouraged as there are no real counters to the strategy.  PD shouldn't be beating someone to death in the water, shooting them feels wrong and insta-carry feels powerful and doesn't involve securing the captured individual.

Cuffing in the water also leads to drowning and swimming the captured individual back to shore is VERY slow, 

This would provide at least SOME viable option other than downing the escapee and, hypothetically, take way less coding than other options.

It would also provide an alternative or supplement, depending on server owner discretion, to Air One and thermals for locating people in the water.

Note: This is the asset tracker first to see if making the vehicle is even possible.

**Comment by King2704** [comment]
What's wrong with PD just carrying crims when they are swimming/diving?
The crims can struggle to get away again, a submarine seems very excessive and doesn't really make sense with the way how you explained it to capture crims.
In my opinion way to op.

**Comment by HollaYalla** [comment]
And not that realistic if you ask me.

**Comment by MetaHatter** [comment]
> What's wrong with PD just carrying crims when they are swimming/diving? The crims can struggle to get away again, a submarine seems very excessive and doesn't really make sense with the way how you explained it to capture crims. In my opinion way to op.

As stated in the suggestion... Carrying is VERY slow and there is no way to cuff an individual so it's a guaranteed struggle out and keep chasing situation.  It's a horrible gameplay loop.  The only alternative currently is downing the escapee, which requires EMS assistance and downtime that shouldn't be necessary for most captures.

If it's too OP or unrealistic for a particular server's liking they can always choose not to use it.  But it's no less realistic than driving around with a scuba tank on your back, PD punching someone unconscious to capture them, or carrying someone instantly in the water without their consent.  It's realistic enough.

**Comment by COWBOI28** [comment]
> > What's wrong with PD just carrying crims when they are swimming/diving? The crims can struggle to get away again, a submarine seems very excessive and doesn't really make sense with the way how you explained it to capture crims. In my opinion way to op.
> 
> As stated in the suggestion... Carrying is VERY slow and there is no way to cuff an individual so it's a guaranteed struggle out and keep chasing situation. It's a horrible gameplay loop. The only alternative currently is downing the escapee, which requires EMS assistance and downtime that shouldn't be necessary for most captures.
> 
> If it's too OP or unrealistic for a particular server's liking they can always choose not to use it. But it's no less realistic than driving around with a scuba tank on your back, PD punching someone unconscious to capture them, or carrying someone instantly in the water without their consent. It's realistic enough.

I think a PD Sub would be cool but it think that it would be overkill maybe a system where if you carry a crim you have the option to cuff them while your carrying them and then being able to "suspect in" them onto a boat and then be taken onto shore . While it's not as cool or flashy i think it be a bit more practical and realistic then adding in a whole submarine .
