### ISSUE TITLE
Suggestion - Prison Break 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/legacy-assets-issue-tracker#808]
### Name

gadjinee

### Summary

Prison Break Legacy edition 

So this idea comes from the prison break show and been part of DOC for a while kinda thought would be cool to see if it’s possible to do it 

So the idea is to any prisioneira ( HUT or anyone with over 200 minutes ) been able to find other things while cleaning 

- metal, scrap, alum, map pieces / note with riddles to escape routes 

That for example would allow you to create key / pass that would allow you to open certain doors for outside of prison.

Also they could find like a map pieces that could be combined somewhere in prison with like escape routes 

Also getting the crafting locations in areas of the prison that are not easily accessible and will involve RP. (Combine map pieces in to one map in laundry room, with is required to someone from DOC to open)
Prisoner can come out with clever ideas on why would they need to go up to laundry room or any other locations.

I have few idea on what doors can the keys / cards unlock maybe creating a route around the prison so it’s not very obvious and prisoners would need to sneak in to get out.

Don’t know if this was mentioned before but thought would be good to have something like this, from DOC prospective as well as HUT prisoners.

Having the ability to escape, DOC could then contact PD to issue a warrant and get man hunt on the go.
Maybe even notification to PD and DOC that the inmate did escape

### Reason

Think this would be great for some DOC interactions, again some of the crafting would involve RP’ing in order to get through the officers on duty

getting DOC a bit more involved in man hunts also stop people logging of as soon as they go to jail and wait in idle mode, we want them to actually do the time

**Comment by coalaura** [comment]
This would be for the [script github](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
