### ISSUE TITLE
High Beams on PD Ford Interceptor Sedan

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/legacy-assets-issue-tracker#81]
**Reporter:**
Masik52#5834

**Summary:**
When you hit H to turn the high beams on the lights are projected to the back of the vehicle instead of the front.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
Normal lights 

![image](https://user-images.githubusercontent.com/52395441/66885477-692fee00-efa2-11e9-9e48-4d51796b3d50.png)

High Beams

![image](https://user-images.githubusercontent.com/52395441/66885524-8cf33400-efa2-11e9-8633-54b99a659e1a.png)

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey, 

Thanks for providing me with these images. I'll take a look into the issue however i'll porbably just need to swap the model for another vehicle. 

_Karpenko_

**_OP-FW Assets Dev_**
