### ISSUE TITLE
Suggestion - Remote Vehicle Start

### ISSUE THREAD

**Issue by JasonPTodd45** [InZidiuZ/legacy-assets-issue-tracker#813]
### Name

duckfucker223

### Summary

Okay so in GTA online, You can remote start your vehicles it would be hella awesome if in legacy your able to use the same menu to remote start your vehicle as well! 

### Link

https://gta5mod.net/gta-5-mods/scripts/remote-vehicle-control-v1-1-2/

### Reason

It would be really cool for car meets and stuff. Be able to start your car and let it warm up before driving or racing. It was a nice feature in GTAo and id like to see it get implemented here

**Comment by coalaura** [comment]
This will not happen
