### ISSUE TITLE
Bug report - Boats stealing my money

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/legacy-assets-issue-tracker#814]
### Reporter

enutpeanut

### Summary

When pulling out a (civ) boat, sometimes it says 'the area is not clear', even when it is. Your money is taken and no boat is spawned.
Only happened with the Toro at Paleto so far, but if I find more I'll update.
(Related} Also, had a bug with the Marquis where I could not park it, but it seems like a one-off. Also from Paleto boat spawner.

### Note

https://medal.tv/games/gta-v/clips/1FoV0un7qA5wJm/d1337nRKbAZo?invite=cr-MSxwOUssMjUzNzIxNjcs

**Comment by ImArteria** [comment]
This is for the script github
https://github.com/InZidiuZ/op-framework-issue-tracker/issues
