### ISSUE TITLE
[maps/?] Paleto Repair Shop - Suggestion

### ISSUE THREAD

**Issue by AndyToretto** [InZidiuZ/legacy-assets-issue-tracker#818]
### Name

Andy Toretto

### Summary

I think the place could do with a few changes, I've recently just took over the shop and have a few things in mind, some are simple other of which are complete long term things that I honestly think would benefit the shop and have more people wanting to come up the top of city.

1. We really could do with a water fountain being added to the shop many of the staff have asked for it and I wouldn't want any customers going thirsty.

2. Id love you host event in the bar that's attached to the repair shop. I think it would be a good idea to have taps on the bar where we can sell alcohol and food. Also that would require an alcohol license for the shop.

3. Id love if we could change the name from Paleto Bay Repairs to "Toretto's"

4. We have a huge showroom that's just going to waste and its already set up for motorcycles, I think a good way is to have only motorcycles from PDM sold within the showroom. If you were to remove said motorcycle's from PDM and have them all sold here it would bring not just the MCs further up city but all new people to city, I say new people due to the fact bikes are some of the cheapest form of transport in city and it would be an easy first buy.

5. Have the showroom mechanic bay next door to the office operational, Not only does it give another bay it also allows for easier and better RP when the "BOSS" is working on your car and getting it just right.

6. Desperately in need of a clothing spot where we can get into uniform. maybe in the bathroom.

7. Uniforms with logo and new name.

### Reason

Paleto Bay Repairs is such a big repair shop with much more potential than just a repair shop, i think with all these changes been put in place over the next few months, that it would separate people from always been down in city and have them branch further up. With a little TLC and some effort the shop could really benefit massively not just that but so would the staff thats so determined to make the place the best earning repair shop in the city one day.

**Comment by coalaura** [comment]
> We really could do with a water fountain being added to the shop many of the staff have asked for it and I wouldn't want any customers going thirsty.

Easy to do, will be added

> Id love you host event in the bar that's attached to the repair shop. I think it would be a good idea to have taps on the bar where we can sell alcohol and food. Also that would require an alcohol license for the shop.

Adding a bar store to the shop would be a [script suggestion](https://github.com/InZidiuZ/op-framework-issue-tracker/issues). 

> Also that would require an alcohol license for the shop.

There is no such thing as an alcohol license.

> Id love if we could change the name from Paleto Bay Repairs to "Toretto's"

You can rename it through RP, however the sign will most likely not be changed since that would affect all subdivisions.

> I think a good way is to have only motorcycles from PDM sold within the showroom

This will not happen

> Have the showroom mechanic bay next door to the office operational, Not only does it give another bay it also allows for easier and better RP when the "BOSS" is working on your car and getting it just right.

showroom mechanic bay? Where, which one? Could you send a screenshot of what you mean exactly?

> Desperately in need of a clothing spot where we can get into uniform. maybe in the bathroom.

This would also be a [script suggestion](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).

**Comment by MetaHatter** [comment]
The water dispenser and vending machines have been added.
