### ISSUE TITLE
Drift Tampa

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/legacy-assets-issue-tracker#82]
**Reporter:** Randy James#4851
**Summary:**
Add Modes for the car like /Drift /Sport 
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
Hey,

While i can't make modes such as /Drift,/Sport,/Drag Etc. I can change the handling of the Drift Tampa as you requested. I'd appriciate if you put a bit more effort into your bug reports in the future. 

_Karpenko_

**_OP-FW Assets Dev_**
