### ISSUE TITLE
Suggestion - serial numbers on guns

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/legacy-assets-issue-tracker#820]
### Name

selliee

### Summary

I believe that to enhance role play from all aspects, removing 'serial numbers' from 'illegally imported guns' is something that should be considered.

### Reason

Something that makes a gun illegal, is the fact that it does not have a serial number. 

I believe that removing this aspect, would enhance the low quality RP that has been happening surrounding these sorts of guns. 

Walking up to a person, asking for the serial number on their rather large gun- would never happen realistically. People with illegal weapons should be 'feared', neither would someone probably hand over a gun of such for anyone to inspect realistically. 

I feel like it is important to note that having these serial numbers on these guns, also can hinder the RP of the person possessing the gun.. removes the possibility of having a 'scratched off serial number' scenario, if someone were to obtain the weapon & look for the number.

**Comment by DaxterPancake** [comment]
This is the wrong github for this suggestion, please report [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues).
