### ISSUE TITLE
Suggestion - add the back to back world war champion: M1911

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/legacy-assets-issue-tracker#823]
### Name

scufflord

### Summary

Adding a Kimber 1911 tactical + attachments to the framework. 

### Link

https://www.gta5-mods.com/weapons/1911-kimber-tactical-animated

### Reason

1911's are the best gun of all time. They won two World Wars and they'll win your next gang war too.

**Comment by coalaura** [comment]
im sold
