### ISSUE TITLE
[maps/?] Suggestion - neighborhood update

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/legacy-assets-issue-tracker#824]
### Name

SluggsV2

### Summary

Nikola Place Mirror Park Gated Community + removing the For Sale Sign Boards on front lawns

### Reason

Can we make the Mirror Park Mansions Nikola Place Gated makes them feel upper class and safer just on at the end of the street nothing crazy and please could we take away the for sale sign boards!

**Comment by ImArteria** [comment]
I'm pretty sure we declined this in the past due to us having to unnecessarily stream the area.
