### ISSUE TITLE
Suggestion - Red Mafia Old Mask

### ISSUE THREAD

**Issue by ivanez1** [InZidiuZ/legacy-assets-issue-tracker#826]
### Name

ivan_ez

### Summary

Its a Official RED MAFIA mask which is used in Legacy India 2022 and 2021 for RED MAFIA. And like last time, this should be added again. so Please Add This Mask Again for RED MAFIA Gang.

### Link

![IMG_20231122_011356](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/138415095/d3f73b5f-c9b5-47ee-a4b8-e90d8274d7d7)

### Reason

I respect it as always and love to share my gang roleplay with legacy so i want a little favor to you add this mask again in legacy for Red Mafia like 2021 and 2022 legacy india update.

**Comment by DaxterPancake** [comment]
Absolutely not, sorry.
