### ISSUE TITLE
[vehicles/heli] Bug report - Heavyweight Heli (Pave Low) Wayy to fast?

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/legacy-assets-issue-tracker#827]
### Reporter

tyyy1022

### Summary

With the new Heavyweight chopper, (idk the full name but its (..) Pave low,), it's really quick in the sense that if you angle the chopper in any way, it will almost do a flip. Specifically forwards and backwards.

### Note

I'm guessing this will only be an issue with mouse control, but I'm not sure on that.

**Comment by coalaura** [comment]
fixed
