### ISSUE TITLE
[maps/?] Suggestion - Paleto Bay Repair shop

### ISSUE THREAD

**Issue by AndyToretto** [InZidiuZ/legacy-assets-issue-tracker#829]
### Name

Andy Torretto

### Summary

Hello, I currently own Paleto Bay Repair Shop. I was hoping to put over yet again a few ideas just to help out attractions in Paleto Bay to possibly help the revenue of the mechanic shop. although ive doubled profit from previous owners I'm still not getting the custom needed. So to change a few things within the shop just to help the guys out and myself.

- A water fountain, I was approved this once before yet it wasn't yet added
- Vending Machines, which would save all mechs and customers a trip to the store every time were hungry
- A gas pump, We have the outside bay for bigger vehicles but recently we have been using them for cars thats ran out of fuel and heavily damaged cars. Adding a gas pump where you either able to refill or purchase a jerry can would be very beneficial due to the fact of not having to ask the customer to run to the nearest gas station. which isn't miles away don't get me wrong but its still a bit of a nightmare running their and back. and losing that little bit of RP feel to it.
- The Bar, Making the bar operational would be great for a venue spot or event spot. It can be done through RP at the monent with the purchase of alcohol elsewhere. but making it where Paleto can hire bar staff and sell it from their. I honestly think would help out majorly to even bring people up to Paleto.
- Id like the store to be called Toretto's Garage/Toretto's Repair, I've done this through RP as is however id just like the logo changing. I will attach the logo as I've already managed to make one up if i were approved. 
![Toretto Repairs Logo](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/153224433/1257ac79-7fb9-4e18-9fbc-9e17094c0f5f)

Paleto Bay in general lacks so much attractions which is the main problem for the shop theirs been a tool store added which is great but obviously its not changed much in regards of profit in Paleto. I have a few ideas id just like someone to look over them and see if I have any chance of making a difference.

- A Second Daily's Spot. Maybe over from the shop where them empty warehouses are just in form theirs stalls and everything their to make it an awesome daily's spot. whether they need handed in or someone flew out in sandy or Paleto they wont have to travel all the way down to the city to collect their reward or to even check out said daily's.
- Motorbikes, I've asked this before and I did get knocked back but I've changed it a little before i asked for motorbikes to be removed from PDM and placed up in Paleto. I understand that's not possible however what if the showroom on the Repair Shop sold them as well as PDM. might not bring loads more people up but we could place them at a discounted price to entice people to make the journey.
- Get someone to buy the Bar, Paleto Bay has a massive bar with an underground fighting ring. with the right person that bar could be insanely profitable bringing more people up to Paleto and having a possible fighting venue which no where else in the city has other than the country club but that's more of a gym than it is a fighting club. None the less it can be done through RP either way again with the right ownership. especially if the bar on the repair shop isn't ever going to be operational. 
- Tattoo Removals, To be honest ive not met a person in city that isn't wanting to have tattoos removed. their potential for this where you could make it a whole fresh new business in Paleto with new staff and fresh faces. i believe they can be removed in a hospital at the moment but im unsure on that to be honest. but i think a business for them to be removed where its as quick to take them off as it is to put them on would be great. and better if it were in Paleto.

### Reason

That's it for now of what I've managed to come up with and right down, we need help up in Paleto as everywhere else in thriving in city bar Paleto to just put things in a little prospective for you. Last months revenue at the Paleto garage was just over 800k. with some research and a few friends to let me in on what they made I found that Harmony in Sandy Shores made over 2m that's double Paleto and i mean Mirror Park Quadrupled it. Paleto doesn't lack hard workers or active people. It lacks attraction. and giving the right things in place … it could be thriving just like the main city. I know this is a lot but I'm not wanting to give up on the place, Tank you for taking the time out for reading all of this. Please get back to me when you can.

**Comment by COWBOI28** [comment]
Tattoo removal is a revenue source for EMS so i don’t  think they be happy giving that up

**Comment by HollaYalla** [comment]
There is a lot of issues with this

* The bike selling inside of the Paleto Repair shop could cause issues with your job on the backend side but I’m not sure plus yes it seems good on paper but it also removes the rp PDM can get from the motorbike sales if anything make another spot in the city that sells off-roading vehicles and bikes

* The bar would be a very nice addition but it makes Paleto Repair kind of a one stop shop which can take out the RP other places in Paleto can benefit from

* The logo was told by Laura in a previous Issue that it is going to stay on this logo as the map and buildings share between servers so it wouldn’t make sense for the Indian division to have Torettos Repairs when they are already branded and everything as Paleto Repairs. Also if you were to get found not fit to own the repair shop or it gets shut down in the international server or even you get banned it would still be torettos repairs on all the other OPFW servers, I believe it causes lag as well and unnecessary work for the devs that can be working on other stuff


Now I am not a Developer or anyone who has a say in the future of OPFW and they may do some of the stuff you ask but I am just saying for those it is probably a very slim chance it happens.

I am not trying to sound dickish and these are good ideas that can improve Paleto but it can give the repair store too much power up there.

**Comment by ThatSinisterGuy** [comment]
Just to add 2c here, while a gas pump at the shop is a nice idea on paper, in practice it's a massive headache. Just ask anyone who worked Flywheels back in the day. People will bump into those pumps regularly and explode them, causing a mess to clean up and leaving non-functioning pumps unless everyone leaves the area so the cell can reload. Honestly it's just not worth it.

**Comment by MetaHatter** [comment]
Regarding the map updates, I will look into adding the vending machines and water today.

On the other points, my thoughts:
- I am not on board with renaming the shop. It is used across all OPFW servers and having a generic name is more flexible for RP.
- There is a gas station and store less than a block away so no reason to add exploding pumps at the shop. Buy Jerry Cans.
- The business is a mech shop. It does not also need to be a bar, bike dealer and fight cub. Too much for one spot.
- Tattoo removals is an EMS function.
- The bazaar is a singular spot for people to cross paths. Creating multiple goes against its core purpose.

There are pros and cons to buying a business in a remote, rural town.  You have to expect going in that owning a remote business will make far less money than one in a city.  That's true in reality as well.  It will never be and, arguably should never be, as thriving as the city.

There are also negatives mechanically and socially with pulling too many people too far from the population centers. (EMS/PD/etc RP).

**Comment by HollaYalla** [comment]
A good way you can run the bar is purchase a lot of food and alcohol and host like a karaoke night or smth there and sell it upcharged or cater from someone

**Comment by AndyToretto** [comment]
Thanks for the feedback. As for the fighting place i ment the bar down the road not the actual repair shop itself … its been up for sale for so long now because no ones wanted to buy it ... selling it to someone that can make a good business out of it might give Paleto that little bit better of a chance, however tis just finding someone to buy it.

Thanks for the vending and water

Hearing the rename thing now i understand why not.

And yes Paleto may be remote destination right up in the sticks I get the point in that, like and old town sort of vibe, I honestly just thought id get some ideas out their to try and pick up the town a little bit than it been this old run down place no one wants to go to.

**Comment by MetaHatter** [comment]
Water dispenser and vending machines should be in w/next asset update.
