### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KiwiUK** [InZidiuZ/legacy-assets-issue-tracker#83]
**Name:**
Kiwi#6887

**Summary:**
Probably won't get looked at but I would love to see this in the next exclusive dealership :)

**Link:**
https://www.gta5-mods.com/vehicles/2017-mercedes-benz-c63s-amg-coupe-add-on-tuning-template

**Reason:**
I saw Ivanov say something about suggesting cars so I though I might drop one. Might encourage people to donate.

**Comment by Karpenkooo** [comment]
Hey,

Thanks for the suggestion. I've noted it down so you may see it in the future.

_Karpenko_

_**OP-FW Asset Dev**_

**Comment by KiwiUK** [comment]
Thanks man, I really appreciate it!
