### ISSUE TITLE
[vehicles/?] Bug report - Nissan Silvia S15 Suspension Bug.

### ISSUE THREAD

**Issue by SkippingBaboon** [InZidiuZ/legacy-assets-issue-tracker#835]
### Reporter

Baboon - Skipping Baboon

### Summary

The final and most expensive suspension upgrade named "Competition Suspension" is currently bugged on the EDM car Nissan Silvia S15 and is identical in ride height to that of the "Stock" suspension (effectively making it pointless).

It should be lower than the "Sport Suspension" of which it is not, it should be the lowest ride height suspension upgrade.

### Screenshots/Videos

https://drive.google.com/file/d/1EJa6aoXByZivtmcaVlkeIp2Yb32hIVr9/view?usp=sharing

### Note

Please fix I love you long time.

**Comment by coalaura** [comment]
closing in favor of #927
