### ISSUE TITLE
Suggestion - Add Red Mafia Official Mask  

### ISSUE THREAD

**Issue by ivanez1** [InZidiuZ/legacy-assets-issue-tracker#836]
### Name

ivan_ez

### Summary

This is a mask for Red mafia Gang to wear and respect his mask and do rp with high quality so please add this mask in the server 

### Link

this is mask png and 3d model to previews and i have also a .ytd file to add this mask easly in server. 

![berd_diff_016_a_uni](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/138415095/062fe585-e954-4f32-b4d4-5639f2db5650)

![Screenshot 2024-01-27 233738](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/138415095/7b561ce6-8bcd-4bf7-a873-d179e7cd3e70)

Link ytd file.---https://drive.google.com/file/d/1jvAmy3ASvI3HGkv_p2ax4MmE4tN8095R/view?usp=sharing

### Reason

We don't have its original mask, so it dictates to us. And if we add this mask then it will be even better and Red Mafia will get a different identity. so please add this mask ,I designed it with my own hands its not a copy from others platform.

**Comment by coalaura** [comment]
We have some bad history with gangs named "Red Mafia", i'd rather not bring that name back xD

**Comment by ivanez1** [comment]
> We have some bad history with gangs named "Red Mafia", i'd rather not bring that name back xD

are yrr history bad thi log bad honge but aage future hm bana rahe h.... toh add krdo na kya masla h yrr itna  piche ka huwa jo gaya

**Comment by DaxterPancake** [comment]
When an issue is closed please refrain from continuing to comment. 

We will not be adding any gang gear that represents Red Mafia. The only thing I suggest is picking a different name and then it may be considered.
