### ISSUE TITLE
housing issue - 

### ISSUE THREAD

**Issue by Noquitt365** [InZidiuZ/legacy-assets-issue-tracker#837]
### Reporter

yt.noguit365.yt

### Summary

my house with the address **wild oats 5**  has 2 issues.  first i have 2 back decks with 1 having my pool on it the rear door takes me to the bottom deck but the only way that you can get to the upper deck and pool in to jump on a a picnic umbrella to get there.  could you add a stairway to get up and down from here from the deck.  the second issue is once in the back yard if you jump off the deck you cannot exit the back yard without going around the neighbors house could u add a gate or passageway to use. at this moment the most import fix is the stairway added to access the pool deck thank you

### Screenshots/Videos

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/158012164/ea44aa1b-e057-4f69-be88-588cdb5b7668)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/158012164/8a4512ef-f605-4eb9-a45f-471d2db5343a)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/158012164/8850fe8a-7855-4045-a57b-fcb8ee26aac3)

**Comment by coalaura** [comment]
this wont happen as we would have to stream the entire block
