### ISSUE TITLE
Suggestion - Be able to change level of car engine sounds - kind of how radio sound can be changed

### ISSUE THREAD

**Issue by MAGiCxPOTATOE** [InZidiuZ/legacy-assets-issue-tracker#838]
### Name

xxfaze_magicx_potatoexx360

### Summary

make a option to turn down the volume of car engines like you can do with radio. So make it like if the radio one is /radio_noise 50 for 50%. Then the car one would be like /car_volume 50 for 50% or original volume. Although it would need to have a cap at like 30% or something so people cant turn their engine sound of completely to try hard in police chases or if they are tryna sounds whore something they shouldn't be able to hear if the engine was on.

### Reason

Sick of trying to talk to people or hear people when trying to RP and all i hear is BRRRRRRRRRRRRRRRRRRRRRRRRRRR BRRRRRRRRRRRRRRRRR CCCCCCCssssssshhhhhhhhhh. So it would actually allow me to hear my radio or even the people in my car if im trying to have a convo. Some examples are the GTR cars, they are awful. It also make sense that the audio in cars is quiet cause i dont remember a time in real life where i could hear another person in the car yelling just cause the engine sounds like it was inside my eardrum

**Comment by coalaura** [comment]
There is no way to change the engine sound dynamically. Sounds can be changed globally but not otherwise.

**Comment by MAGiCxPOTATOE** [comment]
Womp womp
