### ISSUE TITLE
Bug report - unable to do zombie in Franklin mansion zombies not coming inside franklin

### ISSUE THREAD

**Issue by sakil987536** [InZidiuZ/legacy-assets-issue-tracker#839]
### Reporter

sakil.__.

### Summary

Zombies not coming inside franklin mansion kindly solve it asap

**Comment by coalaura** [comment]
what? more detail please...

**Comment by MetaHatter** [comment]
If I'm reading it right I think they want AI to walk into the building. 

Unless I am mistaken there is no AI navmesh to allow them to path into and out of a lot of interiors.  It's a GTA thing.
