### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by novasosa** [InZidiuZ/legacy-assets-issue-tracker#84]
Reporter:
 novasosa#7875

Summary:
Whenever I repair the window of my black fin, it just doesn't get fixed.. Front window in general.
Roof keeps going on and off whenever I put a new piece of glass.

Additional Information:
I recently bought the black fin from a friend.

**Screenshots:**
https://plays.tv/i/5da8ec382e6ef549ee/fivem

**Comment by InZidiuZ** [comment]
That car was removed from the dealership for a reason. If you want me to manually delete it from your garage, let me know & can help you.
