### ISSUE TITLE
UI adjustment Ultrawide

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/legacy-assets-issue-tracker#840]
### Name

BotSkai

### Summary

A command for adjusting the size of the inventory UI/Htotbar 

### Link

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/52269307/862520a4-93e1-44c7-a1f6-aa49c67c4c7a)

### Reason

Ultra Widescreen makes the UI all funky. Hotbar is very large compared to the map and other UI. 

Inventory is huge, made for 1920-1080 and its scaled up. Can count the pixels. 

Idk if it can be done but it would honestly just be a quality of life thing

**Comment by coalaura** [comment]
This is the wrong github, this is for assets like cars, clothing and mapping related changes. There is a setting in FiveM that forces UIs to be 1920x1080, this will not be fixed
