### ISSUE TITLE
Suggestion - Weapon Sfx Sound Of 1911 Kimber Pistol

### ISSUE THREAD

**Issue by Poisonous13** [InZidiuZ/legacy-assets-issue-tracker#841]
### Name

shoccho12

### Summary

There is new weapon added to the server Name : 1911 Kimber Tactical . The Sfx Sound of the gun is from Pistol .50 . So My Suggestion is to change the sound .50 to Heavy pistol sfx sound . 

### Reason

1911 Is IRL Gun which sounds like much similar to heavy pistol . And also the .50 sound is very loud but the 1911 is not a loud gun . It will be great and Cute If you change the sound .50 to heavy pistol . Thanks

**Comment by coalaura** [comment]
I made it the .50 sound so it sounds more agressive
