### ISSUE TITLE
Suggestion - New fire station

### ISSUE THREAD

**Issue by mastersamii** [InZidiuZ/legacy-assets-issue-tracker#842]
### Name

mastersamii

### Summary

I'm suggesting the construction of a new fire station to address the limitations of our current facility. After being stationed here for a year, it's become evident that our current space is insufficient for our needs. With over 30 personnel and ongoing growth, the existing station's small size poses challenges, particularly with tasks like clocking in, changing, and conducting interviews or presentations. The proposed new station, located a short distance away towards Grapeseed, promises to provide the space and resources we need to operate more effectively.

### Link

tour video: https://www.youtube.com/watch?v=7YR1e8oUtWE&t=1s

I have the file for the fire station already I cannot attach it because it is too large.
(One of our firefighters bought it before I could even tell them not to)

### Reason

The primary motivation behind advocating for a new fire station is to address the limitations imposed by our current facility. As our team has grown, we've encountered various operational difficulties due to space constraints. By relocating to a larger facility, we can not only overcome these challenges but also significantly improve our operational efficiency and effectiveness. Additionally, the new space will provide opportunities for expanded training activities, allowing us to better prepare for emergencies and serve our community more effectively.

We recognize that the transition to a new station may require some effort and that there are no guarantees that the proposal will be implemented. However, we believe that it's essential to explore this option to ensure that our team has the resources and infrastructure needed to fulfill our duties effectively.

Moreover, it's important to clarify that our intention is to replace our current station with the larger one. This move is necessary to accommodate our growing team and better serve our community.

Additionally, the inclusion of a helipad will be needed at the new fire station as it doesn't currently have one and is crucial for enhancing our capabilities.

**Comment by coalaura** [comment]
If the tour video is by the same people who sell it i'm fairly certain the asset is completely unusable since its escrowed, thats why we always say not to buy things until you are told that it will actually be put in

**Comment by coalaura** [comment]
based on it being operated by tebex AND asking for your cfx username when checking out

![yeah](https://i.shrt.day/9E33MLOS5K.png)

**Comment by HollaYalla** [comment]
If we found a non escrow map file would yall look into it?

**Comment by coalaura** [comment]
We can always look into it but dont purchase it right away before we tell you that we are actually gonna use it

**Comment by HollaYalla** [comment]
> We can always look into it (if its not escrowed ofc) but dont purchase it right away before we tell you that we are actually gonna use it

Just a quick question why can’t yall use a escrow MLO?

**Comment by mastersamii** [comment]
I do apologize I know that we shouldn't buy anything before asking and I did in fact mention that then got sent the file for the station a few days later. I did attempt to see if it was escrowed by asking Arteria but I think he was unable to tell when he checked the map.

**Comment by coalaura** [comment]
If the checkout is done through tebex and it asks you for your CFX.re login, thats a good indicator to know if something is escrowed or not (for next time (ask))
