### ISSUE TITLE
[maps/?] Suggestion - Replacing Graffiti at Bay City Avenue 1/2

### ISSUE THREAD

**Issue by Jvyxh** [InZidiuZ/legacy-assets-issue-tracker#844]
### Name

jme666

### Summary

At the moment there is a graffiti sprayed logo of a previous gang that held this block a couple of months ago, tang gang. For the past 4/5 months the location has been held down by a new up and coming gang "The Irish". We are looking to remove the current logo and replace it with our own. Apologies in advance if this is wrong place to make this request.

I would be happy to provide logo files if this request is approved. Thank you

### Link

![The-Irish---Eire-Logo-two-colour2](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/159549169/50d1a3bb-1701-4e3e-8487-d9e9085dd410)
![Screenshot_4](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/159549169/5066dec2-8257-48d5-985e-e5962509cc68)
![Screenshot_2](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/159549169/a1060f2c-5b36-4fd4-93f6-78c5625c5ace)

### Reason

I believe tang gang are no longer an active gang in our city

**Comment by MetaHatter** [comment]
We will add removing the tag to the list but it is unlikely that we will be replacing it.  We have been making an effort to be more gang agnostic as this framework is used over many servers.

**Comment by MetaHatter** [comment]
The tag should be removed now. 
We won't be adding a new logo. As I said before, we are making a concerted effort to ensure mapping assets are gang-agnostic to ensure RP is as flexible as possible across all regions and OPFW servers (another gang on another server might want that house).
