### ISSUE TITLE
[maps/?] Suggestion - Removing trash bins from Bay City Avenue 1/2

### ISSUE THREAD

**Issue by Jvyxh** [InZidiuZ/legacy-assets-issue-tracker#845]
### Name

jme666

### Summary

Would be it be possible to remove the trash bins from outside of block Bay City Avenue 1/2

### Link

![bins](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/159549169/603efe21-9bb5-409b-a0a3-c6ddce04dab1)

![bins location](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/159549169/0ba8034f-949b-4deb-bbf1-3de2b78d0b33)

### Reason

 People tend to hang out here and sit along the wall and chat. We've found when trying to check your pockets, your character instead searches the bin from meters away, again not even sure if this is possible but would be great to get these moved/removed completely

**Comment by coalaura** [comment]
i really dont think this is needed
