### ISSUE TITLE
Suggestion - Add wheelchairs as a placeable thing (like chairs)

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/legacy-assets-issue-tracker#846]
### Name

tyyy1022

### Summary

Instead of EMS having to give wheelchair keys to people, allow wheelchairs as a placeable thing like a dildo or a seat.
To make it so it cannot be abused: Add it as a "prescription", so the EMS will give the chair after surgery or whatever, and then they will /report and get a staff to give the patient permission to actually place it? (Idk if this is possible, it's just off the top of my head)

### Reason

For the people who are around in the earlier times, when no EMS are around, it's much more convenient.
If you cannot access EMS at those times, you cannot do the injured RP. Especially if you're told to not walk, because then you're stuck in a predicament.
It's also easier, for example, if you need to store it somewhere. Like "Fold it up" and put it in the trunk of a vehicle for a friend to drive you around.

**Comment by coalaura** [comment]
I don't see a need for this considering you can just get the actual wheelchair prescribed...

**Comment by scufflord** [comment]
> I don't see a need for this considering you can just get the actual wheelchair prescribed...

Yes, but then usage of it is limited to only when EMS are on duty to hand it out to that individual that day. Perhaps treat it like a license? When the prescription is handed out it applies a license that is then revoked after whatever the length of the prescription is? Allows people to access a spawner at Mt. Zonah to spawn and put away their wheelchair.

**Comment by txxlrrsCoding** [comment]
> > I don't see a need for this considering you can just get the actual wheelchair prescribed...
> 
> Yes, but then usage of it is limited to only when EMS are on duty to hand it out to that individual that day. Perhaps treat it like a license? When the prescription is handed out it applies a license that is then revoked after whatever the length of the prescription is? Allows people to access a spawner at Mt. Zonah to spawn and put away their wheelchair.

Yeah, like scuff said. It's only available if theres EMS. Which in my case, there isn't. Even for brits, which is a good population of the city, it's not available in the earlier times.

**Comment by txxlrrsCoding** [comment]
To add onto this @coalaura, Only doctors can pull the wheelchair. Which there's only two of, so it makes it a lot harder, especially when one of the two doctors flies in at 4am for me.
