### ISSUE TITLE
Suggestion - Green Wonderland business calls

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/legacy-assets-issue-tracker#847]
### Name

tyyy1022

### Summary

Since GW can deliver to businesses and mining spots, I think we should have a phone contact like state or any food spot.

### Reason

Same reason any other place has a phone number. Also means people will stop begging on twitter, they can just contact the line and see if anyone is around to open up.

**Comment by coalaura** [comment]
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new?assignees=&labels=suggestion&projects=&template=suggestion.yml&title=Suggestion+-+
