### ISSUE TITLE
[maps/?] Angels of Death Clubhouse

### ISSUE THREAD

**Issue by MillerManPlays** [InZidiuZ/legacy-assets-issue-tracker#848]
### Name

Bikernut

### Summary

In summary,, We as AoD MC have been around for a while and are using a house to hold a club house but it causes issues when we want to keep our bikes outsidee and we don't have people to keep watch so we would like a club house built where the "Boat House" currently sits - Max was attempting tto build one but he has a lot of work on at the moment - If the second one can't have the logo's changed we get tthat it can't be used.

### Link

https://www.youtube.com/watch?v=uDGF6WzML_g&t=2s

https://gtasix.store/models/mlo_clubhouse_modern_sandy_shores

### Reason

This would be a great additioin as it would allow us to build RP by having private parties and private meeting including our weekly meeting (church) without using a house this will also bring more attention to us from other gangs having a place we can call our own.

**Comment by antihero6713** [comment]
Sorry this MLO is escrowed so. We can not put this on our server.
