### ISSUE TITLE
Suggestion - Tickets for PD to give out as a item

### ISSUE THREAD

**Issue by TROWER-MF** [InZidiuZ/legacy-assets-issue-tracker#849]
### Name

beansontoast123.

### Summary

When on duty officers can give out tickets to people. It would be cool if you give them a copy of the ticket like a cop would IRL

### Reason

This would be a good addition as it would enhance the roleplay between police and civs

**Comment by coalaura** [comment]
This would just end up as another trash items people leave on the ground everywhere
