### ISSUE TITLE
Suggestion - To Add Garage Near Repair Shop 2

### ISSUE THREAD

**Issue by yeasinaman** [InZidiuZ/legacy-assets-issue-tracker#851]
### Name

.sussy.baka

### Summary

near the tlmc repair shop 2 there is no garage its really hard to store vehicles and just normally parking them makes them despawn or dissapear compleaty if they vanish then i gotta retirieve them and even the closest garage is far away

### Reason

To make life easier for the people working at repair shop 2 its really frustrating it will be very great to have a garage near the casino

**Comment by txxlrrsCoding** [comment]
Repair shop 2 is hayes, and that has a garage?

Also, casino has an underground parking unit. It's just that nobody uses it.

**Comment by txxlrrsCoding** [comment]
> Repair shop 2 is hayes, and that has a garage?
> 
> Also, casino has an underground parking unit. It's just that nobody uses it.

Unless your subdiv has lostmc garage open, but either way... Casino has a garage.

**Comment by yeasinaman** [comment]
wait which one is the tlmc garage again im missing something here

**Comment by yeasinaman** [comment]
the casino doesnt have a garage and its far away to be of use and the mirrorpark garage is also far away

**Comment by yeasinaman** [comment]
> > Repair shop 2 is hayes, and that has a garage?
> > Also, casino has an underground parking unit. It's just that nobody uses it.
> 
> Unless your subdiv has lostmc garage open, but either way... Casino has a garage.

where?? can you show me any sort of images of reference?

**Comment by txxlrrsCoding** [comment]
> > > Repair shop 2 is hayes, and that has a garage?
> > > Also, casino has an underground parking unit. It's just that nobody uses it.
> > 
> > 
> > Unless your subdiv has lostmc garage open, but either way... Casino has a garage.
> 
> where?? can you show me any sort of images of reference?

I can't show you where because metagaming ✨. It's not a marked one on your GPS, but it's definitely a garage that works perfectly fine.

**Comment by yeasinaman** [comment]
wait so like this casino garage is it like private or public like the normal garages we can store vehicles without the possibility of despawning but here if i say park a car there will like a anather player see my car in the garage when he enters it , its confusing really and is there any chance the cars will despawn? also its different from the other garages and thus i dont see any arrow thats why im asking

**Comment by yeasinaman** [comment]
That garage / parking area is very messy and buggy it teleports me outside of the casino area on top of some cliff same to my friends when i try with them 
it would be a great idea to like have that area like an actual garage with the red arrow to store retrieve and spawn vehicles

**Comment by CloudTheWolf** [comment]
I would say that the garage at mirror park is within an acceptable distance to go to/from, and is a fairly similar distance from Paleto Mech to the Paleto parking area. You've just got to RP going to the garage instead of expecting everything to be at hand.

**Comment by coalaura** [comment]
not needed also wrong github

**Comment by yeasinaman** [comment]
atleast tell me how the parking lot at the casino works even though its bugged
