### ISSUE TITLE
Suggestion - North Calafia Way eyesore

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/legacy-assets-issue-tracker#852]
### Name

scufflord

### Summary

Can we get rid of the big ass barge looking thing? Pretty pointless being there, and I know in GTA Online it isn't there cause boats normally spawn here.

### Link

https://i.imgur.com/6XlvhPB.jpeg

### Reason

eyesore, and i so can ask on the framework github for a boat dock spawner to be added there 💀

**Comment by scufflord** [comment]
as you can see, local boats still spawn here as well, and will bug out and fly all over the place as well 
https://i.imgur.com/IZShuVn.jpeg

**Comment by MetaHatter** [comment]
Done

![2024-02-18-17_06_01](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/84351858/ab62a1e3-444c-4a2e-8849-9a69c11c48eb)

Kidding... I actually moved it here: 
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/84351858/c5e1f51d-e793-4a89-98b0-7fcbec16b886)

**Comment by scufflord** [comment]
At least it wouldn't have covered up my house! lol thank you so much Meta!
