### ISSUE TITLE
[vehicles/gta] Suggestion - Obey Omnis E-GT handling

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/legacy-assets-issue-tracker#855]
### Name

scufflord

### Summary

Car handling could use a re-work overall. It has a tendency to fishtail easily, goes up on two wheels around turns sometimes, and for some reason on gear shifts it loses a few miles per hour off the speed cause the shifts take so long.

### Reason

quality of life. it's an expensive car that doesn't drive like an expensive car

**Comment by northbayjoe** [comment]
handling has been updated, let me know how it feels
