### ISSUE TITLE
Suggestion - Add shredder and Printer in Mount Zonah Hospital

### ISSUE THREAD

**Issue by Lucifer630** [InZidiuZ/legacy-assets-issue-tracker#858]
### Name

khonshu1606

### Summary

To Add shredder and Printer in Staff room at Mount Zonah Hospital to Increase EMS RP.

### Reason

It would be Great if you Add shredder and Printer in staff room as if gonna improve the EMS RP while discharging we give them Discharge papers and Prescription.
1) shredder :- when the patient comes next time with prescription we take the prescription and give him the meds and after that we can use shredder to destroy the prescription instead of throwing it here and there and other use of shredder to destroy old EMS id cards.
2) It would be easy to print docs like discharge papers and prescription and give it right away while discharging cause every EMS member dont carry the printer with them.

**Comment by coalaura** [comment]
not needed, you can purchase a printer
