### ISSUE TITLE
Suggestion - Add hair changing spot to MT zonah 

### ISSUE THREAD

**Issue by Dinomasen** [InZidiuZ/legacy-assets-issue-tracker#859]
### Name

Dinomasen

### Summary

The reason this should be added is for quality of life. It is a hassle to drive all the way to a hair salon when putting on a new uniform and your hair clips into it. I feel it would be better if we had a place to change hair in the break room bathrooms or somewhere else nearby.

### Link

![20240301191050_1](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/144753175/fb9ea94d-eca1-4e7c-b8d3-941ab2275cae)
![20240301191102_1](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/144753175/c7a7610d-e19b-4ba2-9214-ecab99345166)

### Reason

It improves the quality of life to have a hair changing area at Mount Zonah for EMS when making new outfits.

**Comment by coalaura** [comment]
Yes, this is a script change tho so it should go [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues). You don't have to redo it, i've done it already just next time
