### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by watpsp1** [InZidiuZ/legacy-assets-issue-tracker#860]
### Name

Teddy Does/ Teddydoesnt

### Summary

We as the daybreakers have found a underground hidden garage with a sea horse on it we made a ticket seeing if we could claim it got told to make a map change request here 
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/77626173/f766d595-f8eb-4643-9f22-207d48875e11)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/77626173/cf1f5813-f618-48af-857a-8f46524a1f59)

### Reason

we would love to claim this as a little hang out spot for our guys

**Comment by MetaHatter** [comment]
That MLO is not there for general use.
