### ISSUE TITLE
 map Suggestion - i would like to buy the bunker 

### ISSUE THREAD

**Issue by chargerkon** [InZidiuZ/legacy-assets-issue-tracker#861]
### Name

tub56

### Summary

found this bunker near quarry . Don't think its in use would like to open it up and make use of it. 

### Reason

could add some good lore to the city. i feel like its going to waste the way it sits now would love to host secret events or other activities.

**Comment by MetaHatter** [comment]
As stated in the other ticket opened today, this MLO is not for civilian/general use.
