### ISSUE TITLE
[maps/?] Suggestion - Hen House (Paleto bar) Black jack or poker table (Poker preferred if possible?)

### ISSUE THREAD

**Issue by Breezy368** [InZidiuZ/legacy-assets-issue-tracker#862]
### Name

cryptic1776

### Summary

I am interested in the possibility of adding a gambling table to the hen house. Its hard getting people out of the city, and this added attraction would do wonders on top of the fighting ring! I would personally place it in the corner that is hard to use and sit at.

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/5093406/dfa355df-60f2-4e1f-b701-7be6f6d30e09)

Is this possible? Would this interest and benefit the community? I know it would be a nice attraction to paleto in legacy, but I dont know the back end stuff to make this happen. Thank you for your time.

### Reason

More paleto attractions

**Comment by coalaura** [comment]
Adding the table as a prop is easy. However you wont be getting actual functionality with it

**Comment by Breezy368** [comment]
Oof, was hoping functionality, but Ill leave it to yalls discretion then.
