### ISSUE TITLE
Suggestion - Inventory storage in Paleto's Hen House

### ISSUE THREAD

**Issue by Breezy368** [InZidiuZ/legacy-assets-issue-tracker#863]
### Name

cryptic1776

### Summary

Other bars have storage and its difficult not having it trying to sell extra fun things that are going around in the city like bbq sandwiches.

### Reason

This allows for much easier use of extra ways to make money in the bar, instead of the cheap and RP food players would actually get filling meals or other products that can be sold there!

**Comment by coalaura** [comment]
Do you mean a locker?

**Comment by coalaura** [comment]
Also this is the asset github. The asset github is for map edits, clothing, vehicles and props. The [script github](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) is for any script related stuff like this for example

**Comment by Breezy368** [comment]
Sorry I still dont quite understand the difference. But Ill make one there.

**Comment by coalaura** [comment]
> Sorry I still dont quite understand the difference. But Ill make one there.

This github is used by all asset developers. They do anything that involves changing assets. An asset be a car, an MLO, a piece of clothing, a weapon, etc. Assets don't have any special functionality by themselves.

The other github is used by all script developers. They do anything that involves script changes like adding a new feature, etc. or in this case adding a storage somewhere.

Only reason we have these 2 githubs is to organize tasks a bit better

**Comment by Breezy368** [comment]
Ty for explaining it, I appreciate the effort you put into this. I definitely chose the right crew to support!
