### ISSUE TITLE
[maps/mission_row_pd] Suggestion - Sound Proof MRPD Range

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/legacy-assets-issue-tracker#867]
### Name

HollaYalla

### Summary

It would be quite nice if you could sound proof the MRPD Range so people dont get nosey when we are practicing

### Link

N/A

### Reason

QoL

**Comment by coalaura** [comment]
not sure if its even possible to mute gunshots

**Comment by scufflord** [comment]
also if possible, adding the shooting range script from ammunation to MRPD's shooting range would be nice. gives unlimited ammo for target practice I'm pretty sure

**Comment by coalaura** [comment]
@scufflord that'd be script github

**Comment by scufflord** [comment]
> @scufflord that'd be script github

imma keep it a buck, i didnt even look to see which hub this was lmfao my fault OG

**Comment by antihero6713** [comment]
its on my list to sound proof closing
