### ISSUE TITLE
[maps/?] Suggestion - Transparent windows at Luxury Autos

### ISSUE THREAD

**Issue by laalaalaee** [InZidiuZ/legacy-assets-issue-tracker#869]
### Name

laalaalaee

### Summary

![curtains_removal1](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107997024/ab0e709e-85a8-41f8-b44c-8901de9eb719)
especially this one, It will give good exposure to our cars, as anyone passing from that side have no view and I want curtains to be removed and glasses as transparent like this below mentioned, old snap of Luxury Autos
![OLD_LA](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107997024/3c3fc9a2-98c4-4b56-bb4e-61a66b297cbf)

![curtains_removal2](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107997024/c58fe656-cb2c-4da0-9a19-9d7fe389174e)
So do these curtains, 

### Reason

It will give good exposure to our cars, as anyone passing from front left and side have no view and removing the curtains will do the work and glasses as transparent like it was before, old snap of Luxury Autos mentioned above.
We're running this business perfectly, if these changes are made it will eventually boost our work and excites us and the citizens of los santos.

**Comment by antihero6713** [comment]
The reason we did this was because it caused headache with the amount of cars that were in the shop would headache people driving by the area. Especially in the intersection area.

**Comment by antihero6713** [comment]
Might re take a look at this but gonna close it for now
