### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 1THC** [InZidiuZ/legacy-assets-issue-tracker#87]
**Name:**
Who is suggesting this? Please include discord name.
1THC#4847

**Summary:**
Write a short summary of what your suggestion is about.
Add a bong emote and maybe a government ran weed dispensary in the future with the new growing feature coming out. I've found the correct animations for the bong emote from story mode provided below.

**Link:**
If there are any links to what you're suggesting, please add them here.

anim@safehouse@bong bong_stage1_lighter
anim@safehouse@bong bong_stage1
anim@safehouse@bong bong_stage2
anim@safehouse@bong bong_stage3
anim@safehouse@bong bong_stage4

attachentitytoentity to put the bong in the hand

**Reason:**
Why would your suggestion be a good addition to Legacy?

A place where you can buy weed legally instead of growing it yourself or buying it off the streets from other people would be sick. The bong emote could be used with a bong item which would be sold at this store.

**Comment by InZidiuZ** [comment]
Wrong issue tracker. This is for assets strictly.
