### ISSUE TITLE
[maps/?] Pacific Bluffs Business Event Collab Area

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/legacy-assets-issue-tracker#870]
### Name

beezy710

### Summary

Inquiring on making the Pacific Bluffs to be able to be retro-fit to accommodate multiple businesses. I had the general idea of trying to covert the area to be more enticing to plan events at by changing it so the businesses can actually thrive there while throwing events for the entire community to enjoy. I don't know how difficult it would be to make it so the inventory that the businesses access to buy their food similar to every other citizen does at the gas stations. That way when an event is thrown at the Pacific Bluffs they have a work space that already works for their business. There would need very little to any modifications needed apart from whatever is needed for them to have an inventory to purchase their food the same as lockers are added.  As it stands now there is a private strip club which could be used for vanilla unicorn workers (dont believe they have food or anything but there is a stand that could possible be added), there is a fighting ring for fight night events, there is a kitchen big enough to accommodate Burger Shot, the Kassaki Sushi, or Casa Blanca. (they might not have room or the script to do their entire job but possibly a way to purchase their items directly). There is also a casino which could easily be adjusted to an area for arcade to thrive and attend events. There is a private movie theatre that doesn't have a screen and would need one to fit and Doppler Cinema could be included. There is an announcement area with an open mic which could include Split-Sides Comedy.  There is a counter near that room perfect setup for tequi-la-la. An open pool downstairs with a cabana at which Bahama Mama's would be perfectly ideal for. As well as an office space to assist with my private company Sleezy Investments. Lastly and would actually require work, there is an open bay garage with 2 spots big enough for mechanics to work during events, if retro-fit it would help draw people to events while they are out doing their normal routine thus pulling more of the community together as a whole.

### Link

Below i will include links to all the locations mentioned above incase you are unfamiliar with all the areas i'm speaking about at Pacific Bluffs

arcade area potential
https://cdn.discordapp.com/attachments/1193088660141252648/1222807467675877407/image.png?ex=66178f32&is=66051a32&hm=94f8e110c96d86b377ffcc27250107dd69064584e7bd13538603b8a6bbcb964d&

vanilla unicorn private area
https://cdn.discordapp.com/attachments/1193088660141252648/1222807627273343056/image.png?ex=66178f59&is=66051a59&hm=0522e4abec0f80d5b18054738288651306600d7175104c7b5924e1782be81ba3&

burger shot, kissaki sushi, or casa blanca kitchen
https://cdn.discordapp.com/attachments/1193088660141252648/1222807913492385812/image.png?ex=66178f9d&is=66051a9d&hm=ccf1280d41d79700de7f167b86f7805f675df9c7cf676f8da7ad2c7a011c9b43&

doppler cinema potential
https://cdn.discordapp.com/attachments/1193088660141252648/1222808048775598141/image.png?ex=66178fbd&is=66051abd&hm=ecc84e374652a2163d8caf29ddf1160b2bd2e2b1e80692d23cc8744d3eee9e3e&

fight night area
https://cdn.discordapp.com/attachments/1193088660141252648/1222808398060453949/image.png?ex=66179010&is=66051b10&hm=e4a5285af7e276dbf6cd357df04835363fd05de633910ad10f27f17e7c0ff791&

mechanic shops potential (big enough for 2 shops to work during 1 event)
https://cdn.discordapp.com/attachments/1193088660141252648/1222809304839491615/image.png?ex=661790e8&is=66051be8&hm=ed7442f287a3e06eed1c29ec74549533fc65799fd4020082658201bf23d7b258&

bean machine/tequi-la-la potential
https://cdn.discordapp.com/attachments/1193088660141252648/1222809827827515503/image.png?ex=66179165&is=66051c65&hm=4f748cd46be6ca343b09155c23060f1da4efa7a9293d53d890ff7228c33ca3ca&

split-sides comedy , announcement area
https://cdn.discordapp.com/attachments/1193088660141252648/1222809982467182654/image.png?ex=6617918a&is=66051c8a&hm=6df2ac49b9aecd6ca88365d255dfa0ca4bb5044c0a5a5cfe8bb474c5a0240bc2&

pool side area where bahama mama potential cabana is located
https://cdn.discordapp.com/attachments/1193088660141252648/1222811044376739850/image.png?ex=66179287&is=66051d87&hm=8a6cfb7ac2fa1d08658b47c89809f47e84bc7dde23891342f040292a76f1bcd7&

bahama mama's potential cabana
https://cdn.discordapp.com/attachments/1193088660141252648/1222814749314515004/image.png?ex=661795fb&is=660520fb&hm=ed898b0b9ff920f628b0b08890498aa94737b44896412096ff228ca6c226609f&

sleezy investments potential office
https://cdn.discordapp.com/attachments/1193088660141252648/1222811951847968810/image.png?ex=66179360&is=66051e60&hm=22a1ed7d1939d60551e4d59d85d5baeae66b2ca54405c50adde1c11ba39e3c9c&

### Reason

I know this sounds like alot but companies working together should be the top priority in our city, if we want to promote businesses to be open and to throw events, why not give them an area big enough to work together and draw the community together in the process. I know we like to spend our free time adding private things that split our community apart and let people do things on their own, so how about we do one where we bring the community together as a whole. Pacific Bluffs remains an open public area able to be used for multiple venues while enabling all businesses to work their as their normal jobs would while building a stronger community together as a whole.

Would love other companies feedback on this idea as I haven't heard a single company apposed to the idea yet, its really in the hands of the engineers here and what they want to do or allow us to do.

**Comment by antihero6713** [comment]
closing not gonna put all these in one location
