### ISSUE TITLE
Suggestion - ZYN/Chew 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/legacy-assets-issue-tracker#872]
### Name

jr.bacon1

### Summary

I think something like ZYN or chew being sold in gas station/convenient stores for stress relief would be a great way to relive stress. They should relieve about the same amount of stress as a typical cigarettes. 

### Reason

These would be a great way to relive stress instead of something like cigarettes or vapes

**Comment by HollaYalla** [comment]
This would be awesome and if possible maybe make it like you need to do like /spit to spit out the Zyn or Chew before you can use more to stop it from being OP and make it an overtime thing aswell

**Comment by coalaura** [comment]
This github issue tracker is for issues relating assets such as vehicles, maps, clothing, etc. Script suggestions would be [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
