### ISSUE TITLE
Suggestion - DOC panic button 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/legacy-assets-issue-tracker#873]
### Name

gadjinee

### Summary

So the idea is to have something like a panic button but for riots, obviously there’s a panic button for when the officer goes down but having some sort of command that would lock all the doors of the prison , sound the alarm if possible and maybe send Dispatch notification that “Riot Alert” 

### Reason

I think this will be a massive help for all the DOC officers, specially now that weapons a can be found at the prison, this will help to notify the Police and EMS quickly as well as locks all the doors at prison isolating the inmates.

there’s similar systems in place irl prisons, basically kill switch for all the doors

**Comment by CloudGamer1** [comment]
I think it would be great if it's triggered by a command, maybey like /riot or /lockdown so DOC dosen't have to go down to trigger it

**Comment by coalaura** [comment]
[script github](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
