### ISSUE TITLE
[maps/?] Suggestion - Revert to old galaxy night club interior

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/legacy-assets-issue-tracker#875]
### Name

kay.32

### Summary

Revert to the old elevator entrance to the underground bar Galaxy. About 2 years ago, the interior MLO of galaxy was changed to remove the elevator entrance and make it a walk thru. Since then, the bars been broken and if you try to enter the bar (Vinewood parking garage and the building across the street from he 24/7 just walk into the closest place a door would be) you fall thru the map. 

### Link

N/A

### Reason

I think it would be another fun place to host night outs and bringing back a business would bring excitment back to the city.

**Comment by MetaHatter** [comment]
This map used to cause crashes.  I did a MASSIVE cleanup of the files that will hopefully improve stability.  Enabling it again but it may have to be disabled if the cleanup doesn't fix the crashing.
