### ISSUE TITLE
[maps/?] Bug report - Videogeddon Assets Missing (Dark)

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/legacy-assets-issue-tracker#876]
### Reporter

navonody

### Summary

A little over a week ago, multiple people noticed the Videogeddon Arcade was completely dark and had some assets missing. This doesn't appear to be on the individual level, since we all seem to see the same thing. 

If a new MLO is required due to this one being corrupted for whatever reason, I can make a few suggestions.

### Screenshots/Videos

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/f16d135a-ac84-4239-ae49-215117f931e6)

No stairs to get out once you're inside:
![no stairs](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/96219411/cf476bf8-9120-4e09-8d54-28a86236d81c)

### Note

Troubleshooting steps:

- Cleared cache
- Reinstalled FiveM
- Preloaded Assets
- Reloading FiveM
- Soft nap/Fly out and in again

**Comment by coalaura** [comment]
fairly certain this is cause of the new GTA build we are on

**Comment by navonody1** [comment]
> fairly certain this is cause of the new GTA build we are on

Is this something we have to attempt to fix on an individual level? Or is the solution a work in progress at the moment?

**Comment by coalaura** [comment]
atm we have no clue how to fix it

**Comment by MetaHatter** [comment]
We have made MASSIVE changes to the arcade on the back end and this appears to be less of an issue.  Is it still happening?

**Comment by MetaHatter** [comment]
I am closing this issue for now due to a lack of response or reports of it continuing. Reopen if necessary.
