### ISSUE TITLE
Suggestion - Improvements of Document Reading

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/legacy-assets-issue-tracker#877]
### Name

rakibulhasan456

### Summary

After _using_ the document item, its size is very small to read properly (the image is an example). When there are a lot of writing of the texts are very small, creates a hard time understanding it.

![1](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/88003289/2958299d-bb38-48a0-9158-bd59800cba7d)

Therefore, I would suggest introducing a new **Read Document** option at the inventory.

![2](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/88003289/c8306495-4a80-4738-aad6-8ad217938bbd)

After dragging the document in this option, it will pop up and enlarge the size to make it easily readable. Like the example below:

![3](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/88003289/e3963dfe-c100-4dff-8e27-d24bb05af688)

### Reason

It will ease the document reading and help all the department/ person using the document for their everyday work.

**Comment by coalaura** [comment]
[wrong github](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)

**Comment by coalaura** [comment]
I've made it bigger

![yes](https://i.shrt.day/QWWXFCBTG0.webp)
