### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by iDaxr** [InZidiuZ/legacy-assets-issue-tracker#879]
### Name

daxr.

### Summary

So the shoes I am suggesting to be added for the males has more colors with the clothes that match. The current Air Jordan 1s have a lighter and sometimes darker color than the clothing, the females however match almost perfectly with most of the clothing styles. Would really appreciate it if it was added for the males. The picture below is the style of Jordans that the females have that I would like it to be added to the males

### Link

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/143039199/89db20ce-c118-4b84-87f6-42b0195fa1bb)

### Reason

The Air Jordans for the males have less matching color schemes with the clothing styles and a lot of the pants styles dont fit it well, so even if the color of the pants match it looks weird bc of the overlap and odd fitting it has

**Comment by DaxterPancake** [comment]
Sure, this has been done and will be live when we do a build soonTM
