### ISSUE TITLE
Cop Cars getting dirty Bug report

### ISSUE THREAD

**Issue by PanchoGarcia** [InZidiuZ/legacy-assets-issue-tracker#88]
**Reporter:**
Pancho#0001

**Summary:**
Dirt on PD cars models looks bad and goofy on some cars
## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/523275352131239937/635290668163399700/unknown.png

**Notes:**
this is a minor example some of the vehicles look much worse

**Comment by HridayHS** [comment]
wut mate

**Comment by Karpenkooo** [comment]
_Hey_

There's not much i can do here as it's up to the mod author to fix that issue.

_Karpenko_

_**OP-FW Asset Dev**_
