### ISSUE TITLE
Suggestion - Addition of Firearms at State Store

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/legacy-assets-issue-tracker#880]
### Name

rakibulhasan456

### Summary

Currently, the State Store has only a Taser, Glock 19X, and FN-509 pistol. But, we often need to rely on Class 2 & 3 during session/area visit.

So, including new firearms at the store will be a fantastic addition for the State Security (SASS).

I suggest adding the SMG and AR that's available at the PD store to the state store. The models should be **SIG MCX, H&K 416, LWRC M6IC**.

Also, I suggest adding **SMG and AR ammo** besides the gun at the store.

### Reason

Adding Class 2 & 3 firearms will give better protection to the State employee. As the ammo and firearms has **Gov** tags in it, there shouldn't be any misuse with this addition. It will be useful for the SASS and ensure better safety.

**Comment by coalaura** [comment]
State security should not have class 2-3's. They are not PD

**Comment by coalaura** [comment]
also wrong github, script suggestions would be [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
