### ISSUE TITLE
Bug report - Hospital elevator to Surgery takes you in the middle of the road.

### ISSUE THREAD

**Issue by uolla** [InZidiuZ/legacy-assets-issue-tracker#881]
### Reporter

GambloTwitch

### Summary

When you use the elevator for the Hospital 1 trying to go to Surgery, you get tp'd in the middle of the road.

### Screenshots/Videos

https://i.imgur.com/BPQcfKw.mp4

**Comment by coalaura** [comment]
This would be a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
