### ISSUE TITLE
[vehicles/?] BCFD Trucks scuffed

### ISSUE THREAD

**Issue by Astrozombiecat** [InZidiuZ/legacy-assets-issue-tracker#883]
### Reporter

Astrozombiecat

### Summary

While trying to pull out a Firetruck from the Sandy BCFD location, the vehicle jacks up the front and does not move, It's like there is a brake on or something that is not. the wheels won't even move.   This is happening with Wild 1(Bush Truck) , Engine 1 (Small host Truck) , and Ladder 1 (Large Ladder Truck.   Ladder 1 spawned in from the garage at Sandy medical missing everything, No latter, or proper livery. Medical

### Screenshots/Videos

https://clips.twitch.tv/LightCrepuscularCrabsHassaanChop-3pQP2-xEwJDsdd3D

https://clips.twitch.tv/CorrectFlirtyVampirePRChase-nYm5MeVIoqo0uUBX

### Note

The clips are from my live stream taken from both locations  BCFD  Sandy and Sandy medical garages.

**Comment by coalaura** [comment]
this would be a script issue not a vehicle issue [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
