### ISSUE TITLE
Suggestion - Vehicle Plate Reader / Speed Radar Being usable from passenger seat of PD vehicle

### ISSUE THREAD

**Issue by Manannn924** [InZidiuZ/legacy-assets-issue-tracker#884]
### Name

manannn

### Summary

The Speed Radar or Plate Reader should be also accessible from, the passenger seat of the PD vehicle . Because in some scenarios it is necessary for the driver to focus on driving and the passenger can run plates or check the speeds of the vehicles. As per the vehicle interior the Radar is accessible to both Driver and passenger so it makes sense.

### Reason

A "/radar" or any other command should be added for the passenger in the PD vehicle to toggle the radar , In some cases of switches vehicles during a chase it is helpful as passenger to setup BOLO plate , Lock vehicle plates or Run plates of the vehicles.

**Comment by coalaura** [comment]
This is a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) not an asset issue
