### ISSUE TITLE
[maps/?] Suggestion - Adding a midsummer pole for Midsummer event

### ISSUE THREAD

**Issue by fnxye** [InZidiuZ/legacy-assets-issue-tracker#886]
### Name

Johan fnxye#3740

### Summary

We would like to ask if a Midsummer pole could be added to the City for an event to host every Midsummer. As I'm not a modeler I frankly dont have any idea or clues about it, but we were curious if one could be made and added into the city for us to celebrate.

Adding a picture for reference: 
![midsommar](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/161089455/06d12e9f-8277-45bd-bd8f-658848e7c8d6)

I cannot speak for the difficulty of creating or if something like this can be found and just added as I am way too dumb for that and I have no clue about modelling. Just curious if this is a possible thing cause it would really make the event come alive!

### Reason

We were planning events for the future and came up with a few ideas and Midsummer got brought up as a way for the city to come together and celebrate the midsummer. The actual celebration around the pole would of course be the "main" thing and we're hoping that it will bring in a lot of people even if this may mostly be a Scandinavian thing. And its something that will run for a few days (maybe a week) and then be reused again next year.

**Comment by fnxye** [comment]
https://www.tartspecialisten.se/wp-content/uploads/sites/43/2021/04/midsommarstang-1024x683.jpg
https://img.fotocommunity.com/midsommarstng-325571b6-3143-40a8-b886-9c861699b384.jpg?width=1000
https://i.pinimg.com/originals/95/ad/5e/95ad5e95bedb86d9c834089e496812ec.jpg
https://gunillablixt.se/wp-content/uploads/2013/06/midsommarst%C3%A5ng-gotland.jpg

Adding a few more reference pictures cause for some reason I chose one that covers like half a screen

**Comment by Dibbey** [comment]
Adding onto this, if this is even possible, we've got some Locations in mind where we would like to host said event. The date for it would be on the 24th of June. Though we understand if its not possible and will somehow do it anyways, but it would be a fun cool thing.

The Soccer field near the Lost Compound would be aa cool spot as it is big enough for people to dance and to place some tables around for business for catering and such.
![FiveM_b3095_GTAProcess Neneko_Muffin  Gameplay  2024-06-03 23-19-48](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107942951/cf42b174-0b89-4feb-ba81-050bb1e694e8)

This dog-park up in the VInewood Hills would also be a preferable spot as yet again it is big enough for people to dance and gather, as well as tables for businesses.
![FiveM_b3095_GTAProcess Neneko_Muffin  Gameplay  2024-06-03 23-24-53](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107942951/8c58a3a6-6edd-41ef-9475-d8ed0d189910)

The High-School/University sports field would be our least liked alternative but can also work here as it is also big enough.
![FiveM_b3095_GTAProcess Neneko_Muffin  Gameplay  2024-06-03 23-27-10](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107942951/045c634d-1932-43a7-8440-53cb00aaa958)

For any questions, please feel free to reach out and I'd be happy if we could get this to work. If not thats also fine ♥

**Comment by Dibbey** [comment]
This was just shown to me by Ruby, this could also be a really cool location to host said Event, as we could host the music and such from the Stage, and with the hay as seats and such. 
![imageee](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107942951/9d94dc69-04d2-4415-acb2-5f76ab1b510f)

**Comment by HollaYalla** [comment]
This seems easy enough

**Comment by coalaura** [comment]
Do you have a 3d model we should use? If not it'd be up to the asset devs if they are willing to make a custom one (which may take longer)

**Comment by fnxye** [comment]
> Do you have a 3d model we should use? If not it'd be up to the asset devs if they are willing to make a custom one (which may take longer)

We scouted for a little and came up with these two:
https://sketchfab.com/3d-models/midsummer-pole-f5772b86f5414b1181578f404e192668
https://www.thingiverse.com/thing:3544333/

I'd prefer the first option if it's not SMOL but maybe that can be changed?

**Comment by HollaYalla** [comment]
I have seen this but a thing that might not be good is that it has 6k Triangles which can cause a lot of lag

**Comment by coalaura** [comment]
6k should be fine considering its size

**Comment by coalaura** [comment]
> > Do you have a 3d model we should use? If not it'd be up to the asset devs if they are willing to make a custom one (which may take longer)
> 
> We scouted for a little and came up with these two: https://sketchfab.com/3d-models/midsummer-pole-f5772b86f5414b1181578f404e192668 https://www.thingiverse.com/thing:3544333/ https://sketchfab.com/3d-models/midsommarstang-ae84fc837fae4e99af7869cc8dc80373
> 
> I'd prefer the first option if it's not SMOL but maybe that can be changed?

With sketchfab you have to make sure you search for downloadable models (the 2 links you posted are both not downloadable) and thingiverse is usually for 3d printing therefore has no textures

**Comment by antihero6713** [comment]
is this still wanted?
