### ISSUE TITLE
[vehicles/?] Bug Report - 2015 Stellor Orion GT12 changing colours

### ISSUE THREAD

**Issue by laalaalaee** [InZidiuZ/legacy-assets-issue-tracker#887]
### Name

laalaalaee

### Summary

this car 2015 Stellor Orion GT12, is changing colours automatically and with different angles. previously the front windshield was used to work with pitch black now its just transparent
- Actual Colour is Black
- it changes to brown with dust maybe
- it changes to some differnet colour again
![FiveM_b3095_GTAProcess_CbvoIma5iH](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107997024/8511c179-ddb9-4b84-971e-e53609bcf66e)
![FiveM_b3095_GTAProcess_FgLJF3XhjG](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107997024/8588e3c3-3971-4357-96e2-648896e47f52)
![FiveM_b3095_GTAProcess_UPLYPE8YLf](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/107997024/edce920e-097a-46f5-951e-0676bc011dad)

### Reason

cuz it will fix the issue, and headache.

**Comment by northbayjoe** [comment]
this has been fixed and should already be live.
