### ISSUE TITLE
Suggestion - The lucky vault mirror park

### ISSUE THREAD

**Issue by Beetkrunkles** [InZidiuZ/legacy-assets-issue-tracker#888]
### Name

Demolitiondevo

### Summary

i have just recently acquired a business The lucky vault in the mirror park area it is an underground gambling room i would like to request that it has a locking door to the building so not just anyone may enter my business, 
![Screenshot 2024-06-06 212029](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/172076019/74a0efe4-6fdf-4e41-9e4c-922916d5103f)
![Screenshot 2024-06-06 212048](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/172076019/7b4823f3-aeb0-4c5d-8150-ef292c3f27d9)

### Reason

this is a new up and coming business in the city and it will help me promote good rp and fun interactions by having my business safe with locked doors

**Comment by SluggsV2** [comment]
i will say, this may affect more cities then not, but i could be wrong i know some cities use this as an "underground gambling ring", making this an actual business and Map icon may cause backlash!

**Comment by Beetkrunkles** [comment]
how so? there are 3 or more spots just like it around the map and if they use the info from this city to ruin others thats meta

**Comment by MetaHatter** [comment]
I agree that it does not need an icon. It's an "underground" gambling room in a residential area. It is not really there to be a legitimate business.

**Comment by HollaYalla** [comment]
Lockable doors makes a bit of sense as it could be said a Gang has taken it over and installed locks on it for RP but yea the Marker shouldnt be added

**Comment by coalaura** [comment]
As discussed above, this is mainly intended as an **underground** bar/hangout spot, so no to the locks and icon. However, to make it more usable without compromising its intended use, I've added counter spots, a bar store (accessible via the "Bar and Clubs") job and i also put an outfit spot in the back office.

**Comment by coalaura** [comment]
Also for next time, this would be a script issue not an asset issue (https://github.com/InZidiuZ/op-framework-issue-tracker/issues). Asset means vehicle models, addon clothing, mapping work, etc. while script means everything feature wise (in this case door locks and/or a blip)
