### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Lilgrizz818** [InZidiuZ/legacy-assets-issue-tracker#89]
**Reporter:**
Who is reporting this? Please include discord name.
LilGrizz818#1818
**Summary:**
Write a summary of what you're experiencing.
Ive paid for my Blocks that i own and its showing me last payment was today and my next payment is today i dont think the payment is registering 
## Additional Information
Also the paying the blocks on the /comp is also broken cause its a invisible button that we have to click to pay the block. I also suggest maybe fixing it to where it gives us a yes or no before paying so its not a one click. 
**Screenshots:**
If suitable, include some screenshots.
https://cdn.discordapp.com/attachments/574379082868064297/635633844476837909/20191020171433_1.jpg
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Wrong issue tracker. This is for assets strictly.
