### ISSUE TITLE
Bug report - While Frisking it considers BR Weapon aswell

### ISSUE THREAD

**Issue by Manannn924** [InZidiuZ/legacy-assets-issue-tracker#890]
### Reporter

manann

### Summary

When we frisk someone , if they're carrying a BR weapon weapon . It show's up as possible large weapon. If the BR weapons are only useable in arena so it doesn't make sense to be considered while frisking.

**Comment by Alyshiva** [comment]
I mean if you think about realism, it makes sense that any gun shaped item would make cops suspicious and they would investigate further, to THEN find out it’s a paintball gun (since br guns can be used in paintball now).

**Comment by Manannn924** [comment]
I mean if it’s a gun shaped thing/prop then it should be visible on the back aswell to be considered , How can you consider a BR Carbine Rifle as a gun shaped thing which can be carried without even getting spotted?

**Comment by coalaura** [comment]
this is not an asset issue https://github.com/InZidiuZ/op-framework-issue-tracker/issues
