### ISSUE TITLE
[maps/?] Suggestion- Lucky Plucker

### ISSUE THREAD

**Issue by LuckyXIV** [InZidiuZ/legacy-assets-issue-tracker#891]
### Name

Lucky Sanchez Osas (999lucky)

### Summary

My suggestion is about opening the Lucky Plucker down at Davis. We have already scoped out a blueprint for it, which doesn't change much on the building itself, it just renovates it to open the doors and look cleaner with new chairs/tables/counters etc. 
In addition to that, I would LOVE to import some Chicken for the people of Los Santos. A Chicken Bucket, Dino Nuggies, Chicken Fingers, Spicy Chicken Wings, etc. is what I would want to present and serve to everyone.

### Link

https://www.youtube.com/watch?v=JB09JMuTx2Y  **(Blueprint)**
[Chicken.txt](https://github.com/user-attachments/files/15795794/Chicken.txt) **(Petition with Signatures from LS Citizens)**
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/93774604/2460a4ef-0823-46bc-9df3-dc900cae136b) **(Twitter Post in Top Liked)**
![Screenshot 2024-06-12 020729](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/93774604/3b556262-5c82-41be-b62c-d71f6c02878a)

### Reason

With how the food situation in the city seems to be like recently, I believe that a new place serving some fresh chicken to the people would be amazing. Burger Shot is rarely open for longer than 5 minutes and alot of people are almost starving, buying dry tacos from the grocery stores or even growing their own food. It seems like people have to yell on X just for the other restaurants to open so they don't starve and I don't believe that is how a business should be run and i want to prove to everyone, including the city, that I and the team that I am going to build can be reliable and open. I've gone around the city to ask over a hundred people the past 3 days and collected signatures of those who were VERY excited to hear about the idea of some chicken in Los Santos! (I added the document in the field above) 
Everyone seemed very excited to be able to stop in the, so far mostly food dry, south side in Davis and get some fresh and juicy Chicken served to them for cheaper than the usual amount. 
Me and over a hundred people would be happy to spend money and time in the Restaurant and do whatever is needed to keep the business open and running! I would love to work together with the City for this business to happen and keep the city fed and satisfied! 
In addition to all of the above, i have already heard from other businesses, that they would like to work together in the future, if everything works out.

**Comment by HollaYalla** [comment]
From taking a quick glance it appears that this is Escrowed so we won’t use it even if it’s bought but I’ll look into it and either make one or find one that we can use

**Comment by HollaYalla** [comment]
That is if it’s approved to be added as that area has a lot of lag due to the high population

**Comment by LuckyXIV** [comment]
Yeah, while i would really love the one in the south side, i do know that its very laggy, so in case that is the reason it doesnt work there is also one down in little seoul

**Comment by LuckyXIV** [comment]
https://forum.cfx.re/t/free-mlo-lucky-plucker/5151950
Found this one too, im not sure if its also Escrowed though

**Comment by navonody1** [comment]
Definitely makes sense...we have a whole chicken factory in Paleto, but no chicken related products anywhere in the city. Good luck finding an MLO that isn't escrowed though, since that's gonna be the biggest hurdle of getting this good idea in.

**Comment by coalaura** [comment]
> https://forum.cfx.re/t/free-mlo-lucky-plucker/5151950 Found this one too, im not sure if its also Escrowed though

Escrow you can usually see if its paid and you go through tebex during the checkout, if its free to download like that it shouldn't be

**Comment by HollaYalla** [comment]
I found a free version Laura and it works pretty well there’s just a few adjustments that need to be made that are quite simple

**Comment by northbayjoe** [comment]
So my thing with this is, once the pizza place is active we're gonna have 4 active food places, and I honestly don't think we really would need anymore than that with the current server capacity. That and adding an MLO into that area which is already plauged by low fps wouldn't be a good idea to do. The South Side near mosleys is already hard enough to drive through without adding a 2nd mlo into that same general area. Combined that with people and cars there more than the clothing store already has would make it even worse as well. I appreciate the effort that went into this but that's my thoughts on it.

**Comment by scufflord** [comment]
on top of that we still have a restaurant over in vespucci that isnt functional yet and on the list to be added as functioning. So that would put us at 5 restaurants total.

**Comment by LuckyXIV** [comment]
As of right now i dont really see any functioning food businesses though. I know burger shot and bean machine are a thing but they are maybe open for like an hour in total every week. The location down south is optional since there is also one in little seoul, the exact coordinates are in the second link i had sent in. 
I agree with the crowded issue in the south side area, but I wouldnt even count the currently available businesses as active businesses, since they arent reliably open at all. Im aware of the pizza and sushi place that are opening but from what ive been looking at that would judt put us at 3 active food places.

**Comment by antihero6713** [comment]
I dont think adding another food place at the current state is a good idea as we have about 8ish or so places to get food.  It be nice to staff people in the MLOs we do have before adding another restaurant that people will get bored with because its very small inside and people will get stir-crazy. Id say a BIG maybe to possibly putting the MLO in if it did involve the factory up north, but the script devs are mostly busy with other things I am sure.  

Not sure how this place could offer better RP then the current locations beside the link to the chicken factory. My thoughts

**Comment by battlea** [comment]
I really think this place will be a great addition to the city. I don't see an  issue with adding another place to be able to get food.

These guys have worked hard going around and asking what people in the city think about the idea and they got a lot of positive feedback. From what I've seen from them and at the town hall meeting people are very excited about the possibility of Lucky Plucker opening. I've even seen other people offering to collaborate their business with them when they do open.

These guys aren't just opening another food place I think they are doing a great job at bringing the community together and I look forward to see what else they come up with in the future.

**Comment by RubanioBoi** [comment]
TBH the comment above said exactly what I was thinking plus more. The fact that other businesses are in support of this and want to collab with something that isn't even in the city yet shows that Lucky Plucker can and will bring some good RP to the city and something that hasn't been here for the 3 plus years I've been playing here and that's chicken.

**Comment by coalaura** [comment]
I agree with antihero that i don't think its worth opening a new restaurant *at the moment* with 2 new restaurants not even being used yet

**Comment by LuckyXIV** [comment]
I dont completely disagree, but whats the point of having the restaurants if they aren't being used? 
I mean hes mentioning the place not bringing rp into the city, but i see a restaurant that's already involved with over a hundred people and other businesses being much better RP for everyone involved than the current ones, especially the ones that exist without being used, right?

**Comment by rackyyuh** [comment]
Whilst there's a buncha resturants opening and it seems redundant right now - as far as I know, it'll also help during EU timezone; I'm not sure if there's any restaurants open during that time but I doubt it. While EU timezone might not be popping as much, I'm sure those guys would appreciate some good ass chicken. Good luck Lucky! Let's get it cuhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!!!

**Comment by RubanioBoi** [comment]
Different subdivisions might use different restaurants. Some might not have BurgerShot or Bean Machine so this would give them the option to open a chicken restaurant. Other than the MLO possibly causing lag there's no downside to offering players more to choose from.

**Comment by coalaura** [comment]
> Different subdivisions might use different restaurants. Some might not have BurgerShot or Bean Machine so this would give them the option to open a chicken restaurant. Other than the MLO possibly causing lag there's no downside to offering players more to choose from.

All subdivisions have the same restaurants, its up to them to use them

**Comment by LuckyXIV** [comment]
you can't use a restaurant that isn't open

**Comment by coalaura** [comment]
then just open it???

**Comment by antihero6713** [comment]
the pizza place will need a owner. it has none right now. that i know of

**Comment by LuckyXIV** [comment]
The thing with owning a pizza store is that there is already Pizza being sold at the arcade. If noone owns the Pizza Place then why did it get opened in the city, you know? I definetly understand what you are saying and it isn't like i disagree completely i just had a whole other vision. My characters name is Lucky already and I've been saying for years i should open that place one day and again theres over 100 people already that were really really excited over the Lucky Plucker opening and said that they really wanted some chicken since it was never in the city before. Most people dont even know that there IS a pizza place at all and i've already worked hard to promote the business and set up roleplay for myself and alot of other groups of people that i have never talked to before this aswell. What i wanted is to present the city with something new, because people seem to be tired of the same food and places to go to and chicken at the lucky plucker seemed to be the best way to do so.

**Comment by LuckyXIV** [comment]
If it was just me alone and i had never talked to anyone about this before then i wouldn't even have suggested this, but i know that it is something that a huge amount of people would love to have in the city and that's why I do wanna put the work into it.

**Comment by northbayjoe** [comment]
> The thing with owning a pizza store is that there is already Pizza being sold at the arcade. 

I belive that might change but don't quote me on that.

**Comment by MetaHatter** [comment]
Pizza place has been in the works for months as a 100% custom interior for OPFW.  It was just hooked up for in city use today but it has been a LONG journey to get here.

We try to add what we can but there are a lot of factors to weigh in besides "is there RP in one division around it".  We develop for a dozen servers that all use the restaurants.

Interest in a chicken place did not exist until VERY recently and it is on the map teams radar now.  Does that mean that it will get added? No.  Does that mean it won't sometime in the future? No.

Sadly for the chicken place, the Pizza place and Kissaki were first in line and they got done first.  IF/when there is the ability/need to open an additional restaurant, I can say, at least from my perspective, a chicken shop will be first in line to be next.

But that will likely be quite some time away as we literally added two restaurants this month.

**Comment by HollaYalla** [comment]
Arcade no longer Sells Pizza that is all done through Pizza This now and for the fact of Lucky Plucker within this past week or two we have gotten 2 new Restaurants and atleast on the International server neither of them have Owners yet so I would say just give it a bit then come back to the topic of this because we dont want to push so many new Restaurants onto the servers at once because a lot of RP stuff needs to happen like state setups and shit like that it also allows us to narrow down any crashes to a certain job/interior instead of it just is a bit much at this time

**Comment by northbayjoe** [comment]
Yah what meta just said is exaclty the case, that and even if it's considered, that locaiton will proably not work regardless given the proximity to mosleys and the clothing store which already suffers from performance issues in that location. We have to think of server performance is the number 1 prioirty when making these decisions and outside of everything else mentioned here which dont get wrong all are good points and alot of effort went into the ask, but for me that's why I was like "yah that wont work"

**Comment by LuckyXIV** [comment]
there still is one in little seoul

**Comment by HollaYalla** [comment]
Like Meta said maybe in the future we can look into the South side or the Little Seoul locations for a Lucky Plucker

**Comment by LuckyXIV** [comment]
I would have to think it over but what if i wanted to own the pizzaria then..?

**Comment by HollaYalla** [comment]
That would be up to how the server you play on would like to RP that out

**Comment by LuckyXIV** [comment]
There is one nice restaurant that isnt in use anymore right now aswell... how about the import of some chicken as food though? Or is that also part of the no

**Comment by HollaYalla** [comment]
If you would like to suggest a new food Item that should be sent through the Scripting Tracker as this is the Asset Tracker

https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by LuckyXIV** [comment]
But would it even be worth opening a new thing there, or would i just get another no lol

**Comment by LuckyXIV** [comment]
Because the Salieris bar would be a nice spot to sell some food at aswell, the location is much better lag wise aswell

**Comment by MetaHatter** [comment]
I would just  keep in mind that there are a dozen other servers that will be sharing that menu... so the menu suggestion should fit the type of food they would sell.  

i.e. for Saleri's maybe suggest an Italian Chicken Marinade or Chicken Milanese rather than a fried chicken sandwich.

**Comment by LuckyXIV** [comment]
Ofcourse, even get some pizza in aswell since it is an italian place.

**Comment by MetaHatter** [comment]
Pizza might be tougher since it has a dedicated restaurant now but nothing wrong with suggesting it...  Either way, need to be in the other tracker.

**Comment by LuckyXIV** [comment]
Lets say i do get the Salieris Bar.. would it be possible to just change the NAME and the sign upfront to Lucky Plucker? 🤔

**Comment by HollaYalla** [comment]
Changing an asset on one server will change it on ALL servers that use the Framework so no that wont be possible unless u do it in RP

**Comment by DaxterPancake** [comment]
I think you're missing the point where that when we change anything in the server it also changes it for 10+ other servers that are using the OP-FW framework. At this moment please use what custom maps are already available to you and if you wish to request custom food then it's for the script tracker not here.

Developers don't just say no because they want to, they say no because we know everything on the back end that goes into doing something like this and we have to constantly duct tape and balance things within this 11+ year old game to ensure it's running as smoothly as we can manage.

**Comment by MetaHatter** [comment]
> Changing an asset on one server will change it on ALL servers that use the Framework so no that wont be possible unless u do it in RP

Won't be possible even IN RP... there are other servers that use Saleri's

**Comment by LuckyXIV** [comment]
Ahh okay now that makes alot of sense.

**Comment by DaxterPancake** [comment]
Closing this issue now. Please refer to the script tracker for custom food requests.
