### ISSUE TITLE
[peds/?] Suggestion - Hayes Female Shirts

### ISSUE THREAD

**Issue by SooDurty** [InZidiuZ/legacy-assets-issue-tracker#892]
### Name

Dusty Ford (SooDurtyTTV)

### Summary

We are looking to get a couple new shirts for the ladies at Hayes. Attached are a couple examples/ideas.
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/a30ec2f1-dea1-4d0c-9275-c1495361d570)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/b721d1c6-2df2-4835-865e-2468c197bbd5)

### Reason

A bunch of the female mechanics have reached out to management regarding new shirts. The one shirt they currently have is a cropped undershirt that has a knot tied in the front. Attached are some of the feedback I've gotten from the ladies on the Hayes team.
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/815f2ed1-f707-4d54-921f-eea38dc2c486)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/8120c171-622d-485f-979e-4939349441ba)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/ed45790e-e9d4-472a-b93d-2e9791a4b1b3)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/9e22879e-e4a5-43f4-b6e1-a9e97edf836c)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/431bb341-f43a-49c4-99d4-895da50f3923)

**Comment by kayuenn** [comment]
I totally agree with this. Very grateful for the clothing options we do have, but I can definitely see that it's very black or white with a crop top and then a jacket or hoodie. A good diversity to the current clothing line would open up the opportunity for current and future employees to be able to work at the best mechanic shop in town while also looking their best. Different personalities, different styles, and not to mention different seasons like entering peak summer right now. This would be an amazing addition!

**Comment by Alyshiva** [comment]
Absolutely agree, we need some new styles especially coming into summer since the crop top is both scuffed and too feminine for some employees, and the only other options are long sleeved sweaters/coats. It would also be nice to have another kind of sweater for those looking for some variety in the colder months.

**Comment by DaxterPancake** [comment]
Can I please get someone to pick some clothing you'd actually want a texture for Hayes on? It's easier for me to know what you would want. I see that you have two photos provided but it's easier for me if you actually pick specific things instead of just in general 'winter clothing or less feminine' because there are thousands of files in the game. Thanks guys!

**Comment by SooDurty** [comment]
@DaxterPancake I will talk with the team and get you specifics. Thank you so much for you fast response! I should have been better prepared!

**Comment by DaxterPancake** [comment]
> @DaxterPancake I will talk with the team and get you specifics. Thank you so much for you fast response! I should have been better prepared!

No problem at all! Feel free to reach out in my DMs if you need to chat easier.

**Comment by SooDurty** [comment]
The the first two photos from the original post would be great to have the Hayes Logo on. Would love if we could have a black version and a white version.

Next, we would love to have a black and white version of the following shirts with the Hayes logo.
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/a5c24929-bbbc-40ad-9ced-deb4b9b6d7de)

![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/442238ff-fb0e-47a5-a165-77648c4241b2)

It was also requested that we get this mechanic jumpsuit. 
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/fb442265-ade1-4660-a7e6-79248f190f6e)
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/55ee658d-94df-4fcf-8b0a-c1536c7ae1d2)

Last but not least... They guys may have requested a tank top (black and white versions) :P
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/5489f6ea-efc8-4068-b011-b21cf130c987)

**Comment by SooDurty** [comment]
I forgot to request this void black shirt with a Hayes logo.
![image](https://github.com/InZidiuZ/legacy-assets-issue-tracker/assets/164375395/7e894346-c9a7-4d1a-b8b5-4f38258cb809)

I apologize if I'm asking for way too much! Also, feel free to DM me if needed. I respond much faster on Discord.

**Comment by DaxterPancake** [comment]
Sorry for the delay, I have done everything requested. Some I got creative with, some I just did nice and simple. Majority won't be live until I get a clothing build done so thank you for being patient, shouldn't be long now.

**Comment by SooDurty** [comment]
@DaxterPancake Sorry for my delayed response on thanking you!!! I just got back from LOA and see all of the amazingness you did for us! You are a rockstar!!! <3
