### ISSUE TITLE
Bug report - Locals don't trigger 66's in Sandy for Meth 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/legacy-assets-issue-tracker#895]
### Reporter

jr.bacon1

### Summary

I tested this and when you try to sell meth to the locals in sandy if they deny they have absolutely no reaction and they don't trigger 66's for PD. 

### Note

I fully tested this by going on duty in the test server and trying to sell meth

**Comment by coalaura** [comment]
This is a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) not an asset issue. Please post script issues here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by coalaura** [comment]
There is an explanation as to what the difference is in the readme of this repository and its also linked when you create an issue https://github.com/InZidiuZ/legacy-assets-issue-tracker?tab=readme-ov-file#whats-the-difference-between-script-and-asset-issues
