### ISSUE TITLE
Suggestion - Bigger TV outside apartments

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/legacy-assets-issue-tracker#896]
### Name

kieran.

### Summary

Digi Den should invest in selling bigger tvs as the small tv is fairly small and if a group of people are viewing it it can be harder to see

This could allow for things like movie nights, drive in theaters

we can watch the euros together 🤣

### Reason

.

**Comment by coalaura** [comment]
This is a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) not an asset issue. Please post script issues here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by coalaura** [comment]
There is an explanation as to what the difference is in the readme of this repository and its also linked when you create an issue https://github.com/InZidiuZ/legacy-assets-issue-tracker?tab=readme-ov-file#whats-the-difference-between-script-and-asset-issues
