### ISSUE TITLE
Suggestion - Ability to walk around with phone out when using mouse control

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/legacy-assets-issue-tracker#897]
### Name

kieran.

### Summary

Would be nice to be able to walk around with the phone out when using mouse control

### Reason

.

**Comment by coalaura** [comment]
This is a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) not an asset issue. Please post script issues here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by coalaura** [comment]
There is an explanation as to what the difference is in the readme of this repository and its also linked when you create an issue https://github.com/InZidiuZ/legacy-assets-issue-tracker?tab=readme-ov-file#whats-the-difference-between-script-and-asset-issues

**Comment by coalaura** [comment]
Also, how would that work tho, what if i want to type W or look around?

**Comment by kieran179** [comment]
Well you won't be typing W until you press in a box where you can actually type in no? So it wouldn't effect it. You wouldn't be able to move the third person camera around, but you can still look around with WASD
