### ISSUE TITLE
Suggestion - Midnight upgrades reciept

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/legacy-assets-issue-tracker#898]
### Name

kieran.

### Summary

Would be nice to go into midnight when someone isn't working and be able to PREVIEW all cosmetics and upgrades etc you can have done to you vehicle. Then at the end get a receipt you can give to a mechanic there and they can copy. This way if you are unhappy with a change they don't need to spend more money to change/fix it

This also does not mean you are always waiting for someone to be at midnight just to get a quote or idea on how much something would cost to get work done etc

### Reason

.

**Comment by Alyshiva** [comment]
Yessss, this! I also always feel really bad with how long I take of the midnight tuner’s time because I have trouble making decisions 😂😅

**Comment by CloudCait** [comment]
As the person who has owned Midnight for almost 2 years now on the international server, I can confidently say that this will have a negative impact on tuner rp. 

I can guarantee you, no tuner cares how long you take to pick what you want. That's their job. If they're being impatient, handle it the rp route.

If you wanna go in and have little to no interaction just go to an LS customs and get the rest of what you need at Midnight

**Comment by kieran179** [comment]
It's not about not wanting to have an interaction. Sometimes you have to wait literally hours for a midnight person just to get a quote on something you want doing to your vehicle. 

This suggestion is not trying to get people to avoid midnight workers as you are not actually getting work done, you are simply going there in your own time to view what you want to have done to your vehicle and then going there to get it done. 

I can see the point you are trying to make also. But this is not something that is going to put midnight out of business, its more of a unique feature.

**Comment by CloudCait** [comment]
I didn't say it would put midnight out of business, I said it would negatively impact the roleplay aspect of being a Midnight worker. It's essentially like adding a self service to burger shot. 

You can basically do all this minus wraps, bumpers and lights, by going to a bennies/ls customs and writing down what you want.

**Comment by coalaura** [comment]
This is a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) not an asset issue. Please post script issues here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by coalaura** [comment]
There is an explanation as to what the difference is in the readme of this repository and its also linked when you create an issue https://github.com/InZidiuZ/legacy-assets-issue-tracker?tab=readme-ov-file#whats-the-difference-between-script-and-asset-issues

**Comment by coalaura** [comment]
As said by others tho, this wont be done
