### ISSUE TITLE
Suggestion - Weed Planting 

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/legacy-assets-issue-tracker#899]
### Name

kieran.

### Summary

Once harvesting weed from where it is grown in an apartment you should be able to get the bucket back for reuse.

I am not sure if it is set like this for a reason. But if not, it does make sense to get the bucket back once harvested it is 

### Reason

.

**Comment by coalaura** [comment]
This is a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) not an asset issue. Please post script issues here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

**Comment by coalaura** [comment]
There is an explanation as to what the difference is in the readme of this repository and its also linked when you create an issue https://github.com/InZidiuZ/legacy-assets-issue-tracker?tab=readme-ov-file#whats-the-difference-between-script-and-asset-issues
