### ISSUE TITLE
Nissan Titan

### ISSUE THREAD

**Issue by meeksbtw** [InZidiuZ/legacy-assets-issue-tracker#9]
**Name:**
Meeks#5150

**Summary:**
Short summary is maybe increasing the max speed of the Nissan Titan, bought it stock and it went about 120-130, fully upgraded it and it still caps out at about 130, feels like I wasted $15k upgrading it for only a 5 mph difference.

**Reason:**
It would make it a better car :)

**Comment by Cricketx818** [comment]
Mr Meeks you should contact Karpenko for this

**Comment by RGDaviid** [comment]
Hello @meeksbtw 

Alright i've updated the Handling lines for the Nissan Titan. The upgrades now have a bigger impact on the vehicles top speed. Thank You for reporting this issue and have a nice day.  :)

_Karpenko_

_**OP-FW Car Developer**_
