### ISSUE TITLE
Weed progress at house not working

### ISSUE THREAD

**Issue by naaazz** [InZidiuZ/legacy-assets-issue-tracker#90]
**Reporter:**
Naaazz#0545

**Summary:**

 I started yesterday with planting weed. it is now about 15+ hours since I have put my first plant. and it is still 0% and most plants do not have the percentage symbol ... in the meantime I have placed 40 plants. is this a bug or do we have to wait any longer? if I lose my plants refund possible?

## Additional Information

**Screenshots:**

https://www.youtube.com/watch?v=jsOAvbntP7I

**Notes:**
<3

**Comment by InZidiuZ** [comment]
Wrong issue tracker. This is for assets strictly.
