### ISSUE TITLE
Suggestion - State issued License for Part-Time Lawyer

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/legacy-assets-issue-tracker#901]
### Name

rakibulhasan456

### Summary

It will work similarly to the **Press Pass**. The license name will be **Lawyer**. The heading in the ID card will also be **Lawyer** and be available at the Courthouse.

### Reason

In our subdivision, we have many people who have other full-time job and do the lawyer as a part-time service. I am sure other subdivision also have people like this.

The problem is, they don't have any access to the DOJ office or can't withdraw any Lawyer ID card. They can't show any identification card when required.

So a State issued ID card only for those lawyer will do a great job for the people involved as a part-time lawyer.

**Comment by Faisalhasan7** [comment]
Thanks man for this suggestion. 
It will be a good feature. this ID Card will allow to do lawyer stuff to those who are willing to RP as lawyer but don't wanna leave a business or job. Especially the sub-divisions with lower player count.

**Comment by coalaura** [comment]
This is a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) not an asset issue. Please post script issues here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues

There is an explanation as to what the difference is in the readme of this repository and its also linked when you create an issue https://github.com/InZidiuZ/legacy-assets-issue-tracker?tab=readme-ov-file#whats-the-difference-between-script-and-asset-issues
