### ISSUE TITLE
[maps/?] Suggestion - DOJ office additions

### ISSUE THREAD

**Issue by 07ashishdas** [InZidiuZ/legacy-assets-issue-tracker#902]
### Name

_.aarav (<@535528646572638209>

### Summary

Please Add

ATM Machine
Food Vending Machine
   &
Drinking Water Machine

In DOJ office 

Most Important I think

### Reason

Players often face situations where they don't have cash or a watch on them, leading to frequent trips to the bank or ATM for withdrawals. This can be inconvenient, especially during critical moments. Additionally, when players are hungry and no food shops are open, they must interrupt important meetings to get food and water. This disrupts the game flow and doesn't make sense in urgent scenarios.

**Comment by Alyshiva** [comment]
Devils advocate, maybe just be prepared with food and water like everyone else in the city is?

**Comment by 07ashishdas** [comment]
i just say this machine are important in DOJ office.

**Comment by 07ashishdas** [comment]
https://discord.com/channels/618449264271687682/1258689134814564403/1258798448438939711
http://img.itsaarav.com/u/agq9Ba.jpg
http://img.itsaarav.com/u/TP6kpA.jpg
http://img.itsaarav.com/u/nAvGhN.jpg

**Comment by MetaHatter** [comment]
Should no longer be necessary after next update.  Reopen if it's not the case.
