### ISSUE TITLE
Suggestion - Ability to craft fake plates

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/legacy-assets-issue-tracker#907]
### Name

kieran.

### Summary

There should be a way to craft fake plates, this would be a good selling product for smaller gangs to sell to people, or criminals in general. 

Could make it a long process to make so they aren't incredibly easy to make

### Reason

Just something new to craft, and a new item to sell illegally to players

**Comment by ImArteria** [comment]
This is the incorrect github. Please make this post on the script github here
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose
