### ISSUE TITLE
Suggestion - Wax for cars

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/legacy-assets-issue-tracker#908]
### Name

kieran.

### Summary

Wax should be something you can buy from mechanics or something that you can use on your car. Using wax will keep the vehicle clean and immune from dirt longer so it stays looking nice

### Reason

.

**Comment by ImArteria** [comment]
This would be something for the script github linked here
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose
