### ISSUE TITLE
[maps/?] Suggestion - Yellow Jack Bar TV Menu (Making it Permanent)

### ISSUE THREAD

**Issue by MissPianist43** [InZidiuZ/legacy-assets-issue-tracker#909]
### Name

Miss Pianist#5640

### Summary

I know Yellow Jack is a landmine for no construction. BUT is there any possible way, we can put a tv in one of these four places to get a menu available? We currently have to put our big tv over the shelves already, but it causes hassle when it takes 20 minutes to place it correctly, and look nice, to be able to provide our new good looking menu.  Most bars and restuarants in our city has a TV menu permanantly placed. Our menu/tv is placed beside of the fridge (locker), and anywhere there would be ideal, but over the windows will work too. I was thinking the TV can be placed in front of the shelves or the previous menu to avoid doing any construction to the establishment. Please see provided photos.

Please contact me if you have any questions, or if I can be of more assistance. We always appreciate everything you do!

Stella Jones, YJ Manager

### Link

![TV ideas 2 (1)](https://github.com/user-attachments/assets/a494606b-709e-4abb-9bf6-1d2b897c8cf3)
![TV ideas 2](https://github.com/user-attachments/assets/04d53f5f-dfa5-4c7a-9221-64f9816621d5)

### Reason

We currently have to put our big tv over the shelves already, but it causes hassle when it takes 20 minutes to place it correctly, and look nice, to be able to provide our new good looking menu.  Most bars and restuarants in our city has a TV menu permanantly placed.

**Comment by MissPianist43** [comment]
![YJ Bar Menu (5)](https://github.com/user-attachments/assets/44bf5352-6c68-440c-95be-bc4e7621e21d)

**Comment by MetaHatter** [comment]
Added a TV appropriate to the aesthetic.

![image](https://github.com/user-attachments/assets/e3ac9663-838e-4fc1-ab4f-ed6690210103)
