### ISSUE TITLE
Suggestion for PD changes on Handling.

### ISSUE THREAD

**Issue by TRParagon** [InZidiuZ/legacy-assets-issue-tracker#91]
**Name:**
Paragon#9700

**Summary:**
Most of PD would like to see some changes be done to the 2016 Explorer because it breaks slower than a tank and turns like a bus, the 2014 and 2016 Chargers lost complete grip and traction above 100mph for any turn they make so a re-balance on those vehicles could help the PD be more consistent rather than needing to fight the vehicle itself to continue a pursuit.

**Link:**
No Links.

**Reason:**
It would help the PD be more consistent overall and have vehicles that handle in a more similar way to imports or Vanilla vehicles.

**Comment by Karpenkooo** [comment]
I am not going to buff the PD cars any more. Most PD cars are faster and handle better than Civ cars...
