### ISSUE TITLE
[vehicles/?] - Water Cannons not visible to driver

### ISSUE THREAD

**Issue by Astrozombiecat** [InZidiuZ/legacy-assets-issue-tracker#910]
### Reporter

Astrozombiecat

### Summary

While seated inside a Fire truck equipped with a fire hose, the driver can activate the hose but can not see or hear the water. Everyone outside of the vehicle can see and hear the water just fine.  This issue is fairly new as it started about a day ago and we became fully aware when 20 cars were on fire in the city and they could not put out the fire. started about a day 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/inNEEDt1hrS_k-u1R/d1337eMouVZ1?invite=cr-MSwzaWMsMjUzMDkwNTE3LA

### Note

In the above clip I'm in my fire truck and attempting to put out the fire on the car in our burn pit.  The hose in my eye is not spraying anything however to Aluric he was seeing water spraying.  I had him pull out his truck to spray to show that I see it from his truck (seen from another perspective)

**Comment by Astrozombiecat** [comment]
I did some testing with Northbayjoe and Meta in the test server. We found that the water canon is affected by something dealing with weapons.  If we take a firetruck into Bennys, do not do anything and then leave the water cannon works then, but only until the vehicle is put away.

**Comment by coalaura** [comment]
This should be fixed now

**Comment by Astrozombiecat** [comment]
Laura thanks for looking into and fixing this issue. You are awesome!
