### ISSUE TITLE
Requesting new food added to the Videogeddon Arcade Bar menu

### ISSUE THREAD

**Issue by JennyLynn001** [InZidiuZ/legacy-assets-issue-tracker#911]
### Name

Jenny, jen999

### Summary

In summary, updating the menu with new food items at Videogeddon is a strategic move that can significantly benefit the arcade by improving customer satisfaction, attracting more customers, boost revenue, enhance image, and create cross-promotion opportunities.

### Reason

Adding new food to the menu at Videogeddon would be essential for improving and enhancing the overall customer experience and would promote business growth. 

The current food offerings at Videogeddon right now are slim and no one purchases them. At the current moment we have hot dogs, nachos and wonder waffles, all of which you can purchase at many different locations leaving the Arcade bar very unappealing to others. Introducing new food items would refresh the menu, attract a wider audience, and encourage repeat visits by providing more variety and options that are unique from other places. 

**The benefits of adding new food to the Videogeddon menu would be:**

**Increased Customer Satisfaction:** New and exciting menu options can improve customers' experience, making their visit to the arcade more enjoyable rather than going there to only purchase VR pills.

**Boost in Revenue:** New menu items can lead to increased sales as customers try out the latest additions. 

**Cross-Promotion Opportunities:** New food items can be paired with gaming promotions, creating bundled deals that enhance value for customers. For example, offering a discounted meal with the purchase of a VR pill can drive both food and gaming sales.

**Some of the food we had in mind:**

- Deep Fried Pickles
- Chicken Wings
- Garlic Butter Pretzel Sticks
- Churros
- Buffalo Chicken Sliders
- Popcorn
- Poutine
- Fajitas
- Quesadillas
- Mozzarella Sticks

**Comment by coalaura** [comment]
So, this would be a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) not an asset issue. However, the arcade's thing is mainly the zombie and arena pills, its not meant to be a restaurant, more a bar with some special items making it unique. Arcade already has a lot more food than any other bar in the city.
