### ISSUE TITLE
Bug report - Vehical Emi

### ISSUE THREAD

**Issue by mi10b** [InZidiuZ/legacy-assets-issue-tracker#912]
### Reporter

Miten (mi103842)

### Summary

im not able to pay car emi. it shows loading screen after click on pay. then noting happning

### Screenshots/Videos

![Screenshot 2024-08-06 215740](https://github.com/user-attachments/assets/403d794c-ed6a-47e8-9518-2beead7c3d3f)

**Comment by coalaura** [comment]
This would be a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
