### ISSUE TITLE
Suggestion - Upgrade Marlowe Vineyard

### ISSUE THREAD

**Issue by killa3130** [InZidiuZ/legacy-assets-issue-tracker#913]
### Name

Michael Little'nee (killa3130)

### Summary

Crafting table
Adding a crafting table/station would be great for my employees to be able to craft drinks such as alcohol and sodas to sell mix drinks. Also who doesn't enjoy a nice snack or bite while they drink? Maybe if we could add a way to craft food or small snacks at the vineyard as well.

Locker relocation
i have 1 usable locker at the vineyard and its in my Laundry room. I would like to see it moved to the cellar room as it would make more sense to go down to my cellar room to access "stored wine". Also it would make it less suspicious on my end to not have to go through my hidden door each time to access my wine.

Exit signs/Fire Extinguishers
Small green exit sign above the door that leads back to the stairs on the second floor. (Once you go up the stairs the first door leads you to a room with 3 other doors that lead to the other rooms. If we could place a exit sign above the door that would lead you back out to the stairs.) Fire extinguisher on each floor.

Garage Location
There's a small building in front of the vineyard that could be used as a garage. May i suggest using this building as a new public garage point. I think it would be ideal to use this as a public garage so people can store their vehicles to create less lag for people when we throw events at the vineyard. If that cannot be done how about a private garage so my employees can at least store their vehicles at the vineyard.

Grape Press/Exclusive items
Adding a press to the vineyard would be an ideal for a way to craft wine or drinks at the vineyard. Would also like to suggest a new wine or a grape soda exclusive to the vineyard. Perhaps a charcuterie board!! I think the idea of exclusive items are fun and bring in a new flow of traffic to a location. 

Map Icon
Could I have an icon enabled on the map so people can better find my business? I was thinking maybe a basic white M for Marlowe Vineyard. This would really help bring in more people to explore the vineyard and help other find the location easily when we throw events here.

### Link

![Screenshot (363)](https://github.com/user-attachments/assets/2e13c393-5dd6-4979-a8df-087f89add682)

Crafting Table Location.

![Screenshot (362)](https://github.com/user-attachments/assets/b58a0fff-ca99-4cec-a284-dc7102742d75)

Locker Relocation to Cellar room.

![Screenshot (365)](https://github.com/user-attachments/assets/5406cfdc-2d9f-44d8-b27a-3b733a4ce3e1)

Exit Sign location.

![Screenshot (367)](https://github.com/user-attachments/assets/ff8942a6-e316-4348-9c2e-4822fd37fbe4)

Garage building.

### Reason

I believe my suggestions would create a fun and enjoyable way to RP with the vineyard and would involve the rest of the community. By making the vineyard more functional in the way of being able to craft items would help my employees be able to craft and sell items there. That would help me give people jobs at the vineyard so they could craft and sell like any other bar or club. This would be such a big deal, not only for me but for the community too. I could hire people and give them a chance to make money and RP! It would also give the community a new spot to engage in! If this is possible, I believe an exclusive item to the vineyard would really add a nice touch to the new things being added to the city!

**Comment by coalaura** [comment]
This would be a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) and has also been suggested already here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2088
