### ISSUE TITLE
Suggestion - Locking Plate Auto Run plate

### ISSUE THREAD

**Issue by rustyjohn1** [InZidiuZ/legacy-assets-issue-tracker#915]
### Name

rustyjohn1

### Summary

For PD we have a plate reader that we are able to lock plates and set BOLO's etc, Would it be possible to have the plate autorun and return details when we press the keybind that locks the plate. currently, we type *CP* followed by the plate and it returns it back. For me I press numpad key 9 and it locks the front plate would be great to have this run the plate automatically.  

### Link

so when locked on the plate reader would pop this back https://i.imgur.com/MC1n9c9.png

### Reason

not to make the job easier for PD, but this would be an excellent quality-of-life change as I'm sure in the reel world plates can be run by just scanning the plate but I could be wrong.

**Comment by coalaura** [comment]
This would be a [script issue](https://github.com/InZidiuZ/op-framework-issue-tracker/issues)
