### ISSUE TITLE
[maps/?] Suggestion - Yellow Jack QOL Additions

### ISSUE THREAD

**Issue by Dibbey** [InZidiuZ/legacy-assets-issue-tracker#916]
### Name

Dibbey

### Summary

I was looking through previous Yellow Jack Suggestions and wanted to forward some suggestions that had been posted by MADxxVIKING in this github: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/3460#issue-2403347894

This is specific to:
1. A Blender - instead of trying to fiddle with placing down a Blender that doesn't obstruct pathing for people or other objects.

2. A Water Cooler - Well... for Water really haha

They would be nice QOL additions to the business.

### Link

Blender Position Suggestion:
- https://files.catbox.moe/lpxyxn.png

Water Cooler Position Suggestions:
- https://files.catbox.moe/dd846y.png
- https://files.catbox.moe/w01ju9.png

### Reason

Same as what MADxxVIKING said:

The **Blender** would allow Bartenders to be able to make Drinks from the Bar Menu and use fruits from fruit stands. We already try to kind of place a blender each time we want to use it inside the business, however it is very tight behind the counter and placement can be weird each time. 

The **Water Cooler** would just be a nice addition for the business as we have no other source of water at the location for water bottles or so.

I believe they are good suggestions as they are nice QOL for employees mixing alcoholic or non-alcoholic beverages and for visitors being able to have a source of water that we are unable to sell.

**Comment by Dibbey** [comment]
Additionally, if possible (and I hope this is the correct github, if not I will post it on the script one), it would be really nice if the grill in the Yellow Jack Bar that is on the counter, next to the suggested position of the Blender, could become usable for cooking.

The most balanced slots to cook meat, eggs and pancake better would be really neat, as we are currently utilizing the 4-slot grills to slowly cook up everything. So anything would be really nice, such as replacing the counter grill with the 4-slot grill to be permanently usable by Yellowjack Employees and such, or a similar grill of the cheaper variaton.

**Comment by Dibbey** [comment]
If possible (and I will gladly make this a new GitHub if needed) could the Locals that are *inside* the Yellow jack, the ones that sit at the bar, be disabled from ever spawning? They sometimes kick over the chairs which blocks people from reaching the counter space or just run around crazy and all scared. I'm sure we'd be all very grateful, but no rush on it ♥

**Comment by MetaHatter** [comment]
I will remove the spawns at the bar.  Are the ones back by the pool table ok?  Trying to make things feel a tiny bit less empty but want to keep them "out of the way".

**Comment by Dibbey** [comment]
Personally, when having walked into there I only ever really notice the ones at the bar being bothersome. I'm not sure I can remember the ones at the pool table but I would assume any there would be fine as long as Employees can pass by to reach the clothing spot in the corner. But yea, it's mostly the ones at the bar that at some point freak out, run around inside the bar and if someone attacks them or gets attacked by them it just ends with a dead local in the bar haha

**Comment by MetaHatter** [comment]
I have removed the local spawns from the bar stools.  Up to a script dev to address the other parts of the request.

**Comment by MissPianist43** [comment]
![Screenshot 2024-08-30 192905](https://github.com/user-attachments/assets/97d171e4-5794-4762-ab3c-07260b3c03fc)
Hi! The water cooler does not allow anyone to refill their water bottle or get a cup of water. Thank you! :)

**Comment by MetaHatter** [comment]
Water cooler should be fixed next update.

**Comment by MetaHatter** [comment]
The blender should also be in on the next update.
