### ISSUE TITLE
Bug report - jackpot stuff venished worth 130000

### ISSUE THREAD

**Issue by krrish2929** [InZidiuZ/legacy-assets-issue-tracker#917]
### Reporter

Pandu Yadav (322)

### Summary

i was doing my daily task there is a task to bet 8000 worth of stuff i tell my friend to bet small amount than i bet my stuff and it didnt bet and not showing in my jackpot inventory now what to do? i dont have proof but i have worth of 130000 of stuff 

### Screenshots/Videos

![Screenshot 2024-08-25 120446](https://github.com/user-attachments/assets/743f2159-2dca-47e6-be1c-fbc8a37135dc)

![Screenshot 2024-08-25 120830](https://github.com/user-attachments/assets/919cb3a0-8dfe-4812-86d7-93d9018e8d10)
![Screenshot 2024-08-25 120909](https://github.com/user-attachments/assets/ee0b6cad-bd69-4e5d-9fd5-79ce0204e813)

### Note

i dont have that much proof but i have couples of Screenshots

**Comment by coalaura** [comment]
this was fixed already, its also a script issue not an asset issue

**Comment by krrish2929** [comment]
but what about my asset
