### ISSUE TITLE
Suggestion - FIB Multicam Vest

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/legacy-assets-issue-tracker#918]
### Name

enutpeanut

### Summary

Add/update a texture from vests 49 or 51 to match multicam FIB outfit.

### Link

![image](https://github.com/user-attachments/assets/68f823b0-2bca-49f2-8356-bbab331b5636)

### Reason

We recently lost our beloved vest (because it was 9MB lmao), and FIB now no longer has a vest that matches the multicam outfit.
Vests 49, 50, and 51 all have a texture option which is the same camouflage, however they all say SWAT on them.
It would be fantastic if we could get a vest with this outfit again, you did an amazing job on the Highway vest and we'd appreciate it for FIB.

**Comment by DaxterPancake** [comment]
Absolutely, I gotchu. I will get this done tonight and update this when it's done.

**Comment by enutpeanut** [comment]
> Absolutely, I gotchu. I will get this done tonight and update this when it's done.

Wow, thank you so much!! 😇

**Comment by DaxterPancake** [comment]
This has been done, I made a camo version for all 3 of the more raid/tactical vests (unfortunely women don't have those models therefore I have not made any for them). Not sure on exact time it will be in the server though as a build will need to be done.
