### ISSUE TITLE
Suggestion - New doors 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/legacy-assets-issue-tracker#919]
### Name

gadjinee

### Summary

hello team, i was looking to see if its possible to make a small change at very special room at Fudge lane.
![image](https://github.com/user-attachments/assets/c33f7085-d5d7-4b27-becb-00300a5934d2)

The current door wont really shut unless you are right at the end, witch makes the room a little bit unusable 
![image](https://github.com/user-attachments/assets/45d6d7e7-9114-4c96-9749-900abb65fe4b)

i was wondering if its possible to maybe replace the door with something like this 

![image](https://github.com/user-attachments/assets/bc48fb97-9722-47d7-8045-7d64403aedf1)

Those doors will only open with player bumping in to them and actually opening

### Reason

its a really cool room, i think having actual door that can be closed will be benefitial for some "torture" RP, at this moment since it wont close its not as utilised as it could be 

Please and thank you

**Comment by gadjinee** [comment]
![image](https://github.com/user-attachments/assets/d1303bbb-df6f-41fe-9d1b-185e48b1e2f1)


Added location

**Comment by gadjinee** [comment]
https://medal.tv/games/gta-v/clips/iCpODFsyG_a4xFwdl/d1337TDbCsSf?invite=cr-MSxRM3EsMTYzNDQ4MDQ2LA

added the video, as you can see it opens when you quite far away from the door as well as only closes if you all the way to the end. if someone is sitting on the central chair it will never close

**Comment by coalaura** [comment]
This was already declined in your discord post (https://discord.com/channels/618449264271687682/1279175089765486592)

**Comment by gadjinee** [comment]
my bad i didnt see it since it was closed
