### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by reklez** [InZidiuZ/legacy-assets-issue-tracker#92]
**Reporter:** reklez#8643
Who is reporting this? Please include discord name.

**Summary:**
i havent paid my rent in two weeks because i was gonna rebuy my house at a cheaper price and i still own it so i cant rebuy it is there any way i can get it taken off my character so i can rebuy it ??

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Wrong issue tracker. This is for assets strictly.
