### ISSUE TITLE
Suggestion - Quality of Life Improvements for Yellow Jack Bar

### ISSUE THREAD

**Issue by MissPianist43** [InZidiuZ/legacy-assets-issue-tracker#922]
### Name

Miss Pianist#5640

### Summary

We at Yellow Jack Bar are reaching out to explore potential modifications that could enhance our operations within the city. We are interested in integrating several features that would significantly improve both efficiency and the overall experience for our patrons. Below, we have outlined our key requests, each in its respective category, with accompanying details.

**Topic #1: Consolidation of Ingredients within the Bar**
Currently, we face challenges in sourcing ingredients for our menu due to the need to collect items from four different locations:

- Alamo Fruit Stand for buckets, cherries for drinks, and water
- Paleto Grocery for Pigeon Milk
- Paleto Market for BBQ Sauce, bread, salt, cucumbers, pancakes, eggs, and beans
- Paleto Hunting Store for charcoal
- Time Spent Hunting for meat or buying it from people

This process, on average, takes an hour and fifteen minutes (as timed) before we can open with a full menu. This extended preparation period delays our operations and often results in excess inventory, leading to food wastage and potential financial loss.

We propose that our bar stock these ingredients directly at a set bar price. This change would allow us to streamline our operations, enabling faster openings, reducing waste, and improving cost efficiency by preventing the over-purchasing of ingredients. Having our necessary supplies readily available in the bar will ensure a smoother and more reliable service for our customers. Even if some can get moved, anything to specifically lower the opening time, would be amazing! We strive to open Yellow Jack daily, but with the extensive time constraint, it is difficult to remain open if you do not have the ample time to prepare. 

**Topic #2: Installation of a Permanent Grill (Similar to Burger Shot)**
To further improve our service, we would like to request the addition of a permanent working grill at Yellow Jack, similar to the setup at Burger Shot. Currently, the lack of a stable cooking facility hampers our ability to efficiently prepare meals for our customers.

With the permanent grill, we would be able to cook directly at the bar, enhancing our ability to serve fresh food quickly. Combined with the implementation of Topic #1, this would lead to a more streamlined kitchen operation, reducing wait times and enhancing the overall customer experience at Yellow Jack. Even if it is an electric grill that removes the need for charcoal, or a permanent charcoal grill with more slots than 4 so it results in less coal usage and faster multi-food cooking time. 

**Topic #3: Addition of Chicken Wings to the Menu**
In alignment with the improvements discussed in Topics #1 and #2, we would like to introduce new items to our menu. We would like Bar food that would add a unique offering that could set Yellow Jack apart as a standout venue in the city. Subject, but not limited to, Chicken Wings (one or multiple flavors), BBQ Ribs, Stuffed Peppers, Kebabs/Skewers, Chips, Fries, etc. Maybe not all of those, but those are some options that would definitely fit the bar vibe. 

This addition would be feasible and practical only if the ingredients were consolidated as described in Topic #1, allowing us to maintain a consistent supply. We envision offering different flavors of wings or simply serving traditional options as a Yellow Jack special, creating a “wow” factor for our patrons.

### Reason

**Conclusion**
We believe these modifications would significantly improve the operational efficiency of Yellow Jack Bar, enhance the customer experience, and contribute to a more immersive gameplay environment within the city. We kindly request your expertise in evaluating the feasibility of these changes and look forward to discussing potential next steps.

Thank you for your time and consideration. We are excited about the possibility of collaborating with your team to bring these enhancements to life.

**Comment by MetaHatter** [comment]
These ideas are interesting but not an asset issue. Please repost in the framework issue tracker so the proper team can see it. 

https://github.com/InZidiuZ/op-framework-issue-tracker

**Comment by MissPianist43** [comment]
Done!

**Comment by Dibbey** [comment]
Re-opening the specific part about the permanent grill as instructed by Laura.

> Installation of a Permanent Grill

> This would be something for the [asset issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)

So basically 
> Topic https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/2: Installation of a Permanent Grill (Similar to Burger Shot)

**Comment by MetaHatter** [comment]
Done.

**Comment by Dibbey** [comment]
I just wanna say I appreciate all the work.
However, I don't seem to be able to locate the usable grill in the yellow jack. I attempted to find it on International (after restart) and on the current test server with the yellow jack manager job. 

Edit: I also had eggs on me just in case it needed ingredients to be usable.

**Comment by MetaHatter** [comment]
There was a restart but it did not include an assets update/merge.  It will get there, Just might take a couple restarts.

![image](https://github.com/user-attachments/assets/81bc448a-1d73-4f23-9038-5b14fa5ab2e1)
