### ISSUE TITLE
Coffee Maker PD Stations!

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/legacy-assets-issue-tracker#923]
### Name

Sluggs

### Summary

think we could get a coffee pot that we can make coffee with at MRPD (or all stations) something to entice the “break room”
We would still have to find or buy coffee beans
Water bottle + Coffee Beans = Coffee
Then you could add milk and or cream

### Reason

 it would reduce stress much effectively and break room would be actually useful rather than just waking up there and going straight to reception and increase player to player interaction by hanging around in the break room on break! could even add toaster and bagels, toast, ect

**Comment by coalaura** [comment]
This would be a script issue not an asset issue. However, i don't see the breakroom getting more used by adding random things to it. It already has a snack machine and i believe coffee machine too. This would be a lot of work for something that would most likely barely ever get used
