### ISSUE TITLE
[maps/rhjustice] Suggestion - City Hall Reception Desk

### ISSUE THREAD

**Issue by Dibbey** [InZidiuZ/legacy-assets-issue-tracker#924]
### Name

Dibbey

### Summary

Currently in the new City Hall you can climb over the counter/reception desk. And I wanted to ask if it's possible to put something on the counter so you can't climb over but still be able to interact with the person on the other side, such as billing them and giving items like pieces of paper or so.

It's not that big of a deal, but thought I'd still just point it out and see if there's a way to stop being able to climb over the counter.
But please don't just put an NPC there, that would make standing there and processing licenses really awkward.

### Link

![FiveM_b3095_GTAProcess Neneko_Muffin  Gameplay  2024-09-21 21-14-39](https://github.com/user-attachments/assets/eea2dfd7-e7e3-46ae-b500-4e0ab25e2de6)

### Reason

Being able to climb over the counter makes the doors next to it not really mean much or keep anyone out even if you locked them. And anyone can just climb to whoever is behind the counter, possibly also picking up stuff like paper or so if we leave it on the ground there.

**Comment by MetaHatter** [comment]
This will be fixed next update.
