### ISSUE TITLE
Suggestion - Add Speed detection camera at junctions and Add Mobile speed cam

### ISSUE THREAD

**Issue by ekhowan12** [InZidiuZ/legacy-assets-issue-tracker#926]
### Name

alcoholic9999

### Summary

Speed Detection Cameras at Junctions
Installing speed detection cameras at junctions will greatly assist highway patrol and local police in monitoring traffic and enforcing speed limits. These cameras will automatically detect any vehicle exceeding the speed limit and issue a fine without the need for officers to be present. The cameras will be linked to a system that uses police department (PD) number plate detection technology, ensuring that fines are issued accurately and efficiently. The police will also have access to the camera footage and system data to review violations, with fines being automatically deducted from the offenders.

Mobile Speed Cameras
In addition to fixed cameras, mobile speed cameras will give the police department more flexibility. Officers can place these cameras in any location as needed, allowing them to monitor areas where speeding is a concern temporarily. These mobile cameras will also use PD number plate detection to issue fines automatically, just like the fixed cameras. This system will help reduce speeding in various locations and improve road safety.

### Reason

Introducing speed detection and mobile cameras in Legacy will create more dynamic and immersive roleplay opportunities for both police and citizens. These systems will encourage people to obey speed limits because of the consequences, such as automatic fines or even the possibility of having their license revoked. This will make players think twice before speeding, leading to more realistic driving behavior and traffic enforcement roleplay.

Additionally, with the increased fines, there will be greater deterrence, ensuring that people take traffic laws seriously. The ability for police to use mobile cameras will also give them more control over traffic management, allowing them to address speeding in different areas as needed, enhancing both the realism and depth of police roleplay.

**Comment by ekhowan12** [comment]
![image](https://github.com/user-attachments/assets/651278e8-7d6f-400b-a4b9-6961b7366390)
![image](https://github.com/user-attachments/assets/41f15eee-d5d5-4641-8d2a-0b4d7df1941e)
These are some mobile cam idea from my place

**Comment by davidrupam** [comment]
Its a very good idea but i dont think automatic fine would be good rather than in dispatch there will be a over speeding call with full details of the vehicle and if possible a tracker like boosting vehicle when it is under the speed detection cameras

**Comment by V4P1Dx69** [comment]
Yes, just the dispatch calls with the vehicle details and location will be good!

**Comment by coalaura** [comment]
No, that would be way too OP. Cops have speed radars in their cars allowing them to set up and catch speeders. I don't want automatic speeder-catching
