### ISSUE TITLE
Possible buff/nerf for the Dodge Charger

### ISSUE THREAD

**Issue by TTVErraticAlcoholic** [InZidiuZ/legacy-assets-issue-tracker#93]
**Name:**
ErraticAlcoholic#7703

**Summary:**
Buff:
The Dodge Charger in the Heroic donator tier is a really underwhelming car. Stock I've reached about 140mph coming up to Sandy. After upgrading everything but the brakes it maxes out at about 151mph. 

Nerf:
The car handles like it's on rails. Pretty much no reason to brake when taking turns (probably because it's rather slow) and it feels like it has no weight to it. That's why upgrading the brakes probably isn't worth the money.

**Reason:**
I feel like a car such as the Charger should have a lot more weight to it and should be harder to control. But in return, it should go faster. The car should be changed because there's no incentive to buy and drive the car right now. I'm damn sure it's outclassed by most cars in its price range.
Hell, my legendary tier Jeep Wrangler easily smokes the Charger even without upgrades despite being 15k cheaper.

**Comment by Karpenkooo** [comment]
Hey,

The Dodge charger has now been buffed and should come into effect in the next server update! 

_**Karpenko - OP FW Assets Developer**_
