### ISSUE TITLE
[maps/?] Suggestion - Adding items the comedy club

### ISSUE THREAD

**Issue by bdiddyg53** [InZidiuZ/legacy-assets-issue-tracker#931]
### Name

ringo star (bdiddyg53#5618)

### Summary

i was hoping that sometime in the near future we would be able to get a few things added behind the bar at the comedy club. it would greatly benefit us to have a working storage behind the bar, as well as a couple blenders, and a working grill. not sure if we would be able to add those in the room behind the bar that isn't accessible at the moment. that just seems like the best place to add them all so its private and we can make food behind closed doors. also a working tv down by the bar that we could have our menu on. as well as working counters to place peoples orders when they are done. 

### Reason

the reasoning behind all this, things are despawning before were done with them (blenders, boomboxes,tv's,etc). its costing the folks that work there a lot of extra money to keep purchasing these things. if the stuff was behind the counter it would make it a lot easier for my employees to do there jobs and not have to keep leaving the bar unattended where people are taking stuff they arent paying for.

**Comment by bdiddyg53** [comment]
is this where im supposed to add stuff like this. I'm new at this. so I'm just looking for a little guidance

**Comment by MetaHatter** [comment]
![image](https://github.com/user-attachments/assets/b3db6e18-1a55-42e7-91f2-9556ab0377a0)

I have added a blender, TV and grill (hidden in the microwave to make it fit the building better).

Storage is a script decision.

**Comment by bdiddyg53** [comment]
o snap. thank you guys so much

**Comment by coalaura** [comment]
no storage
