### ISSUE TITLE
[peds/*] Suggestion - "Shadow Syndicate" Gang clothing

### ISSUE THREAD

**Issue by dhalishipo** [InZidiuZ/legacy-assets-issue-tracker#938]
### Name

dhalishipo#0001

### Summary

We are requesting the addition of custom clothing for the Shadow Syndicate gang in Legacy RP Bangladesh. Our gang consists of many active members, each with over 400 hours of roleplay experience. Additionally, we have over 20 unofficial new members actively learning roleplay. We’ve already designed our custom gang outfit and would like it to be implemented in the server.

**Our custom outfit includes:**

**Bandana:** Designed in the Shadow Syndicate's signature white and black colors with our gang logo.

**Hoodie:** Featuring the gang's name and logo in white and black for a bold and stylish look.

**T-Shirt:** Matching the gang’s color theme to complement the hoodie and bandana.

Currently, the server has 8 official gangs, and 7 of them already have their custom outfits. Unfortunately, Shadow Syndicate is the only gang without any custom gang clothing, which creates an inconsistency in roleplay immersion and identity. As a newer gang, having our own custom clothing would boost our members' confidence, encourage them to increase their roleplay activities, and attract newcomers to join our family, strengthening our presence in the server.

### Link

**Bandana** : https://drive.google.com/file/d/1vCo830HZ2Sc8J4_pEzmBY6dGFuINp2Nk/view?usp=sharing
**Hoodie** : https://drive.google.com/file/d/1g1aUTeflIfZP90jHQjIg8TGhj4ZCrs_j/view?usp=sharing
**T-Shirt** : https://drive.google.com/file/d/1EvpTNiU78CvnzleKlmhhQTtC-iZjROF-/view?usp=sharing

### Reason

Adding our custom outfit will enhance the immersive roleplay experience for both our gang members and other players on the server. It will help us stand out visually, establish our presence as one of the official gangs, and enable better engagement in RP scenarios. This addition will ensure all gangs are treated equally in terms of customization, fostering fair play and inclusivity.

Kindly consider our request and help us represent Shadow Syndicate properly in Legacy RP Bangladesh!

**Comment by coalaura** [comment]
you already opened an issue #937

**Comment by dhalishipo** [comment]
Bro, regarding the first issue (#937), Dexter Sir mentioned:
"Your clothing has a real-world brand all over it (LOUIS VUITTON), so I will not be adding it at this time. You are more than welcome to fix this and provide me with the updated files, and I will consider it. Also, the file sizes for the textures are way too big; please stick to 1MB or under per texture."

I fixed all the issues and resubmitted the new clothing files. Now the issue is closed—what should I do?

**Comment by coalaura** [comment]
you don't have to create a whole new issue, your original issue (the one i linked) is still open, you can comment on it
