### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by nilmartwitch** [InZidiuZ/legacy-assets-issue-tracker#94]
**Name:**
Who is suggesting this? Please include discord name. nilmar#3552

**Summary:**
Write a short summary of what your suggestion is about. opening the garage carpark on mirror park for ppl who cannot access garages for shared houses 

**Link:**
If there are any links to what you're suggesting, please add them here. https://gyazo.com/458d2b932c92ca81ae2909938bd83902

**Reason:**
Why would your suggestion be a good addition to Legacy? would help the ppl out who share houses in mirror park and cannot use the home garages

**Comment by samsn8** [comment]
+1, we share houses up there and theres like 20 of us with 10 houses so 10 people cant pull out a car there

**Comment by AdeptCL** [comment]
I don't live in Mirror Park, but can agree this would be a pretty cool idea.
Especially with houses now, parties are more likely to happen, so having somewhere to store a vehicle without the possibility of trolls just messing cars up.

**Comment by InZidiuZ** [comment]
Wrong issue tracker. This is for assets strictly.
