### ISSUE TITLE
Suggestion - PDM workers able to help pay off financed vehicles

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/legacy-assets-issue-tracker#95]
**Name:**
AdeptCL#0402

**Summary:**
PDM workers able to take finance payments directly to reduce cost for customer.

**Link:**
N/A.

**Reason:**
To bring more interactions and experiences for both PDM workers and customers, I think PDM workers should be able to help someone pay off their vehicle. I've seen from different places that a customer can use a PDM worker to pay their finances, and in return, they can get a little bit of a discount, and it also gives some commission to the PDM worker.

An example, $10,000 is due on a weekly payment for a vehicle. If a customer uses a PDM worker directly to help pay the vehicle, then 5-10% can be discounted as the PDM worker pays it for them.
In return, if the 5% discount is applied, $500 is discounted from the $10,000 payment, and the PDM worker can either 50/50 split that and give $250 back or keep the $500 or give it all back.

I think this is a good addition as it would create some further roleplay experience for the PDM workers and doesn't just give their job the idea of selling cars and that's it.

I'm not a PDM worker, but that was always something that dis-interested me, the fact you could sit there all day, sell 3-4 cars but have no further RP with the financing process, as people can pay directly from wherever in the city. This addition allows customer to get some incentive to do it, and allows PDM to create more RP scenarios.

**Comment by InZidiuZ** [comment]
a) Wrong issue tracker. b) Probably not.
