### ISSUE TITLE
Classic Jester

### ISSUE THREAD

**Issue by LuisSi** [InZidiuZ/legacy-assets-issue-tracker#96]
**Name:**
DaPizza #2928

**Summary:**
I bought a Classic Jester and without upgrades it goes aroun 150-160 mph aand then after i upgraded engine to max n put a turbo on it goes aroun 150-160mph aswell

**Link:**
/

**Reason:**
If it goes the same spee before and after upgrade its a waste of 11k

**Comment by Karpenkooo** [comment]
Hey, 
This issue should now be fixed! Your car upgrades should come into effect after the next server update!

_**Karpenko - OP FW Assets Developer**_
