### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/legacy-assets-issue-tracker#99]
**Reporter:**
Who is reporting this? Please include discord name.
Ciros#2048
**Summary:**
Write a summary of what you're experiencing.
EMS Explorer does not spawn instantly, takes about 40 seconds to spawn.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Notes:**
For anything else noteworthy.
Sometimes it wont spawn and we have to mass spawn them then start parking them or /impound

**Comment by InZidiuZ** [comment]
This would most likely be related to slow internet, as it needs to first be downloaded to your cache before it can be spawned.

**Comment by Cironite** [comment]
> This would most likely be related to slow internet, as it needs to first be downloaded to your cache before it can be spawned.

Makes sense, I have no idea why, but my FiveM starts in windowed mode like 800x800 resolution with no UI, So i must clear my cache every time i use FiveM.
